src-ken&y/objects/Accounting_Entry__c.object
<CustomObject>
    <customHelpPage>HelpAccountingEntries</customHelpPage>
    <description>Accounting Entry Header records</description>
    <fields>
        <fullName>Bank_Transaction_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bank Transaction Group</label>
        <referenceTo>Bank_Transaction_Group__c</referenceTo>
        <relationshipLabel>Accounting Entries</relationshipLabel>
        <relationshipName>Accounting_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Accounting Entries</relationshipLabel>
        <relationshipName>Accounting_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Receipt__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Customer receipt</description>
        <label>Customer Receipt</label>
        <referenceTo>Customer_Receipt__c</referenceTo>
        <relationshipLabel>Accounting Entries</relationshipLabel>
        <relationshipName>Accounting_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to the associated Customer</description>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Accounting Entries</relationshipLabel>
        <relationshipName>Accounting_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Accounting Entry</label>
    <nameField>
        <label>Accounting Entry</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Accounting_Rule__c.object
<CustomObject>
    <customHelpPage>HelpAccountingRules</customHelpPage>
    <description>The rules based engine that generates the accounting entries for all Financial Companies from Operating Companies</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Accounting Rules</relationshipLabel>
        <relationshipName>Accounting_Generator</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Accounting Rule</label>
    <nameField>
        <label>Accounting Rule</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Bank_Account__c.object
<CustomObject>
    <customHelpPage>HelpBankAccounts</customHelpPage>
    <description>Bank Account Information</description>
    <fields>
        <fullName>Balance_Offset__c</fullName>
        <description>Balance offset for Bank Reconciliation.</description>
        <label>Balance Offset</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company associated with this bank account</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Bank Accounts</relationshipLabel>
        <relationshipName>Bank_Accounts_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opening_Balance_Date__c</fullName>
        <description>Opening Balance date maintains the Date/Time when the opening balance is actually obtained. All the Source Documents(CR/SP/JEs) will not be considered for reconciliation which were transacted before this date.</description>
        <label>Opening Balance Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Opening_Balance__c</fullName>
        <description>Opening balance is used for the Bank Reconciliation.</description>
        <label>Opening Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Bank Account</label>
    <nameField>
        <label>Bank Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Bank_Transaction__c.object
<CustomObject>
    <customHelpPage>HelpManageBankTransactions</customHelpPage>
    <fields>
        <fullName>Bank_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bank Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND 3</booleanFilter>
            <errorMessage>Please populate correct bank account which is related to associated company.</errorMessage>
            <filterItems>
                <field>$Source.Company__c</field>
                <operation>equals</operation>
                <valueField>Bank_Account__c.Company__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.Company__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>Bank_Account__c.Company__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Bank_Account__c</referenceTo>
        <relationshipLabel>Bank Transactions</relationshipLabel>
        <relationshipName>Bank_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bank_Transaction_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Bank transaction group for bank transactions</description>
        <label>Bank Transaction Group</label>
        <referenceTo>Bank_Transaction_Group__c</referenceTo>
        <relationshipLabel>Bank Transactions</relationshipLabel>
        <relationshipName>Bank_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Bank Transactions</relationshipLabel>
        <relationshipName>Bank_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bank Transaction</label>
    <nameField>
        <label>Bank Transaction</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Bank_Transaction_Group__c.object
<CustomObject>
    <customHelpPage>HelpManageBankTransactions</customHelpPage>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Bank Transaction Groups</relationshipLabel>
        <relationshipName>Bank_Transaction_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bank Transaction Group</label>
    <nameField>
        <label>Bank Transaction Group</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Transaction Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Bank_Transaction_Match__c.object
<CustomObject>
    <customHelpPage>HelpManageBankTransactions</customHelpPage>
    <fields>
        <fullName>Bank_Transaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to bank transaction matched to CR/SP/BT/JE</description>
        <label>Bank Transaction</label>
        <referenceTo>Bank_Transaction__c</referenceTo>
        <relationshipLabel>Bank Transaction Matches</relationshipLabel>
        <relationshipName>Bank_Transaction_Match</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Bank Transaction Matches</relationshipLabel>
        <relationshipName>Bank_Transaction_Match</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Receipt__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to customer receipt match</description>
        <label>Customer Receipt</label>
        <referenceTo>Customer_Receipt__c</referenceTo>
        <relationshipLabel>Bank Transaction Matches</relationshipLabel>
        <relationshipName>Bank_Transaction_Match</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bank Transaction Match</label>
    <nameField>
        <label>Bank Transaction Match</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Transaction Match</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Customer__c.object
<CustomObject>
    <customHelpPage>HelpCustomers</customHelpPage>
    <description>Information that relates a Customer business to the manufacturing company (Company) and describes the business agreement between the two entities.</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The company that originates and owns the customer relationship</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Customers</relationshipLabel>
        <relationshipName>Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer</label>
    <nameField>
        <label>Customer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Customer_Receipt__c.object
<CustomObject>
    <customHelpPage>HelpReceipts</customHelpPage>
    <description>Records all customer receipts (checks, credit cards, EFT, etc) against invoice.</description>
    <fields>
        <fullName>Amount_Received__c</fullName>
        <description>Amount received</description>
        <label>Amount Received</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Bank_Account_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bank Account</label>
        <referenceTo>Bank_Account__c</referenceTo>
        <relationshipLabel>Customer Receipts</relationshipLabel>
        <relationshipName>Customer_Receipts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company associated with this Customer Receipt. It should be populated with the default value for the user logged in.</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Customer Receipts</relationshipLabel>
        <relationshipName>Customer_Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Customer</description>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>The user must enter either a corporate or a bill to customer</errorMessage>
            <filterItems>
                <field>Customer__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Corporate Parent</value>
            </filterItems>
            <filterItems>
                <field>Customer__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Bill To</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Customer Receipts</relationshipLabel>
        <relationshipName>Customer_Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Receipt</label>
    <nameField>
        <label>Customer Receipt</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Customer_Receipt_Line__c.object
<CustomObject>
    <customHelpPage>HelpReceipts</customHelpPage>
    <description>Payment details associated with a payment received or issued</description>
    <fields>
        <fullName>Customer_Receipt__c</fullName>
        <label>Customer Receipt</label>
        <referenceTo>Customer_Receipt__c</referenceTo>
        <relationshipLabel>Customer Receipt Lines</relationshipLabel>
        <relationshipName>Customer_Receipt_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill To Customer</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1</booleanFilter>
            <filterItems>
                <field>Customer__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Bill To</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Customer Receipt Lines</relationshipLabel>
        <relationshipName>Customer_Receipt_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Receipt Line</label>
    <nameField>
        <label>Payment Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Receipt Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/classes/BankTransactionGroupAccountingTest.cls
@istest
public class BankTransactionGroupAccountingTest {
    public class TestDataForBankTxns{
        public Testfuel fuel = new Testfuel();
        public Bank_Transaction_Group__c BankTxnGrp  = new Bank_Transaction_Group__c();            
        public List<Bank_Transaction__c> BankTxnList = new list<Bank_Transaction__c>();

        public TestDataForBankTxns(){
  
            system.assert(fuel.periodList.size()>0);

 
            Bank_account__c ba= fuel.bankAccount;
            ba.Opening_balance__C = 100;
            ba.Balance_offset__c=50;
            ba.opening_balance_date__c = system.now().adddays(-30);
            update ba;
            
            Customer_Receipt__c custReceipt = new Customer_Receipt__c();
            custReceipt.Company__c = fuel.company.Id;
            custReceipt.Customer__c = fuel.customerParent.Id;
            custReceipt.Amount_Received__c = 100;
            custReceipt.bank_Account_2__c = ba.Id;
            custReceipt.Payment_Method_G__c = 'Check';
            custReceipt.Reference_Number__c = '1234';
            custReceipt.Date_Received__c = system.now();
            custReceipt.Type__c = 'Receipt';
            custReceipt.Currency__c = TestFuel.currencyUSD.id;
            insert custReceipt; 
            
            Customer_Receipt_Line__c additionalPayment = new Customer_Receipt_Line__c();
            additionalPayment.Amount__c = 100;
            additionalPayment.Customer_Receipt__c = custReceipt.Id;
            additionalPayment.Type__c = PaymentService.TYPE_PREPAYMENT;
            insert additionalPayment;
            
            custReceipt.Finalized__c = true;
            update custReceipt;
        
            Bank_Transaction__c bt  = new Bank_Transaction__c (Company__c = fuel.company.id, Amount__c = 100, Transaction_Date__c = custReceipt.Date_Received__c , 
                                                           Bank_Account__c = ba.Id,subtransaction_type__c ='Credit');
            insert bt;
            BT = [Select id,name,bank_transaction_group__c from Bank_Transaction__c where id = :bt.id];
           BankTxnList.add(bt);
       
        Bank_Transaction_Match__c btm = new Bank_Transaction_Match__c(Bank_Transaction__c = bt.Id, Customer_Receipt__c = custReceipt.Id, Amount__c = 100);
        insert btm;
            
            //Create BT
            /*BankTxnList = fuel.bankTransactions;
            system.assertNotEquals(BankTxnList.size(),0,'Expecting Bank txns.');
            
            
            for(Bank_Transaction__c bt:BankTxnList){
                bt.Bank_Transaction_Group__c=BankTxnGrp.Id;
            }
            update BankTxnList;*/
                //Create BTG
                //Commenting this flow as BT insert automatically BTG.
           /* BankTxnGrp.name = 'BTG-01';
            BankTxnGrp.Transaction_Type__c = 'Standard';
            BankTxnGrp.Currency__c = TestFuel.currencyUSD.id;
            BankTxnGrp.Transaction_Date__c=system.now();
            BankTxnGrp.Company__c=fuel.company.id;
            insert BankTxnGrp;
            
            bt.Bank_Transaction_Group__c = BankTxnGrp.Id;
            update bt; 
            BankTxnList.add(bt);
          
            BankTxnGrp.Finalized__c=true;
            update BankTxnGrp;*/
            BankTxnGrp =[select id,name,finalized__c from Bank_Transaction_Group__c where id in  (select bank_transaction_group__c from Bank_Transaction__c where ID IN :BankTxnList) LIMIT 1];
            system.assertEquals(BankTxnGrp.finalized__c,true,'Expecting BTB to be succesfully finalized.');             
        }
       
    }
    public static testMethod void testBTGAccounting() {
         
        TestDataForBankTxns testData = new TestDataForBankTxns();
   
        Test.startTest();
        //Generate Accounting
        BankTransactionGroupAccounting btga = new BankTransactionGroupAccounting();
        btga.execute(testData.BankTxnList);
        List<Accounting_Entry__c> AEs = new list<Accounting_Entry__c>(); 
        AEs = [select id,name from Accounting_Entry__c 
               where Bank_Transaction_Group__c = :testData.BankTxnGrp.Id 
               and status__c='Active'
               and Has_Exceptions__c = true];
        system.assertNotEquals(AEs.size(),0,'Expecting excpetions as no rules are created.');
        
        //Create Rules in testfuel
        system.assert(testData.fuel.BankTxnGrpAcctRulesList.size()>0);
        //Generate Accounting 
        //Reset mrules map so that it is repopulated with new rules giving correct segmentrefernces.
        AccountingRuleService.mAccountingRules  =  new Map<string, List<Accounting_Rule__c>>();
        btga = new BankTransactionGroupAccounting();//Load segment references again.
        btga.execute(testData.BankTxnList);
        List<Accounting_Entry__c> newAEs = new list<Accounting_Entry__c>(); 
       /* list<task> exceptiontasks = [select id,description from task where whatid in :newAEs];
        system.assertEqual(exceptiontasks,null);*/
        newAEs = [select id,name from Accounting_Entry__c 
               where Bank_Transaction_Group__c = :testData.BankTxnGrp.Id 
               and status__c='Active'
               and Has_Exceptions__c = false];
        system.assertNotEquals(newAEs.size(),0,'Expecting no exceptions rules are created.');    
        Test.stoptest();
    }
    public static testMethod void testBTAccountingListView(){
        testDataForBankTxns testData = new testDataForBankTxns();
         system.assert(testData.fuel.BankTxnGrpAcctRulesList.size()>0);        
         Test.startTest();
            Apexpages.StandardSetController setcon = new Apexpages.StandardSetController(testdata.BankTxnList);        
            setcon.setSelected(testdata.BankTxnList);
           BankTransactionAccountingExt BAcctExt = new BankTransactionAccountingExt(setcon);
            BAcctExt.generateBankTransactionAccounting();
        Test.stoptest();
        List<Accounting_Entry__c> newAEs = new list<Accounting_Entry__c>(); 
        newAEs = [select id,name from Accounting_Entry__c 
                   where Bank_Transaction_Group__c = :testData.BankTxnGrp.Id 
                   and status__c='Active'
                   and Has_Exceptions__c = false];
        system.assertNotEquals(newAEs.size(),0,'Expecting no exceptions as rules are created.');    
    }
    public static testMethod void testBTGAccountingListView(){
        testDataForBankTxns testData = new testDataForBankTxns();
         system.assert(testData.fuel.BankTxnGrpAcctRulesList.size()>0);        
         Test.startTest();
            Apexpages.StandardSetController setcon = new Apexpages.StandardSetController(new list<Bank_Transaction_Group__c>{testdata.BankTxnGrp});        
            setcon.setSelected(new list<Bank_Transaction_Group__c>{testdata.BankTxnGrp});
            BankTransactionGroupAccountingExt BAcctExt = new BankTransactionGroupAccountingExt(setcon);
            BAcctExt.generateBankTransactionGroupAccounting();
        Test.stoptest();
        List<Accounting_Entry__c> newAEs = new list<Accounting_Entry__c>(); 
        newAEs = [select id,name from Accounting_Entry__c 
                   where Bank_Transaction_Group__c = :testData.BankTxnGrp.Id 
                   and status__c='Active'
                   and Has_Exceptions__c = false];
        system.assertNotEquals(newAEs.size(),0,'Expecting no exceptions as rules are created.');    
    }
    public static testMethod void testBTGAccountingBatch(){
        TestDataForBankTxns testData = new TestDataForBankTxns();
        system.assert(testData.fuel.BankTxnGrpAcctRulesList.size()>0);        
        Test.startTest();        
            BankTransactionGroupAccountingBatch BTGBatch = new BankTransactionGroupAccountingBatch(new set<id>{testData.fuel.company.id});
            Database.executeBatch(BTGBatch);
        Test.stoptest();
       
        List<Accounting_Entry__c> newAEs = new list<Accounting_Entry__c>(); 
        newAEs = [select id,name from Accounting_Entry__c 
                   where Bank_Transaction_Group__c = :testData.BankTxnGrp.Id 
                   and status__c='Active'
                   and Has_Exceptions__c = false];
        system.assertNotEquals(newAEs.size(),0,'Expecting no exceptions as  rules are created.');    
    }   
      
}