src-ken&y/objects/Accounting_Entry__c.object
<CustomObject>
    <customHelpPage>HelpAccountingEntries</customHelpPage>
    <description>Accounting Entry Header records</description>
    <fields>
        <fullName>Bank_Transaction_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bank Transaction Group</label>
        <referenceTo>Bank_Transaction_Group__c</referenceTo>
        <relationshipLabel>Accounting Entries</relationshipLabel>
        <relationshipName>Accounting_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Accounting Entries</relationshipLabel>
        <relationshipName>Accounting_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Receipt__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Customer receipt</description>
        <label>Customer Receipt</label>
        <referenceTo>Customer_Receipt__c</referenceTo>
        <relationshipLabel>Accounting Entries</relationshipLabel>
        <relationshipName>Accounting_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to the associated Customer</description>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Accounting Entries</relationshipLabel>
        <relationshipName>Accounting_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Accounting Entry</label>
    <nameField>
        <label>Accounting Entry</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Accounting_Rule__c.object
<CustomObject>
    <customHelpPage>HelpAccountingRules</customHelpPage>
    <description>The rules based engine that generates the accounting entries for all Financial Companies from Operating Companies</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Accounting Rules</relationshipLabel>
        <relationshipName>Accounting_Generator</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Accounting Rule</label>
    <nameField>
        <label>Accounting Rule</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Bank_Account__c.object
<CustomObject>
    <customHelpPage>HelpBankAccounts</customHelpPage>
    <description>Bank Account Information</description>
    <fields>
        <fullName>Balance_Offset__c</fullName>
        <description>Balance offset for Bank Reconciliation.</description>
        <label>Balance Offset</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company associated with this bank account</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Bank Accounts</relationshipLabel>
        <relationshipName>Bank_Accounts_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opening_Balance_Date__c</fullName>
        <description>Opening Balance date maintains the Date/Time when the opening balance is actually obtained. All the Source Documents(CR/SP/JEs) will not be considered for reconciliation which were transacted before this date.</description>
        <label>Opening Balance Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Opening_Balance__c</fullName>
        <description>Opening balance is used for the Bank Reconciliation.</description>
        <label>Opening Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Bank Account</label>
    <nameField>
        <label>Bank Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Bank_Transaction__c.object
<CustomObject>
    <customHelpPage>HelpManageBankTransactions</customHelpPage>
    <fields>
        <fullName>Bank_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bank Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND 3</booleanFilter>
            <errorMessage>Please populate correct bank account which is related to associated company.</errorMessage>
            <filterItems>
                <field>$Source.Company__c</field>
                <operation>equals</operation>
                <valueField>Bank_Account__c.Company__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.Company__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>Bank_Account__c.Company__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Bank_Account__c</referenceTo>
        <relationshipLabel>Bank Transactions</relationshipLabel>
        <relationshipName>Bank_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bank_Transaction_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Bank transaction group for bank transactions</description>
        <label>Bank Transaction Group</label>
        <referenceTo>Bank_Transaction_Group__c</referenceTo>
        <relationshipLabel>Bank Transactions</relationshipLabel>
        <relationshipName>Bank_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Bank Transactions</relationshipLabel>
        <relationshipName>Bank_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bank Transaction</label>
    <nameField>
        <label>Bank Transaction</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Bank_Transaction_Group__c.object
<CustomObject>
    <customHelpPage>HelpManageBankTransactions</customHelpPage>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Bank Transaction Groups</relationshipLabel>
        <relationshipName>Bank_Transaction_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bank Transaction Group</label>
    <nameField>
        <label>Bank Transaction Group</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Transaction Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Bank_Transaction_Match__c.object
<CustomObject>
    <customHelpPage>HelpManageBankTransactions</customHelpPage>
    <fields>
        <fullName>Bank_Transaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to bank transaction matched to CR/SP/BT/JE</description>
        <label>Bank Transaction</label>
        <referenceTo>Bank_Transaction__c</referenceTo>
        <relationshipLabel>Bank Transaction Matches</relationshipLabel>
        <relationshipName>Bank_Transaction_Match</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Bank Transaction Matches</relationshipLabel>
        <relationshipName>Bank_Transaction_Match</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Receipt__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to customer receipt match</description>
        <label>Customer Receipt</label>
        <referenceTo>Customer_Receipt__c</referenceTo>
        <relationshipLabel>Bank Transaction Matches</relationshipLabel>
        <relationshipName>Bank_Transaction_Match</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bank Transaction Match</label>
    <nameField>
        <label>Bank Transaction Match</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Transaction Match</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Customer__c.object
<CustomObject>
    <customHelpPage>HelpCustomers</customHelpPage>
    <description>Information that relates a Customer business to the manufacturing company (Company) and describes the business agreement between the two entities.</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The company that originates and owns the customer relationship</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Customers</relationshipLabel>
        <relationshipName>Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer</label>
    <nameField>
        <label>Customer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Customer_Receipt__c.object
<CustomObject>
    <customHelpPage>HelpReceipts</customHelpPage>
    <description>Records all customer receipts (checks, credit cards, EFT, etc) against invoice.</description>
    <fields>
        <fullName>Amount_Received__c</fullName>
        <description>Amount received</description>
        <label>Amount Received</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Bank_Account_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bank Account</label>
        <referenceTo>Bank_Account__c</referenceTo>
        <relationshipLabel>Customer Receipts</relationshipLabel>
        <relationshipName>Customer_Receipts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company associated with this Customer Receipt. It should be populated with the default value for the user logged in.</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Customer Receipts</relationshipLabel>
        <relationshipName>Customer_Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Customer</description>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>The user must enter either a corporate or a bill to customer</errorMessage>
            <filterItems>
                <field>Customer__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Corporate Parent</value>
            </filterItems>
            <filterItems>
                <field>Customer__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Bill To</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Customer Receipts</relationshipLabel>
        <relationshipName>Customer_Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Receipt</label>
    <nameField>
        <label>Customer Receipt</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Customer_Receipt_Line__c.object
<CustomObject>
    <customHelpPage>HelpReceipts</customHelpPage>
    <description>Payment details associated with a payment received or issued</description>
    <fields>
        <fullName>Customer_Receipt__c</fullName>
        <label>Customer Receipt</label>
        <referenceTo>Customer_Receipt__c</referenceTo>
        <relationshipLabel>Customer Receipt Lines</relationshipLabel>
        <relationshipName>Customer_Receipt_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill To Customer</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1</booleanFilter>
            <filterItems>
                <field>Customer__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Bill To</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Customer Receipt Lines</relationshipLabel>
        <relationshipName>Customer_Receipt_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Receipt Line</label>
    <nameField>
        <label>Payment Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Receipt Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/classes/BankTransactionVoidCancelTest.cls
@isTest
private with sharing class BankTransactionVoidCancelTest {
 
      public class TestDataForBankTxns{
        public Testfuel fuel = new Testfuel();
        public Bank_Transaction_Group__c BankTxnGrp  = new Bank_Transaction_Group__c();            
        public List<Bank_Transaction__c> BankTxnList = new list<Bank_Transaction__c>();

        public TestDataForBankTxns(){
  
            system.assert(fuel.periodList.size()>0);

 
            Bank_account__c ba= fuel.bankAccount;
            ba.Opening_balance__C = 100;
            ba.Balance_offset__c=50;
            ba.opening_balance_date__c = system.now().adddays(-30);
            update ba;
            
            Customer_Receipt__c custReceipt = new Customer_Receipt__c();
            custReceipt.Company__c = fuel.company.Id;
            custReceipt.Customer__c = fuel.customerParent.Id;
            custReceipt.Amount_Received__c = 100;
            custReceipt.bank_Account_2__c = ba.Id;
            custReceipt.Payment_Method_G__c = 'Check';
            custReceipt.Reference_Number__c = '1234';
            custReceipt.Date_Received__c = system.now() - 25;
            custReceipt.Type__c = 'Receipt';
            custReceipt.Currency__c = TestFuel.currencyUSD.id;
            insert custReceipt; 
            
            Customer_Receipt_Line__c additionalPayment = new Customer_Receipt_Line__c();
            additionalPayment.Amount__c = 100;
            additionalPayment.Customer_Receipt__c = custReceipt.Id;
            additionalPayment.Type__c = PaymentService.TYPE_PREPAYMENT;
            insert additionalPayment;
            
            custReceipt.Finalized__c = true;
            update custReceipt;
        
            Bank_Transaction__c bt  = new Bank_Transaction__c (Company__c = fuel.company.id, Amount__c = 100, Transaction_Date__c = custReceipt.Date_Received__c , 
                                                           Bank_Account__c = ba.Id,subtransaction_type__c ='Credit');
            insert bt;
            BT = [Select id,name,bank_transaction_group__c from Bank_Transaction__c where id = :bt.id];
           BankTxnList.add(bt);
       
        Bank_Transaction_Match__c btm = new Bank_Transaction_Match__c(Bank_Transaction__c = bt.Id, Customer_Receipt__c = custReceipt.Id, Amount__c = 100);
        insert btm;
            
         
            BankTxnGrp =[select id,name,finalized__c,void_date__c from Bank_Transaction_Group__c where id in  (select bank_transaction_group__c from Bank_Transaction__c where ID IN :BankTxnList) LIMIT 1];
            system.assertEquals(BankTxnGrp.finalized__c,true,'Expecting BTB to be succesfully finalized.');             
        }
    }
       
    public static testMethod void testCanVoidBTG() {
         
        TestDataForBankTxns testData = new TestDataForBankTxns();
       // TestFuel fuel = new TestFuel();
        
        //Generate Accounting
        BankTransactionGroupAccounting btga = new BankTransactionGroupAccounting();
     
        Test.startTest();
        //Create Rules in testfuel
        system.assert(testData.fuel.BankTxnGrpAcctRulesList.size()>0);
        //Generate Accounting 
        //Reset mrules map so that it is repopulated with new rules giving correct segmentrefernces.
        AccountingRuleService.mAccountingRules  =  new Map<string, List<Accounting_Rule__c>>();
        btga = new BankTransactionGroupAccounting();//Load segment references again.
        btga.execute(testData.BankTxnList);
        List<Accounting_Entry__c> newAEs = new list<Accounting_Entry__c>(); 
       
        newAEs = [select id,name from Accounting_Entry__c 
               where Bank_Transaction_Group__c = :testData.BankTxnGrp.Id 
               and status__c='Active'
               and Has_Exceptions__c = false];
        system.assertNotEquals(newAEs.size(),0,'Expecting no exceptions rules are created.');    
        //Bank_transaction__c bt = [select bank_Transaction_group__c ,Amount__c, id,finalized__c from bank_transaction__c where id =:testData.BankTxnList[0].id ];
        Bank_transaction_group__c btg = [select id , finalized__c,Void_Date__c from bank_transaction_group__c where id =:testData.BankTxnGrp.Id  ];
        
         Test.stoptest();

         BankTransactionVoidCancelExt ext = new BankTransactionVoidCancelExt(new ApexPages.standardsetController(testData.BankTxnList));
         BankTransactionVoidCancelExt.voidCancelBankTransactionGroup(testData.BankTxnList[0].id, 'void',String.valueOf((System.now() - 10) .format('yyyy-MM-dd HH:mm:ss')));
         Bank_transaction_group__c BankTransactionGroup = [select id , finalized__c,status__c,Void__c, void_date__c from bank_transaction_group__c where id =:testData.BankTxnGrp.Id  ];
         system.assertEquals( 'Void',BankTransactionGroup.Status__c,'**'+testData.BankTxnList[0]);
            system.assertEquals(BankTransactionGroup.Void__c, true);
         system.assertEquals(BankTransactionGroup.Void_date__c.date(), System.today() - 10);
    }
        
    public static testMethod void testCannotCancelBTG() {
         
        TestDataForBankTxns testData = new TestDataForBankTxns();
       // TestFuel fuel = new TestFuel();
        
        //Generate Accounting
        BankTransactionGroupAccounting btga = new BankTransactionGroupAccounting();
     
        Test.startTest();
        //Create Rules in testfuel
        system.assert(testData.fuel.BankTxnGrpAcctRulesList.size()>0);
        //Generate Accounting 
        //Reset mrules map so that it is repopulated with new rules giving correct segmentrefernces.
        AccountingRuleService.mAccountingRules  =  new Map<string, List<Accounting_Rule__c>>();
        btga = new BankTransactionGroupAccounting();//Load segment references again.
        btga.execute(testData.BankTxnList);
        List<Accounting_Entry__c> newAEs = new list<Accounting_Entry__c>(); 
       
        newAEs = [select id,name from Accounting_Entry__c 
               where Bank_Transaction_Group__c = :testData.BankTxnGrp.Id 
               and status__c='Active'
               and Has_Exceptions__c = false];
        system.assertNotEquals(newAEs.size(),0,'Expecting no exceptions rules are created.');    
        Bank_transaction_group__c btg = [select id , finalized__c from bank_transaction_group__c where id =:testData.BankTxnGrp.Id  ];
        
        Test.stoptest();
        BankTransactionVoidCancelExt ext = new BankTransactionVoidCancelExt(new ApexPages.standardsetController(testData.BankTxnList));
        BankTransactionVoidCancelExt.voidCancelBankTransactionGroup(testData.BankTxnList[0].id, 'void',String.valueOf(System.now().format('yyyy-MM-dd HH:mm:ss')));
        Bank_transaction_group__c BankTransactionGroup = [select id , finalized__c,status__c,Void__c from bank_transaction_group__c where id =:testData.BankTxnGrp.Id  ];
            system.assertNotEquals( 'Cancelled',BankTransactionGroup.Status__c,'Cannot cancel because of accouting entry available.');
    }
        
        public static testMethod void testCanNotVoidBTG() {
         
        TestDataForBankTxns testData = new TestDataForBankTxns();
       // TestFuel fuel = new TestFuel();
        
        //Generate Accounting
        BankTransactionGroupAccounting btga = new BankTransactionGroupAccounting();
     
        Test.startTest();
        //Create Rules in testfuel
       
        List<Accounting_Entry__c> newAEs = new list<Accounting_Entry__c>(); 
       
        newAEs = [select id,name from Accounting_Entry__c 
               where Bank_Transaction_Group__c = :testData.BankTxnGrp.Id 
               and status__c='Active'
               and Has_Exceptions__c = false];
        system.assertEquals(newAEs.size(),0,'Expecting no accouting rules.');    
      
        Test.stoptest();
         BankTransactionVoidCancelExt ext = new BankTransactionVoidCancelExt(new ApexPages.standardsetController(testData.BankTxnList));
        testData.BankTxnList[0].Transaction_Date__c = System.now()-10;
        BankTransactionVoidCancelExt.voidCancelBankTransactionGroup(testData.BankTxnList[0].id, 'void',String.valueOf(System.now().format('yyyy-MM-dd HH:mm:ss')));
        Bank_transaction_group__c BankTransactionGroup = [select id , finalized__c,status__c,Void__c from bank_transaction_group__c where id =:testData.BankTxnGrp.Id  ];
            system.assertNOTEquals( 'Void',BankTransactionGroup.Status__c,'**'+testData.BankTxnList[0]);
            system.assertEquals(BankTransactionGroup.Void__c, false);
    }
        
    public static testMethod void testCanCancelBTG() {
         
        TestDataForBankTxns testData = new TestDataForBankTxns();
       // TestFuel fuel = new TestFuel();
        
        //Generate Accounting
        BankTransactionGroupAccounting btga = new BankTransactionGroupAccounting();
     
        Test.startTest();
       
        List<Accounting_Entry__c> newAEs = new list<Accounting_Entry__c>(); 
       
        newAEs = [select id,name from Accounting_Entry__c 
               where Bank_Transaction_Group__c = :testData.BankTxnGrp.Id 
               and status__c='Active'
               and Has_Exceptions__c = false];
        system.assertEquals(newAEs.size(),0,'Expecting no accouting rules.');    
      
        Test.stoptest();
         BankTransactionVoidCancelExt ext = new BankTransactionVoidCancelExt(new ApexPages.standardsetController(testData.BankTxnList));
           BankTransactionVoidCancelExt.voidCancelBankTransactionGroup(testData.BankTxnList[0].id, 'void',String.valueOf(System.now().format('yyyy-MM-dd HH:mm:ss')));
        Bank_transaction_group__c BankTransactionGroup = [select id , finalized__c,status__c,Void__c from bank_transaction_group__c where id =:testData.BankTxnGrp.Id  ];
            system.assertNOTEquals( 'Cancelled',BankTransactionGroup.Status__c,'**'+testData.BankTxnList[0]);
        
       
    }

}