src-ken&y/objects/Accounting_Code__c.object
<CustomObject>
    <customHelpPage>HelpAccountingCode</customHelpPage>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Accounting Codes</relationshipLabel>
        <relationshipName>Accounting_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Validated__c</fullName>
        <label>Last Validated</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SCOA_Key__c</fullName>
        <externalId>true</externalId>
        <label>SCOA Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Valid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Valid</label>
        <type>Checkbox</type>
    </fields>
    <label>Accounting Code</label>
    <nameField>
        <displayFormat>AC-{0000000000}</displayFormat>
        <label>Accounting Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounting Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Company__c.object
<CustomObject>
    <customHelpPage>HelpCompany</customHelpPage>
    <description>Each Logistics or Financial entity will be represented by a single Company record.  Master data for the Company is recorded here and used throughout the System.</description>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Process_Job__c.object
<CustomObject>
    <customHelpPage>HelpProcessJobs</customHelpPage>
    <description>Establish and manage scheduled jobs to run at various hours or frequencies</description>
    <fields>
        <fullName>Batch_Size__c</fullName>
        <defaultValue>25</defaultValue>
        <description>The number of records for each execution of the batch.</description>
        <inlineHelpText>The number of records for each execution of the batch.</inlineHelpText>
        <label>Batch Size</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The company that will be used for the input parameter to the job</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Process Jobs</relationshipLabel>
        <relationshipName>Process_Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Process Job</label>
    <nameField>
        <label>Process Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Segment_Definition__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Defines the GL Segments, their associated objects, and the field on the Accounting Entry</description>
    <fields>
        <fullName>Accounting_Entry_Field__c</fullName>
        <description>Field on the accounting entry where this segment information is stored</description>
        <inlineHelpText>Field on the accounting entry where this segment information is stored</inlineHelpText>
        <label>Accounting Entry Field</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Accounting Entry Segment Definition</label>
</CustomObject>

src-ken&y/objects/Segment_Validation__c.object
<CustomObject>
    <customHelpPage>HelpSegmentValidation</customHelpPage>
    <label>Segment Validation</label>
    <nameField>
        <displayFormat>SV-{0000000000}</displayFormat>
        <label>Segment Validation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segment Validations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/AccountingCodeValidationBatch.cls
/*
* without sharing is intentional.  accounting needs to be run in system mode.
*/
public without sharing class AccountingCodeValidationBatch implements Database.batchable<sObject>, Process.Runnable2, Database.Stateful {
    
    public string query;
    public set<Id> operatingCompanyIds = new set<Id>();
    public List<Notify.Message> messages = new List<Notify.Message>();
    AccountingCodeService ACS = new AccountingCodeService();
	SegmentService SS = new SegmentService();
	
    public void runBatch( Process_Job__c job ) {     // Process.Runnable2 implementation 
		AccountingCodeValidationBatch obj=new AccountingCodeValidationBatch(new set<id>{ job.Company__c} );
		integer defaultBatchSize = 10;
		if ( job.Batch_Size__c !=null && integer.valueOf(job.Batch_Size__c) <= 20 && integer.valueOf(job.Batch_Size__c) >= 1 ) { 
			defaultBatchSize = integer.valueOf(job.Batch_Size__c);
		}
        Database.executebatch(obj, defaultBatchSize);
    }
    
    public AccountingCodeValidationBatch() {}

    public AccountingCodeValidationBatch(set<Id> operatingCompIds){
        operatingCompanyIds = operatingCompIds;
        string segFields = '';
		for(Segment_Definition__c sd : SS.segments){
			segFields += ', ' + sd.Accounting_entry_field__c ;
		}
   	
      	query = 'SELECT Id, name, Valid__c, last_validated__c, SCOA_Key__c '
      				+ segFields
      				+ ' FROM Accounting_Code__c' 
      				+ ' WHERE Company__c IN :operatingCompanyIds ';
    }
      
    public Database.QueryLocator start(Database.BatchableContext BC){ 
    	MasterControlProgram.checkAlreadyRunning( this, BC );    
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext info, List<Accounting_Code__c> scope){
        
        Savepoint sp = Database.setSavepoint();
        try{
			//KNDY-10473: Adding CRUD/FLS checks with SOQLUtil
			SOQLUtil soql = new SOQLUtil('Accounting_Code__c', false); //enforceFLS=false, running in system mode
			soql.addFields(new set<string>{
				'Last_Validated__c'
			});
			soql.setOrderByClause('last_validated__c ASC'); 
			soql.setLimit(1);
			Accounting_Code__c acctCode = Database.query(soql.getQuery());


			//KNDY-10473: Adding CRUD/FLS checks with SOQLUtil
			soql = new SOQLUtil('segment_validation__c', false); //enforceFLS=false, running in system mode
			soql.addFields(new set<string>{
				'lastmodifiedDate'
			});
			soql.setOrderByClause('lastmodifieddate DESC'); 
			soql.setLimit(1);
			Segment_Validation__c segValidation = Database.query(soql.getQuery());
 			
 			
 			system.debug(logginglevel.info,'segValidation.lastmodifiedDate:'+segValidation.lastmodifiedDate);
 			system.debug(logginglevel.info,'acctCode.Last_Validated__c:'+acctCode.Last_Validated__c);
 			if(segValidation.lastmodifiedDate > acctCode.Last_Validated__c){
 				system.debug(logginglevel.info,'Inside if loop of execute');
 				AccountingCodeService.isInvokedfromBatch = true;
 				AccountingCodeService.segmentValidation(scope);
 			}
        } catch(Exception e) {
        	system.debug('EXCEPTION: ' + e);
            Database.rollback(sp);
            messages.add(Notify.getErrorMessage(scope, e.getMessage(), e.getStackTraceString()));
        }
    }
    
    public void finish(Database.BatchableContext info){
  	
        BatchToChatter.processBatchInformation(info.getJobId(), this, messages);
        Notify.sendEmailBatchFinish( null, messages, info);        
        MasterControlProgram.finishedBatch( this ); 

    }
}