src-ken&y/objects/Accounting_Entry__c.object
<CustomObject>
    <customHelpPage>HelpAccountingEntries</customHelpPage>
    <description>Accounting Entry Header records</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Accounting Entries</relationshipLabel>
        <relationshipName>Accounting_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Journal_Entry__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Journal Entry</label>
        <referenceTo>Journal_Entry__c</referenceTo>
        <relationshipLabel>Accounting Entries</relationshipLabel>
        <relationshipName>Accounting_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Period</description>
        <label>Period</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Period__c.Open__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Period__c</referenceTo>
        <relationshipLabel>Accounting_Entries</relationshipLabel>
        <relationshipName>Accounting_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Accounting Entry</label>
    <nameField>
        <label>Accounting Entry</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Accounting_Entry_Line__c.object
<CustomObject>
    <customHelpPage>HelpAccountingEntries</customHelpPage>
    <description>Accounting Entry Lines</description>
    <fields>
        <fullName>Accounting_Entry__c</fullName>
        <label>Accounting Entry</label>
        <referenceTo>Accounting_Entry__c</referenceTo>
        <relationshipLabel>Accounting Entry Lines</relationshipLabel>
        <relationshipName>Accounting_Entry_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Accounting Entry Lines</relationshipLabel>
        <relationshipName>Accounting_Entry_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>TEXT(Accounting_Entry__r.Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Accounting Entry Line</label>
    <nameField>
        <label>Accounting Entry Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Entry Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Bank_Transaction_Group__c.object
<CustomObject>
    <customHelpPage>HelpManageBankTransactions</customHelpPage>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Bank Transaction Groups</relationshipLabel>
        <relationshipName>Bank_Transaction_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Bank Transaction Group</label>
    <nameField>
        <label>Bank Transaction Group</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Transaction Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Customer_Invoice__c.object
<CustomObject>
    <customHelpPage>HelpCustomerInvoice</customHelpPage>
    <description>Customer invoices</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Customer Invoices</relationshipLabel>
        <relationshipName>Ship_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of this shipment - Open, Shipped, Invoiced, Closed</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Invoice</label>
    <nameField>
        <label>Customer Invoice</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Customer_Receipt__c.object
<CustomObject>
    <customHelpPage>HelpReceipts</customHelpPage>
    <description>Records all customer receipts (checks, credit cards, EFT, etc) against invoice.</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company associated with this Customer Receipt. It should be populated with the default value for the user logged in.</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Customer Receipts</relationshipLabel>
        <relationshipName>Customer_Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Authorized</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Receipt</label>
    <nameField>
        <label>Customer Receipt</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Journal_Entry__c.object
<CustomObject>
    <customHelpPage>HelpJournalEntry</customHelpPage>
    <fields>
        <fullName>Auto_Reverse__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Auto Reverse check box tells to generate the reversing accounting entry in the next period.</description>
        <inlineHelpText>A checkmark indicates that Kenandy will generate a reversing accounting entry in the next period.</inlineHelpText>
        <label>Auto Reverse</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Journal Entries</relationshipLabel>
        <relationshipName>Journal_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Period</description>
        <label>Period</label>
        <referenceTo>Period__c</referenceTo>
        <relationshipLabel>Journal_Entries</relationshipLabel>
        <relationshipName>Journal_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Journal Entry</label>
    <nameField>
        <label>Journal Entry</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journal Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Period__c.object
<CustomObject>
    <customHelpPage>HelpPeriods</customHelpPage>
    <description>Segment of time that financial entries fall into</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Periods</relationshipLabel>
        <relationshipName>Periods</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Period</label>
    <nameField>
        <label>Period</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Process_Job__c.object
<CustomObject>
    <customHelpPage>HelpProcessJobs</customHelpPage>
    <description>Establish and manage scheduled jobs to run at various hours or frequencies</description>
    <fields>
        <fullName>Batch_Size__c</fullName>
        <defaultValue>25</defaultValue>
        <description>The number of records for each execution of the batch.</description>
        <inlineHelpText>The number of records for each execution of the batch.</inlineHelpText>
        <label>Batch Size</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The company that will be used for the input parameter to the job</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Process Jobs</relationshipLabel>
        <relationshipName>Process_Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Process Job</label>
    <nameField>
        <label>Process Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Receiving_Document__c.object
<CustomObject>
    <customHelpPage>HelpReceivingDocument</customHelpPage>
    <description>Receiving Document - Advanced Shipment Notice - ASN</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Receiving Documents</relationshipLabel>
        <relationshipName>Advanced_Shipment_Notice</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Receiving Document</label>
    <nameField>
        <label>Receiving Document</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Receiving Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Supplier_Invoice__c.object
<CustomObject>
    <customHelpPage>HelpSupplierInvoice</customHelpPage>
    <description>Record invoices for items or services  that are received from a supplier.  Bills can be recorded with or without purchase orders</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Supplier Invoices</relationshipLabel>
        <relationshipName>Supplier_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Supplier Invoice</label>
    <nameField>
        <label>Supplier Invoice</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Supplier_Payment__c.object
<CustomObject>
    <customHelpPage>HelpSupplierPayments</customHelpPage>
    <description>Pay supplier invoices</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company with which this supplier payment is associated with</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Supplier Payments</relationshipLabel>
        <relationshipName>Supplier_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Supplier Payment</label>
    <nameField>
        <label>Supplier Payment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/AccountingEntryVoidBatch.cls
public with sharing class AccountingEntryVoidBatch implements Database.Batchable<sObject>, Database.Stateful, Process.Runnable2, Schedulable{

    public set<Id> AEtoVoid;
    public Id batchJobId;
    public Id CompId;																																											
    private List<Period__c> periods;
    private List<Id> periodIds = new list<Id>();
    public List<Notify.Message> messages = new List<Notify.Message>();
    
    //This Id is used to pass which period we're closing the subledger for
    public Id subledgerClosePeriodId;
    //This is the field of the subledger closed field we intend to populate
    public string subledgerCloseField;
    
    public AccountingEntryVoidBatch(set<Id> AEtoVoid){
        this.AEtoVoid = AEtoVoid;
    }
    
    public AccountingEntryVoidBatch(Id batchJobId){
    	this.batchJobId = batchJobId;
    }
 
    public AccountingEntryVoidBatch() {}
    
    public void runBatch( Process_Job__c job ) { 		// Process.Runnable2 implementation 
    	
    	system.debug('job: ' + job);
    	AccountingEntryVoidBatch batch = new AccountingEntryVoidBatch();
        batch.CompId=job.company__c;
    	
    	integer defaultBatchSize = 200;
		if(job.batch_size__c != null){
			if(job.batch_size__c < 1){
				defaultBatchSize = 1;
			}else if(job.batch_size__c > 2000){
				defaultBatchSize = 2000;
			}else{
				defaultBatchSize = integer.valueOf(job.Batch_Size__c);
			}
		}
		
        Database.executebatch(batch, defaultBatchSize);
    } 
    
    
    public void execute(SchedulableContext context){
        Database.executeBatch(new AccountingEntryVoidBatch());
    }
    public Database.QueryLocator start(Database.BatchableContext BC){
                
	   	string query =  'SELECT Id, Accounting_Entry__c, Accounting_Entry__r.Period__c,Accounting_Entry__r.Journal_Entry__r.Auto_Reverse__c FROM Accounting_Entry_Line__c'
						+ ' WHERE Accounting_Entry__c  IN'
    					+ ' (SELECT Id FROM Accounting_Entry__c'
    					+ ' WHERE status__c = \'Active\' AND (Journal_Entry__r.Void__c = true '
    					+ ' OR Supplier_Invoice__r.Void__c = true OR Supplier_Payment__r.Void__c = true OR Journal_Entry__r.Auto_Reverse__c = true OR Customer_Invoice__r.Void__c = true OR Customer_Receipt__r.Void__c = true OR Receiving_Document__r.Void__c = true OR Bank_Transaction_Group__r.Void__c = true) AND Has_Exceptions__c != true  )'
						+ ' AND Accounting_Entry__c NOT  IN (SELECT Related_Accounting_Entry__c from Accounting_entry__c where Status__c=\'Active\' AND Has_Exceptions__c=false AND Related_Accounting_Entry__c!=null)'//Exclude valid reversal AEs .  					
    					+ ' AND Related_Accounting_entry_line__c = null';
    					
		/*if(AEtoVoid != null){
			query += ' AND Accounting_Entry__c in: AEtoVoid';
		}*/
		
		if(CompId!=null)
		{
			query +=  ' AND Accounting_Entry__r.company__c=:compId';
		}
		if(batchJobId != null){
			query += ' AND Accounting_Entry__r.BatchJobId__c = :batchJobId';
		}
		 //FIN-903 Pick reverse AEs with exceptions
    		//query += ' OR Accounting_Entry__c  IN (SELECT related_accounting_entry__c from Accounting_Entry__c where status__c=\'Active\' AND related_accounting_entry__c!=null and has_exceptions__c=true)';
        
        system.debug('queryLocator: ' + query);
        system.debug('AEtoVoid: ' + AEtoVoid);
        system.debug('compId: ' + CompId);
        system.debug('batchJobId: ' + batchJobId);
        
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext info, List<Accounting_Entry_Line__c> scope){
        list<Accounting_Entry_Line__c> AELtoVoid = new list<Accounting_Entry_Line__c>();
        list<Accounting_Entry_Line__c> AELtoReverse = new list<Accounting_Entry_Line__c>();
        for(Accounting_Entry_Line__c ael:scope){
        	periodIds.add(ael.Accounting_Entry__r.Period__c);
        
        	if(ael.Accounting_Entry__r.Journal_Entry__r.Auto_Reverse__c == true)
	        	AELtoReverse.add(ael);
        	else
	        	AELtoVoid.add(ael);
        }
        AccountingEntryService aes = AccountingEntryService.getInstance();
        //FIN-903 Send batchjob id to stamp in the reversal lines.
        if(!AELtoReverse.isEmpty())
	        aes.AccountingEntryLineReversal(AccountingEntryService.AEReverseType.AEReverse, AELtoReverse,info.getJobId());        		
        if(!AELtoVoid.isEmpty())
	        aes.AccountingEntryLineReversal(AccountingEntryService.AEReverseType.AEVoid, AELtoVoid,info.getJobId());        		
    }
    
    public void finish(Database.BatchableContext info){
    	
        BatchToChatter.processBatchInformation(info.getJobId(), this, messages);
        Notify.sendEmailBatchFinish( null, messages, info);        
        MasterControlProgram.finishedBatch( this ); 
        Map<Id, Period__c> mPeriods = new Map<Id, Period__c>();

		//KNDY-10473: Adding CRUD/FLS checks with SOQLUtil
		SOQLUtil soql = new SOQLUtil('Period__c', true); //enforceFLS=true, running in user mode
		soql.addFields(new set<string>{
			'Id','name','AR_Subledger_Job__c','AP_Subledger_Job__c','Shipment_Subledger_Job__c','Receiving_Subledger_Job__c','Inventory_Subledger_Job__c',
			'FA_Subledger_Job__c','JE_Subledger_Job__c'
		});
		soql.setWhereClause('open__c = true AND Id in :periodIds AND type__c IN (\'Fiscal\', \'Adjustment\',null)');
		periods = Database.query(soql.getQuery());
        
        system.debug('periods: ' + periods);
       	for(period__c p : periods){
            
            Period__c iPeriod;
            if(mPeriods.containsKey(p.Id)){
            	system.debug('getting period: ' + p.Id);
                iPeriod = mPeriods.get(p.Id);
            }else{
                iPeriod = p;
                system.debug('setting period: ' + p.Id);
                system.debug('iPeriod matches subledger close period ' + iPeriod.Id + ' - ' + subledgerClosePeriodId + ' - ' +  subledgerCloseField);
                if(iPeriod.Id != null && iPeriod.Id == subledgerClosePeriodId){
                	
                	if(subledgerCloseField != null){
                		PeriodService.systemEditable.add(iPeriod.Id);
                		iPeriod.put(subledgerCloseField, system.now());
                		system.debug('subledger closed: ' + iPeriod.get(subledgerCloseField));
                	}
                }
            }
            
			if(iPeriod.AR_Subledger_Job__c == info.getJobId())
		    	iPeriod.AR_Subledger_Job__c = null;   			
			if(iPeriod.AP_Subledger_Job__c == info.getJobId())
		    	iPeriod.AP_Subledger_Job__c = null;   			
			if(iPeriod.Shipment_Subledger_Job__c == info.getJobId())
		    	iPeriod.Shipment_Subledger_Job__c = null;   			
			if(iPeriod.FA_Subledger_Job__c == info.getJobId())
		    	iPeriod.FA_Subledger_Job__c = null;   			
			if(iPeriod.Receiving_Subledger_Job__c == info.getJobId())
		    	iPeriod.Receiving_Subledger_Job__c = null;   			
			if(iPeriod.Inventory_Subledger_Job__c == info.getJobId())
		    	iPeriod.Inventory_Subledger_Job__c = null;   			
			if(iPeriod.JE_Subledger_Job__c == info.getJobId())
		    	iPeriod.JE_Subledger_Job__c = null;   			
		    PeriodService.systemEditable.add(iPeriod.Id);
            system.debug('add period: ' + iPeriod);
			mPeriods.put(iPeriod.Id, iPeriod);
            
       	}
       	
       	
       	if(mPeriods.keySet().size() > 0) {
            system.debug('mPeriods: ' +  mPeriods);
       		DML.updateAsSystem(mPeriods.values());
        }       
    }
}