src-ken&y/objects/Accounting_Entry__c.object
<CustomObject>
    <customHelpPage>HelpAccountingEntries</customHelpPage>
    <description>Accounting Entry Header records</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Accounting Entries</relationshipLabel>
        <relationshipName>Accounting_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Accounting Entries</relationshipLabel>
        <relationshipName>Accounting_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fixed_Asset_Adjustment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Fixed Asset Adjustment</label>
        <referenceTo>Fixed_Asset_Adjustment__c</referenceTo>
        <relationshipLabel>Accounting Entries</relationshipLabel>
        <relationshipName>Accounting_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Accounting Entry</label>
    <nameField>
        <label>Accounting Entry</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Company__c.object
<CustomObject>
    <customHelpPage>HelpCompany</customHelpPage>
    <description>Each Logistics or Financial entity will be represented by a single Company record.  Master data for the Company is recorded here and used throughout the System.</description>
    <fields>
        <fullName>Default_Transaction_Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Default Transaction Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Companies (Default Transaction Currency)</relationshipLabel>
        <relationshipName>Default_Transaction_Currency</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Currency__c.object
<CustomObject>
    <customHelpPage>HelpCurrency</customHelpPage>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Currency</label>
    <nameField>
        <label>Currency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Fixed_Asset__c.object
<CustomObject>
    <customHelpPage>HelpFixedAssets</customHelpPage>
    <description>Stores the companies fixed assets for tracking and depreciation</description>
    <fields>
        <fullName>Acquisition_Cost__c</fullName>
        <description>Total cost to place asset in to service.</description>
        <inlineHelpText>stated in functional currency</inlineHelpText>
        <label>Acquisition Cost</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Book_Value__c</fullName>
        <description>This is the current value of the asset less the accumulated depreciation.</description>
        <formula>(Acquisition_Cost__c + Total_Adjustments__c) -Total_Depreciated_Value__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The current value of the asset, less the accumulated depreciation. The amount is stated in functional currency.</inlineHelpText>
        <label>Book Value</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Fixed Assets</relationshipLabel>
        <relationshipName>Fixed_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Last_Depreciated__c</fullName>
        <description>Date asset was last depreciated.</description>
        <label>Date Last Depreciated</label>
        <summarizedField>Fixed_Asset_Depreciation__c.Depreciation_Date__c</summarizedField>
        <summaryForeignKey>Fixed_Asset_Depreciation__c.Fixed_Asset__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Depreciation_Count__c</fullName>
        <description>The total number of times depreciation has been applied to this Fixed Asset.</description>
        <inlineHelpText>The total number of times depreciation has been applied to this Fixed Asset.</inlineHelpText>
        <label>Depreciation Count</label>
        <summaryFilterItems>
            <field>Fixed_Asset_Depreciation__c.Subtransaction_Type__c</field>
            <operation>equals</operation>
            <value>Depreciation</value>
        </summaryFilterItems>
        <summaryForeignKey>Fixed_Asset_Depreciation__c.Fixed_Asset__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Depreciation_Method__c</fullName>
        <description>The method that is used to model the assets depreciation.</description>
        <inlineHelpText>The method that is used to model the asset&apos;s depreciation.</inlineHelpText>
        <label>Depreciation Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Straight Line</fullName>
                </value>
                <value>
                    <fullName>Declining Balance</fullName>
                </value>
                <value>
                    <fullName>Sum of Years</fullName>
                </value>
                <value>
                    <fullName>MACRS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Depreciation_Period__c</fullName>
        <description>The time period between depreciation cycles for this asset.</description>
        <inlineHelpText>The time period between depreciation cycles for this asset.</inlineHelpText>
        <label>Depreciation Period</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Depreciation_Method__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Annually</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Estimated_End_of_Life__c</fullName>
        <description>In Service Date plus the number of months specified in Depreciation Life.</description>
        <inlineHelpText>The &quot;In Service Date&quot; plus the number of months specified in &quot;Depreciation Life&quot;.</inlineHelpText>
        <label>Estimated End of Life</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Final_Depreciation_Date__c</fullName>
        <description>This is the date that the final depreciation is assessed to the asset.</description>
        <label>Final Depreciation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fixed_Asset_Key__c</fullName>
        <externalId>true</externalId>
        <label>Fixed Asset Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Fixed_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link the relevant corporate book tax asset when creating a fixed asset for tax book purposes</description>
        <inlineHelpText>Link the relevant corporate book tax asset when creating a fixed asset for tax book purposes</inlineHelpText>
        <label>Fixed Asset (Corporate Book)</label>
        <referenceTo>Fixed_Asset__c</referenceTo>
        <relationshipLabel>Fixed Assets (Tax Books)</relationshipLabel>
        <relationshipName>Tax_Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>In_Service_Date__c</fullName>
        <description>Date this asset was put in to service.</description>
        <label>In Service Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Residual_Value__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Residual value of the asset at the end of its useful life.</description>
        <inlineHelpText>Residual value of the asset at the end of its service life. The amount is stated in functional currency.</inlineHelpText>
        <label>Residual Value</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <label>Fixed Asset</label>
    <nameField>
        <label>Fixed Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fixed Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Fixed_Asset_Adjustment__c.object
<CustomObject>
    <customHelpPage>HelpFixedAssets</customHelpPage>
    <description>Stores the value of all the costs associated with this asset throughout it&apos;s acquistion and lifecycle.</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Fixed Asset Adjustments</relationshipLabel>
        <relationshipName>Fixed_Asset_Adjustments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Fixed Asset Adjustments</relationshipLabel>
        <relationshipName>Fixed_Asset_Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fixed_Asset__c</fullName>
        <description>Lookup to Fixed Asset</description>
        <label>Fixed Asset</label>
        <referenceTo>Fixed_Asset__c</referenceTo>
        <relationshipLabel>Fixed Asset Adjustments</relationshipLabel>
        <relationshipName>Fixed_Asset_Adjustments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Fixed Asset Adjustment</label>
    <nameField>
        <label>Fixed Asset Adjustment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fixed Asset Adjustments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Fixed_Asset_Depreciation__c.object
<CustomObject>
    <customHelpPage>HelpFixedAssets</customHelpPage>
    <description>Records depreciation amounts and dates for fixed assets over time.</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Fixed Asset Depreciations</relationshipLabel>
        <relationshipName>Fixed_Asset_Depreciations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Fixed Asset Depreciations</relationshipLabel>
        <relationshipName>Fixed_Asset_Depreciations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fixed_Asset__c</fullName>
        <description>The fixed asset that this depreciation is applied to.</description>
        <label>Fixed Asset</label>
        <referenceTo>Fixed_Asset__c</referenceTo>
        <relationshipLabel>Fixed Asset History</relationshipLabel>
        <relationshipName>Fixed_Asset_Depreciations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Fixed Asset Depreciation</label>
    <nameField>
        <label>Fixed Asset Depreciation Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fixed Asset Depreciations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Supplier_Invoice__c.object
<CustomObject>
    <customHelpPage>HelpSupplierInvoice</customHelpPage>
    <description>Record invoices for items or services  that are received from a supplier.  Bills can be recorded with or without purchase orders</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Supplier Invoices</relationshipLabel>
        <relationshipName>Supplier_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to currency</description>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Supplier Invoice Currency</relationshipLabel>
        <relationshipName>Supplier_Invoice_Currency</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Supplier Invoice</label>
    <nameField>
        <label>Supplier Invoice</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Supplier_Invoice_Line__c.object
<CustomObject>
    <customHelpPage>HelpSupplierInvoice</customHelpPage>
    <fields>
        <fullName>Currency__c</fullName>
        <formula>Supplier_Invoice__r.Currency__r.ISO_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Currency</label>
        <type>Text</type>
    </fields>
    <label>Supplier Invoice Line</label>
    <nameField>
        <label>Supplier Invoice Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier Invoice Line</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/classes/FixedAssetAdjustmentAccountingBatchTest.cls
@isTest
private class FixedAssetAdjustmentAccountingBatchTest {
    
    @testSetup
    static void createTestData() {
        Test.startTest(); //denote testing context
            FixedAssetData fad =  new FixedAssetData();
             Test.stopTest();
            List<Fixed_Asset_Adjustment__c> faas = new List<Fixed_Asset_Adjustment__c>();
            // Create Fixed Asset Data with final depreciation date greater than FAA TD to be used in testFAAUnfinalizeWhenValidFADsExists
            Fixed_Asset__c fa = [SELECT id, name, depreciation_method__c, depreciation_period__c, estimated_end_of_life__c, in_service_date__c, 
                                acquisition_cost__c, residual_value__c, date_last_depreciated__c, book_value__c, Fixed_Asset_Key__c,
                                company__c, company__r.Default_Transaction_Currency__c, Final_Depreciation_Date__c, depreciation_count__c,
                                Depreciation_Convention__c, depreciable_basis__c, Asset_Tag_Number__c, Total_Depreciated_Value__c,Prorate_First_Period__c
                                FROM Fixed_Asset__c 
                                WHERE Id = :fad.slfa.Id];
                                
            for(integer i=0; i<10; i++){
                Fixed_Asset_Adjustment__c iFaa = 
                        new Fixed_Asset_Adjustment__c(Supplier_Invoice_line__c = fad.ril1.Id, supplier_invoice__c = fad.ril1.supplier_invoice__c, amount__c = 1, 
                                                        type__c = 'Upgrade', subtransaction_type__c = 'Upgrade',  fixed_asset__c = fad.insertFixedAssets[0].Id,
                                                        company__c = fad.si.Company__c, Currency__c = fad.si.Currency__c,
                                                        adjustment_date__c = system.today(), transaction_date__c = system.now());
                faas.add(iFaa);
            }
            insert faas;
            for(Fixed_Asset_Adjustment__c faa : faas){
                faa.finalized__c = true;
            }
            update faas;
            
            Fixed_Asset_Adjustment__c unfinalizedFAA      = 
                                        new Fixed_Asset_Adjustment__c(Supplier_Invoice_line__c = fad.ril1.Id, supplier_invoice__c = fad.ril1.supplier_invoice__c, amount__c = 1, 
                                                    type__c = 'Upgrade', subtransaction_type__c = 'Upgrade', fixed_asset__c = fa.Id,
                                                    company__c = fad.si.Company__c, Currency__c = fad.si.Currency__c,
                                                    adjustment_date__c = system.today().addMonths(-1), transaction_date__c = system.now().addMonths(-1));   
            insert unfinalizedFAA;
                                                    
        //Test.stopTest(); //revert from testing context
    }
    static testMethod void testBatch() {
       
       Set<Id> faaIds    = new Set<Id>();
       
       List<Fixed_Asset_Adjustment__c> adjustments  = [SELECT Supplier_Invoice_line__c , 
                                                            supplier_invoice__c  , amount__c  , 
                                                            type__c  , subtransaction_type__c  , 
                                                            fixed_asset__c ,
                                                            company__c  , 
                                                            Currency__c  ,
                                                            adjustment_date__c  , 
                                                            transaction_date__c 
                                                      FROM Fixed_Asset_Adjustment__c LIMIT 5  ] ;
        
        for(Fixed_Asset_Adjustment__c eachFAA : adjustments){
            faaIds.add(eachFAA.Id);
        }
        test.startTest();
        	FixedAssetAdjustmentAccountingBatch batch = new FixedAssetAdjustmentAccountingBatch(new Set<Id>{adjustments[0].company__c});
        	database.executebatch(batch);
        test.stopTest();
         
		List<Accounting_Entry__c> aes = [SELECT Id 
		                                    FROM Accounting_Entry__c 
		                                    WHERE Fixed_Asset_Adjustment__c IN :faaIds];
		system.assertEquals(5, aes.size(), 'We expect 1 AE for every Adjustment' + batch.messages);
		
    }
    
    static testMethod void testAccounting() {
    	 Set<Id> compIds = new  Set<Id>();
         List<Fixed_Asset_Adjustment__c> adjustments  = [SELECT Supplier_Invoice_line__c , 
                                                            supplier_invoice__c  , amount__c  , 
                                                            type__c  , subtransaction_type__c  , 
                                                            fixed_asset__c ,company__r.Id,
                                                            company__c  , 
                                                            Currency__c  ,
                                                            adjustment_date__c  , 
                                                            transaction_date__c 
                                                      FROM Fixed_Asset_Adjustment__c LIMIT 5  ] ;
                                                      
        for(Fixed_Asset_Adjustment__c adj: adjustments){
            compIds.add(adj.company__r.Id);
        }
        test.startTest();
        	AccountingProcessFixedAssetAdjustments faa = new AccountingProcessFixedAssetAdjustments();
        	faa.execute(adjustments);
            List<Accounting_Entry__c> aes = [SELECT Id FROM Accounting_Entry__c WHERE Fixed_Asset_Adjustment__c IN :adjustments];
		    system.assertEquals(5, aes.size(), 'We expect 1 AE for every Adjustment');
		    FixedAssetAdjustmentAccountingBatch batch = new FixedAssetAdjustmentAccountingBatch(compIds);
        test.stopTest();
		List<Accounting_Entry__c> aes1 = [SELECT Id FROM Accounting_Entry__c WHERE Fixed_Asset_Adjustment__c IN :adjustments and status__c = 'Draft'];
		system.assertEquals(0, aes1.size(), 'We expect records are nopt picked up again'); 
    }
    
    static testMethod void testHeaderFinalize(){
    	 Fixed_Asset_Adjustment__c iFaa  = [SELECT Supplier_Invoice_line__c , 
                                                        supplier_invoice__c  , amount__c  , 
                                                        type__c  , subtransaction_type__c  , 
                                                        fixed_asset__c ,
                                                        company__c  , 
                                                        Currency__c  ,
                                                        adjustment_date__c  , 
                                                        transaction_date__c 
                                            FROM Fixed_Asset_Adjustment__c LIMIT 1  ] ;
       
        
        Test.startTest();
            boolean sawError = false;
            try{
              iFaa.transaction_date__c = iFaa.transaction_date__c.addDays(1); 
              update iFaa;
            }catch(exception ex){
            	sawError = true;
            }
        Test.stopTest();
        
        System.assert(sawError, 'We should see an error when attempting to update a finalized header');
    }
    static testMethod void testFAAUnfinalize() {
         
           Fixed_Asset_Adjustment__c iFaa  = [SELECT Supplier_Invoice_line__c , 
                                                        supplier_invoice__c  , amount__c  , 
                                                        type__c  , subtransaction_type__c  , 
                                                        fixed_asset__c ,
                                                        company__c  , 
                                                        Currency__c  ,
                                                        adjustment_date__c  , 
                                                        transaction_date__c 
                                            FROM Fixed_Asset_Adjustment__c LIMIT 1  ] ;
       
            AccountingProcessFixedAssetAdjustments faaAdjAcc = new AccountingProcessFixedAssetAdjustments();
            faaAdjAcc.execute(new List<Fixed_Asset_Adjustment__c>{iFaa}); 
            List<Accounting_Entry__c> aes = [SELECT Id FROM Accounting_Entry__c WHERE Fixed_Asset_Adjustment__c = :iFaa.Id];
            system.assertEquals(1, aes.size(), 'We expect 1 AE for every Adjustment');
            
            Fixed_Asset_Adjustment__c fadToBeUnfinalized = iFaa;
            //System.debug('Before Finalize'+fadToBeUnfinalized);
            Test.startTest();
                // Test Unfinalize FAA   
                Test.setCurrentPage(Page.SourceDocumentUnfinalize);
                ApexPages.currentPage().getParameters().put('id',fadToBeUnfinalized.id);
                SourceDocumentUnfinalize unfinalize = new SourceDocumentUnfinalize();
                unfinalize.unfinalizeSourceDoc();
                unfinalize.unfinalize();
           Test.stopTest();
          
          
        Fixed_Asset_Adjustment__c unfinalizedFAA = [select id, finalized__c from Fixed_Asset_Adjustment__c where id=:fadToBeUnfinalized.id]; 
        //System.debug('After Finalize'+unfinalizedFAA);
        System.assertEquals(false,unfinalizedFAA.finalized__c);
        // Verify that the  Acc Entry becomes Obsolete
        Accounting_Entry__c aeForUnfinalizedFAA = [SELECT Id,Status__c FROM Accounting_Entry__c WHERE Fixed_Asset_Adjustment__c =:unfinalizedFAA.id];
        //System.debug('Acc entry after Unfinalize'+aeForUnfinalizedFAA);
        System.assertEquals('Obsolete',aeForUnfinalizedFAA.Status__c);
    }
    
    
    // KNDY-10996 -- FAA can not be unfinalized if the FAD for that Fixed Asset exists 
      //and Date Last Depreciated > Transaction Date ( FAA's TD)
    static testMethod void testFAAUnfinalizeWhenValidFADsExists() { 
         
            Fixed_Asset__c fa = [SELECT id, name, depreciation_method__c, depreciation_period__c, estimated_end_of_life__c, in_service_date__c, 
                                    acquisition_cost__c, residual_value__c, date_last_depreciated__c, book_value__c, Fixed_Asset_Key__c,company__r.Comp_Currency__c,
                                    company__c, company__r.Default_Transaction_Currency__c, Final_Depreciation_Date__c, depreciation_count__c,
                                    Depreciation_Convention__c, depreciable_basis__c, Asset_Tag_Number__c, Total_Depreciated_Value__c,Prorate_First_Period__c
                                FROM Fixed_Asset__c 
                                LIMIT 1];
        
            // Create FAA for that FA with transaction date less than final depreciation date 
             
            Fixed_Asset_Adjustment__c unfinalizedFAA = [SELECT Supplier_Invoice_line__c , 
                                                            supplier_invoice__c  , amount__c  , 
                                                            type__c  , subtransaction_type__c  , 
                                                            fixed_asset__c ,
                                                            company__c  , 
                                                            Currency__c  ,
                                                            adjustment_date__c  , 
                                                            transaction_date__c 
                                                      FROM Fixed_Asset_Adjustment__c 
                                                      WHERE finalized__C=false
                                                      LIMIT 1]; 
           	  
           	 	unfinalizedFAA.transaction_date__c = system.now().addMonths(-1) ;
           	    unfinalizedFAA.finalized__C        = true;
           	Test.StartTest();
           	 	update  unfinalizedFAA; 
           	 	System.debug('Fixed Asset Adjustment--'+unfinalizedFAA);
            
        		// Create Fixed Asset depreciations on the FA
        		AccountingStraightLineDepreciation asld = new AccountingStraightLineDepreciation();
    	     	asld.execute(new List<sObject>{(sObject)fa}, system.today(), true);
        	
        	 
        		List<Fixed_Asset_Depreciation__c> fads = [SELECT Id
            												 FROM Fixed_Asset_Depreciation__c 
            												 WHERE Fixed_Asset__c = :fa.Id]; 
            	System.debug('The SL FAD records'+fads); 
             
    	    	// Do Unfinalize on FAA 
    	        Test.setCurrentPage(Page.SourceDocumentUnfinalize);
    	        ApexPages.currentPage().getParameters().put('id',unfinalizedFAA.id);
    	        SourceDocumentUnfinalize unfinalize = new SourceDocumentUnfinalize(); 
    	        unfinalize.unfinalizeSourceDoc();
    	        unfinalize.unfinalize();  
          Test.StopTest();
    	// Check the status of Fixed Asset Adjustment - Should be finalized
    	 system.assertEquals(unfinalizedFAA.finalized__C,true);  
    	 	
    } 
}