src-ken&y/objects/Accounting_Entry__c.object
<CustomObject>
    <customHelpPage>HelpAccountingEntries</customHelpPage>
    <description>Accounting Entry Header records</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Accounting Entries</relationshipLabel>
        <relationshipName>Accounting_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fixed_Asset_Depreciation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Fixed Asset Depreciation</description>
        <label>Fixed Asset Depreciation</label>
        <referenceTo>Fixed_Asset_Depreciation__c</referenceTo>
        <relationshipLabel>Accounting Entries</relationshipLabel>
        <relationshipName>Accounting_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Period_Status__c</fullName>
        <formula>IF(Period__r.Open__c, &apos;Open&apos;, if(Period__r.Closed__c,&apos;Closed&apos;,if(Period__r.Permanently_Closed__c,&apos;Permanently closed&apos;,&apos;Not Opened&apos;)))</formula>
        <label>Period Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Void__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This check box is selected when the entry is successfully Voided</description>
        <label>Void</label>
        <type>Checkbox</type>
    </fields>
    <label>Accounting Entry</label>
    <nameField>
        <label>Accounting Entry</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Company__c.object
<CustomObject>
    <customHelpPage>HelpCompany</customHelpPage>
    <description>Each Logistics or Financial entity will be represented by a single Company record.  Master data for the Company is recorded here and used throughout the System.</description>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Fixed_Asset__c.object
<CustomObject>
    <customHelpPage>HelpFixedAssets</customHelpPage>
    <description>Stores the companies fixed assets for tracking and depreciation</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Fixed Assets</relationshipLabel>
        <relationshipName>Fixed_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fixed_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link the relevant corporate book tax asset when creating a fixed asset for tax book purposes</description>
        <inlineHelpText>Link the relevant corporate book tax asset when creating a fixed asset for tax book purposes</inlineHelpText>
        <label>Fixed Asset (Corporate Book)</label>
        <referenceTo>Fixed_Asset__c</referenceTo>
        <relationshipLabel>Fixed Assets (Tax Books)</relationshipLabel>
        <relationshipName>Tax_Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GL_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Fixed Asset GL Account -  The full acquisition cost of the asset will be debited from this GL account when the asset is first activated.</description>
        <inlineHelpText>The full acquisition cost of the asset is debited from this GL account when the asset is first activated.</inlineHelpText>
        <label>Fixed Asset GL Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>GL_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>GL_Account__c</referenceTo>
        <relationshipLabel>Fixed Assets</relationshipLabel>
        <relationshipName>Fixed_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Book</description>
        <label>Book</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Company__c</field>
                <operation>equals</operation>
                <valueField>Tax_Book__c.Company__r.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Tax_Book__c</referenceTo>
        <relationshipLabel>Fixed Assets</relationshipLabel>
        <relationshipName>Fixed_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Fixed Asset</label>
    <nameField>
        <label>Fixed Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fixed Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Fixed_Asset_Depreciation__c.object
<CustomObject>
    <customHelpPage>HelpFixedAssets</customHelpPage>
    <description>Records depreciation amounts and dates for fixed assets over time.</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Fixed Asset Depreciations</relationshipLabel>
        <relationshipName>Fixed_Asset_Depreciations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Depreciation_Amount__c</fullName>
        <description>The amount that the asset has been depreciated for the specified period.</description>
        <label>Depreciation Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Depreciation_Date__c</fullName>
        <description>The date on which the depreciation is assessed.</description>
        <label>Depreciation Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Depreciation_Type__c</fullName>
        <description>This is the algorithm used to model the depreciation for the asset.</description>
        <inlineHelpText>This is the algorithm used to model the depreciation for the asset.</inlineHelpText>
        <label>Depreciation Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Straight Line</fullName>
                </value>
                <value>
                    <fullName>Double Declining</fullName>
                </value>
                <value>
                    <fullName>Sum of Years</fullName>
                </value>
                <value>
                    <fullName>MACRS</fullName>
                </value>
                <value>
                    <fullName>CIP</fullName>
                </value>
                <value>
                    <fullName>Residual</fullName>
                </value>
                <value>
                    <fullName>Retire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Finalized__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag is set to true when the invoice is finalized and no more changes are expected</description>
        <label>Finalized</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Fixed_Asset__c</fullName>
        <description>The fixed asset that this depreciation is applied to.</description>
        <label>Fixed Asset</label>
        <referenceTo>Fixed_Asset__c</referenceTo>
        <relationshipLabel>Fixed Asset History</relationshipLabel>
        <relationshipName>Fixed_Asset_Depreciations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>GL_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to GL Account</description>
        <label>GL Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>GL_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>GL_Account__c</referenceTo>
        <relationshipLabel>Fixed Asset Depreciations</relationshipLabel>
        <relationshipName>Fixed_Asset_Depreciations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GL_Date__c</fullName>
        <description>This is the date that the accounting entry will be made for the depreciation cycle.</description>
        <label>GL Date</label>
        <type>Date</type>
    </fields>
    <label>Fixed Asset Depreciation</label>
    <nameField>
        <label>Fixed Asset Depreciation Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fixed Asset Depreciations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/GL_Account__c.object
<CustomObject>
    <customHelpPage>HelpGLAccount</customHelpPage>
    <description>Table of acceptable General Ledger Numbers or Names with associated Cross Reference Information</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Select box if GL account is active</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>GL Account</label>
    <nameField>
        <label>GL Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Tax_Book__c.object
<CustomObject>
    <customHelpPage>Help_Books</customHelpPage>
    <description>Tax Book related to a Company</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Company.</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipName>Tax_Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent corporate book for this tax book.</description>
        <inlineHelpText>Lookup (Book). For tax books this is the parent book.</inlineHelpText>
        <label>Book</label>
        <referenceTo>Tax_Book__c</referenceTo>
        <relationshipLabel>Tax Books</relationshipLabel>
        <relationshipName>Tax_Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/CompanyFixedAssetDepreciationRollbackExt.cls
public with sharing class CompanyFixedAssetDepreciationRollbackExt {
	
	private Apexpages.Standardcontroller companyController;
	public integer pageSize {get;set;} { pagesize = 25;}
	public Apexpages.Standardsetcontroller fadStandardSetController {get;set;}
	public boolean disableRollback {get;set;}
	public Map<Id, List<SelectOption>> mTaxBooks {get;set;}
	public List<SelectOption> companyOptions {get;set;}
	public string selectedCompanyId {get;set;}
	public string selectedBookId {get;set;}
	
	public CompanyFixedAssetDepreciationRollbackExt(Apexpages.Standardcontroller controller){
		companyController = controller;
		disableRollback = true;
		if(companyController != null){
			selectedCompanyId = companyController.getId();
		}
		updateCompanyBookOptions();
	}
	
	public void updateFixedAssetDepreciations(){
		//KNDY-10473: Adding CRUD/FLS checks with SOQLUtil
		SOQLUtil soql = new SOQLUtil('Fixed_Asset_Depreciation__c', true); //enforceFLS=true, running in user mode
		soql.addFields(new set<string>{
			'Id','name','depreciation_amount__c','depreciation_date__c','depreciation_type__c','gl_date__c','finalized__c','fixed_asset__c',
			'fixed_asset__r.name','fixed_asset__r.gl_account__c'
		});
		soql.setWhereClause('Fixed_Asset__r.company__c = :selectedCompanyId'+
							' AND Fixed_Asset__r.tax_book__c = :selectedBookId'+
							' AND id not in (Select Fixed_Asset_Depreciation__c from Accounting_Entry__c where void__c = false  and Period_Status__c = \'Closed\')');
		soql.setOrderByClause('fixed_asset__r.name asc, depreciation_date__c desc');
		fadStandardSetController = new ApexPages.StandardSetController(Database.getQueryLocator(soql.getQuery()));

		if(fadStandardSetController.getRecords().size() == 0){
			disableRollback = true;
			fadStandardSetController.setPageSize(pageSize);
			ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.WARNING, Label.No_depreciation_records_for_rollback));
		}else{
			disableRollback = false;
		}
	}
	
	public void updateCompanyBookOptions(){
		mTaxBooks = new Map<Id, List<SelectOption>>();
		companyOptions = new List<SelectOption>();

		//KNDY-10473: Adding CRUD/FLS checks with SOQLUtil
		SOQLUtil soql = new SOQLUtil('Tax_Book__c', true); //enforceFLS=true, running in user mode
		soql.addFields(new set<string>{
			'Id','name','company__c','company__r.name','active__c'
		});
		soql.setWhereClause('active__c = true');
		soql.setOrderByClause('company__r.name, name');
		List<Tax_Book__c> taxBooks = Database.query(soql.getQuery());

		for(Tax_Book__c tb : taxBooks){
			if(mTaxBooks.containsKey(tb.company__c)){
				mTaxBooks.get(tb.company__c).add(new SelectOption(tb.Id, tb.name));
			}else if(tb.company__c != null){
				companyOptions.add(new SelectOption(tb.company__c, tb.company__r.name));
				mTaxBooks.put(tb.company__c, new List<SelectOption>{new SelectOption('', '- Select One -'), new SelectOption(tb.Id, tb.name)});
			}
		}
		//if(companyOptions.size() == 1){
			selectedCompanyId = companyOptions[0].getValue();
		//}
	}
	
	public List<SelectOption> getTaxBookOptions(){
		if(mTaxBooks.containsKey(selectedCompanyId)){
			return mTaxBooks.get(selectedCompanyId);
		}else{
			ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.WARNING, Label.Could_not_find_active_tax_books));
			return new List<SelectOption>();			
		}
	}
	
	public List<Fixed_Asset_Depreciation__c> getFixedAssetDepreciations(){
		if(fadStandardSetController == null){
			return new List<Fixed_Asset_Depreciation__c>();	
		}else{
			return fadStandardSetController.getRecords();
		}
	}
	
	/* pagination controls and flags */
	public integer getPageNumber(){
		return fadStandardSetController.getPageNumber();
	}
	
	public boolean getHasNext(){
		return fadStandardSetController.getHasNext();
	}
	
	public boolean getHasPrevious(){
		return fadStandardSetController.getHasPrevious();
	}
	
	public integer getNumberOfPages(){
		decimal noPages = (decimal)fadStandardSetController.getResultSize();
		noPages = noPages.divide(pageSize,0, System.RoundingMode.UP);
		return (integer)noPages;
	}
	
	public void first(){
		fadStandardSetController.first();
	}
	
	public void previous(){
		fadStandardSetController.previous();
	}
	
	public void next(){
		fadStandardSetController.next();
	}
	
	public void last(){
		fadStandardSetController.last();
	}
	
	public void btn_Rollback(){
		try{
			database.executeBatch(new FixedAssetDepreciationRollbackBatch(new Set<Id>{companyController.getId()}));
			disableRollback = true;
			ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.CONFIRM, Label.Batch_job_initiated));
		}catch(Exception ex){
			ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.Error, Label.Batch_job_could_not_be_started));
		}
	}
	public pageReference cancel(){
		return Page.FixedAssetWorkbench;
	} 
}