src-ken&y/objects/Accounting_Default__c.object
<CustomObject>
    <customHelpPage>HelpAccountingDefaults</customHelpPage>
    <description>The default values for document lines, used to hold accounting segments for the COA</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Accounting Defaults</relationshipLabel>
        <relationshipName>Accounting_Defaults</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GL_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The default general ledger account.</description>
        <label>GL Account</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The GL account that you selected is inactive. Select an active GL account.</errorMessage>
            <filterItems>
                <field>GL_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>GL_Account__c</referenceTo>
        <relationshipLabel>Accounting Defaults</relationshipLabel>
        <relationshipName>Accounting_Defaults</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Accounting Default</label>
    <nameField>
        <displayFormat>AD-{0000000000}</displayFormat>
        <label>Accounting Default</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounting Defaults</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Bin__c.object
<CustomObject>
    <customHelpPage>HelpBins</customHelpPage>
    <description>Bin is a sub-level of location</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Descriptive information about the bin.</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Bin</label>
    <nameField>
        <label>Bin</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bins</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Company__c.object
<CustomObject>
    <customHelpPage>HelpCompany</customHelpPage>
    <description>Each Logistics or Financial entity will be represented by a single Company record.  Master data for the Company is recorded here and used throughout the System.</description>
    <fields>
        <fullName>Comp_Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Companies</relationshipLabel>
        <relationshipName>Companies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Consol_Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Consolidation Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Companies (Consolidation Currency)</relationshipLabel>
        <relationshipName>Consol_Currency</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Default_Transaction_Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Default Transaction Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Companies (Default Transaction Currency)</relationshipLabel>
        <relationshipName>Default_Transaction_Currency</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stat_Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Statutory Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Companies (Statutory Currency)</relationshipLabel>
        <relationshipName>Stat_Currency</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subs_Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subsidiary Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Companies (Subsidiary Currency)</relationshipLabel>
        <relationshipName>Subs_Currency</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Exchange_Rate__c.object
<CustomObject>
    <customHelpPage>HelpExchangeRates</customHelpPage>
    <description>Record the time snap shot of currency exchange rate that will be used for new records created.  Serves as a historical record of past rates</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox Active to perform check if the currency exchange rate is active or not</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Daily_Monthly__c</fullName>
        <description>To distinguish the Daily rate and Monthly rate</description>
        <inlineHelpText>Specifies whether the rate is used daily or monthly.</inlineHelpText>
        <label>Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Daily</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Exchange_Rate_Type__c</fullName>
        <description>Exchange rate type</description>
        <label>Exchange Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Corporate</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>From_Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>From Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Exchange Rates</relationshipLabel>
        <relationshipName>Exchange_Rates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Multiplier_Exchange_Rate__c</fullName>
        <description>Multiplier exchange rate ex. Currency From = USD and Currency to = EUR and multiplier exchange rate = 0.7714 10 USD = 10 *  0.7714 = 7.7143 USD</description>
        <inlineHelpText>The multiplier value that determines of the &quot;To&quot; currency.  For example, Currency From = USD, Currency To = EUR, and multiplier exchange rate = 0.7714. So, 10 USD = 10 * 0.7714 = 7.7143 EUR.</inlineHelpText>
        <label>Multiplier Exchange Rate</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rate_End_DateTime__c</fullName>
        <inlineHelpText>Date and time the rate expires.</inlineHelpText>
        <label>Rate End DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Rate_Start_DateTime__c</fullName>
        <inlineHelpText>Date and time the rate takes effect.</inlineHelpText>
        <label>Rate Start DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>To_Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>To Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Exchange Rates (To Currency)</relationshipLabel>
        <relationshipName>Exchange_Rates1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Exchange Rate</label>
    <nameField>
        <label>Exchange Rate</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exchange Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/GL_Account__c.object
<CustomObject>
    <customHelpPage>HelpGLAccount</customHelpPage>
    <description>Table of acceptable General Ledger Numbers or Names with associated Cross Reference Information</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Select box if GL account is active</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description or reference information for GL account</description>
        <label>Description</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>GL Account</label>
    <nameField>
        <label>GL Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Item__c.object
<CustomObject>
    <customHelpPage>HelpItems</customHelpPage>
    <description>Item Master object</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Active Item if checked; Used to phase out a item. If item is inactive, a P.O. or W.O. can not be placed against item but the QOH can be used.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company that controls this item</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Item description can be up to 255 characters; use extended description field if needed</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Location__c.object
<CustomObject>
    <customHelpPage>HelpLocations</customHelpPage>
    <description>Organizational Unit or physical location primarily used if  subclassification reporting is desired</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Location description</description>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Pricebook__c.object
<CustomObject>
    <customHelpPage>HelpPricebooks</customHelpPage>
    <description>List prices for a company and the products it sells</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The company that this pricebook belongs to</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Pricebooks</relationshipLabel>
        <relationshipName>Pricebooks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Details about this pricebook</description>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Pricebook</label>
    <nameField>
        <label>Pricebook Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricebooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/UOM__c.object
<CustomObject>
    <customHelpPage>HelpUOM</customHelpPage>
    <description>Units of Measure.</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of UOM</description>
        <label>Description</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>UOM</label>
    <nameField>
        <label>UOM</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UOMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/User_Preference__c.object
<CustomObject>
    <customHelpPage>HelpUserPreference</customHelpPage>
    <description>Track individual user preferences or configurations</description>
    <fields>
        <fullName>Accounting_Default__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Default segment values for chart of accounts values.</description>
        <inlineHelpText>Default segment values for chart of accounts values.</inlineHelpText>
        <label>Accounting Default</label>
        <referenceTo>Accounting_Default__c</referenceTo>
        <relationshipLabel>User Preferences</relationshipLabel>
        <relationshipName>User_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Default_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The company that is used to default on new orders</description>
        <label>Default Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>User Preferences</relationshipLabel>
        <relationshipName>User_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Default_Facility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Facility</description>
        <inlineHelpText>The default company facility to which a user belongs. This controls access to inventory transfer and inventory change records.</inlineHelpText>
        <label>Default Facility</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Default Facility does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>Facility__c.Company__c</field>
                <operation>equals</operation>
                <valueField>$Source.Default_Company__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Facility__c</referenceTo>
        <relationshipLabel>User Preferences</relationshipLabel>
        <relationshipName>User_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Preference</label>
    <nameField>
        <label>User Preference Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Preferences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/TestData_Extension.cls
@isTest
public class TestData_Extension {
    public static String uniqueString () { return String.valueOf(System.currentTimeMillis()); }
    public testdata td = new testdata();
    
    public Exchange_Rate__c CADUSDExchangeRate = new Exchange_Rate__c(); {
    	
    	CADUSDExchangeRate.From_Currency__c = TestFuel.currencyCAD.id;
    	CADUSDExchangeRate.To_Currency__c = TestFuel.currencyUSD.id;
    	CADUSDExchangeRate.Daily_Monthly__c = 'Daily';
    	CADUSDExchangeRate.Exchange_Rate_Type__c = 'Corporate';
    	CADUSDExchangeRate.Multiplier_Exchange_Rate__c = 1;
    	CADUSDExchangeRate.Active__c = true;
    	CADUSDExchangeRate.Rate_Start_DateTime__c = system.now() - 1 ;
    	CADUSDExchangeRate.Rate_End_DateTime__c = system.now() + 1;
    	
    	insert CADUSDExchangeRate;
    	
    }
    
    public Exchange_Rate__c CADEURExchangeRate = new Exchange_Rate__c(); {
    	
    	CADEURExchangeRate.From_Currency__c = TestFuel.currencyCAD.id;
    	CADEURExchangeRate.To_Currency__c = TestFuel.currencyEUR.id;
    	CADEURExchangeRate.Daily_Monthly__c = 'Daily';
    	CADEURExchangeRate.Exchange_Rate_Type__c = 'Corporate';
    	CADEURExchangeRate.Multiplier_Exchange_Rate__c = 1;
    	CADEURExchangeRate.Active__c = true;
    	CADEURExchangeRate.Rate_Start_DateTime__c = system.now() - 1;
    	CADEURExchangeRate.Rate_End_DateTime__c = system.now() + 1;
    	
    	insert CADEURExchangeRate;
    	
    }
       
    public Exchange_Rate__c ExchangeRate = new Exchange_Rate__c(); {
    	
    	ExchangeRate.From_Currency__c = TestFuel.currencyUSD.id;
    	ExchangeRate.To_Currency__c = TestFuel.currencyUSD.id;
    	ExchangeRate.Daily_Monthly__c = 'Daily';
    	ExchangeRate.Exchange_Rate_Type__c = 'Corporate';
    	ExchangeRate.Multiplier_Exchange_Rate__c = 1;
    	ExchangeRate.Active__c = true;
    	ExchangeRate.Rate_Start_DateTime__c = system.now() - 1;
    	ExchangeRate.Rate_End_DateTime__c = system.now() + 1;
    	
    	insert ExchangeRate;
    	
    }
    
    public Exchange_Rate__c ExchangeRate1 = new Exchange_Rate__c(); {
    	
    	ExchangeRate1.From_Currency__c = TestFuel.currencyUSD.id;
    	ExchangeRate1.To_Currency__c = TestFuel.currencyEUR.id;
    	ExchangeRate1.Daily_Monthly__c = 'Daily';
    	ExchangeRate1.Exchange_Rate_Type__c = 'Corporate';
    	ExchangeRate1.Multiplier_Exchange_Rate__c = 1;
    	ExchangeRate1.Active__c = true;
    	ExchangeRate1.Rate_Start_DateTime__c = system.now() - 1;
    	ExchangeRate1.Rate_End_DateTime__c = system.now() + 1;
    	
    	insert ExchangeRate1;
    	
    }
       
    public Company__c company = new Company__c();{
        company = td.company;
        company.Comp_Currency__c = TestFuel.currencySGD.id;
        company.Consol_Currency__c = TestFuel.currencyEUR.id;
        company.Stat_Currency__c = TestFuel.currencyGBP.id;
        company.Subs_Currency__c = TestFuel.currencyUSD.id;
        company.Default_Transaction_Currency__c = TestFuel.currencyUSD.id;        
    }
    
    public Accounting_Default__c accDef = new Accounting_Default__c();{
        accDef.Company__c = td.company.id;
        accDef.GL_Account__c = td.AcctData.CashGL.id;
        insert accDef;
    }
    
    public User_Preference__c userinfo = new User_Preference__c();{
        // Company
        userinfo.Default_Company__c = td.company.id;
        userinfo.Accounting_Default__c = accDef.id;
        userinfo.Default_Facility__c = td.facility.id;
        insert userinfo;
    }
    
    public UOM__c uom = new UOM__c();{
        uom.name = 'EA' + uniquestring();
        insert uom;
    }
    
    public Item__c Item = new Item__c(); {
        Item.name = 'Catalog Item '+ uniquestring();
        Item.description__c = 'test catalog item';
        Item.source__c = 'Miscellaneous';
        Item.Non_Inventory__c = true;
        Item.Purchasing_UOM__c = UOM.id;
        insert Item;     
    }
    
    // Test to see all above elements can be inserted correctly
    public static testMethod void t1() {
        testdata_extension td_ext = new testdata_extension();
        system.assert( td_ext != null ); 
    }
    
    public static testMethod void checkBinUniqueness(){
        TestData globalTestData = new TestData();
        update new Location__c(id = globalTestData.location.Id ,Bin_Tracked__c = true );
        Bin__c originalBin = new Bin__c(
                            Name = 'Bin 1',
                            Location__c = globalTestData.location.Id);
        insert originalBin;
        
        Bin__c duplicateBin = new Bin__c(
                            Name = 'Bin 1',
                            Location__c = globalTestData.location.Id);
        try{
            insert duplicateBin;
            system.assert(false, 'Duplicate bin creation did not fail.');
        }catch(Exception e){
            system.assert(duplicateBin.Id == null);
        }
    }
    
    public static testMethod void checkPricebookUniqueness(){
        TestData globalTestData = new TestData();
        
        Pricebook__c originalPricebook = new Pricebook__c(
                            Name = 'Pricebook 1',
                            Company__c = globalTestData.company.Id);
        insert originalPricebook;
        
        Pricebook__c duplicatePricebook = new Pricebook__c(
                            Name = 'Pricebook 1',
                            Company__c = globalTestData.company.Id);
        try{
            insert duplicatePricebook;
            system.assert(false, 'Duplicate Pricebook creation did not fail.');
        }catch(Exception e){
            system.assert(duplicatePricebook.Id == null);
        }
    }
    
    public static testMethod void gridTileCon_test() { 
        gridTileCon con = new gridTileCon(); 
        con.token = 'Account';
        con.titleSTR = 'address';
        system.assertEquals( '/001', con.hrefURL);
        system.assertNotEquals( null, con.labelPlural);
        system.assertEquals( 'Account', con.className);
    }
    
}