src-ken&y/objects/Accounting_Entry__c.object
<CustomObject>
    <customHelpPage>HelpAccountingEntries</customHelpPage>
    <description>Accounting Entry Header records</description>
    <fields>
        <fullName>Fixed_Asset_Adjustment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Fixed Asset Adjustment</label>
        <referenceTo>Fixed_Asset_Adjustment__c</referenceTo>
        <relationshipLabel>Accounting Entries</relationshipLabel>
        <relationshipName>Accounting_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Has_Exceptions__c</fullName>
        <formula>OR(
Exceptions_Count__c &gt; 0,
Line_Exceptions__c &gt; 0
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Has Exceptions</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reversed_Journal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The journal containing the reverse entries</description>
        <label>Reversed Accounting Entry</label>
        <referenceTo>Accounting_Entry__c</referenceTo>
        <relationshipLabel>Accounting Entries</relationshipLabel>
        <relationshipName>Accounting_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supplier_Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Supplier invoice</description>
        <label>Supplier Invoice</label>
        <referenceTo>Supplier_Invoice__c</referenceTo>
        <relationshipLabel>Accounting Entries</relationshipLabel>
        <relationshipName>Accounting_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier_Payment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Supplier payment</description>
        <label>Supplier Payment</label>
        <referenceTo>Supplier_Payment__c</referenceTo>
        <relationshipLabel>Accounting Entries</relationshipLabel>
        <relationshipName>Accounting_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Void__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This check box is selected when the entry is successfully Voided</description>
        <label>Void</label>
        <type>Checkbox</type>
    </fields>
    <label>Accounting Entry</label>
    <nameField>
        <label>Accounting Entry</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Fixed_Asset_Adjustment__c.object
<CustomObject>
    <customHelpPage>HelpFixedAssets</customHelpPage>
    <description>Stores the value of all the costs associated with this asset throughout it&apos;s acquistion and lifecycle.</description>
    <fields>
        <fullName>Supplier_Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Supplier Invoice</description>
        <label>Supplier Invoice</label>
        <referenceTo>Supplier_Invoice__c</referenceTo>
        <relationshipLabel>Fixed Asset Adjustments</relationshipLabel>
        <relationshipName>Fixed_Asset_Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Fixed Asset Adjustment</label>
    <nameField>
        <label>Fixed Asset Adjustment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fixed Asset Adjustments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Supplier_Invoice__c.object
<CustomObject>
    <customHelpPage>HelpSupplierInvoice</customHelpPage>
    <description>Record invoices for items or services  that are received from a supplier.  Bills can be recorded with or without purchase orders</description>
    <fields>
        <fullName>Apply_to_Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Apply to Invoice</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select an invoice that matches the supplier on the credit memo</errorMessage>
            <filterItems>
                <field>Supplier_Invoice__c.Supplier__c</field>
                <operation>equals</operation>
                <valueField>$Source.Supplier__c</valueField>
            </filterItems>
            <filterItems>
                <field>Supplier_Invoice__c.Invoice_Type__c</field>
                <operation>notEqual</operation>
                <value>Credit Memo</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Supplier_Invoice__c</referenceTo>
        <relationshipLabel>Supplier Invoices</relationshipLabel>
        <relationshipName>Credit_Memos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Has_Exceptions__c</fullName>
        <formula>Exceptions_Count__c &gt; 0</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Has Exceptions</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of bill</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supplier_Invoice__c</fullName>
        <description>Supplier invoice no. reference</description>
        <label>Invoice Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Void__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Void</label>
        <type>Checkbox</type>
    </fields>
    <label>Supplier Invoice</label>
    <nameField>
        <label>Supplier Invoice</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Supplier_Payment__c.object
<CustomObject>
    <customHelpPage>HelpSupplierPayments</customHelpPage>
    <description>Pay supplier invoices</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of transaction</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Unapproved</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Wire request submitted, payment pending</fullName>
                </value>
                <value>
                    <fullName>Wire request submitted, payment confirmed</fullName>
                </value>
                <value>
                    <fullName>Void payment</fullName>
                </value>
                <value>
                    <fullName>Paid and reconciled</fullName>
                </value>
                <value>
                    <fullName>Unreconciled</fullName>
                </value>
                <value>
                    <fullName>Applied</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Void__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Void</label>
        <type>Checkbox</type>
    </fields>
    <label>Supplier Payment</label>
    <nameField>
        <label>Supplier Payment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Supplier_Payment_Line__c.object
<CustomObject>
    <customHelpPage>HelpSupplierPayments</customHelpPage>
    <description>Payment details associated with a payment received or issued</description>
    <fields>
        <fullName>Credit_Memo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Credit Memo</label>
        <referenceTo>Supplier_Invoice__c</referenceTo>
        <relationshipName>Supplier_Payment_Lines1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier_Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier Invoice</label>
        <referenceTo>Supplier_Invoice__c</referenceTo>
        <relationshipLabel>Supplier Payment Lines (Supplier Invoice)</relationshipLabel>
        <relationshipName>Supplier_Payment_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier_Payment__c</fullName>
        <label>Supplier Payment</label>
        <referenceTo>Supplier_Payment__c</referenceTo>
        <relationshipName>Supplier_Payment_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Supplier Payment Line</label>
    <nameField>
        <label>Supplier Payment Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier Payment Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/classes/SupplierInvoiceVoidCancelService.cls
public with sharing class SupplierInvoiceVoidCancelService extends VoidCancelService{

    public SupplierInvoiceVoidCancelService(List<Supplier_Invoice__c> supplierInvoices){
    	super(supplierInvoices);  
    }
    
    public SupplierInvoiceVoidCancelService(){
    }
    
    
    
    public override Map<Id, VoidCancelService.VoidCancelDetail> getBusinessVoidCancelDetails(List<sObject> sObjRecs){
    	Map<Id, VoidCancelService.VoidCancelDetail> mBusinessVoidCancelDetails = new Map<Id, VoidCancelService.VoidCancelDetail>();
    	Set<Id> sourceDocIds = new Set<Id>();
    	for(sObject sObj : sObjRecs) {
    		sourceDocIds.add(sObj.Id);
    	}
    	
		//KNDY-10473: Adding CRUD/FLS checks with SOQLUtil
		
		SOQLUtil soql = new SOQLUtil('Supplier_Invoice__c', true); //enforceFLS=true, running in user mode
		soql.addFields(new set<string>{
			'Id','Name','Status__c','Void__c'
		});
		soql.setWhereClause('Id IN :sourceDocIds');
		
		SOQLUtil.ChildRelationship childRel1 = new SOQLUtil.ChildRelationship(soql, 'Supplier_Payment_Lines__r');
		childRel1.addFields(new set<string>{
			'Id'
		});
		childRel1.setWhereClause('Supplier_Payment__r.Status__c != \'Void\' AND Supplier_Payment__r.Status__c != \'Cancel\' AND Supplier_Payment__r.Void__c = false');
		soql.addChildRelationship(childRel1);
		
		SOQLUtil.ChildRelationship childRel2 = new SOQLUtil.ChildRelationship(soql, 'Supplier_Payment_Lines1__r');
		childRel2.addFields(new set<string>{
			'Id'
		});
		childRel2.setWhereClause('Supplier_Payment__r.Status__c != \'Void\' AND Supplier_Payment__r.Status__c != \'Cancel\' AND Supplier_Payment__r.Void__c = false');
		soql.addChildRelationship(childRel2);
		
		SOQLUtil.ChildRelationship childRel3 = new SOQLUtil.ChildRelationship(soql, 'Credit_Memos__r');
		childRel3.addFields(new set<string>{
			'Id'
		});
		childRel3.setWhereClause('Status__c != \'Void\' AND Status__c != \'Cancel\' AND Void__c = false');
		soql.addChildRelationship(childRel3);
		
		SOQLUtil.ChildRelationship childRel4 = new SOQLUtil.ChildRelationship(soql, 'Fixed_Asset_Adjustments__r');
		childRel4.addFields(new set<string>{
			'Id'
		});
		soql.addChildRelationship(childRel4);
		
		SOQLUtil.ChildRelationship childRel5 = new SOQLUtil.ChildRelationship(soql, 'Accounting_Entries__r');
		childRel5.addFields(new set<string>{
			'id','name'
		});
		childRel5.setWhereClause('status__c = \'Active\' and Has_Exceptions__c != true');
		soql.addChildRelationship(childRel5);

		List<Supplier_Invoice__c> sourceDocumentChildren = Database.query(soql.getQuery());
		
		for(Supplier_Invoice__c si : sourceDocumentChildren) {
			VoidCancelDetail iVCD = new VoidCancelDetail();
            iVCD.recordId = si.Id;
            iVCD.recordName = si.Name;
            iVCD.isVoidable = true;
            iVCD.isCancellable = true;
            iVCD.voidMessages = new List<string>();
            iVCD.cancelMessages = new List<string>();
            list<Accounting_Entry__c> aelist = si.Accounting_Entries__r;
            
            
            
            if(si.Void__c) {
				//iVCD.voidMessages.add('Cannot Void, this Supplier Invoice is already Void');
				iVCD.cancelMessages.add('Cannot Cancel, this Supplier Invoice is already Void');
			}
			if(si.Status__c == 'Cancelled') {
				iVCD.voidMessages.add('Cannot Void, this Supplier Invoice is already Cancelled');
				//iVCD.cancelMessages.add('Cannot Cancel, this Supplier Invoice is already Cancelled');
			}
			if(si.Supplier_Payment_Lines__r != null && si.Supplier_Payment_Lines__r.size() > 0) {
				iVCD.voidMessages.add('Cannot Void, this Supplier Invoice is referenced in one or more Supplier Payments');
				iVCD.cancelMessages.add('Cannot Cancel, this Supplier Invoice is referenced in one or more Supplier Payments');
			}
			if(si.Supplier_Payment_Lines1__r != null && si.Supplier_Payment_Lines1__r.size() > 0) {
				iVCD.voidMessages.add('Cannot Void, this Supplier Invoice is referenced in one or more Supplier Payments');
				iVCD.cancelMessages.add('Cannot Cancel, this Supplier Invoice is referenced in one or more Supplier Payments');
			}
			if(si.Credit_Memos__r != null && si.Credit_Memos__r.size() > 0) {
				iVCD.voidMessages.add('Cannot Void, this Supplier Invoice is referenced in one or more Credit Memos');
				iVCD.cancelMessages.add('Cannot Cancel, this Supplier Invoice is referenced in one or more Credit Memos');
			}
			if(si.Fixed_Asset_Adjustments__r != null && si.Fixed_Asset_Adjustments__r.size() > 0) {
				iVCD.voidMessages.add('Cannot Void, this Supplier Invoice is referenced in one or more Fixed Asset Adjustments');
				iVCD.cancelMessages.add('Cannot Cancel, this Supplier Invoice is referenced in one or more Fixed Asset Adjustments');
			}
			
	    	if(!(aelist.size()> 0)){
				iVCD.voidMessages.add('Cannot Void, this Supplier Invoice does not have Accounting Entry generated or have Exceptions');
			}
			if(iVCD.voidMessages.size() > 0) {
				iVCD.isVoidable = false;
			}
			if(iVCD.cancelMessages.size() > 0) {
				iVCD.isCancellable = false;
			}
			
			mBusinessVoidCancelDetails.put(si.Id, iVCD);
		}
        system.debug(logginglevel.error,'mBusinessVoidCancelDetails--->'+mBusinessVoidCancelDetails);
    	return mBusinessVoidCancelDetails; 
    }
    
    public override Map<Id, VoidCancelService.VoidCancelResponse> businessVoid(List<sObject> sObjRecs){
    	Map<Id, VoidCancelService.VoidCancelResponse> mResponses = new Map<Id, VoidCancelService.VoidCancelResponse>();
		
    	for(sObject sObj : sObjRecs){
    		//Business Process Logic
    		
    		List<String> messages = new List<String>{'Successfully Voided!'};	
    		mResponses.put(sObj.Id, new VoidCancelService.VoidCancelResponse(sObj.Id, (string)sObj.get('Name'), true, messages, VoidCancelService.Action.VOIDDOC));
    	}
    	
    	return mResponses;
    }
    

	public override Map<Id, VoidCancelService.VoidCancelResponse> businessCancel(List<sObject> sObjRecs){
    	Map<Id, VoidCancelService.VoidCancelResponse> mResponses = new Map<Id, VoidCancelService.VoidCancelResponse>();

    	for(sObject sObj : sObjRecs){
    		//Business Process Logic
    		List<String> messages = new List<String>{'Successfully Cancelled!'};
    		mResponses.put(sObj.Id, new VoidCancelService.VoidCancelResponse(sObj.Id, (string)sObj.get('Name'), true, messages, VoidCancelService.Action.CANCELDOC));
    	}
    	
    	return mResponses;
    }

}