src-ken&y/objects/Accounting_Entry__c.object
<CustomObject>
    <customHelpPage>HelpAccountingEntries</customHelpPage>
    <description>Accounting Entry Header records</description>
    <fields>
        <fullName>Bank_Transaction_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bank Transaction Group</label>
        <referenceTo>Bank_Transaction_Group__c</referenceTo>
        <relationshipLabel>Accounting Entries</relationshipLabel>
        <relationshipName>Accounting_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Accounting Entries</relationshipLabel>
        <relationshipName>Accounting_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exceptions_Count__c</fullName>
        <label>Exceptions Count</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Finalized_Date__c</fullName>
        <description>Finalized Date for the associated source document.</description>
        <label>Finalized Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Has_Exceptions__c</fullName>
        <formula>OR(
Exceptions_Count__c &gt; 0,
Line_Exceptions__c &gt; 0
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Has Exceptions</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Posting_Date__c</fullName>
        <label>Posting Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Reversed_Journal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The journal containing the reverse entries</description>
        <label>Reversed Accounting Entry</label>
        <referenceTo>Accounting_Entry__c</referenceTo>
        <relationshipLabel>Accounting Entries</relationshipLabel>
        <relationshipName>Accounting_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <description>Transaction date for the associated source document.</description>
        <label>Transaction Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Void__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This check box is selected when the entry is successfully Voided</description>
        <label>Void</label>
        <type>Checkbox</type>
    </fields>
    <label>Accounting Entry</label>
    <nameField>
        <label>Accounting Entry</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Bank_Transaction__c.object
<CustomObject>
    <customHelpPage>HelpManageBankTransactions</customHelpPage>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Amount received or paid (in bank account currency; may have been converted by bank)</description>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Bank_Transaction_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Bank transaction group for bank transactions</description>
        <label>Bank Transaction Group</label>
        <referenceTo>Bank_Transaction_Group__c</referenceTo>
        <relationshipLabel>Bank Transactions</relationshipLabel>
        <relationshipName>Bank_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Bank Transactions</relationshipLabel>
        <relationshipName>Bank_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exceptions_Count__c</fullName>
        <label>Exceptions Count</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Finalized_2__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Finalized</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Finalized__c</fullName>
        <formula>Bank_Transaction_Group__r.Finalized__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Finalized</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Exceptions__c</fullName>
        <formula>Exceptions_Count__c &gt; 0</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Has Exceptions</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Historical__c</fullName>
        <formula>Bank_Transaction_Group__r.Historical__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Historical</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Match_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Match Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <description>The type of activity in the account.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACH</fullName>
                </value>
                <value>
                    <fullName>Check</fullName>
                </value>
                <value>
                    <fullName>Wire</fullName>
                </value>
                <value>
                    <fullName>EFT</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
                <value>
                    <fullName>Deposit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reconciled_Hidden__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reconciled Hidden</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reference_Number__c</fullName>
        <description>Check Number, etc</description>
        <label>Reference Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>TEXT(Bank_Transaction_Group__r.Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <description>Date/time transaction cleared bank</description>
        <label>Transaction Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Void_Date__c</fullName>
        <formula>Bank_Transaction_Group__r.Void_Date__c</formula>
        <label>Void Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Void__c</fullName>
        <formula>Bank_Transaction_Group__r.Void__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Void</label>
        <type>Checkbox</type>
    </fields>
    <label>Bank Transaction</label>
    <nameField>
        <label>Bank Transaction</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Bank_Transaction_Group__c.object
<CustomObject>
    <customHelpPage>HelpManageBankTransactions</customHelpPage>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Bank Transaction Groups</relationshipLabel>
        <relationshipName>Bank_Transaction_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exceptions_Count__c</fullName>
        <label>Exceptions Count</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Finalized_Date__c</fullName>
        <description>Date bank transaction group was finalized</description>
        <label>Finalized Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Finalized__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag indicating finalized</description>
        <label>Finalized</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Exceptions__c</fullName>
        <formula>OR(

Exceptions_Count__c &gt; 0,

Line_Exceptions__c &gt; 0

)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Has Exceptions</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Historical__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Historical</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Posting_Date__c</fullName>
        <label>Posting Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <label>Transaction Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Void_Date__c</fullName>
        <label>Void Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Void__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Void</label>
        <type>Checkbox</type>
    </fields>
    <label>Bank Transaction Group</label>
    <nameField>
        <label>Bank Transaction Group</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Transaction Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Company__c.object
<CustomObject>
    <customHelpPage>HelpCompany</customHelpPage>
    <description>Each Logistics or Financial entity will be represented by a single Company record.  Master data for the Company is recorded here and used throughout the System.</description>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Payment_Method__c.object
<CustomObject>
    <customHelpPage>HelpProcessCreditCardPayments</customHelpPage>
    <label>Payment Method</label>
    <nameField>
        <label>Payment Method</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/BankTransactionVoidCancelExt.cls
public with sharing class BankTransactionVoidCancelExt extends VoidCancelBaseExt{
    public VoidCancelService voidCancelSvc {get;private set;}
    public Apexpages.Standardcontroller con {get;set;}
    ApexPages.StandardSetController setcon;
    
    public Bank_Transaction_Group__c btg{get;set;}{
        btg = new Bank_Transaction_Group__c();
        btg.Void_Date__c = system.now();    
    }
    public Bank_Transaction__c bt{get;set;}
    public static list<Bank_Transaction__c> lstBT{get;set;}
    public list<Bank_Transaction_Group__c>lstBTG{get;set;}
    
    public String lstBTJson{get{
        return JSON.serialize(lstBT);}}
    public string namespace {get;set;}
    
    public BankTransactionVoidCancelExt(Apexpages.Standardcontroller controller)
    {
        this.con = controller;
        this.namespace = KSE.NamespaceUU;
        list<Id> btIds = new list<Id>(); // contains only one record
        btIds.add(con.getId());
        
        lstBT = new list<Bank_Transaction__c>();
        system.debug(logginglevel.error,'controller:' + controller + 'con.getId() :' + con.getId());
        
        SOQLUtil soql = new SOQLUtil('Bank_Transaction__c', TRUE);
        soql.addFields(new Set<String>{'Id','Name','Finalized_2__c','Transaction_Date__c', 'Bank_Transaction_Group__c',
              'Bank_Transaction_Group__r.Finalized_Date__c','Bank_Transaction_Group__r.Posting_Date__c',
              'Bank_Transaction_Group__r.Void__c' , 'Bank_Transaction_Group__r.Status__c', 'Bank_Transaction_Group__r.Void_Date__c',
              'Historical__c' ,'company__c','Match_Approved__c' ,'Reconciled_Hidden__c' ,'Amount__c'
              ,'Payment_Method__c','Reference_Number__c'});
        soql.setWhereClause('id in :btIds');
        lstBT = database.query(soql.getQuery());
        System.debug(logginglevel.error,'lstBT--->'+lstBT);
              
        lstBTG = new list<Bank_Transaction_Group__c>();
        list<Id> btgIds = new list<Id>();
        btgIds.add(lstBT[0].Bank_Transaction_Group__c);
        
        soql = new SOQLUtil('Bank_Transaction_Group__c', TRUE);
        soql.addFields(new Set<String>{'Id', 'Company__c', 'Exceptions_Count__c', 'Finalized__c',
              'Finalized_Date__c', 'Transaction_Date__c', 'Posting_Date__c', 'Void__c', 'Void_Date__c', 'Status__c', 'Historical__c', 'Name'});
        soql.setWhereClause('id in :btgIds');
        lstBTG = database.query(soql.getQuery());                                 
        btg  = lstBTG[0];
        System.debug(logginglevel.error,'btg--->'+btg);  
        
          voidCancelSvc = new BankTransactionVoidCancelService(new List<sObject>{btg}); //Calling from UI
    }
    // standard set controller constructor for list view page	
    public BankTransactionVoidCancelExt(Apexpages.standardsetcontroller controller) {
        this.setcon = controller;
         list<Bank_Transaction__c> btCon = setcon.getSelected();
        lstBT = new list<Bank_Transaction__c>();
        
            SOQLUtil soql = new SOQLUtil('Bank_Transaction__c', TRUE);
            soql.addFields('Match_Bank_Transactions_Columns');
            soql.addFields(new Set<String>{'Id','Name','Finalized_2__c','Transaction_Date__c', 'Bank_Transaction_Group__c',
                  'Bank_Transaction_Group__r.Finalized_Date__c','Bank_Transaction_Group__r.Posting_Date__c',
                  'Historical__c' ,'company__c','Match_Approved__c' ,'Reconciled_Hidden__c' ,'Amount__c'
                  ,'Payment_Method__c','Reference_Number__c'});
            soql.setWhereClause('id in :btCon');
        lstBT = database.query(soql.getQuery());
    } 
    public void pageMessages( string msg , String severityLevel) {
        system.debug('msg: ' + msg + ' - sev: ' + severityLevel);
        msg = MessageUtil.toFriendlyErrorMessage(msg);
        if(severityLevel.equalsIgnoreCase('FATAL')){
            ApexPages.addMessage( new ApexPages.Message( ApexPages.severity.FATAL,msg));
        }else if(severityLevel.equalsIgnoreCase('ERROR')){
            ApexPages.addMessage( new ApexPages.Message( ApexPages.severity.ERROR,msg));
        }else if(severityLevel.equalsIgnoreCase('WARNING') ){
            ApexPages.addMessage( new ApexPages.Message( ApexPages.severity.WARNING,msg));
        }else if(severityLevel.equalsIgnoreCase('INFO') ){
            ApexPages.addMessage( new ApexPages.Message( ApexPages.severity.INFO,msg));
        }
    }
    
    
  
    public boolean getDisableVoid(){
        if(voidCancelSvc.getVoidCancelDetails()==null || lstBT == null) return false;
		return !voidCancelSvc.getVoidCancelDetails().get(lstBT[0].bank_Transaction_Group__c).isVoidable;
	}
    
	public boolean getDisableCancel(){
        if(voidCancelSvc.getVoidCancelDetails()==null || lstBT == null) return false;
        
		return !voidCancelSvc.getVoidCancelDetails().get(lstBT[0].bank_Transaction_Group__c).isCancellable;
	}
	
	public VoidCancelService.VoidCancelDetail getVoidCancelDetails(){
		return voidCancelSvc.getVoidCancelDetails().get(lstBT[0].bank_Transaction_Group__c);
	}
    
    public List<string> getVoidDetails(){
        List<String> voidMessages = new List<String>();
        map<String,string> mapBTGNameAndBTName = new map<String,string>();
        if (lstBT==null) return null;
          List<Bank_Transaction__c>   lstQueriedBT = [Select Id, Name, Bank_Transaction_Group__c, Bank_Transaction_Group__r.Name,Amount__c 
                            from Bank_Transaction__c where Id = :lstBT[0].id];
            for(Bank_Transaction__c bt: lstQueriedBT){
                mapBTGNameAndBTName.put(bt.Bank_Transaction_Group__r.Name,bt.Name);
            }
         mapBTGNameAndBTName.put('Bank Transaction Group','Bank Transaction');
        for(String strVmsg: (voidCancelSvc.getVoidCancelDetails().get(lstBT[0].bank_Transaction_Group__c)).voidMessages){
             if(String.isnotBlank(strVmsg)){
                    for(String btgname :mapBTGNameAndBTName.keySet()){
                        if(strVmsg.contains(btgname)) voidMessages.add(strVmsg.replace(btgname,mapBTGNameAndBTName.get(btgname)));
                    }
             }
        }
		return voidMessages;
	}
    
    public List<string> getCancelDetails(){
        List<String> cancelMessages = new List<String>();
        map<String,string> mapBTGNameAndBTName = new map<String,string>();
         if (lstBT==null) return null;
          List<Bank_Transaction__c>   lstQueriedBT = [Select Id, Name, Bank_Transaction_Group__c, Bank_Transaction_Group__r.Name,Amount__c 
                            from Bank_Transaction__c where Id = :lstBT[0].id];
            for(Bank_Transaction__c bt: lstQueriedBT){
                mapBTGNameAndBTName.put(bt.Bank_Transaction_Group__r.Name,bt.Name);
            }
         mapBTGNameAndBTName.put('Bank Transaction Group','Bank Transaction');
        for(String strVmsg: (voidCancelSvc.getVoidCancelDetails().get(lstBT[0].bank_Transaction_Group__c)).cancelMessages){
            if(String.isnotBlank(strVmsg)){
                for(String btgname :mapBTGNameAndBTName.keySet()){
                if(strVmsg.contains(btgname) )  cancelMessages.add(strVmsg.replace(btgname,mapBTGNameAndBTName.get(btgname)));
                }
            }
        }
		return cancelMessages;
	}
    @RemoteAction
    public static JsonResult voidCancelBankTransactionGroup(Id listBT, string action, string voidDate){
        JSONResult result = new JSONResult();  
        if(!String.isBlank(listBT) && !String.isBlank(action) && !String.isBlank(voidDate) ){
            map<Id,string> mapBTGMessages = new map<Id,string>();
            map<Id,Id> mapBTGIdAndBTId = new map<Id,Id>();
            map<string,string> mapBTGNameAndBTName = new map<string,string>();
            map<Id,string> mapBTGIdAndBTGName = new map<Id,string>();
            list<Bank_Transaction__c> lstQueriedBT = new list<Bank_Transaction__c>();
            lstQueriedBT = [Select Id, Name, Bank_Transaction_Group__c, Bank_Transaction_Group__r.Name,Amount__c 
                            from Bank_Transaction__c where Id = :listBT];
            for(Bank_Transaction__c bt: lstQueriedBT){
                mapBTGIdAndBTId.put(bt.Bank_Transaction_Group__c,bt.Id);
                mapBTGNameAndBTName.put(bt.Bank_Transaction_Group__r.Name,bt.Name);
                mapBTGIdAndBTGName.put(bt.Bank_Transaction_Group__c,bt.Bank_Transaction_Group__r.Name);
            }
            if(!mapBTGIdAndBTId.isEmpty() && !mapBTGNameAndBTName.isEmpty()){
                //add void fields in the query.
                /*list<Bank_Transaction_Group__c>  lstBTG = [Select Id, Company__c, Exceptions_Count__c, Finalized__c, Finalized_Date__c,Transaction_date__c,Posting_date__c, name, Void__c, Void_Date__c, Historical__c, Status__c,                
                                                           (Select Id from Bank_Transactions__r),
                                                           (select id, name from Accounting_Entries__r  where status__c = 'Active' and Has_Exceptions__c != true) 
                                                           From Bank_Transaction_Group__c where id  in: mapBTGIdAndBTId.keyset()];*/
               Set<id> btgids =  mapBTGIdAndBTId.keyset();
                 SOQLUtil soql = new SOQLUtil('Bank_Transaction_Group__c', TRUE);
                string status='Active';
            soql.addFields('Match_Bank_Transactions_Columns');
            soql.addFields(new Set<String>{'Id', 'Company__c', 'Exceptions_Count__c', 'Finalized__c', 'Finalized_Date__c','Transaction_date__c','Posting_date__c', 
                							'name', 'Void__c', 'Void_Date__c', 'Historical__c', 'Status__c'});
            soql.setWhereClause('id in :btgids');     
        list<Bank_Transaction_Group__c>  lstBTG = database.query(soql.getQuery());
               Datetime dateTimeInFormat = null;
               dateTimeInFormat = (datetime)JSON.deserialize(voidDate, Datetime.class);
               //dateTimeInFormat = DateTime.valueOf(voidDate);
            mapBTGMessages = new BankTransactionVoidCancelService(lstBTG).voidCancelBankTransactionGroup(lstBTG,action,voidDate);
                if(!mapBTGMessages.isEmpty()){
                    for(Id btgId: mapBTGMessages.keyset()){
                        if(mapBTGIdAndBTId.containsKey(btgId)){
                            string msg = mapBTGMessages.get(btgId);
                            
                            if(!string.isblank(msg)){
                                if(msg.contains(btgId)){
                                    msg = mapBTGMessages.get(btgId).replaceAll(btgId,mapBTGIdAndBTId.get(btgId));
                                }
                                if( msg.contains('Bank Transaction Group')){
                                    msg = msg.replaceAll('Bank Transaction Group','Bank Transaction');
                                }
                                
                                if( msg.contains(mapBTGIdAndBTGName.get(btgId))){
                                    msg = msg.replaceAll(mapBTGIdAndBTGName.get(btgId),mapBTGNameAndBTName.get(mapBTGIdAndBTGName.get(btgId)));
                                }else {
                                    msg =mapBTGNameAndBTName.get(mapBTGIdAndBTGName.get(btgId))+ ': ' + msg;
                                }
                                if(msg.contains('Successfully')){
                                    result.addmessage(msg,ApexPages.severity.Confirm);
                                    result.success=true;
                                }else{
                                    result.addmessage(msg,ApexPages.severity.Error);
                                    result.success = false; 
                                }                                
                            }
                        }
                    }
                }
            }
        }
        return result;
    }
}