src-ken&y/objects/Accounting_Entry__c.object
<CustomObject>
    <customHelpPage>HelpAccountingEntries</customHelpPage>
    <description>Accounting Entry Header records</description>
    <fields>
        <fullName>Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Accounting Entries</relationshipLabel>
        <relationshipName>Accounting_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Accounting Entries</relationshipLabel>
        <relationshipName>Accounting_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <description>Transaction date for the associated source document.</description>
        <label>Transaction Date</label>
        <type>DateTime</type>
    </fields>
    <label>Accounting Entry</label>
    <nameField>
        <label>Accounting Entry</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Accounting_Entry_Line__c.object
<CustomObject>
    <customHelpPage>HelpAccountingEntries</customHelpPage>
    <description>Accounting Entry Lines</description>
    <fields>
        <fullName>Accounting_Entry__c</fullName>
        <label>Accounting Entry</label>
        <referenceTo>Accounting_Entry__c</referenceTo>
        <relationshipLabel>Accounting Entry Lines</relationshipLabel>
        <relationshipName>Accounting_Entry_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Amount_CR__c</fullName>
        <description>Credit amount for this transaction</description>
        <label>Amount CR</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Amount_DR__c</fullName>
        <description>Debit amount for this transaction</description>
        <label>Amount DR</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <formula>Accounting_Entry__r.Currency__r.ISO_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Currency</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice Line</label>
        <referenceTo>Invoice_Line__c</referenceTo>
        <relationshipLabel>Accounting Entry Lines</relationshipLabel>
        <relationshipName>Accounting_Entry_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Line_Type__c</fullName>
        <label>Line Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Related_Accounting_Entry_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Accounting Entry Line</label>
        <referenceTo>Accounting_Entry_Line__c</referenceTo>
        <relationshipLabel>Accounting Entry Lines</relationshipLabel>
        <relationshipName>Accounting_Entry_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>TEXT(Accounting_Entry__r.Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubTransaction_Type__c</fullName>
        <description>Sub Transaction Type</description>
        <label>SubTransaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Off Invoice Allowance</fullName>
                </value>
                <value>
                    <fullName>Sundry Allowance</fullName>
                </value>
                <value>
                    <fullName>Bill Back Allowance</fullName>
                </value>
                <value>
                    <fullName>Deductions</fullName>
                </value>
                <value>
                    <fullName>Earned Discount</fullName>
                </value>
                <value>
                    <fullName>Unearned Discount</fullName>
                </value>
                <value>
                    <fullName>Write Off</fullName>
                </value>
                <value>
                    <fullName>OverPayment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <description>Transaction Date of this Accounting Entry Line</description>
        <label>Transaction Date</label>
        <type>Date</type>
    </fields>
    <label>Accounting Entry Line</label>
    <nameField>
        <label>Accounting Entry Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Entry Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Currency__c.object
<CustomObject>
    <customHelpPage>HelpCurrency</customHelpPage>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Currency</label>
    <nameField>
        <label>Currency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Invoice__c.object
<CustomObject>
    <customHelpPage>HelpIntercompanyInvoices</customHelpPage>
    <fields>
        <fullName>Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to company</description>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Invoice Currency</relationshipLabel>
        <relationshipName>Invoice_Currency</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Finalized__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Finalized</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>From_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>From Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>From Company Invoices</relationshipLabel>
        <relationshipName>From_Company_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>To_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>To Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>To Company Invoices</relationshipLabel>
        <relationshipName>To_Company_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <label>Transaction Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Intercompany Investment</fullName>
                </value>
                <value>
                    <fullName>Intercompany Cross Charge</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Invoice_Line__c.object
<CustomObject>
    <fields>
        <fullName>Currency__c</fullName>
        <formula>Invoice__r.Currency__r.ISO_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Currency</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Extended_Amount__c</fullName>
        <label>Extended Amount</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Finalized__c</fullName>
        <formula>Invoice__r.Finalized__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Finalized</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Line_Type__c</fullName>
        <label>Line Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subtransaction_Type__c</fullName>
        <label>Subtransaction Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Intercompany Investment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Invoice Line</label>
    <nameField>
        <label>Invoice Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/classes/InvoiceAccountingTest.cls
@isTest
private class InvoiceAccountingTest {

    public class SampleData{
        
        public testFuel data = new testFuel();
        public SampleData(){
            updateData();
        }
        
        
	    public List<Invoice_Line__c> InvLineList1 = new List<Invoice_Line__c>();
	    public List<Invoice_Line__c> InvLineList2 = new List<Invoice_Line__c>();
	    public List<Invoice__c> InvAEList = new List<Invoice__c>();
	    public Invoice__c Inv1, Inv2, Inv3;
        public Invoice_Line__c InvLine1, InvLine2, InvLine3, InvLine4, rilt1;
        
        private void updateData(){
            
           	Inv1 = new Invoice__c();
            Inv1.From_Company__c = data.company.id;
            Inv1.To_Company__c = data.altCompany.id;
            Inv1.Type__c = 'Intercompany Investment';
            Inv1.Currency__c = TestFuel.currencyUSD.id;
            Inv1.Transaction_Date__c = system.now();
            
            
           	Inv2 = new Invoice__c();
            Inv2.From_Company__c = data.company.id;
            Inv2.To_Company__c = data.altCompany.id;
            Inv2.Type__c = 'Intercompany Cross Charge';
            Inv2.Currency__c = TestFuel.currencyUSD.id;
            Inv2.Transaction_Date__c = system.now();
            
            
            InvAEList.add(Inv1);
            InvAEList.add(Inv2);
            
            insert InvAEList;
            
            Invoice_Line__c InvLine1 = new Invoice_Line__c(); 
            InvLine1.Invoice__c = Inv1.id;
            InvLine1.Extended_Amount__c = 5000;
            InvLineList1.add(InvLine1);
            
            Invoice_Line__c InvLine2 = new Invoice_Line__c(); 
            InvLine2.Invoice__c = Inv1.id;
            InvLine2.Extended_Amount__c = 10000;
            InvLineList1.add(InvLine2);
            
            Invoice_Line__c InvLine3 = new Invoice_Line__c(); 
            InvLine3.Invoice__c = Inv2.id;
            InvLine3.Extended_Amount__c = 5000;
            InvLineList1.add(InvLine3);
            
            Invoice_Line__c InvLine4 = new Invoice_Line__c(); 
            InvLine4.Invoice__c = Inv2.id;
            InvLine4.Extended_Amount__c = 10000;
            InvLineList1.add(InvLine4);
            insert InvLineList1;
            
            system.assert(data.periodList.size() >0);
            system.assert(data.altCompanyPeriodList.size() >0);
            system.assert(data.invoiceRuleList.size() >0);
            
            Inv1.finalized__c = true;
			Inv2.finalized__c = true;            
             
            update InvAEList;
        }
        
        
	    
    }   
    static testMethod void InvoiceAccountingTest() {
        SampleData sd = new SampleData();
        
 	    Test.startTest();
	    
	    sd.Inv1 = [Select id, Name, Finalized__c
	                                    from Invoice__c 
	                                    where id = :sd.Inv1.id];
	    system.assertEquals(true, sd.Inv1.Finalized__c);
	    	            
	    InvoiceAccounting ia = new InvoiceAccounting();
        list<invoice_line__c> silList = new list<invoice_line__c>();
        silList.addall(sd.InvLineList1);

	    ia.execute(silList);
	    
	    Set<Id> InvIds = new Set<Id>();
	    for(Invoice__c Inv: sd.InvAEList){
	        InvIds.add(Inv.id);
	    }
	    List<Accounting_Entry__c> acctEntry = [Select id, Name, Invoice__c,status__c,
	                                            (Select id, Name, Amount_CR__c, Amount_DR__c, SubTransaction_Type__c, Line_Type__c
	                                            from Accounting_Entry_Lines__r)
	                                            from Accounting_Entry__c 
	                                            where (Invoice__c in :InvIds) order by id];
	        
	    system.debug('acctEntry:'+acctEntry);
	    system.assertnotEquals(null,acctEntry);
	    system.assertEquals(4,acctEntry.size());
	    Integer listSize = acctEntry.size();
    }
}