src-ken&y/objects/Accounting_Default__c.object
<CustomObject>
    <customHelpPage>HelpAccountingDefaults</customHelpPage>
    <description>The default values for document lines, used to hold accounting segments for the COA</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Accounting Defaults</relationshipLabel>
        <relationshipName>Accounting_Defaults</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <description>Select the transaction type for this accounting default</description>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Shipment</fullName>
                </value>
                <value>
                    <fullName>Customer Invoice</fullName>
                </value>
                <value>
                    <fullName>Customer Receipt</fullName>
                </value>
                <value>
                    <fullName>Purchase Receipt</fullName>
                </value>
                <value>
                    <fullName>Supplier Invoice</fullName>
                </value>
                <value>
                    <fullName>Supplier Payment</fullName>
                </value>
                <value>
                    <fullName>Supplier Credit Memo</fullName>
                </value>
                <value>
                    <fullName>Customer Credit Memo</fullName>
                </value>
                <value>
                    <fullName>Inventory Change</fullName>
                </value>
                <value>
                    <fullName>Work Order</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Accounting Default</label>
    <nameField>
        <displayFormat>AD-{0000000000}</displayFormat>
        <label>Accounting Default</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounting Defaults</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Company__c.object
<CustomObject>
    <customHelpPage>HelpCompany</customHelpPage>
    <description>Each Logistics or Financial entity will be represented by a single Company record.  Master data for the Company is recorded here and used throughout the System.</description>
    <fields>
        <fullName>City__c</fullName>
        <description>Company city</description>
        <formula>Address__r.BillingCity</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Company Country</description>
        <formula>Address__r.BillingCountry</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>Company State</description>
        <formula>Address__r.BillingState</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <description>Company Street</description>
        <formula>Address__r.BillingStreet</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Street</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <description>Company Zip Code</description>
        <formula>Address__r.BillingPostalCode</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Zip Code</label>
        <type>Text</type>
    </fields>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/GL_Account__c.object
<CustomObject>
    <customHelpPage>HelpGLAccount</customHelpPage>
    <description>Table of acceptable General Ledger Numbers or Names with associated Cross Reference Information</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Revenue</fullName>
                </value>
                <value>
                    <fullName>Expense</fullName>
                </value>
                <value>
                    <fullName>Asset</fullName>
                </value>
                <value>
                    <fullName>Liability</fullName>
                </value>
                <value>
                    <fullName>Equity</fullName>
                </value>
                <value>
                    <fullName>--None--</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GL Account</label>
    <nameField>
        <label>GL Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Invoice__c.object
<CustomObject>
    <customHelpPage>HelpIntercompanyInvoices</customHelpPage>
    <fields>
        <fullName>Finalized__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Finalized</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>From_City__c</fullName>
        <label>From City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>From_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>From Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>From Company Invoices</relationshipLabel>
        <relationshipName>From_Company_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>From_Country__c</fullName>
        <label>From Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>From_State__c</fullName>
        <label>From State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>From_Street__c</fullName>
        <label>From Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>From_Zip_Code__c</fullName>
        <label>From Zip Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_Amount__c</fullName>
        <label>Invoice Amount</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>To_City__c</fullName>
        <label>To City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>To_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>To Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>To Company Invoices</relationshipLabel>
        <relationshipName>To_Company_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>To_Country__c</fullName>
        <label>To Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>To_State__c</fullName>
        <label>To State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>To_Street__c</fullName>
        <label>To Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>To_Zip_Code__c</fullName>
        <label>To Zip Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Intercompany Investment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Intercompany Investment</fullName>
                </value>
                <value>
                    <fullName>Intercompany Cross Charge</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Invoice_Line__c.object
<CustomObject>
    <fields>
        <fullName>Accounting_Default__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Accounting Default</label>
        <referenceTo>Accounting_Default__c</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>Invoice_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Extended_Amount__c</fullName>
        <label>Extended Amount</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Finalized__c</fullName>
        <formula>Invoice__r.Finalized__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Finalized</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Intercompany Investment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Invoice Line</label>
    <nameField>
        <label>Invoice Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Supplier_Invoice__c.object
<CustomObject>
    <customHelpPage>HelpSupplierInvoice</customHelpPage>
    <description>Record invoices for items or services  that are received from a supplier.  Bills can be recorded with or without purchase orders</description>
    <fields>
        <fullName>Balance_Due__c</fullName>
        <formula>IF( OR(ISPICKVAL(Status__c, &quot;Void&quot;),ISPICKVAL(Status__c, &quot;Cancelled&quot;)) , 0, (Invoice_Amount__c  -  Amount_Paid__c +  Credit_Memo_Amount_Applied__c - Discount_Taken__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Balance Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Supplier Invoices</relationshipLabel>
        <relationshipName>Supplier_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Credit_Memo_Amount__c</fullName>
        <label>Credit Memo Amount</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Credit_Memo_Balance__c</fullName>
        <description>Reflects the credit memo amount available for use</description>
        <label>Credit Memo Balance</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Finalized__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag is set to true when the invoice is finalized and no more changes are expected</description>
        <inlineHelpText>A check mark indicates that the document is final. Kenandy will automatically generate an accounting entry for it in the next scheduled batch process.</inlineHelpText>
        <label>Finalized</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoice_Amount__c</fullName>
        <inlineHelpText>The invoice amount is required. Invoice cannot be approved for payment if the invoice amount does not match the total amount on each line of the invoice.</inlineHelpText>
        <label>Invoice Amount</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoice_Type__c</fullName>
        <label>Invoice Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Credit Memo</fullName>
                </value>
                <value>
                    <fullName>Invoice</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Prepayment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of bill</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supplier_Invoice__c</fullName>
        <description>Supplier invoice no. reference</description>
        <label>Invoice Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>--None--</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Supplier Invoice</label>
    <nameField>
        <label>Supplier Invoice</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/InvoiceService.cls
public with sharing class InvoiceService {
	public static ExceptionService exService = new ExceptionService();
	public static final String INTERCO_INVEST = 'Intercompany Investment';
	public static final String INTERCO_CROSS = 'Intercompany Cross Charge';

	public InvoiceService() {
		
	}

	public static boolean validateAndUpsert(List<Invoice__c>invoices, List<Invoice_Line__c>invoiceLines, JSONResult result, Boolean skipQuery){
		Set<Id>invoiceIds = new Set<Id>();

		for(Invoice__c inv : invoices){
			invoiceIds.add(inv.Id);

			if(INTERCO_INVEST.equalsIgnoreCase(inv.Type__c)){
				inspectIntercoInvestment(inv, invoiceLines, result);
			}else if(INTERCO_CROSS.equalsIgnoreCase(inv.Type__c)){
				inspectIntercoCross(inv, invoiceLines, result);
			}
		}

		exService.newExceptionsAlreadyOverridden(invoiceIds, new set<String>{TaskType.EXCEPTION_STATUS_OVERRIDDEN});

		exService.finishTasks(true);

		System.debug(LoggingLevel.INFO, '#### Num Messages: ' + result.messages.size() );

		if(result.messages.size() > 0){
			return false;
		}else{
			return true;
		}
	}

	/* This method blocks the Invoices edit on a closed/approved ones if any payment is available,
	 similar to the way it behaves on the UI */
    public static void restrictEditOnApprovedClosedInvoices(){
        
        // Add the Object and its Payment Issue related fieldset to enhance this method for other Invoices/sObjects        
        Map<String,List<String>> objectAndPaymentFieldsetMap = new Map<String,List<String>>{'Supplier_Invoice__c' => new List<String>{'Payment_Issued'}};
        
        List<sObject> sObjRecs = new List<sObject>();
        Schema.sObjectType iSObjType = null;
        String sObjectName = null;
        String sObjectLabel = null;
        
        if(trigger.isBefore && trigger.isUpdate){
            
            sObjRecs = trigger.new;
            iSObjType = sObjRecs[0].getSObjectType();
            sObjectName = iSObjType.getDescribe().getLocalName();
            System.debug(logginglevel.error,'sObjectName-->'+sObjectName);
            sObjectLabel = iSObjType.getDescribe().getLabel();
            
        }else if(trigger.isBefore && trigger.isDelete){
            
            sObjRecs = trigger.old;
            iSObjType = sObjRecs[0].getSObjectType();
            sObjectName = iSObjType.getDescribe().getLocalName();
            System.debug(logginglevel.error,'sObjectName-->'+sObjectName);
            sObjectLabel = iSObjType.getDescribe().getLabel();
        }
        
        if(trigger.isBefore){
            for(integer i = 0; i< sObjRecs.size(); i++){
                
                if(trigger.isBefore && trigger.isDelete){
                    trigger.old[i].addError(Label.You_cannot_delete_an_invoice);
                }
                
                sObject sObj = sObjRecs[i];
                
                Boolean isFinalized = false;
                Boolean isApproved = false;
                Boolean isClosed = false;
                isFinalized = ((Boolean)sObj.get('Finalized__c') && (Boolean)trigger.old[i].get('Finalized__c')) ? true : false;
                isApproved = ((String)sObj.get('Status__c') == SupplierInvoiceService.STATUS_APPROVED && (String)trigger.old[i].get('Status__c') == SupplierInvoiceService.STATUS_APPROVED) ? true : false;
                isClosed = ((String)sObj.get('Status__c') == SupplierInvoiceService.STATUS_CLOSED && (String)trigger.old[i].get('Status__c') == SupplierInvoiceService.STATUS_CLOSED) ? true : false;
                
                List<String> tobeComparedFieldsetList = new List<String>();
                Boolean paymentsPresent = false;
                
                if(isFinalized && isApproved){
                     if(((String)sObj.get('Invoice_Type__c') == SupplierInvoiceService.invTypeInvoice || (String)sObj.get('Invoice_Type__c') == SupplierInvoiceService.invTypePrepymt)
                        && ((double)sObj.get('Invoice_Amount__c') != (double)sObj.get('Balance_Due__c'))){
                          if(objectAndPaymentFieldsetMap.containsKey(sObjectName)){
                             tobeComparedFieldsetList.addAll(objectAndPaymentFieldsetMap.get(sObjectName)); //the fieldset for payment issued added
                          }
                          paymentsPresent = true;
                          System.debug(logginglevel.error,'Inside the payments present section of invoice/prepayment');
                     }else if((String)sObj.get('Invoice_Type__c') == SupplierInvoiceService.invTypeCM && ((double)sObj.get('Credit_Memo_Amount__c') != (double)sObj.get('Credit_Memo_Balance__c'))){
                          if(objectAndPaymentFieldsetMap.containsKey(sObjectName)){
                             tobeComparedFieldsetList.addAll(objectAndPaymentFieldsetMap.get(sObjectName)); //the fieldset for payment issued added
                          }
                          paymentsPresent = true;
                          System.debug(logginglevel.error,'Inside the payments present section of creditmemo');
                     }
                }
                if(isFinalized && isClosed){
                    if(objectAndPaymentFieldsetMap.containsKey(sObjectName)){
                         tobeComparedFieldsetList.addAll(objectAndPaymentFieldsetMap.get(sObjectName)); //the fieldset for payment issued added
                    } 
                    paymentsPresent = true;
                }
                
                if(tobeComparedFieldsetList != null){
                    map<string, string> validateFields = sObjectValidateFields(iSObjType, tobeComparedFieldsetList);  
                    if(trigger.isBefore && trigger.isUpdate){
                        //The record exists and is being updated - make sure the vital fields aren't changing
                        for(string field : validateFields.keySet()){
                             System.debug(logginglevel.error,'field-->'+field);
                             System.debug(logginglevel.error,'new value-->'+trigger.new[i].get(field));
                             System.debug(logginglevel.error,'old value-->'+trigger.old[i].get(field));
                             
                            if(trigger.new[i].get(field) != trigger.old[i].get(field)){
                                if(paymentsPresent){
                                    //String messageStr = Label.You_cannot_change +' '+ '{!field}' +' '+ Label.on_a +' '+ sObjectLabel +' '+ Label.when_payment_has_been_issues;
                                    //messageStr = messageStr.replace('{!field}',field);
                                    trigger.new[i].addError(Label.You_cannot_change +' '+ field +' '+ Label.on_a +' '+ sObjectLabel +' '+ Label.when_payment_has_been_issues);
                                }  
                            }
                        }
                    }
                }
            }
        }
    }
    
    private static map<Schema.sObjectType, map<string, string>> mValidateFields = new map<Schema.sObjectType, map<string, string>>();  
    public static map<string, string> sObjectValidateFields(Schema.sObjectType sObjectType, List<String> fieldSetNames){
        map<string, string> mFieldLabel = new map<string, string>();
        if(mValidateFields.containsKey(sObjectType)){
            mFieldLabel = mValidateFields.get(sObjectType);
        }else{
            System.debug(logginglevel.error,'fieldSetNames-->'+fieldSetNames);
            for(String fieldSetString : fieldSetNames){
                for( Schema.FieldSetMember fsm : SchemaUtil.getInstance().getFieldsFromFieldSet(sObjectType, fieldSetString) ){  
                    mFieldLabel.put(fsm.getFieldPath(), fsm.getLabel());
                }
                mValidateFields.put(sObjectType, mFieldLabel);
                System.debug(logginglevel.error,'mValidateFields-->'+mValidateFields);
            }
        }
        return mFieldLabel; 
    }

	public static void invoiceChangedTrigger(List<Invoice__c>newIn, map<Id, Invoice__c>oldIn){

		List<Invoice__c>toChange = new List<Invoice__c>();
		List<Invoice__c>fromChange = new List<Invoice__c>();
		Set<Id> companyId = new Set<Id>();

		for(Invoice__c i : newIn){
			if(i.Id == null || oldIn.containsKey(i.Id) == false || oldIn.get(i.Id).Type__c != i.Type__c ){
				i.Transaction_Type__c = i.Type__c;
			}

			if(i.Id == null || oldIn.containsKey(i.Id) == false || oldIn.get(i.Id).To_Company__c != i.To_Company__c){
				toChange.add(i);
				companyId.add(i.To_Company__c);
			}

			if(i.Id == null || oldIn.containsKey(i.Id) == false || oldIn.get(i.Id).From_Company__c != i.From_Company__c){
				fromChange.add(i);
				companyId.add(i.From_Company__c);
			}
		}

		map<Id, Company__c>companies = new map<Id, Company__c>([Select Id, Street__c, City__c, State__c, Zip_Code__c, Country__c From Company__c Where Id in:companyId]);

		for(Invoice__c i : toChange){
			i.To_Street__c = companies.get(i.To_Company__c).Street__c;
			i.To_City__c =  companies.get(i.To_Company__c).City__c;
			i.To_State__c =  companies.get(i.To_Company__c).State__c;
			i.To_Zip_Code__c =  companies.get(i.To_Company__c).Zip_Code__c;
			i.To_Country__c =  companies.get(i.To_Company__c).Country__c;
		}

		for(Invoice__c i : fromChange){
			i.From_Street__c = companies.get(i.From_Company__c).Street__c;
			i.From_City__c =  companies.get(i.From_Company__c).City__c;
			i.From_State__c =  companies.get(i.From_Company__c).State__c;
			i.From_Zip_Code__c =  companies.get(i.From_Company__c).Zip_Code__c;
			i.From_Country__c =  companies.get(i.From_Company__c).Country__c;
		}
	}

	private static void inspectIntercoInvestment(Invoice__c inv, List<Invoice_Line__c> lines, JSONResult result){

		validateIntercompany(inv, result);

		if(lines != null && lines.size() > 0){
			//validate lines and insert
			Set<Id> lIds = new Set<Id>();
			for(Invoice_Line__c il : lines){
				if(il.Extended_Amount__c == null || il.Extended_Amount__c <= 0){
					exService.setException(il, ExceptionUtil.IL_INVALID_AMOUNT);
					addResult(result, ExceptionUtil.IL_INVALID_AMOUNT);
				}else{
					exService.clearException(il, ExceptionUtil.IL_INVALID_AMOUNT);
				}
				if(il.Id != null){
					lIds.add(il.Id);
				}
			}

			System.debug(LoggingLevel.INFO, '#### Line Ids: ' + lIds);
			exService.newExceptionsAlreadyOverridden(lIds, new set<String>{TaskType.EXCEPTION_STATUS_OVERRIDDEN});
		}

	}

	private static void inspectIntercoCross(Invoice__c inv, List<Invoice_Line__c> lines, JSONResult result){
		System.debug(LoggingLevel.INFO, '### Validating Cross: Num Lines: ' + lines.size());
		validateIntercompany(inv, result);

		if(lines != null && lines.size() > 0){
			//validate lines and insert
			Set<Id> lIds = new Set<Id>();
			for(Invoice_Line__c il : lines){
				System.debug(LoggingLevel.INFO, '### Line Price: ' + il.Extended_Amount__c + '\tGL: ' );
				if(il.Extended_Amount__c <= 0){
					exService.setException(il, ExceptionUtil.IL_INVALID_AMOUNT);
					addResult(result, ExceptionUtil.IL_INVALID_AMOUNT);
				}else{
					exService.clearException(il, ExceptionUtil.IL_INVALID_AMOUNT);
				}


				if(il.Accounting_Default__c != null){
					//clear all deafult exceptions
					exService.clearException(il, ExceptionUtil.IL_Accounting_Default_Required);
					exService.clearException(il, ExceptionUtil.IL_Accounting_Default_GLAccount_Required);
					exService.clearException(il, ExceptionUtil.IL_Accounting_Default_Company_Required);
					exService.clearException(il, ExceptionUtil.IL_Accounting_Default_Intercompany_Required);
				}else{
					if(il.Accounting_Default__r == null){
						exService.setException(il, ExceptionUtil.IL_Accounting_Default_Required);
						addResult(result, ExceptionUtil.IL_Accounting_Default_Required);
					}else{
						//clear ad required excption
						exService.clearException(il, ExceptionUtil.IL_Accounting_Default_Required);
					}

					if(il.Accounting_Default__r.GL_Account__c == null){
						exService.setException(il, ExceptionUtil.IL_Accounting_Default_GLAccount_Required);
						addResult(result, ExceptionUtil.IL_Accounting_Default_GLAccount_Required);
					}else{
						//clear ad required excption
						exService.clearException(il, ExceptionUtil.IL_Accounting_Default_GLAccount_Required);
					}

					if(il.Accounting_Default__r.Company__c == null){
						//company required
						exService.setException(il, ExceptionUtil.IL_Accounting_Default_Company_Required);
						addResult(result, ExceptionUtil.IL_Accounting_Default_Company_Required);
					}else if(il.Accounting_Default__r.Company__c != inv.From_Company__c){
						//company doesn't match
						exService.setException(il, ExceptionUtil.IL_Accounting_Default_Company_Required);
						addResult(result, ExceptionUtil.IL_Accounting_Default_Company_Required);
					}else{
						//clear company exception
						exService.clearException(il, ExceptionUtil.IL_Accounting_Default_Company_Required);
					}

					if(il.Accounting_Default__r.Intercompany__c == null){
						//intercompany required
						exService.setException(il, ExceptionUtil.IL_Accounting_Default_Intercompany_Required);
						addResult(result, ExceptionUtil.IL_Accounting_Default_Intercompany_Required);
					}else if(il.Accounting_Default__r.Intercompany__c != inv.To_Company__c){
						//intercompany doesn't match
						exService.setException(il, ExceptionUtil.IL_Accounting_Default_Intercompany_Required);
						addResult(result, ExceptionUtil.IL_Accounting_Default_Intercompany_Required);
					}else{
						//clear company exception
						exService.clearException(il, ExceptionUtil.IL_Accounting_Default_Intercompany_Required);
					}

				}

				if(il.Id != null){
					lIds.add(il.Id);
				}
			}

			System.debug(LoggingLevel.INFO, '#### Line Ids: ' + lIds);
			exService.newExceptionsAlreadyOverridden(lIds, new set<String>{TaskType.EXCEPTION_STATUS_OVERRIDDEN});
		}
	}

	private static void validateIntercompany(Invoice__c inv, JSONResult result){

		if(inv.To_Company__c == null){
			exService.setException(inv, ExceptionUtil.I_MISSING_TO_COMPANY);
			addResult(result, ExceptionUtil.I_MISSING_TO_COMPANY);
		}else{
			exService.clearException(inv, ExceptionUtil.I_MISSING_TO_COMPANY);
		}

		if(inv.From_Company__c == null){
			exService.setException(inv, ExceptionUtil.I_MISSING_FROM_COMPANY);
			addResult(result, ExceptionUtil.I_MISSING_FROM_COMPANY);
		}else{
			exService.clearException(inv, ExceptionUtil.I_MISSING_FROM_COMPANY);
		}
	}


	private static void addResult(JSONResult result, TaskType tt){
		if(result != null){
			result.addMessage(tt.description, ApexPages.Severity.ERROR);
		}
	}
}