src-ken&y/objects/Accounting_Entry__c.object
<CustomObject>
    <customHelpPage>HelpAccountingEntries</customHelpPage>
    <description>Accounting Entry Header records</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Accounting Entries</relationshipLabel>
        <relationshipName>Accounting_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Accounting Entries</relationshipLabel>
        <relationshipName>Accounting_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Period</description>
        <label>Period</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Period__c.Open__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Period__c</referenceTo>
        <relationshipLabel>Accounting_Entries</relationshipLabel>
        <relationshipName>Accounting_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reverse_Next_Period__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Select this check box if the entry should be reversed at the beginning of the next period</description>
        <label>Reverse Next Period</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <description>Transaction date for the associated source document.</description>
        <label>Transaction Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <description>Select the transaction type of the original transaction</description>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Manual</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Accounting Entry</label>
    <nameField>
        <label>Accounting Entry</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Accounting_Entry_Line__c.object
<CustomObject>
    <customHelpPage>HelpAccountingEntries</customHelpPage>
    <description>Accounting Entry Lines</description>
    <fields>
        <fullName>Accounting_Entry__c</fullName>
        <label>Accounting Entry</label>
        <referenceTo>Accounting_Entry__c</referenceTo>
        <relationshipLabel>Accounting Entry Lines</relationshipLabel>
        <relationshipName>Accounting_Entry_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Amount_CR__c</fullName>
        <description>Credit amount for this transaction</description>
        <label>Amount CR</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Amount_DR__c</fullName>
        <description>Debit amount for this transaction</description>
        <label>Amount DR</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Accounting Entry Lines</relationshipLabel>
        <relationshipName>Accounting_Entry_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <formula>Accounting_Entry__r.Currency__r.ISO_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Currency</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exception__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Exception is set to true when the line has any exception set to true which will cause the header Exception to set it to true</description>
        <inlineHelpText>A checkmark indicates that there is one or more exceptions associated with this accounting entry/line (header record).</inlineHelpText>
        <label>Exception</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GL_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>GL account</description>
        <label>GL Account</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>GL Account used in the Accounting rule is Inactive. Please Select a Active GL Account</errorMessage>
            <filterItems>
                <field>GL_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>GL_Account__c</referenceTo>
        <relationshipLabel>Accounting Entry Lines</relationshipLabel>
        <relationshipName>Accounting_Entry_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Accounting_Entry_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Accounting Entry Line</label>
        <referenceTo>Accounting_Entry_Line__c</referenceTo>
        <relationshipLabel>Accounting Entry Lines</relationshipLabel>
        <relationshipName>Accounting_Entry_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <description>Transaction Date of this Accounting Entry Line</description>
        <label>Transaction Date</label>
        <type>Date</type>
    </fields>
    <label>Accounting Entry Line</label>
    <nameField>
        <label>Accounting Entry Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Entry Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Company__c.object
<CustomObject>
    <customHelpPage>HelpCompany</customHelpPage>
    <description>Each Logistics or Financial entity will be represented by a single Company record.  Master data for the Company is recorded here and used throughout the System.</description>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Currency__c.object
<CustomObject>
    <customHelpPage>HelpCurrency</customHelpPage>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Currency</label>
    <nameField>
        <label>Currency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Fiscal_Year__c.object
<CustomObject>
    <customHelpPage>HelpYearEndClose</customHelpPage>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Fiscal Years</relationshipLabel>
        <relationshipName>Fiscal_Years</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GL_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Retained Earnings</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (1 AND 3 AND 4)</booleanFilter>
            <errorMessage>Value does not exist or does not match filter criteria. The GL Account you selected is either not Active or Type is not Equity or does not has GL Type with accounting type as Equity</errorMessage>
            <filterItems>
                <field>GL_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>GL_Account__c.Type__c</field>
                <operation>equals</operation>
                <value>Equity</value>
            </filterItems>
            <filterItems>
                <field>GL_Account__c.GL_Type__c</field>
                <operation>notEqual</operation>
                <value>null</value>
            </filterItems>
            <filterItems>
                <field>GL_Account__c.GL_Type__r.Accounting_Type__c</field>
                <operation>equals</operation>
                <value>Equity</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>GL_Account__c</referenceTo>
        <relationshipLabel>Fiscal Years</relationshipLabel>
        <relationshipName>Fiscal_Years</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Key__c</fullName>
        <label>Primary Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Fiscal Year</label>
    <nameField>
        <label>Fiscal Year</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fiscal Years</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/GL_Account__c.object
<CustomObject>
    <customHelpPage>HelpGLAccount</customHelpPage>
    <description>Table of acceptable General Ledger Numbers or Names with associated Cross Reference Information</description>
    <label>GL Account</label>
    <nameField>
        <label>GL Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Period__c.object
<CustomObject>
    <customHelpPage>HelpPeriods</customHelpPage>
    <description>Segment of time that financial entries fall into</description>
    <fields>
        <fullName>Adjustment_Period__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check the box if this is an adjustment period</description>
        <label>Adjustment Period</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Periods</relationshipLabel>
        <relationshipName>Periods</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Corporate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box of this period falls under corporate calendar</description>
        <label>Corporate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Fiscal_Year__c</fullName>
        <description>Label to describe the fiscal year</description>
        <label>Fiscal Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fiscal__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Check this box of this period falls under Fiscal calendar</description>
        <inlineHelpText>A checkmark indicates  this period belongs to a fiscal calendar. Only one period type can be selected.</inlineHelpText>
        <label>Fiscal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Open__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box to open the period</description>
        <label>Open</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Period_End__c</fullName>
        <description>Period End is the date and time when the period actually ends.</description>
        <label>Period End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Period_Number__c</fullName>
        <description>Period Number in sequence from 1-12 or 1-13 etc</description>
        <label>Period Number</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Period_Start__c</fullName>
        <description>Period Start is date and time when this period actually starts.</description>
        <label>Period Start</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Primary_Key__c</fullName>
        <description>This field serves the purpose of the primary key on the Period object which will be a combination of the fields Fiscal, Corporate, Tax, Company, Year start date</description>
        <label>Primary Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Quarter_Number__c</fullName>
        <description>Enter the quarter number for the period ex. 1</description>
        <label>Quarter Number</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Year_End_Date__c</fullName>
        <description>End date of the year in period calendar. Ex. Year end date for the corporate calendar to which this period belongs to.</description>
        <label>Year End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Year_Start_Date__c</fullName>
        <description>Start date of the year in period calendar. Ex. Year end date for the corporate calendar to which this period belongs to.</description>
        <label>Year Start Date</label>
        <type>Date</type>
    </fields>
    <label>Period</label>
    <nameField>
        <label>Period</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/RecurringAccountingEntryServiceTest.cls
@isTest
private class RecurringAccountingEntryServiceTest {
	//TODO SK: Deprecate this class when recurring accounting entry functionality is removed
	/*	
	static testMethod void myUnitTest() {
		
		TestDataForFinance testData = new TestDataForFinance();
		
		system.assert( testdata.Acctdata.cashGL.id != null, ' expected valid GL account ');
		
		List<Recurring_Accounting_Entry__c> RAEList = new List<Recurring_Accounting_Entry__c>(); 
		
		Recurring_Accounting_Entry__c RAE = new Recurring_Accounting_Entry__c();
		RAE.Company__c = testData.company.id;
		RAE.Start_Period__c = testData.periodList[0].Id;
		RAE.End_Period__c = testData.periodList[1].Id;
		RAE.Currency__c = TestFuel.currencyUSD.id;
		
		RAEList.add(RAE);
		
		insert RAEList;
		
		List<Recurring_Accounting_Entry_Line__c> lines = new List<Recurring_Accounting_Entry_Line__c>();
		
		Recurring_Accounting_Entry_Line__c RAELineCR = new Recurring_Accounting_Entry_Line__c();
		RAELineCR.Recurring_Accounting_Entry__c = RAE.Id;
		RAELineCR.Amount_CR__c = 125;
	    RAELineCR.GL_Account__c = testData.Acctdata.cashGL.id;
	    RAELineCR.Transaction_Date__c = system.today();
	    
	    lines.add(RAELineCR);
	    
	    Recurring_Accounting_Entry_Line__c RAELineDR = new Recurring_Accounting_Entry_Line__c();
	    RAELineDR.Recurring_Accounting_Entry__c = RAE.Id;
	    RAELineDR.Amount_DR__c = 125;
	    RAELineDR.GL_Account__c = testData.Acctdata.cashGL.id;
	    RAELineDR.Transaction_Date__c = system.today();
		
		lines.add(RAELineDR);
		
		insert lines;
		
		
		//Create accounting entry
		List<Accounting_Entry__c> AEList = new List<Accounting_Entry__c>(); 
		
		Accounting_Entry__c AE = new Accounting_Entry__c();
		AE.Company__c = testData.company.id;
		AE.Transaction_Type__c = 'Manual';
		AE.Currency__c = TestFuel.currencyUSD.id;
		AE.GL_Date__c = System.today();
		
		AEList.add(AE);
		
		insert AEList;
		
		
		List<Accounting_Entry_Line__c> AElines = new List<Accounting_Entry_Line__c>();
		
		Accounting_Entry_Line__c AELineCR = new Accounting_Entry_Line__c();
		AELineCR.Accounting_Entry__c = AE.Id;
		AELineCR.Amount_CR__c = 125;
	    AELineCR.GL_Account__c = testData.Acctdata.cashGL.id;
	    AELineCR.Transaction_Date__c = system.today();
	    
	    AElines.add(AELineCR);
	    
	    Accounting_Entry_Line__c AELineDR = new Accounting_Entry_Line__c();
	    AELineDR.Accounting_Entry__c = AE.Id;
	    AELineDR.Amount_DR__c = 125;
	    AELineDR.GL_Account__c = testData.Acctdata.cashGL.id;
	    AELineDR.Transaction_Date__c = system.today();
		
		AElines.add(AELineDR);
		
		insert AElines;
		
		Test.startTest();
		
		RecurringAccountingEntryService Service = RecurringAccountingEntryService.getInstance();
		
		//New Test for bulk
		List<Accounting_Entry__c> result = Service.createAccountingEntryRecurrences(Service.retriveRecurringAccountingEntries(new Period__c[]{testData.periodList[0]}));
		
		List<Accounting_Entry__c> generatedAccountingEntries = [select Id, (select Id from Accounting_Entry_Lines__r) from Accounting_Entry__c where Recurring_Accounting_Entry__c = :RAE.Id];
		
		System.assertEquals(1,generatedAccountingEntries.size());
		
		System.assertEquals(2,generatedAccountingEntries[0].Accounting_Entry_Lines__r.size());
		
		result = Service.createAccountingEntryRecurrences(Service.retriveRecurringAccountingEntries(new Period__c[]{testData.periodList[0]}));
		
		System.assertEquals(1,generatedAccountingEntries.size());
		
		System.assertEquals(2,generatedAccountingEntries[0].Accounting_Entry_Lines__r.size());
		
		//Test create a recurring accounting entry from accounting entry
		Map<Id,Recurring_Accounting_Entry__c> RAEMap = new Map<Id,Recurring_Accounting_Entry__c>();
		
		RAEMap.put(AE.Id,new Recurring_Accounting_Entry__c());
		
		List<Recurring_Accounting_Entry__c> response = Service.convertToRecurringAccountingEntry(AEList,RAEMap);
		
		Set<Id> AEIds = new Set<Id>();
		
		for(Accounting_Entry__c record:generatedAccountingEntries){
			
			AEIds.add(record.Id);
			
		}
		
		List<Accounting_Entry__c> AERecords = Service.retrieveAccountingEntries(AEIds);
		
		
		//Create an instance of recurring accounting entry extension
		ApexPages.StandardController STDcontroller = new ApexPages.StandardController(AE);
		RecurringAccountingEntryExtension extension = new RecurringAccountingEntryExtension(STDcontroller);
		
		extension.initCreateRecurringAEfromAE();
		
		PageReference resultPage = extension.createRecurringAEfromAE();
		
		System.assertEquals( new PageReference( '/' + String.valueOf(AE.Id).substring(0,15) ).getUrl(), extension.cancel().getUrl() );
		
		//Create an instance of recurring accounting entry extension with the set controller
		ApexPages.StandardsetController STDSETController = new ApexPages.StandardsetController(testData.periodList);
		
		RecurringAccountingEntryExtension extension2 = new RecurringAccountingEntryExtension(STDSETController);
		
		extension2.initGenerateRAE();
		
		extension2.generateRAE();
		
		STDSETController.setSelected(testData.periodList);
		extension2 = new RecurringAccountingEntryExtension(STDSETController);
		
		extension2.initGenerateRAE();
		
		extension2.generateRAE();
		
		//Test list of accounting entries to review
		STDSETController = new ApexPages.StandardsetController(AEList);
		
		RecurringAccountingEntryExtension extension3 = new RecurringAccountingEntryExtension(STDSETController);
		
		extension3.initReview();
		
		STDSETController.setSelected(AEList);
		extension3 = new RecurringAccountingEntryExtension(STDSETController);
		
		extension3.initReview();
		
		ApexPages.currentPage().getParameters().put('retURL','/'+AE.Id);
		
		extension3.AEWrapperList[0].selected = true;
		
		extension3.saveChanges();
		
		extension3.goReview();
		
		//Create accounting entry
		AEList = new List<Accounting_Entry__c>(); 
		
		AE = new Accounting_Entry__c();
		AE.Company__c = testData.company.id;
		AE.Transaction_Type__c = 'Manual';
		AE.Currency__c = TestFuel.currencyUSD.id;
		AE.Exception__c = false;
		AE.Period__c = testData.periodList[0].id;
		AE.GL_Date__c = System.today();
		//insert AE;
		
		AEList.add(AE);
		insert AEList;
		
		
		AElines = new List<Accounting_Entry_Line__c>();
		
		AELineCR = new Accounting_Entry_Line__c();
		AELineCR.Accounting_Entry__c = AE.Id;
		AELineCR.Amount_CR__c = 125;
		AELineCR.Exception__c = false;
	    AELineCR.GL_Account__c = testData.Acctdata.cashGL.id;
	    AELineCR.Transaction_Date__c = system.today();
	    
	    AElines.add(AELineCR);
	    
	    AELineDR = new Accounting_Entry_Line__c();
	    AELineDR.Accounting_Entry__c = AE.Id;
	    AELineDR.Amount_DR__c = 125;
		AELineDR.Exception__c = false;
	    AELineDR.GL_Account__c = testData.Acctdata.cashGL.id;
	    AELineDR.Transaction_Date__c = system.today();
		
		AElines.add(AELineDR);
		
		
		insert AElines;
		
		List<Period__c> periodList = [select id, Name, Adjustment_Period__c, Corporate__c, Fiscal__c, Fiscal_Year__c, Period_End__c,
                            Period_Number__c, Period_Start__c, Primary_key__c, Quarter_Number__c, Year_End_Date__c, Year_Start_Date__c
                            from Period__c where open__c = true];
                            
		AE.Period__c = periodList[0].id;
		update AE;
		
		STDSETController.setSelected(AEList);
		
		RecurringAccountingEntryExtension extension4 = new RecurringAccountingEntryExtension(STDSETController);
		
		extension4.initReview();
		
		//ApexPages.currentPage().getParameters().put('retURL','/'+AE.Id);
		

		
		
		//Test reverse accounting entries
		Accounting_Entry__c AERev = new Accounting_Entry__c();
		AERev.Company__c = testData.company.id;
		AERev.Currency__c = TestFuel.currencyUSD.id;
		AERev.GL_Date__c = System.today();
		AERev.Reverse_Next_Period__c = true;
		
		insert AERev;
		
		List<Accounting_Entry_Line__c> AElinesRev = new List<Accounting_Entry_Line__c>();
		
		Accounting_Entry_Line__c AELineCRRev = new Accounting_Entry_Line__c();
		AELineCRRev.Accounting_Entry__c = AERev.Id;
		AELineCRRev.Amount_CR__c = 125;
	    AELineCRRev.GL_Account__c = testData.Acctdata.cashGL.id;
	    AELineCRRev.Transaction_Date__c = system.today();
	    
	    AElinesRev.add(AELineCRRev);
	    
	    Accounting_Entry_Line__c AELineDRRev = new Accounting_Entry_Line__c();
	    AELineDRRev.Accounting_Entry__c = AERev.Id;
	    AELineDRRev.Amount_DR__c = 125;
	    AELineDRRev.GL_Account__c = testData.Acctdata.cashGL.id;
	    AELineDRRev.Transaction_Date__c = system.today();
		
		AElinesRev.add(AELineDRRev);
		
		insert AElinesRev;
		
		result = Service.createAccountingEntryRecurrences(Service.retriveRecurringAccountingEntries(new Period__c[]{testData.periodList[1]}));

		
	}
*/
}