src-ken&y/objects/Accounting_Entry__c.object
<CustomObject>
    <customHelpPage>HelpAccountingEntries</customHelpPage>
    <description>Accounting Entry Header records</description>
    <fields>
        <fullName>Bank_Transaction_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bank Transaction Group</label>
        <referenceTo>Bank_Transaction_Group__c</referenceTo>
        <relationshipLabel>Accounting Entries</relationshipLabel>
        <relationshipName>Accounting_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Accounting Entries</relationshipLabel>
        <relationshipName>Accounting_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Finalized_Date__c</fullName>
        <description>Finalized Date for the associated source document.</description>
        <label>Finalized Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Has_Exceptions__c</fullName>
        <formula>OR(
Exceptions_Count__c &gt; 0,
Line_Exceptions__c &gt; 0
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Has Exceptions</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <description>Transaction date for the associated source document.</description>
        <label>Transaction Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Validation_Ready__c</fullName>
        <formula>AND( 
ISPICKVAL(Status__c, &apos;Active&apos;), 

Period__r.Open__c,

OR( 

AND( 
OR( 
NOT(ISBLANK(Customer_Invoice__c)), 
NOT(ISBLANK(Bank_Transaction_Group__c)),  
NOT(ISBLANK(Customer_Receipt__c)) 
), 
ISNULL(Period__r.AR_Subledger_Closed__c), 
NOW() &gt;= IF(ISNULL(Period__r.AR_Valid_After__c), Period__r.AR_Subledger_Cutoff__c, Period__r.AR_Valid_After__c) 
), 

AND( 
OR( 
NOT(ISBLANK(Supplier_Invoice__c)), 
NOT(ISBLANK(Supplier_Payment__c))
),
ISNULL(Period__r.AP_Subledger_Closed__c), 
NOW() &gt;= IF(ISNULL(Period__r.AP_Valid_After__c), Period__r.AP_Subledger_Cutoff__c, Period__r.AP_Valid_After__c) 
), 

AND( 
OR( 
NOT(ISBLANK(Work_Order__c)), 
NOT(ISBLANK(Inventory_Change__c)) 
), 
ISNULL(Period__r.Inventory_Subledger_Closed__c), 
NOW() &gt;= IF(ISNULL(Period__r.Inventory_Valid_After__c), Period__r.Inventory_Subledger_Cutoff__c, Period__r.Inventory_Valid_After__c) 
), 

AND( 
OR( 
NOT(ISBLANK(Fixed_Asset_Adjustment__c)), 
NOT(ISBLANK(Fixed_Asset_Depreciation__c)) 
), 
ISNULL(Period__r.FA_Subledger_Closed__c), 
NOW() &gt;= IF(ISNULL(Period__r.FA_Valid_After__c), Period__r.FA_Subledger_Cutoff__c, Period__r.FA_Valid_After__c) 
), 

AND( 
NOT(ISBLANK(Shipment__c)), 
ISNULL(Period__r.Shipment_Subledger_Closed__c), 
NOW() &gt;= IF(ISNULL(Period__r.Shipment_Valid_After__c), Period__r.Shipment_Subledger_Cutoff__c, Period__r.Shipment_Valid_After__c) 
), 

AND( 
NOT(ISBLANK(Receiving_Document__c)), 
ISNULL(Period__r.Receiving_Subledger_Closed__c), 
NOW() &gt;= IF(ISNULL(Period__r.Receiving_Valid_After__c), Period__r.Receiving_Subledger_Cutoff__c, Period__r.Receiving_Valid_After__c) 
), 

AND( 
NOT(ISBLANK(Journal_Entry__c)), 
ISNULL(Period__r.GL_Close__c), 
NOW() &gt;= IF(ISNULL(Period__r.JE_Valid_After__c), Period__r.JE_Cutoff__c, Period__r.JE_Valid_After__c) 
) 

, 

AND( 
OR( 
NOT(ISBLANK(Invoice__c)), 
NOT(ISBLANK(Payment__c)) 
), 
ISNULL(Period__r.InterCompany_Subledger_Closed__c), 
NOW() &gt;= IF(ISNULL(Period__r.InterCompany_Valid_After__c), Period__r.InterCompany_Subledger_Cutoff__c, Period__r.InterCompany_Valid_After__c) 
) 

) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Validation Ready</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isValidated__c</fullName>
        <formula>AND(
ISPICKVAL(Status__c, &apos;Active&apos;),

NOT(Has_Exceptions__c),

OR(

AND(
OR(
NOT(ISBLANK(Customer_Invoice__c)),
NOT(ISBLANK(Bank_Transaction_Group__c)),  
NOT(ISBLANK(Customer_Receipt__c))
),
IF(ISNULL(Last_Validated__c), LastModifiedDate, Last_Validated__c) &gt;=  IF(ISNULL(Period__r.AR_Valid_After__c), Period__r.AR_Subledger_Cutoff__c, Period__r.AR_Valid_After__c)
),

AND(
OR(
NOT(ISBLANK(Supplier_Invoice__c)),
NOT(ISBLANK(Supplier_Payment__c))
),
IF(ISNULL(Last_Validated__c), LastModifiedDate, Last_Validated__c) &gt;=  IF(ISNULL(Period__r.AP_Valid_After__c), Period__r.AP_Subledger_Cutoff__c, Period__r.AP_Valid_After__c)
),

AND(
OR(
NOT(ISBLANK(Work_Order__c)),
NOT(ISBLANK(Inventory_Change__c))
),
IF(ISNULL(Last_Validated__c), LastModifiedDate, Last_Validated__c) &gt;=  IF(ISNULL(Period__r.Inventory_Valid_After__c), Period__r.Inventory_Subledger_Cutoff__c, Period__r.Inventory_Valid_After__c)
),

AND(
OR(
NOT(ISBLANK(Fixed_Asset_Adjustment__c)),
NOT(ISBLANK(Fixed_Asset_Depreciation__c))
),
IF(ISNULL(Last_Validated__c), LastModifiedDate, Last_Validated__c) &gt;=  IF(ISNULL(Period__r.FA_Valid_After__c), Period__r.FA_Subledger_Cutoff__c, Period__r.FA_Valid_After__c)
),

AND(
NOT(ISBLANK(Shipment__c)),
IF(ISNULL(Last_Validated__c), LastModifiedDate, Last_Validated__c) &gt;=  IF(ISNULL(Period__r.Shipment_Valid_After__c), Period__r.Shipment_Subledger_Cutoff__c, Period__r.Shipment_Valid_After__c)
),

AND(
NOT(ISBLANK(Receiving_Document__c)),
IF(ISNULL(Last_Validated__c), LastModifiedDate, Last_Validated__c) &gt;=  IF(ISNULL(Period__r.Receiving_Valid_After__c), Period__r.Receiving_Subledger_Cutoff__c, Period__r.Receiving_Valid_After__c)
),

AND(
NOT(ISBLANK(Journal_Entry__c)),
IF(ISNULL(Last_Validated__c), LastModifiedDate, Last_Validated__c) &gt;=  IF(ISNULL(Period__r.JE_Valid_After__c), Period__r.JE_Cutoff__c, Period__r.JE_Valid_After__c)
),

AND(
OR(
NOT(ISBLANK(Invoice__c)),
NOT(ISBLANK(Payment__c))
),
IF(ISNULL(Last_Validated__c), LastModifiedDate, Last_Validated__c) &gt;=  IF(ISNULL(Period__r.InterCompany_Valid_After__c), Period__r.InterCompany_Subledger_Cutoff__c, Period__r.InterCompany_Valid_After__c)
)

)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Validated</label>
        <type>Checkbox</type>
    </fields>
    <label>Accounting Entry</label>
    <nameField>
        <label>Accounting Entry</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Bank_Transaction__c.object
<CustomObject>
    <customHelpPage>HelpManageBankTransactions</customHelpPage>
    <fields>
        <fullName>Bank_Transaction_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Bank transaction group for bank transactions</description>
        <label>Bank Transaction Group</label>
        <referenceTo>Bank_Transaction_Group__c</referenceTo>
        <relationshipLabel>Bank Transactions</relationshipLabel>
        <relationshipName>Bank_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Bank Transactions</relationshipLabel>
        <relationshipName>Bank_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Finalized__c</fullName>
        <formula>Bank_Transaction_Group__r.Finalized__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Finalized</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Exceptions__c</fullName>
        <formula>Exceptions_Count__c &gt; 0</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Has Exceptions</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Historical__c</fullName>
        <formula>Bank_Transaction_Group__r.Historical__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Historical</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>TEXT(Bank_Transaction_Group__r.Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <description>Date/time transaction cleared bank</description>
        <label>Transaction Date</label>
        <type>DateTime</type>
    </fields>
    <label>Bank Transaction</label>
    <nameField>
        <label>Bank Transaction</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Bank_Transaction_Group__c.object
<CustomObject>
    <customHelpPage>HelpManageBankTransactions</customHelpPage>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Bank Transaction Groups</relationshipLabel>
        <relationshipName>Bank_Transaction_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Finalized_Date__c</fullName>
        <description>Date bank transaction group was finalized</description>
        <label>Finalized Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Finalized__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag indicating finalized</description>
        <label>Finalized</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Exceptions__c</fullName>
        <formula>OR(

Exceptions_Count__c &gt; 0,

Line_Exceptions__c &gt; 0

)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Has Exceptions</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Historical__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Historical</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <label>Transaction Date</label>
        <type>DateTime</type>
    </fields>
    <label>Bank Transaction Group</label>
    <nameField>
        <label>Bank Transaction Group</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Transaction Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Company__c.object
<CustomObject>
    <customHelpPage>HelpCompany</customHelpPage>
    <description>Each Logistics or Financial entity will be represented by a single Company record.  Master data for the Company is recorded here and used throughout the System.</description>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/BankTransactionGroupAccountingBatch.cls
/*
* without sharing is intentional.  accounting needs to be run in system mode.
*/
public without sharing class BankTransactionGroupAccountingBatch extends AccountingBatchBaseClass  {
     public BankTransactionGroupAccountingBatch()
        {
             super('Bank_Transaction_Group__c');
           
        }

    public BankTransactionGroupAccountingBatch(set<Id> operatingCompIds){
        super('Bank_Transaction_Group__c');
        operatingCompanyIds = operatingCompIds;
        

    }    
    //Override abstract method of super to query for specifics with respect to source doc
    public override void createBaseQuery(){
        BaseQuery='SELECT Id, Bank_Transaction_Group__c '
   			    + ' FROM Bank_Transaction__c ';
    }
                                                
    public override void createwhereClause()
    {
    	
    	whereclause=    'WHERE Bank_Transaction_Group__r.Company__c IN :operatingCompanyIds '
	   			+ ' AND Finalized__c = true '
	   			+ ' AND Historical__c = false '
	   			+ ' AND Bank_Transaction_Group__r.Finalized_Date__c != null '
	   			+ ' AND Bank_Transaction_Group__r.Transaction_Date__c != null ';
	   			
    	if(processJob != null){
    		
    		if(processJob.Max_Records__c != null){
    			
	    		integer limitRecs = (integer)processJob.Max_Records__c;
	    		limitRecs = limitRecs < 1 ? 1 : limitRecs;
	    		limitRecs = limitRecs > LIMITS.getLimitQueryRows() ? LIMITS.getLimitQueryRows() : limitRecs;
    			
    			system.debug('limitRecs: ' + limitRecs);
    		
	    		Map<Id, Bank_Transaction_Group__c> mNewBtgs 
						= new Map<Id, Bank_Transaction_Group__c>(
	    											(List<Bank_Transaction_Group__c>)Database.Query(
	    											'SELECT Id '
	    											+' FROM Bank_Transaction_Group__c '
	    											+' WHERE Finalized__c = true AND Historical__c = false AND Company__c IN :operatingCompanyIds ' 
	    											+' AND Id NOT IN (SELECT Bank_Transaction_Group__c '  
	    																	+ ' FROM Accounting_Entry__c ' 
	    																	+ ' WHERE Company__c IN :operatingCompanyIds ' 
	    																	+ ' AND has_exceptions__c = false ' 
	    																	+ ' AND status__c = \'Active\''
	    																	+ ' AND Bank_Transaction_Group__c != null ) '
													+ ' LIMIT ' + string.valueOf(limitRecs)));
	    											
	    		recordIds.addAll(mNewBtgs.keySet());
    		
	    		integer incrementalLimit = (integer)processJob.Max_Records__c - recordIds.size();
	    		incrementalLimit = (LIMITS.getLimitQueryRows() - LIMITS.getQueryRows()) < incrementalLimit ? (LIMITS.getLimitQueryRows() - LIMITS.getQueryRows()) : incrementalLimit;
	    		system.debug('incrementalLimit: ' + incrementalLimit);
	    		
	    		string aeQuery = 'SELECT Bank_Transaction_Group__c '
	    					+ ' FROM Accounting_Entry__c '
	    					+ ' WHERE Status__c = \'Active\' '
	    					+ ' AND isValidated__c = false '
	    				 	+ ' AND Validation_Ready__c = true '
	    				 	+ ' AND Bank_Transaction_Group__c != null '
	    				 	+ ' ORDER BY LastModifiedDate asc '
	    				 	+ ' LIMIT ' +  string.valueOf(incrementalLimit);
	    				 	
		    	List<Accounting_Entry__c> incrementalBTGs = Database.query(aeQuery);
		    	for(Accounting_Entry__c ae : incrementalBTGs){
		    		recordIds.add(ae.Bank_Transaction_Group__c);
		    	}
    		}
	    	
    	}
    	
    	system.debug('recordIds: ' + recordIds);	
		if(recordIds.size() > 0){
			whereClause += ' AND Bank_Transaction_Group__c IN :recordIds';
		}else{
			whereClause += ' AND Bank_Transaction_Group__c NOT IN (SELECT Bank_Transaction_Group__c FROM Accounting_Entry__c WHERE Company__c IN :operatingCompanyIds AND has_exceptions__c = false AND status__c = \'Active\') ';
		}

    }
}