src-ken&y/objects/Accounting_Entry__c.object
<CustomObject>
    <customHelpPage>HelpAccountingEntries</customHelpPage>
    <description>Accounting Entry Header records</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Accounting Entries</relationshipLabel>
        <relationshipName>Accounting_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Accounting Entries</relationshipLabel>
        <relationshipName>Accounting_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Customer invoice</description>
        <label>Customer Invoice</label>
        <referenceTo>Customer_Invoice__c</referenceTo>
        <relationshipLabel>Accounting Entries</relationshipLabel>
        <relationshipName>Accounting_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <description>Select the transaction type of the original transaction</description>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Manual</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Accounting Entry</label>
    <nameField>
        <label>Accounting Entry</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Currency__c.object
<CustomObject>
    <customHelpPage>HelpCurrency</customHelpPage>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Currency</label>
    <nameField>
        <label>Currency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Customer_Invoice__c.object
<CustomObject>
    <customHelpPage>HelpCustomerInvoice</customHelpPage>
    <description>Customer invoices</description>
    <fields>
        <fullName>Apply_to_Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Customer Invoice that the Credit Memo is applied to</description>
        <label>Apply to Invoice</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Customer_Invoice__c.Bill_To_Customer__c</field>
                <operation>equals</operation>
                <valueField>$Source.Bill_To_Customer__c</valueField>
            </filterItems>
            <filterItems>
                <field>Customer_Invoice__c.Invoice_Type__c</field>
                <operation>notEqual</operation>
                <value>Credit Memo</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Customer_Invoice__c</referenceTo>
        <relationshipLabel>Customer Credit Memos</relationshipLabel>
        <relationshipName>Customer_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Customer Invoices</relationshipLabel>
        <relationshipName>Ship_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Customer Invoices</relationshipLabel>
        <relationshipName>Customer_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Invoiced__c</fullName>
        <description>Date of invoice</description>
        <label>Invoice Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Finalized__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Once the invoice is finalized the record is eligible to generate accounting entries.</description>
        <label>Finalized</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Total_Sales_Tax__c</fullName>
        <label>Sales Tax Amount</label>
        <summarizedField>Customer_Invoice_Line__c.Sales_Tax__c</summarizedField>
        <summaryForeignKey>Customer_Invoice_Line__c.Customer_Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <description>Accounting process uses this field as one of the criteria to determine the accounting rule to be used to book this transaction.</description>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>--None--</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Invoice</label>
    <nameField>
        <label>Customer Invoice</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Customer_Invoice_Line__c.object
<CustomObject>
    <customHelpPage>HelpCustomerInvoice</customHelpPage>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Company.</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipName>Customer_Transaction_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <formula>Customer_Invoice__r.Currency__r.ISO_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Currency</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Invoice__c</fullName>
        <label>Customer Invoice</label>
        <referenceTo>Customer_Invoice__c</referenceTo>
        <relationshipLabel>Customer Invoice Lines</relationshipLabel>
        <relationshipName>Customer_Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Finalized__c</fullName>
        <formula>Customer_Invoice__r.Finalized__c</formula>
        <label>Finalized</label>
        <type>Checkbox</type>
    </fields>
    <label>Customer Invoice Line</label>
    <nameField>
        <label>Customer Invoice Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Item__c.object
<CustomObject>
    <customHelpPage>HelpItems</customHelpPage>
    <description>Item Master object</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company that controls this item</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Product__c.object
<CustomObject>
    <customHelpPage>HelpProducts</customHelpPage>
    <description>Products are sellable Items with Selling Unit of Measure included</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Sales_Order__c.object
<CustomObject>
    <customHelpPage>HelpSalesOrders_Managing</customHelpPage>
    <description>Sales Order Header</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to currency</description>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Sales Order Currency</relationshipLabel>
        <relationshipName>Sales_Order_Currency</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Adjustment</fullName>
                </value>
                <value>
                    <fullName>RMA-Credit</fullName>
                </value>
                <value>
                    <fullName>RMA-Customer-Repair</fullName>
                </value>
                <value>
                    <fullName>RMA-Replacement</fullName>
                </value>
                <value>
                    <fullName>Resale</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Sales_Order_Line__c.object
<CustomObject>
    <customHelpPage>HelpSalesOrders_Managing</customHelpPage>
    <description>Line Items on the Sales Order.</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company passed down from the sales order header</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <formula>Sales_Order__r.Currency__r.ISO_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Currency</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type indicates the sales order line type. (eg. RMA, Kit, Kit-Child, etc...). Based on the value the Sales order line flow is controlled through different status.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>RMA</fullName>
                </value>
                <value>
                    <fullName>Kit</fullName>
                </value>
                <value>
                    <fullName>Kit-Child</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <label>Sales Order Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Shipment_Line__c.object
<CustomObject>
    <customHelpPage>HelpShipment</customHelpPage>
    <description>Shipment lines.</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company associated with this shipment invoice line</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Shipment Lines</relationshipLabel>
        <relationshipName>Shipment_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Finalized__c</fullName>
        <description>Indicates if the header is finalized.</description>
        <formula>Shipment__r.Finalized__c</formula>
        <inlineHelpText>A check mark indicates that the document is final. Kenandy will automatically generate an accounting entry for it in the next scheduled batch process.</inlineHelpText>
        <label>Finalized</label>
        <type>Checkbox</type>
    </fields>
    <label>Shipment Line</label>
    <nameField>
        <label>Shipment Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipment Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/classes/CustomerInvoiceAccountingExt.cls
public with sharing class CustomerInvoiceAccountingExt {
    
    public ApexPages.StandardSetController setcon{get; set;}
    public Boolean selecterror {get; set;} { selecterror = false; } 
    public Boolean requiredFielderror {get; set;} { requiredFielderror = false; } 
    public Boolean BatchInitiated {get; set;} { BatchInitiated = false; } 
    
    public list<Customer_Invoice__c> objectList {get;set;}
    set<ID> invoiceIDs = new set<ID>();
    //GenerateAccountingService GAS = new GenerateAccountingService();
    List<Accounting_Entry__c> acctEntryList = new List<Accounting_Entry__c>();
    List<Accounting_Entry__c> acctEntryListCM = new List<Accounting_Entry__c>();
    AccountingRuleService ARS = new AccountingRuleService();
     
    public CustomerInvoiceAccountingExt(ApexPages.StandardSetController controller) {     
        
        setcon = controller;
        
        if ( ! Schema.sObjectType.Customer_Invoice__c.isCreateable() ) {
		      ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL,
	                                               	Label.Insufficient_access_to_create_Customer_Invoice));
			requiredFielderror = true;
			return;
	    }
	    
        if (setCon.getSelected().size() == 0) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.FATAL, Label.No_records_selected) );
            selecterror = true;
            return;
        }
        
        for (Customer_Invoice__c invoice: (List<Customer_Invoice__c>)setCon.getSelected() ) {      
            invoiceIDs.add(invoice.ID);
        }

        //String dynamicQuery = ARS.getQueryStringList(new List<String>{'Customer Invoice','Adjustment','Customer Credit Memo'});

        //String hdrdynamicQuery = ARS.getQueryStringList(new List<String>{'Customer Credit Memo'});
        
        String objectFieldString = 'id, Name, Date_Invoiced__c, Company__c, Finalized__c, Total_Sales_Tax__c, Currency__c, transaction_type__c, '+
        						'Apply_to_Invoice__c, Invoice_Type__c,Bill_To_Customer__c,Sold_To_Customer__c, Subtotal__c';
		String subQueryFieldString = 'id, Name, Discount_Percent__c, Extended_Price__c,'+
                                ' Product__r.Item__c, Quantity_Shipped__c,  '+
                                ' Unit_Price__c, Shipment_Line__r.Sales_Order_Line__r.Sales_Order__r.id,'+
                                ' Customer_Invoice__r.Total_Sales_Tax__c, Shipment_Line__r.Sales_Order__r.Type__c, Shipment_Line__c,'+
                                'Shipment_Line__r.Sales_Order__r.Company__c, Customer_Invoice__r.Date_Invoiced__c,Customer_Invoice__r.Finalized__c, Customer_Invoice__r.Sales_Order__r.Type__c';
								//(dynamicQuery != null? ','+dynamicQuery : '')+
								//(hdrdynamicQuery != null? ','+hdrdynamicQuery : '')+
        String whereClause = 'id in :invoiceIDs'+
                            ' and Finalized__c = true' +
                            ' and transaction_date__c != null '+
                            ' and finalized_date__c != null ' +
                            ' and id not in ( Select Customer_Invoice__c from Accounting_Entry__c where Customer_Invoice__c in :invoiceIDs AND related_accounting_entry__c = null AND has_exceptions__c = false AND status__c = \'Active\') ';
        // TODO: put try catch for the query
        Set<String> objectFieldPaths = new Set<String>(objectFieldString.split(','));
        Set<String> subQueryFieldPaths = new Set<String>(subQueryFieldString.split(','));

        SOQLUtil soql = new SOQLUtil('Customer_Invoice__c', TRUE);
        soql.addFields(objectFieldPaths);
        soql.setWhereClause(whereClause);

        SOQLUtil.ChildRelationship childRel = new SOQLUtil.ChildRelationship(soql, 'Customer_Invoice_Lines__r');
        childRel.addFields(subQueryFieldPaths);

        soql.addChildRelationship(childRel);

		objectList = Database.query (soql.getQuery());
		
        if (selecterror ) {
            return ;
        }
        
        list<string> transactionTypeList = new list<string>();
        
        for(Customer_Invoice__c ci: (list<Customer_Invoice__c>)objectList){
        		if(ci.transaction_type__c != null && ci.transaction_type__c != '')
        			transactionTypeList.add(ci.transaction_type__c);
        		else
        			transactionTypeList.add(ci.invoice_type__c);
        			
        }
        if(!ARS.isRuleDefined(new List<String>{'Customer_Invoice__c'}, transactionTypeList)){
        	ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.FATAL, Label.Create_Accounting_Rules));
    		requiredFielderror = true;
        	selecterror = true;
        	return;
        }
        if(objectList == null || objectList.size() < 1){
        	ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.FATAL, Label.No_eligible_records_to_process ) );
        	requiredFielderror = true;
          	selecterror = true;
        	return;
        }
        for(integer i = 0; i < objectList.size(); i++){
        	if(objectList[i].Date_Invoiced__c == null){
        		ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.FATAL, Label.Date_Invoiced_is_blank + objectList[i].Name ) );
        		requiredFielderror = true;
            	selecterror = true;
            	return;
        	}
        	if(objectList[i].Currency__c == null){
        		ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.FATAL, Label.Transaction_Currency_is_blank + objectList[i].Name ) );
        		requiredFielderror = true;
            	selecterror = true;
            	return;
        	}
        	if(objectList[i].Company__c == null){
        		ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.FATAL, Label.Company_is_blank + objectList[i].Name ) );
        		requiredFielderror = true;
            	selecterror = true;
            	return;
        	}
        }
        
    } // End of Constructor
    
    
    //Function to generate the accounting entries for the invoice lines
    public pagereference GenerateCustomerInvoiceAccounting() {
        Map<Id,Customer_Invoice__c> invoiceMapUpd = new Map<Id,Customer_Invoice__c>();
        Map<Id,Customer_Invoice__c> invoiceMapUpdCM = new Map<Id,Customer_Invoice__c>();
        If(objectList != null && objectList.size() > 0){
        	Savepoint sp = Database.setSavepoint();
        	try{
	            	//GAS.createCustInvoiceAccounting(objectList);
	            	//CustomerInvoiceAccounting cia = new CustomerInvoiceAccounting();
	            	//cia.execute(objectList);
	            	// KNDY 2196 - Changed the approach to update the Accounted flag on source document.
	            	// FIN-758 Invoke Batch
	            	
                     //Create a stub header
                    //AccountingService.upsertAccountingEntry(objectList);   
                           
                    set<Id> sourceDocIds = new set<Id>();
                    set<Id> companyIds = new set<Id>();   
                    for(Customer_Invoice__c ci : objectList){
                        companyIds.add(ci.company__c);
                        sourceDocIds.add(ci.Id);
                    }             
                    CustomerInvoiceAccountingBatch  batch = new CustomerInvoiceAccountingBatch(companyIds);
                    batch.setSourceDocId(sourceDocIds);
                    batch.setuseSuperWhere(true);
                    string jobid= Database.ExecuteBatch(batch);  
                

                    ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.INFO, 'Batch Job '+ jobid+ ' has been initiated.' ) );
                    BatchInitiated=true;   
	            	
	            					
            	} catch(Exception e) {
            		Database.rollback(sp);
                	selecterror = true;
                	ApexPages.addMessages(e);
                	return null;
            	}
        }
        //KNDY-2020 Checking for Pg msgs before moving the page forward. Hiding the button if any error or fatal msgs
        if (Apexpages.hasMessages(ApexPages.Severity.FATAL) || Apexpages.hasMessages(ApexPages.Severity.ERROR)){
        	requiredFielderror = true;
        	selecterror = true;
        	
        }
        return (Apexpages.hasMessages() ? null : this.setcon.cancel() ); 
        //return setcon.cancel();
       
    } 
	
}