src-ken&y/objects/Accounting_Entry__c.object
<CustomObject>
    <customHelpPage>HelpAccountingEntries</customHelpPage>
    <description>Accounting Entry Header records</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Accounting Entries</relationshipLabel>
        <relationshipName>Accounting_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Accounting Entries</relationshipLabel>
        <relationshipName>Accounting_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Customer invoice</description>
        <label>Customer Invoice</label>
        <referenceTo>Customer_Invoice__c</referenceTo>
        <relationshipLabel>Accounting Entries</relationshipLabel>
        <relationshipName>Accounting_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Period</description>
        <label>Period</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Period__c.Open__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Period__c</referenceTo>
        <relationshipLabel>Accounting_Entries</relationshipLabel>
        <relationshipName>Accounting_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <description>Transaction date for the associated source document.</description>
        <label>Transaction Date</label>
        <type>DateTime</type>
    </fields>
    <label>Accounting Entry</label>
    <nameField>
        <label>Accounting Entry</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Company__c.object
<CustomObject>
    <customHelpPage>HelpCompany</customHelpPage>
    <description>Each Logistics or Financial entity will be represented by a single Company record.  Master data for the Company is recorded here and used throughout the System.</description>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Currency__c.object
<CustomObject>
    <customHelpPage>HelpCurrency</customHelpPage>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Currency</label>
    <nameField>
        <label>Currency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Customer_Invoice__c.object
<CustomObject>
    <customHelpPage>HelpCustomerInvoice</customHelpPage>
    <description>Customer invoices</description>
    <fields>
        <fullName>Bill_To_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Bill To Customer</description>
        <label>Bill To Customer</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <filterItems>
                <field>Customer__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Bill To</value>
            </filterItems>
            <filterItems>
                <field>Customer__c.Parent_Customer__c</field>
                <operation>equals</operation>
                <valueField>$Source.Customer__c</valueField>
            </filterItems>
            <filterItems>
                <field>Customer__c.Top_Parent_Customer__c</field>
                <operation>equals</operation>
                <valueField>$Source.Customer__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Customer Invoices (Bill To Customer)</relationshipLabel>
        <relationshipName>Bill_To_Customer_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Customer Invoices</relationshipLabel>
        <relationshipName>Ship_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Customer Invoices</relationshipLabel>
        <relationshipName>Customer_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Invoiced__c</fullName>
        <description>Date of invoice</description>
        <label>Invoice Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Finalized__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Once the invoice is finalized the record is eligible to generate accounting entries.</description>
        <label>Finalized</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoice_Type__c</fullName>
        <description>Select the invoice type</description>
        <label>Invoice Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Manual</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Overpayment</fullName>
                </value>
                <value>
                    <fullName>Prepayment</fullName>
                </value>
                <value>
                    <fullName>Ship Invoice</fullName>
                </value>
                <value>
                    <fullName>Allowance Accrual</fullName>
                </value>
                <value>
                    <fullName>RMA-Credit</fullName>
                </value>
                <value>
                    <fullName>Standard</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sold_To_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Sold To Customer</description>
        <label>Sold To Customer</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <filterItems>
                <field>Customer__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Sold To</value>
            </filterItems>
            <filterItems>
                <field>Customer__c.Parent_Customer__c</field>
                <operation>equals</operation>
                <valueField>$Source.Bill_To_Customer__c</valueField>
            </filterItems>
            <filterItems>
                <field>Customer__c.Top_Parent_Customer__c</field>
                <operation>equals</operation>
                <valueField>$Source.Customer__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Customer Invoices (Sold To Customer)</relationshipLabel>
        <relationshipName>Sold_To_Customer_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subtotal__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Total amount of all lines ( Sum(Extended_Price__c) for all invoice detail lines for the invoice)</description>
        <inlineHelpText>Total amount of all lines.</inlineHelpText>
        <label>Subtotal</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <description>Date of the transaction, this could be populated from any source using a workflow depending on customer need.</description>
        <inlineHelpText>Date of the transaction. Can be populated from any source using a workflow.</inlineHelpText>
        <label>Transaction Date</label>
        <type>DateTime</type>
    </fields>
    <label>Customer Invoice</label>
    <nameField>
        <label>Customer Invoice</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Customer_Invoice_Line__c.object
<CustomObject>
    <customHelpPage>HelpCustomerInvoice</customHelpPage>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Company.</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipName>Customer_Transaction_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <formula>Customer_Invoice__r.Currency__r.ISO_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Currency</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Invoice__c</fullName>
        <label>Customer Invoice</label>
        <referenceTo>Customer_Invoice__c</referenceTo>
        <relationshipLabel>Customer Invoice Lines</relationshipLabel>
        <relationshipName>Customer_Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Discount_Percent__c</fullName>
        <label>Discount Percent</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Extended_Price__c</fullName>
        <label>Extended Price</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Finalized__c</fullName>
        <formula>Customer_Invoice__r.Finalized__c</formula>
        <label>Finalized</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipName>Customer_Transaction_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity_Shipped__c</fullName>
        <label>Quantity Fulfilled</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <label>Customer Invoice Line</label>
    <nameField>
        <label>Customer Invoice Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Period__c.object
<CustomObject>
    <customHelpPage>HelpPeriods</customHelpPage>
    <description>Segment of time that financial entries fall into</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Periods</relationshipLabel>
        <relationshipName>Periods</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Period_End__c</fullName>
        <description>Period End is the date and time when the period actually ends.</description>
        <label>Period End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Period_Start__c</fullName>
        <description>Period Start is date and time when this period actually starts.</description>
        <label>Period Start</label>
        <type>DateTime</type>
    </fields>
    <label>Period</label>
    <nameField>
        <label>Period</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Product__c.object
<CustomObject>
    <customHelpPage>HelpProducts</customHelpPage>
    <description>Products are sellable Items with Selling Unit of Measure included</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/SubledgerServiceTest.cls
@isTest
public class SubledgerServiceTest {
    
    public static testMethod void testSubledgers(){
        
        TestFuel fuel = new TestFuel();
        
        List<Period__c> periods = fuel.periodList;
        Period__c p = periods[0];
        
        test.startTest();
        
        SubledgerService.isOpenForValidation(SubledgerService.Subledger.AR, p, null,true);
        SubledgerService.isOpenForValidation(SubledgerService.Subledger.AP, p, null,true);
        SubledgerService.isOpenForValidation(SubledgerService.Subledger.RECEIVING, p, null,true);
        SubledgerService.isOpenForValidation(SubledgerService.Subledger.SHIPMENT, p, null,true);
        SubledgerService.isOpenForValidation(SubledgerService.Subledger.INVENTORY, p, null,true);
        SubledgerService.isOpenForValidation(SubledgerService.Subledger.FA, p, null,true);
        SubledgerService.isOpenForValidation(SubledgerService.Subledger.PERIOD, p, null,true);
        
        test.stopTest();
    }
    
    
    public static testMethod void testMultiCompany(){
    	
    	TestFuel fuel1 = new TestFuel();
    	List<Period__c> periods1 = fuel1.periodList;
    	Period__c p1;
    	for(Period__c p : periods1){
    		if(p.period_start__c <= system.now() && p.period_end__c > system.now()){
    			p1 = p;
    			break;
    		}
    	}
        
        Customer_Invoice__c custInv1 = new Customer_Invoice__c();
	    custInv1.Company__c = fuel1.company.id;
	    custInv1.Invoice_Type__c = 'Manual';
	    custInv1.Date_Invoiced__c = System.today();
	    custInv1.Sold_To_Customer__c = fuel1.customerSoldTo.id;
	    custInv1.Bill_To_Customer__c = fuel1.customerBillTo.id;
	    custInv1.Subtotal__c = 0;
	    custInv1.transaction_date__c = system.now();
	    custInv1.Currency__c = TestFuel.currencyUSD.id;
	    
	    insert custInv1;
	    
	    Customer_Invoice_Line__c custInvLine1 = new Customer_Invoice_Line__c();
	    custInvLine1.Company__c = fuel1.company.id;
	    custInvLine1.Quantity_Shipped__c = 2;
	    custInvLine1.Unit_Price__c = 7;
	    custInvLine1.Product__c = fuel1.product.id; 
	    custInvLine1.Discount_Percent__c = 0.2;
	    custInvLine1.Customer_Invoice__c = custInv1.id;
	    custInvLine1.Extended_Price__c = custInvLine1.Quantity_Shipped__c * custInvLine1.Unit_Price__c;
        insert custInvLine1;
        
        custInv1.finalized__c = true;
        update custInv1;

		List<Period__c> periods2 = fuel1.altCompanyPeriodList;
        Period__c p2;
        for(Period__c p : periods2){
    		if(p.period_start__c <= system.now() && p.period_end__c > system.now()){
    			p2 = p;
    			break;
    		}
    	}
        
     	test.startTest();
        system.assert(p1.period_start__c <= custInv1.Transaction_Date__c && custInv1.Transaction_Date__c < p1.period_end__c);
        
        List<Accounting_Entry__c> aes = [SELECT Id FROM Accounting_Entry__c WHERE Customer_Invoice__c = :custInv1.Id];
        system.assertEquals(0, aes.size(), aes);
        
        boolean ar1 = SubledgerService.isOpenForValidation(SubledgerService.Subledger.AR, p1, null,false);
        system.assertEquals(false, ar1, 'This subledger should not be open for validation');
        SubledgerService.isOpenForValidation(SubledgerService.Subledger.AP, p1, null,false);
        SubledgerService.isOpenForValidation(SubledgerService.Subledger.RECEIVING, p1, null,false);
        SubledgerService.isOpenForValidation(SubledgerService.Subledger.SHIPMENT, p1, null,false);
        SubledgerService.isOpenForValidation(SubledgerService.Subledger.INVENTORY, p1, null,false);
        SubledgerService.isOpenForValidation(SubledgerService.Subledger.FA, p1, null,false);
        SubledgerService.isOpenForValidation(SubledgerService.Subledger.PERIOD, p1, null,false);
        
        boolean ar2 = SubledgerService.isOpenForValidation(SubledgerService.Subledger.AR, p2, null,false);
        SubledgerService.isOpenForValidation(SubledgerService.Subledger.AP, p2, null,false);
        SubledgerService.isOpenForValidation(SubledgerService.Subledger.RECEIVING, p2, null,false);
        SubledgerService.isOpenForValidation(SubledgerService.Subledger.SHIPMENT, p2, null,false);
        SubledgerService.isOpenForValidation(SubledgerService.Subledger.INVENTORY, p2, null,false);
        SubledgerService.isOpenForValidation(SubledgerService.Subledger.FA, p2, null,false);
        SubledgerService.isOpenForValidation(SubledgerService.Subledger.PERIOD, p2, null,false);
        
        test.stopTest();
        
        
    }
}