src-ken&y/objects/Accounting_Entry__c.object
<CustomObject>
    <customHelpPage>HelpAccountingEntries</customHelpPage>
    <description>Accounting Entry Header records</description>
    <fields>
        <fullName>Bank_Transaction_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bank Transaction Group</label>
        <referenceTo>Bank_Transaction_Group__c</referenceTo>
        <relationshipLabel>Accounting Entries</relationshipLabel>
        <relationshipName>Accounting_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Accounting Entries</relationshipLabel>
        <relationshipName>Accounting_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Finalized_Date__c</fullName>
        <description>Finalized Date for the associated source document.</description>
        <label>Finalized Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Has_Exceptions__c</fullName>
        <formula>OR(
Exceptions_Count__c &gt; 0,
Line_Exceptions__c &gt; 0
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Has Exceptions</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <description>Transaction date for the associated source document.</description>
        <label>Transaction Date</label>
        <type>DateTime</type>
    </fields>
    <label>Accounting Entry</label>
    <nameField>
        <label>Accounting Entry</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Accounting_Entry_Line__c.object
<CustomObject>
    <customHelpPage>HelpAccountingEntries</customHelpPage>
    <description>Accounting Entry Lines</description>
    <fields>
        <fullName>Accounting_Entry__c</fullName>
        <label>Accounting Entry</label>
        <referenceTo>Accounting_Entry__c</referenceTo>
        <relationshipLabel>Accounting Entry Lines</relationshipLabel>
        <relationshipName>Accounting_Entry_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Bank_Transaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bank Transaction</label>
        <referenceTo>Bank_Transaction__c</referenceTo>
        <relationshipLabel>Accounting Entry Lines</relationshipLabel>
        <relationshipName>Accounting_Entry_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Accounting Entry Lines</relationshipLabel>
        <relationshipName>Accounting_Entry_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Has_Exceptions__c</fullName>
        <formula>Exceptions_Count__c &gt; 0</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Has Exceptions</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Related_Accounting_Entry_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Accounting Entry Line</label>
        <referenceTo>Accounting_Entry_Line__c</referenceTo>
        <relationshipLabel>Accounting Entry Lines</relationshipLabel>
        <relationshipName>Accounting_Entry_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>TEXT(Accounting_Entry__r.Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <description>Transaction Date of this Accounting Entry Line</description>
        <label>Transaction Date</label>
        <type>Date</type>
    </fields>
    <label>Accounting Entry Line</label>
    <nameField>
        <label>Accounting Entry Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Entry Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Bank_Transaction__c.object
<CustomObject>
    <customHelpPage>HelpManageBankTransactions</customHelpPage>
    <fields>
        <fullName>Bank_Transaction_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Bank transaction group for bank transactions</description>
        <label>Bank Transaction Group</label>
        <referenceTo>Bank_Transaction_Group__c</referenceTo>
        <relationshipLabel>Bank Transactions</relationshipLabel>
        <relationshipName>Bank_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Bank Transactions</relationshipLabel>
        <relationshipName>Bank_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Finalized__c</fullName>
        <formula>Bank_Transaction_Group__r.Finalized__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Finalized</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Exceptions__c</fullName>
        <formula>Exceptions_Count__c &gt; 0</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Has Exceptions</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>TEXT(Bank_Transaction_Group__r.Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <description>Date/time transaction cleared bank</description>
        <label>Transaction Date</label>
        <type>DateTime</type>
    </fields>
    <label>Bank Transaction</label>
    <nameField>
        <label>Bank Transaction</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Bank_Transaction_Group__c.object
<CustomObject>
    <customHelpPage>HelpManageBankTransactions</customHelpPage>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Bank Transaction Groups</relationshipLabel>
        <relationshipName>Bank_Transaction_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Finalized_Date__c</fullName>
        <description>Date bank transaction group was finalized</description>
        <label>Finalized Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Finalized__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag indicating finalized</description>
        <label>Finalized</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Exceptions__c</fullName>
        <formula>OR(

Exceptions_Count__c &gt; 0,

Line_Exceptions__c &gt; 0

)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Has Exceptions</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <label>Transaction Date</label>
        <type>DateTime</type>
    </fields>
    <label>Bank Transaction Group</label>
    <nameField>
        <label>Bank Transaction Group</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Transaction Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Company__c.object
<CustomObject>
    <customHelpPage>HelpCompany</customHelpPage>
    <description>Each Logistics or Financial entity will be represented by a single Company record.  Master data for the Company is recorded here and used throughout the System.</description>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/BankTransactionAccountingExt.cls
public class BankTransactionAccountingExt {
    public ApexPages.StandardSetController setcon{get; set;}
    public Boolean selecterror {get; set;} { selecterror = false; } 
    public Boolean RequiredFieldError {get; set;} { RequiredFieldError = false; }    
    public Boolean BatchInitiated {get; set;} { BatchInitiated = false; }
    
    public list<Bank_Transaction__c> objectList {get;set;}
    set<ID> BTIds = new set<ID>();
    BankTransactionGroupAccounting btga = new BankTransactionGroupAccounting();
    List<Accounting_Entry__c> acctEntryList = new List<Accounting_Entry__c>();
    AccountingRuleService ARS = new AccountingRuleService();
    
    public BankTransactionAccountingExt(ApexPages.StandardSetController controller) {     
        
        setcon = controller;
        
        if (setCon.getSelected().size() == 0) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.FATAL, Label.No_records_selected) );
            selecterror = true;
            return;
        }
        
        for (Bank_Transaction__c bt: (List<Bank_Transaction__c>)setCon.getSelected() ) {      
            BTIds.add(bt.id);
        }
        
        set<string> BTFields = new set<string>(schemautil.getinstance().getFieldsFromFieldSetString('Bank_Transaction__c','Bank_Transaction_AE_RO'));
        BTFields.add('Bank_Transaction_Group__c');
        string Fields = String.join(new list<string>(BTFields),',' );
        String Querystr = 'Select '+Fields+ ' From Bank_Transaction__c'
            			+ ' where ID in :BTIds'
                        + '  and Finalized__c = true '
                        + '  and Bank_Transaction_Group__r.transaction_date__c != null '
                        + '  and Bank_Transaction_Group__r.finalized_date__c != null '
                        + '  and id not in ( Select Bank_Transaction__c from Accounting_Entry_Line__c where Bank_Transaction__c in :BTIds AND Related_Accounting_Entry_Line__c  = null AND has_exceptions__c = false AND status__c = \'Active\')';
        objectList  = Database.Query(Querystr);
                        
                    


        if(objectList == null || objectList.size() < 1){
        	ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.FATAL, Label.No_eligible_records_to_process ) );
          	selecterror = true;
        	return;
        }

        
    } // End of Constructor
    
    
    //Function to generate the accounting entries for the invoice lines
    public pagereference generateBankTransactionAccounting() {
        
        If(objectList != null && objectList.size() > 0){
            Savepoint sp = Database.setSavepoint();
            try{

                set<Id> sourceDocIds = new set<Id>();
                set<Id> companyIds = new set<Id>();
                for(Bank_Transaction__c bt : objectList){
                	companyIds.add(bt.company__c);
                	sourceDocIds.add(bt.Bank_Transaction_Group__c);
                }
                
                BankTransactionGroupAccountingBatch  batch = new BankTransactionGroupAccountingBatch(companyIds);
                batch.setSourceDocId(sourceDocIds);
                batch.setuseSuperWhere(true);
               
                
                String jobid=Database.ExecuteBatch(batch);
                
                ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.INFO, 'Batch Job '+ jobid+ ' has been initiated.' ) );
				BatchInitiated=true;
                
                
            }catch(Exception e){
                Database.rollback(sp);
                selecterror=true;
                String errorMessage = e.getMessage();
                ApexPages.addMessages(e);
                return null;
            }
        }

        if (Apexpages.hasMessages(ApexPages.Severity.FATAL) || Apexpages.hasMessages(ApexPages.Severity.ERROR)){
        	requiredFielderror = true;
        	selecterror = true;
        	
        }
        return (Apexpages.hasMessages() ? null : this.setcon.cancel() ); 
        //return setcon.cancel();
    }
}