src-ken&y/objects/Accounting_Entry__c.object
<CustomObject>
    <customHelpPage>HelpAccountingEntries</customHelpPage>
    <description>Accounting Entry Header records</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Accounting Entries</relationshipLabel>
        <relationshipName>Accounting_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Finalized_Date__c</fullName>
        <description>Finalized Date for the associated source document.</description>
        <label>Finalized Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Has_Exceptions__c</fullName>
        <formula>OR(
Exceptions_Count__c &gt; 0,
Line_Exceptions__c &gt; 0
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Has Exceptions</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Related_Accounting_Entry__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Void - Related Accounting Entry</description>
        <label>Related Accounting Entry</label>
        <referenceTo>Accounting_Entry__c</referenceTo>
        <relationshipLabel>Related Accounting Entry</relationshipLabel>
        <relationshipName>Related_Accounting_Entry</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transaction_Currency__c</fullName>
        <description>Transaction currency code for this entry</description>
        <label>Transaction Currency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>USD</fullName>
                </value>
                <value>
                    <fullName>EUR</fullName>
                </value>
                <value>
                    <fullName>INR</fullName>
                </value>
                <value>
                    <fullName>AUD</fullName>
                </value>
                <value>
                    <fullName>SGD</fullName>
                </value>
                <value>
                    <fullName>GBP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <description>Transaction date for the associated source document.</description>
        <label>Transaction Date</label>
        <type>DateTime</type>
    </fields>
    <label>Accounting Entry</label>
    <nameField>
        <label>Accounting Entry</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Company__c.object
<CustomObject>
    <customHelpPage>HelpCompany</customHelpPage>
    <description>Each Logistics or Financial entity will be represented by a single Company record.  Master data for the Company is recorded here and used throughout the System.</description>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Purchase_Order__c.object
<CustomObject>
    <customHelpPage>HelpPurchaseOrders</customHelpPage>
    <description>Purchase header information</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Logistics or Financial company that this PO will be owned by</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purchase_Order_Value__c</fullName>
        <description>Sum of all line values on PO Detail</description>
        <label>Purchase Order Value</label>
        <summarizedField>Purchase_Order_Line__c.Line_Value__c</summarizedField>
        <summaryFilterItems>
            <field>Purchase_Order_Line__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Cancelled</value>
        </summaryFilterItems>
        <summaryForeignKey>Purchase_Order_Line__c.Purchase_Order__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the Purchase Order;  PO will be kept on file after beng closed until company runs a maintenance transaction to backup and purge closed and cancelled purchase orders</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <description>Date of the transaction, this could be populated from any source using a workflow</description>
        <inlineHelpText>Date of the transaction, this could be populated from any source using a workflow</inlineHelpText>
        <label>Transaction Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>The PO type. &quot;Standard&quot; -&gt; lists goods or services you require. &quot;Production&quot; -&gt; establishes a contract with a co-manufacturer to produce goods. &quot;Shipment&quot; -&gt; lists goods ready to be picked up.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Production</fullName>
                </value>
                <value>
                    <fullName>Standard</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Shipment</fullName>
                </value>
                <value>
                    <fullName>Drop Ship</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Purchase Order</label>
    <nameField>
        <label>Purchase Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/PurchaseOrderAccountingExt.cls
public with sharing class PurchaseOrderAccountingExt {
//DEPRECATED CLASS FIN-1046    
/*    public ApexPages.StandardSetController setcon{get; set;}
    public Boolean selecterror {get; set;} { selecterror = false; } 
    public Boolean requiredFielderror {get; set;} { requiredFielderror = false; } 
    public list<Purchase_Order__c> objectList {get;set;}
    set<ID> purchaseOrderIds = new set<ID>();
    AccountingRuleService ARS = new AccountingRuleService();
    public boolean disableGenerate {get;set;}
     
    public PurchaseOrderAccountingExt(ApexPages.StandardSetController controller) {     
        
        setcon = controller;
        disableGenerate = false;
        
        if ( ! Schema.sObjectType.Purchase_Order__c.isCreateable() ) {
		      ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL,
	                                               	Label.Insufficient_access_to_create_Purchase_Order));
			requiredFielderror = true;
			disableGenerate = true;
			return;
	    }
	    
        if (setCon.getSelected().size() == 0) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.FATAL, Label.No_records_selected) );
            selecterror = true;
            disableGenerate = true;
            return;
        }
        
        for (Purchase_Order__c po : (List<Purchase_Order__c>)setCon.getSelected() ) {      
            purchaseOrderIds.add(po.ID);
        }
        
        set<string> purchaseOrderFields = new set<string>{'id', 'name', 'company__c', 'finalized__c', 'finalized_date__c', 'transaction_currency__c', 'transaction_date__c', 'type__c', 'Purchase_Order_Value__c'};
        set<string> purchaseOrderLineFields = new set<string>{ 'id', 'name', 'subtransaction_type__c', 'line_type__c', 'line_value__c'};
        
        string purchaseOrderQuery = 'SELECT ' + string.join(new List<string>(purchaseOrderFields),', ');
		purchaseOrderQuery += ' FROM Purchase_Order__c '
							+ 'WHERE id in :purchaseOrderIds '
                            + 'AND Finalized__c = true '
                            + 'AND Company__c != null '
                            + 'AND Transaction_Date__c != null '
                            + 'AND Transaction_Currency__c != null '
                            + 'AND Id NOT IN (SELECT Purchase_Order__c FROM Accounting_Entry__c WHERE Purchase_Order__c in :purchaseOrderIds AND related_accounting_entry__c = null AND has_exceptions__c = false AND status__c = \'Active\') ';
                            
        objectList = Database.query(purchaseOrderQuery);    
        
        if(!ARS.objectHasRules('Purchase_Order__c')){
        	ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.FATAL, Label.No_Accounting_Rules_defined_for_Purchase_Orders));
    		requiredFielderror = true;
        	selecterror = true;
        	disableGenerate = true;
        	return;
        }
        if(objectList == null || objectList.size() < 1){
        	ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.FATAL, Label.No_eligible_records_to_process ) );
        	requiredFielderror = true;
          	selecterror = true;
          	disableGenerate = true;
        	return;
        }
        for(integer i = 0; i < objectList.size(); i++){
        	if(objectList[i].Transaction_Date__c == null){
        		ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.FATAL, Label.Transaction_Date_is_blank + objectList[i].Name ) );
        		requiredFielderror = true;
            	selecterror = true;
            	disableGenerate = true;
            	return;
        	}
        	if(objectList[i].Transaction_Currency__c == null){
        		ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.FATAL, Label.Transaction_Currency_is_blank + objectList[i].Name ) );
        		requiredFielderror = true;
            	selecterror = true;
            	disableGenerate = true;
            	return;
        	}
        	if(objectList[i].Company__c == null){
        		ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.FATAL, Label.Company_is_blank + objectList[i].Name ) );
        		requiredFielderror = true;
            	selecterror = true;
            	disableGenerate = true;
            	return;
        	}
        }
        
    } // End of Constructor
    
    
    //Function to generate the accounting entries for the invoice lines
    public pagereference GeneratePurchaseOrderAccounting() {
        Map<Id,Purchase_Order__c> invoiceMapUpd = new Map<Id,Purchase_Order__c>();
        Map<Id,Purchase_Order__c> invoiceMapUpdCM = new Map<Id,Purchase_Order__c>();
        If(objectList != null && objectList.size() > 0){
        	Savepoint sp = Database.setSavepoint();
        	try{
	            	//AccountingService.upsertAccountingEntry(objectList);          
	                set<Id> sourceDocIds = new set<Id>();
	                set<Id> companyIds = new set<Id>();
	                for(Purchase_Order__c po : objectList){
	                    companyIds.add(po.company__c);
	                    sourceDocIds.add(po.Id);
	                }   
	                                    
	                PurchaseOrderAccountingBatch  batch = new PurchaseOrderAccountingBatch(companyIds);
	                batch.setSourceDocId(sourceDocIds);
	                batch.setuseSuperWhere(true);
	                string jobid= Database.ExecuteBatch(batch);
	                disableGenerate = true;
	                
	                ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.INFO, 'Batch Job '+ jobid+ ' has been initiated.' ) );
	            	
            	} catch(Exception e) {
            		system.debug('EXCEPTION: ' + e.getStackTraceString());
            		Database.rollback(sp);
                	selecterror = true;
                	ApexPages.addMessages(e);
                	disableGenerate = true;
                	return null;
            	}
        }
        //KNDY-2020 Checking for Pg msgs before moving the page forward. Hiding the button if any error or fatal msgs
        if (Apexpages.hasMessages(ApexPages.Severity.FATAL) || Apexpages.hasMessages(ApexPages.Severity.ERROR)){
        	requiredFielderror = true;
        	selecterror = true;
        	
        }
        return (Apexpages.hasMessages() ? null : this.setcon.cancel() ); 
       
    } 
	
*/}