src-ken&y/objects/Action__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <length>240</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Step__c</fullName>
        <label>Step</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Action</label>
</CustomObject>

src-ken&y/objects/Criteria__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Field__c</fullName>
        <label>Field</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <label>Process</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Reference</label>
        <length>240</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Step__c</fullName>
        <label>Step</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value_Field__c</fullName>
        <label>Value/Field</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Criteria</label>
</CustomObject>

src-ken&y/objects/Process__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Automated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Automated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Before__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Before</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Insert__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Insert</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Object_Step__c</fullName>
        <label>Object Step</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Update__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Update</label>
        <type>Checkbox</type>
    </fields>
    <label>Process</label>
</CustomObject>

src-ken&y/objects/Product__c.object
<CustomObject>
    <customHelpPage>HelpProducts</customHelpPage>
    <description>Products are sellable Items with Selling Unit of Measure included</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status indicates if the product is active or retired</description>
        <label>Status</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UPC_Code__c</fullName>
        <description>13 char UPC code</description>
        <label>UPC Code</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <description>Product&apos;s weight in weight uom units</description>
        <label>Weight</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Sales_Order_Line__c.object
<CustomObject>
    <customHelpPage>HelpSalesOrders_Managing</customHelpPage>
    <description>Line Items on the Sales Order.</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Line_Type__c</fullName>
        <label>Line Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Product</description>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <filterItems>
                <field>Product__c.Item__r.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Product__c.Company__c</field>
                <operation>equals</operation>
                <valueField>$Source.Company__c</valueField>
            </filterItems>
            <filterItems>
                <field>Product__c.Company__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity_Change_Reason__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Required code associated with quantity changes</description>
        <label>Reason Code</label>
        <referenceTo>Reason_Code__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity_Ordered__c</fullName>
        <description>The number of items ordered in this sales order line</description>
        <label>Quantity Ordered</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Line open if item is not shipped; line closed if shipped; line partial if partially shipped</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Step__c</fullName>
        <label>Step</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UPC_Code__c</fullName>
        <description>13 char UPC code</description>
        <label>UPC Code</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <label>Sales Order Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Step__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Process__c</fullName>
        <label>Process</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Step</label>
</CustomObject>

src-ken&y/objects/Substitution__c.object
<CustomObject>
    <customHelpPage>HelpSubstitution</customHelpPage>
    <fields>
        <fullName>Current_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The current product that the substitution should apply to.</description>
        <label>Current Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipName>Product_Selections</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>The date on which the substitution is effective until.</description>
        <inlineHelpText>Date on which the block or substitution ends. The end date must be greater than the start date.</inlineHelpText>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>The date on which the substitution is effective from.</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Substitute_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The product that should be substituted for the current product.</description>
        <inlineHelpText>The substitute product must have the same UPC code as the current product.</inlineHelpText>
        <label>Substitute Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Substitutions (Substitute Product)</relationshipLabel>
        <relationshipName>Product_Selections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Substitution</label>
    <nameField>
        <label>Substitution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Substitutions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/SalesOrderLineFlowHandlerTest.cls
@isTest
public with sharing class SalesOrderLineFlowHandlerTest {
	class TestFlowData {
		
		public Process__c salesOrderLineProcess {
			get{
				if(salesOrderLineProcess == null){
					salesOrderLineProcess = new Process__c();
					
					salesOrderLineProcess.Name = 'Sales Order Line';
					salesOrderLineProcess.Active__c = true;
					salesOrderLineProcess.Automated__c = true;
					salesOrderLineProcess.Object__c = KSE.NamespaceUU + 'Sales_Order_Line__c';
					
					salesOrderLineProcess.Object_Step__c = KSE.NamespaceUU + 'Step__c';
					salesOrderLineProcess.State__c = 'SalesOrderLineFlowHandler.SalesOrderLineState';
					salesOrderLineProcess.Sequence__c = 10;
					
					salesOrderLineProcess.Before__c = true;
					salesOrderLineProcess.Insert__c = true;
					salesOrderLineProcess.Update__c = true;
					
					insert salesOrderLineProcess;
				}
				return salesOrderLineProcess;
			}
			set;
		}
		
		public Step__c salesOrderLineStep {
			get{
				if(salesOrderLineStep == null){
					salesOrderLineStep = new Step__c();
					
					salesOrderLineStep.Name = 'Sales Order Line - Means of Transport';
					salesOrderLineStep.Sequence__c = 10;
					salesOrderLineStep.Process__c = salesOrderLineProcess.Id;
					
					insert salesOrderLineStep;
				}
				return salesOrderLineStep;
			}
			set;
		}
		
		public Action__c setMoTAction {
			get{
				if(setMoTAction == null){
					setMoTAction = new Action__c();
					
					setMoTAction.Name = 'Sales Order Line - Means of Transport';
					setMoTAction.Action__c = 'SalesOrderLineFlowHandler.SetMeansOfTransport';
					setMoTAction.Sequence__c = 10;
					setMoTAction.Step__c = salesOrderLineStep.Id;
					
					insert setMoTAction;
				}
				return setMoTAction;
			}
			set;
		}
		
		public Criteria__c statusIsChangingCriteria {
			get{
				if(statusIsChangingCriteria == null){
					statusIsChangingCriteria = new Criteria__c();
					
					statusIsChangingCriteria.Name = 'Status is changing';
					statusIsChangingCriteria.Field__c = 'Status__c';
					statusIsChangingCriteria.Operator__c = 'is changing';
					statusIsChangingCriteria.Value_Field__c = 'Field';
					statusIsChangingCriteria.Step__c = salesOrderLineStep.Id;
					
					insert statusIsChangingCriteria;
				}
				return statusIsChangingCriteria;
			}
			set;
		}
		
		public Criteria__c lineTypeCriteria {
			get{
				if(lineTypeCriteria == null){
					lineTypeCriteria = new Criteria__c();
					
					lineTypeCriteria.Name = 'Line type is military';
					lineTypeCriteria.Field__c = 'Line_Type__c';
					lineTypeCriteria.Operator__c = 'equals';
					lineTypeCriteria.Value_Field__c = 'Value';
					lineTypeCriteria.Reference__c = 'Military';
					lineTypeCriteria.Step__c = salesOrderLineStep.Id;
					
					insert lineTypeCriteria;
				}
				return lineTypeCriteria;
			}
			set;
		}
			
		public Substitution__c substitution {
			get{
				if(substitution == null){
					substitution = new Substitution__c();
					substitution.Name = 'Primary Product Sub';
					substitution.Current_Product__c = globalTestData.product.Id;
					substitution.Start_Date__c = system.today() - 1;
					substitution.End_Date__c = system.today() + 720;
					
					insert substitution;
				}
				return substitution;
			}
			set;
		}
	}
	
	static TestFlowData localTestData = new TestFlowData();
	static TestFuel globalTestData = new TestFuel();
	 
	// The following method tests that if the record is selected by
	// the process engine, then it should skip the "managed actions" in the trigger.
	static testMethod void testSalesOrderLineFlow(){
		
		system.assert(localTestData.statusIsChangingCriteria.Id != null);
		system.assert(localTestData.lineTypeCriteria.Id != null);
		system.assert(localTestData.setMoTAction.Id != null);
		system.assert(localTestData.salesOrderLineStep.Id != null);
		system.assert(localTestData.salesOrderLineProcess.Id != null);
		system.assert(localTestData.substitution.Id != null);
	
		// Change the product upc
		globalTestData.product2.UPC_Code__c = globalTestData.product.UPC_Code__c;
		update globalTestData.product2;
		
		localTestData.substitution.Substitute_Product__c = globalTestData.product2.Id;
		update localTestData.substitution;
		
		system.assert(globalTestData.salesOrder.Id != null);
		system.assert(globalTestData.salesOrderLines.size() > 0);
		
		for(Sales_Order_Line__c sol : globalTestData.salesOrderLines){
			system.assert(sol.Id != null);
		}
		
		globalTestData.salesOrder.Status__c = 'Open';

		update globalTestData.salesOrder;
		
		Map<Id, Sales_Order_Line__c> oldMap = new Map<Id, Sales_Order_Line__c>(
													  [SELECT Id, Product__c, Weight__c
													     FROM Sales_Order_Line__c 
													    WHERE Id IN :globalTestData.salesOrderLines]); 
		
		system.assert(oldMap.size() > 0);
		
		for(Sales_Order_Line__c sol : oldMap.values()){
			// Since we have a substituiton rule, both lines should have product 2
			system.assertEquals(globalTestData.product2.Id, sol.Product__c);
		}
			
		// Change the status to check that the so line
		// will be picked up by the process engine.
		Sales_Order_Line__c sol = oldMap.get(globalTestData.salesOrderLines[0].Id);
		sol.Status__c = 'Open';
		sol.Line_Type__c = 'Standard';
		sol.Quantity_Ordered__c = 8;
		sol.Quantity_Change_Reason__c = globalTestData.deductionCode.Id;
		
		Sales_Order_Line__c sol2 = oldMap.get(globalTestData.salesOrderLines[1].Id);
		sol2.Status__c = 'Open';
		sol2.Line_Type__c = 'Military';
		sol2.Quantity_Ordered__c = 8;
		sol2.Quantity_Change_Reason__c = globalTestData.deductionCode.Id;
		 
		// Clear out the dispatches
		ProcessHandler.dispatches.clear();
        
		// Changed the status from Draft to Open.
		// Normally, it will go through the "managed actions" in the trigger and updates the weight of the lines.
		update oldmap.values();

		// One of the records will be selected by the process engine and
		// no step has been setup for updating the weight on the sales order line in the process, 
		// so the weight should not be recalculated for one of the sales order lines.
		Map<Id, Sales_Order_Line__c> newMap = new Map<Id, Sales_Order_Line__c>(
												  [SELECT Id, Product__c, Weight__c, Line_Type__c
												     FROM Sales_Order_Line__c 
												    WHERE Id IN :globalTestData.salesOrderLines]); 
		system.assert(newMap.size() > 0);
		system.debug(LoggingLevel.INFO, newMap);
		system.assertNotEquals(oldMap.get(globalTestData.salesOrderLines[0].Id).Weight__c, newMap.get(globalTestData.salesOrderLines[0].Id).Weight__c);
		system.assertEquals(oldMap.get(globalTestData.salesOrderLines[1].Id).Weight__c, newMap.get(globalTestData.salesOrderLines[1].Id).Weight__c);										      
													    
	}	
}