src-ken&y/objects/Agreement__c.object
<CustomObject>
    <customHelpPage>HelpAgreement</customHelpPage>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Agreement_Line__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Agreement Lines</relationshipLabel>
        <relationshipName>Agreement_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Agreement Line</label>
    <nameField>
        <label>Agreement Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreement Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Customer__c.object
<CustomObject>
    <customHelpPage>HelpCustomers</customHelpPage>
    <description>Information that relates a Customer business to the manufacturing company (Company) and describes the business agreement between the two entities.</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The company that originates and owns the customer relationship</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Customers</relationshipLabel>
        <relationshipName>Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer</label>
    <nameField>
        <label>Customer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <recordTypes>
        <fullName>Bill_To</fullName>
        <active>true</active>
        <description>Customer location that receives invoices</description>
        <label>Bill To</label>
    </recordTypes>
    <recordTypes>
        <fullName>Corporate_Parent</fullName>
        <active>true</active>
        <description>Top of the customer hierarchy, owns or controls related customer records</description>
        <label>Corporate Parent</label>
    </recordTypes>
    <recordTypes>
        <fullName>Ship_To</fullName>
        <active>true</active>
        <description>Customer location that receives shipments</description>
        <label>Ship To</label>
    </recordTypes>
    <recordTypes>
        <fullName>Site</fullName>
        <active>true</active>
        <label>Site</label>
    </recordTypes>
    <recordTypes>
        <fullName>Sold_To</fullName>
        <active>true</active>
        <description>Customer location that places orders</description>
        <label>Sold To</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Fulfillment__c.object
<CustomObject>
    <customHelpPage>HelpFulfillment</customHelpPage>
    <fields>
        <fullName>Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Fulfillments</relationshipLabel>
        <relationshipName>Fulfillments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Fulfillments</relationshipLabel>
        <relationshipName>Fulfillments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Fulfillments</relationshipLabel>
        <relationshipName>Fulfillments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Fulfillment</label>
    <nameField>
        <label>Fulfillment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fulfillments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Invoice_Grouping_Rule__c.object
<CustomObject>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Invoice Grouping Rules</relationshipLabel>
        <relationshipName>Invoice_Grouping_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Group_By_Agreements__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Use checkbox to group invoices by Agreement OR use field For Agreement</inlineHelpText>
        <label>Group By Agreements</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Group_By_Category__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Group by Category OR for specific Category OR by Product OR for specific Product</inlineHelpText>
        <label>Group By Categories</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Group_By_Customer_Hierarchy__c</fullName>
        <inlineHelpText>Use checkbox to select a customer hierarchy level OR use field to enter a specific customer. You can combine multiple selections in a rule but you must specify criteria for the customer level at least.</inlineHelpText>
        <label>Group By Customer Hierarchy</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Corporate Parent</fullName>
                </value>
                <value>
                    <fullName>Bill To</fullName>
                </value>
                <value>
                    <fullName>Sold To</fullName>
                </value>
                <value>
                    <fullName>Ship To</fullName>
                </value>
                <value>
                    <fullName>Site</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Group_By_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Group by Category OR for specific Category OR by Product OR for specific Product</inlineHelpText>
        <label>Group By Products</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Group_By_Sales_Order_If__c</fullName>
        <inlineHelpText>Use only if Group by Sales Orders or Group by Sales Order Types is selected. Invoice only when entire sales order is closed, sales order line is closed, or leave blank to invoice whenever fulfillment records are generated.</inlineHelpText>
        <label>Group By Sales Order If</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Order is closed</fullName>
                </value>
                <value>
                    <fullName>Order line is closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Group_By_Sales_Order_Types__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Group By Sales Order Types</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Group_By_Sales_Orders__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Group by Sales Orders OR by Sales Order Types OR by Shipments</inlineHelpText>
        <label>Group By Sales Orders</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Group_By_Shipments__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Group by Sales Orders OR by Sales Order Types OR by Shipments</inlineHelpText>
        <label>Group By Shipments</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rank__c</fullName>
        <inlineHelpText>Rank determines the order in which rules will be matched against fulfillments.</inlineHelpText>
        <label>Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Invoice Grouping Rule</label>
    <nameField>
        <displayFormat>IGR-{0000000000}</displayFormat>
        <label>Invoice Grouping Rule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Grouping Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Product__c.object
<CustomObject>
    <customHelpPage>HelpProducts</customHelpPage>
    <description>Products are sellable Items with Selling Unit of Measure included</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Sales_Order__c.object
<CustomObject>
    <customHelpPage>HelpSalesOrders_Managing</customHelpPage>
    <description>Sales Order Header</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Sales_Order_Line__c.object
<CustomObject>
    <customHelpPage>HelpSalesOrders_Managing</customHelpPage>
    <description>Line Items on the Sales Order.</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company passed down from the sales order header</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Product</description>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <filterItems>
                <field>Product__c.Item__r.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Product__c.Company__c</field>
                <operation>equals</operation>
                <valueField>$Source.Company__c</valueField>
            </filterItems>
            <filterItems>
                <field>Product__c.Company__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <label>Sales Order Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Shipment__c.object
<CustomObject>
    <customHelpPage>HelpShipment</customHelpPage>
    <description>Sales Order Shipment Header</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Shipment</label>
    <nameField>
        <label>Shipment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Shipment_Line__c.object
<CustomObject>
    <customHelpPage>HelpShipment</customHelpPage>
    <description>Shipment lines.</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company associated with this shipment invoice line</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Shipment Lines</relationshipLabel>
        <relationshipName>Shipment_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Product</description>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Shipment Lines</relationshipLabel>
        <relationshipName>Shipment_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Shipment Line</label>
    <nameField>
        <label>Shipment Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipment Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/classes/InvoiceGroupingRuleDefinition.cls
public with sharing class InvoiceGroupingRuleDefinition implements Comparable {
	/*
	WE use this class to compress our Invoice grouping Rule. 
	*/
	public Id companyId; //for a particular company id
	public String groupByCustomers;
	public boolean groupByAgreements;
	public boolean groupBySalesOrders;
	public boolean groupBySalesOrderTypes;
	public String groupSOIf;
	public boolean groupByShipments;
	public boolean groupByCategory;
	public boolean groupByProduct;
	public decimal rank;
	public Date recurrenceStartDate;
	public String periodicity;
	public Id groupingRule;
	public boolean UseBillingFromFulfillment;
	public integer everyPeriodicity;
    public Set<Id> forAgreements;
    public Set<Id> forCategories;
    public Set<Id> forCustomers;
    public Set<Id> forProducts;
	public DateTime recurrenceStartDatetime;
	
	public static final string CUSTOMER_BILL_TO = 'Bill To';
	//CONSTRUCTOR
	public InvoiceGroupingRuleDefinition (Invoice_Grouping_Rule__c igr) {
		
		 this.companyId = igr.Company__c; //for a particular company id
		 this.groupByCustomers = igr.Group_By_Customer_Hierarchy__c;
		 this.groupByAgreements = igr.Group_By_Agreements__c;
		 this.groupBySalesOrders  = igr.Group_By_Sales_Orders__c;
		 this.groupBySalesOrderTypes  = igr.Group_By_Sales_Order_Types__c;
		 this.groupSOIf = igr.Group_By_Sales_Order_If__c;
		 this.groupByShipments  = igr.Group_By_Shipments__c;
		 this.groupByProduct = igr.Group_By_Product__c;
		 this.groupByCategory = igr.Group_By_Category__c;
		 this.rank  = igr.Rank__c;
		 this.periodicity = igr.Billing_UOM__c  == null ? FrequencyService.FREQUENCY_PERIOD_IMMEDIATE : igr.Billing_UOM__r.Recurrence__c; 
		 this.recurrenceStartDate = this.periodicity ==  FrequencyService.FREQUENCY_PERIOD_IMMEDIATE ? null : igr.Recurrence_Start_Date__c.date(); 
		 this.recurrenceStartDatetime = this.periodicity ==  FrequencyService.FREQUENCY_PERIOD_IMMEDIATE ? null : igr.Recurrence_Start_Date__c;
		 this.everyPeriodicity = Integer.valueOf(igr.Billing_UOM__r.Every__c);
		 this.groupingRule = igr.id;
		 this.UseBillingFromFulfillment = igr.Use_Billing_Frequency_on_Fulfillment__c == null ? false: igr.Use_Billing_Frequency_on_Fulfillment__c;

         
         this.forAgreements = (igr.For_Agreements__c != null) ? (Set<Id>)JSON.deserialize(String.valueOf(igr.For_Agreements__c), Set<Id>.Class) : null;
         this.forCategories = (igr.For_Categories__c != null) ? (Set<Id>)JSON.deserialize(String.valueOf(igr.For_Categories__c), Set<Id>.Class) : null;
         this.forCustomers =  (igr.For_Customers__c != null) ? (Set<Id>)JSON.deserialize(String.valueOf(igr.For_Customers__c), Set<Id>.Class) : null;
         this.forProducts =   (igr.For_Products__c != null) ? (Set<Id>)JSON.deserialize(String.valueOf(igr.For_Products__c), Set<Id>.Class)  : null;
        
	}
	public InvoiceGroupingRuleDefinition() {
		//EMPTY Constructor
	}
	
	public static InvoiceGroupingRuleDefinition createRuleForSObject(Id companyId, String objectName) {
		
		InvoiceGroupingRuleDefinition ruleDef = new InvoiceGroupingRuleDefinition();
		ruleDef.companyId = companyId;
		if(objectName.equalsIgnoreCase('Agreement__c')) {
			ruleDef.groupByAgreements = true;
			ruleDef.groupBySalesOrderTypes = true;
			ruleDef.groupByCustomers = 'Corporate Parent';
		}
			
		else {
			ruleDef.groupByCustomers = 'Bill To';
		if(objectName.equalsIgnoreCase('Sales_Order__c'))
			ruleDef.groupBySalesOrders = true;
			else if(objectName.equalsIgnoreCase('Shipment__c')) {
			ruleDef.groupByShipments = true;
				ruleDef.groupBySalesOrderTypes = true;
			}else {
				ruleDef.groupBySalesOrderTypes = true;
			}
		}
		 
		
		ruleDef.rank = 1;
		ruleDef.periodicity =FrequencyService.FREQUENCY_PERIOD_IMMEDIATE;
		ruleDef.recurrenceStartDate = null;
		ruleDef.recurrenceStartDatetime = null;
		ruleDef.UseBillingFromFulfillment = false;
		return ruleDef;
	}
	
	//Currently the ranking is explicit, based on the rank (user specified) field. TODO: could have an implicit ranking based on the granular level specified. 
	public integer compareTo(Object compareTo) { //SORTS IN DESCENDING ORDER
		
		InvoiceGroupingRuleDefinition ruleDef = (InvoiceGroupingRuleDefinition) compareTo;
		if(rank == ruleDef.rank) return 0;
		else if(rank > ruleDef.rank) return 1;
		else return -1;
	}
	
	public integer hashCode(){
		return HashCodeGenerator.getHashCode(this);  
	}
	
	public boolean equals(object obj){
		InvoiceGroupingRuleDefinition compare = (InvoiceGroupingRuleDefinition)obj;
        if(this.companyId == compare.companyId &&
           this.groupByCustomers == compare.groupByCustomers &&
		   this.groupByAgreements == compare.groupByAgreements &&
		   this.groupBySalesOrders  == compare.groupBySalesOrders &&
		   this.groupBySalesOrderTypes  == compare.groupBySalesOrderTypes &&
		   this.groupSOIf == compare.groupSOIf &&
		   this.groupByShipments  == compare.groupByShipments &&
		   this.groupByProduct == compare.groupByProduct &&
		   this.groupByCategory == compare.groupByCategory &&
		   this.rank  == compare.rank &&
		   this.recurrenceStartDate == compare.recurrenceStartDate &&
		   this.periodicity == compare.periodicity &&
		   this.groupingRule == compare.groupingRule &&
		   this.UseBillingFromFulfillment == compare.UseBillingFromFulfillment &&
		   this.everyPeriodicity == compare.everyPeriodicity && 
           this.forAgreements == compare.forAgreements &&
           this.forCategories == compare.forCategories &&
           this.forCustomers == compare.forCustomers &&
           this.forProducts == compare.forProducts)
		  	
	  	{
	  		return true;
	  	}else{
			return false;
		}
	}
	
	public class status{

           public boolean qualifies;
           public string message;
           public status(){}
           public status(boolean qualifies, string message){
               this.qualifies= qualifies;
               this.message = message;
           }
    }
	
	//added as a part of KNDY-9741
    public static status isQualifiedWithMessage(Fulfillment__c f, InvoiceGroupingRuleDefinition ruleDef) {
            system.debug(logginglevel.error,ruleDef);
            system.debug(logginglevel.error,f);
            if(f.Type__c == AllowanceRuleService.ALLOWANCE_ACCRUAL){ //KNDY-14713
                return new status(true,'Success'); 
            }
            if(ruleDef.companyId != f.Company__c) {
                system.debug('company didnt match');
                return new status(false,'Company not matching');
            }else if((f.Agreement_Line__r.Agreement__c != null && (f.Agreement_Line__r.Agreement__r.Activation_Date__c == null || f.Agreement_Line__r.Agreement__r.Activation_Date__c > system.today()))){
                system.debug('agreement date issue: '+(f.Agreement_Line__r.Agreement__c != null && (f.Agreement_Line__r.Agreement__r.Activation_Date__c == null || f.Agreement_Line__r.Agreement__r.Activation_Date__c > system.today()))); 
                return new status(false,'Agreement Activation Date is incorrect');
            }else if((f.Sales_Order_Line__c != null && f.Sales_Order_Line__r.Sales_Order__r.Has_Exceptions__c == true)){
                system.debug(logginglevel.error,'SO issue: '+(f.Sales_Order_Line__c != null && f.Sales_Order_Line__r.Sales_Order__r.Has_Exceptions__c == true));
                return new status(false,'Related Sales Order is having exceptions');
            }else if((f.Shipment_Line__c != null && f.Shipment_Line__r.Shipment__r.Has_Exceptions__c == true)){
                system.debug('SH issue: '+(f.Shipment_Line__c != null && f.Shipment_Line__r.Shipment__r.Has_Exceptions__c == true));
                return new status(false,'Related Shipment is having exceptions');
            }else if(ruleDef.groupByCustomers != null && !InvoiceGroupingRuleDefinition.isWithinHierarchy(ruleDef.groupByCustomers, f)) {
                system.debug('groupBy Cust didnt match');
                return new status(false,'Group By Customers not matching');
            }else if(ruleDef.groupByAgreements == true && f.Agreement_Line__r.Agreement__c == null) {//KNDY-8667
                system.debug('groupByAgreements didnt match');
                return new status(false,'Group By Agreements not matching');
            }else if((ruleDef.groupBySalesOrders == true || ruleDef.groupBySalesOrderTypes == true) && f.Sales_Order_Line__c == null) { //KNDY-8634
                system.debug('groupBySalesOrders didnt match');
                return new status(false,'Group By SalesOrders not matching');
            }else if(ruleDef.groupSOIf == InvoiceGroupingRuleService.GROUP_ENTIRE_SO && f.Sales_Order_Line__r.Sales_Order__r.Status__c != 'Closed') {
                system.debug('groupSOIf entire so didnt match');
                return new status(false,'Entire SO not matching');
            }else if(ruleDef.groupSOIf == InvoiceGroupingRuleService.GROUP_ENTIRE_SOL && f.Sales_Order_Line__r.Status__c != 'Closed') {
                system.debug('groupSOIf entire sol didnt match');
                return new status(false,'Entire SOL not matching');
            }else if(ruleDef.groupByShipments == true && f.Shipment_Line__c == null) {
                system.debug('groupByShipments didnt match');
                return new status(false,'Group By Shipments not matching');
            }else if(ruleDef.groupByCategory == true && f.Category__c == null) {
                system.debug('groupByCategory didnt match');
                return new status(false,'Group By Category not matching');
            }else if(ruleDef.groupByProduct == true && f.Product__c == null) {
                system.debug('groupByProduct didnt match');
                return new status(false,'Group By Product not matching');
            }else if(ruleDef.forAgreements != null && !ruleDef.forAgreements.contains(f.Agreement_Line__r.Agreement__c)){
                system.debug('forAgreements didnt match');
                return new status(false,'Agreements not matching');  
            }else if(ruleDef.forCategories != null && !ruleDef.forCategories.contains(f.Category__c)){
               system.debug('forCategories didnt match');
                return new status(false,'Categories not matching');
            }else if(ruleDef.forProducts != null && !ruleDef.forProducts.contains(f.Product__c)){
                system.debug('forProducts didnt match');
                return new status(false,'Products not matching');
            }else if(ruleDef.forCustomers != null && !ruleDef.forCustomers.contains(f.Customer__c)){
                system.debug('forCustomers didnt match');
                return new status(false,'Customers not matching');
            }else {
                return new status(true,'Success'); 
            }           
    }
	
	private static boolean isWithinHierarchy (String hierarchy, Fulfillment__c f) {
		system.debug('hierarchy '+hierarchy);
		system.debug('f.Customer__r.RecordType.DeveloperName '+f.Customer__r.RecordType.DeveloperName);
		
		if(hierarchy == 'Corporate Parent' && (f.Customer__r.RecordType.DeveloperName == 'Corporate_Parent' || f.Customer__r.RecordType.DeveloperName == 'Bill_To' || f.Customer__r.RecordType.DeveloperName == 'Sold_To' || f.Customer__r.RecordType.DeveloperName == 'Ship_To' || f.Customer__r.RecordType.DeveloperName == 'Site' ))
			return true;
		else if(hierarchy == 'Bill To' && (f.Customer__r.RecordType.DeveloperName == 'Bill_To' || f.Customer__r.RecordType.DeveloperName == 'Sold_To' || f.Customer__r.RecordType.DeveloperName == 'Ship_To'|| f.Customer__r.RecordType.DeveloperName == 'Site'))
			return true;
		else if(hierarchy == 'Sold To' && (f.Customer__r.RecordType.DeveloperName == 'Sold_To' || f.Customer__r.RecordType.DeveloperName == 'Ship_To' || f.Customer__r.RecordType.DeveloperName == 'Site')) 
			return true;
		else if(hierarchy == 'Ship To' && (f.Customer__r.RecordType.DeveloperName == 'Ship_To' || f.Customer__r.RecordType.DeveloperName == 'Site'))
			return true;
		else if(hierarchy == 'Site' && f.Customer__r.RecordType.DeveloperName == 'Site')
			return true;
		else 
			return false;
		
	}
	 

}