src-ken&y/objects/Agreement__c.object
<CustomObject>
    <customHelpPage>HelpAgreement</customHelpPage>
    <fields>
        <fullName>Activation_Date__c</fullName>
        <inlineHelpText>This date will let the billing engine know to pick up fulfillment lines for consolidated billing.</inlineHelpText>
        <label>Acceptance Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Agreement_Code__c</fullName>
        <externalId>true</externalId>
        <label>Agreement Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Approval_Date__c</fullName>
        <label>Approval Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Bill_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Bill to Customer: Record TypeEQUALSBill To</inlineHelpText>
        <label>Bill To</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <filterItems>
                <field>Customer__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Bill To</value>
            </filterItems>
            <filterItems>
                <field>Customer__c.Parent_Customer__c</field>
                <operation>equals</operation>
                <valueField>$Source.Customer__c</valueField>
            </filterItems>
            <filterItems>
                <field>Customer__c.Top_Parent_Customer__c</field>
                <operation>equals</operation>
                <valueField>$Source.Customer__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Agreements (Bill To)</relationshipLabel>
        <relationshipName>Agreements1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Customer__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Corporate_Parent</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Recurrence_Start_Date__c</fullName>
        <label>Recurrence Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND ((4 AND 2) OR 3)</booleanFilter>
            <filterItems>
                <field>Customer__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Ship To</value>
            </filterItems>
            <filterItems>
                <field>Customer__c.Parent_Customer__c</field>
                <operation>equals</operation>
                <valueField>$Source.Sold_To__c</valueField>
            </filterItems>
            <filterItems>
                <field>Customer__c.Top_Parent_Customer__c</field>
                <operation>equals</operation>
                <valueField>$Source.Customer__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.Sold_To__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Agreements (Ship To)</relationshipLabel>
        <relationshipName>Agreements3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sold_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold To</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND ((4 AND 2) OR 3)</booleanFilter>
            <filterItems>
                <field>Customer__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Sold To</value>
            </filterItems>
            <filterItems>
                <field>Customer__c.Parent_Customer__c</field>
                <operation>equals</operation>
                <valueField>$Source.Bill_To__c</valueField>
            </filterItems>
            <filterItems>
                <field>Customer__c.Top_Parent_Customer__c</field>
                <operation>equals</operation>
                <valueField>$Source.Customer__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.Bill_To__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Agreements (Sold To)</relationshipLabel>
        <relationshipName>Agreements2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>Now()</defaultValue>
        <label>Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Agreement_Line__c.object
<CustomObject>
    <fields>
        <fullName>Agreement_Price__c</fullName>
        <label>Agreement Price</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Agreement__c</fullName>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Agreement Lines</relationshipLabel>
        <relationshipName>Agreement_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Approval_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approval Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Line__c</fullName>
        <description>Line number of the Agreement Line</description>
        <label>Line</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_Agreement_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Agreement Line</label>
        <referenceTo>Agreement_Line__c</referenceTo>
        <relationshipLabel>Agreement Lines</relationshipLabel>
        <relationshipName>Agreement_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Agreement Lines</relationshipLabel>
        <relationshipName>Agreement_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Remaining_Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Remaining Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Revised_Agreement_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Revised Agreement Line</label>
        <referenceTo>Agreement_Line__c</referenceTo>
        <relationshipLabel>Agreement Lines (Revised Agreement Line)</relationshipLabel>
        <relationshipName>Agreement_Lines1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Revised__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Revised</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Revision_Approval_date__c</fullName>
        <label>Revision Approval date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Revision_Status__c</fullName>
        <label>Revision Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Revised</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sales_Agreement_Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Agreement Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Customer__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Ship_To</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Agreement Lines (Ship To)</relationshipLabel>
        <relationshipName>Agreement_Lines1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Updatable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Updatable</label>
        <type>Checkbox</type>
    </fields>
    <label>Agreement Line</label>
    <nameField>
        <label>Agreement Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreement Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Company__c.object
<CustomObject>
    <customHelpPage>HelpCompany</customHelpPage>
    <description>Each Logistics or Financial entity will be represented by a single Company record.  Master data for the Company is recorded here and used throughout the System.</description>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Customer__c.object
<CustomObject>
    <customHelpPage>HelpCustomers</customHelpPage>
    <description>Information that relates a Customer business to the manufacturing company (Company) and describes the business agreement between the two entities.</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The company that originates and owns the customer relationship</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Customers</relationshipLabel>
        <relationshipName>Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of this customer: Approved,Under Consideration,Pending Approval,Not Approved,Inactive</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer</label>
    <nameField>
        <label>Customer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Product__c.object
<CustomObject>
    <customHelpPage>HelpProducts</customHelpPage>
    <description>Products are sellable Items with Selling Unit of Measure included</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status indicates if the product is active or retired</description>
        <label>Status</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/AgreementCloneCon.cls
public with sharing class AgreementCloneCon {
    
    public Apexpages.Standardcontroller con {get;set;}
    public List<LineWrapper> lws {get;set;}
    public boolean renderGrid  {get;set;}
    public boolean disableButton {get;set;}
    public boolean isSuccess {get;set;}
    public String errorMsg{get;set;}
    public List<Agreement_line__c> agreementLine{get;set;}
    public Agreement__c agrm {get;set;}
    public Agreement__c agreement {get;set;}
    
    public AgreementCloneCon(){
        //system.debug('no args specified');
        ApexPages.addMessage( new ApexPages.Message( ApexPages.severity.ERROR, 'No agreement is specified.'));
    }
    
    public AgreementCloneCon(Apexpages.Standardcontroller controller){
        this.con = controller;
        agrm  = (Agreement__c) con.getRecord(); 
        agreement = (Agreement__c) con.getRecord(); 
        
        Agreement__c ag = [SELECT Id, Status__c, Start_Date__c, End_Date__c FROM Agreement__c WHERE id = :agrm.id ];
            if(ag.Start_Date__c < System.now())
        	    agrm.Start_Date__c = System.now();
        
            if(ag.End_Date__c < System.now())
                agrm.End_Date__c = null;
            else{
                agrm.End_Date__c = ag.End_Date__c;
            }
     
        updateLines();
        renderGrid = true;
    }
    
    public void updateLines(){
        lws = new List<LineWrapper>();
       
        List<String> statusList = new List<String>();
        statusList.add('Pending Approval');
        statusList.add('Rejected');
        
        //get all fields from object for cloning 
        SchemaUtil util = SchemaUtil.getInstance();
        set<String> allFields = new set<String>();
        Schema.DescribesobjectResult obj = util.getGlobalDescribe('Agreement_Line__c').getDescribe();
        for(Schema.sObjectField fieldapi: obj.fields.getMap().values()) {
            if(!fieldapi.getDescribe().isUnique()){
                allFields.add(string.valueof(fieldAPI) ); 
            }
        }
        
        SOQLUtil soql = new SOQLUtil('Agreement_Line__c', TRUE);
        soql.addFields(allFields);
        soql.setWhereClause('Agreement__c = \'' + con.getId() + '\'');
        soql.setOrderByClause('NAME');
        for(Agreement_Line__c al : Database.query(soql.getQuery())){
        	if(al.start_Date__c < system.now()){ 
        		al.start_Date__c = system.now();
        	}
        	if(al.End_Date__c < system.now()){
        		al.End_Date__c = null;
        	}
            lws.add(new LineWrapper(al));
        }
        //get agreement fields
        set<String> aFields = new set<String>();
        Schema.DescribesobjectResult o = util.getGlobalDescribe('Agreement__c').getDescribe();
        for(Schema.sObjectField fieldapi: o.fields.getMap().values()) {
            if(!fieldapi.getDescribe().isUnique()){
                aFields.add(string.valueof(fieldAPI) ); 
            }
        }
        
        soql = new SOQLUtil('Agreement__c', TRUE);
        soql.addFields(aFields);
        string  agreementId = con.getId();
        soql.setWhereClause('ID = :agreementId');
        agreement = Database.query(soql.getQuery());
        
        if(lws.size() == 0){
            renderGrid = false;
            ApexPages.addMessage( new ApexPages.Message( ApexPages.severity.WARNING, 'There are no lines for this agreement.'));
        }
    }
    
    public void agmtClone(){
        
        Savepoint sp = Database.setSavepoint();
        list <Agreement__c> agmtList = new list <Agreement__c>();
        try{
            boolean hasLines = false;
            Agreement__c a = (Agreement__c)con.getRecord();
            Agreement__c agmt = new  Agreement__c();
            agmt = agreement.clone(false,true);
            agmt.name = agreement.name;
            agmt.Status__c = 'Draft';
            agmt.Agreement_Code__c  = null ;
            agmt.Customer__c = agreement.Customer__c;
            agmt.Bill_To__c = agreement.Bill_To__c;
            agmt.Sold_To__c = agreement.Sold_To__c;
            agmt.Ship_To__c = agreement.Ship_To__c;
            agmt.Start_date__c = agrm.Start_Date__c;
            agmt.End_date__c = agrm.End_Date__c;
            agmt.Activation_Date__c =  null;
            agmt.Recurrence_Start_Date__c =  null;
            agmt.Company__c = agreement.Company__c;
            agmt.Approval_Date__c   = null;
            
            agmtList.add(agmt);
            DML.insertAsUser(agmt);
            list <Agreement_Line__c> alList = new list <Agreement_Line__c>();
            Map<id, Agreement_Line__c> oldToNewAgreementLineMap = new Map<id,Agreement_Line__c>();
            

            for(LineWrapper lw : lws){
                if(lw.selected  ){
                  Agreement_Line__c aline = new  Agreement_Line__c();
                  aline = lw.al.clone(false,true);
                  aline.Agreement__c = agmt.id;
                  aline.Product__c = lw.al.Product__c;  
                  aline.Sales_Agreement_Quantity__c = lw.al.Sales_Agreement_Quantity__c;
                  aline.Agreement_Price__c = lw.al.Agreement_Price__c;
                  aline.Start_Date__c = lw.al.Start_Date__c;
                  aline.End_Date__c = lw.al.End_Date__c;
                  aline.Approval_Required__c  = false;   
                  aline.Updatable__c = true; 
                  aline.Remaining_Quantity__c = lw.al.Sales_Agreement_Quantity__c;
                  aline.Revised_Agreement_Line__c = null;  
                  aline.Revision_Status__c = null ; 
                  aline.Revision_Approval_date__c = null; //need to set it null because cloning set it to previous record Revision_Approval_date__c
                  aline.Revised__c = false;  //need to set to default because cloning set it to previous record Revised__c
                  aline.Parent_Agreement_Line__c = null;  //need to set it null because cloning set it to previous record Parent_Agreement_Line__c
                  aline.Line__c = null; //need to set it to null so trigger can set the appropriate line number
                  alList.add(aline);    
                  oldToNewAgreementLineMap.put(lw.al.id, aline);
                }
              
            }
			DML.insertAsUser(alList);

            alList.clear();
            for(LineWrapper lw : lws){
                if(lw.selected){
                    if (lw.al.Parent_Agreement_Line__c != NULL){
                        Agreement_Line__c tmp = oldToNewAgreementLineMap.get(lw.al.id);
                        tmp.Parent_Agreement_Line__c = oldToNewAgreementLineMap.get(lw.al.Parent_Agreement_Line__c).id;
                        alList.add(tmp);
                    }
                }
            }
			
			if (alList.size() > 0){
            	DML.updateAsUser(alList);
			}

              isSuccess = true;
              errorMsg = '<a href="/'+ agmt.Id+'">' + agmt.Name + '</a>' + ' was cloned successfully'; 
                   
           }
            catch(Exception ex){
                Database.rollback(sp);
                ApexPages.addMessage( new ApexPages.Message( ApexPages.severity.ERROR, MessageUtil.toFriendlyErrorMessage(ex.getMessage())));
                System.debug(LoggingLevel.ERROR, ex.getStackTraceString() + ' ' + ex.getMessage());
        }
    }
    

    
    public class LineWrapper{
        
        public Agreement_Line__c al {get;set;}
        public boolean selected {get;set;}
        

        public LineWrapper(Agreement_Line__c al){
            
            this.al = al;
            
            this.selected = true;
           
        }
        
    }
    
    
   
       
}