src-ken&y/objects/Agreement__c.object
<CustomObject>
    <customHelpPage>HelpAgreement</customHelpPage>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Customer__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Corporate_Parent</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Agreement_Line__c.object
<CustomObject>
    <fields>
        <fullName>Pricebook__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pricebook</label>
        <referenceTo>Pricebook__c</referenceTo>
        <relationshipLabel>Agreement Lines</relationshipLabel>
        <relationshipName>Agreement_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Agreement Lines</relationshipLabel>
        <relationshipName>Agreement_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Agreement Line</label>
    <nameField>
        <label>Agreement Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreement Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Component__c.object
<CustomObject>
    <customHelpPage>HelpItemSpecifications</customHelpPage>
    <description>Product structure details</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company this Component belongs to</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Components</relationshipLabel>
        <relationshipName>Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Component</label>
    <nameField>
        <label>Component</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Customer__c.object
<CustomObject>
    <customHelpPage>HelpCustomers</customHelpPage>
    <description>Information that relates a Customer business to the manufacturing company (Company) and describes the business agreement between the two entities.</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The company that originates and owns the customer relationship</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Customers</relationshipLabel>
        <relationshipName>Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pricebook__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Pricebooks are associated with the Sold-to customer (one pricebook per customer).</inlineHelpText>
        <label>Pricebook</label>
        <referenceTo>Pricebook__c</referenceTo>
        <relationshipLabel>Customers</relationshipLabel>
        <relationshipName>Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Track_Install_Base__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Track Install Base</label>
        <type>Checkbox</type>
    </fields>
    <label>Customer</label>
    <nameField>
        <label>Customer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <recordTypes>
        <fullName>Site</fullName>
        <active>true</active>
        <label>Site</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Fulfillment__c.object
<CustomObject>
    <customHelpPage>HelpFulfillment</customHelpPage>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Fulfillments</relationshipLabel>
        <relationshipName>Fulfillments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Fulfillments</relationshipLabel>
        <relationshipName>Fulfillments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Fulfillments</relationshipLabel>
        <relationshipName>Fulfillments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Fulfillment</label>
    <nameField>
        <label>Fulfillment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fulfillments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Item__c.object
<CustomObject>
    <customHelpPage>HelpItems</customHelpPage>
    <description>Item Master object</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company that controls this item</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Track_Install_Base__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Track Install Base</label>
        <type>Checkbox</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Item_Specification__c.object
<CustomObject>
    <customHelpPage>HelpItemSpecifications</customHelpPage>
    <description>Item Specifications and Component Header</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company that this Item Specification belongs to</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Item Specfications</relationshipLabel>
        <relationshipName>Item_Specfications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item Specification</label>
    <nameField>
        <label>Item Specification</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Specifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Pricebook__c.object
<CustomObject>
    <customHelpPage>HelpPricebooks</customHelpPage>
    <description>List prices for a company and the products it sells</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The company that this pricebook belongs to</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Pricebooks</relationshipLabel>
        <relationshipName>Pricebooks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Pricebook</label>
    <nameField>
        <label>Pricebook Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricebooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Product__c.object
<CustomObject>
    <customHelpPage>HelpProducts</customHelpPage>
    <description>Products are sellable Items with Selling Unit of Measure included</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Sales_Order__c.object
<CustomObject>
    <customHelpPage>HelpSalesOrders_Managing</customHelpPage>
    <description>Sales Order Header</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Customer</description>
        <label>Customer Sold To</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <errorMessage>Sales Order Customer value does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>Customer__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Sold To</value>
            </filterItems>
            <filterItems>
                <field>Customer__c.Company__c</field>
                <operation>equals</operation>
                <valueField>$Source.Company__c</valueField>
            </filterItems>
            <filterItems>
                <field>Customer__c.Company__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Sales Orders (Customer)</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pricebook__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Pricebook used for this sales order, defaults from Sold To customer</description>
        <label>Pricebook</label>
        <referenceTo>Pricebook__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Sales_Order_Line__c.object
<CustomObject>
    <customHelpPage>HelpSalesOrders_Managing</customHelpPage>
    <description>Line Items on the Sales Order.</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company passed down from the sales order header</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Sales Order Lines (Customer)</relationshipLabel>
        <relationshipName>Sales_Order_Lines2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pricebook__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pricebook</label>
        <referenceTo>Pricebook__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <label>Sales Order Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/SKID__c.object
<CustomObject>
    <customHelpPage>HelpSKIDAbout</customHelpPage>
    <description>Stock Keeping ID</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>SKIDs</relationshipLabel>
        <relationshipName>SKIDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>SKIDs</relationshipLabel>
        <relationshipName>SKIDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SKID</label>
    <nameField>
        <label>SKID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SKIDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/AgreementDeinstallExtTest.cls
@isTest
private class AgreementDeinstallExtTest {

//    static testMethod void myUnitTest() {
//
//        TestFuel fuel = new TestFuel();
//        Company__c company = fuel.company;
//        Customer__c customerBillTo = fuel.customerBillTo;
//        Customer__c customerSoldTo = fuel.customerSoldTo;
//        Customer__c customerShipTo = fuel.customerShipto;
//        customerShipTo.Track_Install_Base__c = true;
//        update customerShipTo;
//        Pricebook__c pricebook = fuel.pricebook;
//        Product__c product = fuel.product;
//        List<Item__c> itemList = fuel.itemList;
//        Item_Specification__c configItemSpec = fuel.configItemSpec;
//        List<Component__c> components = fuel.components;
//        Product__c configProduct = fuel.configProduct;
//        Item__c item = new Item__c(Id = configProduct.Item__c);
//        item.Track_Install_Base__c = true;
//        update item;
//        Agreement__c agreement = fuel.agreement;
//        Customer__c site = fuel.customerSite;
//        Agreement_Line__c agreementLine = fuel.agreementLine;
//        agreementLine.Revision_Status__c = null;
//        update agreementLine;
//
//
//        agreement = [Select Customer__c, Customer__r.RecordType.DeveloperName, Status__c,
//                       Customer__r.Parent_Customer__c, Customer__r.Parent_Customer__r.Name, Company__r.Serial_Control__c,
//                       Customer__r.Parent_Customer__r.Parent_Customer__c, Customer__r.Parent_Customer__r.Parent_Customer__r.Name,
//                       Customer__r.Top_Parent_Customer__c, Customer__r.Top_Parent_Customer__r.Name From Agreement__c where id =:fuel.agreement.id limit 1];
//
//
//
//        AgreementReleaseExt ext = new AgreementReleaseExt(new Apexpages.Standardcontroller(agreement));
//        ext.updateLines();
//        JsonResult jsonResult = AgreementReleaseExt.getAgreementLineData(agreement.Id);
//        system.assertNotEquals(0, jsonResult.records.size(), Apexpages.getMessages());
//
//        AgreementReleaseExt.LineWrapper lineWrapper = new AgreementReleaseExt.LineWrapper();
//        lineWrapper.al = agreementLine;
//        lineWrapper.qty = 10;
//        lineWrapper.selected = true;
//        lineWrapper.used = false;
//        lineWrapper.isSerialProduct = false;
//        List<AgreementReleaseExt.LineWrapper> lineWrapperList = new List<AgreementReleaseExt.LineWrapper>();
//        lineWrapperList.add(lineWrapper);
//        Test.startTest();
//        DataSourceResult result = AgreementReleaseExt.createSalesOrders(lineWrapperList, agreement.Id, customerBillTo.Id, customerSoldTo.Id, customerShipTo.Id, null);
//        List<Sales_Order_Line__c> sols = [SELECT Id FROM Sales_Order_Line__c];
//        system.assertNotEquals(0, sols.size(), Apexpages.getMessages());
//
//        Fulfillment__c tmpFulf = new Fulfillment__c();
//        tmpFulf.Sales_Order_Line__c = sols[0].Id;
//        tmpFulf.Company__c = company.Id;
//        tmpFulf.Agreement__c = agreement.Id;
//        tmpFulf.Agreement_Line__c = fuel.agreementLine.Id;
//        tmpFulf.customer__c = customerSoldTo.Id;
//        tmpFulf.Quantity__c = 10;
//        tmpFulf.status__c = 'Complete';
//        insert tmpFulf;
//
//
//        List<SKID__c> skids = [SELECT Id FROM SKID__c]; // WHERE Customer__c = :site.Id
//        system.assertNotEquals(0, skids.size());
//
//        List<Fulfillment__c> fs = [SELECT Id, Status__c FROM Fulfillment__c WHERE Agreement_Line__r.Agreement__c = :agreement.Id];
//        system.assertNotEquals(0, fs.size(), fs);
//        for(Fulfillment__c f : fs){
//            f.Status__c = 'Complete';
//            f.quantity__c = 10;
//        }
//
//        update fs;
//
//
//        AgreementDeinstallExt extd = new AgreementDeinstallExt(new Apexpages.Standardcontroller(agreement));
//        system.assertNotEquals(0, extd.installationDetails.size(), extd);
//        system.assertNotEquals(0, extd.installationDetails[0].skids.size(), extd.installationDetails[0]);
//        Id skidId = extd.installationDetails[0].skids[0].skid.Id;
//        extd.installationDetails[0].skids[0].selected = true;
//        extd.installationDetails[0].skids[0].qty = 10;
//        extd.deinstall();
//
//
//        Test.stopTest();
//        List<Sales_Order__c> so = [SELECT Id, Agreement__c, (Select Id, Unit_Price__c from Sales_Order_Lines__r) FROM Sales_Order__c WHERE Type__c = 'Adjustment'];
//        //Test.stopTest();
//        system.assertNotEquals(0, so.size());
//        system.assertEquals(agreement.Id, so[0].Agreement__c);
//        system.assertEquals(1,so[0].Sales_Order_Lines__r.size());
//        system.assertEquals(100,so[0].Sales_Order_Lines__r[0].Unit_Price__c);//KNDY-7929
//
//
//        Fulfillment__c deinstallFulf = new Fulfillment__c();
//        deinstallFulf.Sales_Order_Line__c = sols[0].Id;
//        deinstallFulf.Company__c = company.Id;
//        deinstallFulf.Agreement__c = agreement.Id;
//        deinstallFulf.Agreement_Line__c = fuel.agreementLine.Id;
//        deinstallFulf.customer__c = customerSoldTo.Id;
//        deinstallFulf.Quantity__c = -10;
//        deinstallFulf.status__c = 'Complete';
//        deinstallFulf.Type__c = 'Deinstall';
//        deinstallFulf.SKID__c = skidId;
//        insert deinstallFulf;
//
//        SKID__c skid = [SELECT Id, Quantity__c FROM SKID__c WHERE Id = :skidId];
//        system.assertEquals(0, skid.Quantity__c, 'There should be 0 quantity left at the install base');
//
//    }
}