src-ken&y/objects/Agreement__c.object
<CustomObject>
    <customHelpPage>HelpAgreement</customHelpPage>
    <fields>
        <fullName>Bill_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Bill to Customer: Record TypeEQUALSBill To</inlineHelpText>
        <label>Bill To</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <filterItems>
                <field>Customer__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Bill To</value>
            </filterItems>
            <filterItems>
                <field>Customer__c.Parent_Customer__c</field>
                <operation>equals</operation>
                <valueField>$Source.Customer__c</valueField>
            </filterItems>
            <filterItems>
                <field>Customer__c.Top_Parent_Customer__c</field>
                <operation>equals</operation>
                <valueField>$Source.Customer__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Agreements (Bill To)</relationshipLabel>
        <relationshipName>Agreements1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Customer__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Corporate_Parent</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Payment_Terms__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Terms</label>
        <referenceTo>Payment_Term__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>Now()</defaultValue>
        <label>Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Currency__c.object
<CustomObject>
    <customHelpPage>HelpCurrency</customHelpPage>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Currency</label>
    <nameField>
        <label>Currency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Customer__c.object
<CustomObject>
    <customHelpPage>HelpCustomers</customHelpPage>
    <description>Information that relates a Customer business to the manufacturing company (Company) and describes the business agreement between the two entities.</description>
    <fields>
        <fullName>Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Customers</relationshipLabel>
        <relationshipName>Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Related Customers</relationshipLabel>
        <relationshipName>Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of this customer: Approved,Under Consideration,Pending Approval,Not Approved,Inactive</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer</label>
    <nameField>
        <label>Customer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Fulfillment__c.object
<CustomObject>
    <customHelpPage>HelpFulfillment</customHelpPage>
    <fields>
        <fullName>Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Fulfillments</relationshipLabel>
        <relationshipName>Fulfillments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Fulfillments</relationshipLabel>
        <relationshipName>Fulfillments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Invoice_Ready__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Invoice Ready</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Revised</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Fulfillment</label>
    <nameField>
        <label>Fulfillment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fulfillments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Inventory_Transaction__c.object
<CustomObject>
    <customHelpPage>HelpInventoryTransaction</customHelpPage>
    <description>This object records the movements of items caused by WIP and inventory transactions</description>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Inventory Transactions</relationshipLabel>
        <relationshipName>Inventory_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Inventory Transaction</label>
    <nameField>
        <label>Inventory Transaction</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Product__c.object
<CustomObject>
    <customHelpPage>HelpProducts</customHelpPage>
    <description>Products are sellable Items with Selling Unit of Measure included</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status indicates if the product is active or retired</description>
        <label>Status</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Sales_Order_Line__c.object
<CustomObject>
    <customHelpPage>HelpSalesOrders_Managing</customHelpPage>
    <description>Line Items on the Sales Order.</description>
    <fields>
        <fullName>Currency__c</fullName>
        <formula>Sales_Order__r.Currency__r.ISO_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Currency</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Sales Order Lines (Customer)</relationshipLabel>
        <relationshipName>Sales_Order_Lines2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Line open if item is not shipped; line closed if shipped; line partial if partially shipped</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <label>Sales Order Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/SKID__c.object
<CustomObject>
    <customHelpPage>HelpSKIDAbout</customHelpPage>
    <description>Stock Keeping ID</description>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>SKIDs</relationshipLabel>
        <relationshipName>SKIDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SKID</label>
    <nameField>
        <label>SKID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SKIDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/ActivateFulfillmentsExt.cls
/**
 * Created by aravindbabusadhanandham on 11/6/17.
 */

global with sharing class ActivateFulfillmentsExt extends BaseController{

    private static SchemaUtil util = SchemaUtil.getInstance();
    public string NamespaceUU { get { return KSE.NamespaceUU; } }
    public GridRelatedListController.GridRelatedListConfig FulfillmentConfig {get; set;}
    public String fulfillmentLinesFieldList = null;
    public Apexpages.Standardcontroller con {get;set;}
    public id agreementId {get;set;}

    public String getfulfillmentLinesConfigJson() {
        String configStr = JSON.serialize(this.FulfillmentConfig);

        return configStr;
    }
    public string getfulfillmentLinesFieldList() {
        if (fulfillmentLinesFieldList == null && FulfillmentConfig != null) {

            // get the contract lines field info list
            List<FieldInfo> fieldInfoList = FieldInfo.fetchJsonFieldInfos(FulfillmentConfig.objectName, FulfillmentConfig.fieldset);

            FieldInfo f = FieldInfo.getFieldInfo('invoice_ready__c', util.getGlobalDescribe(FulfillmentConfig.objectName));
            fieldInfoList.add(f);
            // set all the fields as readonly
            for(Integer i = 0; i < fieldInfoList.size(); i++) {
                String fieldName = fieldInfoList[i].field;
                fieldInfoList[i].field = fieldName;
                fieldInfoList[i].editable = false;

                //Rename the start and end date on fulfillments
                if (fieldName == 'end_date__c') {
                    fieldInfoList[i].title = 'Fulfillment End Date';
                    fieldInfoList[i].editable = true;
                } else if (fieldName == 'start_date__c') {
                    fieldInfoList[i].title = 'Fulfillment Start Date';
                    fieldInfoList[i].editable = true;
                } else if (fieldName == 'invoice_ready__c') {
                    fieldInfoList[i].editable = true;
                }
            }

            fulfillmentLinesFieldList = JSON.serialize(fieldInfoList);
        }

        return fulfillmentLinesFieldList;
    }

    public ActivateFulfillmentsExt(ApexPages.StandardController controller) {

        this.con = controller;

        if(this.con == null){
            ApexPages.addMessage( new ApexPages.Message( ApexPages.severity.ERROR, 'No agreement is specified.'));
        }else{
            if(!test.isRunningTest()){
                this.con.addFields(new list<String>{'Customer__c', 'Customer__r.RecordType.DeveloperName', 'Status__c', 'Currency__c',//Ship To
                        'Customer__r.Parent_Customer__c', 'Customer__r.Parent_Customer__r.Name', //Sold To
                        'Customer__r.Parent_Customer__r.Parent_Customer__c', 'Customer__r.Parent_Customer__r.Parent_Customer__r.Name', //Bill To
                        'Payment_Terms__c', 'Bill_To__c', 'Sold_To__c', 'Ship_To__c',
                        'Company__c', 'Company__r.Serial_Control__c', //company's serial attribute
                        'Customer__r.Top_Parent_Customer__c', 'Customer__r.Top_Parent_Customer__r.Name'});
            }
            Agreement__c a  = (Agreement__c) con.getRecord();

            agreementId = a.id;

        }

        //Fulfillment Grid config
        FulfillmentConfig = new GridRelatedListController.GridRelatedListConfig();
        FulfillmentConfig.uniqueId = 'FulfillmentGrid';
        FulfillmentConfig.title = 'Fulfillments';
        FulfillmentConfig.objectName = 'Fulfillment__c';
        FulfillmentConfig.fieldset = 'Return';
        FulfillmentConfig.buttons = 'columnmenu, search';
        FulfillmentConfig.alwaysUseFullDateTimeFormat = false;

    }

    @RemoteAction
    global static JsonResult getFulfillments(String id) {

        JsonResult result = new JsonResult();

        List<Fulfillment__c> Fulfillments = new List<Fulfillment__c>();

        List<String> filterCriteria = new List<String>();
        filterCriteria.add('Sales_Order_Line__r.Agreement__c = :id');
        filterCriteria.add('Type__c = \'Rental\'');
        filterCriteria.add('Invoice_Ready__c = false');
        filterCriteria.add('Inventory_Transaction__r.Type__c = \'Sales Order Shipment\'');

        String whereClause = '';
        if (filterCriteria.size() > 0) {
            whereClause += String.join(filterCriteria, ' AND ');
        }

        //List<String> fieldstoQuery = util.getFieldsFromFieldSetString('Fulfillment__c', 'Return');
        //Set<String> fieldSettouseinQuery = new Set<String>(fieldstoQuery);
        //datetime oDate = system.now();
        SOQLUtil soql = new SOQLUtil('Fulfillment__c', TRUE);
        soql.addFields(new Set<String>{'Id', 'Name', 'Company__c', 'SKID__c', 'Product__r.Item__c',
                'Product__r.Item__r.Item_Attribute__c',
                'Product__r.Item__r.Item_Attribute__r.Serial_Number__c', 'Rate_Basis__c' });
        soql.addFields(util.getAllCustomFieldsFromObject('', 'Fulfillment__c'));
        //soql.addFields(fieldSettouseinQuery);
        soql.addFields(util.getAllCustomFieldsFromObject('Sales_Order_Line__r.','Sales_Order_Line__c'));
        soql.setWhereClause(whereClause);
        soql.setOrderByClause('LastModifiedDate');

        system.debug(LoggingLevel.Error, 'soql.getQuery()--'+soql.getQuery());
        Fulfillments = database.query(soql.getQuery());
        system.debug(LoggingLevel.Error, 'Fulfillments--'+Fulfillments);

        result.success = true;
        result.records = Fulfillments;

        return result ;
    }

    @RemoteAction
    global static JsonResult updateFulfillments(List<Fulfillment__c> flmts) {

        JsonResult result = new JsonResult();
        Savepoint sp = Database.setSavepoint();
        if (flmts.size() > 0) {
            try{
                for (Fulfillment__c flmt : flmts) {
                    //flmt.Start_Date__c = system.now();
                    //flmt.End_Date__c = null;
                    flmt.End_Date__c = (flmt.End_Date__c != Datetime.newInstance(0)) ? flmt.End_Date__c : null;
                    flmt.Invoice_Ready__c = true;
                }
                DML.updateAsUser(flmts);
                result.addMessage('Selected fulfillments are activated successfully!', ApexPages.Severity.CONFIRM);
            }catch(Exception e){
                Database.rollback(sp);
                result.success = false;
                result.addMessage('Activating fulfillments failed: ' + e.getMessage() , ApexPages.Severity.ERROR);
                system.debug(LoggingLevel.ERROR, '\n' + e.getStackTraceString());
            }
        }


        return result ;
    }

}