src-ken&y/objects/APIGateway__mdt.object
<CustomObject>
    <fields>
        <fullName>Namespace__c</fullName>
        <label>Namespace</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target__c</fullName>
        <label>Target</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>API Gateway</label>
    <pluralLabel>API Gateways</pluralLabel>
</CustomObject>

src-ken&y/objects/Bin__c.object
<CustomObject>
    <customHelpPage>HelpBins</customHelpPage>
    <description>Bin is a sub-level of location</description>
    <fields>
        <fullName>Blocked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Blocked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <description>Lookup to Location.</description>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Bins</relationshipLabel>
        <relationshipName>Bins</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Max_Capacity__c</fullName>
        <label>Max Capacity</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Packaging_UOM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Packaging UOM</label>
        <referenceTo>UOM__c</referenceTo>
        <relationshipLabel>Bins</relationshipLabel>
        <relationshipName>Bins</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bin</label>
    <nameField>
        <label>Bin</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bins</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Configuration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>(Name, Value) pairs, holds configuration switches for fine tuning subsystems</description>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Configuration</label>
</CustomObject>

src-ken&y/objects/Facility__c.object
<CustomObject>
    <customHelpPage>HelpFacilites</customHelpPage>
    <description>Warehouse or building</description>
    <label>Facility</label>
    <nameField>
        <label>Facility</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Fixed_Asset__c.object
<CustomObject>
    <customHelpPage>HelpFixedAssets</customHelpPage>
    <description>Stores the companies fixed assets for tracking and depreciation</description>
    <fields>
        <fullName>Fixed_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link the relevant corporate book tax asset when creating a fixed asset for tax book purposes</description>
        <inlineHelpText>Link the relevant corporate book tax asset when creating a fixed asset for tax book purposes</inlineHelpText>
        <label>Fixed Asset (Corporate Book)</label>
        <referenceTo>Fixed_Asset__c</referenceTo>
        <relationshipLabel>Fixed Assets (Tax Books)</relationshipLabel>
        <relationshipName>Tax_Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The physical location of the asset.</description>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Fixed Assets</relationshipLabel>
        <relationshipName>Fixed_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Fixed Asset</label>
    <nameField>
        <label>Fixed Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fixed Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Location__c.object
<CustomObject>
    <customHelpPage>HelpLocations</customHelpPage>
    <description>Organizational Unit or physical location primarily used if  subclassification reporting is desired</description>
    <fields>
        <fullName>Bin_Tracked__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Specifies whether this location has bins tracked.</description>
        <label>Bin Tracked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Facility__c</fullName>
        <description>Lookup to facility</description>
        <label>Facility</label>
        <referenceTo>Facility__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Mixed_Bins_Allowed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mixed Bins Allowed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Track_Bin_Capacity__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Track Bin Capacity</label>
        <type>Checkbox</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Package_Class__c.object
<CustomObject>
    <customHelpPage>HelpPackageClasses</customHelpPage>
    <description>Package Class defines the UOM hierarchies.</description>
    <label>Package Class</label>
    <nameField>
        <label>Package Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Package Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Serial__c.object
<CustomObject>
    <customHelpPage>HelpSerials</customHelpPage>
    <fields>
        <fullName>Fixed_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Fixed Asset</label>
        <referenceTo>Fixed_Asset__c</referenceTo>
        <relationshipLabel>Serials</relationshipLabel>
        <relationshipName>Serials</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Serial</label>
    <nameField>
        <label>Serial Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Serials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/UOM__c.object
<CustomObject>
    <customHelpPage>HelpUOM</customHelpPage>
    <description>Units of Measure.</description>
    <fields>
        <fullName>Package_Class__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Package Class for the UOM.</description>
        <label>Package Class</label>
        <referenceTo>Package_Class__c</referenceTo>
        <relationshipLabel>UOMs</relationshipLabel>
        <relationshipName>UOMs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>UOM</label>
    <nameField>
        <label>UOM</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UOMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/BaseController.cls
global virtual with sharing class BaseController {

	public class BaseControllerException extends Exception{}

	// This will show a top page along with the existing bottom pager fr serials popup
	public Boolean serialShowTopBar { get {
		if ( serialShowTopBar == null ) {
			Configuration__c config = Configuration__c.getAll().get ( 'SerialShowTopBar' );
			if ( config == null || String.isEmpty(config.Value__c) || !config.Value__c.equalsIgnoreCase('true') ) {
				serialShowTopBar = false;
			} else {
				serialShowTopBar = true;
			}
		}
		return serialShowTopBar;
	} private set;}

	public BaseController() {
	}

	public BaseController(ApexPages.StandardSetController scon) {
		// just to support integration with vf pages
	}

	public BaseController(ApexPages.StandardController scon) {
		// just to support integration with vf pages
	}

	@AuraEnabled
	@RemoteAction
	global static Action.Response doAction(string actionTarget, string obj){
		system.debug('actionTarget: ' + actionTarget);
		system.debug('object: ' + obj);
		Action.Target actionType;
		long thenTime = system.now().getTime();
		APIGateway__mdt route = APIGateway.getRoute(actionTarget);
		if(route != null){
			Type t;
			if(!string.isBlank(route.Namespace__c)){
				t = Type.forName(route.Namespace__c, route.Target__c);
			}else{
				t = Type.forName(route.Target__c);
			}
			actionType = (Action.Target)t.newInstance();
		}else{
			throw new BaseControllerException('Unknown target');
		}
		Action.Response r = actionType.execute(obj);
		long nowTime = system.now().getTime();
		system.debug('TIME: '  + (nowTime - thenTime));
		system.debug('resp: ' + r);
		return r;
	}

	@RemoteAction
	global static List<SelectListItem> lookupSearch(string searchTerm, string objectName) {
		return lookupSearchFilter(searchTerm, objectName, '');
	}

	@RemoteAction
	global static List<SelectListItem> lookupSearchFilter(string searchTerm, string objectName, string filterCriteria) {
		SchemaUtil util = SchemaUtil.getInstance();
		List<SelectListItem> selectList = new List<SelectListItem>();

		if (String.isBlank(objectName))
		{
			return selectList;
		}

		Schema.SObjectType objectType = util.getGlobalDescribe(objectName);

		SOQLUtil soql = new SOQLUtil(objectName);
		soql.addFields(new set<string>{'Id', 'Name'});

		String filterString = '';
		System.debug(LoggingLevel.INFO, '*** searchTerm: ' + searchTerm);
		if(String.isNotBlank(searchTerm)){
			filterString += 'Name LIKE \'%' + String.escapeSingleQuotes(searchTerm) + '%\'';

			if(searchTerm.length() <= 3) {
				soql.setLimit(100);
			}
		}else{
			soql.setLimit(100);
		}

		if(String.isNotBlank(filterCriteria)){
			if(filterString.trim().startsWith('Name')) {
				filterString += ' AND ' + filterCriteria;
			}
			else {
				filterString += filterCriteria;
			}
		}

		soql.setWhereClause(filterString);
		soql.setOrderByClause('Name');
		system.debug('query: ' + soql.getQuery());
		List<SObject> result = Database.query(soql.getQuery());

		for (SObject obj : result) {
			String id = String.valueOf(obj.get('Id'));
			String name = String.valueOf(obj.get('Name'));

			selectList.add(new SelectListItem(id, name));
		}

		return selectList;
	}

	@RemoteAction
	global static set<SelectListItem> lookupSearchFilterNoDuplicates(string searchTerm, string objectName, string filterCriteria) {
		SchemaUtil util = SchemaUtil.getInstance();
		set<SelectListItem> selectList = new set<SelectListItem>();
		map<id,list<SelectListItem>>  mSelectItems = new map<id,list<SelectListItem>>();
		if (String.isBlank(objectName))
		{
			return selectList;
		}

		Schema.SObjectType objectType = util.getGlobalDescribe(objectName);

		SOQLUtil soql = new SOQLUtil(objectName);
		soql.addFields(new set<string>{'Name'});
		String filterString = '';
		System.debug(LoggingLevel.INFO, '*** searchTerm: ' + searchTerm);
		if(String.isNotBlank(searchTerm)){
			filterString += 'Name LIKE \'%' + String.escapeSingleQuotes(searchTerm) + '%\'';

			if(searchTerm.length() <= 3) {
				soql.setLimit(100);
			}
		}

		if(String.isNotBlank(filterCriteria)){
			if(filterString.trim().startsWith('Name')) {
				filterString += ' AND ' + filterCriteria;
			}
			else {
				filterString += filterCriteria;
			}
		}
		if(String.isNotBlank(searchTerm)){
			filterString += ' GROUP BY Name';

		}
		soql.setWhereClause(filterString );
		//soql.setOrderByClause('Name');
		system.debug('query: ' + soql.getQuery());
		List<SObject> result = Database.query(soql.getQuery());
		set<string> sObjectNameSet = new set<string>();
	    /*for (SObject obj : result) {
	    	//String id = String.valueOf(obj.get('Id'));
			String name = String.valueOf(obj.get('Name'));
			sObjectNameSet.add(name);
		}*/
		for (SObject obj : result) {
			selectList.add(new SelectListItem(String.valueOf(obj.get('Name')), String.valueOf(obj.get('Name'))));

		}

		return selectList;
	}

	@RemoteAction
	global static List<SelectListItem> getPicklistValues(string objectName, string fieldName)
	{
		SchemaUtil util = SchemaUtil.getInstance();
		List<SelectListItem> selectList = new List<SelectListItem>();

		if (String.isBlank(objectName) || String.isBlank(fieldName))
		{
			return selectList;
		}

		Map<String, sObjectField> fieldmap = util.getFieldsMap(objectName);
		Schema.DescribeFieldResult dfr = fieldMap.get(fieldName).getDescribe();

		if (dfr.getType() == Schema.DisplayType.Picklist) {
			selectList.add(new SelectListItem(' ', '--Any--'));

			for (Schema.PicklistEntry pe : dfr.getPicklistValues()) {
				if (pe.isActive()) {
					selectList.add(new SelectListItem(pe.getValue(), pe.getLabel()));
				}
			}
		}

		return selectList;
	}

	@RemoteAction
	global static Serial__c refreshSerialAttr( Id serialId ){

		set<String> serialFields = new set<string>{ 'id', 'name', 'Fixed_Asset__r.Name'};
		serialFields.addAll(SchemaUtil.getInstance().getAllCustomFieldsFromObject(null, 'Serial__c'));
		String whereClause = ' Id =:serialId ';

		SOQLUtil soql = new SOQLUtil('Serial__c');
		soql.addFields(serialFields);
		soql.setWhereClause(whereClause);

		List<Serial__c> serials = (List<Serial__c>)Database.query(soql.getQuery());
		if(serials.size() > 0){
			return serials[0];
		}
		else{
			return null;
		}
	}

    @RemoteAction
    global static Location__c getLocation(Id locId) {
        SOQLUtil locQuery = new SOQLUtil('Location__c');
        locQuery.addFields(new Set<String>{ 'Id', 'Name', 'Bin_Tracked__c', 'Facility__c', 'Mixed_Bins_Allowed__c', 'Track_Bin_Capacity__c' });
        locQuery.setWhereClause('Id = :locId');
        return Database.query(locQuery.getQuery());
    }

    @RemoteAction
    global static Bin__c getBin(Id binId) {
        SOQLUtil binQuery = new SOQLUtil('Bin__c');
        binQuery.addFields(new Set<String>{ 'Id', 'Name', 'Blocked__c', 'Location__c', 'Max_Capacity__c', 'Packaging_UOM__c', 'Packaging_UOM__r.Package_Class__c' });
        binQuery.setWhereClause('Id = :binId');
        return Database.query(binQuery.getQuery());
    }
}