src-ken&y/objects/Asset_Class__c.object
<CustomObject>
    <customHelpPage>HelpAssetClass</customHelpPage>
    <description>Relates fixed assets to their approriate GL Accounts and stores instructions on how to process the depreciation.</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Asset Classes</relationshipLabel>
        <relationshipName>Asset_Classes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Asset Class</label>
    <nameField>
        <label>Asset Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Company__c.object
<CustomObject>
    <customHelpPage>HelpCompany</customHelpPage>
    <description>Each Logistics or Financial entity will be represented by a single Company record.  Master data for the Company is recorded here and used throughout the System.</description>
    <fields>
        <fullName>Comp_Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Companies</relationshipLabel>
        <relationshipName>Companies</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Currency__c.object
<CustomObject>
    <customHelpPage>HelpCurrency</customHelpPage>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Currency</label>
    <nameField>
        <label>Currency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Fixed_Asset__c.object
<CustomObject>
    <customHelpPage>HelpFixedAssets</customHelpPage>
    <description>Stores the companies fixed assets for tracking and depreciation</description>
    <fields>
        <fullName>Acquisition_Cost__c</fullName>
        <description>Total cost to place asset in to service.</description>
        <inlineHelpText>stated in functional currency</inlineHelpText>
        <label>Acquisition Cost</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Asset_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Asset classfication.</description>
        <label>Asset Class</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Asset_Class__c.Company__c</field>
                <operation>equals</operation>
                <valueField>$Source.Company__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Asset_Class__c</referenceTo>
        <relationshipLabel>Fixed Assets</relationshipLabel>
        <relationshipName>Fixed_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Asset_Tag_Number__c</fullName>
        <description>Tag number used for identifying a specific asset.</description>
        <label>Asset Tag Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Fixed Assets</relationshipLabel>
        <relationshipName>Fixed_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Purchased__c</fullName>
        <description>Date this asset was purchased.</description>
        <label>Date Purchased</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Depreciation_Life__c</fullName>
        <description>Number of months over which this asset is to be depreciated.</description>
        <inlineHelpText>Number of months over which this asset is to be depreciated.</inlineHelpText>
        <label>Depreciation Life in Months</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Fixed_Asset_Type__c</fullName>
        <inlineHelpText>Can be either &quot;Tax&quot; or &quot;Accounting&quot;.</inlineHelpText>
        <label>Fixed Asset Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accounting</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Tax</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fixed_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link the relevant corporate book tax asset when creating a fixed asset for tax book purposes</description>
        <inlineHelpText>Link the relevant corporate book tax asset when creating a fixed asset for tax book purposes</inlineHelpText>
        <label>Fixed Asset (Corporate Book)</label>
        <referenceTo>Fixed_Asset__c</referenceTo>
        <relationshipLabel>Fixed Assets (Tax Books)</relationshipLabel>
        <relationshipName>Tax_Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>In_Service_Date__c</fullName>
        <description>Date this asset was put in to service.</description>
        <label>In Service Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Purchase_Price__c</fullName>
        <description>Purchase Price of asset.</description>
        <label>Purchase Price</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Purchase_currency__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Purchase Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Fixed Assets (Purchase currency)</relationshipLabel>
        <relationshipName>Fixed_Assets1</relationshipName>
        
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Residual_Value__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Residual value of the asset at the end of its useful life.</description>
        <inlineHelpText>Residual value of the asset at the end of its service life. The amount is stated in functional currency.</inlineHelpText>
        <label>Residual Value</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Defines the status of the asset during its lifecycle. Specifies if the asset is inactive, active or fully depreciated.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>CIP</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Depreciated</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tax_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Book</description>
        <label>Book</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Company__c</field>
                <operation>equals</operation>
                <valueField>Tax_Book__c.Company__r.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Tax_Book__c</referenceTo>
        <relationshipLabel>Fixed Assets</relationshipLabel>
        <relationshipName>Fixed_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Fixed Asset</label>
    <nameField>
        <label>Fixed Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fixed Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Fixed_Asset_Depreciation__c.object
<CustomObject>
    <customHelpPage>HelpFixedAssets</customHelpPage>
    <description>Records depreciation amounts and dates for fixed assets over time.</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Fixed Asset Depreciations</relationshipLabel>
        <relationshipName>Fixed_Asset_Depreciations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Fixed Asset Depreciations</relationshipLabel>
        <relationshipName>Fixed_Asset_Depreciations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Finalized__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag is set to true when the invoice is finalized and no more changes are expected</description>
        <label>Finalized</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Fixed_Asset__c</fullName>
        <description>The fixed asset that this depreciation is applied to.</description>
        <label>Fixed Asset</label>
        <referenceTo>Fixed_Asset__c</referenceTo>
        <relationshipLabel>Fixed Asset History</relationshipLabel>
        <relationshipName>Fixed_Asset_Depreciations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Fixed Asset Depreciation</label>
    <nameField>
        <label>Fixed Asset Depreciation Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fixed Asset Depreciations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Tax_Book__c.object
<CustomObject>
    <customHelpPage>Help_Books</customHelpPage>
    <description>Tax Book related to a Company</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Company.</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipName>Tax_Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent corporate book for this tax book.</description>
        <inlineHelpText>Lookup (Book). For tax books this is the parent book.</inlineHelpText>
        <label>Book</label>
        <referenceTo>Tax_Book__c</referenceTo>
        <relationshipLabel>Tax Books</relationshipLabel>
        <relationshipName>Tax_Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/FixedAssetCapitalizeExtTest.cls
@isTest
private class FixedAssetCapitalizeExtTest { 
	
	//--------Test data setup for all methods in this class----------//
	@testSetup
	static void allTheDataForThisTestClass() {
	    //Arun: moved out of test setup as FixedAssetTest.FixedAssetData is doing a lot of computation and with some new things in
	    //testData.cls , this was hitting too many soql within test setup 
	}
	
	static testMethod void testCapitalizeAsset() { 
         FixedAssetData fad = new FixedAssetData();
        
        Test.startTest();
        Currency__c defaultCurr = [Select Id from Currency__c where Id =: fad.td.company.Comp_Currency__c];
	    Fixed_Asset__c slfa = new Fixed_Asset__c();
    	slfa.company__c = fad.td.company.Id;
    	slfa.Asset_Class__c = fad.slac.Id;
    	slfa.Asset_Tag_Number__c = '5050505';
    	slfa.Date_Purchased__c = system.today().addYears(-5);
    	slfa.In_Service_Date__c = system.today().addYears(-5);
    	slfa.Acquisition_Cost__c = 38000;
        slfa.Purchase_Price__c = slfa.Acquisition_Cost__c;
        slfa.Purchase_Currency__c = defaultCurr.Id;
    	slfa.Depreciation_Life__c = 60;
    	slfa.Status__c = FixedAssetService.STATUS_CIP;
    	slfa.Residual_Value__c = 2000;
    	slfa.Fixed_Asset_Type__c = FixedAssetService.ASSET_ACCOUNTING;
    	slfa.Tax_Book__c = fad.corp.Id;
	   	insert slfa;
	    	
		Apexpages.Standardcontroller Con = new Apexpages.Standardcontroller(slfa);
    	test.setCurrentPage(page.FixedAssetCapitalize);
    	FixedAssetCapitalizeExt ext = new FixedAssetCapitalizeExt(Con);
    	system.assert(ext.isValid);
    	ext.btn_Capitalize();
    	Test.stopTest();

    	Fixed_Asset__c fa = [SELECT Id, status__c,
    							 (SELECT id ,finalized__c FROM Fixed_Asset_Depreciations__r)
    						   FROM Fixed_Asset__c 
    						   WHERE Id =:slfa.Id];
    	List<Fixed_Asset_Depreciation__c> fads = fa.Fixed_Asset_Depreciations__r;
    
    	system.assert(fa.status__c == FixedAssetService.STATUS_ACTIVE);
    	system.assert(fads.size()>0);
    	system.assertEquals(fads[0].finalized__c,true);
    	
    }
	
    static testMethod void testCapitalizeAssets() {
        
        FixedAssetData fad = new FixedAssetData();
        
        Test.startTest();
        Currency__c defaultCurr = [Select Id from Currency__c where Id =: fad.td.company.Comp_Currency__c];
	    Fixed_Asset__c slfa = new Fixed_Asset__c();
    	slfa.company__c = fad.td.company.Id;
    	slfa.Asset_Class__c = fad.slac.Id;
    	slfa.Asset_Tag_Number__c = '5050505';
    	slfa.Date_Purchased__c = system.today().addYears(-5);
    	slfa.In_Service_Date__c = system.today().addYears(-5);
    	slfa.Acquisition_Cost__c = 38000;
        slfa.Purchase_Price__c = slfa.Acquisition_Cost__c;
        slfa.Purchase_Currency__c = defaultCurr.Id;
    	slfa.Depreciation_Life__c = 60;
    	slfa.Status__c = FixedAssetService.STATUS_CIP;
    	slfa.Residual_Value__c = 2000;
    	slfa.Fixed_Asset_Type__c = FixedAssetService.ASSET_ACCOUNTING;
    	slfa.Tax_Book__c = fad.corp.Id;
	    	
	    insert slfa;
	    	
	    List<Fixed_Asset__c> fixedAssetsToCapitalize = [SELECT id 
	                                FROM Fixed_Asset__c LIMIT 2]; 
    	Apexpages.Standardsetcontroller ssCon = new Apexpages.Standardsetcontroller(fixedAssetsToCapitalize);
    	ssCon.setSelected(fixedAssetsToCapitalize);
    	
    	test.setCurrentPage(page.FixedAssetsCapitalize); 
    	FixedAssetCapitalizeExt ext = new FixedAssetCapitalizeExt(ssCon); 
    	
    	system.assert(!ext.hasInvalid, 'both sample assets are valid');
    	
    	ext.btn_CapitalizeAssets();
        Test.stopTest();
     
    	for(Fixed_Asset__c faCapitalized  : [SELECT Id, status__c 
    	                                            FROM Fixed_Asset__c 
    	                                            WHERE id in :fixedAssetsToCapitalize ]){
    		system.assertEquals(FixedAssetService.STATUS_ACTIVE,faCapitalized.status__c);
    	}
    	
    }
    
    static testMethod void testCapitalizeActiveAsset() {
        
         FixedAssetData fad = new  FixedAssetData();
        
        Test.startTest();
        
        Currency__c defaultCurr = [Select Id from Currency__c where Id =: fad.td.company.Comp_Currency__c];
	    Fixed_Asset__c slfa = new Fixed_Asset__c();
    	slfa.company__c = fad.td.company.Id;
    	slfa.Asset_Class__c = fad.slac.Id;
    	slfa.Asset_Tag_Number__c = '5050505';
    	slfa.Date_Purchased__c = system.today().addYears(-5);
    	slfa.In_Service_Date__c = system.today().addYears(-5);
    	slfa.Acquisition_Cost__c = 38000;
    	slfa.Purchase_Price__c = slfa.Acquisition_Cost__c;
        slfa.Purchase_Currency__c = defaultCurr.Id;
        slfa.Depreciation_Life__c = 60;
    	slfa.Status__c = FixedAssetService.STATUS_CIP;
    	slfa.Residual_Value__c = 2000;
    	slfa.Fixed_Asset_Type__c = FixedAssetService.ASSET_ACCOUNTING;
    	slfa.Tax_Book__c = fad.corp.Id;
	    	
	    insert slfa;
	    	
	    slfa.In_Service_Date__c = system.today().addDays(1);
        update slfa;
        
    	Apexpages.Standardcontroller Con = new Apexpages.Standardcontroller(slfa);
    	
    	pageReference testPage = page.FixedAssetCapitalize;
    	testPage.getParameters().put('Id', slfa.Id);
    	
    	test.setCurrentPage(testPage);
    	
    	FixedAssetCapitalizeExt ext = new FixedAssetCapitalizeExt(Con);
        Test.stopTest();
        system.assert(!ext.isValid);
    	
    }
}