src-ken&y/objects/Bin__c.object
<CustomObject>
    <customHelpPage>HelpBins</customHelpPage>
    <description>Bin is a sub-level of location</description>
    <fields>
        <fullName>Location__c</fullName>
        <description>Lookup to Location.</description>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Bins</relationshipLabel>
        <relationshipName>Bins</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Max_Capacity__c</fullName>
        <label>Max Capacity</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Packaging_UOM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Packaging UOM</label>
        <referenceTo>UOM__c</referenceTo>
        <relationshipLabel>Bins</relationshipLabel>
        <relationshipName>Bins</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bin</label>
    <nameField>
        <label>Bin</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bins</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Customer__c.object
<CustomObject>
    <customHelpPage>HelpCustomers</customHelpPage>
    <description>Information that relates a Customer business to the manufacturing company (Company) and describes the business agreement between the two entities.</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The company that originates and owns the customer relationship</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Customers</relationshipLabel>
        <relationshipName>Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer</label>
    <nameField>
        <label>Customer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Facility__c.object
<CustomObject>
    <customHelpPage>HelpFacilites</customHelpPage>
    <description>Warehouse or building</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Facilities</relationshipLabel>
        <relationshipName>Facilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Facility</label>
    <nameField>
        <label>Facility</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Item__c.object
<CustomObject>
    <customHelpPage>HelpItems</customHelpPage>
    <description>Item Master object</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company that controls this item</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Packaging_UOM__c</fullName>
        <description>Specify multiple Packaging UOM&apos;s for the Item. Limit 1 Packaging UOM per Packaging class Level</description>
        <inlineHelpText>Specify multiple Packaging UOM&apos;s for the Item. Limit 1 Packaging UOM per Packaging class Level</inlineHelpText>
        <label>Packaging UOM</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Location__c.object
<CustomObject>
    <customHelpPage>HelpLocations</customHelpPage>
    <description>Organizational Unit or physical location primarily used if  subclassification reporting is desired</description>
    <fields>
        <fullName>Bin_Tracked__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Specifies whether this location has bins tracked.</description>
        <label>Bin Tracked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Facility__c</fullName>
        <description>Lookup to facility</description>
        <label>Facility</label>
        <referenceTo>Facility__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Track_Bin_Capacity__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Track Bin Capacity</label>
        <type>Checkbox</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/SKID__c.object
<CustomObject>
    <customHelpPage>HelpSKIDAbout</customHelpPage>
    <description>Stock Keeping ID</description>
    <fields>
        <fullName>Bin__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The specific bin in which the skid is going to be placed inside the location.</description>
        <label>Bin</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Bin__c.Location__c</field>
                <operation>equals</operation>
                <valueField>$Source.Location__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Bin__c</referenceTo>
        <relationshipLabel>SKIDs</relationshipLabel>
        <relationshipName>SKIDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>SKIDs</relationshipLabel>
        <relationshipName>SKIDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Facility2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Facility</label>
        <referenceTo>Facility__c</referenceTo>
        <relationshipLabel>SKIDs</relationshipLabel>
        <relationshipName>SKIDs2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to location</description>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>SKIDs</relationshipLabel>
        <relationshipName>SKIDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Packaging_UOM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Packaging UOM</label>
        <referenceTo>UOM__c</referenceTo>
        <relationshipLabel>SKIDs (Packaging UOM)</relationshipLabel>
        <relationshipName>SKIDs_Packaging_UOM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Quantity of the item in this SKID</description>
        <label>Quantity (Packaging UOM)</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <label>SKID</label>
    <nameField>
        <label>SKID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SKIDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Stock_Movement_Rule__c.object
<CustomObject>
    <customHelpPage>HelpStockpoints</customHelpPage>
    <description>Defines the rules to use to decide the picking and the putaway location throughout the system.</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company for the rule.</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Stock Movement Rules</relationshipLabel>
        <relationshipName>Stock_Movement_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Facility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Facility for the rule.</description>
        <label>Facility</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Facility must belong to the company specified !</errorMessage>
            <filterItems>
                <field>Facility__c.Company__c</field>
                <operation>equals</operation>
                <valueField>$Source.Company__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Facility__c</referenceTo>
        <relationshipLabel>Stock Movement Rules</relationshipLabel>
        <relationshipName>Stock_Movement_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Location to be used in pick/putaway.</description>
        <label>Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Location must belong to the company and facility specified !</errorMessage>
            <filterItems>
                <field>Location__c.Facility__r.Company__c</field>
                <operation>equals</operation>
                <valueField>$Source.Company__c</valueField>
            </filterItems>
            <filterItems>
                <field>Location__c.Facility__c</field>
                <operation>equals</operation>
                <valueField>$Source.Facility__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Stock Movement Rules</relationshipLabel>
        <relationshipName>Stock_Movement_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Packaging_UOM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Packaging UOM</label>
        <referenceTo>UOM__c</referenceTo>
        <relationshipLabel>Stock Movement Rules</relationshipLabel>
        <relationshipName>Stock_Movement_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Stock Movement Rule</label>
    <nameField>
        <label>Stock Movement Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stock Movement Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/User_Preference__c.object
<CustomObject>
    <customHelpPage>HelpUserPreference</customHelpPage>
    <description>Track individual user preferences or configurations</description>
    <fields>
        <fullName>Default_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The company that is used to default on new orders</description>
        <label>Default Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>User Preferences</relationshipLabel>
        <relationshipName>User_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Default_Facility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Facility</description>
        <inlineHelpText>The default company facility to which a user belongs. This controls access to inventory transfer and inventory change records.</inlineHelpText>
        <label>Default Facility</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Default Facility does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>Facility__c.Company__c</field>
                <operation>equals</operation>
                <valueField>$Source.Default_Company__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Facility__c</referenceTo>
        <relationshipLabel>User Preferences</relationshipLabel>
        <relationshipName>User_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The user to whom this user preference applies.</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Preferences2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Preference</label>
    <nameField>
        <label>User Preference Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Preferences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/DirectPutawayTest.cls
@isTest
private class DirectPutawayTest {
    @testSetup
    private static void setupData() {
        TestFuel f = new TestFuel();
        System.assert(f.periodList != null);
        System.assert(f.itemList != null);
        System.assert(f.location3 != null);
        System.assert(f.location5 != null);
        System.assert(f.itemAttrObj2 != null);
        System.assert(f.smrsList != null);
        System.assert(f.stockMovementRuleList != null);

        insert new User_Preference__c(
            OwnerId = UserInfo.getUserId(),
            Default_Company__c = f.company.Id,
            Default_Facility__c = f.facility2.Id,
            User__c = UserInfo.getUserId()
        );
    }

    private static TestFuelQuery fuel = new TestFuelQuery();

    private static testMethod void putawayInventoryInEaches() {
        
        update new Location__c(Id = fuel.location3.Id, Bin_Tracked__c = true,Track_Bin_Capacity__c = true);
        
        Bin__c bin1 = new Bin__c(
            Name = 'Location 3 Bin1',
            Location__c = fuel.location3.Id,
            Max_Capacity__c = 100,
            Packaging_UOM__c = fuel.uomList[8].Id
        );
        insert bin1;
         Bin__c bin2 = new Bin__c(
            Name = 'Location 3 Bin2',
            Location__c = fuel.location3.Id,
            Max_Capacity__c = 100,
            Packaging_UOM__c = fuel.uomList[8].Id
        );
        insert bin2;
        
        SKID__c skid = new SKID__c(
            Facility2__c = fuel.facility2.Id,
            Location__c = fuel.location3.Id,
            Quantity__c = 100,
            Item__c = fuel.itemList[0].Id,
            Type__c = 'Location',
            Bin__c = bin1.id,
            Company__c = fuel.company.Id,
            Packaging_UOM__c = fuel.uomList[8].Id,
            Packaging_UOM__r = fuel.uomList[8]
        );
        insert skid;
        
        
        //create putaway dummy stock movement rule and putaway skid for direct putaway
        Stock_Movement_Rule__c dummySMR = new Stock_Movement_Rule__c(Name = 'Dummy',
        Rule_Type__c = null,
        Company__c = fuel.company.Id,
        Facility__c = fuel.facility2.Id,
        Class__c = null,
        Item__c =  fuel.itemList[0].Id,
        Customer__c = null,
        Source_Document__c = 'Transfer',
        source_location__c = fuel.location5.Id,
        Active__c = true);
        
        skid__c dummySkid = new skid__c (Name = 'DummySkid',
        Company__c = fuel.company.Id,
        Facility2__c = fuel.facility2.Id,
        Item__c =  fuel.itemList[0].Id,
        Quantity__c = 3,
        Packaging_UOM__c = fuel.uomList[8].Id,
        Packaging_UOM__r =  fuel.uomList[8],                        
        //License_Plate_Number__c = 'a3K50000001LFFB',
        Container_Item__c = fuel.itemList[0].Id ,
        Container_Item__r = fuel.itemList[0]                        
       );
          
        list<skidservice3.directPutawayWrapper> dpWList = new list<skidservice3.directPutawayWrapper>();
        skidservice3.directPutawayWrapper dpW =  new SkidService3.directPutawayWrapper( dummySMR, dummySkid);
        
        dpWList.add(dpW);
        map<integer, Bin__c > availableBin = SkidService3.availableBinForDirectPutaway(dpWList);
        system.assertEquals(1, availableBin.size());
        system.assertEquals(bin2.id, availableBin.get(0).id);
        
 
    }
     private static testMethod void putawayInventoryInCases() {
        
        update new Location__c(Id = fuel.location3.Id, Bin_Tracked__c = true,Track_Bin_Capacity__c = true);
        //cs-2 each,pt-3 cases,pt-eaches -6 cases = 12,PT -13,EA2 - 11
       // update new Item__c(Id = fuel.itemList[24].Id ,Container_Item__c =  fuel.itemList[22].Id );
        Bin__c bin1 = new Bin__c(
            Name = 'Location 3 Bin1',
            Location__c = fuel.location3.Id,
            Max_Capacity__c = 2,
            Packaging_UOM__c = fuel.uomList[12].Id
        );
        insert bin1;
         Bin__c bin2 = new Bin__c(
            Name = 'Location 3 Bin2',
            Location__c = fuel.location3.Id,
            Max_Capacity__c = 2,
            Packaging_UOM__c = fuel.uomList[12].Id
        );
        insert bin2;
        
        SKID__c skid = new SKID__c(
            Facility2__c = fuel.facility2.Id,
            Location__c = fuel.location3.Id,
            Quantity__c = 4,
            Item__c = fuel.itemList[14].Id,
            Type__c = 'Location',
            Bin__c = bin1.id,
            Company__c = fuel.company.Id,
            Packaging_UOM__c = fuel.uomList[11].Id,
            Packaging_UOM__r = fuel.uomList[11]
        );
        insert skid;
        
        
        //create putaway dummy stock movement rule and putaway skid for direct putaway
        Stock_Movement_Rule__c dummySMR = new Stock_Movement_Rule__c(Name = 'Dummy',
        Rule_Type__c = null,
        Company__c = fuel.company.Id,
        Facility__c = fuel.facility2.Id,
        Class__c = null,
        Item__c =  fuel.itemList[14].Id,
        Customer__c = null,
        Source_Document__c = 'Transfer',
        source_location__c = fuel.location5.Id,
        Active__c = true);
        
        skid__c dummySkid = new skid__c (Name = 'DummySkid',
        Company__c = fuel.company.Id,
        Facility2__c = fuel.facility2.Id,
        Item__c =  fuel.itemList[14].Id,
        Quantity__c = 3,
        Packaging_UOM__c = fuel.uomList[11].Id,
        Packaging_UOM__r =  fuel.uomList[11], 
        Container_Item__c = fuel.itemList[12].Id ,
        Container_Item__r = fuel.itemList[12]                        
       );
          
        list<skidservice3.directPutawayWrapper> dpWList = new list<skidservice3.directPutawayWrapper>();
        skidservice3.directPutawayWrapper dpW =  new SkidService3.directPutawayWrapper( dummySMR, dummySkid);
        
        dpWList.add(dpW);
        map<integer, Bin__c > availableBin = SkidService3.availableBinForDirectPutaway(dpWList);
        system.assertEquals(1, availableBin.size());
        system.assertEquals(bin2.id, availableBin.get(0).id);
        
 
    }
    private static testMethod void putawayInventoryInPartPallet() {
        
        update new Location__c(Id = fuel.location3.Id, Bin_Tracked__c = true,Track_Bin_Capacity__c = true);
        //cs-2 each,pt-3 cases,pt-eaches -6 cases = 12,PT -13,EA2 - 11
        Bin__c bin1 = new Bin__c(
            Name = 'Location 3 Bin1',
            Location__c = fuel.location3.Id,
            Max_Capacity__c = 1,
            Packaging_UOM__c = fuel.uomList[13].Id
        );
        insert bin1;
         Bin__c bin2 = new Bin__c(
            Name = 'Location 3 Bin2',
            Location__c = fuel.location3.Id,
            Max_Capacity__c = 2,
            Packaging_UOM__c = fuel.uomList[13].Id
        );
        insert bin2;
        LPN__c LPN1 = new LPN__c(
            Name = 'LPN-1'
        );
        insert LPN1;
        SKID__c skid = new SKID__c(
            Facility2__c = fuel.facility2.Id,
            Location__c = fuel.location3.Id,
            Quantity__c = 2,
            Item__c = fuel.itemList[14].Id,
            Type__c = 'Location',
            Bin__c = bin1.id,
            Company__c = fuel.company.Id,
            Packaging_UOM__c = fuel.uomList[12].Id,
            Packaging_UOM__r = fuel.uomList[12]
        );
        insert skid;
        
        
        //create putaway dummy stock movement rule and putaway skid for direct putaway
        Stock_Movement_Rule__c dummySMR = new Stock_Movement_Rule__c(Name = 'Dummy',
        Rule_Type__c = null,
        Company__c = fuel.company.Id,
        Facility__c = fuel.facility2.Id,
        Class__c = null,
        Item__c =  fuel.itemList[14].Id,
        Customer__c = null,
        Source_Document__c = 'Transfer',
        source_location__c = fuel.location5.Id,
        Active__c = true);
        
        skid__c dummySkid = new skid__c (Name = 'DummySkid',
        Company__c = fuel.company.Id,
        Facility2__c = fuel.facility2.Id,
        Item__c =  fuel.itemList[14].Id,
        Quantity__c = 1,
        Packaging_UOM__c = fuel.uomList[12].Id,
        Packaging_UOM__r =  fuel.uomList[12],                          
        License_Plate_Number__c = LPN1.id,
        Container_Item__c = fuel.itemList[13].Id ,//pallet container item
        Container_Item__r = fuel.itemList[13]                        
       );
          
        list<skidservice3.directPutawayWrapper> dpWList = new list<skidservice3.directPutawayWrapper>();
        skidservice3.directPutawayWrapper dpW =  new SkidService3.directPutawayWrapper( dummySMR, dummySkid);
        
        dpWList.add(dpW);
        map<integer, Bin__c > availableBin = SkidService3.availableBinForDirectPutaway(dpWList);
        system.assertEquals(1, availableBin.size());
        system.assertEquals(bin2.id, availableBin.get(0).id);
        
 
    }
    private static testMethod void putawayInventoryInPartPalletWithOnhandPartPalletInv() {
       
        update new Location__c(Id = fuel.location3.Id, Bin_Tracked__c = true,Track_Bin_Capacity__c = true);
        //cs-2 each,pt-3 cases,pt-6 eaches , cases = uomList[12],PT = uomList[13],EA2 - uomList[11]
        Bin__c bin1 = new Bin__c(
            Name = 'Location 3 Bin1',
            Location__c = fuel.location3.Id,
            Max_Capacity__c = 1,
            Packaging_UOM__c = fuel.uomList[13].Id
        );
        insert bin1;
         Bin__c bin2 = new Bin__c(
            Name = 'Location 3 Bin2',
            Location__c = fuel.location3.Id,
            Max_Capacity__c = 2,
            Packaging_UOM__c = fuel.uomList[13].Id
        );
        insert bin2;
        LPN__c LPN1 = new LPN__c(
            Name = 'LPN-1'
        );
        insert LPN1;
         LPN__c LPN2 = new LPN__c(
            Name = 'LPN-2'
        );
        insert LPN2;
        SKID__c skid = new SKID__c(
            Facility2__c = fuel.facility2.Id,
            Location__c = fuel.location3.Id,
            Quantity__c = 1,
            Item__c = fuel.itemList[14].Id,
            Type__c = 'Location',
            Bin__c = bin1.id,
            Company__c = fuel.company.Id,
            Packaging_UOM__c = fuel.uomList[12].Id,
            Packaging_UOM__r = fuel.uomList[12],
            License_Plate_Number__c = LPN2.id,
            Container_Item__c = fuel.itemList[13].Id ,//pallet container item
            Container_Item__r = fuel.itemList[13]                        
        );
        insert skid;
        
        
        //create putaway dummy stock movement rule and putaway skid for direct putaway
        Stock_Movement_Rule__c dummySMR = new Stock_Movement_Rule__c(Name = 'Dummy',
        Rule_Type__c = null,
        Company__c = fuel.company.Id,
        Facility__c = fuel.facility2.Id,
        Class__c = null,
        Item__c =  fuel.itemList[14].Id,
        Customer__c = null,
        Source_Document__c = 'Transfer',
        source_location__c = fuel.location5.Id,
        Active__c = true);
        
        skid__c dummySkid = new skid__c (Name = 'DummySkid',
        Company__c = fuel.company.Id,
        Facility2__c = fuel.facility2.Id,
        Item__c =  fuel.itemList[14].Id,
        Quantity__c = 1,
        Packaging_UOM__c = fuel.uomList[12].Id,
        Packaging_UOM__r =  fuel.uomList[12],                          
        License_Plate_Number__c = LPN1.id,
        Container_Item__c = fuel.itemList[13].Id ,//pallet container item
        Container_Item__r = fuel.itemList[13]                        
       );
          
        list<skidservice3.directPutawayWrapper> dpWList = new list<skidservice3.directPutawayWrapper>();
        skidservice3.directPutawayWrapper dpW =  new SkidService3.directPutawayWrapper( dummySMR, dummySkid);
        
        dpWList.add(dpW);
        map<integer, Bin__c > availableBin = SkidService3.availableBinForDirectPutaway(dpWList);
        system.assertEquals(1, availableBin.size());
        system.assertEquals(bin2.id, availableBin.get(0).id);
        
 
    }
    private static testMethod void putawayInventoryMatchingLPN() {
       
        update new Location__c(Id = fuel.location3.Id, Bin_Tracked__c = true,Track_Bin_Capacity__c = true);
        //cs-2 each,pt-3 cases,pt-eaches -6 cases = 12,PT -13,EA2 - 11
        Bin__c bin1 = new Bin__c(
            Name = 'Location 3 Bin1',
            Location__c = fuel.location3.Id,
            Max_Capacity__c = 2,
            Packaging_UOM__c = fuel.uomList[13].Id
        );
        insert bin1;
         Bin__c bin2 = new Bin__c(
            Name = 'Location 3 Bin2',
            Location__c = fuel.location3.Id,
            Max_Capacity__c = 2,
            Packaging_UOM__c = fuel.uomList[13].Id
        );
        insert bin2;
        LPN__c LPN1 = new LPN__c(
            Name = 'LPN-1'
        );
        insert LPN1;
         LPN__c LPN2 = new LPN__c(
            Name = 'LPN-2'
        );
        insert LPN2;
        //part pallet skid
        SKID__c skid = new SKID__c(
            Facility2__c = fuel.facility2.Id,
            Location__c = fuel.location3.Id,
            Quantity__c = 1,
            Item__c = fuel.itemList[14].Id,
            Type__c = 'Location',
            Bin__c = bin1.id,
            Company__c = fuel.company.Id,
            Packaging_UOM__c = fuel.uomList[12].Id,
            Packaging_UOM__r = fuel.uomList[12],
            License_Plate_Number__c = LPN1.id,
            Container_Item__c = fuel.itemList[13].Id ,
            Container_Item__r = fuel.itemList[13]                        
        );
        insert skid;
        //pallet skid
        SKID__c skid2 = new SKID__c(
            Facility2__c = fuel.facility2.Id,
            Location__c = fuel.location3.Id,
            Quantity__c = 1,
            Item__c = fuel.itemList[14].Id,
            Type__c = 'Location',   
            Bin__c = bin2.id,
            Company__c = fuel.company.Id,
            Packaging_UOM__c = fuel.uomList[13].Id,
            Packaging_UOM__r = fuel.uomList[13],
            License_Plate_Number__c = LPN2.id,
            Container_Item__c = fuel.itemList[13].Id ,
            Container_Item__r = fuel.itemList[13]                        
        );
        insert skid2;
        
        
        //create putaway dummy stock movement rule and putaway skid for direct putaway
        Stock_Movement_Rule__c dummySMR = new Stock_Movement_Rule__c(Name = 'Dummy',
        Rule_Type__c = null,
        Company__c = fuel.company.Id,
        Facility__c = fuel.facility2.Id,
        Class__c = null,
        Item__c =  fuel.itemList[14].Id,
        Customer__c = null,
        Source_Document__c = 'Transfer',
        source_location__c = fuel.location5.Id,
        Active__c = true);
        
        skid__c dummySkid = new skid__c (Name = 'DummySkid',
        Company__c = fuel.company.Id,
        Facility2__c = fuel.facility2.Id,
        Item__c =  fuel.itemList[14].Id,
        Quantity__c = 1,
        Packaging_UOM__c = fuel.uomList[12].Id,
        Packaging_UOM__r =  fuel.uomList[12],                          
        License_Plate_Number__c = LPN1.id,
        Container_Item__c = fuel.itemList[13].Id ,//pallet container item
        Container_Item__r = fuel.itemList[13]                        
       );
          
        list<skidservice3.directPutawayWrapper> dpWList = new list<skidservice3.directPutawayWrapper>();
        skidservice3.directPutawayWrapper dpW =  new SkidService3.directPutawayWrapper( dummySMR, dummySkid);
        
        dpWList.add(dpW);
        map<integer, Bin__c > availableBin = SkidService3.availableBinForDirectPutaway(dpWList);
        system.assertEquals(1, availableBin.size());
        system.assertEquals(bin1.id, availableBin.get(0).id);  
 
    }
    private static testMethod void putawayInventoryNoBinFound() {
        
        update new Location__c(Id = fuel.location3.Id, Bin_Tracked__c = true,Track_Bin_Capacity__c = true);
        //cs-2 each,pt-3 cases,pt-eaches -6 cases = 12,PT -13,EA2 - 11
      
        Bin__c bin1 = new Bin__c(
            Name = 'Location 3 Bin1',
            Location__c = fuel.location3.Id,
            Max_Capacity__c = 2,
            Packaging_UOM__c = fuel.uomList[12].Id
        );
        insert bin1;
         Bin__c bin2 = new Bin__c(
            Name = 'Location 3 Bin2',
            Location__c = fuel.location3.Id,
            Max_Capacity__c = 2,
            Packaging_UOM__c = fuel.uomList[12].Id
        );
        insert bin2;
        
        SKID__c skid = new SKID__c(
            Facility2__c = fuel.facility2.Id,
            Location__c = fuel.location3.Id,
            Quantity__c = 4,
            Item__c = fuel.itemList[14].Id,
            Type__c = 'Location',
            Bin__c = bin1.id,
            Company__c = fuel.company.Id,
            Packaging_UOM__c = fuel.uomList[11].Id,
            Packaging_UOM__r = fuel.uomList[11]
        );
        insert skid;
        
        SKID__c skid2 = new SKID__c(
            Facility2__c = fuel.facility2.Id,
            Location__c = fuel.location3.Id,
            Quantity__c = 4,
            Item__c = fuel.itemList[14].Id,
            Type__c = 'Location',
            Bin__c = bin2.id,
            Company__c = fuel.company.Id,
            Packaging_UOM__c = fuel.uomList[11].Id,
            Packaging_UOM__r = fuel.uomList[11]
        );
        insert skid2;
        
        
        //create putaway dummy stock movement rule and putaway skid for direct putaway
        Stock_Movement_Rule__c dummySMR = new Stock_Movement_Rule__c(Name = 'Dummy',
        Rule_Type__c = null,
        Company__c = fuel.company.Id,
        Facility__c = fuel.facility2.Id,
        Class__c = null,
        Item__c =  fuel.itemList[14].Id,
        Customer__c = null,
        Source_Document__c = 'Transfer',
        source_location__c = fuel.location5.Id,
        Active__c = true);
        
        skid__c dummySkid = new skid__c (Name = 'DummySkid',
        Company__c = fuel.company.Id,
        Facility2__c = fuel.facility2.Id,
        Item__c =  fuel.itemList[14].Id,
        Quantity__c = 3,
        Packaging_UOM__c = fuel.uomList[11].Id,
        Packaging_UOM__r =  fuel.uomList[11], 
        Container_Item__c = fuel.itemList[12].Id ,
        Container_Item__r = fuel.itemList[12]                        
       );
          
        list<skidservice3.directPutawayWrapper> dpWList = new list<skidservice3.directPutawayWrapper>();
        skidservice3.directPutawayWrapper dpW =  new SkidService3.directPutawayWrapper( dummySMR, dummySkid);
        
        dpWList.add(dpW);
        map<integer, Bin__c > availableBin = SkidService3.availableBinForDirectPutaway(dpWList);
        system.assertEquals(0, availableBin.size());//No bin found 
 
    }

    private static testMethod void putawayInventoryInMultipleWrapper() {
        
        update new Location__c(Id = fuel.location3.Id, Bin_Tracked__c = true,Track_Bin_Capacity__c = true);
        //cs-2 each,pt-3 cases,pt-eaches -6 cases = 12,PT -13,EA2 - 11
       // update new Item__c(Id = fuel.itemList[24].Id ,Container_Item__c =  fuel.itemList[22].Id );
        Bin__c bin1 = new Bin__c(
            Name = 'Location 3 Bin1',
            Location__c = fuel.location3.Id,
            Max_Capacity__c = 2,
            Packaging_UOM__c = fuel.uomList[12].Id
        );
        insert bin1;
         Bin__c bin2 = new Bin__c(
            Name = 'Location 3 Bin2',
            Location__c = fuel.location3.Id,
            Max_Capacity__c = 2,
            Packaging_UOM__c = fuel.uomList[12].Id
        );
        insert bin2;
        
        
        //create putaway dummy stock movement rule and putaway skid for direct putaway
        Stock_Movement_Rule__c dummySMR = new Stock_Movement_Rule__c(Name = 'Dummy',
        Rule_Type__c = null,
        Company__c = fuel.company.Id,
        Facility__c = fuel.facility2.Id,
        Class__c = null,
        Item__c =  fuel.itemList[14].Id,
        Customer__c = null,
        Source_Document__c = 'Transfer',
        source_location__c = fuel.location5.Id,
        Active__c = true);
        
        skid__c dummySkid = new skid__c (Name = 'DummySkid',
        Company__c = fuel.company.Id,
        Facility2__c = fuel.facility2.Id,
        Item__c =  fuel.itemList[14].Id,
        Quantity__c = 3,
        Packaging_UOM__c = fuel.uomList[11].Id,
        Packaging_UOM__r =  fuel.uomList[11], 
        Container_Item__c = fuel.itemList[12].Id ,
        Container_Item__r = fuel.itemList[12]                        
       );
       
        Stock_Movement_Rule__c dummySMR2 = new Stock_Movement_Rule__c(Name = 'dummySMR2',
        Rule_Type__c = null,
        Company__c = fuel.company.Id,
        Facility__c = fuel.facility2.Id,
        Class__c = null,
        Item__c =  fuel.itemList[14].Id,
        Customer__c = null,
        Source_Document__c = 'Transfer',
        source_location__c = fuel.location5.Id,
        Active__c = true);
        
        skid__c dummySkid2 = new skid__c (Name = 'DummySkid2',
        Company__c = fuel.company.Id,
        Facility2__c = fuel.facility2.Id,
        Item__c =  fuel.itemList[14].Id,
        Quantity__c = 3,
        Packaging_UOM__c = fuel.uomList[11].Id,
        Packaging_UOM__r =  fuel.uomList[11], 
        Container_Item__c = fuel.itemList[12].Id ,
        Container_Item__r = fuel.itemList[12]                        
       );
          
        list<skidservice3.directPutawayWrapper> dpWList = new list<skidservice3.directPutawayWrapper>();
        skidservice3.directPutawayWrapper dpW =  new SkidService3.directPutawayWrapper( dummySMR, dummySkid);
        skidservice3.directPutawayWrapper dpW2 =  new SkidService3.directPutawayWrapper( dummySMR2, dummySkid2);
        dpWList.add(dpW);
        dpWList.add(dpW2);
        system.assertEquals(2, dpWList.size(),dpWList);
        map<integer, Bin__c > availableBin = SkidService3.availableBinForDirectPutaway(dpWList);
        system.assertEquals(2, availableBin.size(),availableBin);
        system.assertEquals(bin1.id, availableBin.get(0).id);
        system.assertEquals(bin2.id, availableBin.get(1).id);
 
    }

    
}