src-ken&y/objects/Bin__c.object
<CustomObject>
    <customHelpPage>HelpBins</customHelpPage>
    <description>Bin is a sub-level of location</description>
    <fields>
        <fullName>Location__c</fullName>
        <description>Lookup to Location.</description>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Bins</relationshipLabel>
        <relationshipName>Bins</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Bin</label>
    <nameField>
        <label>Bin</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bins</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Facility__c.object
<CustomObject>
    <customHelpPage>HelpFacilites</customHelpPage>
    <description>Warehouse or building</description>
    <fields>
        <fullName>Facility_Identifier__c</fullName>
        <label>Facility Identifier</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Primary_Key__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>unique key used to data load this table</description>
        <externalId>true</externalId>
        <label>Primary Key</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Facility</label>
    <nameField>
        <label>Facility</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Item__c.object
<CustomObject>
    <customHelpPage>HelpItems</customHelpPage>
    <description>Item Master object</description>
    <fields>
        <fullName>Primary_Key__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Primary Key</label>
        <length>128</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Location__c.object
<CustomObject>
    <customHelpPage>HelpLocations</customHelpPage>
    <description>Organizational Unit or physical location primarily used if  subclassification reporting is desired</description>
    <fields>
        <fullName>Bin_Tracked__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Specifies whether this location has bins tracked.</description>
        <label>Bin Tracked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Facility_Identifier__c</fullName>
        <description>Facility code to link this location to a facility at data load time ( matches Primary_Key on Facility)</description>
        <label>Facility Identifier</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Facility__c</fullName>
        <description>Lookup to facility</description>
        <label>Facility</label>
        <referenceTo>Facility__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Mixed_Bins_Allowed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mixed Bins Allowed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary_Key__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>unique key to allow data loading</description>
        <externalId>true</externalId>
        <label>Primary Key</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/SKID__c.object
<CustomObject>
    <customHelpPage>HelpSKIDAbout</customHelpPage>
    <description>Stock Keeping ID</description>
    <fields>
        <fullName>Bin__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The specific bin in which the skid is going to be placed inside the location.</description>
        <label>Bin</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Bin__c.Location__c</field>
                <operation>equals</operation>
                <valueField>$Source.Location__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Bin__c</referenceTo>
        <relationshipLabel>SKIDs</relationshipLabel>
        <relationshipName>SKIDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>SKIDs</relationshipLabel>
        <relationshipName>SKIDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to location</description>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>SKIDs</relationshipLabel>
        <relationshipName>SKIDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>SKID Type delineates where the SKID is at in its life cycle</description>
        <inlineHelpText>SKID type reveals the state of the SKID in its lifecycle.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Forecast Demand</fullName>
                </value>
                <value>
                    <fullName>SO Demand</fullName>
                </value>
                <value>
                    <fullName>WOM Demand</fullName>
                </value>
                <value>
                    <fullName>WO Supply</fullName>
                </value>
                <value>
                    <fullName>PO Supply</fullName>
                </value>
                <value>
                    <fullName>History</fullName>
                </value>
                <value>
                    <fullName>Location</fullName>
                    <default>true</default>
                </value>
                <value>
               		<fullName>Planned Pick</fullName>
                 </value>
                 <value>
                     <fullName>Draft In-Transit</fullName>
                 </value>
                 <value>
                     <fullName>TO Supply</fullName>
                 </value>
                 <value>
                     <fullName>In-Transit</fullName>
                 </value>
                 <value>
                     <fullName>Allocated</fullName>
                 </value>
                 <value>
                     <fullName>TO Demand</fullName>
                 </value>
                 <value>
                     <fullName>WIP</fullName>
                 </value>
                 <value>
                     <fullName>Install Base</fullName>
                 </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SKID</label>
    <nameField>
        <label>SKID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SKIDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/LocationTriggerHandler.cls
public with sharing class LocationTriggerHandler {
    private static void setFacility(List<Location__c> locations, Boolean isBefore) {
        Relate.setLookupUsingField(locations, isBefore, 'Facility__c', 'Facility__c', 'Facility_Identifier__c', 'Primary_Key__c');
    }

    private static void checkMixedBins(Map<Id, Location__c> locations, Map<Id, Location__c> oldLocations) {
        Set<Id> locIds = new Set<Id>();
        for (Location__c loc:locations.values()) {
            if (loc.Bin_Tracked__c == true && loc.Mixed_Bins_Allowed__c == false && KSE.isFieldChanging('Mixed_Bins_Allowed__c', loc, oldLocations)) {
                locIds.add(loc.Id);
            }
        }

        if (locIds.size() > 0) {
            SOQLUtil skidQuery = new SOQLUtil('SKID__c', false, true);
            skidQuery.addFields(new Set<String>{ 'Bin__c binId', 'COUNT_DISTINCT(Item__c) itemCt' });
            skidQuery.setWhereClause('Location__c IN :locIds ' +
                                     'AND Type__c = \'' + SkidService3.SKID_TYPE_LOCATION + '\' ' +
                                     'GROUP BY Bin__c');

            Set<Id> binIds = new Set<Id>();
            for (AggregateResult ar:Database.query(skidQuery.getQuery())) {
                if ((Integer)ar.get('itemCt') > 1) binIds.add((Id)ar.get('binId'));
            }

            if (binIds.size() > 0) {
                SOQLUtil binQuery = new SOQLUtil('Bin__c');
                binQuery.addFields(new Set<String>{ 'Id', 'Name', 'Location__c' });
                binQuery.setWhereClause('Id IN :binIds');

                Map<Id, List<String>> binsWithMultipleItems = new Map<Id, List<String>>();
                for (Bin__c bin:Database.query(binQuery.getQuery())) {
                    if (binsWithMultipleItems.containsKey(bin.Location__c) == false) binsWithMultipleItems.put(bin.Location__c, new List<String>{ bin.Name });
                    else binsWithMultipleItems.get(bin.Location__c).add(bin.Name);
                }

                for (Id locId:binsWithMultipleItems.keySet()) {
                    Location__c loc = locations.get(locId);

                    List<String> binNames = binsWithMultipleItems.get(locId);
                    binNames.sort();

                    loc.Mixed_Bins_Allowed__c.addError('You can\'t disable mixed bins on location ' + loc.Name + ' because the following bins have multiple items in them: ' + String.join(binNames, ', '));
                }
            }
        }
    }

    private static void validateBinTracked(List<Location__c> locs, Map<Id, Location__c> oldLocs) {
        Set<Id> locsForSkids = new Set<Id>();
        Set<Id> locsForBins = new Set<Id>();
        List<Location__c> locsToCheck = new List<Location__c>();
        for (Location__c loc:locs) {
            if (KSE.isFieldChanging('Bin_Tracked__c', loc, oldLocs) == true) {
                if (loc.Bin_Tracked__c == true) locsForSkids.add(loc.Id);
                else locsForBins.add(loc.Id);   // Should we just check for skids and delete bins instead?
                locsToCheck.add(loc);
            }
        }
        if (locsToCheck.size() == 0) return;

        Set<Id> locsWithSkids = new Set<Id>();
        if (locsForSkids.size() > 0) {
            Set<String> skidTypes = new Set<String>{ SkidService3.SKID_TYPE_LOCATION, SkidService3.SKID_TYPE_ALLOCATED, SkidService3.SKID_TYPE_PLANNED };
            SOQLUtil skidQuery = new SOQLUtil('SKID__c', false, true);
            skidQuery.addFields(new Set<String>{ 'Location__c locId' });
            skidQuery.setWhereClause('Location__c IN :locsForSkids AND Type__c IN :skidTypes GROUP BY Location__c');
            for (AggregateResult ar:Database.query(skidQuery.getQuery())) locsWithSkids.add((Id)ar.get('locId'));
        }

        Set<Id> locsWithBins = new Set<Id>();
        if (locsForBins.size() > 0) {
            SOQLUtil binQuery = new SOQLUtil('Bin__c', true, true);
            binQuery.addFields(new Set<String>{ 'Location__c locId' });
            binQuery.setWhereClause('Location__c IN :locsForBins GROUP BY Location__c');
            for (AggregateResult ar:Database.query(binQuery.getQuery())) locsWithBins.add((Id)ar.get('locId'));
        }

        for (Location__c loc:locsToCheck) {
            if (loc.Bin_Tracked__c == true && locsWithSkids.contains(loc.Id) == true) loc.Bin_Tracked__c.addError(loc.Name + ': You can\'t enable bin tracking because this location has SKIDs associated with it.');
            else if (loc.Bin_Tracked__c == false && locsWithBins.contains(loc.Id) == true) loc.Bin_Tracked__c.addError(loc.Name + ': You can\'t disable bin tracking because this location has bins.');
        }
    }

    public static void beforeInsert() { setFacility(Trigger.new, true); }
    public static void beforeUpdate() { 
        setFacility(Trigger.new, true);
        checkMixedBins((Map<Id, Location__c>)Trigger.newMap, (Map<Id, Location__c>)Trigger.oldMap);
        validateBinTracked(Trigger.new, (Map<Id, Location__c>)Trigger.oldMap);
    }
    public static void beforeDelete() { KSE.blockRecordDeletion(); }
    public static void afterInsert() { }
    public static void afterUpdate() { }
    public static void afterDelete() { }
    public static void afterUndelete() { }
}