src-ken&y/objects/Budget__c.object
<CustomObject>
    <customHelpPage>HelpBudgets</customHelpPage>
    <fields>
        <fullName>Budget_Amount__c</fullName>
        <label>Budget Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Budget_From__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Budget From</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Budget From Company must match Company</errorMessage>
            <filterItems>
                <field>Period__c.Company__c</field>
                <operation>equals</operation>
                <valueField>$Source.Company__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Period__c</referenceTo>
        <relationshipLabel>Budgets (Budget From)</relationshipLabel>
        <relationshipName>Budgets1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Budget_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Budget To</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Budget To Company must match Company</errorMessage>
            <filterItems>
                <field>Period__c.Company__c</field>
                <operation>equals</operation>
                <valueField>$Source.Company__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Period__c</referenceTo>
        <relationshipLabel>Budgets (Budget To)</relationshipLabel>
        <relationshipName>Budgets2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>Budgets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Budget</label>
    <nameField>
        <label>Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Budget_Line1__c.object
<CustomObject>
    <customHelpPage>HelpBudgetLine</customHelpPage>
    <fields>
        <fullName>Budget_Amount__c</fullName>
        <label>Budget Amount</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Budget__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Budget</label>
        <referenceTo>Budget__c</referenceTo>
        <relationshipLabel>Budget Lines</relationshipLabel>
        <relationshipName>Budget_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Budget Lines</relationshipLabel>
        <relationshipName>Budget_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GL_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GL Account</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>GL Account is not enabled for budgeting.</errorMessage>
            <filterItems>
                <field>GL_Account__c.Include_in_Budgets__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>GL_Account__c</referenceTo>
        <relationshipLabel>Budget Lines</relationshipLabel>
        <relationshipName>Budget_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Intercompany__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Intercompany</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Budget Lines (Intercompany)</relationshipLabel>
        <relationshipName>Budget_Details1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Period</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Period Company must match Company</errorMessage>
            <filterItems>
                <field>Period__c.Company__c</field>
                <operation>equals</operation>
                <valueField>$Source.Company__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Period__c</referenceTo>
        <relationshipLabel>Budget Lines</relationshipLabel>
        <relationshipName>Budget_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Budget Line</label>
    <nameField>
        <label>Budget Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Company__c.object
<CustomObject>
    <customHelpPage>HelpCompany</customHelpPage>
    <description>Each Logistics or Financial entity will be represented by a single Company record.  Master data for the Company is recorded here and used throughout the System.</description>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/GL_Account__c.object
<CustomObject>
    <customHelpPage>HelpGLAccount</customHelpPage>
    <description>Table of acceptable General Ledger Numbers or Names with associated Cross Reference Information</description>
    <fields>
        <fullName>Include_in_Budgets__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Include in Budgets</label>
        <type>Checkbox</type>
    </fields>
    <label>GL Account</label>
    <nameField>
        <label>GL Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Period__c.object
<CustomObject>
    <customHelpPage>HelpPeriods</customHelpPage>
    <description>Segment of time that financial entries fall into</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Periods</relationshipLabel>
        <relationshipName>Periods</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Period</label>
    <nameField>
        <label>Period</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Product__c.object
<CustomObject>
    <customHelpPage>HelpProducts</customHelpPage>
    <description>Products are sellable Items with Selling Unit of Measure included</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Segment_Definition__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Defines the GL Segments, their associated objects, and the field on the Accounting Entry</description>
    <label>Accounting Entry Segment Definition</label>
</CustomObject>

src-ken&y/classes/BudgetImportConTest.cls
@isTest
public with sharing class BudgetImportConTest {
    
    public class BudgetImportTestData {
    	public TestFuel fuel = new TestFuel();
    	
    	public Budget__c budget {
    		get{
    			if(budget == null){
    				budget = new Budget__c(Company__c = fuel.company.Id, Budget_From__c = fuel.periodList[0].Id, Budget_To__c = fuel.periodList[fuel.periodList.size() - 1].Id);
    				insert budget;
    			}
    			return budget;
    		}
    		set;
    	}
    	
    	public List<Map<String, String>> budgetLinesToImport {
    		get{
    			if(budgetLinesToImport == null){
    				
    				System.JSONGenerator jsonGen = JSON.createGenerator(false);
    				jsonGen.writeStartArray();
    				
    				for(Period__c period : fuel.periodList){
    					jsonGen.writeStartObject();
    					
    					jsonGen.writeStringField('GL_Account__c', fuel.expenseGL.Name);
    					//jsonGen.writeStringField('Product__c', fuel.product.Name);
    					jsonGen.writeNumberField('Budget_Amount__c', 1);
    					jsonGen.writeStringField('Period__c', period.Name);
    					
    					jsonGen.writeEndObject();
    				}
    				
    				jsonGen.writeEndArray();
    				jsonGen.close();
    				
    				budgetLinesToImport = (List<Map<String, String>>) JSON.deserialize(jsonGen.getAsString(), List<Map<String, String>>.class);
    				
    			}
    			return budgetLinesToImport;
    		}
    		set;
    	}
    	
    }

    static testMethod void testBudgetImportCon(){
    	BudgetImportConTest.BudgetImportTestData biTestFuel = new BudgetImportConTest.BudgetImportTestData();
    	
    	delete [SELECT Id FROM Segment_Definition__c WHERE Name='Intercompany__c'];
    	
    	system.assert(! String.isBlank(BudgetImportCon.segmentsJSON));
    	
    	BudgetImportCon biCon = new BudgetImportCon(new ApexPages.StandardController(new Budget__c()));
    	
    	system.assert(ApexPages.hasMessages());
    	
    	biCon = new BudgetImportCon(new ApexPages.StandardController(biTestFuel.budget));
    	
    	system.assert(biTestFuel.budget.Id != null);
    	
    	JSONResult result = BudgetImportCon.saveBudgetLines(biTestFuel.budget.Id, new List<String>{'GL Account', 'Period'}, biTestFuel.budgetLinesToImport);
    	
    	system.assert(result.success == false);
    	system.assert([SELECT Id FROM Budget_Line1__c WHERE Budget__c = :biTestFuel.budget.Id].size() == 0);
    	
    	biTestFuel.fuel.expenseGL.Include_in_Budgets__c = true;
    	update biTestFuel.fuel.expenseGL;
    	
    	result = BudgetImportCon.saveBudgetLines(biTestFuel.budget.Id, new List<String>{'GL Account', 'Period'}, biTestFuel.budgetLinesToImport);
    	
    	system.assert(result.success == true, result.messages);
    	system.assertEquals(biTestFuel.fuel.periodList.size(), [SELECT Id FROM Budget_Line1__c WHERE Budget__c = :biTestFuel.budget.Id].size());
    }
}