src-ken&y/objects/Budget__c.object
<CustomObject>
    <customHelpPage>HelpBudgets</customHelpPage>
    <label>Budget</label>
    <nameField>
        <label>Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Budget_Line1__c.object
<CustomObject>
    <customHelpPage>HelpBudgetLine</customHelpPage>
    <fields>
        <fullName>Budget__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Budget</label>
        <referenceTo>Budget__c</referenceTo>
        <relationshipLabel>Budget Lines</relationshipLabel>
        <relationshipName>Budget_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Budget Line</label>
    <nameField>
        <label>Budget Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/BudgetDeleteExt.cls
public with sharing class BudgetDeleteExt {
    
    Budget__c bdg;

    private ApexPages.StandardController con;
    public BudgetDeleteExt(ApexPages.StandardController controller) {
        con = controller;
        bdg = (Budget__c)con.getRecord();
    }
     
    public PageReference deletebudget() {
        
        Id budgetId = bdg.Id;  
        SOQLUtil soql    = new SOQLUtil('Budget_Line1__c', true); 
        soql.addFields(new set<string>{'Id'}); 
        soql.setWhereClause('Budget__c = :budgetId');
        List<Budget_Line1__c> deleteBL = Database.query(soql.getQuery()); 
          
        try {
            DML.deleteAsUser(deleteBL);
            DML.deleteAsUser(bdg);
        } 
        catch(Exception e) {
             ApexPages.addMessages(e);
        }
    
        return ApexPages.hasMessages() ? null : con.cancel(); 
    }

    
}