src-ken&y/objects/Budget__c.object
<CustomObject>
    <customHelpPage>HelpBudgets</customHelpPage>
    <fields>
        <fullName>Budget_From__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Budget From</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Budget From Company must match Company</errorMessage>
            <filterItems>
                <field>Period__c.Company__c</field>
                <operation>equals</operation>
                <valueField>$Source.Company__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Period__c</referenceTo>
        <relationshipLabel>Budgets (Budget From)</relationshipLabel>
        <relationshipName>Budgets1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Budget_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Budget To</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Budget To Company must match Company</errorMessage>
            <filterItems>
                <field>Period__c.Company__c</field>
                <operation>equals</operation>
                <valueField>$Source.Company__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Period__c</referenceTo>
        <relationshipLabel>Budgets (Budget To)</relationshipLabel>
        <relationshipName>Budgets2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>Budgets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Budget</label>
    <nameField>
        <label>Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Company__c.object
<CustomObject>
    <customHelpPage>HelpCompany</customHelpPage>
    <description>Each Logistics or Financial entity will be represented by a single Company record.  Master data for the Company is recorded here and used throughout the System.</description>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Period__c.object
<CustomObject>
    <customHelpPage>HelpPeriods</customHelpPage>
    <description>Segment of time that financial entries fall into</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Periods</relationshipLabel>
        <relationshipName>Periods</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Period</label>
    <nameField>
        <label>Period</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/BudgetDeleteExtTest.cls
@isTest
private class BudgetDeleteExtTest {
    //----# Verify the budget and its lines re deleted-------#
    static testMethod void testDeleteBudgetNdLines() {
        TestFuel testData           = new TestFuel();
        List<Period__c> periodList = testData.periodList;
        
        test.startTest();
        
            Budget__c bdjToDelete = new Budget__c(Company__c=TestData.company.Id,
                                          Budget_From__c=periodList[0].Id,Budget_To__c=periodList[1].Id);
            insert bdjToDelete;
            Apexpages.StandardController budgetCon        
                                         = new Apexpages.StandardController(bdjToDelete);
            test.setCurrentPage(page.BudgetDelete);
            BudgetDeleteExt deleteObj = new BudgetDeleteExt(budgetCon); 
            deleteObj.deletebudget();
            
            
            
        test.stopTest();
        
      List<Budget__c> budgets =   [SELECT id,name,Company__c 
                                          FROM Budget__c 
                                          WHERE Id=:bdjToDelete.Id];
                                          
      system.assert(budgets.size()==0, 'Expected the  Budget record to be removed');    
    }
    
    
 }