src-ken&y/objects/Claim__c.object
<CustomObject>
    <customHelpPage>HelpClaims</customHelpPage>
    <description>Tracks the lifecycle of source documents claims that require further review.</description>
    <fields>
        <fullName>Claim_Balance__c</fullName>
        <formula>IF(OR(ISPICKVAL(Settlement_Method__c, &quot;Chargeback&quot;),ISPICKVAL(Settlement_Method__c, &quot;Split&quot;),ISPICKVAL(Status__c, &quot;Closed&quot;),ISPICKVAL(Status__c, &quot;Cancelled&quot;)), 0, Amount__c - Total_Line_Amount__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Claim Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>This will define the from where the claim was created.</description>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Manual</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Invoice Deduction</fullName>
                </value>
                <value>
                    <fullName>General Deduction</fullName>
                </value>
                <value>
                    <fullName>Trade</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Claim Status.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Claim</label>
    <nameField>
        <label>Claim</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Claim_Line__c.object
<CustomObject>
    <customHelpPage>HelpClaims</customHelpPage>
    <description>Provides additional information about the claim and how it should be settled.</description>
    <fields>
        <fullName>Claim__c</fullName>
        <label>Claim</label>
        <referenceTo>Claim__c</referenceTo>
        <relationshipLabel>Claim Lines</relationshipLabel>
        <relationshipName>Claim_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Claim Line</label>
    <nameField>
        <label>Claim Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claim Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/classes/RefundCreditClaimLaunchExt.cls
public with sharing class RefundCreditClaimLaunchExt {
    ApexPages.StandardController stdcon;
    public string theClaimId;
    public string claimName { get; private set; }

    public RefundCreditClaimLaunchExt(ApexPages.StandardController controller){
        stdcon = controller;
        sObject tmpsObj = stdcon.getRecord() ;
        theClaimId = String.valueof((Id) tmpsObj.get('Id'));
    }
    
    // pass the id ( one or more ) as parameter to the navigated Page
    public PageReference navigateToRefundCredit() {        
        boolean isValidClaim = false;
        system.debug(logginglevel.error,'theClaimId'+theClaimId);
        if(stdcon != null && !String.isBlank( theClaimId )){
            isValidClaim = validateTheClaim( theClaimId );
            System.debug(logginglevel.error,'isValidClaim-->'+isValidClaim);
        }

        if( !isValidClaim){
          return null;
        }else{
          PageReference p = Page.RefundCreditManage;
          p.getParameters().put('claimId', theClaimId);
          return p.setRedirect(true);
        }
    }

    // Assumption: parameter not null, and claim exists
    private boolean validateTheClaim( String theClaimId ){
        boolean validFlag = true;
        try{
            system.assert(!String.isBlank( theClaimId ));
            SOQLUtil soql = new SOQLUtil( 'Claim__c', true ); //enforceFLS=true, running in user mode
            soql.addFields(new set<string>{
                'Id','Name','Source__c', 'Claim_Balance__c','Status__c'
            });
            soql.setWhereClause( 'Id = :theClaimId' );
            SOQLUtil.ChildRelationship childRel = new SOQLUtil.ChildRelationship(soql, 'Claim_Lines__r');
            childRel.addFields(new set<string>{
                'Id','Name'
            });
            soql.addChildRelationship(childRel);
            List<Claim__c> claimList = Database.query(soql.getQuery());
            system.debug(logginglevel.error,'claimList-->'+claimList);
            system.assertEquals(claimList.size(), 1, '>>> claimList: ' + claimList);
            claimName = 'Return to ' + claimList[0].Name;

            if(claimList[0].Status__c == 'Closed') {
                validFlag = false;
                ApexPages.addMessage( new ApexPages.Message( ApexPages.severity.ERROR,label.You_can_settle_only_an_open_claim));
            }
            else if( claimList[0].Claim_Balance__c <= 0 ||
               (claimList[0].Claim_Lines__r != null && claimList[0].Claim_Lines__r.size() != 0) ){
                validFlag = false;
                ApexPages.addMessage( new ApexPages.Message( ApexPages.severity.ERROR,label.Refund_Credit_Invalid_Claim));
            }
        }
        catch (Exception ex){
            validFlag = false;
            ApexPages.addMessage( new ApexPages.Message( ApexPages.severity.ERROR, MessageUtil.toFriendlyErrorMessage(ex.getMessage())));
            system.debug(LoggingLevel.Error, 'EXCEPTION: ' + ex.getMessage() + ' ' + ex.getStackTraceString());
        }
        return validFlag;
    }

    public Pagereference returnToClaim() {
        if ( Apexpages.hasMessages(Apexpages.severity.FATAL)|| Apexpages.hasMessages(Apexpages.severity.WARNING) || Apexpages.hasMessages(Apexpages.severity.ERROR)) {
                return null;
        }else{
             return new PageReference( '/' +theClaimId );
        }
    }
}