src-ken&y/objects/Class__c.object
<CustomObject>
    <customHelpPage>HelpClasses</customHelpPage>
    <description>A class can be any code or name that groups or classifies inventory.</description>
    <fields>
        <fullName>Status_1_Name__c</fullName>
        <label>Status 1 Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status_1_Offset_Days__c</fullName>
        <label>Status 1 Offset Days</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status_2_Name__c</fullName>
        <label>Status 2 Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status_2_Offset_Days__c</fullName>
        <label>Status 2 Offset Days</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status_3_Name__c</fullName>
        <label>Status 3 Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status_3_Offset_Days__c</fullName>
        <label>Status 3 Offset Days</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Company__c.object
<CustomObject>
    <customHelpPage>HelpCompany</customHelpPage>
    <description>Each Logistics or Financial entity will be represented by a single Company record.  Master data for the Company is recorded here and used throughout the System.</description>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Item__c.object
<CustomObject>
    <customHelpPage>HelpItems</customHelpPage>
    <description>Item Master object</description>
    <fields>
        <fullName>Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This code is used to group items for control and/or reporting.  Can be used to designate  a group, division, or product line.  Many reports have the option to sort by Class Code.</description>
        <inlineHelpText>Used to group items for control and/or reporting; can be used to designate a group, division, or product line.</inlineHelpText>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company that controls this item</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Lot__c.object
<CustomObject>
    <customHelpPage>HelpLot</customHelpPage>
    <description>Lot information for an Item that is Lot tracked. The Lot contains the Lot attributes and is unique for the Item and Supplier.</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Indicates if this Company produced or purchased this Lot. If Company is set and Supplier is null, this Company produced the Lot. Otherwise, Lot comes from the manufacturing Supplier.</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Lots</relationshipLabel>
        <relationshipName>Lots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <description>Date this Lot of this Product expires.</description>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lot on this Item.</description>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Lots</relationshipLabel>
        <relationshipName>Lots</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lot_Hold__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates that this Lot is on hold. Lots on hold are non-nettable.</description>
        <label>Lot Hold</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Shelf_Life_Status__c</fullName>
        <label>Shelf Life Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Saleable</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Lot</label>
    <nameField>
        <label>Lot</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/LotUpdateStatusBatch.cls
public with sharing class LotUpdateStatusBatch implements Database.batchable<sObject>,Database.stateful, Process.Runnable {
  
    public string query;
    public Id companyId;
    public List<Notify.Message> messages = new List<Notify.Message>();
    
    public void runBatch( id CompanyId ) {      // Process.Runnable implementation 
        LotUpdateStatusBatch obj=new LotUpdateStatusBatch();
        obj.companyId = CompanyId;
        Id jobId=Database.executebatch(obj, 2000);
    }
    
    public LotUpdateStatusBatch(){

        query='select ID, Expiration_Date__c, Item__r.Class__c, Lot_Hold__c, Shelf_Life_Status__c '+
              'from Lot__c '+
              'where Company__c =: CompanyId and '+
              'Expiration_Date__c != null '+
              'and Item__r.Class__c != null '+
              'and Lot_Hold__c = false';      
    }
    
    public Database.QueryLocator start(Database.BatchableContext BC){         
        return Database.getQueryLocator(query);
    }
    
     public void execute(Database.BatchableContext info, List<Lot__c> scope){
     
         Date todaysdate;
         Set<ID> classSet = new Set<ID>();
         List<Lot__c> lotList = new List<Lot__c>();
         
         todaysdate = System.today();
         
         for (Lot__c lotObj : scope) {
             classSet.add(lotObj.Item__r.Class__c);
         }
        
        Map<ID, Class__c> classMap = new Map<ID, Class__c> ([select ID,
                                                             Status_1_Name__c, Status_1_Offset_Days__c,
                                                             Status_2_Name__c, Status_2_Offset_Days__c,
                                                             Status_3_Name__c, Status_3_Offset_Days__c
                                                             from Class__c
                                                             where Status_1_Offset_Days__c > 0 and
                                                             Status_2_Offset_Days__c != 0 and
                                                             Status_3_Offset_Days__c != 0 and
                                                             ID in: classSet]);
                                                             
        for (Lot__c lotObj : scope) {
            if (classMap.containsKey(lotObj.Item__r.Class__c)) {
                if (lotObj.Expiration_Date__c - (long)classMap.get(lotObj.Item__r.Class__c).Status_3_Offset_Days__c <= todaysdate) {
                    if (lotObj.Shelf_Life_Status__c != classMap.get(lotObj.Item__r.Class__c).Status_3_Name__c) {
                        lotObj.Shelf_Life_Status__c = classMap.get(lotObj.Item__r.Class__c).Status_3_Name__c;
                        lotObj.Lot_Hold__c = true;
                        lotList.add(lotObj);
                    }
                }
                else if (lotObj.Expiration_Date__c - (long)classMap.get(lotObj.Item__r.Class__c).Status_2_Offset_Days__c <= todaysdate) {
                         if (lotObj.Shelf_Life_Status__c != classMap.get(lotObj.Item__r.Class__c).Status_2_Name__c) {
                             lotObj.Shelf_Life_Status__c = classMap.get(lotObj.Item__r.Class__c).Status_2_Name__c;
                             lotList.add(lotObj);
                         }
                     }
                     else if (lotObj.Expiration_Date__c - (long)classMap.get(lotObj.Item__r.Class__c).Status_1_Offset_Days__c <= todaysdate) {
                              if (lotObj.Shelf_Life_Status__c != classMap.get(lotObj.Item__r.Class__c).Status_1_Name__c) {
                                  lotObj.Shelf_Life_Status__c = classMap.get(lotObj.Item__r.Class__c).Status_1_Name__c;                          
                                  lotList.add(lotObj);
                              }
                         }
                         else if (lotObj.Expiration_Date__c - (long)classMap.get(lotObj.Item__r.Class__c).Status_1_Offset_Days__c > todaysdate) {
                                  if (lotObj.Shelf_Life_Status__c != null) {
                                      lotObj.Shelf_Life_Status__c = null;                          
                                      lotList.add(lotObj);
                              }
                         }
            }             
        }
        
        update(lotList);
        
    }
    
    public void finish(Database.BatchableContext info){
        BatchToChatter.processBatchInformation(info.getJobId(), this, messages);
        Notify.sendEmailBatchFinish( null, messages, info);        
        MasterControlProgram.finishedBatch( this ); 

    }
}