src-ken&y/objects/Class__c.object
<CustomObject>
    <customHelpPage>HelpClasses</customHelpPage>
    <description>A class can be any code or name that groups or classifies inventory.</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of this class</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Company__c.object
<CustomObject>
    <customHelpPage>HelpCompany</customHelpPage>
    <description>Each Logistics or Financial entity will be represented by a single Company record.  Master data for the Company is recorded here and used throughout the System.</description>
    <fields>
        <fullName>Use_Quantity_on_Hand_as_Supply_in_MRP__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Use Quantity on Hand as Supply in MRP</description>
        <inlineHelpText>Use Quantity on Hand as Supply in MRP: ignore Safety Stock and Negative Quantity on Hand if checkbox is not selected.</inlineHelpText>
        <label>Quantity on Hand as Supply</label>
        <type>Checkbox</type>
    </fields>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Facility__c.object
<CustomObject>
    <customHelpPage>HelpFacilites</customHelpPage>
    <description>Warehouse or building</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Facilities</relationshipLabel>
        <relationshipName>Facilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Facility&apos;s description</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Use_Quantity_on_Hand_as_Supply_in_MRP__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Use Quantity on Hand as Supply in MRP</description>
        <inlineHelpText>If not selected, MRP ignores  Safety Stock and Negative Quantity on Hand.</inlineHelpText>
        <label>Quantity on Hand as Supply</label>
        <type>Checkbox</type>
    </fields>
    <label>Facility</label>
    <nameField>
        <label>Facility</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Item__c.object
<CustomObject>
    <customHelpPage>HelpItems</customHelpPage>
    <description>Item Master object</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Active Item if checked; Used to phase out a item. If item is inactive, a P.O. or W.O. can not be placed against item but the QOH can be used.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This code is used to group items for control and/or reporting.  Can be used to designate  a group, division, or product line.  Many reports have the option to sort by Class Code.</description>
        <inlineHelpText>Used to group items for control and/or reporting; can be used to designate a group, division, or product line.</inlineHelpText>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company that controls this item</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Item description can be up to 255 characters; use extended description field if needed</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EOQ__c</fullName>
        <description>Economic Order Quantity: Optimum quantity to make or buy at one time : EOQ is determined by opitmizing the cost incurred to place each order for this item with the carrying cost of holding these items in stock.</description>
        <inlineHelpText>Optimum quantity to make or buy at one time; EOQ is determined by optimizing the cost incurred to place each order with the carrying cost of holding these items in stock.</inlineHelpText>
        <label>EOQ</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Auto-generated by MRP as first step in MRP run. Buy and outsourced items are level 0; all make items depend on highest BOM assembly level.</description>
        <inlineHelpText>Auto-generated by MRP as first step in MRP run. Items that are purchased (Buy) and outsourced are level 0.</inlineHelpText>
        <label>Level</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ordering_Multiple__c</fullName>
        <description>Ordering multiple is used by MRP in planning orders; for example, if multiple is 25 and the actual demand is 70, then the system will suggest an order of 75</description>
        <inlineHelpText>Used by MRP to plan orders. For example, if the order multiple is 25 and the actual demand is 70, then MRP will suggest an order of 75.</inlineHelpText>
        <label>Ordering Multiple</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Safety_Stock__c</fullName>
        <description>The amount of stock over and above what is forecast to be required so as to provide stock availaility for customer service or other miscellaneous uses not forecast in the Master Plan to the MRP i.e, Buffer stock.</description>
        <inlineHelpText>The amount of stock over and above the forecast that provides a buffer for unanticipated needs.</inlineHelpText>
        <label>Safety Stock</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Shrinkage__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The % of an item expected to be unusable or defective. (MRP inflates planned orders to cover shrinkage.) For example, 10 % shrinkage would be entered as 10</description>
        <inlineHelpText>Loss of inventory due to defective or unusable material; expressed as a percentage. MRP inflates the planned orders to cover shrinkage.</inlineHelpText>
        <label>Shrinkage</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <inlineHelpText>The source of the item. Click &quot;Help for this Page&quot; for information about the different item sources in Kenandy.</inlineHelpText>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Purchased</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Manufactured</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous</fullName>
                </value>
                <value>
                    <fullName>Phantom</fullName>
                </value>
                <value>
                    <fullName>Expense</fullName>
                </value>
                <value>
                    <fullName>Kit</fullName>
                </value>
                <value>
                    <fullName>Outside Processing</fullName>
                </value>
                <value>
                    <fullName>One Time Charge</fullName>
                </value>
                <value>
                    <fullName>Build To Order</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Use_Lot_Sizing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used by MRP; if checked (YES) then safety stock, EQO, Order Multiple and shrinkage factor are used when MRP plans orders for this item, if unchecked (NO) then lot for lot technique used for this item.</description>
        <inlineHelpText>Used to inflate the planned requirement to protect against unexpected shortages. If this field is selected, but Safety stock, Shrinkage, EOQ, and the Order Multiple are all &quot;0&quot;, it is equivalent to no lot sizing. No checkmark = lot-for-lot technique.</inlineHelpText>
        <label>Use Lot Sizing</label>
        <type>Checkbox</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/MRP__c.object
<CustomObject>
    <customHelpPage>HelpMRP</customHelpPage>
    <description>MRP supply/demand/planned information</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>MRPs</relationshipLabel>
        <relationshipName>MRPs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Facility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Facility of this order/supply</description>
        <inlineHelpText>MRP can be run at the company or facility level.  If run at the facility level, MRP only looks at the supply and demand for the selected facility.</inlineHelpText>
        <label>Facility</label>
        <referenceTo>Facility__c</referenceTo>
        <relationshipLabel>MRPs</relationshipLabel>
        <relationshipName>MRPs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Demand__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this a demand record or supply</description>
        <inlineHelpText>Indicates this is demand (not supply).</inlineHelpText>
        <label>Is Demand</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Item</description>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>MRPs</relationshipLabel>
        <relationshipName>MRPs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <formula>Item__r.Level__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>MRP uses the BOM on each item spec to calculate the net-material requirements for every component item and sub-assembly. The level indicates the item level within the BOM. If the item appears on multiple BOMs, the level indicates its lowest position.</inlineHelpText>
        <label>Level</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MRP_Run__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to MRP_Run</description>
        <inlineHelpText>Lookup to MRP_Run</inlineHelpText>
        <label>MRP Run</label>
        <referenceTo>MRP_Run__c</referenceTo>
        <relationshipLabel>MRPs</relationshipLabel>
        <relationshipName>MRPs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Modified_Quantity__c</fullName>
        <description>Modified Quantity</description>
        <inlineHelpText>The balance remaining on a planned order after you create a work order or purchase order.</inlineHelpText>
        <label>Modified Quantity</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>Quantity</description>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Required_Date__c</fullName>
        <description>Required Date</description>
        <label>Required Date</label>
        <type>Date</type>
    </fields>
    <label>MRP</label>
    <nameField>
        <displayFormat>MRP-{0000000000}</displayFormat>
        <label>MRP</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MRPs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/MRP_Run__c.object
<CustomObject>
    <customHelpPage>HelpMRPRun</customHelpPage>
    <description>MRP Runtime Run ID and run time parameters</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Company</description>
        <inlineHelpText>Lookup to Company</inlineHelpText>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>MRP Runs</relationshipLabel>
        <relationshipName>MRP_Runs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Facility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Facility</description>
        <inlineHelpText>Lookup to Facility</inlineHelpText>
        <label>Facility</label>
        <referenceTo>Facility__c</referenceTo>
        <relationshipLabel>MRP Runs</relationshipLabel>
        <relationshipName>MRP_Runs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>MRP Run</label>
    <nameField>
        <displayFormat>MRP_Run - {0000000000}</displayFormat>
        <label>MRP_Run</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MRP Runs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/GenerateMRPExtTest.cls
/**
 * 
 */
@isTest
private class GenerateMRPExtTest {

    static testMethod void batchTest() {
        
      TestData data=new TestData();
      data.company.Use_Quantity_on_Hand_as_Supply_in_MRP__c = true;
      update data.company;
      
      List<Item__c> itemList=new List<Item__c>(); 

      for(integer i=1;i<200;i++){
            Item__c item = new Item__c();
            item.name='TestLevel'+i;
            item.Description__c='TestLevel'+i;
            item.Source__c=Label.Source_field_of_ItemP;
            item.company__c = data.company.Id;
            item.Use_Lot_Sizing__c=true;
            item.Ordering_Multiple__c=10;
            item.Shrinkage__c=2;
            item.EOQ__c=10;
            item.Active__c = true;
            item.Class__c=data.clsObj.Id;

            itemList.add(item);
      }
      insert itemList;

      Test.startTest();
      Apexpages.Standardcontroller stdcon = new Apexpages.Standardcontroller(data.company);
      GenerateMRPExt utilObj=new GenerateMRPExt(stdcon);
      utilObj.companyId=data.company.Id;
      utilObj.generateItemLevel();

      utilObj.IncrementCounter() ; // void
      system.assert( utilObj.getApexJobList() != null ) ; // could be an empty list
      
      MRP_Run__c mrpRun = new MRP_Run__c();
      mrpRun.Company__c = data.company.id;
      mrpRun.Facility__c = null;

      insert mrpRun;
        
      list<MRP__c> insertList=new list<MRP__c>();
      for(integer i=1;i<11;i++){
            data.itemList[i-1].use_lot_sizing__c = true;
            data.itemList[i-1].safety_stock__c = 1000;
            data.itemList[i-1].level__c = 1;
            MRP__c mrpObj=new MRP__c();
            mrpObj.Company__c=data.company.Id;
            mrpObj.Item__c=data.itemList[i-1].ID;
            mrpObj.Quantity__c=50;
            mrpObj.Modified_Quantity__c=50;
            mrpObj.Required_Date__c=system.today();
            if (i < 5) mrpObj.Is_Demand__c=true;
            else mrpObj.Is_Demand__c=false;
            mrpObj.MRP_Run__c = mrpRun.ID;
            insertList.add(mrpObj);
        }
      update data.itemlist;
       
      GenerateMRPExt utilObj2 = new GenerateMRPExt(stdcon);
      utilObj2.companyId=data.company.Id;
      utilObj2.generatePlan();
      
      Test.stopTest();
      System.assert( ApexPages.hasMessages() );
    }

}