src-ken&y/objects/Company__c.object
<CustomObject>
    <customHelpPage>HelpCompany</customHelpPage>
    <description>Each Logistics or Financial entity will be represented by a single Company record.  Master data for the Company is recorded here and used throughout the System.</description>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Item__c.object
<CustomObject>
    <customHelpPage>HelpItems</customHelpPage>
    <description>Item Master object</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company that controls this item</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Lot__c.object
<CustomObject>
    <customHelpPage>HelpLot</customHelpPage>
    <description>Lot information for an Item that is Lot tracked. The Lot contains the Lot attributes and is unique for the Item and Supplier.</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Indicates if this Company produced or purchased this Lot. If Company is set and Supplier is null, this Company produced the Lot. Otherwise, Lot comes from the manufacturing Supplier.</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Lots</relationshipLabel>
        <relationshipName>Lots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <description>Date this Lot of this Product expires.</description>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lot on this Item.</description>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Lots</relationshipLabel>
        <relationshipName>Lots</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lot_Hold__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates that this Lot is on hold. Lots on hold are non-nettable.</description>
        <label>Lot Hold</label>
        <type>Checkbox</type>
    </fields>
    <label>Lot</label>
    <nameField>
        <label>Lot</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/LotUpdateStatusBatchTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 */
@isTest
private class LotUpdateStatusBatchTest {

    static testMethod void batchTest() {
        TestData data = new TestData();
        
        data.clsObj.Status_1_Offset_Days__c = 10;
        data.clsObj.Status_3_Offset_Days__c = 35;
        update data.clsObj;
        
        Lot__c lot = new Lot__c( Name = '1234' , Item__c = data.itemList[0].id ,Company__c =  data.company.id, Expiration_Date__c = system.today()+30 );
        insert lot;
        
        test.startTest();
        
        LotUpdateStatusBatch obj = new LotUpdateStatusBatch();
        obj.CompanyID = data.company.ID;
        obj.runBatch(data.company.id);
        
        test.stopTest();
        
        lot = [ select id, lot_hold__c from lot__c where id=:lot.id];
        system.assertEquals(lot.lot_hold__c,true);
    }
}