src-ken&y/objects/Company__c.object
<CustomObject>
    <customHelpPage>HelpCompany</customHelpPage>
    <description>Each Logistics or Financial entity will be represented by a single Company record.  Master data for the Company is recorded here and used throughout the System.</description>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Order_Forecast__c.object
<CustomObject>
    <customHelpPage>HelpOrderForecasts</customHelpPage>
    <description>Order Forecast for MRP</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Order Forecasts</relationshipLabel>
        <relationshipName>Order_Forecasts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order Forecast</label>
    <nameField>
        <label>Order Forecast</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Forecasts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/classes/OrderForecastNewExt.cls
public with sharing class OrderForecastNewExt {

    // TODO could use the controller.getRecord() instead of creating a new object in this class... 
    
    public OrderForecastNewExt(ApexPages.StandardController controller) {
        newObj = new Order_Forecast__c();
        newObj.Company__c = CompanyService.getDefaultCompanyId();
    }
    
    public void save(){
        try {
            DML.insertAsUser( new list<sobject>{newObj } ); 
        } 
        catch ( Exception e ) {
            Apexpages.addMessages(e);
        }
        return;
    }
    
    public Order_Forecast__c newObj {get;set;}
    public String getOrderForecastId(){
        return (String)newObj.Id;
    }
   
}