src-ken&y/objects/Company__c.object
<CustomObject>
    <customHelpPage>HelpCompany</customHelpPage>
    <description>Each Logistics or Financial entity will be represented by a single Company record.  Master data for the Company is recorded here and used throughout the System.</description>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Component__c.object
<CustomObject>
    <customHelpPage>HelpItemSpecifications</customHelpPage>
    <description>Product structure details</description>
    <fields>
        <fullName>Assembly_Item_Specification__c</fullName>
        <description>Assembly Item Specification</description>
        <label>Assembly Item Specification</label>
        <referenceTo>Item_Specification__c</referenceTo>
        <relationshipLabel>Components</relationshipLabel>
        <relationshipName>Components</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company this Component belongs to</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Components</relationshipLabel>
        <relationshipName>Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Component_Item__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Component Item</description>
        <label>Component Item</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 OR 2)</booleanFilter>
            <errorMessage>Component Item Company does not match Component Company.</errorMessage>
            <filterItems>
                <field>Item__c.Company__c</field>
                <operation>equals</operation>
                <valueField>$Source.Company__c</valueField>
            </filterItems>
            <filterItems>
                <field>Item__c.Company__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Components (Component Item)</relationshipLabel>
        <relationshipName>Components</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Routing__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Routing</description>
        <inlineHelpText>Lookup to Routing</inlineHelpText>
        <label>Routing</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Routing Assembly must match Component Assembly</errorMessage>
            <filterItems>
                <field>Routing__c.Assembly_Item_Specification__c</field>
                <operation>equals</operation>
                <valueField>$Source.Assembly_Item_Specification__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Routing__c</referenceTo>
        <relationshipLabel>Components</relationshipLabel>
        <relationshipName>Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Specifies whether the component is to be kitted, backflushed, or is a by-product of previously manufactured finished goods. To account for a by-product component being used in this assembly,  specify the Quantity Per Assembly as a negative amount.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Kit</fullName>
                </value>
                <value>
                    <fullName>Backflush</fullName>
                </value>
                <value>
                    <fullName>By-product</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Component</label>
    <nameField>
        <label>Component</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Facility__c.object
<CustomObject>
    <customHelpPage>HelpFacilites</customHelpPage>
    <description>Warehouse or building</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Facilities</relationshipLabel>
        <relationshipName>Facilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Facility</label>
    <nameField>
        <label>Facility</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Item__c.object
<CustomObject>
    <customHelpPage>HelpItems</customHelpPage>
    <description>Item Master object</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company that controls this item</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Packaging_UOM__c</fullName>
        <description>Specify multiple Packaging UOM&apos;s for the Item. Limit 1 Packaging UOM per Packaging class Level</description>
        <inlineHelpText>Specify multiple Packaging UOM&apos;s for the Item. Limit 1 Packaging UOM per Packaging class Level</inlineHelpText>
        <label>Packaging UOM</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stocking_UOM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stocking Unit of Measure.  Table of acceptable UOM applies. If Purchasing UOM is not = to Stocking UOM  then conversion factor is used to convert purchased quantities to stocking quantities when purchased items are received into Inventory: Quantity from PO x conversion = Stock Quantity</description>
        <inlineHelpText>You can convert item quantities from one unit of measure to another. For example, if you purchase in dozens (DZ) but stock in eaches (EA) you can indicate the UOM information on the Item detail page and Kenandy will do the conversion for you.</inlineHelpText>
        <label>Stocking UOM</label>
        <referenceTo>UOM__c</referenceTo>
        <relationshipLabel>Items (Stocking UOM)</relationshipLabel>
        <relationshipName>Item_Stocking_UOM</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Item_Specification__c.object
<CustomObject>
    <customHelpPage>HelpItemSpecifications</customHelpPage>
    <description>Item Specifications and Component Header</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company that this Item Specification belongs to</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Item Specfications</relationshipLabel>
        <relationshipName>Item_Specfications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Costing__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Defines this Item Specification as a Costing type specification</description>
        <inlineHelpText>A checkmark indicates that the specification is included in the costing rollup process. Costing specifications (BOMs) are included in the assembly cost rollup process, but are ignored by MRP.</inlineHelpText>
        <label>Costing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Default_Work_Order_Packaging_UOM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Default Work Order Packaging UOM</label>
        <referenceTo>UOM__c</referenceTo>
        <relationshipLabel>Item Specifications (Default Work Order Packaging UOM)</relationshipLabel>
        <relationshipName>Item_Specifications1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Facility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The facility for which the item specification applies.</description>
        <inlineHelpText>BOMs can be maintained at the company or facility level. If specified, this BOM is used by the specified facility.</inlineHelpText>
        <label>Facility</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Facility Company must match Item Specification Company</errorMessage>
            <filterItems>
                <field>Facility__c.Company__c</field>
                <operation>equals</operation>
                <valueField>$Source.Company__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Facility__c</referenceTo>
        <relationshipLabel>Item Specifications</relationshipLabel>
        <relationshipName>Item_Specifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Item</description>
        <inlineHelpText>Displays the list of available items.</inlineHelpText>
        <label>Item</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <filterItems>
                <field>Item__c.Non_Inventory__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>Item__c.Company__c</field>
                <operation>equals</operation>
                <valueField>$Source.Company__c</valueField>
            </filterItems>
            <filterItems>
                <field>Item__c.Company__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Item Specifications</relationshipLabel>
        <relationshipName>Item_Specifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Packaging_UOM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Specification UOM</label>
        <referenceTo>UOM__c</referenceTo>
        <relationshipLabel>Item Specifications</relationshipLabel>
        <relationshipName>Item_Specifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Production__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Defines this Item Specification as a Production type specification</description>
        <inlineHelpText>A check mark indicates that this BOM is used in production. Production BOMs are included in the MRP planning process and in work orders.</inlineHelpText>
        <label>Production</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Revision__c</fullName>
        <description>Item Revision</description>
        <inlineHelpText>The revision code for the selected item.</inlineHelpText>
        <label>Revision</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date2__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>DEPRECATED</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Item Specification Type</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Assembly</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Repair</fullName>
                </value>
                <value>
                    <fullName>Template</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Item Specification</label>
    <nameField>
        <label>Item Specification</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Specifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Routing__c.object
<CustomObject>
    <customHelpPage>HelpWorkOrder</customHelpPage>
    <description>Routing Detail object:  contains the detailed operations required to make an Assembly</description>
    <fields>
        <fullName>Assembly_Item_Specification__c</fullName>
        <description>Routing for this assembly</description>
        <inlineHelpText>Routing for this assembly</inlineHelpText>
        <label>Assembly Item Specification</label>
        <referenceTo>Item_Specification__c</referenceTo>
        <relationshipLabel>Routings</relationshipLabel>
        <relationshipName>Routings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company this routing belongs to</description>
        <inlineHelpText>Company this routing belongs to. After a routing has been created, you cannot change the company.</inlineHelpText>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Routings</relationshipLabel>
        <relationshipName>Routings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Facility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Facility</description>
        <inlineHelpText>Lookup to Facility</inlineHelpText>
        <label>Facility</label>
        <referenceTo>Facility__c</referenceTo>
        <relationshipLabel>Routings</relationshipLabel>
        <relationshipName>Routings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Routing</label>
    <nameField>
        <label>Routing</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/classes/ItemSpecificationNewTest.cls
@isTest
private class ItemSpecificationNewTest {
	private static testMethod void nameError() {
		ApexPages.StandardController con = new ApexPages.StandardController(new Item_Specification__c());
		ItemSpecificationNewExt ext = new ItemSpecificationNewExt(con);
		Item_Specification__c spec = (Item_Specification__c)con.getRecord();

		spec.Type__c = 'Template';
		ext.save();

		System.assert(ApexPages.hasMessages(ApexPages.Severity.FATAL));
	}

	private static testMethod void successNew() {
		TestFuel fuel = new TestFuel();
		ApexPages.StandardController con = new ApexPages.StandardController(new Item_Specification__c());
		ItemSpecificationNewExt ext = new ItemSpecificationNewExt(con);
		Item_Specification__c spec = (Item_Specification__c)con.getRecord();

		spec.Company__c = fuel.company.Id;
		spec.Facility__c = fuel.facility2.Id;
		spec.Item__c = fuel.itemList[2].Id;
		spec.Revision__c = 'R1';
		spec.Start_Date2__c = System.now().addDays(-1);
		spec.Costing__c = true;
		spec.Production__c = true;
		spec.Type__c = 'Assembly';
		ext.save();
		System.assert(!ApexPages.hasMessages(),ApexPages.getMessages());

		List<Item_Specification__c> specs = [SELECT Id FROM Item_Specification__c WHERE Item__c = :fuel.itemList[2].Id];
		System.assert(specs.size() == 1);
	}

	private static testMethod void successClone() {
		TestFuel fuel = new TestFuel();
		Item_Specification__c spec = fuel.itemSpec;
		List<Routing__c> routings = fuel.routings;
		ApexPages.StandardController con = new ApexPages.StandardController(spec);
		ItemSpecificationNewExt ext = new ItemSpecificationNewExt(con);
		spec = (Item_Specification__c)con.getRecord();

		spec.Item__c = fuel.itemList[6].Id;
		ext.save();
		System.assert(!ApexPages.hasMessages(),ApexPages.getMessages());


		List<Item_Specification__c> specs = [SELECT Id,(SELECT Id FROM Routings__r),(SELECT Id FROM Components__r) FROM Item_Specification__c WHERE Item__c = :fuel.itemList[6].Id];
		System.assert(specs.size() == 1,specs);
		System.assert(specs[0].Routings__r.size() == fuel.routings.size(),specs[0].Routings__r);
		System.assert(specs[0].Components__r.size() == fuel.components.size(),specs[0].Components__r);
	}

//	private static testMethod void failureNew() {
//		TestFuel fuel = new TestFuel();
//		ApexPages.StandardController con = new ApexPages.StandardController(new Item_Specification__c());
//		ItemSpecificationNewExt ext = new ItemSpecificationNewExt(con);
//		Item_Specification__c spec = (Item_Specification__c)con.getRecord();
//
//		spec.Company__c = fuel.company.Id;
//		spec.Facility__c = fuel.facility2.Id;
//		spec.Item__c = fuel.itemList[2].Id;
//		spec.Revision__c = 'R1';
//		spec.Start_Date__c = System.today() - 1;
//		spec.Costing__c = true;
//		spec.Production__c = true;
//		spec.Type__c = 'Assembly';
//		spec.Packaging_UOM__c = fuel.uomList[0].Id;
//		spec.Default_Work_Order_Packaging_UOM__c = fuel.uomList[8].Id;
//		ext.save();
//		System.assert(ApexPages.hasMessages(),'Expected create failure with invalid packaging uom for item master');
//		system.assert(String.valueOf(ApexPages.getMessages()).contains(Label.Packaging_UOM_not_configured_for_the_Item), ApexPages.getMessages());
//
//		spec.Company__c = fuel.company.Id;
//		spec.Facility__c = fuel.facility2.Id;
//		spec.Item__c = fuel.itemList[2].Id;
//		spec.Revision__c = 'R1';
//		spec.Start_Date__c = System.today() - 1;
//		spec.Costing__c = true;
//		spec.Production__c = true;
//		spec.Type__c = 'Assembly';
//		spec.Packaging_UOM__c = fuel.uomList[8].Id;
//		spec.Default_Work_Order_Packaging_UOM__c = fuel.uomList[0].Id;
//		ext.save();
//		System.assert(ApexPages.hasMessages(),'Expected create failure with invalid packaging uom for item master');
//		system.assert(String.valueOf(ApexPages.getMessages()).contains(Label.Packaging_UOM_not_configured_for_the_Item), ApexPages.getMessages());
//	}
//
//	private static testMethod void failureUpdate() {
//		TestFuel fuel = new TestFuel();
//		ApexPages.StandardController con = new ApexPages.StandardController(new Item_Specification__c());
//		ItemSpecificationNewExt ext = new ItemSpecificationNewExt(con);
//		Item_Specification__c spec = (Item_Specification__c)con.getRecord();
//
//		spec.Company__c = fuel.company.Id;
//		spec.Facility__c = fuel.facility2.Id;
//		spec.Item__c = fuel.itemList[2].Id;
//		spec.Revision__c = 'R1';
//		spec.Start_Date__c = System.today() - 1;
//		spec.Costing__c = true;
//		spec.Production__c = true;
//		spec.Type__c = 'Assembly';
//		spec.Packaging_UOM__c = fuel.itemList[2].Stocking_UOM__c;
//		spec.Default_Work_Order_Packaging_UOM__c = fuel.itemList[2].Stocking_UOM__c;
//		ext.save();
//		System.assert(!ApexPages.hasMessages(), ApexPages.getMessages());
//
//		SOQLUtil util = new SOQLUtil('Item_Specification__c');
//		util.addAllCustomFields();
//		util.setLimit(1);
//		util.setOrderByClause('CreatedDate DESC');
//		List<Item_Specification__c> itemSpecs = Database.query(util.getQuery());
//
//		System.assert(itemSpecs.size() > 0);
//		con = new ApexPages.StandardController(itemSpecs[0]);
//		ext = new ItemSpecificationNewExt(con);
//		spec = (Item_Specification__c)con.getRecord();
//		spec.Packaging_UOM__c = fuel.uomList[8].Id;
//		spec.Default_Work_Order_Packaging_UOM__c = fuel.uomList[0].Id;
//		ext.save();
//		System.assert(ApexPages.hasMessages(),'Expected create failure with invalid packaging uom for item master');
//		system.assert(String.valueOf(ApexPages.getMessages()).contains(Label.Packaging_UOM_not_configured_for_the_Item), ApexPages.getMessages());
//	}

}