src-ken&y/objects/Company__c.object
<CustomObject>
    <customHelpPage>HelpCompany</customHelpPage>
    <description>Each Logistics or Financial entity will be represented by a single Company record.  Master data for the Company is recorded here and used throughout the System.</description>
    <fields>
        <fullName>A_Days__c</fullName>
        <description>The number of days between cycle counts for A parts</description>
        <inlineHelpText>The number of days between cycle counts for A parts.</inlineHelpText>
        <label>A Days</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to account for address</description>
        <label>Address</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Companies</relationshipLabel>
        <relationshipName>Companies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>B_Days__c</fullName>
        <description>The number of days between cycle counts for B parts</description>
        <inlineHelpText>The number of days between cycle counts for B parts.</inlineHelpText>
        <label>B Days</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>C_Days__c</fullName>
        <description>The number of days between cycle counts for C parts</description>
        <inlineHelpText>The number of days between cycle counts for C parts.</inlineHelpText>
        <label>C Days</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Comp_Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Companies</relationshipLabel>
        <relationshipName>Companies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Consol_Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Consolidation Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Companies (Consolidation Currency)</relationshipLabel>
        <relationshipName>Consol_Currency</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Default_Transaction_Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Default Transaction Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Companies (Default Transaction Currency)</relationshipLabel>
        <relationshipName>Default_Transaction_Currency</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stat_Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Statutory Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Companies (Statutory Currency)</relationshipLabel>
        <relationshipName>Stat_Currency</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subs_Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subsidiary Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Companies (Subsidiary Currency)</relationshipLabel>
        <relationshipName>Subs_Currency</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Customer__c.object
<CustomObject>
    <customHelpPage>HelpCustomers</customHelpPage>
    <description>Information that relates a Customer business to the manufacturing company (Company) and describes the business agreement between the two entities.</description>
    <fields>
        <fullName>Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customers</relationshipLabel>
        <relationshipName>Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The company that originates and owns the customer relationship</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Customers</relationshipLabel>
        <relationshipName>Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Credit_Limit__c</fullName>
        <description>Credit limit you set for the top parent customer; if the field is null, there is no limit</description>
        <inlineHelpText>Credit limit  set for the top parent customer. If a value is not specified, there is no limit.</inlineHelpText>
        <label>Credit Limit</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payment_Term__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Payment terms for this business partner</description>
        <label>Payment Terms</label>
        <referenceTo>Payment_Term__c</referenceTo>
        <relationshipLabel>Customers</relationshipLabel>
        <relationshipName>Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of this customer: Approved,Under Consideration,Pending Approval,Not Approved,Inactive</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer</label>
    <nameField>
        <label>Customer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Payment_Term__c.object
<CustomObject>
    <customHelpPage>HelpPaymentTerms</customHelpPage>
    <description>Payment Terms</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of the payment terms</description>
        <label>Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Discount_Days__c</fullName>
        <description>Number of days discount applies</description>
        <inlineHelpText>The number of days after the invoice date within which the invoice must be paid to receive the discount.</inlineHelpText>
        <label>Discount Days</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Discount_Percent__c</fullName>
        <description>The discount that can be taken if invoice is paid within the discount days</description>
        <inlineHelpText>The discount given if the invoice is paid within the specified discount days.</inlineHelpText>
        <label>Discount Percent</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Due_Days__c</fullName>
        <description>Number of days from delivery of goods or services until the payment is due</description>
        <inlineHelpText>Number of days from delivery of goods or services until the payment is due.</inlineHelpText>
        <label>Due Days</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Due Days</fullName>
                    <default>true</default>
                    <label>Due Days</label>
                </value>
                <value>
                    <fullName>Due Day Of Month</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment Terms</label>
    <nameField>
        <label>Payment Term</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Supplier__c.object
<CustomObject>
    <customHelpPage>HelpSuppliers</customHelpPage>
    <description>Supplier object</description>
    <fields>
        <fullName>Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookupt to Account</description>
        <label>Address</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Suppliers</relationshipLabel>
        <relationshipName>Suppliers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Suppliers</relationshipLabel>
        <relationshipName>Suppliers1_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Term__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Term</label>
        <referenceTo>Payment_Term__c</referenceTo>
        <relationshipLabel>Suppliers</relationshipLabel>
        <relationshipName>Suppliers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Supplier Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tax_ID__c</fullName>
        <description>Tax identification number for the supplier</description>
        <inlineHelpText>Tax identification number for the supplier</inlineHelpText>
        <label>Tax Identification</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>The type of supplier record.</description>
        <inlineHelpText>Type of supplier record. Options include: Purchasing and Remit-To.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Parent</fullName>
                </value>
                <value>
                    <fullName>Purchasing</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Remit-To</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Supplier</label>
    <nameField>
        <label>Supplier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <recordTypes>
        <fullName>Remit_To</fullName>
        <active>true</active>
        <description>Supplier that receives payments</description>
        <label>Remit To</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/DynatreeTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 */
@isTest
private class DynatreeTest {

	class TestData {
		public Payment_Term__c terms = new Payment_Term__c(); {
	        terms.name = '10% Net 30'; 
	        terms.Description__c = 'Ten Percent Net 30 Days';
	        terms.Discount_Days__c = 30;
	        terms.Discount_Percent__c = 10;
	        terms.Due_Days__c = 60;
	        insert terms; 
	    }
	    public Company__c company = new Company__c(); {
	        company = new Company__c();
	        company.name = 'Kenandy';
	        company.A_Days__c = 30;
	        company.B_Days__c = 60;
	        company.C_Days__c = 180;
	        company.Comp_Currency__c = TestFuel.currencySGD.id;
	        company.Consol_Currency__c = TestFuel.currencyEUR.id;
	        company.Stat_Currency__c = TestFuel.currencyGBP.id;
	        company.Subs_Currency__c = TestFuel.currencyUSD.id;
	        company.Default_Transaction_Currency__c = TestFuel.currencyUSD.id;	        
	        insert company;
	    }  
	    public Customer__c customer = new Customer__c(); {
	        customer.name = 'Customer-1';
	        customer.Company__c = company.id;
	        customer.Payment_Term__c = terms.ID;
	      //  customer.Address__c = soldtoaccount.ID;
	        customer.Credit_Limit__c = 100000.0;
	        insert customer;
	    }	 
	   	public Account remittoaccount = new Account(); {
		    remittoaccount = new Account();
		    remittoaccount.name = 'Remit-to Account';
		    remittoaccount.billingstreet = '1 Boardwalk Dr';
		    remittoaccount.billingcity = 'Santa Jose';
		    remittoaccount.billingstate = 'CA';
		    remittoaccount.billingpostalcode = '95205';
		    remittoaccount.phone = '408-555-1965';
		    remittoaccount.fax = '408-555-8341';
		    insert remittoaccount;
		}
		
		public map <string,string> rtMap = KSE.RecordTypeDevNameMap('Supplier__c');
        
        public Supplier__c supplier = new Supplier__c(); {
	        supplier.Name =  'Supplier-1';
	        supplier.Company__c = company.ID;
	        supplier.Tax_ID__c = 'tax ID';
	        supplier.Address__c = remittoaccount.ID;
	        supplier.Status__c = 'Active';
	        supplier.Payment_Term__c = terms.ID;
	        supplier.Type__c = 'Remit-To';
        	supplier.RecordTypeId = rtMap.get('Remit_To');
	        insert supplier;
	    }     
	}
	
	public static testmethod void t1() { 
		TestData data = new TestData(); 
	
		Hierarchy.Node nod =Dynatree.getHierarchy( data.customer.id , 'Overview') ;
		system.assertEquals( data.customer.id, nod.node.id);
	}

}