src-ken&y/objects/Company__c.object
<CustomObject>
    <customHelpPage>HelpCompany</customHelpPage>
    <description>Each Logistics or Financial entity will be represented by a single Company record.  Master data for the Company is recorded here and used throughout the System.</description>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Currency__c.object
<CustomObject>
    <customHelpPage>HelpCurrency</customHelpPage>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Currency</label>
    <nameField>
        <label>Currency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Customer_Invoice__c.object
<CustomObject>
    <customHelpPage>HelpCustomerInvoice</customHelpPage>
    <description>Customer invoices</description>
    <fields>
        <fullName>Bill_To_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Bill To Customer</description>
        <label>Bill To Customer</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <filterItems>
                <field>Customer__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Bill To</value>
            </filterItems>
            <filterItems>
                <field>Customer__c.Parent_Customer__c</field>
                <operation>equals</operation>
                <valueField>$Source.Customer__c</valueField>
            </filterItems>
            <filterItems>
                <field>Customer__c.Top_Parent_Customer__c</field>
                <operation>equals</operation>
                <valueField>$Source.Customer__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Customer Invoices (Bill To Customer)</relationshipLabel>
        <relationshipName>Bill_To_Customer_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Customer Invoices</relationshipLabel>
        <relationshipName>Ship_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Customer Invoices</relationshipLabel>
        <relationshipName>Customer_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Invoiced__c</fullName>
        <description>Date of invoice</description>
        <label>Invoice Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Finalized__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Once the invoice is finalized the record is eligible to generate accounting entries.</description>
        <label>Finalized</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoice_Type__c</fullName>
        <description>Select the invoice type</description>
        <label>Invoice Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Manual</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Overpayment</fullName>
                </value>
                <value>
                    <fullName>Prepayment</fullName>
                </value>
                <value>
                    <fullName>Ship Invoice</fullName>
                </value>
                <value>
                    <fullName>Allowance Accrual</fullName>
                </value>
                <value>
                    <fullName>RMA-Credit</fullName>
                </value>
                <value>
                    <fullName>Standard</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of this shipment - Open, Shipped, Invoiced, Closed</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <description>Date of the transaction, this could be populated from any source using a workflow depending on customer need.</description>
        <inlineHelpText>Date of the transaction. Can be populated from any source using a workflow.</inlineHelpText>
        <label>Transaction Date</label>
        <type>DateTime</type>
    </fields>
    <label>Customer Invoice</label>
    <nameField>
        <label>Customer Invoice</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Customer_Invoice_Line__c.object
<CustomObject>
    <customHelpPage>HelpCustomerInvoice</customHelpPage>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Company.</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipName>Customer_Transaction_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <formula>Customer_Invoice__r.Currency__r.ISO_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Currency</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Invoice__c</fullName>
        <label>Customer Invoice</label>
        <referenceTo>Customer_Invoice__c</referenceTo>
        <relationshipLabel>Customer Invoice Lines</relationshipLabel>
        <relationshipName>Customer_Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Discount_Percent__c</fullName>
        <label>Discount Percent</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Extended_Price__c</fullName>
        <label>Extended Price</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Finalized__c</fullName>
        <formula>Customer_Invoice__r.Finalized__c</formula>
        <label>Finalized</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipName>Customer_Transaction_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity_Shipped__c</fullName>
        <label>Quantity Fulfilled</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <label>Customer Invoice Line</label>
    <nameField>
        <label>Customer Invoice Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Product__c.object
<CustomObject>
    <customHelpPage>HelpProducts</customHelpPage>
    <description>Products are sellable Items with Selling Unit of Measure included</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status indicates if the product is active or retired</description>
        <label>Status</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/ExceptionTasksExtNewTest.cls
@isTest 	
public with sharing class ExceptionTasksExtNewTest {
		
		public static testMethod void ExceptionTasksTest() {
			TestFuel data = new TestFuel();
			
			Customer_Invoice_Line__c custInvLine1 = new Customer_Invoice_Line__c();
		    custInvLine1.Company__c = data.company.id;
		    custInvLine1.Quantity_Shipped__c = 2;
		    custInvLine1.Unit_Price__c = 7;
		    custInvLine1.Product__c = data.product.id ; 
		    custInvLine1.Discount_Percent__c = 0.2;
		    custInvLine1.Customer_Invoice__c = data.custInv1.id;
		    custInvLine1.Extended_Price__c = custInvLine1.Quantity_Shipped__c * custInvLine1.Unit_Price__c;
		    
		    insert custInvLine1;
		    
			ExceptionTasksExtNew con = new ExceptionTasksExtNew();
			con.parent = data.custInv1;
			String type = con.parentType;
			
			ExceptionService exService = new ExceptionService();
			exService.setException(data.custInv1,ExceptionUtil.SO_INVOICE_LINE_PRICE_MISMATCH);
			exService.setException(custInvLine1,ExceptionUtil.PRODUCT_IS_BLOCKED);
			exService.setException(custInvLine1,ExceptionUtil.PRODUCT_IS_MISSING_VALID_PRICE);
			exService.finishTasks();
			
			System.assert(con.getFieldList() != null);

		}
		
		public static testMethod void MassOverride_withNoProhibitOverride()
		{
			TestFuel fuel = new TestFuel();
			
			Customer_Invoice__c CustomerInvoice = new Customer_Invoice__c();
			CustomerInvoice.Bill_To_Customer__c = fuel.customerBillTo.Id;
            CustomerInvoice.Company__c = fuel.company.Id;
            CustomerInvoice.Invoice_Type__c = 'Manual';
            CustomerInvoice.Status__c = CustomerInvoiceService.STATUS_OPEN;
            CustomerInvoice.Date_Invoiced__c = system.now();
            CustomerInvoice.Currency__c = TestFuel.currencyUSD.id;
            CustomerInvoice.Transaction_Date__c = Date.today();
			//CustomerInvoice.Finalized__c =true;
			insert CustomerInvoice;
			
			Customer_Invoice_Line__c cil = new Customer_Invoice_Line__c();
			cil.Customer_Invoice__c = CustomerInvoice.Id;
			cil.Quantity_Shipped__c = 1;
			cil.Unit_Price__c = 100;
			insert cil;
			
			CustomerInvoice.Finalized__c = true;
			update CustomerInvoice;
			
			list<Task> tasks = new list<Task>();
			tasks.add(new Task(whatId = CustomerInvoice.Id, Subject = 'tasks with no override', Type = 'Exception', Exception_Code__c = 'someCode1', Status = 'Open', Prohibit_Override__c = false));
			tasks.add(new Task(whatId = CustomerInvoice.Id, Subject = 'tasks with  override', Type = 'Exception', Exception_Code__c = 'someCode2', Status = 'Open', Prohibit_Override__c = false));
			
			insert tasks;
			
			ExceptionTasksExtNew con = new ExceptionTasksExtNew();
			con.parent = CustomerInvoice;
			String type = con.parentType;
			
			
			System.assert(con.getFieldList() != null);
			TasksMassOverride overrideExt = new TasksMassOverride(con);
			
			JSONResult result = TasksMassOverride.massOverrideTasks(tasks);
			system.assertEquals(result.success, true,'We expect none to fail the update');
			//system.assertEquals(result.messages.size(),1);
			
			
			for(Task t: [Select Id, isClosed, Prohibit_Override__c from Task where id in :tasks])
			{
				if(t.Prohibit_Override__c)
					system.assertEquals(t.isClosed,false);
				//else
				//	system.assertEquals(t.isClosed,true);
			}
			
		}
		
		
		public static testMethod void MassOverride_withProhibitOverride()
		{
			TestFuel fuel = new TestFuel();
			
			Customer_Invoice__c CustomerInvoice = new Customer_Invoice__c();
			CustomerInvoice.Bill_To_Customer__c = fuel.customerBillTo.Id;
            CustomerInvoice.Company__c = fuel.company.Id;
            CustomerInvoice.Invoice_Type__c = 'Manual';
            CustomerInvoice.Status__c = CustomerInvoiceService.STATUS_OPEN;
            CustomerInvoice.Date_Invoiced__c = system.now();
            CustomerInvoice.Currency__c = TestFuel.currencyUSD.id;
            CustomerInvoice.Transaction_Date__c = Date.today();
			//CustomerInvoice.Finalized__c =true;
			insert CustomerInvoice;
			
			Customer_Invoice_Line__c cil = new Customer_Invoice_Line__c();
			cil.Customer_Invoice__c = CustomerInvoice.Id;
			cil.Quantity_Shipped__c = 1;
			cil.Unit_Price__c = 100;
			insert cil;
			
			CustomerInvoice.Finalized__c = true;
			update CustomerInvoice;
			
			list<Task> tasks = new list<Task>();
			tasks.add(new Task(whatId = CustomerInvoice.Id, Subject = 'tasks with no override', Type = 'Exception', Exception_Code__c = 'someCode1', Status = 'Open', Prohibit_Override__c = false));
			tasks.add(new Task(whatId = CustomerInvoice.Id, Subject = 'tasks with  override', Type = 'Exception', Exception_Code__c = 'someCode2', Status = 'Open', Prohibit_Override__c = true));
			
			insert tasks;
			
			ExceptionTasksExtNew con = new ExceptionTasksExtNew();
			con.parent = CustomerInvoice;
			String type = con.parentType;
			
			
			System.assert(con.getFieldList() != null);
			TasksMassOverride overrideExt = new TasksMassOverride(con);
			
			JSONResult result = TasksMassOverride.massOverrideTasks(tasks);
			system.assertEquals(result.success, false,'We expect one to fail the update');
			system.assertEquals(result.messages.size(),1);
			
			
			for(Task t: [Select Id, isClosed, Prohibit_Override__c from Task where id in :tasks])
			{
				if(t.Prohibit_Override__c)
					system.assertEquals(t.isClosed,false);
				//else
				//	system.assertEquals(t.isClosed,true);
			}
			
		}
}