src-ken&y/objects/Company__c.object
<CustomObject>
    <customHelpPage>HelpCompany</customHelpPage>
    <description>Each Logistics or Financial entity will be represented by a single Company record.  Master data for the Company is recorded here and used throughout the System.</description>
    <fields>
        <fullName>Serial_Control__c</fullName>
        <description>Defines which processes needs to track serials</description>
        <label>Serial Control</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>At receipt and all processes</fullName>
                </value>
                <value>
                    <fullName>At shipment only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Item__c.object
<CustomObject>
    <customHelpPage>HelpItems</customHelpPage>
    <description>Item Master object</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company that controls this item</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Material_Tracking__c.object
<CustomObject>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Material Trackings</relationshipLabel>
        <relationshipName>Material_Trackings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Order__c</fullName>
        <label>Work Order</label>
        <referenceTo>Work_Order__c</referenceTo>
        <relationshipLabel>Material Trackings</relationshipLabel>
        <relationshipName>Material_Trackings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Material Tracking</label>
    <nameField>
        <displayFormat>MT-{0000000000}</displayFormat>
        <label>Material Tracking</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Material Trackings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Work_Order__c.object
<CustomObject>
    <customHelpPage>HelpWorkOrder</customHelpPage>
    <description>All work orders including planned orders from MRP as well as unplanned orders.</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company this Work Order belongs to</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Item</description>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Work Order</label>
    <nameField>
        <label>Work Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/WorkOrderAllocationExt.cls
public with sharing class WorkOrderAllocationExt extends GridRelatedListController {

    public String namespaceUU { get; set; } { namespaceUU = KSE.NamespaceUU; }
    public Boolean serialTracked { get; set; } { serialTracked = false; }
    public Boolean disable { get; set; } { disable = false; }

    private Work_Order__c wo;

    public WorkOrderAllocationExt(ApexPages.StandardController con) { 
        wo = WorkOrderService.getWorkOrders(new Set<Id>{ con.getId() },null,null,null)[0];

        if (wo.Company__r.Serial_Control__c == SkidService3.AT_RECEIPT) {
            serialTracked = true;
        }

        try {
            AllocationService.validate(new List<Work_Order__c>{ wo });
        } catch (Exception e) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, MessageUtil.toFriendlyErrorMessage(e.getMessage())));
            system.debug(LoggingLevel.Error, 'EXCEPTION: ' + e.getMessage() + ' ' + e.getStackTraceString());
            disable = true;
        }
    }

    @RemoteAction
    public static JsonResult getMaterialData(Id woId) {
        JsonResult result = new JsonResult();
        try {
            result.records = AllocationService.getLines(new Set<Id>{ woId });
            result.total = result.records.size();
        } catch(Exception e) {
            result.success = false;
            result.addMessage(e.getMessage(),ApexPages.Severity.ERROR);
        }
        return result;
    }

    @RemoteAction
    public static JsonResult save(List<LineWrapper> mWrappers,List<String> mDateFields,List<String> skidDateFields) {
        JsonResult result = new JsonResult();
        Savepoint sp = Database.setSavepoint();
        try {
            for (LineWrapper mWrapper:mWrappers) {
                KendoUtils.UpdateDateFields(mWrapper.line,mDateFields);
                
                for (SkidService3.SerialWrapper sw:mWrapper.serialWrappers) {
                    KendoUtils.UpdateDateFields(sw.skid,skidDateFields);

                    sw.skid.Item__r = (Item__c)mWrapper.line.getSObject('Item__r');
                }
            }

            AllocationService.allocate(mWrappers);
        } catch(Exception e) {
            Database.rollback(sp);
            result.success = false;
            result.addMessage(e.getMessage(),ApexPages.Severity.ERROR);
        }
        return result;
    }

    public String woJson {
        get {
            if (woJson == null) {
                woJson = JSON.serialize(wo);
            }
            return woJson;
        } set;
    }

    public String materialConfigJson {
        get {
            if (materialConfigJson == null) {
                materialConfigJson = JSON.serialize(AllocationService.getLineConfig(Material_Tracking__c.sObjectType));
            }
            return materialConfigJson;
        } set;
    }

    public String materialFieldsJson {
        get {
            if (materialFieldsJson == null) {
                materialFieldsJson = JSON.serialize(AllocationService.getLineFields('Material_Tracking__c'));
            }
            return materialFieldsJson;
        } set;
    }

    public String skidFieldsJson {
        get {
            if (skidFieldsJson == null) {
                skidFieldsJson = JSON.serialize(AllocationService.skidFields);
            }
            return skidFieldsJson;
        } set;
    }

    public String serialFieldsJson {
        get {
            if (serialFieldsJson == null) {
                serialFieldsJson = JSON.serialize(AllocationService.serialFields);
            }
            return serialFieldsJson;
        } set;
    }

    public String serialAttributesJson {
        get {
            if (serialAttributesJson == null) {
                serialAttributesJson = JSON.serialize(SkidService3.serialAttributes); 
            }
            return serialAttributesJson;
        } set;
    }

    public Integer gridSize {
        get {
            if (gridSize == null) {
                gridSize = AllocationService.gridSize;
            }
            return gridSize;
        } set;
    }

    public PageReference cancel() { return new PageReference('/' + wo.Id); }
}