src-ken&y/objects/Company__c.object
<CustomObject>
    <customHelpPage>HelpCompany</customHelpPage>
    <description>Each Logistics or Financial entity will be represented by a single Company record.  Master data for the Company is recorded here and used throughout the System.</description>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Financial_Report__c.object
<CustomObject>
    <customHelpPage>Help_Financial_Reports</customHelpPage>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Set to filter this report by a company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Financial Reports</relationshipLabel>
        <relationshipName>Financial_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Numeric_Scale__c</fullName>
        <defaultValue>2</defaultValue>
        <description>show 0 , 1 or 2 decimal places</description>
        <inlineHelpText>The number of decimal places to show in the report/section/item.</inlineHelpText>
        <label>Numeric Scale</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Period_Name__c</fullName>
        <label>Period Name</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Report_Object_Name__c</fullName>
        <description>The API name of the object that is being reported on</description>
        <label>Report Object Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Show_Symbols__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Display or hide currency symbols</description>
        <label>Show Symbols</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Symbols_First_Last__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Show Symbols on the first and last rows of a report only</description>
        <label>Symbols First Last</label>
        <type>Checkbox</type>
    </fields>
    <label>Financial Report</label>
    <nameField>
        <label>Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Financial_Report_Section__c.object
<CustomObject>
    <customHelpPage>Help_Financial_Reports</customHelpPage>
    <fields>
        <fullName>Company__c</fullName>
        <formula>Financial_Report__r.Company__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Company</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Display_Section_Name__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Display or hide this section name on the final Financial Report</description>
        <label>Display Section Name</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Financial_Report__c</fullName>
        <label>Financial Report</label>
        <referenceTo>Financial_Report__c</referenceTo>
        <relationshipLabel>Report Sections</relationshipLabel>
        <relationshipName>Financial_Report_Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Numeric_Scale__c</fullName>
        <formula>Financial_Report__r.Numeric_Scale__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Numeric Scale</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <description>The order this section appears in the output report</description>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Period_Name__c</fullName>
        <formula>Financial_Report__r.Period_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Period Name</label>
        <type>Text</type>
    </fields>
    <label>Financial Report Section</label>
    <nameField>
        <label>Report Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Report Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Order__c.object
<CustomObject>
    <customHelpPage>HelpOrder</customHelpPage>
    <label>Order</label>
    <nameField>
        <label>Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Report_Item__c.object
<CustomObject>
    <customHelpPage>Help_Financial_Reports</customHelpPage>
    <fields>
        <fullName>Asynchronous__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The Analytics API can handle a higher number of asynchronous run requests at a time.</description>
        <inlineHelpText>Select to generate the report in a background process. When you run a report asynchronously, a message displays informing you that the report will be ready to view at a later point in time. Recommended for large reports.</inlineHelpText>
        <label>Asynchronous</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Column_Total_Label__c</fullName>
        <description>The text to be displayed as column totals row label</description>
        <label>Column Total Label</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <formula>Financial_Report_Section__r.Financial_Report__r.Company__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Company</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Field__c</fullName>
        <description>Object API name and field API name to apply the date range filter to</description>
        <label>Date Field</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Display_Column_Labels__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Display or hide column headers on this Report</description>
        <label>Display Column Labels</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Display_Column_Totals__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If checked, the column totals will be shown. Only used for matrix reports.</description>
        <label>Display Column Totals</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Display_Name__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Checked if the name should appear in the report output</description>
        <label>Display Name</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Display_Total__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If checked, the totals from the report will be shown. For matrix reports, this checkbox controls the row totals.</description>
        <label>Display Total</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>Ending date to filter the report on</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Financial_Report_Section__c</fullName>
        <label>Financial Report Section</label>
        <referenceTo>Financial_Report_Section__c</referenceTo>
        <relationshipLabel>Report Items</relationshipLabel>
        <relationshipName>Report_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>currently not used</description>
        <label>Key</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Numeric_Scale__c</fullName>
        <formula>Financial_Report_Section__r.Numeric_Scale__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The number of decimal places to show in the report/section/item.</inlineHelpText>
        <label>Numeric Scale</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <description>order to display this report item by within the report section</description>
        <label>Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Period_Name__c</fullName>
        <formula>Financial_Report_Section__r.Period_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Period Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Report_Id__c</fullName>
        <inlineHelpText>Enter the Report ID for the report to which you want to link this item.</inlineHelpText>
        <label>Report Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Report_Key__c</fullName>
        <description>This value is used to group report items into the same table</description>
        <label>Report Key</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Show_Details__c</fullName>
        <defaultValue>false</defaultValue>
        <description>use with Tabular reports, shows rows of data</description>
        <inlineHelpText>Select to show rows of data in tabular reports.</inlineHelpText>
        <label>Show Details</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Start date for the report to filter on</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Label__c</fullName>
        <defaultValue>&quot;Total&quot;</defaultValue>
        <description>The text to appear in the Total line of this report</description>
        <label>Total Label</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_On_Top__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Total On Top</label>
        <type>Checkbox</type>
    </fields>
    <label>Report Item</label>
    <nameField>
        <label>Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Report Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/classes/FinancialReportExt.cls
public with sharing class FinancialReportExt {

    public Apexpages.Standardcontroller con { get; private set; }
    public String runtime { get; private set; } //KNDY-2515: Add date/time to financial report
    
    public FinancialReportExt(ApexPages.StandardController controller) { 
        con = controller;
        runtime = String.valueOf(Datetime.now());   //KNDY-2515: Add date/time to financial report
        loadLines();
    }

    public Pagereference cloneFR() { // and it's children sections/ items
        String serializedData = SObjectDataLoader.serialize( 
                                                    new set<id>{con.getId()}, 
                                                    new SObjectDataLoader.SerializeConfig().
                                                        followChild( Financial_Report_Section__c.Financial_Report__c).
                                                        followChild( Report_Item__c.Financial_Report_Section__c).
                                                        includeLookups(true)      );
        //system.debug( LoggingLevel.INFO, 'data '+serializedData );
        //system.debug( LoggingLevel.INFO, 'data length '+serializedData.length() );
        Set<ID> resultIds = SObjectDataLoader.deserialize(serializedData, 
                                                    null , 
                                                    new TransformNewRecords()    );
        List<id> fid = new List<id>(resultIds); 
        return new ApexPages.standardController(new Financial_Report__c(id=fid[0] ) ).view();                                                               
        //return null;  
    }
    
    // called for each recod we are about to insert by deserialize
    private class TransformNewRecords implements SObjectDataLoader.ITransformCallback {
        public TransformNewRecords() { } 
        public boolean transformRecord (Schema.SObjectType sObjectType, sobject record ) { 
            //system.debug( logginglevel.info, 'transform '+ record);
            if ( sObjectType == Financial_Report__c.sObjectType) {
                record.put('Company__c',null);
                record.put('Period_Name__c','');
            }
            if ( sObjectType == Report_Item__c.sObjectType) {
                record.put('Key__c',null);
            }
            return true;
        }
    }
    
    private void loadLines() {
    	List<Schema.FieldSetMember> fsFields = SObjectType.Financial_Report__c.FieldSets.Report_Filters.getFields();
    	Map<String,String> fsPathToLabel = new Map<String,String>(); 
    	filterFields = new Map<Id,List<String>>();
    	Set<String> tempSegments = new Set<String>();
    	


/*
//KNDY-10473: Adding CRUD/FLS checks with SOQLUtil
    */
//V2
SOQLUtil soql = new SOQLUtil('Financial_Report_Section__c', true); //enforceFLS=true, running in user mode
soql.addFields(new set<string>{
	'Id','Name','Display_Section_Name__c','Financial_Report__c','Order__c'
});
    string cId = con.getId();        
    soql.setWhereClause('Financial_Report__c = :cId');
soql.setOrderByClause('Order__c ASC');
SOQLUtil.ChildRelationship childRel = new SOQLUtil.ChildRelationship(soql, 'Report_Items__r');
childRel.addFields(new set<string>{
	'Id','Name','Asynchronous__c','Column_Total_Label__c','Company__c','Date_Field__c','Display_Column_Labels__c',
	'Display_Column_Totals__c','Display_Name__c','Report_Key__c','Display_Total__c','End_Date__c','Financial_Report_Section__c',
	'Numeric_Scale__c','Order__c','Period_Name__c','Report_Id__c','Show_Details__c','Start_Date__c','Total_Label__c',
	'Total_On_Top__c','Financial_Report_Section__r.Financial_Report__r.Show_Symbols__c','Financial_Report_Section__r.Financial_Report__r.Symbols_First_Last__c'
});
soql.addChildRelationship(childRel);
records = Database.query(soql.getQuery());



        for (Financial_Report_Section__c sec:records) {
            for (Report_Item__c item:sec.Report_Items__r) {
                if (item.Report_Key__c == null || item.Report_Key__c == '')
                    item.Report_Key__c = ((String)item.Id).substring(8,18);
                    
                
                if (!filterFields.containsKey(item.Id))
                	filterFields.put(item.Id,new List<String>());
                
                List<String> flds = new List<String>();
                 /*
                String query = 'SELECT Id,Name,Financial_Report_Section__r.Financial_Report__r.Report_Object_Name__c';            
    			for (Schema.FieldSetMember fsField:fsFields) {
		    		//TODO:HANDLE NON LOOKUP FILTERS
		       		query += ',Financial_Report_Section__r.Financial_Report__r.' + fsField.getFieldPath().replaceAll('__c','__r') + '.Name';
		       		query += ',Financial_Report_Section__r.Financial_Report__r.' + fsField.getFieldPath();
		       		flds.add(fsField.getFieldPath());
		       		fsPathToLabel.put(fsField.getFieldPath(),fsField.getLabel());
		    	}
    			query += ' FROM Report_Item__c WHERE Id = \'' + item.Id + '\'';    */
    			
                Set<String> cusFields = new Set<String>();
                for (Schema.FieldSetMember fsField:fsFields) {
		    		//TODO:HANDLE NON LOOKUP FILTERS
		       		cusFields.add( ',Financial_Report_Section__r.Financial_Report__r.' + fsField.getFieldPath().replaceAll('__c','__r') + '.Name');
		       		cusFields.add( ',Financial_Report_Section__r.Financial_Report__r.' + fsField.getFieldPath());
		       		flds.add(fsField.getFieldPath());
		       		fsPathToLabel.put(fsField.getFieldPath(),fsField.getLabel());
		    	}
                
                
                
                String whereClause = 'Id = \'' + item.Id + '\'';//KNDY-8796
                 soql = new SOQLUtil('Report_Item__c');
                soql.addFields(new Set<String>{'Id', 'Name', 'Financial_Report_Section__r.Financial_Report__r.Report_Object_Name__c'});
                soql.addFields(cusFields);
                soql.setWhereClause(whereClause);
                
    			
    			//Report_Item__c ri = ((List<Report_Item__c>)Database.query(query))[0];
                Report_Item__c ri = ((List<Report_Item__c>)Database.query(soql.getQuery()))[0];
		    	for (String fieldName:flds) {
		    		String column,value;
		    		
		    		Financial_Report_Section__c section = (Financial_Report_Section__c)ri.getSObject('Financial_Report_Section__r');
		    		
		    		Financial_Report__c report = (Financial_Report__c)section.getSObject('Financial_Report__r');
		    		
		    		if ((String)report.get('Report_Object_Name__c') == null)
		    			break;
		    			
		    		sObject obj = (sObject)report.getSObject(fieldName.replaceAll('__c','__r'));
		    		if (obj == null)
		    			continue;
		    		
		    		column = (String)report.get('Report_Object_Name__c') + '.' + fieldName;
		    		
		    		value = (String)obj.get('Name');
		    		
		    		filterFields.get(item.Id).add(column + '::' + value);
		    		tempSegments.add(fsPathToLabel.get(fieldName) + ' : ' + value);
		    	}
            }
        }
        segments = new List<String>(tempSegments);  
    }
    public List<Financial_Report_Section__c> records { get; private set;}
    public Map<Id,List<String>> filterFields { get; private set; }
    public List<String> segments { get; private set; }
    
    @remoteAction 
    public static id addNewReportItem( string lineid, string reportid, string nam) {
        Report_item__c ri = new Report_item__c();
        ri.name = nam.replaceAll('&amp;','&'); // replace &amp; ==> & TODO use html escape string method
        ri.report_id__c = reportid; 
        ri.Financial_Report_Section__c = lineid; 
        DML.insertAsUser( new List<sobject>{ ri } ); 
        return ri.id; // need the new id back in the client
    } 
    
    @remoteAction 
    public static void removeReportItem ( string reportid ) {
        DML.deleteAsUser( new List<Sobject>{ new Report_Item__c( id = reportid ) } );
    }
    
    public void saveOrder() { 
        DML.checkUpsertAsUser(records); upsert records;
        list<Report_Item__c> itemsList = new list<Report_Item__c>();  
        for (Financial_Report_Section__c f : records ) {
            itemsList.addAll ( f.Report_Items__r );
        }
        DML.checkUpsertAsUser(itemsList); upsert itemsList;
        loadLines();    
    }
    public void reLoad() { loadLines(); }  
    
}