src-ken&y/objects/Company__c.object
<CustomObject>
    <customHelpPage>HelpCompany</customHelpPage>
    <description>Each Logistics or Financial entity will be represented by a single Company record.  Master data for the Company is recorded here and used throughout the System.</description>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Currency__c.object
<CustomObject>
    <customHelpPage>HelpCurrency</customHelpPage>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Currency</label>
    <nameField>
        <label>Currency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Invoice__c.object
<CustomObject>
    <customHelpPage>HelpIntercompanyInvoices</customHelpPage>
    <fields>
        <fullName>Balance__c</fullName>
        <formula>Total_Line_Amount__c  - Amount_Paid__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to company</description>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Invoice Currency</relationshipLabel>
        <relationshipName>Invoice_Currency</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Finalized__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Finalized</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>From_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>From Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>From Company Invoices</relationshipLabel>
        <relationshipName>From_Company_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>To_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>To Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>To Company Invoices</relationshipLabel>
        <relationshipName>To_Company_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <label>Transaction Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Intercompany Investment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Intercompany Investment</fullName>
                </value>
                <value>
                    <fullName>Intercompany Cross Charge</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Payment__c.object
<CustomObject>
    <customHelpPage>HelpIntercompanyInvoices</customHelpPage>
    <fields>
        <fullName>Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to currency</description>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Payment Currency</relationshipLabel>
        <relationshipName>Payment_Currency</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Finalized__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Finalized</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>From_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>From Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>From Company Payments</relationshipLabel>
        <relationshipName>From_Company_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Amount__c</fullName>
        <label>Payment Amount</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>To_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>To Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>To Company Payments</relationshipLabel>
        <relationshipName>To_Company_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <label>Transaction Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Intercompany Payment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Intercompany Payment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Payment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Payment_Line__c.object
<CustomObject>
    <fields>
        <fullName>Currency__c</fullName>
        <formula>Payment__r.Currency__r.ISO_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Currency</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Finalized__c</fullName>
        <formula>Payment__r.Finalized__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Finalized</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <label>Payment</label>
        <referenceTo>Payment__c</referenceTo>
        <relationshipLabel>Payment Lines</relationshipLabel>
        <relationshipName>Payment_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Payment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment Line</label>
    <nameField>
        <label>Payment Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Period__c.object
<CustomObject>
    <customHelpPage>HelpPeriods</customHelpPage>
    <description>Segment of time that financial entries fall into</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Periods</relationshipLabel>
        <relationshipName>Periods</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Adjustment</fullName>
                </value>
                <value>
                    <fullName>Fiscal</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Historical</fullName>
                </value>
                <value>
                    <fullName>Period 13</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Period</label>
    <nameField>
        <label>Period</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/PaymentLinesManageExtTest.cls
@isTest
private class PaymentLinesManageExtTest {
	
	static testMethod void testExtensionLoadNew() {
    	
        TestFuel fuel = new TestFuel();
        Company__c company = fuel.company;
        Company__c altCompany = fuel.altCompany;
        List<Period__c> periodList = fuel.periodList;
        List<Period__c> altCompanyPeriodList = fuel.altCompanyPeriodList;
        Invoice__c inv = fuel.intercompanyInvestmentInvoice;
        
        inv.Finalized__c = true;
        update inv;
        
        Payment__c pmt = new Payment__c();
        
        test.startTest();
        
        PaymentLinesManageExt ext = new PaymentLinesManageExt(new Apexpages.Standardcontroller(pmt));
        ext.getPaymentHeaderAdditionalFieldList();
        ext.getPaymentHeaderManageFieldList();
        ext.getPaymentLineFieldList();
        ext.getInvoiceFieldList();
        ext.getPaymentMatchFieldList();
        ext.getExceptionFieldList();
        List<Integer> inds = ext.selected_indexes;
        ext.getInvoiceOptionsConfigJson();
        ext.getPaymentLinesConfigJson();
        
        system.assertEquals(null, pmt.Id);
        
        JSONResult pmtDetailResult = PaymentLinesManageExt.getPaymentDetails(pmt.Id);
        system.assertEquals(0, pmtDetailResult.records.size());
        
        pmt.From_Company__c = company.Id;
		pmt.To_Company__c = altCompany.Id;
		pmt.Currency__c = TestFuel.currencyUSD.id;
		pmt.Transaction_Date__c = system.now();
		pmt.Type__c = 'Intercompany Payment';
		pmt.Transaction_Type__c = 'Intercompany Payment';
        
        JSONResult pmtSaveResult = PaymentLinesManageExt.savePaymentDetails(JSON.serialize(pmt));
        system.assertEquals(1, pmtSaveResult.total, pmtSaveResult);
        pmt = (Payment__c)pmtSaveResult.records[0];
        
        ext = new PaymentLinesManageExt(new Apexpages.Standardcontroller(pmt));
        ext.invoiceOptionsConfig.parentRecord = pmt;
        
        JsonResult invoiceOptions = PaymentLinesManageExt.getInvoiceOptions(ext.invoiceOptionsConfig);
        system.assertEquals(1, invoiceOptions.total, invoiceOptions);
        
        JSONResult addInvoicesResult = PaymentLinesManageExt.addInvoicesToPayment(pmt.Id, new list<string>{inv.Id});
        system.assertEquals(1, addInvoicesResult.total, addInvoicesResult);
		
		inv = [SELECT Id, Name, Balance__c FROM Invoice__c WHERE Id = :inv.Id];
        pmt = [SELECT Id, payment_amount__c, (SELECT Id FROM Payment_Lines__r) FROM Payment__c WHERE Id = :pmt.Id];
        system.assertEquals(inv.Balance__c, pmt.payment_amount__c);
        system.assertNotEquals(0, pmt.Payment_Lines__r.size());
        
        pmt.finalized__c = true;
        pmtSaveResult = PaymentLinesManageExt.savePaymentDetails(JSON.serialize(pmt));
        system.assertEquals(1, pmtSaveResult.total, pmtSaveResult);
        pmt = (Payment__c)pmtSaveResult.records[0];
        system.assert(pmt.Finalized__c);
        
        
        test.stopTest();
        
        
    }
	
    static testMethod void testExtensionLoadExisting() {
    	
        TestFuel fuel = new TestFuel();
        Company__c company = fuel.company;
        Company__c altCompany = fuel.altCompany;
        List<Period__c> periodList = fuel.periodList;
        List<Period__c> altCompanyPeriodList = fuel.altCompanyPeriodList;
        
        Payment__c pmt = fuel.intercompanyPayment;
        
        test.startTest();
        
        PaymentLinesManageExt ext = new PaymentLinesManageExt(new Apexpages.Standardcontroller(pmt));
        ext.getPaymentHeaderAdditionalFieldList();
        ext.getPaymentHeaderManageFieldList();
        ext.getPaymentLineFieldList();
        ext.getInvoiceFieldList();
        ext.getPaymentMatchFieldList();
        ext.getExceptionFieldList();
        List<Integer> inds = ext.selected_indexes;
        GridRelatedListController.GridRelatedListConfig invOptsConfig = (GridRelatedListController.GridRelatedListConfig)JSON.deserialize(ext.getInvoiceOptionsConfigJson(), GridRelatedListController.GridRelatedListConfig.class);
        GridRelatedListController.GridRelatedListConfig pmtLinesConfig = (GridRelatedListController.GridRelatedListConfig)JSON.deserialize(ext.getPaymentLinesConfigJson(), GridRelatedListController.GridRelatedListConfig.class);
        
		JSONResult pmtDetailResult = PaymentLinesManageExt.getPaymentDetails(pmt.Id);
        system.assertEquals(1, pmtDetailResult.records.size());
        Payment__c refPmt = (Payment__c)pmtDetailResult.records[0];
        system.assertEquals(pmt.Id, refPmt.Id);
        
        JSONResult pmtSaveResult = PaymentLinesManageExt.savePaymentDetails(JSON.serialize(pmt));
        system.assertEquals(1, pmtSaveResult.total, pmtSaveResult);
        refPmt = (Payment__c)pmtSaveResult.records[0];
        system.assertEquals(pmt.Id, refPmt.Id);
        
        DataSourceResult pmtLinesSaveResult = PaymentLinesManageExt.savePaymentLines(new list<sObject>{pmt}, new list<sObject>(), new list<sObject>(), new list<string>());
        system.assertEquals(1, pmtLinesSaveResult.total, pmtLinesSaveResult);
        
        JSONResult pmtLines = PaymentLinesManageExt.getPaymentLines(pmtLinesConfig);
        
        JSONResult invOpts = PaymentLinesManageExt.getInvoiceOptions(invOptsConfig);
        
        test.stopTest();
        
        
    }
}