src-ken&y/objects/Company__c.object
<CustomObject>
    <customHelpPage>HelpCompany</customHelpPage>
    <description>Each Logistics or Financial entity will be represented by a single Company record.  Master data for the Company is recorded here and used throughout the System.</description>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Supplier_1099__c.object
<CustomObject>
    <customHelpPage>HelpSupplier1099</customHelpPage>
    <description>This handles the supplier 1099s for the current year and the previous historical 1099s.</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Company the 1099 supplier / record belongs on.</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Supplier 1099s</relationshipLabel>
        <relationshipName>Supplier_1099s</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exclude__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allows an AP user to exclude this 1099 from being filed for the year.</description>
        <inlineHelpText>Allows an AP user to exclude this 1099 from being filed for the year.</inlineHelpText>
        <label>Exclude</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier</label>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Supplier 1099s</relationshipLabel>
        <relationshipName>Supplier_1099</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <defaultValue>&quot;2013&quot;</defaultValue>
        <description>Year of tax filing</description>
        <inlineHelpText>Year of tax filing</inlineHelpText>
        <label>Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Supplier 1099</label>
    <nameField>
        <displayFormat>1099-{0000000000}</displayFormat>
        <label>Supplier 1099</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier 1099s</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Supplier__c.object
<CustomObject>
    <customHelpPage>HelpSuppliers</customHelpPage>
    <description>Supplier object</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Suppliers</relationshipLabel>
        <relationshipName>Suppliers1_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Supplier</label>
    <nameField>
        <label>Supplier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/Export1099RecordsExt.cls
public with sharing class Export1099RecordsExt extends BaseController{
    public static SchemaUtil util = SchemaUtil.getInstance();
    public string s1099Fields;
    public string NamespaceUU { get { return KSE.NamespaceUU; }}

    public Export1099RecordsExt(Apexpages.Standardcontroller controller){
       s1099Fields = getS1099Fields();
    }
    
    	public Export1099RecordsExt(ApexPages.StandardSetController scon) {
		// to support integration with vf pages for list view buttons
	}
    
    public String getReturnUrl(){
        PageReference pageRef;
        Schema.DescribeSObjectResult result = Supplier_1099__c.SObjectType.getDescribe();
        pageRef = new PageReference('/' + result.getKeyPrefix());
        return pageRef.getUrl();
    }
    
    @RemoteAction @ReadOnly 
    public static JsonResult getSupplier1099Records(List<String> selectedCompanyIds, String selectedYear) {
        JsonResult result = new JsonResult();
        Integer intYr = Integer.ValueOf(selectedYear);
        Map<String, List<Supplier_1099__c>> mapCompanyId1099s = new Map<String, List<Supplier_1099__c>>();
        String fieldset = 'Export_1099_Records';
        string whereClause =  ' Company__c in :selectedCompanyIds and Exclude__c = false and Year__c =:selectedYear';
        Set<String> additionalFields = new Set<String>{'Company__c', 'Year__c','Supplier__r.Name', 'Company__r.Name'};
        if (selectedCompanyIds == null || selectedCompanyIds.size() == 0){
            whereClause =  ' Exclude__c = false and Year__c =:selectedYear';
        }
        try{
            String queryString = util.generateQueryFromFieldSet('Supplier_1099__c', new Set<string>{ fieldset }, additionalFields, whereClause);
            List<Supplier_1099__c> s1099List = database.query(queryString);
            result.records = s1099List;
            result.success = false;
            if (result.records != null && result.records.size() > 0){
                result.success = true;
                result.total = result.records.size();
                Map<String, List<Supplier_1099__c>> mapCompanyId1099Records = get1099sPerCompany(s1099List);
                result.records = new List<Map<String, List<Supplier_1099__c>>>{mapCompanyId1099Records};
            }else{
                result.total = 0;
                String errorMessage = Label.No_records_are_available_to_export;   
                result.addMessage(errorMessage, ApexPages.Severity.INFO);
            }
        }catch (Exception ex){
            String errorMessage = 'An Error occured : ' + ex.getMessage();   
            result.addMessage(errorMessage, ApexPages.Severity.ERROR);
        }
        return result;
    }
    
    public static Map<String, List<Supplier_1099__c>> get1099sPerCompany(List<Supplier_1099__c> s1099List){
         Map<String, List<Supplier_1099__c>> mapCompanyId1099s = new Map<String, List<Supplier_1099__c>>();
         for (Supplier_1099__c record: s1099List){
         	 String fileName = 'Supplier 1099s-<Company Name>-<Year>';
             fileName = fileName.replace('<Year>',record.Year__c);
             fileName = fileName.replace('<Company Name>' ,record.Company__r.Name);
             if (!mapCompanyId1099s.containsKey(fileName)){
                 mapCompanyId1099s.put(fileName, new List<Supplier_1099__c>());
             }
             mapCompanyId1099s.get(fileName).add(record);
         }
         return mapCompanyId1099s;
    }
    
    public string getS1099Fields(){
        List<FieldInfo> fieldInfoList = FieldInfo.fetchJsonFieldInfos('Supplier_1099__c', 'Export_1099_Records');
        fieldInfoList.remove(0); // remove Id field
        s1099Fields = JSON.serialize(fieldInfoList);
        return s1099Fields;
    }
}