src-ken&y/objects/Company__c.object
<CustomObject>
    <customHelpPage>HelpCompany</customHelpPage>
    <description>Each Logistics or Financial entity will be represented by a single Company record.  Master data for the Company is recorded here and used throughout the System.</description>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Facility__c.object
<CustomObject>
    <customHelpPage>HelpFacilites</customHelpPage>
    <description>Warehouse or building</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Facilities</relationshipLabel>
        <relationshipName>Facilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Facility</label>
    <nameField>
        <label>Facility</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Facility_Item__c.object
<CustomObject>
    <customHelpPage>HelpFacilityItem</customHelpPage>
    <description>Facility specific Item information</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Facility Items</relationshipLabel>
        <relationshipName>Facility_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Facility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Facility</description>
        <label>Facility</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Facility Company must match Facility Item Company</errorMessage>
            <filterItems>
                <field>Facility__c.Company__c</field>
                <operation>equals</operation>
                <valueField>$Source.Company__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Facility__c</referenceTo>
        <relationshipLabel>Facility Items</relationshipLabel>
        <relationshipName>Facility_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <description>Master relationship to Item</description>
        <label>Item</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>Item Company must match Facility Item Company</errorMessage>
            <filterItems>
                <field>Item__c.Company__c</field>
                <operation>equals</operation>
                <valueField>$Source.Company__c</valueField>
            </filterItems>
            <filterItems>
                <field>Item__c.Company__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Facility Items</relationshipLabel>
        <relationshipName>Facility_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Facility Item</label>
    <nameField>
        <label>Facility Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facility Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Item__c.object
<CustomObject>
    <customHelpPage>HelpItems</customHelpPage>
    <description>Item Master object</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company that controls this item</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/FacilityItemNewExtTest.cls
@isTest
public with sharing class FacilityItemNewExtTest {

    static TestData data = new TestData();
    
    static testMethod void test_FacilityItemNew() {
         
        Test.startTest();
        
        Facility_Item__c fi = new Facility_Item__c();
        fi.Company__c = data.company.ID;
        fi.Facility__c = data.facility2.ID;
        fi.Item__c = data.itemList[0].ID;
        
        Apexpages.Standardcontroller con = new Apexpages.Standardcontroller( fi );        
        FacilityItemNewExt ext = new FacilityItemNewExt(con);
        ext.SaveFI();
        system.assert(Apexpages.hasMessages() == false, Apexpages.getMessages());        
    }
 
  
}