src-ken&y/objects/Company__c.object
<CustomObject>
    <customHelpPage>HelpCompany</customHelpPage>
    <description>Each Logistics or Financial entity will be represented by a single Company record.  Master data for the Company is recorded here and used throughout the System.</description>
    <fields>
        <fullName>MRP_Backward_Horizon_in_Days__c</fullName>
        <description>The number of days in the past from today that MRP will search for demand and supply</description>
        <inlineHelpText>Specifies the number of days in the past that MRP looks to for supply and demand.</inlineHelpText>
        <label>MRP Backward Horizon in Days</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MRP_Demand_Time_Fence_in_Days__c</fullName>
        <description>MRP uses forecasted demand outside of this time window and Sales Orders inside this time fence</description>
        <inlineHelpText>MRP uses forecast demand outside of this time fence and sales order demand inside the time fence.</inlineHelpText>
        <label>MRP Demand Time Fence in Days</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MRP_Forward_Horizon_in_Days__c</fullName>
        <description>The number of days in the future from today that MRP will search for demand and supply</description>
        <inlineHelpText>Specifies the number of days in the future that MRP looks to for supply and demand.</inlineHelpText>
        <label>MRP Forward Horizon in Days</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MRP_Planning_Time_Fence_in_Days__c</fullName>
        <description>The number of days in the future from today before MRP creates any planned make order</description>
        <inlineHelpText>MRP will not change existing planned orders within the specified period.</inlineHelpText>
        <label>MRP Planning Time Fence in Days</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Planning_Calendar2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Planning Calendar</label>
        <referenceTo>Calendar__c</referenceTo>
        <relationshipLabel>Companies (Planning Calendar)</relationshipLabel>
        <relationshipName>Companies1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Receiving_Calendar2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Receiving Calendar</label>
        <referenceTo>Calendar__c</referenceTo>
        <relationshipLabel>Companies (Receiving Calendar)</relationshipLabel>
        <relationshipName>Companies2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Use_Only_Level_Zero_QOH_as_Supply_in_MRP__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Use Only Level Zero QOH as Supply in MRP when checkbox is selected.</inlineHelpText>
        <label>Level Zero QOH as Supply</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Use_Order_Forecast_as_Demand_in_MRP__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Use Order Forecast as Demand in MRP</description>
        <inlineHelpText>MRP ignores order forecasts as demand if the checkbox is not selected.</inlineHelpText>
        <label>Order Forecast as Demand</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Use_Purchase_Orders_as_Supply_in_MRP__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Use Purchase Orders as Supply in MRP</description>
        <inlineHelpText>MRP ignores purchase orders as supply if the checkbox is not selected.</inlineHelpText>
        <label>Purchase Orders as Supply</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Use_Quantity_on_Hand_as_Supply_in_MRP__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Use Quantity on Hand as Supply in MRP</description>
        <inlineHelpText>Use Quantity on Hand as Supply in MRP: ignore Safety Stock and Negative Quantity on Hand if checkbox is not selected.</inlineHelpText>
        <label>Quantity on Hand as Supply</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Use_Sales_Orders_as_Demand_in_MRP__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Use Sales Orders as Demand in MRP</description>
        <inlineHelpText>MRP ignores sales orders as demand if checkbox is not selected.</inlineHelpText>
        <label>Sales Orders as Demand</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Use_Transfer_Orders_as_Demand_in_MRP__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Use Transfer Orders as Demand in MRP</description>
        <inlineHelpText>Use Transfer Orders as Demand in MRP</inlineHelpText>
        <label>Transfer Orders as Demand</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Use_Work_Orders_as_Demand_in_MRP__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Use Work Orders as Demand in MRP</description>
        <inlineHelpText>MRP ignores work orders as demand if the checkbox is not selected.</inlineHelpText>
        <label>Work Orders as Demand</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Use_Work_Orders_as_Supply_in_MRP__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Use Work Orders as Supply in MRP</description>
        <inlineHelpText>MRP ignores work orders as supply if the checkbox is not selected.</inlineHelpText>
        <label>Work Orders as Supply</label>
        <type>Checkbox</type>
    </fields>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Facility__c.object
<CustomObject>
    <customHelpPage>HelpFacilites</customHelpPage>
    <description>Warehouse or building</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Facilities</relationshipLabel>
        <relationshipName>Facilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MRP_Backward_Horizon_in_Days__c</fullName>
        <description>The number of days in the past from today that MRP will search for demand and supply</description>
        <inlineHelpText>Specifies the number of days in the past that MRP looks to for supply and demand.</inlineHelpText>
        <label>MRP Backward Horizon in Days</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MRP_Demand_Time_Fence_in_Days__c</fullName>
        <description>MRP uses forecasted demand outside of this time window and Sales Orders inside this time fence</description>
        <inlineHelpText>MRP uses forecast demand outside of this time fence and sales order demand inside the time fence.</inlineHelpText>
        <label>MRP Demand Time Fence in Days</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MRP_Forward_Horizon_in_Days__c</fullName>
        <description>The number of days in the future from today that MRP will search for demand and supply</description>
        <inlineHelpText>Specifies the number of days in the future that MRP looks to for supply and demand.</inlineHelpText>
        <label>MRP Forward Horizon in Days</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MRP_Planning_Time_Fence_in_Days__c</fullName>
        <description>The number of days in the future from today before MRP creates any planned make order</description>
        <inlineHelpText>MRP will not change existing planned orders within the specified period.</inlineHelpText>
        <label>MRP Planning Time Fence in Days</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Planning_Calendar2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Planning Calendar</label>
        <referenceTo>Calendar__c</referenceTo>
        <relationshipLabel>Facilities (Planning Calendar)</relationshipLabel>
        <relationshipName>Facilities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Receiving_Calendar2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Receiving Calendar</label>
        <referenceTo>Calendar__c</referenceTo>
        <relationshipLabel>Facilities (Receiving Calendar)</relationshipLabel>
        <relationshipName>Facilities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Use_Only_Level_Zero_QOH_as_Supply_in_MRP__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Level Zero QOH as Supply</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Use_Order_Forecast_as_Demand_in_MRP__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Use Order Forecast as Demand in MRP</description>
        <inlineHelpText>If not selected, MRP ignores order forecasts as demand.</inlineHelpText>
        <label>Order Forecast as Demand</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Use_Purchase_Orders_as_Supply_in_MRP__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Use Purchase Orders as Supply in MRP</description>
        <inlineHelpText>If not selected, MRP ignores purchase orders as supply.</inlineHelpText>
        <label>Purchase Orders as Supply</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Use_Quantity_on_Hand_as_Supply_in_MRP__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Use Quantity on Hand as Supply in MRP</description>
        <inlineHelpText>If not selected, MRP ignores  Safety Stock and Negative Quantity on Hand.</inlineHelpText>
        <label>Quantity on Hand as Supply</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Use_Sales_Orders_as_Demand_in_MRP__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Use Sales Orders as Demand in MRP</description>
        <inlineHelpText>If not selected, MRP ignores sales orders as demand.</inlineHelpText>
        <label>Sales Orders as Demand</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Use_Work_Orders_as_Demand_in_MRP__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Use Work Orders as Demand in MRP</description>
        <inlineHelpText>If not selected, MRP ignores work orders as demand.</inlineHelpText>
        <label>Work Orders as Demand</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Use_Work_Orders_as_Supply_in_MRP__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Use Work Orders as Supply in MRP</description>
        <inlineHelpText>If not selected, MRP ignores work orders as supply.</inlineHelpText>
        <label>Work Orders as Supply</label>
        <type>Checkbox</type>
    </fields>
    <label>Facility</label>
    <nameField>
        <label>Facility</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/MRP_Run__c.object
<CustomObject>
    <customHelpPage>HelpMRPRun</customHelpPage>
    <description>MRP Runtime Run ID and run time parameters</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Company</description>
        <inlineHelpText>Lookup to Company</inlineHelpText>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>MRP Runs</relationshipLabel>
        <relationshipName>MRP_Runs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MRP_Backward_Horizon_in_Days__c</fullName>
        <description>The number of days in the past from today that MRP will search for demand and supply</description>
        <inlineHelpText>The number of days in the past from today that MRP will search for demand and supply</inlineHelpText>
        <label>MRP Backward Horizon in Days</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MRP_Demand_Time_Fence_in_Days__c</fullName>
        <description>MRP uses forecasted demand outside of this time window and Sales Orders inside this time fence</description>
        <inlineHelpText>MRP uses forecasted demand outside of this time window and Sales Orders inside this time fence</inlineHelpText>
        <label>MRP Demand Time Fence in Days</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MRP_Forward_Horizon_in_Days__c</fullName>
        <description>The number of days in the future from today that MRP will search for demand and supply</description>
        <inlineHelpText>The number of days in the future from today that MRP will search for demand and supply</inlineHelpText>
        <label>MRP Forward Horizon in Days</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MRP_Planning_Time_Fence_in_Days__c</fullName>
        <description>The number of days in the future from today before MRP creates any planned make order</description>
        <inlineHelpText>The number of days in the future from today before MRP creates any planned make order</inlineHelpText>
        <label>MRP Planning Time Fence in Days</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Planning_Calendar2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Planning Calendar</label>
        <referenceTo>Calendar__c</referenceTo>
        <relationshipLabel>MRP Runs</relationshipLabel>
        <relationshipName>MRP_Runs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Receiving_Calendar2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Receiving Calendar</label>
        <referenceTo>Calendar__c</referenceTo>
        <relationshipLabel>MRP Runs (Receiving Calendar)</relationshipLabel>
        <relationshipName>MRP_Runs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>MRP Run</label>
    <nameField>
        <displayFormat>MRP_Run - {0000000000}</displayFormat>
        <label>MRP_Run</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MRP Runs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/GenerateMRPExtV2.cls
/**
 * GenerateMRPExtV2 : Generate the MRP for the company
 * This is accessible on the Company. 
 * 
 * Design: For generating the MRP, MRP Run is created in Salesforce
 * MRP Run id thus created will be sent to the heroku app to generate MRP records
 * MRPSettingsService will be used to block requests per company
 * 
 * Note that there is no leveling in salesforce. It happens in the heroku backend app
 * 
 */ 
public with sharing class GenerateMRPExtV2 {
    MRPSettingsService settings = new MRPSettingsService () ;
    ApexPages.StandardController con;
    Company__c cRec ; 
    
    // Enable or disable the Generate MRP button based on the MRP Settings [custom settings]
    public Boolean isButtonDisabled { get{
        
        if ( GatewayExt.isUserAuthorized() == false ) {
            ApexPages.addMessage( new ApexPages.Message ( ApexPages.Severity.FATAL , 'Please authorize for Kenandy Gateway. Goto All Tabs > Getting Around > Manage Defaults > Authorize External App > Authorize' ) ) ;
            return true;
        }
        
        // TODO Change to status Complete 
        return settings.mrp_running(cRec.Id) ;
    } set;} 
    
    public GenerateMRPExtV2 ( ApexPages.StandardController con ) { 
        this.con = con ;  
        cRec = (Company__c)con.getRecord();
    }
    
    public GenerateMRPExtV2 ( Id companyId  ) {
        try {
            SOQLUtil util = new SOQLUtil ( 'Company__c', true);
            util.addFields ( new Set<String> {
               'Planning_Calendar2__c','Receiving_Calendar2__c', 'Use_Only_Level_Zero_QOH_as_Supply_in_MRP__c', 'MRP_Backward_Horizon_in_Days__c',
               'MRP_Demand_Time_Fence_in_Days__c', 'MRP_Forward_Horizon_in_Days__c', 'MRP_Planning_Time_Fence_in_Days__c','Use_Order_Forecast_as_Demand_in_MRP__c',
               'Use_Purchase_Orders_as_Supply_in_MRP__c', 'Use_Quantity_on_Hand_as_Supply_in_MRP__c', 'Use_Sales_Orders_as_Demand_in_MRP__c',
               'Use_Work_Orders_as_Demand_in_MRP__c', 'Use_Work_Orders_as_Supply_in_MRP__c','Use_Transfer_Orders_as_Demand_in_MRP__c',
               'Use_Transfer_Orders_as_Supply_in_MRP__c'
            });
            util.setWhereClause('Id = :companyId');
            cRec = Database.query ( util.getQuery() );
        } catch ( Exception e ) {
            ApexPages.addMessage( new ApexPages.Message ( ApexPages.Severity.FATAL , MessageUtil.toFriendlyErrorMessage(e.getMessage()) ) ) ;
            system.debug(LoggingLevel.Error, 'EXCEPTION: ' + e.getMessage() + ' ' + e.getStackTraceString());
        }
        
    }
    
    // Initiates the mrp plan generate process
    public void generatePlan () {
        if (settings.mrp_running(cRec.Id )) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.FATAL, Label.MRP_is_currently_running )) ;
            return ;          
        }
        
        // Checking for running mrp processes by company
        Savepoint sp = Database.setSavepoint() ; 
        
        
        try {
            MRP_Run__c mrpRun = createMRPRun ();
            
            // send a request to the heroku backend to start the mrp generate process
            MRPService.startMRPGenerateFuture ( mrpRun.id  ) ;
            
            mrpSemaphore ();
            
            ApexPages.addMessage( new ApexPages.Message ( ApexPages.Severity.INFO , Label.BatchEmail) ) ;
            
            // TODO post to chatter, email blah blah 
        }
        catch ( Exception e ) {
            Database.rollback(sp) ;
            ApexPages.addMessage( new ApexPages.Message ( ApexPages.Severity.FATAL , MessageUtil.toFriendlyErrorMessage(e.getMessage()) ) ) ;
            system.debug(LoggingLevel.Error, 'EXCEPTION: ' + e.getMessage() + ' ' + e.getStackTraceString());
        }
    }
    
    public MRP_Run__c createMRPRun () {
        // Create a MRP Run record
        MRP_Run__c mrpRun = new MRP_Run__c();
        mrpRun.Company__c = cRec.Id;
        mrpRun.Completion_Status__c = MRPService.STATUS_RUNNING ;
        mrpRun.Facility__c = null; // TODO support for facility
        mrpRun.Failure_Message__c  = null;
        mrpRun.Planning_Calendar2__c = cRec.Planning_Calendar2__c;
        mrpRun.Receiving_Calendar2__c = cRec.Receiving_Calendar2__c;
        mrpRun.Level_Zero_QOH_as_Supply__c = cRec.Use_Only_Level_Zero_QOH_as_Supply_in_MRP__c;
        mrpRun.MRP_Backward_Horizon_in_Days__c = cRec.MRP_Backward_Horizon_in_Days__c;
        mrpRun.MRP_Demand_Time_Fence_in_Days__c = cRec.MRP_Demand_Time_Fence_in_Days__c;
        mrpRun.MRP_Forward_Horizon_in_Days__c = cRec.MRP_Forward_Horizon_in_Days__c;
        mrpRun.MRP_Planning_Time_Fence_in_Days__c = cRec.MRP_Planning_Time_Fence_in_Days__c;
        mrpRun.Order_Forecast_as_Demand__c = cRec.Use_Order_Forecast_as_Demand_in_MRP__c;
        mrpRun.Purchase_Orders_as_Supply__c = cRec.Use_Purchase_Orders_as_Supply_in_MRP__c;
        mrpRun.Quantity_on_Hand_as_Supply__c = cRec.Use_Quantity_on_Hand_as_Supply_in_MRP__c;
        mrpRun.Sales_Orders_as_Demand__c = cRec.Use_Sales_Orders_as_Demand_in_MRP__c;
        mrpRun.Work_Orders_as_Demand__c = cRec.Use_Work_Orders_as_Demand_in_MRP__c;
        mrpRun.Work_Orders_as_Supply__c = cRec.Use_Work_Orders_as_Supply_in_MRP__c;
        mrpRun.Transfer_Orders_as_Demand__c = cRec.Use_Transfer_Orders_as_Demand_in_MRP__c;
        mrpRun.Transfer_Orders_as_Supply__c = cRec.Use_Transfer_Orders_as_Supply_in_MRP__c;
        DML.insertAsUser(mrpRun);
        return mrpRun;
    }
    
    public void mrpSemaphore () {
        // block the mrp generate process on this company
        settings.mrp_start(cRec.Id);
    }
}