src-ken&y/objects/Company__c.object
<CustomObject>
    <customHelpPage>HelpCompany</customHelpPage>
    <description>Each Logistics or Financial entity will be represented by a single Company record.  Master data for the Company is recorded here and used throughout the System.</description>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Item__c.object
<CustomObject>
    <customHelpPage>HelpItems</customHelpPage>
    <description>Item Master object</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Active Item if checked; Used to phase out a item. If item is inactive, a P.O. or W.O. can not be placed against item but the QOH can be used.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company that controls this item</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Auto-generated by MRP as first step in MRP run. Buy and outsourced items are level 0; all make items depend on highest BOM assembly level.</description>
        <inlineHelpText>Auto-generated by MRP as first step in MRP run. Items that are purchased (Buy) and outsourced are level 0.</inlineHelpText>
        <label>Level</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Item_Specification__c.object
<CustomObject>
    <customHelpPage>HelpItemSpecifications</customHelpPage>
    <description>Item Specifications and Component Header</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company that this Item Specification belongs to</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Item Specfications</relationshipLabel>
        <relationshipName>Item_Specfications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Item</description>
        <inlineHelpText>Displays the list of available items.</inlineHelpText>
        <label>Item</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <filterItems>
                <field>Item__c.Non_Inventory__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>Item__c.Company__c</field>
                <operation>equals</operation>
                <valueField>$Source.Company__c</valueField>
            </filterItems>
            <filterItems>
                <field>Item__c.Company__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Item Specifications</relationshipLabel>
        <relationshipName>Item_Specifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item Specification</label>
    <nameField>
        <label>Item Specification</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Specifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/GenerateTempLevels.cls
/*Copyright Kenandy Inc
*@Author: MG
*@Description: This class is initiated from ClearItemLevels class. It updates the items to level 0 which don't exist as an assembly.
*/
public with sharing class GenerateTempLevels	implements Database.batchable<sObject>,Database.stateful {
  	//iterate through the items which doesn't exist as assembly 
  	public String query;
  	public Id companyId;
  
  	public GenerateTempLevels() {
  	    
        // PTM-705 
  	    query = 'select ID '+
  	            'from Item__c '+
  	            'where Company__c =: companyId and '+
  	            'Active__c = true and '+
  	            'ID in (select Item__c from Item_Specification__c)';
  	}
  
  	public Database.QueryLocator start(Database.BatchableContext BC) {              
        return Database.getQueryLocator(query);
  	}
    
	public void execute(Database.BatchableContext info, List<Item__c> itemList) {
	  	execute(itemList);
	}
    
    public void execute(List<Item__c> itemList){
        
        // PTM-705 	
        for(Item__c itemObj : itemList) itemObj.Level__c = 1;
      
        DML.updateAsUser(itemList);  //KNDY-3586
    }
    
    public void finish(Database.BatchableContext info){
        //initiate the next batch for next level
        // PTM-705 
        CreateNextLevel obj = new CreateNextLevel(1);
        obj.companyId=companyId; 
        Id jobId=Database.executebatch(obj,2000);
    }
}