src-ken&y/objects/Company__c.object
<CustomObject>
    <customHelpPage>HelpCompany</customHelpPage>
    <description>Each Logistics or Financial entity will be represented by a single Company record.  Master data for the Company is recorded here and used throughout the System.</description>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Recurring_Template__c.object
<CustomObject>
    <customHelpPage>HelpRecurringTemplates</customHelpPage>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Recurring Templates</relationshipLabel>
        <relationshipName>Recurring_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Recurring Template</label>
    <nameField>
        <label>Recurring Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recurring Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Recurring_Template_Line__c.object
<CustomObject>
    <customHelpPage>HelpRecurringTemplates</customHelpPage>
    <fields>
        <fullName>Amount_CR__c</fullName>
        <label>Amount CR</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Amount_DR__c</fullName>
        <label>Amount DR</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Recurring Template Lines</relationshipLabel>
        <relationshipName>Recurring_Template_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recurring_Template__c</fullName>
        <label>Recurring Template</label>
        <referenceTo>Recurring_Template__c</referenceTo>
        <relationshipLabel>Recurring Template Lines</relationshipLabel>
        <relationshipName>Recurring_Template_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Recurring Template Line</label>
    <nameField>
        <label>Recurring Template Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recurring Template Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/classes/RecurringTemplateLineService.cls
public with sharing class RecurringTemplateLineService {
	public void setOrClearInformation(List<Recurring_Template_Line__c> newRTLineList){
		if ( Trigger.isBefore && (Trigger.isInsert || Trigger.isUpdate) ) {
			Set <Id> RTIds = new Set<Id>();	
	    	if(RTIds!=null)
	    		RTIds.clear();
	
	        for(Recurring_Template_Line__c thisRT: newRTLineList){
	        	
	        	RTIds.add(thisRT.Recurring_Template__c);
	        }

			//KNDY-10473: Adding CRUD/FLS checks with SOQLUtil
			
			SOQLUtil soql = new SOQLUtil('Recurring_Template__c', true); //enforceFLS=true, running in user mode
			soql.addFields(new set<string>{
				'id','Company__c','Company__r.Name'
			});
			soql.setWhereClause('id in :RTIds');

			Map <id, Recurring_Template__c> RTHdrMap = new map <id, Recurring_Template__c>((List<Recurring_Template__c>)Database.query(soql.getQuery()));
	        										
	       	for(Recurring_Template_Line__c rtl: newRTLineList){
	        	if(RTHdrMap.containsKey(rtl.Recurring_Template__c)){
	        		rtl.Company__c = RTHdrMap.get(rtl.Recurring_Template__c).Company__c ; // get header from map
	        	}if(rtl.Amount_DR__c == null){
	        		rtl.Amount_DR__c = 0;
	        	}if(rtl.Amount_CR__c == null){
	        		rtl.Amount_CR__c = 0;
	        	}
	       	}
		}
	}
}