src-ken&y/objects/Component__c.object
<CustomObject>
    <customHelpPage>HelpItemSpecifications</customHelpPage>
    <description>Product structure details</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company this Component belongs to</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Components</relationshipLabel>
        <relationshipName>Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Routing__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Routing</description>
        <inlineHelpText>Lookup to Routing</inlineHelpText>
        <label>Routing</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Routing Assembly must match Component Assembly</errorMessage>
            <filterItems>
                <field>Routing__c.Assembly_Item_Specification__c</field>
                <operation>equals</operation>
                <valueField>$Source.Assembly_Item_Specification__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Routing__c</referenceTo>
        <relationshipLabel>Components</relationshipLabel>
        <relationshipName>Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier</label>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Components</relationshipLabel>
        <relationshipName>Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Specifies whether the component is to be kitted, backflushed, or is a by-product of previously manufactured finished goods. To account for a by-product component being used in this assembly,  specify the Quantity Per Assembly as a negative amount.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Kit</fullName>
                </value>
                <value>
                    <fullName>Backflush</fullName>
                </value>
                <value>
                    <fullName>By-product</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Component</label>
    <nameField>
        <label>Component</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Item__c.object
<CustomObject>
    <customHelpPage>HelpItems</customHelpPage>
    <description>Item Master object</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company that controls this item</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Item description can be up to 255 characters; use extended description field if needed</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Non_Inventory__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates that this Item will not be tracked as inventory in the system, used for Expense or Misc items.</description>
        <inlineHelpText>A check mark indicates that the item is be tracked as inventory in the system. Non-inventory items are used for Expense or Misc items.</inlineHelpText>
        <label>Non Inventory</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <inlineHelpText>The source of the item. Click &quot;Help for this Page&quot; for information about the different item sources in Kenandy.</inlineHelpText>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Purchased</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Manufactured</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous</fullName>
                </value>
                <value>
                    <fullName>Phantom</fullName>
                </value>
                <value>
                    <fullName>Expense</fullName>
                </value>
                <value>
                    <fullName>Kit</fullName>
                </value>
                <value>
                    <fullName>Outside Processing</fullName>
                </value>
                <value>
                    <fullName>One Time Charge</fullName>
                </value>
                <value>
                    <fullName>Build To Order</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to supplier</description>
        <label>Supplier</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Item&apos;s Supplier must be of type Purchase From</errorMessage>
            <filterItems>
                <field>Supplier__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Purchase From</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Items (Supplier)</relationshipLabel>
        <relationshipName>Items1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Material_Tracking__c.object
<CustomObject>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Material Trackings</relationshipLabel>
        <relationshipName>Material_Trackings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Operation_Tracking__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Operation Tracking</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Operation_Tracking__c.Work_Order__c</field>
                <operation>equals</operation>
                <valueField>$Source.Work_Order__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Operation_Tracking__c</referenceTo>
        <relationshipLabel>Material Trackings</relationshipLabel>
        <relationshipName>Material_Trackings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier</label>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Material Trackings</relationshipLabel>
        <relationshipName>Material_Trackings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Kit</fullName>
                </value>
                <value>
                    <fullName>Backflush</fullName>
                </value>
                <value>
                    <fullName>By-product</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Work_Order__c</fullName>
        <label>Work Order</label>
        <referenceTo>Work_Order__c</referenceTo>
        <relationshipLabel>Material Trackings</relationshipLabel>
        <relationshipName>Material_Trackings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Material Tracking</label>
    <nameField>
        <displayFormat>MT-{0000000000}</displayFormat>
        <label>Material Tracking</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Material Trackings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Operation_Tracking__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Routing__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Routing</label>
        <referenceTo>Routing__c</referenceTo>
        <relationshipLabel>Operation Trackings</relationshipLabel>
        <relationshipName>Operation_Trackings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Work_Order__c</fullName>
        <label>Work Order</label>
        <referenceTo>Work_Order__c</referenceTo>
        <relationshipLabel>Operation Trackings</relationshipLabel>
        <relationshipName>Operation_Trackings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Operation Tracking</label>
    <nameField>
        <label>Operation Tracking</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Operation Trackings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Routing__c.object
<CustomObject>
    <customHelpPage>HelpWorkOrder</customHelpPage>
    <description>Routing Detail object:  contains the detailed operations required to make an Assembly</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company this routing belongs to</description>
        <inlineHelpText>Company this routing belongs to. After a routing has been created, you cannot change the company.</inlineHelpText>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Routings</relationshipLabel>
        <relationshipName>Routings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Routing</label>
    <nameField>
        <label>Routing</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Supplier__c.object
<CustomObject>
    <customHelpPage>HelpSuppliers</customHelpPage>
    <description>Supplier object</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Suppliers</relationshipLabel>
        <relationshipName>Suppliers1_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>The type of supplier record.</description>
        <inlineHelpText>Type of supplier record. Options include: Purchasing and Remit-To.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Parent</fullName>
                </value>
                <value>
                    <fullName>Purchasing</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Remit-To</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Supplier</label>
    <nameField>
        <label>Supplier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Work_Order__c.object
<CustomObject>
    <customHelpPage>HelpWorkOrder</customHelpPage>
    <description>All work orders including planned orders from MRP as well as unplanned orders.</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company this Work Order belongs to</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Item</description>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Work Order</label>
    <nameField>
        <label>Work Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/ComponentTriggerHandler.cls
public with sharing class ComponentTriggerHandler {
    public static void afterInsert() { validateOSP(Trigger.new); }
    public static void afterUpdate() { validateOSP(Trigger.new); }

    public static void validateOSP(List<sObject> components) {
        sObjectType objType;
        String itemField;
        String operationField;
        String companyField;
        Map<Id,Id> itemIds = new Map<Id,Id>();
        Set<Id> woIds = new Set<Id>();
        for (sObject component:components) {
            objType = component.getSObjectType();
            if (objType == Component__c.sObjectType) {
                itemField = 'Component_Item__';
                operationField = 'Routing__c';
                companyField = 'Company__r';
            } else {
                itemField = 'Item__';
                operationField = 'Operation_Tracking__c';
                companyField = 'Work_Order__r.Company__r';
                woIds.add((Id)component.get('Work_Order__c'));
            }
            itemIds.put(component.Id,(Id)component.get(itemField + 'c'));
        }

        SOQLUtil itemQuery = new SOQLUtil('Item__c');
        itemQuery.addFields(new Set<String>{ 'Id','Name','Source__c','Supplier__c','Description__c','Non_Inventory__c'});
        itemQuery.setWhereClause('Id IN (\'' + String.join(itemIds.values(),'\',\'') + '\')');
        Map<Id,Item__c> items = new Map<Id,Item__c>((List<Item__c>)Database.query(itemQuery.getQuery()));

        Map<Id,Id> lastOperations = new Map<Id,Id>();
        if (woIds.size() > 0) {
            SOQLUtil opQuery = new SOQLUtil('Operation_Tracking__c');
            opQuery.addFields(new Set<String>{ 'Id','Name','Sequence__c','Work_Order__c' });
            opQuery.setWhereClause('Work_Order__c IN :woIds');
            opQuery.setOrderByClause('Sequence__c DESC');
            for (Operation_Tracking__c op:Database.query(opQuery.getQuery())) {
                if (!lastOperations.containsKey(op.Work_Order__c)) {
                    lastOperations.put(op.Work_Order__c,op.Id);
                }
            }
        }

        Set<Id> operationIds = new Set<Id>();
        for (sObject component:components) {
            Item__c item = items.get(itemIds.get(component.Id));

            if (item.Source__c == ItemService.ITEM_SOURCE_OSP) {
                if ((String)component.get('Type__c') != WorkOrderService.MATERIAL_TYPE_BACKFLUSH && (String)component.get('Type__c') != WorkOrderService.MATERIAL_TYPE_KIT) {
                    component.addError(item.Name + ': Outside processing components must be of type backflush or kit');
                    return;
                }
                if (component.get(operationField) == null) {
                    component.addError(item.Name + ': Outside processing components must be associated with a routing/operation');
                    return;
                }
                if (objType == Material_Tracking__c.sObjectType && lastOperations.get((Id)component.get('Work_Order__c')) == (Id)component.get(operationField)) {
                    component.addError(item.Name + ': Outside processing components cannot be associated with the last operation');
                    return;
                }
                if(objType == Component__c.sObjectType && component.get('Supplier__c') == null || component.get('Supplier__c') == ''){
                	component.addError(item.Name + ': You can’t create an outside processing component without a supplier.');
                    return;
                }
                else if(objType == Material_Tracking__c.sObjectType && component.get('Supplier__c') == null || component.get('Supplier__c') == ''){
                	component.addError(item.Name + ': You can’t create an outside processing material tracking  without a supplier.');
                    return;
                }
                if(objType == Component__c.sObjectType && ((Decimal)component.get('Quantity_per_Assembly__c') >1 || (Decimal)component.get('Quantity_per_Assembly__c') <1)){
                	component.addError(item.Name + ': Quantity per Assembly cannot be greater/less than 1 for an outside processing item.');
                    return;
                }
            }

            if (component.get(operationField) != null) {
                operationIds.add((Id)component.get(operationField));
            }
        }

        if (operationIds.size() > 0) {
            SOQLUtil operationQuery = new SOQLUtil(operationField);
            operationQuery.addFields(new Set<String>{ 'Id','Name' });
            operationQuery.setWhereClause('Id IN :operationIds');

            SOQLUtil.ChildRelationship componentSubquery = objType == Component__c.sObjectType ? new SOQLUtil.ChildRelationship(operationQuery,'Components__r') : new SOQLUtil.ChildRelationship(operationQuery,'Material_Trackings__r');
            componentSubquery.addFields(new Set<String>{ 'Id','Name','Type__c',itemField + 'c','Supplier__c',itemField + 'r.Source__c',companyField + '.Serial_Control__c',itemField + 'r.Item_Attribute__c',itemField + 'r.Item_Attribute__r.Serial_Number__c' });
            if(objType == Component__c.sObjectType){
            	componentSubquery.addFields(new Set<String>{ 'Routing__c'});
            }
            else{
            	componentSubquery.addFields(new Set<String>{'Operation_Tracking__c'});
            }
            operationQuery.addChildRelationship(componentSubquery);
			List<sObject> operations = Database.query(operationQuery.getQuery());
			
            for (sObject operation:operations) {
                Boolean ospFound = false;
                Boolean bpFound = false;
                Boolean serialItemFound = false;
                List<sObject> componentList = objType == Component__c.sObjectType ? operation.getSObjects('Components__r') : operation.getSObjects('Material_Trackings__r');
                Map<Id,sObject> ospSuppliermap = new Map<Id,sObject>();
				Map<String,Id> routingOpItemmap = new Map<String,Id>();
                		
                for (sObject component:componentList) {
                    String serialControl;
                    String key = '';
                    sObject curObj = component;
                    for (String companyPart:companyField.split('\\.')) {
                        curObj = curObj.getSObject(companyPart);
                    }

                    if ((String)component.get('Type__c') == WorkOrderService.MATERIAL_TYPE_BYPRODUCT) {
                        bpFound = true;
                    }

                    if ((String)component.getSObject(itemField + 'r').get('Source__c') == ItemService.ITEM_SOURCE_OSP) {
                    	key = (Id)component.get('Supplier__c');
                    	if(!ospSuppliermap.containskey(key)){
							ospSuppliermap.put(key,component);
						}
						else if (ospSuppliermap.containskey(key)) {
							components[0].addError((String)operation.get('Name') + ': You can’t choose same supplier on a outside processing component associated to same routing/operation.');
                            return;
                        }
                        Id rkey;
                        if(objType == Component__c.sObjectType){
                        	rkey = (Id)component.get('Routing__c');
                        }
                        else if(objType != Component__c.sObjectType){
                        	rkey = (Id)component.get('Operation_Tracking__c');
                        }
                        
                        if(!routingOpItemmap.containskey(rkey)){
                        	routingOpItemmap.put(rkey,(Id)component.get(itemField + 'c'));
                        }		
                        
                        

                        ospFound = true;
                    } else if ((String)curObj.get('Serial_Control__c') == SkidService3.AT_RECEIPT && component.getSObject(itemField + 'r').get('Item_Attribute__c') != null && (Boolean)component.getSObject(itemField + 'r').getSObject('Item_Attribute__r').get('Serial_Number__c')) {
                        serialItemFound = true;
                    }
                }
                if (ospFound) {
                    if (bpFound) {
                        components[0].addError((String)operation.get('Name') + ': Outside processing components and byproduct components cannot be associated with the same routing/operation');
                        return;
                    }
                    if (serialItemFound) {
                        components[0].addError((String)operation.get('Name') + ': Outside processing components and serialized components cannot be associated with the same routing/operation');
                        return;
                    }
                }
            }
        }
    }


    public static void beforeInsert() { }
    public static void beforeUpdate() { }
    public static void beforeDelete() { }
    public static void afterDelete() { }
    public static void afterUndelete() { }
}