src-ken&y/objects/Company__c.object
<CustomObject>
    <customHelpPage>HelpCompany</customHelpPage>
    <description>Each Logistics or Financial entity will be represented by a single Company record.  Master data for the Company is recorded here and used throughout the System.</description>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Configuration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>(Name, Value) pairs, holds configuration switches for fine tuning subsystems</description>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Configuration</label>
</CustomObject>

src-ken&y/objects/Process_Job__c.object
<CustomObject>
    <customHelpPage>HelpProcessJobs</customHelpPage>
    <description>Establish and manage scheduled jobs to run at various hours or frequencies</description>
    <fields>
        <fullName>Batch_Size__c</fullName>
        <defaultValue>25</defaultValue>
        <description>The number of records for each execution of the batch.</description>
        <inlineHelpText>The number of records for each execution of the batch.</inlineHelpText>
        <label>Batch Size</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The company that will be used for the input parameter to the job</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Process Jobs</relationshipLabel>
        <relationshipName>Process_Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Process Job</label>
    <nameField>
        <label>Process Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Purchase_Order__c.object
<CustomObject>
    <customHelpPage>HelpPurchaseOrders</customHelpPage>
    <description>Purchase header information</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Logistics or Financial company that this PO will be owned by</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Memo__c</fullName>
        <label>Memo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the Purchase Order;  PO will be kept on file after beng closed until company runs a maintenance transaction to backup and purge closed and cancelled purchase orders</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Supplier</description>
        <label>Purchase From Supplier</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Supplier__c.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <filterItems>
                <field>Supplier__c.Hold_Purchasing__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>Supplier__c.Type__c</field>
                <operation>equals</operation>
                <value>Purchasing</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Purchase Orders (Supplier)</relationshipLabel>
        <relationshipName>Purchase_Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Purchase Order</label>
    <nameField>
        <label>Purchase Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Supplier__c.object
<CustomObject>
    <customHelpPage>HelpSuppliers</customHelpPage>
    <description>Supplier object</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Suppliers</relationshipLabel>
        <relationshipName>Suppliers1_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Supplier Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Supplier</label>
    <nameField>
        <label>Supplier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Supplier_Invoice__c.object
<CustomObject>
    <customHelpPage>HelpSupplierInvoice</customHelpPage>
    <description>Record invoices for items or services  that are received from a supplier.  Bills can be recorded with or without purchase orders</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Supplier Invoices</relationshipLabel>
        <relationshipName>Supplier_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Invoiced__c</fullName>
        <description>Date when the invoice happened</description>
        <label>Invoice Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Hold__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates this invoice is on hold</description>
        <label>Hold</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoice_Amount__c</fullName>
        <inlineHelpText>The invoice amount is required. Invoice cannot be approved for payment if the invoice amount does not match the total amount on each line of the invoice.</inlineHelpText>
        <label>Invoice Amount</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoice_Type__c</fullName>
        <label>Invoice Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Credit Memo</fullName>
                </value>
                <value>
                    <fullName>Invoice</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Prepayment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Visited_By_Batch__c</fullName>
        <description>This field is used to keep track of the time that this invoice was picked up by the SI Draft Inspect batch process.</description>
        <label>Last Visited By Batch</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Memo__c</fullName>
        <description>Add memo to explain discrepancies. For example, if an item is short paid because the supplier has incorrectly put a charge enter reason in the memo.</description>
        <label>Memo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Purchase_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Purchase Order.</description>
        <label>Purchase Order</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Purchase_Order__c.Supplier__c</field>
                <operation>equals</operation>
                <valueField>$Source.Supplier__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Purchase_Order__c</referenceTo>
        <relationshipLabel>Supplier Invoices</relationshipLabel>
        <relationshipName>Supplier_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of bill</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supplier_Invoice__c</fullName>
        <description>Supplier invoice no. reference</description>
        <label>Invoice Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Remit To Supplier</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Supplier__c.Type__c</field>
                <operation>equals</operation>
                <value>Remit-To</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Supplier Invoices</relationshipLabel>
        <relationshipName>Supplier_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Extended_Price__c</fullName>
        <description>Rollup of the line extended prices</description>
        <label>Total Extended Price</label>
        <summarizedField>Supplier_Invoice_Line__c.Extended_Price__c</summarizedField>
        <summaryForeignKey>Supplier_Invoice_Line__c.Supplier_Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Visited_Last_By_Batch__c</fullName>
        <formula>IF(OR(LastModifiedDate - Last_Visited_By_Batch__c != 0, ISNULL(Last_Visited_By_Batch__c), ISBLANK(Last_Visited_By_Batch__c)), FALSE, TRUE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Visited Last By Batch</label>
        <type>Checkbox</type>
    </fields>
    <label>Supplier Invoice</label>
    <nameField>
        <label>Supplier Invoice</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/SupplierInvoiceDraftInspectBatch.cls
public with sharing class SupplierInvoiceDraftInspectBatch implements Database.Batchable<sObject>, Process.Runnable2, Database.Stateful{
	public Id companyId;
    public List<Notify.Message> messages = new List<Notify.Message>();
    public string query;
    public Boolean hasTax = false;
    public SupplierInvoiceDraftInspectBatch (Id comp){
        companyId = comp;
        
    }
    
    public Database.QueryLocator start(Database.BatchableContext BC){
       
        //PTP-420 CreatedDate < 1 hr or SystemModstamp < 1 hr or Last visited by date > maxTimeIntervalBetweenBatchRuns; use this Int/long in the query below.
        Integer maxTimeIntervalBetweenBatchRuns = 12; 
		Configuration__c c = Configuration__c.getValues('SIBatchMaxIntervalTime'); //Custom setting that dictates the max interval time elapsed before looking at the said invoice again
		if (c != null) {
			maxTimeIntervalBetweenBatchRuns = Integer.valueOf(c.Value__c);
		}

        DateTime maxIntervalHourDT=system.now().addHours(-maxTimeIntervalBetweenBatchRuns) ;
         
    	query =	'Select Id, Name, Invoice_Type__c, Company__c, Supplier__c, Date_Invoiced__c, Supplier_Invoice__c, Memo__c, Invoice_Amount__c, Total_Extended_Price__c, Status__c,'+ 
				' Purchase_Order__c, Purchase_Order__r.Supplier__c '+
				' From Supplier_Invoice__c where Status__c = \'Draft\' and Hold__c = false and Company__c = :companyId AND (Visited_Last_By_Batch__c = false OR Last_Visited_By_Batch__c < :maxIntervalHourDT)'; 
 	
    	return Database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext BC, List<Supplier_Invoice__c> scope){
        system.debug('scope for SupplierInvoiceDraftInspectBatch---> '+scope);
    	Savepoint sp = Database.setSavepoint(); //KNDY-2336
    	TaxService taxSvc = TaxService.getInstance();
    	Integer taxRecSize = 0; 
     
    	for(Supplier_Invoice__c eachSI: scope){ //KNDY-2869 capturing the record ids and including it in the failure msg
    		if(taxSvc.taxServiceConfigured(Supplier_Invoice__c.getSobjectType().getDescribe().getLocalName(), eachSI)==true){
                 taxRecSize++;
            } 
    	}
    	hasTax = taxRecSize>0 ? true : false ;
    	 
        try{
        	SupplierInvoiceService.inspectDraftInvoices(scope, BC.getJobId());
        }catch(Exception e) {
            Database.rollback(sp);
            messages.add(Notify.getErrorMessage(scope, e.getMessage(), e.getStackTraceString()));
        }
    }
    
    public void finish(Database.BatchableContext info){
		BatchToChatter.processBatchInformation(info.getJobId(), this, messages);
		Notify.sendEmailBatchFinish( null, messages, info);    
		
        if(hasTax==true){
            MasterControlProgram.finishedBatch( this ); 
            Database.executeBatch(new SupplierInvoicePostInspectBatch(info.getJobId()),50);
        }else {  MasterControlProgram.finishedBatch( this );  }
        //Boolean hasTax = taxSvc.taxServiceConfigured(Supplier_Invoice__c.getSobjectType().getDescribe().getLocalName(), companyId);
        
        ///if(hasTax == true){
			//MasterControlProgram.finishedBatch( this ); 
            //Database.executeBatch(new SupplierInvoicePostInspectBatch(info.getJobId()),50);
        //}else{
          //  MasterControlProgram.finishedBatch( this ); 
      // }
    }
 
 	/* implementation of Runnable 
 	 */
 	public SupplierInvoiceDraftInspectBatch() {}
 	public void runBatch( Process_Job__c job ) {
		integer defaultBatchSize = 5;
		if ( job.Batch_Size__c !=null && integer.valueOf(job.Batch_Size__c) <= 20 && integer.valueOf(job.Batch_Size__c) >= 1 ) { 
			defaultBatchSize = integer.valueOf(job.Batch_Size__c);
		}
		
		SupplierInvoiceDraftInspectBatch batch = new SupplierInvoiceDraftInspectBatch(job.Company__c);
        ID jobId = Database.executeBatch(batch, defaultBatchSize); 
	}  
}