src-ken&y/objects/Company__c.object
<CustomObject>
    <customHelpPage>HelpCompany</customHelpPage>
    <description>Each Logistics or Financial entity will be represented by a single Company record.  Master data for the Company is recorded here and used throughout the System.</description>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Product__c.object
<CustomObject>
    <customHelpPage>HelpProducts</customHelpPage>
    <description>Products are sellable Items with Selling Unit of Measure included</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Product&apos;s description</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Weight_UOM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Products weight unit of measure</description>
        <label>Weight UOM</label>
        <referenceTo>UOM__c</referenceTo>
        <relationshipLabel>Products (Weight UOM)</relationshipLabel>
        <relationshipName>Products1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Sales_Order__c.object
<CustomObject>
    <customHelpPage>HelpSalesOrders_Managing</customHelpPage>
    <description>Sales Order Header</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Required_Date__c</fullName>
        <description>Default required date for sales order lines.</description>
        <label>Need Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ship_From_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Ship From Location</description>
        <label>Ship From Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Order_Volume__c</fullName>
        <description>Total of order volume of all order lines</description>
        <label>Total Order Volume</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Weight_UOM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Weight UOM</label>
        <referenceTo>UOM__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Sales_Order_Line__c.object
<CustomObject>
    <customHelpPage>HelpSalesOrders_Managing</customHelpPage>
    <description>Line Items on the Sales Order.</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company passed down from the sales order header</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>If item is misc, a description is required; if item is not misc, add additional information as needed. The description will be entered automatically on sales orders, shipping, and invoicing documents.</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Discount_Percent__c</fullName>
        <description>Discount allowed for this item</description>
        <inlineHelpText>Maximum discount allowed for this item.</inlineHelpText>
        <label>Discount Percent</label>
        <precision>9</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Product</description>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <filterItems>
                <field>Product__c.Item__r.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Product__c.Company__c</field>
                <operation>equals</operation>
                <valueField>$Source.Company__c</valueField>
            </filterItems>
            <filterItems>
                <field>Product__c.Company__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity_Ordered__c</fullName>
        <description>The number of items ordered in this sales order line</description>
        <label>Quantity Ordered</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Required_Date__c</fullName>
        <defaultValue>today( )</defaultValue>
        <description>Date the customer requires the line item</description>
        <label>Need Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <label>Sales Order</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Company does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>Sales_Order__c.Company__c</field>
                <operation>equals</operation>
                <valueField>$Source.Company__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Sales_Order__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ship_From_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Location</description>
        <label>Ship From Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Sales Order Line Ship From Location value does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>Location__c.Facility__r.Company__c</field>
                <operation>equals</operation>
                <valueField>$Source.Company__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Sales Order Lines (Ship From Location)</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Weight_UOM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Weight UOM</label>
        <referenceTo>UOM__c</referenceTo>
        <relationshipLabel>Sales Order Lines (Weight UOM)</relationshipLabel>
        <relationshipName>Sales_Order_Lines1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <label>Sales Order Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/classes/RollUpSummaryUtilityTest.cls
@isTest
private class RollUpSummaryUtilityTest {

 
    static testMethod void RollUpSummaryUtility_UnitTest() {
 
             TestData data = new TestData(); 
             Sales_Order_Line__c salesOrderLine1 = data.SalesOrderLines[0];
             Sales_Order_Line__c salesOrderLine2 = data.SalesOrderLines[1];
             List<sObject> SalesOrderLines = (List<Sobject>) data.SalesOrderLines;

            Sales_Order_Line__c SalesOrderLine = new Sales_Order_Line__c();
            SalesOrderLine.Product__c = data.product.Id;
            SalesOrderLine.Description__c = data.product.Description__c;
            SalesOrderLine.Company__c = data.company.id;
            SalesOrderLine.Sales_Order__c = null;
            SalesOrderLine.Quantity_Ordered__c = 100;
            SalesOrderLine.Required_Date__c = System.today()+5;
            SalesOrderLine.Weight_UOM__c = data.uomList[0].ID;
            SalesOrderLine.Discount_Percent__c = 2;
            SalesOrderLine.Ship_From_Location__c = data.location10.ID;

             
             Sales_Order__c salesorder = data.SalesOrder;

            Test.startTest();
            system.assert( salesOrderLine1.id != null , ' expected valid sales order lines');
            system.assert( salesOrderLine2.id != null , ' expected valid sales order lines');
            system.assert( salesOrderLines != null );
            
            list<RollUpSummaryUtility.fieldDefinition> fieldDefinitions = 
            new list<RollUpSummaryUtility.fieldDefinition> {
                new RollUpSummaryUtility.fieldDefinition('SUM', 'Discount_Percent__c', 'Total_Order_Volume__c')};
            
                        
            SalesOrderLines.add( SalesOrderLine);        
            RollUpSummaryUtility.rollUpTrigger(fieldDefinitions, SalesOrderLines, 'Sales_Order_Line__c', 'Sales_Order__c', 'Sales_Order__c', '');
            
            system.assertEquals( salesOrderLine1.Discount_Percent__c, 2);
            system.assertEquals( salesOrderLine2.Discount_Percent__c, 2);

            salesOrder = [Select Total_Order_Volume__c From Sales_Order__c where id=:salesOrder.id limit 1];
                    
            system.assertEquals( salesOrder.Total_Order_Volume__c, 4);

 
    }
 
}