src-ken&y/objects/Company__c.object
<CustomObject>
    <customHelpPage>HelpCompany</customHelpPage>
    <description>Each Logistics or Financial entity will be represented by a single Company record.  Master data for the Company is recorded here and used throughout the System.</description>
    <fields>
        <fullName>MRP_Backward_Horizon_in_Days__c</fullName>
        <description>The number of days in the past from today that MRP will search for demand and supply</description>
        <inlineHelpText>Specifies the number of days in the past that MRP looks to for supply and demand.</inlineHelpText>
        <label>MRP Backward Horizon in Days</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MRP_Demand_Time_Fence_in_Days__c</fullName>
        <description>MRP uses forecasted demand outside of this time window and Sales Orders inside this time fence</description>
        <inlineHelpText>MRP uses forecast demand outside of this time fence and sales order demand inside the time fence.</inlineHelpText>
        <label>MRP Demand Time Fence in Days</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MRP_Forward_Horizon_in_Days__c</fullName>
        <description>The number of days in the future from today that MRP will search for demand and supply</description>
        <inlineHelpText>Specifies the number of days in the future that MRP looks to for supply and demand.</inlineHelpText>
        <label>MRP Forward Horizon in Days</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MRP_Planning_Time_Fence_in_Days__c</fullName>
        <description>The number of days in the future from today before MRP creates any planned make order</description>
        <inlineHelpText>MRP will not change existing planned orders within the specified period.</inlineHelpText>
        <label>MRP Planning Time Fence in Days</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Planning_Calendar__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The business hours used to plan the orders generated through MRP.</description>
        <label>Planning Calendar</label>
        <referenceTo>BusinessHours</referenceTo>
        <relationshipName>Companies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Receiving_Calendar__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Receiving Calendar</label>
        <referenceTo>BusinessHours</referenceTo>
        <relationshipLabel>Companies (Receiving Calendat)</relationshipLabel>
        <relationshipName>Companies1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Use_Only_Level_Zero_QOH_as_Supply_in_MRP__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Use Only Level Zero QOH as Supply in MRP when checkbox is selected.</inlineHelpText>
        <label>Level Zero QOH as Supply</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Use_Order_Forecast_as_Demand_in_MRP__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Use Order Forecast as Demand in MRP</description>
        <inlineHelpText>MRP ignores order forecasts as demand if the checkbox is not selected.</inlineHelpText>
        <label>Order Forecast as Demand</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Use_Purchase_Orders_as_Supply_in_MRP__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Use Purchase Orders as Supply in MRP</description>
        <inlineHelpText>MRP ignores purchase orders as supply if the checkbox is not selected.</inlineHelpText>
        <label>Purchase Orders as Supply</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Use_Quantity_on_Hand_as_Supply_in_MRP__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Use Quantity on Hand as Supply in MRP</description>
        <inlineHelpText>Use Quantity on Hand as Supply in MRP: ignore Safety Stock and Negative Quantity on Hand if checkbox is not selected.</inlineHelpText>
        <label>Quantity on Hand as Supply</label>
        <type>Checkbox</type>
    </fields>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Facility__c.object
<CustomObject>
    <customHelpPage>HelpFacilites</customHelpPage>
    <description>Warehouse or building</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Facilities</relationshipLabel>
        <relationshipName>Facilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MRP_Backward_Horizon_in_Days__c</fullName>
        <description>The number of days in the past from today that MRP will search for demand and supply</description>
        <inlineHelpText>Specifies the number of days in the past that MRP looks to for supply and demand.</inlineHelpText>
        <label>MRP Backward Horizon in Days</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MRP_Demand_Time_Fence_in_Days__c</fullName>
        <description>MRP uses forecasted demand outside of this time window and Sales Orders inside this time fence</description>
        <inlineHelpText>MRP uses forecast demand outside of this time fence and sales order demand inside the time fence.</inlineHelpText>
        <label>MRP Demand Time Fence in Days</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MRP_Forward_Horizon_in_Days__c</fullName>
        <description>The number of days in the future from today that MRP will search for demand and supply</description>
        <inlineHelpText>Specifies the number of days in the future that MRP looks to for supply and demand.</inlineHelpText>
        <label>MRP Forward Horizon in Days</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MRP_Planning_Time_Fence_in_Days__c</fullName>
        <description>The number of days in the future from today before MRP creates any planned make order</description>
        <inlineHelpText>MRP will not change existing planned orders within the specified period.</inlineHelpText>
        <label>MRP Planning Time Fence in Days</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Planning_Calendar__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The business hours calendar used to determine when the facility is open to plan orders.</description>
        <label>Planning Calendar</label>
        <referenceTo>BusinessHours</referenceTo>
        <relationshipName>Facilities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Use_Only_Level_Zero_QOH_as_Supply_in_MRP__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Level Zero QOH as Supply</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Use_Order_Forecast_as_Demand_in_MRP__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Use Order Forecast as Demand in MRP</description>
        <inlineHelpText>If not selected, MRP ignores order forecasts as demand.</inlineHelpText>
        <label>Order Forecast as Demand</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Use_Purchase_Orders_as_Supply_in_MRP__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Use Purchase Orders as Supply in MRP</description>
        <inlineHelpText>If not selected, MRP ignores purchase orders as supply.</inlineHelpText>
        <label>Purchase Orders as Supply</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Use_Quantity_on_Hand_as_Supply_in_MRP__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Use Quantity on Hand as Supply in MRP</description>
        <inlineHelpText>If not selected, MRP ignores  Safety Stock and Negative Quantity on Hand.</inlineHelpText>
        <label>Quantity on Hand as Supply</label>
        <type>Checkbox</type>
    </fields>
    <label>Facility</label>
    <nameField>
        <label>Facility</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/MRP_Run__c.object
<CustomObject>
    <customHelpPage>HelpMRPRun</customHelpPage>
    <description>MRP Runtime Run ID and run time parameters</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Company</description>
        <inlineHelpText>Lookup to Company</inlineHelpText>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>MRP Runs</relationshipLabel>
        <relationshipName>MRP_Runs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Completion_Status__c</fullName>
        <description>Indicates whether the MRP completed with Success or Failure</description>
        <inlineHelpText>Indicates whether the MRP completed with Success or Failure</inlineHelpText>
        <label>Completion Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Facility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Facility</description>
        <inlineHelpText>Lookup to Facility</inlineHelpText>
        <label>Facility</label>
        <referenceTo>Facility__c</referenceTo>
        <relationshipLabel>MRP Runs</relationshipLabel>
        <relationshipName>MRP_Runs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Failure_Message__c</fullName>
        <description>If the MRP failed to complete this is the message received from the system.</description>
        <inlineHelpText>If the MRP failed to complete this is the message received from the system.</inlineHelpText>
        <label>Failure Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Level_Zero_QOH_as_Supply__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Use Only Level Zero Item&apos;s Quantity On Hand as Supply in MRP</description>
        <inlineHelpText>Use Only Level Zero Item&apos;s Quantity On Hand as Supply in MRP</inlineHelpText>
        <label>Level Zero QOH as Supply</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MRP_Backward_Horizon_in_Days__c</fullName>
        <description>The number of days in the past from today that MRP will search for demand and supply</description>
        <inlineHelpText>The number of days in the past from today that MRP will search for demand and supply</inlineHelpText>
        <label>MRP Backward Horizon in Days</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MRP_Demand_Time_Fence_in_Days__c</fullName>
        <description>MRP uses forecasted demand outside of this time window and Sales Orders inside this time fence</description>
        <inlineHelpText>MRP uses forecasted demand outside of this time window and Sales Orders inside this time fence</inlineHelpText>
        <label>MRP Demand Time Fence in Days</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MRP_Forward_Horizon_in_Days__c</fullName>
        <description>The number of days in the future from today that MRP will search for demand and supply</description>
        <inlineHelpText>The number of days in the future from today that MRP will search for demand and supply</inlineHelpText>
        <label>MRP Forward Horizon in Days</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MRP_Planning_Time_Fence_in_Days__c</fullName>
        <description>The number of days in the future from today before MRP creates any planned make order</description>
        <inlineHelpText>The number of days in the future from today before MRP creates any planned make order</inlineHelpText>
        <label>MRP Planning Time Fence in Days</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order_Forecast_as_Demand__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Use Order Forecast as Demand in MRP</description>
        <inlineHelpText>Use Order Forecast as Demand in MRP</inlineHelpText>
        <label>Order Forecast as Demand</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Planning_Calendar__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Business Hours</description>
        <inlineHelpText>Lookup to Business Hours</inlineHelpText>
        <label>Planning Calendar</label>
        <referenceTo>BusinessHours</referenceTo>
        <relationshipName>MRP_Runs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purchase_Orders_as_Supply__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Use Purchase Orders as Supply in MRP</description>
        <inlineHelpText>Use Purchase Orders as Supply in MRP</inlineHelpText>
        <label>Purchase Orders as Supply</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Quantity_on_Hand_as_Supply__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Use Quantity on Hand as Supply in MRP</description>
        <inlineHelpText>Use Quantity on Hand as Supply in MRP</inlineHelpText>
        <label>Quantity on Hand as Supply</label>
        <type>Checkbox</type>
    </fields>
    <label>MRP Run</label>
    <nameField>
        <displayFormat>MRP_Run - {0000000000}</displayFormat>
        <label>MRP_Run</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MRP Runs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/GenerateMRPExt.cls
public with sharing class GenerateMRPExt  {
    public  Id companyId { get;set;}
    public  ID facilityID { get;set;}
    public boolean runLeveling {get; set; } { runLeveling = false; } 
    public boolean runPlanning {get; set; } { runPlanning = false; }
    MRPSettingsService MRPService = new MRPSettingsService();
    Company__c cRec = new Company__c();
    
    ApexPages.StandardController con;
    
    public GenerateMRPExt(ApexPages.StandardController controller) {     
        con = controller; 
        //PTM-440 move retrival of company id to constructor
        cRec = (Company__c)con.getRecord();
        companyID = cRec.ID;
        facilityID = null;
    }
    
    public GenerateMRPExt() { }
     
    public void generatePlan () {  // planning , phase 2
    
        ID PcalID, RcalID;
    
    //  PTM-153 combine Facility and Company ID to allow simultaneous Facility MRPs to run
        String cfID = companyID;
        if (MRPService.mrp_running(cfId)) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.FATAL, Label.MRP_is_currently_running));            
            return;
        }

        MRP_Run__c mrpRun = new MRP_Run__c();
        mrpRun.Company__c = companyID;
        mrpRun.Completion_Status__c = 'Running';
        mrpRun.Facility__c = null;
        mrpRun.Failure_Message__c  = null;
        mrpRun.Level_Zero_QOH_as_Supply__c = cRec.Use_Only_Level_Zero_QOH_as_Supply_in_MRP__c;
        mrpRun.MRP_Backward_Horizon_in_Days__c = cRec.MRP_Backward_Horizon_in_Days__c;
        mrpRun.MRP_Demand_Time_Fence_in_Days__c = cRec.MRP_Demand_Time_Fence_in_Days__c;
        mrpRun.MRP_Forward_Horizon_in_Days__c = cRec.MRP_Forward_Horizon_in_Days__c;
        mrpRun.MRP_Planning_Time_Fence_in_Days__c = cRec.MRP_Planning_Time_Fence_in_Days__c;
        mrpRun.Order_Forecast_as_Demand__c = cRec.Use_Order_Forecast_as_Demand_in_MRP__c;
        mrpRun.Planning_Calendar__c = cRec.Planning_Calendar__c;
        mrpRun.Purchase_Orders_as_Supply__c = cRec.Use_Purchase_Orders_as_Supply_in_MRP__c;
        mrpRun.Quantity_on_Hand_as_Supply__c = cRec.Use_Quantity_on_Hand_as_Supply_in_MRP__c;
        mrpRun.Receiving_Calendar__c = cRec.Receiving_Calendar__c;
        mrpRun.Sales_Orders_as_Demand__c = cRec.Use_Sales_Orders_as_Demand_in_MRP__c;
        mrpRun.Work_Orders_as_Demand__c = cRec.Use_Work_Orders_as_Demand_in_MRP__c;
        mrpRun.Work_Orders_as_Supply__c = cRec.Use_Work_Orders_as_Supply_in_MRP__c;
        try {
            DML.insertAsUser(mrpRun);
        }
        catch (DmlException e) {
           ApexPages.addMessages(e);
           return;
        }
 
        runPlanning = true;


		/*
		//KNDY-10473: Adding CRUD/FLS checks with SOQLUtil
		*/
		SOQLUtil soql = new SOQLUtil('BusinessHours', true); //enforceFLS=true, running in user mode
		soql.addFields(new set<string>{
			'Id'
		});
		soql.setWhereClause('isDefault = true');
		soql.setLimit(1);
		
		BusinessHours Pcal = Database.query(soql.getQuery());
		PcalID = Pcal.id;



        RcalID = PcalID;
        
        if (mrpRun.Planning_Calendar__c != null) {
            PcalID = mrpRun.Planning_Calendar__c;
            RcalID = PcalID;
        }
        
        if (mrpRun.Receiving_Calendar__c != null) RcalID = mrpRun.Receiving_Calendar__c;
                
        // KNDY-3080 if not using qoh skip GenerateSafetyDemand
        if (mrpRun.Level_Zero_QOH_as_Supply__c == true || mrpRun.Quantity_on_Hand_as_Supply__c == true) {
            // PTM-765 user defined batch size
            integer defaultBatchSize = 200;
            MRP_Batch_Sizes__c mrpbs = MRP_Batch_Sizes__c.getInstance('GenerateSafetyDemand');
            if (mrpbs != null) defaultBatchSize = integer.valueOf(mrpbs.Batch_Size__c);
                
            GenerateSafetyDemand obj = new GenerateSafetyDemand(mrpRun.ID, PcalID, RcalID);
            Database.executeBatch( obj, defaultBatchSize);
        }      
        else {
            // PTM-765 user defined batch size
            integer defaultBatchSize = 10;
            MRP_Batch_Sizes__c mrpbs = MRP_Batch_Sizes__c.getInstance('GenerateMRPTempData');
            if (mrpbs != null) defaultBatchSize = integer.valueOf(mrpbs.Batch_Size__c);
                
            GenerateMRPTempData obj1 = new GenerateMRPTempData(mrpRun.ID, PcalID, RcalID);
            Database.executeBatch( obj1, defaultBatchSize);
        }
        
        MRPService.mrp_start(cfID);       // notify the service we have started
        
        ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.INFO,Label.BatchEmail);        
        ApexPages.addMessage(myMsg);
    }
    
    public void generateItemLevel () {  // all starts here
        runLeveling = true;
        ClearItemLevels Obj=new ClearItemLevels();
        obj.companyId=companyId;
        Database.executebatch(obj,2000);
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO,Label.BatchEmail) );              
    }

    /** 
     * used by the Apex Jobs component, just lists out async jobs
     * that are invloved in MRP
     */
    private List<String> planningClassNames = new List<String>{
            'GenerateMRPPlanData',
            'GenerateMRPTempData',
            'GenerateSafetyDemand','GenerateMRPEraseTemp',
            'ClearItemLevels','CleanFinalData','CreateNextLevel','ClearItemLevels'
            };
    
    public void IncrementCounter() {} 
    
    public List<AsyncApexJob> getApexJobList() { 
		//KNDY-10473: Adding CRUD/FLS checks with SOQLUtil
		SOQLUtil soql = new SOQLUtil('AsyncApexJob', true); //enforceFLS=true, running in user mode
		soql.addFields(new set<string>{
			'TotalJobItems','Status','ParentJobId','NumberOfErrors','MethodName','LastProcessedOffset','LastProcessed',
			'JobType','JobItemsProcessed','Id','ExtendedStatus','CreatedDate','CreatedById','CompletedDate','ApexClassId',
			'ApexClass.Name','ApexClass.NamespacePrefix'
		});
		soql.setWhereClause('ApexClass.Name in :planningClassNames');
		soql.setOrderByClause('CreatedDate desc');
		soql.setLimit(20);
		return Database.query(soql.getQuery());
    }
}