src-ken&y/objects/Company__c.object
<CustomObject>
    <customHelpPage>HelpCompany</customHelpPage>
    <description>Each Logistics or Financial entity will be represented by a single Company record.  Master data for the Company is recorded here and used throughout the System.</description>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Facility__c.object
<CustomObject>
    <customHelpPage>HelpFacilites</customHelpPage>
    <description>Warehouse or building</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Facilities</relationshipLabel>
        <relationshipName>Facilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Default_Sales_Order_Ship_From_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Location</description>
        <inlineHelpText>If you want sales orders to automatically include a ship-from location, select a location from the list of available options.</inlineHelpText>
        <label>Sales Order Ship From Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Location__c.Facility__c</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Facilities (Default Sales Order Ship From Location)</relationshipLabel>
        <relationshipName>Facilities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Facility</label>
    <nameField>
        <label>Facility</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Facility_Assignment__c.object
<CustomObject>
    <customHelpPage>HelpFacilityAssignment</customHelpPage>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Facility Assignments</relationshipLabel>
        <relationshipName>Customer_Facility_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Facility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Facility</label>
        <referenceTo>Facility__c</referenceTo>
        <relationshipLabel>Facility Assignments (Facility)</relationshipLabel>
        <relationshipName>Customer_Facility_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Group</label>
        <referenceTo>Product_Group__c</referenceTo>
        <relationshipLabel>Facility Assignments (Product Group)</relationshipLabel>
        <relationshipName>Customer_Facility_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ship_to_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship-to Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Facility Assignments (Ship-to Customer)</relationshipLabel>
        <relationshipName>Customer_Facility_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Facility Assignment</label>
    <nameField>
        <label>Facility Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facility Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Product__c.object
<CustomObject>
    <customHelpPage>HelpProducts</customHelpPage>
    <description>Products are sellable Items with Selling Unit of Measure included</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product group to which this product belongs</description>
        <label>Product Group</label>
        <referenceTo>Product_Group__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status indicates if the product is active or retired</description>
        <label>Status</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Product_Group__c.object
<CustomObject>
    <customHelpPage>HelpProductGroup</customHelpPage>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Product Groups</relationshipLabel>
        <relationshipName>Product_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Facility_Assignment__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked if Product Group is used for Facility Assignment</description>
        <label>Facility Assignment</label>
        <type>Checkbox</type>
    </fields>
    <label>Product Group</label>
    <nameField>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Sales_Order__c.object
<CustomObject>
    <customHelpPage>HelpSalesOrders_Managing</customHelpPage>
    <description>Sales Order Header</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ship_From_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Ship From Location</description>
        <label>Ship From Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ship_to__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Customer</description>
        <label>Customer Ship To</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Customer__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Ship To</value>
            </filterItems>
            <filterItems>
                <field>Customer__c.Parent_Customer__c</field>
                <operation>equals</operation>
                <valueField>$Source.Customer__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Sales Orders (Ship To)</relationshipLabel>
        <relationshipName>Sales_Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Order status</description>
        <label>Order Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>On hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Sales_Order_Line__c.object
<CustomObject>
    <customHelpPage>HelpSalesOrders_Managing</customHelpPage>
    <description>Line Items on the Sales Order.</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company passed down from the sales order header</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Product</description>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <filterItems>
                <field>Product__c.Item__r.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Product__c.Company__c</field>
                <operation>equals</operation>
                <valueField>$Source.Company__c</valueField>
            </filterItems>
            <filterItems>
                <field>Product__c.Company__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <label>Sales Order</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Company does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>Sales_Order__c.Company__c</field>
                <operation>equals</operation>
                <valueField>$Source.Company__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Sales_Order__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ship_From_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Location</description>
        <label>Ship From Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Sales Order Line Ship From Location value does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>Location__c.Facility__r.Company__c</field>
                <operation>equals</operation>
                <valueField>$Source.Company__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Sales Order Lines (Ship From Location)</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Line open if item is not shipped; line closed if shipped; line partial if partially shipped</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <label>Sales Order Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/classes/FacilityAssignmentExt.cls
public with sharing class FacilityAssignmentExt {
    
    private apexpages.StandardController con;
    public Boolean selecterror {get; set;}
    List<Sales_Order__c> soList = new List<Sales_Order__c>();
    List<Sales_Order_Line__c> solList = new List<Sales_Order_Line__c>();
    Set<ID> pgSet = new Set<ID>();

    public FacilityAssignmentExt(ApexPages.StandardController controller) {
        con = controller;
        Sales_Order__c so =(Sales_Order__c)controller.getRecord();
        
		//KNDY-10473: Adding CRUD/FLS checks with SOQLUtil
		SOQLUtil soql = new SOQLUtil('Sales_Order__c', true); //enforceFLS=true, running in user mode
		soql.addFields(new set<string>{
			'ID','Company__c','Ship_From_Location__c','Ship_to__c','Status__c'
		});
		Id soId = so.ID;
		soql.setWhereClause('ID =: soId');
		soList = Database.query(soql.getQuery());

        if (soList[0].Status__c  != 'Draft') {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.FATAL, Label.To_proceed_SalesOrder_status_must_be_set_to_Draft));
            selecterror = true;
            return;
        }

		//KNDY-10473: Adding CRUD/FLS checks with SOQLUtil
		soql = new SOQLUtil('Sales_Order_Line__c', true); //enforceFLS=true, running in user mode
		soql.addFields(new set<string>{
			'ID','Product__r.Name','Product__r.Product_Group__c','Ship_From_Location__c'
		});
		soId = so.ID;
		soql.setWhereClause('Sales_Order__c =: soId and Status__c != \'Closed\' and Status__c != \'Cancelled\'');
		solList = Database.query(soql.getQuery());

        if (solList.size() == 0) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.FATAL, Label.SalesOrder_has_no_open_lines));
            selecterror = true;
            return;
        }
        for (Sales_Order_Line__c sol : solList) {
            if (sol.Product__r.Product_Group__c == null) {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.FATAL, Label.Product_Group_is_missing_for_product +sol.Product__r.Name ));
                selecterror = true;
                return;
            }
            pgSet.add(sol.Product__r.Product_Group__c);
        }
                   
    }
    
     public pagereference fassign() {
     
        Date todaysdate = System.today();
        ID hid;
     
		//KNDY-10473: Adding CRUD/FLS checks with SOQLUtil
		SOQLUtil soql = new SOQLUtil('Facility_Assignment__c', true); //enforceFLS=true, running in user mode
		soql.addFields(new set<string>{
			'ID','Facility__c','Facility__r.Name','Product_Group__c'
		});
		Id cId = soList[0].Company__c;
		Id sId = soList[0].Ship_to__c;
		soql.setWhereClause(
			'Company__c =: cId and ' +
			'Ship_to_Customer__c =: sId and ' +
			'Product_Group__c in: pgSet and ' +
			'Active__c = true and ' +                                            
			'Start_Date__c <=: todaysdate'	
		);
		List<Facility_Assignment__c> faList = Database.query(soql.getQuery());
        
        hid = null;
        for (Integer i = 0; I < faList.size(); ++i) {  // get rid of duplicates for the same product group
            if (hid == faList[i].Product_Group__c) falist.remove(i);
            else hid = faList[i].Product_Group__c;
        }

        if (faList.size() == 0) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.FATAL, Label.No_FacilityAssignment_records_found));
         selecterror = true;
        return null;
        }
         
        if (faList.size() != pgSet.size()) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.FATAL, Label.Not_all_Product_Groups_have_FacilityAssignment_records));
            selecterror = true;
            return null;
        }
         
        for (Facility_Assignment__c fa : faList) {
            if (faList[0].Facility__c != fa.Facility__c) {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.FATAL, Label.Different_Facilities_Found));
                selecterror = true;
                return null;
            }
        }
         
		//KNDY-10473: Adding CRUD/FLS checks with SOQLUtil
		soql = new SOQLUtil('Facility__c', true); //enforceFLS=true, running in user mode
		soql.addFields(new set<string>{
			'ID','Default_Sales_Order_Ship_From_Location__c'
		});
		Id fId = faList[0].Facility__c;
		soql.setWhereClause('ID =: fId');
		List<Facility__c> fList = Database.query(soql.getQuery());

        if (fList.size() == 0 || flist[0].Default_Sales_Order_Ship_From_Location__c == null) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.FATAL,
                                 Label.Default_SalesOrder_ShipFromLocation_not_on_file_for_Facility +faList[0].Facility__r.Name));
            selecterror = true;
            return null;
        }
         
        soList[0].Ship_From_Location__c = flist[0].Default_Sales_Order_Ship_From_Location__c;
        for (Sales_Order_Line__c sol : solList) {
            sol.Ship_From_Location__c = flist[0].Default_Sales_Order_Ship_From_Location__c;
        }
        DML.updateAsUser(soList);
        DML.updateAsUser(solList);
        
        return ( ApexPages.hasMessages() ? null : new PageReference('/'+this.con.getId()) );
    }

}