src-ken&y/objects/Company__c.object
<CustomObject>
    <customHelpPage>HelpCompany</customHelpPage>
    <description>Each Logistics or Financial entity will be represented by a single Company record.  Master data for the Company is recorded here and used throughout the System.</description>
    <fields>
        <fullName>Default_Purchasing_Deliver_To_Facility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Facility</description>
        <inlineHelpText>Default Purchasing Deliver To Facility</inlineHelpText>
        <label>Purchasing Deliver To Facility</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Facility__c.Company__c</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Facility__c</referenceTo>
        <relationshipLabel>Companies</relationshipLabel>
        <relationshipName>Companies</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Facility__c.object
<CustomObject>
    <customHelpPage>HelpFacilites</customHelpPage>
    <description>Warehouse or building</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Facilities</relationshipLabel>
        <relationshipName>Facilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Default_Purchasing_Delivery_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Default Purchasing Delivery Location</description>
        <inlineHelpText>If you want purchase orders to include a delivery location, select a location from the list of available options.</inlineHelpText>
        <label>Purchasing Delivery Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Location__c.Facility__c</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Facilities</relationshipLabel>
        <relationshipName>Facilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Facility</label>
    <nameField>
        <label>Facility</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Purchase_Order__c.object
<CustomObject>
    <customHelpPage>HelpPurchaseOrders</customHelpPage>
    <description>Purchase header information</description>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>POs must be approved by user with appropriate authorization limit</description>
        <inlineHelpText>The acceptable difference, expressed as an amount, between the sales order and the related purchase order. If you choose not to enter a tolerance amount, Kenandy assumes zero tolerance.</inlineHelpText>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Pending Authorization</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Buyer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Buyer or planner responsible for this PO</description>
        <label>Buyer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Purchase_Orders_Buyer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Logistics or Financial company that this PO will be owned by</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Closed__c</fullName>
        <description>Date PO was closed or cancelled</description>
        <label>Date Closed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Delivery_Facility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Delivery facility is defined on the Company page. You can change the default value on the PO header. If you update the facility at the line level, the delivery location  changes to match the Default Purchasing Delivery Location for the specified facility.</inlineHelpText>
        <label>Delivery Facility</label>
        <referenceTo>Facility__c</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delivery_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Location where orders of type Shipment should send the inventory</description>
        <inlineHelpText>Delivery location is defined on the Facility page. You can change the default value on the PO header if you choose a location within the specified facility. At the line level, the delivery location is determined by the location specified in the PO header.</inlineHelpText>
        <label>Delivery Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Location doesn&apos;t belong to the Facility</errorMessage>
            <filterItems>
                <field>Location__c.Facility__c</field>
                <operation>equals</operation>
                <valueField>$Source.Delivery_Facility__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>Date PO is placed with vendor</description>
        <label>Order Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Remit_To_Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The supplier to whom the payment should be made.</description>
        <label>Remit To Supplier</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Supplier__c.Type__c</field>
                <operation>equals</operation>
                <value>Remit-To</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Purchase Orders (Remit To Supplier)</relationshipLabel>
        <relationshipName>Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the Purchase Order;  PO will be kept on file after beng closed until company runs a maintenance transaction to backup and purge closed and cancelled purchase orders</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Supplier</description>
        <label>Purchase From Supplier</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Supplier__c.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <filterItems>
                <field>Supplier__c.Hold_Purchasing__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>Supplier__c.Type__c</field>
                <operation>equals</operation>
                <value>Purchasing</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Purchase Orders (Supplier)</relationshipLabel>
        <relationshipName>Purchase_Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>The PO type. &quot;Standard&quot; -&gt; lists goods or services you require. &quot;Production&quot; -&gt; establishes a contract with a co-manufacturer to produce goods. &quot;Shipment&quot; -&gt; lists goods ready to be picked up.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Production</fullName>
                </value>
                <value>
                    <fullName>Standard</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Shipment</fullName>
                </value>
                <value>
                    <fullName>Drop Ship</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Purchase Order</label>
    <nameField>
        <label>Purchase Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Supplier__c.object
<CustomObject>
    <customHelpPage>HelpSuppliers</customHelpPage>
    <description>Supplier object</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Suppliers</relationshipLabel>
        <relationshipName>Suppliers1_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hold_Purchasing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates that you cannot create a new Purchase order for this supplier, does not affect existing POs or any downstream processes.</description>
        <inlineHelpText>Indicates that you cannot create a new purchase order for this supplier.</inlineHelpText>
        <label>Hold Purchasing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Remit_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Remit-To supplier that this purchasing supplier belongs to.</description>
        <label>Remit-To</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Supplier__c.Type__c</field>
                <operation>equals</operation>
                <value>Remit-To</value>
            </filterItems>
            <infoMessage>Select the Remit-To supplier</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Suppliers (Purchasing)</relationshipLabel>
        <relationshipName>PurchasingSuppliers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Supplier Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>The type of supplier record.</description>
        <inlineHelpText>Type of supplier record. Options include: Purchasing and Remit-To.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Parent</fullName>
                </value>
                <value>
                    <fullName>Purchasing</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Remit-To</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Supplier</label>
    <nameField>
        <label>Supplier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/PurchaseOrderNewExt.cls
public with sharing class PurchaseOrderNewExt {
	
	private ApexPages.StandardController controller;
	public Boolean isVisible { get; set;}
	
    public PurchaseOrderNewExt(ApexPages.StandardController c) {
		controller = c;
        Sobject newObj = controller.getRecord();        
        // use the existing record that the controller has created for us
        newObj.put('Buyer__c', UserInfo.getUserId());   
        isVisible = true; 
        assigndefault();       
    }
    public void assigndefault(){
    	Purchase_Order__c po = (Purchase_Order__c)controller.getRecord();
    	if(po.company__c!=null){
			//KNDY-10473: Adding CRUD/FLS checks with SOQLUtil
			Id companyId = po.company__c;
			
			SOQLUtil soql = new SOQLUtil('company__c', true); //enforceFLS=true, running in user mode
			soql.addFields(new set<string>{
				'Default_Purchasing_Deliver_To_Facility__c','Default_Purchasing_Deliver_To_Facility__r.Default_Purchasing_Delivery_Location__c'
			});
			soql.setWhereClause('id=:companyId');
	
			company__c com = Database.query(soql.getQuery());
	
	    	po.Delivery_Facility__c = com.Default_Purchasing_Deliver_To_Facility__c;
	    	po.Delivery_Location__c = com.Default_Purchasing_Deliver_To_Facility__r.Default_Purchasing_Delivery_Location__c;					
    	}
    }
    
    public Pagereference SavePO(){ //KNDY-2113
     	Purchase_Order__c po = (Purchase_Order__c)controller.getRecord();
    
		//KNDY-10473: Adding CRUD/FLS checks with SOQLUtil
		Id supplierId = po.Supplier__c;
		
		SOQLUtil soql = new SOQLUtil('Supplier__c', true); //enforceFLS=true, running in user mode
		soql.addFields(new set<string>{
			'id','Remit_To__c','Hold_Purchasing__c','RecordType.Name','RecordType.DeveloperName','RecordTypeId','Company__c'
		});
		soql.setWhereClause('id =:supplierId');
		soql.setLimit(1);

		Supplier__c supplier = Database.query(soql.getQuery());

        //PTP-652
        if(!String.isBlank(supplier.Company__c) 
        	&& (po.Company__c != supplier.Company__c)){
            
            ApexPages.addMessage( new Apexpages.Message(ApexPages.severity.FATAL,
                    Label.Purchase_from_Supplier_not_tagged_to_the_Company));
            return null;
        }
       
        if (supplier.Hold_Purchasing__c){
        	ApexPages.addMessage( new Apexpages.Message(ApexPages.severity.FATAL,
                    Label.Purchase_Order_creation_failed));
            isVisible = false;        
            return null;
        }else if (po.Type__c == 'Drop Ship'){
        	ApexPages.addMessage( new Apexpages.Message(ApexPages.severity.FATAL,Label.Purchase_Order_creation_failed_Cannot_create_Drop_Ship_PO));      
            return null;
        }
        else {
	        po.Approval_Status__c = 'Pending Authorization';
	        po.Date_Closed__c = null;
	        po.Order_Date__c = system.today();
	        po.Status__c = 'Open';        
	        po.Remit_To_Supplier__c = supplier.Remit_To__c;// PTP-567
	        
	        Savepoint sp = Database.setSavepoint();
	        try {
            	DML.insertAsUser(po);
	        }catch (DmlException e) {
	           ApexPages.addMessages(e);
	           Database.rollback(sp);
	          // isVisible = false; //KNDY-3735 taking care of save button to not disappear
	           return null;
	        }          
	
	        PageReference POPage = new PageReference('/'+po.Id);
	        POPage.setRedirect(true);
	        return POPage;
	        
        }
     }
}