src-ken&y/objects/ConfigurationMDT__mdt.object
<CustomObject>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Configuration</label>
    <pluralLabel>Configurations</pluralLabel>
</CustomObject>

src-ken&y/objects/Supplier__c.object
<CustomObject>
    <customHelpPage>HelpSuppliers</customHelpPage>
    <description>Supplier object</description>
    <fields>
        <fullName>Hold_Payment__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates that you cannot issue a payment to this supplier</description>
        <inlineHelpText>Indicates that you cannot issue a payment to this supplier.</inlineHelpText>
        <label>Hold Payment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pay_Per_Invoice__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to indicate if payments should be created separately for each invoice against this supplier.</description>
        <inlineHelpText>Indicates that separate payments are to be created for each invoice.</inlineHelpText>
        <label>Pay Per Invoice</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Payment_Method_G__c</fullName>
        <defaultValue>&apos;Check&apos;</defaultValue>
        <description>Defines how the supplier would like to be paid</description>
        <label>Remittance Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Payment_Method</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Supplier Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Supplier</label>
    <nameField>
        <label>Supplier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Supplier_Invoice__c.object
<CustomObject>
    <customHelpPage>HelpSupplierInvoice</customHelpPage>
    <description>Record invoices for items or services  that are received from a supplier.  Bills can be recorded with or without purchase orders</description>
    <fields>
        <fullName>Hold__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates this invoice is on hold</description>
        <label>Hold</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoice_Amount__c</fullName>
        <inlineHelpText>The invoice amount is required. Invoice cannot be approved for payment if the invoice amount does not match the total amount on each line of the invoice.</inlineHelpText>
        <label>Invoice Amount</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoice_Type__c</fullName>
        <label>Invoice Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Credit Memo</fullName>
                </value>
                <value>
                    <fullName>Invoice</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Prepayment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Method_G__c</fullName>
        <description>Defines how the invoice must be paid to the supplier.</description>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Payment_Method</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of bill</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supplier_Invoice__c</fullName>
        <description>Supplier invoice no. reference</description>
        <label>Invoice Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Remit To Supplier</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Supplier__c.Type__c</field>
                <operation>equals</operation>
                <value>Remit-To</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Supplier Invoices</relationshipLabel>
        <relationshipName>Supplier_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Supplier Invoice</label>
    <nameField>
        <label>Supplier Invoice</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Supplier_Payment__c.object
<CustomObject>
    <customHelpPage>HelpSupplierPayments</customHelpPage>
    <description>Pay supplier invoices</description>
    <fields>
        <fullName>Payment_Method_G__c</fullName>
        <description>mode of payment</description>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Payment_Method</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of transaction</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Unapproved</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Wire request submitted, payment pending</fullName>
                </value>
                <value>
                    <fullName>Wire request submitted, payment confirmed</fullName>
                </value>
                <value>
                    <fullName>Void payment</fullName>
                </value>
                <value>
                    <fullName>Paid and reconciled</fullName>
                </value>
                <value>
                    <fullName>Unreconciled</fullName>
                </value>
                <value>
                    <fullName>Applied</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Supplier for whom this payment will be applied against</description>
        <label>Supplier</label>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Supplier Payments</relationshipLabel>
        <relationshipName>Supplier_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Supplier Payment</label>
    <nameField>
        <label>Supplier Payment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/globalValueSets/Payment_Method.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Check</fullName>
    </customValue>
    <customValue>
        <fullName>Credit Card</fullName>
    </customValue>
    <customValue>
        <fullName>ACH</fullName>
    </customValue>
    <customValue>
        <fullName>Online</fullName>
    </customValue>
    <customValue>
        <fullName>EFT</fullName>
    </customValue>
    <customValue>
        <fullName>Wire</fullName>
    </customValue>
    <customValue>
        <fullName>Cash</fullName>
    </customValue>
    <description>Payment Method picklist value set</description>
    <masterLabel>Payment Method</masterLabel>
</GlobalValueSet>

src-ken&y/classes/PaymentBatch.cls
public with sharing class PaymentBatch implements Database.Batchable<sObject>, Process.Runnable, Database.Stateful{

	public Id companyId;
	public List<KendoUtils.FilterDescriptor> filters;
    map<id,SupplierPaymentService.InvoiceWrapper> initialScopeInvsFromUI = new map<id,SupplierPaymentService.InvoiceWrapper>();   //store id with invoice amount to be paid/consumed      
    public Set<Id> initialSetOfSuppliersChosenToBePaid = new Set<Id>();  
    public List<Notify.Message> messages = new List<Notify.Message>();
    public string paymentMethod;
    public Boolean totalCreditsExceedsDebits = false;
    public string query;
    public set<id> SIset = new set<Id>();
    public class PymtBatchException extends Exception{}
    
    public PaymentBatch ( List<KendoUtils.FilterDescriptor> filterCriteria, map<id,SupplierPaymentService.InvoiceWrapper> scopeInvoicesFromUI, Set<Id> scopeOfSuppliersChosen){
        filters = filterCriteria;
        initialScopeInvsFromUI = scopeInvoicesFromUI;
        initialSetOfSuppliersChosenToBePaid = scopeOfSuppliersChosen;
        SIset.addall(initialScopeInvsFromUI.keyset() );
        system.debug('SISet=='+ SISet);
        for(KendoUtils.FilterDescriptor fd: filterCriteria){
            system.debug(LoggingLevel.info,'Filter: ' + fd);            
            if (fd.field == 'Payment_Method_G__c'){                
                paymentMethod = String.valueOf(fd.value);  
            }    
            if (fd.field == 'totalCreditsExceedsDebits'){                
                totalCreditsExceedsDebits =  String.valueOf(fd.value).toLowerCase() == 'true' ? True : False;
            }             
        }
        
    }
    
    public Database.QueryLocator start(Database.BatchableContext BC){
        system.debug(LoggingLevel.ERROR, 'entered query locator, suppliers: ' + initialSetOfSuppliersChosenToBePaid + '=initialScopeInvsFromUI='+ initialScopeInvsFromUI.keyset() + '=paymentMethod=' + paymentMethod);
        MasterControlProgram.checkAlreadyRunning( this, BC );
        string whereClause = ' where Status__c = \'Approved\'  AND Hold__c = false and  Invoice_Type__c NOT IN (\'Credit Memo\') AND Payment_Method_G__c = : paymentMethod AND Supplier__r.Hold_Payment__c = false ' +
            			' AND Supplier__c= : initialSetOfSuppliersChosenToBePaid  And  Id IN :SIset order by Invoice_Amount__c desc,Supplier__c asc';
    	query =	'Select Id, Name,Supplier__c,Invoice_amount__c,Invoice_Type__c From Supplier_Invoice__c ' + whereClause;  
    	return Database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext BC, List<sObject> scope){        
    	system.debug(LoggingLevel.ERROR, 'entered execute, supplier invoice scope: ' + scope);
    	Savepoint sp = Database.setSavepoint();  
    	try{     
    		string suppId = (string)scope[0].get('Supplier__c');            
            SOQLUtil supplierSoql = new SOQLUtil ( 'Supplier__c',true) ; //enforceFLS = true, runs in user mode
	    	supplierSoql.addFields ( new Set<String> { 'Id', 'Name','Pay_Per_Invoice__c'} ) ;
	    	supplierSoql.setWhereClause ( ' Hold_Payment__c = false and Id In :initialSetOfSuppliersChosenToBePaid' );
        	supplierSoql.setOrderByClause ( 'Name ASC' ) ;
        	List<Supplier__C> supplierList = database.query(supplierSoql.getQuery());
        	 
 			SupplierPaymentService spService = new SupplierPaymentService();
        	spService.processPayments( filters, initialScopeInvsFromUI,scope, supplierList, BC.getJobId());
        }catch(Exception ex) {
            system.debug('exception in batch processing : '+ ex.getMessage() + '=' + ex.getStackTraceString());
            Database.rollback(sp);
            if (!Test.isRunningTest()){
                messages.add(new Notify.Message(Label.Error_Occurred_While_Processing_Payment_Batch + ':'  + ex.getMessage() +'.' + Label.Contact_Kenandy_administrator_for_help, '')); //PTP-625
            	//messages.add(Notify.getErrorMessage(scope, ex.getMessage(), ''));
                //failureCounter = 1;
            }else
            	throw new PymtBatchException(ex.getMessage(), ex); 
        }
    } 
    
    public void finish(Database.BatchableContext info){
        system.debug(LoggingLevel.INFO,'finish method : '+ initialScopeInvsFromUI);
		BatchToChatter.processBatchInformation(info.getJobId(), this, messages);
		Notify.sendEmailBatchFinish(messages.size(), null, messages, info);      
		system.debug('error messages : '+ messages.size());
		////NOW call the batch to do actions before the Supplier invoices get finalized
		//KNDY-16750 - seperate batch to finalize SPs
        BatchInjector nextBatch = null;
        Integer finalizeBatchSize = 200;
        if (messages.size() == 0){
	        if(nextBatch == null){
	        	nextBatch = BatchInjector.getNextBatch(Schema.Supplier_Payment__c.getSObjectType().getDescribe().getName(), 0);
	        }
	
	        Id batchId;
	        if(nextBatch != null && nextBatch.executer != null  ){
	        	//run next batch
	        	system.debug('finish method of payment batch, starting SupplierPaymentPreFinalizeBatch' + info.getJobId() + ' , nextBatch ='+nextBatch);
	        	batchId = Database.executeBatch(new SupplierPaymentPreFinalizeBatch(info.getJobId(),totalCreditsExceedsDebits, nextBatch.executer, nextBatch.sequence), nextBatch.scope);
	        }else{
	        	//call finish
	        	MasterControlProgram.finishedBatch( this ); 
	            system.debug('finish method of payment batch, starting SupplierPaymentFinalizeBatch' + info.getJobId() );
	            //KNDY-19040 fetch finalize batch scope from configuration MDT
	            List<ConfigurationMDT__mdt> mdtRecords = [SELECT developerName, Value__c, namespacePrefix
                                        FROM ConfigurationMDT__mdt
                                        WHERE developerName = 'Supplier_Payment_Finalize_Batch_Size'
                                        LIMIT 1];
		        if (mdtRecords.size() > 0){
		            finalizeBatchSize = mdtRecords[0].Value__c != null ? Integer.ValueOf(mdtRecords[0].Value__c) : finalizeBatchSize;
		        }
	        	batchId = Database.executeBatch(new SupplierPaymentFinalizeBatch(info.getJobId(),totalCreditsExceedsDebits),finalizeBatchSize);
	        }
        }else
        	MasterControlProgram.finishedBatch( this ); 

    }
 
 	/* implementation of Runnable 
 	 */
 	public PaymentBatch() {}
 	public void runBatch( id CompanyId) {
		Integer batchSize = 1;
		if (Test.isRunningTest()) {
			batchSize = 10; //need to run more than one in the test, since we only get 1 batch execution in test context
		}
		//KNDY-18789 - Fetch batch scope from CMDT and if it doesnt exists set default batchsize =1
		List<ConfigurationMDT__mdt> mdtRecords = [SELECT developerName, Value__c, namespacePrefix
                                        FROM ConfigurationMDT__mdt
                                        WHERE developerName = 'Supplier_Payment_Batch_Size'
                                        LIMIT 1];
        if (mdtRecords.size() > 0){
            batchSize = mdtRecords[0].Value__c != null ? Integer.ValueOf(mdtRecords[0].Value__c) : batchSize;
        }
		system.debug(LoggingLevel.Error,'Batch size from MDT : ' +mdtRecords + ' and Actual Batch Size : ' + batchSize );
		PaymentBatch jpBatch = new PaymentBatch(filters, initialScopeInvsFromUI, initialSetOfSuppliersChosenToBePaid);
        ID jobId = Database.executeBatch(jpBatch, batchSize); 
	}  
}