src-ken&y/objects/Configuration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>(Name, Value) pairs, holds configuration switches for fine tuning subsystems</description>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Configuration</label>
</CustomObject>

src-ken&y/objects/Facility__c.object
<CustomObject>
    <customHelpPage>HelpFacilites</customHelpPage>
    <description>Warehouse or building</description>
    <fields>
        <fullName>Facility_Identifier__c</fullName>
        <label>Facility Identifier</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Facility</label>
    <nameField>
        <label>Facility</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Item__c.object
<CustomObject>
    <customHelpPage>HelpItems</customHelpPage>
    <description>Item Master object</description>
    <fields>
        <fullName>Packaging_UOM__c</fullName>
        <description>Specify multiple Packaging UOM&apos;s for the Item. Limit 1 Packaging UOM per Packaging class Level</description>
        <inlineHelpText>Specify multiple Packaging UOM&apos;s for the Item. Limit 1 Packaging UOM per Packaging class Level</inlineHelpText>
        <label>Packaging UOM</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stocking_UOM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stocking Unit of Measure.  Table of acceptable UOM applies. If Purchasing UOM is not = to Stocking UOM  then conversion factor is used to convert purchased quantities to stocking quantities when purchased items are received into Inventory: Quantity from PO x conversion = Stock Quantity</description>
        <inlineHelpText>You can convert item quantities from one unit of measure to another. For example, if you purchase in dozens (DZ) but stock in eaches (EA) you can indicate the UOM information on the Item detail page and Kenandy will do the conversion for you.</inlineHelpText>
        <label>Stocking UOM</label>
        <referenceTo>UOM__c</referenceTo>
        <relationshipLabel>Items (Stocking UOM)</relationshipLabel>
        <relationshipName>Item_Stocking_UOM</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Process_Request__c.object
<CustomObject>
    <description>This object stores the request information for processing various actions in the system.</description>
    <fields>
        <fullName>Exceptions_Count__c</fullName>
        <label>Exceptions Count</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Facility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Facility</label>
        <referenceTo>Facility__c</referenceTo>
        <relationshipLabel>Process Requests</relationshipLabel>
        <relationshipName>Process_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Process Requests</relationshipLabel>
        <relationshipName>Process_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Packaging_UOM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Packaging UOM</label>
        <referenceTo>UOM__c</referenceTo>
        <relationshipLabel>Process Requests</relationshipLabel>
        <relationshipName>Process_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parameter_Value__c</fullName>
        <description>Single parameter value for the request. If there are more than one parameter, or the parameter contains custom data structures, use &apos;Parameter Body&apos; field instead.</description>
        <label>Parameter Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Process_Call__c</fullName>
        <description>The process that the request is made for.</description>
        <label>Process Call</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pick Shipment Line</fullName>
                </value>
                <value>
                    <fullName>UndoPick Shipment Line</fullName>
                </value>
                <value>
                    <fullName>Cycle Count</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The current status of the request.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ready</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Work_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Order</label>
        <referenceTo>Work_Order__c</referenceTo>
        <relationshipLabel>Process Requests</relationshipLabel>
        <relationshipName>Process_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Process Request</label>
    <nameField>
        <displayFormat>PR-{0000000000}</displayFormat>
        <label>Process Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Work_Order__c.object
<CustomObject>
    <customHelpPage>HelpWorkOrder</customHelpPage>
    <description>All work orders including planned orders from MRP as well as unplanned orders.</description>
    <fields>
        <fullName>Contents__c</fullName>
        <label>Contents</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Exceptions_Count__c</fullName>
        <label>Exceptions Count</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Facility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The facility in which the work order will be processed.</description>
        <label>Facility</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Facility__c.Company__c</field>
                <operation>equals</operation>
                <valueField>$Source.Company__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Facility__c</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Workorders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Item</description>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Packaging_UOM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Packaging UOM</label>
        <referenceTo>UOM__c</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Indicates the status of this work order: Draft, In Process, Complete, Rework, Cancelled</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Released</fullName>
                </value>
                <value>
                    <fullName>In Process</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Work Order</label>
    <nameField>
        <label>Work Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/WorkOrderQueue.cls
public class WorkOrderQueue implements Queueable {
    public class WorkOrderQueueException extends Exception {}
    public List<Process_Request__c> prs;
    public WorkOrderQueue (){}
    public WorkOrderQueue (List<Process_Request__c> prs){
        this.prs = prs;
    }
    
    public void execute(QueueableContext context) {
        Configuration__c bulkifyProcessRequest = Configuration__c.getValues('BULKIFY_WORK_ORDER_QUEUE');
        // Check custom settings
        Boolean isBulkifyRequests = bulkifyProcessRequest !=null && bulkifyProcessRequest.Value__c.toUpperCase() == 'TRUE' ? true : false;
        if ( isBulkifyRequests )
	        bulkifyRequestExecution();
        else 
            executeSingleRequest ();
    }
    
    void executeSingleRequest() {
        if ( this.prs != null && !this.prs.isEmpty() && this.prs[0].Status__c == 'Draft'  && (this.prs[0].Process_Call__c =='Work Order Complete' || this.prs[0].Process_Call__c =='Work Order Uncomplete') ) {
            
            SOQLUtil woQuery = new SOQLUtil ('Work_Order__c');
            woQuery.addFields( new Set<String>{'Id','Name','Contents__c', 'Item__c', 'Packaging_UOM__c','Item__r.Stocking_UOM__c', 'Item__r.Packaging_UOM__c'});
            woQuery.setWhereClause('Id = \''+this.prs[0].Work_Order__c+'\'');
            List<Work_Order__c> wos = Database.query(woQuery.getQuery());
            
            if ( wos[0].Contents__c != null && wos[0].Contents__c.contains(this.prs[0].Parameter_Value__c) ) {
                delete prs;
            } else {
                
                Map<String, Object> obj = new Map<String,Object>();
                obj.put('woId', this.prs[0].Work_Order__c);
                obj.put('caseNumber', this.prs[0].Parameter_Value__c);
                obj.put('caseQuantity', this.prs[0].Quantity__c);
                
                try {
                    Action.Response res;
                    if ( this.prs[0].Process_Call__c == 'Work Order Complete')
	                    res = APIGateway.doAction('RUN_WORK_ORDER_COMPLETE', JSON.serialize(obj));
                    else if ( this.prs[0].Process_Call__c == 'Work Order Uncomplete') 
                        res = APIGateway.doAction('RUN_WORK_ORDER_UNCOMPLETE', JSON.serialize(obj));
                    
                    delete prs;
                } catch (Exception e ) {
                    if ( e.getMessage().contains('Record Currently Unavailable')) {
                        System.enqueueJob(new WorkOrderQueue(this.prs));
                    } else {
                        throw e;
                    }
                }
            }
        } else {
            system.debug ('No process request...');
        }
    }
    
    void bulkifyRequestExecution () {
        Boolean reRunJob = false;
           
        SOQLUtil util = new SOQLUtil('Process_Request__c', false);
        util.addAllCustomFields();
        util.setWhereClause(' (Work_Order__r.Exceptions_Count__c = null OR Work_Order__r.Exceptions_Count__c = 0) AND Process_Call__c IN (\'Work Order Complete\', \'Work Order Uncomplete\' ) AND Status__c IN (\'Draft\') AND Work_Order__c=\''+this.prs[0].Work_Order__c+'\'');
        util.setForUpdate();
        List<Process_Request__c> requests = Database.query(util.getQuery());
        List<Process_Request__c> requestsToProcess = new List<Process_Request__c>();
        List<Process_Request__c> requestsToDelete = new List<Process_Request__c>();
        ExceptionService exService = new ExceptionService();

        if ( !requests.isEmpty()) {
            try {
                SOQLUtil woQuery = new SOQLUtil ('Work_Order__c');
                woQuery.addFields( new Set<String>{'Id','Name','Contents__c', 'Item__c', 'Packaging_UOM__c','Item__r.Stocking_UOM__c', 'Item__r.Packaging_UOM__c','Item__r.Name','Facility__r.Facility_Identifier__c' });
                woQuery.setWhereClause('Id = \''+requests[0].Work_Order__c+'\'');
                woQuery.setForUpdate();
                List<Work_Order__c> wos = Database.query(woQuery.getQuery());

                Decimal conversionFactor = 1;
                if ( wos != null && !wos.isEmpty()) {
                    // Ensure that work order is completed in the correct Packaging UOM
                    if (wos[0].Item__r.Packaging_UOM__c == null || wos[0].Item__r.Packaging_UOM__c.contains(wos[0].Packaging_UOM__c) == false) {
                        throw new WorkOrderQueueException('Invalid Packaging UOM for the Work Order ' + wos[0].Name);
                    }

                    List<String> packagingUOMs = (List<String>) JSON.deserialize(wos[0].Item__r.Packaging_UOM__c, List<String>.class);
                    conversionFactor = KSE.getConversionFactor( wos[0].Item__c, wos[0].Facility__r.Facility_Identifier__c, wos[0].Packaging_UOM__c, wos[0].Item__r.Stocking_UOM__c, packagingUOMs );
                } else {
                    // throw wo not found exception
                }
                
                Decimal qty = requests[0].Quantity__c;
                String processCall = requests[0].Process_Call__c;
                Boolean addFullCaseOnly = ScannerService.isfullCase( qty, conversionFactor);
                for ( Process_Request__c pr : requests ) {
                    if ( (wos[0].Contents__c != null && wos[0].contents__c.contains(pr.Parameter_Value__c) && pr.Process_Call__c == 'Work Order Complete') 
                       		|| (( wos[0].Contents__c == null || !wos[0].contents__c.contains(pr.Parameter_Value__c)) && pr.Process_Call__c == 'Work Order Uncomplete') ) {
                        requestsToDelete.add(pr);
                    } else if ( pr.Process_Call__c != processCall) {
                        continue;
                    } else {
                        qty = pr.Quantity__c ;
                        // completing either part cases or full cases only
                        if ( ScannerService.isfullCase( qty, conversionFactor) == addFullCaseOnly ) {
                            requestsToProcess.add(pr);
                        }
                    }
                }

                if ( !requestsToDelete.isEmpty()) {
                    delete requestsToDelete;
                }
                
                if ( requestsToProcess.isEmpty()) {
                    system.debug(LoggingLevel.DEBUG, 'No process request found');
                    return;
                }
                Map<String, Object> obj = new Map<String,Object>();
                String woId;
                List<String> caseNumbers = new List<String>();
                Decimal caseQuantity;
                for ( Process_Request__c pr : requestsToProcess ) {
                    woId = pr.Work_Order__c;
                    caseNumbers.add(pr.Parameter_Value__c);
                    caseQuantity = KSE.addQuantityToField(caseQuantity, pr.Quantity__c);
                }
                obj.put('woId', woId);
                obj.put('caseNumber', String.join(caseNumbers, ','));
                obj.put('caseQuantity', caseQuantity);
                obj.put('isFullCase', addFullCaseOnly);
                
                Action.Response res;

                if ( processCall == 'Work Order Complete') {
	                res = APIGateway.doAction('RUN_WORK_ORDER_COMPLETE', JSON.serialize(obj));
                } else if (processCall == 'Work Order Uncomplete') {
                    res = APIGateway.doAction('RUN_WORK_ORDER_UNCOMPLETE', JSON.serialize(obj));
                }

                if ( res.success ) {
                    delete requestsToProcess;
                }
            } catch (Exception e) {
                System.debug(LoggingLevel.ERROR, e.getMessage());
                System.debug(LoggingLevel.ERROR, e.getStackTraceString());

                if ( e.getMessage().contains('Record Currently Unavailable')) {
                    reRunJob = true;
                } else {
                    ExceptionUtil.WO_COMPLETE_EXCEPTION.description += e.getMessage();
                    exService.setException( new Work_Order__c(Id=prs[0].Work_Order__c), ExceptionUtil.WO_COMPLETE_EXCEPTION);
                    exService.finishTasks();
                }
            }
        }
        
        if ( !reRunJob ) {
            util = new SOQLUtil('Process_Request__c', false);
            util.addAllCustomFields();
            util.setOrderByClause('CreatedDate ASC');
            util.setWhereClause('Process_Call__c IN (\'Work Order Complete\', \'Work Order Uncomplete\' ) AND Status__c IN (\'Draft\') AND (Work_Order__r.Exceptions_Count__c = null OR Work_Order__r.Exceptions_Count__c = 0) AND Facility__c =\''+this.prs[0].Facility__c +'\'');
            util.setLimit(1);
            requests = Database.query(util.getQuery());
            
            if ( !requests.isEmpty() ) reRunJob = true;
        }          
        
        if ( reRunJob ) {
            System.enqueueJob(new WorkOrderQueue(requests));
        } 
    }
}