src-ken&y/objects/Contract__c.object
<CustomObject>
    <customHelpPage>HelpPurchasingContract</customHelpPage>
    <description>This objects represents the purchase agreements created during the process of of supplier sourcing and contains the details of the sourcing such as amount/price agreed to, validity etc.</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Purchasing Contracts</relationshipLabel>
        <relationshipName>Purchasing_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Term__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>New field which is a look up, replaces old field by API name: Payment_Terms__c</description>
        <label>Payment Terms</label>
        <referenceTo>Payment_Term__c</referenceTo>
        <relationshipLabel>Purchasing Contracts</relationshipLabel>
        <relationshipName>Purchasing_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Determines the current status of the contract</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Supplier associated with this contract</description>
        <label>Supplier</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2</booleanFilter>
            <filterItems>
                <field>Supplier__c.Type__c</field>
                <operation>equals</operation>
                <value>Purchasing</value>
            </filterItems>
            <filterItems>
                <field>Supplier__c.Hold_Purchasing__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Purchase Agreement</label>
    <nameField>
        <label>Purchase Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Process_Job__c.object
<CustomObject>
    <customHelpPage>HelpProcessJobs</customHelpPage>
    <description>Establish and manage scheduled jobs to run at various hours or frequencies</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The company that will be used for the input parameter to the job</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Process Jobs</relationshipLabel>
        <relationshipName>Process_Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Process Job</label>
    <nameField>
        <label>Process Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Purchase_Order__c.object
<CustomObject>
    <customHelpPage>HelpPurchaseOrders</customHelpPage>
    <description>Purchase header information</description>
    <fields>
        <fullName>Buyer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Buyer or planner responsible for this PO</description>
        <label>Buyer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Purchase_Orders_Buyer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Logistics or Financial company that this PO will be owned by</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Memo__c</fullName>
        <label>Memo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Term__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Payment terms</description>
        <label>Payment Term</label>
        <referenceTo>Payment_Term__c</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purchase_Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The purchase agreement that this PO was released against.</description>
        <label>Purchase Agreement</label>
        <referenceTo>Contract__c</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the Purchase Order;  PO will be kept on file after beng closed until company runs a maintenance transaction to backup and purge closed and cancelled purchase orders</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Supplier</description>
        <label>Purchase From Supplier</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Supplier__c.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <filterItems>
                <field>Supplier__c.Hold_Purchasing__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>Supplier__c.Type__c</field>
                <operation>equals</operation>
                <value>Purchasing</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Purchase Orders (Supplier)</relationshipLabel>
        <relationshipName>Purchase_Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Purchase Order</label>
    <nameField>
        <label>Purchase Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Supplier__c.object
<CustomObject>
    <customHelpPage>HelpSuppliers</customHelpPage>
    <description>Supplier object</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Suppliers</relationshipLabel>
        <relationshipName>Suppliers1_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Supplier Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Supplier</label>
    <nameField>
        <label>Supplier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Supplier_Invoice__c.object
<CustomObject>
    <customHelpPage>HelpSupplierInvoice</customHelpPage>
    <description>Record invoices for items or services  that are received from a supplier.  Bills can be recorded with or without purchase orders</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Supplier Invoices</relationshipLabel>
        <relationshipName>Supplier_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Invoiced__c</fullName>
        <description>Date when the invoice happened</description>
        <label>Invoice Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Hold__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates this invoice is on hold</description>
        <label>Hold</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoice_Amount__c</fullName>
        <inlineHelpText>The invoice amount is required. Invoice cannot be approved for payment if the invoice amount does not match the total amount on each line of the invoice.</inlineHelpText>
        <label>Invoice Amount</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoice_Type__c</fullName>
        <label>Invoice Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Credit Memo</fullName>
                </value>
                <value>
                    <fullName>Invoice</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Prepayment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Memo__c</fullName>
        <description>Add memo to explain discrepancies. For example, if an item is short paid because the supplier has incorrectly put a charge enter reason in the memo.</description>
        <label>Memo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Purchase_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Purchase Order.</description>
        <label>Purchase Order</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Purchase_Order__c.Supplier__c</field>
                <operation>equals</operation>
                <valueField>$Source.Supplier__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Purchase_Order__c</referenceTo>
        <relationshipLabel>Supplier Invoices</relationshipLabel>
        <relationshipName>Supplier_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of bill</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supplier_Invoice__c</fullName>
        <description>Supplier invoice no. reference</description>
        <label>Invoice Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Remit To Supplier</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Supplier__c.Type__c</field>
                <operation>equals</operation>
                <value>Remit-To</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Supplier Invoices</relationshipLabel>
        <relationshipName>Supplier_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Extended_Price__c</fullName>
        <description>Rollup of the line extended prices</description>
        <label>Total Extended Price</label>
        <summarizedField>Supplier_Invoice_Line__c.Extended_Price__c</summarizedField>
        <summaryForeignKey>Supplier_Invoice_Line__c.Supplier_Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Supplier Invoice</label>
    <nameField>
        <label>Supplier Invoice</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/SupplierInvoiceIncompleteInspectBatch.cls
public with sharing class SupplierInvoiceIncompleteInspectBatch implements Database.Batchable<sObject>, Process.Runnable2, Database.Stateful {
    
    
    public string query;
    public Id companyId;
    public List<Notify.Message> messages = new List<Notify.Message>();
    public Schemautil util = Schemautil.getInstance();
    
    public SupplierInvoiceIncompleteInspectBatch (Id comp){
        companyId = comp;
    }

    public Database.QueryLocator start(Database.BatchableContext IC){ 
        
        set<String> fieldStrings = new set<string>{'Id','Name','CreatedById'};
    	fieldStrings.addAll(util.getAllCustomFieldsFromObject('','Supplier_Invoice__c'));
        fieldStrings.addAll(util.getAllCustomFieldsFromObject('Purchase_Order__r.','Purchase_Order__c'));
        fieldStrings.addAll(util.getAllCustomFieldsFromObject('Purchase_Order__r.Purchase_Agreement__r.','Contract__c'));

       	query = util.generateQueryFromFieldSet('Supplier_Invoice__c', new set<string>() ,fieldStrings, 'Status__c = \'Incomplete\' and Hold__c = false and Company__c=' + '\''+companyId + '\'' );
        /*   	
        query =  'Select Id, Buyer__c, Name, Invoice_Type__c, Company__c, Supplier__c, Date_Invoiced__c, Supplier_Invoice__c, Memo__c, Invoice_Amount__c, Total_Extended_Price__c, Status__c,Payment_Term__c,'+ 
                    ' Purchase_Order__c, Purchase_Order__r.Supplier__c, Purchase_Order__r.Remit_To_Supplier__c, Credit_Memo_Amount__c, Apply_To_Invoice__c '+
                    ' From Supplier_Invoice__c where Status__c = \'Incomplete\' and Hold__c = false and Company__c =:companyId '; 
        */     
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext info, List<Supplier_Invoice__c> scope){
        Savepoint sp = Database.setSavepoint(); //KNDY-2336
        
        try{
        	SupplierInvoiceService.inspectIncompleteInvoices( scope );
        }catch(Exception e) {
            Database.rollback(sp);
            messages.add(Notify.getErrorMessage(scope, e.getMessage(), e.getStackTraceString()));
        }	
    }
    
    public void finish(Database.BatchableContext info){
		BatchToChatter.processBatchInformation(info.getJobId(), this, messages);
		Notify.sendEmailBatchFinish( null, messages, info);        
		MasterControlProgram.finishedBatch( this ); 
    }
    
    public SupplierInvoiceIncompleteInspectBatch() {}
    public void runBatch( Process_Job__c job ) {
        integer defaultBatchSize = 5;
		if ( job.Batch_Size__c !=null && integer.valueOf(job.Batch_Size__c) <= 20 && integer.valueOf(job.Batch_Size__c) >= 1 ) { 
			defaultBatchSize = integer.valueOf(job.Batch_Size__c);
        }
        SupplierInvoiceIncompleteInspectBatch batch = new SupplierInvoiceIncompleteInspectBatch(job.Company__c);
        ID jobId = Database.executeBatch(batch, defaultBatchSize); 
    }  
}