src-ken&y/objects/Currency__c.object
<CustomObject>
    <customHelpPage>HelpCurrency</customHelpPage>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Currency</label>
    <nameField>
        <label>Currency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Item__c.object
<CustomObject>
    <customHelpPage>HelpItems</customHelpPage>
    <description>Item Master object</description>
    <fields>
        <fullName>Dimension_UOM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dimension UOM</label>
        <referenceTo>UOM__c</referenceTo>
        <relationshipLabel>Items (Dimension UOM)</relationshipLabel>
        <relationshipName>Items_Dimension_UOM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Weight_UOM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Unit of measure for the weight of item;  mainly used for shipping purposes</description>
        <label>Weight UOM</label>
        <referenceTo>UOM__c</referenceTo>
        <relationshipLabel>Items (Weight UOM)</relationshipLabel>
        <relationshipName>Items_Weight_UOM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <description>Weight of the item in weight UOM</description>
        <label>Weight</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Label__c.object
<CustomObject>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Labels</relationshipLabel>
        <relationshipName>Labels</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>Sales_Order__c</referenceTo>
        <relationshipLabel>Labels</relationshipLabel>
        <relationshipName>Labels</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipment_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipment Line</label>
        <referenceTo>Shipment_Line__c</referenceTo>
        <relationshipLabel>Labels</relationshipLabel>
        <relationshipName>Labels</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Label</label>
    <nameField>
        <label>Labels Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Labels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Product__c.object
<CustomObject>
    <customHelpPage>HelpProducts</customHelpPage>
    <description>Products are sellable Items with Selling Unit of Measure included</description>
    <fields>
        <fullName>Dimension_UOM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dimension UOM</label>
        <referenceTo>UOM__c</referenceTo>
        <relationshipLabel>Products (Dimension UOM)</relationshipLabel>
        <relationshipName>Products_Dimension_UOM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Item</description>
        <label>Item</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Item__c.Company__c</field>
                <operation>equals</operation>
                <valueField>$Source.Company__c</valueField>
            </filterItems>
            <filterItems>
                <field>Item__c.Company__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Layers_per_Pallet__c</fullName>
        <inlineHelpText>The number of product layers per shipping pallet.</inlineHelpText>
        <label>Layers per Pallet</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Units_per_Layer__c</fullName>
        <inlineHelpText>The number of product units that can comprise a layer on a pallet.</inlineHelpText>
        <label>Units per Layer</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Units_per_Pallet__c</fullName>
        <description>Calculated field (Units per Layer x Layers per Pallet)</description>
        <formula>Units_per_Layer__c  *  Layers_per_Pallet__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Units per Layer multiplied by Layers per Pallet.</inlineHelpText>
        <label>Units per Pallet</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Weight_UOM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Products weight unit of measure</description>
        <label>Weight UOM</label>
        <referenceTo>UOM__c</referenceTo>
        <relationshipLabel>Products (Weight UOM)</relationshipLabel>
        <relationshipName>Products1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <description>Product&apos;s weight in weight uom units</description>
        <label>Weight</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Sales_Order__c.object
<CustomObject>
    <customHelpPage>HelpSalesOrders_Managing</customHelpPage>
    <description>Sales Order Header</description>
    <fields>
        <fullName>Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to currency</description>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Sales Order Currency</relationshipLabel>
        <relationshipName>Sales_Order_Currency</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dimension_UOM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Dimension UOM field</description>
        <label>Dimension UOM</label>
        <referenceTo>UOM__c</referenceTo>
        <relationshipLabel>Sales Order (Dimension UOM)</relationshipLabel>
        <relationshipName>Sales_Order_Dimension_UOM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Weight_UOM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Weight UOM</label>
        <referenceTo>UOM__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Shipment__c.object
<CustomObject>
    <customHelpPage>HelpShipment</customHelpPage>
    <description>Sales Order Shipment Header</description>
    <fields>
        <fullName>Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to currency</description>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Shipment Currency</relationshipLabel>
        <relationshipName>Shipment_Currency</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Weight_UOM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Unit Of Measure of the Total Weight.</description>
        <label>Weight UOM</label>
        <referenceTo>UOM__c</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Shipment</label>
    <nameField>
        <label>Shipment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Shipment_Line__c.object
<CustomObject>
    <customHelpPage>HelpShipment</customHelpPage>
    <description>Shipment lines.</description>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Item that is being shipped.</description>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Shipment Lines</relationshipLabel>
        <relationshipName>Shipment_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Product</description>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Shipment Lines</relationshipLabel>
        <relationshipName>Shipment_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The sales order related to this shipment</description>
        <label>Sales Order</label>
        <referenceTo>Sales_Order__c</referenceTo>
        <relationshipLabel>Shipment Lines</relationshipLabel>
        <relationshipName>Shipment_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <description>Lookup to Shipment</description>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Shipment Lines</relationshipLabel>
        <relationshipName>Shipment_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Weight_UOM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Unit of Measure of the Total Weight.</description>
        <label>Weight UOM</label>
        <referenceTo>UOM__c</referenceTo>
        <relationshipLabel>Shipment Lines</relationshipLabel>
        <relationshipName>Shipment_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <description>Product Weight.</description>
        <label>Weight</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <label>Shipment Line</label>
    <nameField>
        <label>Shipment Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipment Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/UOM__c.object
<CustomObject>
    <customHelpPage>HelpUOM</customHelpPage>
    <description>Units of Measure.</description>
    <label>UOM</label>
    <nameField>
        <label>UOM</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UOMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/LabelsApiTest.cls
@isTest
public with sharing class LabelsApiTest {
    @testSetup
    private static void setupData() {
        TestFuel f = new TestFuel();
        System.assert(f.smrsList != null);
        System.assert(f.stockMovementRuleList != null);
        System.assert(f.itemAttrObj2 != null);
        System.assert(f.periodList != null);
        System.assert(f.purchaseOrder != null);
        System.assert(f.purchaseOrderLines != null);
        System.assert(f.supplier != null);
        System.assert(f.transferOrder != null);
        System.assert(f.transferOrderLines!=null);
        system.assert(f.salesOrder != null &&
                f.product3 != null &&
                f.location != null &&
                f.location3 != null &&
                f.pricebook != null &&
                f.uomcList != null &&
                f.uomList != null &&
                f.itemList != null &&
                f.reasonCodes != null &&
                f.itemSpec != null &&
                f.smrsList != null
        );
    }

    private static TestFuelQuery fuel = new TestFuelQuery();

    private static testMethod void transferOrderShipmentLabels() {
        OrderService.release(new Map<Id, Id>{ fuel.transferOrder.Id => null });

        fuel.setupInventory();

        SOQLUtil shipmentQuery = new SOQLUtil('Shipment__c');
        shipmentQuery.addField('Id');
        Shipment__c shipment = Database.query(shipmentQuery.getQuery());
        Map<Id, Shipment_Line__c> shipmentLines = new Map<Id, Shipment_Line__c>(ShipmentWorkbenchExt.getShipmentLines(new Map<String, Object>{ 'Shipment__c' => shipment.Id }, 'allocate'));
        System.assert(shipmentLines.size() == 2, shipmentLines);

        List<Label__c> labels = LabelsApi.generateLabels(new List<SObject>{shipment});
        System.assert(labels.size() > 0);

        Shipment_Line__c shl = shipmentLines.values().get(0);

        LabelWrapper lw = new LabelWrapper();
        lw.quantity = 1;
        lw.caseIndex = 1;
        lw.record = shl;
        lw.packagingUom = fuel.uomList[8];

        labels = LabelsApi.generateSingleLabels(new Map<Id, List<LabelWrapper>>{shl.Id => new List<LabelWrapper>{
                lw
        }});
        System.assert(labels.size() > 0);
    }

    private static testMethod void salesOrderShipmentLabels() {

        ApexPages.StandardController con;
        SOPlanExt soPlanExt;

        Test.startTest();
        final decimal OZ_LB = .0625;

        System.debug(loggingLevel.Error, ' ***** fuel.uomList :' + fuel.uomList);
        fuel.product.Weight_UOM__c = fuel.uomList[3].Id; //oz
        System.debug(loggingLevel.Error, ' ***** fuel.product :' + fuel.product);
        System.debug(loggingLevel.Error, ' ***** fuel.product.Units_per_Pallet__c :' + fuel.product.Units_per_Pallet__c);
        fuel.product.units_per_layer__c = 1;
        fuel.product.layers_per_pallet__c = 1;

        fuel.product2.units_per_layer__c = 1;
        fuel.product2.layers_per_pallet__c = 1;
        List<Product__c> productsToUpdate = new List<Product__c>{fuel.product, fuel.product2};
        update productsToUpdate;

        fuel.salesOrder.Weight_UOM__c = fuel.uomList[0].Id;
        fuel.salesOrder.Dimension_UOM__c = fuel.uomList[6].Id;
        fuel.salesOrder.Currency__c = fuel.currencyUSD.Id;

        update fuel.salesOrder;

        Sales_Order__c salesOrder = [SELECT Id, Weight_UOM__r.Name, Dimension_UOM__r.Name FROM Sales_Order__c WHERE Id = :fuel.salesOrder.Id];
        System.debug(LoggingLevel.INFO, 'fuel.product.: ' + fuel.product.Weight__c);

        con = new ApexPages.StandardController(fuel.salesOrder);
        soPlanExt = new SOPlanExt(con);
        soPlanExt.plan();

        SOQLUtil shipmentQuery = new SOQLUtil('Shipment__c');
        shipmentQuery.addField('Id');
        Shipment__c shipment = Database.query(shipmentQuery.getQuery());
        Map<Id, Shipment_Line__c> shipmentLines = new Map<Id, Shipment_Line__c>(ShipmentWorkbenchExt.getShipmentLines(new Map<String, Object>{ 'Shipment__c' => shipment.Id }, 'allocate'));
        System.assert(shipmentLines.size() == 2, shipmentLines);

        List<Label__c> labels = LabelsApi.generateLabels(new List<SObject>{shipment});
        System.assert(labels.size() > 0);

        Shipment_Line__c shl = shipmentLines.values().get(0);

        LabelWrapper lw = new LabelWrapper();
        lw.quantity = 1;
        lw.caseIndex = 1;
        lw.record = shl;
        lw.packagingUom = fuel.uomList[8];

        labels = LabelsApi.generateSingleLabels(new Map<Id, List<LabelWrapper>>{shl.Id => new List<LabelWrapper>{
                lw
        }});
        System.assert(labels.size() > 0);

        Test.stopTest();
    }

    private static testMethod void testHeterogeneousLabelsSuccess() {

        ApexPages.StandardController con;
        SOPlanExt soPlanExt;

        Test.startTest();
        final decimal OZ_LB = .0625;

        System.debug(loggingLevel.Error, ' ***** fuel.uomList :' + fuel.uomList);
        fuel.product.Weight_UOM__c = fuel.uomList[3].Id; //oz
        System.debug(loggingLevel.Error, ' ***** fuel.product :' + fuel.product);
        System.debug(loggingLevel.Error, ' ***** fuel.product.Units_per_Pallet__c :' + fuel.product.Units_per_Pallet__c);
        fuel.product.units_per_layer__c = 1;
        fuel.product.layers_per_pallet__c = 1;

        fuel.product2.units_per_layer__c = 1;
        fuel.product2.layers_per_pallet__c = 1;
        List<Product__c> productsToUpdate = new List<Product__c>{fuel.product, fuel.product2};
        update productsToUpdate;

        fuel.salesOrder.Weight_UOM__c = fuel.uomList[0].Id;
        fuel.salesOrder.Dimension_UOM__c = fuel.uomList[6].Id;
        fuel.salesOrder.Currency__c = fuel.currencyUSD.Id;

        update fuel.salesOrder;

        Sales_Order__c salesOrder = [SELECT Id, Weight_UOM__r.Name, Dimension_UOM__r.Name FROM Sales_Order__c WHERE Id = :fuel.salesOrder.Id];
        System.debug(LoggingLevel.INFO, 'fuel.product.: ' + fuel.product.Weight__c);

        con = new ApexPages.StandardController(fuel.salesOrder);
        soPlanExt = new SOPlanExt(con);
        soPlanExt.plan();

        SOQLUtil shipmentQuery = new SOQLUtil('Shipment__c');
        shipmentQuery.addField('Id');
        Shipment__c shipment = Database.query(shipmentQuery.getQuery());
        Map<Id, Shipment_Line__c> shipmentLines = new Map<Id, Shipment_Line__c>(ShipmentWorkbenchExt.getShipmentLines(new Map<String, Object>{ 'Shipment__c' => shipment.Id }, 'allocate'));
        System.assert(shipmentLines.size() == 2, shipmentLines);

        List<Label__c> labels = LabelsApi.generateLabels(new List<SObject>{shipment});
        System.assert(labels.size() > 0);

        Shipment_Line__c shl = shipmentLines.values().get(0);

        LabelWrapper lw = new LabelWrapper();
        lw.quantity = 1;
        lw.caseIndex = 1;
        lw.record = shl;
        lw.packagingUom = fuel.uomList[8];
        lw.fromType = 'Item__c';

        LabelWrapper lw1 = new LabelWrapper();
        lw1.quantity = 1;
        lw1.caseIndex = 2;
        lw1.record = fuel.salesOrderLine;
        lw1.packagingUom = fuel.uomList[8];
        lw1.fromType = 'Item__c';

        labels = LabelsApi.generateHeterogeneousLabels(new Map<Id, List<LabelWrapper>>{
                shl.Id => new List<LabelWrapper>{
                        lw
                }, fuel.salesOrderLine.Id => new List<LabelWrapper>{
                        lw1
                }
        });
        System.assert(labels.size() > 0);

        Test.stopTest();
    }

    private static testMethod void testHeterogeneousLabelsFailure() {

        ApexPages.StandardController con;
        SOPlanExt soPlanExt;

        Test.startTest();
        final decimal OZ_LB = .0625;

        System.debug(loggingLevel.Error, ' ***** fuel.uomList :' + fuel.uomList);
        fuel.product.Weight_UOM__c = fuel.uomList[3].Id; //oz
        System.debug(loggingLevel.Error, ' ***** fuel.product :' + fuel.product);
        System.debug(loggingLevel.Error, ' ***** fuel.product.Units_per_Pallet__c :' + fuel.product.Units_per_Pallet__c);
        fuel.product.units_per_layer__c = 1;
        fuel.product.layers_per_pallet__c = 1;

        fuel.product2.units_per_layer__c = 1;
        fuel.product2.layers_per_pallet__c = 1;
        List<Product__c> productsToUpdate = new List<Product__c>{fuel.product, fuel.product2};
        update productsToUpdate;

        fuel.salesOrder.Weight_UOM__c = fuel.uomList[0].Id;
        fuel.salesOrder.Dimension_UOM__c = fuel.uomList[6].Id;
        fuel.salesOrder.Currency__c = fuel.currencyUSD.Id;

        update fuel.salesOrder;

        Sales_Order__c salesOrder = [SELECT Id, Weight_UOM__r.Name, Dimension_UOM__r.Name FROM Sales_Order__c WHERE Id = :fuel.salesOrder.Id];
        System.debug(LoggingLevel.INFO, 'fuel.product.: ' + fuel.product.Weight__c);

        con = new ApexPages.StandardController(fuel.salesOrder);
        soPlanExt = new SOPlanExt(con);
        soPlanExt.plan();

        SOQLUtil shipmentQuery = new SOQLUtil('Shipment__c');
        shipmentQuery.addField('Id');
        Shipment__c shipment = Database.query(shipmentQuery.getQuery());
        Map<Id, Shipment_Line__c> shipmentLines = new Map<Id, Shipment_Line__c>(ShipmentWorkbenchExt.getShipmentLines(new Map<String, Object>{ 'Shipment__c' => shipment.Id }, 'allocate'));
        System.assert(shipmentLines.size() == 2, shipmentLines);

        List<Label__c> labels = LabelsApi.generateLabels(new List<SObject>{shipment});
        System.assert(labels.size() > 0);

        Shipment_Line__c shl = shipmentLines.values().get(0);

        LabelWrapper lw = new LabelWrapper();
        lw.quantity = 1;
        lw.caseIndex = 1;
        lw.record = shl;
        lw.packagingUom = fuel.uomList[8];
        lw.fromType = 'Item__c';

        LabelWrapper lw1 = new LabelWrapper();
        lw1.quantity = 1;
        lw1.caseIndex = 2;
        lw1.record = salesOrder;
        lw1.packagingUom = fuel.uomList[8];
        lw1.fromType = 'Item__c';
        lw1.item = fuel.itemList[8];

        try {
            labels = LabelsApi.generateHeterogeneousLabels(new Map<Id, List<LabelWrapper>>{
                    shl.Id => new List<LabelWrapper>{
                            lw
                    }, salesOrder.Id => new List<LabelWrapper>{
                            lw1
                    }
            });
            System.assert(true);
        } catch (Exception e) {
            System.assert(false, e.getMessage() );
        }
        Test.stopTest();
    }


}