src-ken&y/objects/Currency__c.object
<CustomObject>
    <customHelpPage>HelpCurrency</customHelpPage>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Currency</label>
    <nameField>
        <label>Currency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Customer__c.object
<CustomObject>
    <customHelpPage>HelpCustomers</customHelpPage>
    <description>Information that relates a Customer business to the manufacturing company (Company) and describes the business agreement between the two entities.</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The company that originates and owns the customer relationship</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Customers</relationshipLabel>
        <relationshipName>Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Customers</relationshipLabel>
        <relationshipName>Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer</label>
    <nameField>
        <label>Customer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Customer_Invoice__c.object
<CustomObject>
    <customHelpPage>HelpCustomerInvoice</customHelpPage>
    <description>Customer invoices</description>
    <fields>
        <fullName>Bill_To_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Bill To Customer</description>
        <label>Bill To Customer</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <filterItems>
                <field>Customer__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Bill To</value>
            </filterItems>
            <filterItems>
                <field>Customer__c.Parent_Customer__c</field>
                <operation>equals</operation>
                <valueField>$Source.Customer__c</valueField>
            </filterItems>
            <filterItems>
                <field>Customer__c.Top_Parent_Customer__c</field>
                <operation>equals</operation>
                <valueField>$Source.Customer__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Customer Invoices (Bill To Customer)</relationshipLabel>
        <relationshipName>Bill_To_Customer_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Customer Invoices</relationshipLabel>
        <relationshipName>Ship_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Customer Invoices</relationshipLabel>
        <relationshipName>Customer_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Customer</description>
        <label>Corporate Parent Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Customer__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Corporate Parent</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Customer Invoices</relationshipLabel>
        <relationshipName>Customer_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Invoiced__c</fullName>
        <description>Date of invoice</description>
        <label>Invoice Date</label>
        <type>DateTime</type>
    </fields>
    <label>Customer Invoice</label>
    <nameField>
        <label>Customer Invoice</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Customer_Invoice_Line__c.object
<CustomObject>
    <customHelpPage>HelpCustomerInvoice</customHelpPage>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Company.</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipName>Customer_Transaction_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <formula>Customer_Invoice__r.Currency__r.ISO_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Currency</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Invoice__c</fullName>
        <label>Customer Invoice</label>
        <referenceTo>Customer_Invoice__c</referenceTo>
        <relationshipLabel>Customer Invoice Lines</relationshipLabel>
        <relationshipName>Customer_Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Customer Invoice Line</label>
    <nameField>
        <label>Customer Invoice Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Customer_Receipt__c.object
<CustomObject>
    <customHelpPage>HelpReceipts</customHelpPage>
    <description>Records all customer receipts (checks, credit cards, EFT, etc) against invoice.</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company associated with this Customer Receipt. It should be populated with the default value for the user logged in.</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Customer Receipts</relationshipLabel>
        <relationshipName>Customer_Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Customer Receipts</relationshipLabel>
        <relationshipName>Customer_Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Customer</description>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>The user must enter either a corporate or a bill to customer</errorMessage>
            <filterItems>
                <field>Customer__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Corporate Parent</value>
            </filterItems>
            <filterItems>
                <field>Customer__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Bill To</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Customer Receipts</relationshipLabel>
        <relationshipName>Customer_Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Receipt</label>
    <nameField>
        <label>Customer Receipt</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Customer_Receipt_Line__c.object
<CustomObject>
    <customHelpPage>HelpReceipts</customHelpPage>
    <description>Payment details associated with a payment received or issued</description>
    <fields>
        <fullName>Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Customer Receipt Lines</relationshipLabel>
        <relationshipName>Customer_Receipt_Lines</relationshipName>
        <type>Lookup</type>
    </fields>    
    <fields>
        <fullName>Customer_Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Invoice</label>
        <referenceTo>Customer_Invoice__c</referenceTo>
        <relationshipName>Customer_Receipt_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill To Customer</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1</booleanFilter>
            <filterItems>
                <field>Customer__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Bill To</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Customer Receipt Lines</relationshipLabel>
        <relationshipName>Customer_Receipt_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Receipt Line</label>
    <nameField>
        <label>Payment Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Receipt Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Product__c.object
<CustomObject>
    <customHelpPage>HelpProducts</customHelpPage>
    <description>Products are sellable Items with Selling Unit of Measure included</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Reason_Code__c.object
<CustomObject>
    <customHelpPage>HelpReasonCode</customHelpPage>
    <description>Reason Code</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Reason Codes</relationshipLabel>
        <relationshipName>Reason_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Reason Code</label>
    <nameField>
        <label>Reason Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reason Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Sales_Order__c.object
<CustomObject>
    <customHelpPage>HelpSalesOrders_Managing</customHelpPage>
    <description>Sales Order Header</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to currency</description>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Sales Order Currency</relationshipLabel>
        <relationshipName>Sales_Order_Currency</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Customer</description>
        <label>Customer Sold To</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <errorMessage>Sales Order Customer value does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>Customer__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Sold To</value>
            </filterItems>
            <filterItems>
                <field>Customer__c.Company__c</field>
                <operation>equals</operation>
                <valueField>$Source.Company__c</valueField>
            </filterItems>
            <filterItems>
                <field>Customer__c.Company__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Sales Orders (Customer)</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/CustomerInvoiceWriteOffExtTest.cls
@isTest
private class CustomerInvoiceWriteOffExtTest {
	public static TestFuel tdf = new TestFuel();
	
	public static Customer_Invoice__c custInvoice
	{
		get 
		{
			if(custInvoice == null)
			{
				custInvoice = new Customer_Invoice__c();
				custInvoice.Company__c = tdf.company.Id;
				custInvoice.Customer__c = tdf.customerParent.Id;
				custInvoice.Bill_to_Customer__c = tdf.customerBillTo.Id;
				custInvoice.Currency__c = TestFuel.currencyUSD.id;
				custInvoice.date_invoiced__c = system.now();
				custInvoice.transaction_date__c = system.now();
				custInvoice.Invoice_Type__c = 'Ship Invoice';
				custInvoice.Status__c = 'Open';
				custInvoice.Sales_Order__c = tdf.salesOrder.Id;
                
			}
			 return custInvoice;
		}
		set;
	}
	
	public static Customer_Invoice_Line__c custInvoiceLine
	{
		get 
		{
			if(custInvoiceLine == null)
			{
				custInvoiceLine = new Customer_Invoice_Line__c();
				custInvoiceLine.Customer_Invoice__c = custInvoice.Id;
				custInvoiceLine.Product__c = tdf.product.Id;
				custInvoiceLine.Quantity_Shipped__c = 10;
				custInvoiceLine.Unit_Price__c = 10;
				custInvoiceLine.Extended_Price__c = 100;
                
			}
			 return custInvoiceLine;
		}
		set;
	}
	
    static testMethod void testExtension() {
    	
    	Reason_Code__c res = new Reason_Code__c(Name= 'resolution', Type__c ='Resolution');
    	insert res;
    	
    	insert custInvoice;
    	insert custInvoiceLine;
    	custInvoice.Finalized__c =true;
    	update custInvoice;
    	
    	custInvoice.Resolution_Code__c = res.Id;
    	Apexpages.Standardcontroller con = new Apexpages.Standardcontroller(custInvoice);
        CustomerInvoiceWriteOffExt ext = new CustomerInvoiceWriteOffExt(con);
        ext.writeOff();
        
        Customer_Invoice__c ci = [Select id, Balance__c, Status__c, Resolution_Code__c, (Select Id, Type__c, Customer_Receipt__c, Finalized__c from Customer_Receipt_Lines__r) from Customer_Invoice__c where id =:custInvoice.id limit 1];
        //system.debug([select id, subject from Task where whatId =:ci.Customer_Receipt_Lines__r[0].Customer_Receipt__c]);
        system.assertEquals(ci.Status__c,'Closed');
        system.assertEquals(ci.Balance__c,0);
        system.assertEquals(ci.Resolution_Code__c,res.Id);
        system.assertEquals(ci.Customer_Receipt_Lines__r.size(),1);
        system.assertEquals(ci.Customer_Receipt_Lines__r[0].Finalized__c,true);
        system.assertEquals(ci.Customer_Receipt_Lines__r[0].Type__c,PaymentService.TYPE_WRITEOFF);
    }
    
    static testMethod void testExtension_unfinalized() {
    	
    	insert custInvoice;
    	insert custInvoiceLine;
    	
    	
    	Apexpages.Standardcontroller con = new Apexpages.Standardcontroller(custInvoice);
        CustomerInvoiceWriteOffExt ext = new CustomerInvoiceWriteOffExt(con);
        system.assertEquals(ext.disableAction,true,'It should be disable as CI is not finalized');
        system.assertEquals(ApexPages.hasMessages(), true,'There should be some error messages');
        system.assert(ApexPages.getMessages()[0].getSummary().contains(Label.Cannot_writeoff_invoice_not_finalized));
        
    }
    
    static testMethod void testExtension_closed() {
    	
    	insert custInvoice;
    	insert custInvoiceLine;
    	
    	custInvoice.Finalized__c =true;
    	custInvoice.Amount_Paid__c = 100;
    	update custInvoice;
    	
    	custInvoice = [select id, Balance__c, Amount_Paid__c, Status__c from Customer_Invoice__c where id = :custInvoice.id limit 1];
    	system.debug('after update ci : '+custInvoice);
    	Apexpages.Standardcontroller con = new Apexpages.Standardcontroller(custInvoice);
        CustomerInvoiceWriteOffExt ext = new CustomerInvoiceWriteOffExt(con);
        system.assertEquals(ext.disableAction,true,'It should be disable as CI is not finalized');
        system.assertEquals(ApexPages.hasMessages(), true,'There should be some error messages');
        system.assert(ApexPages.getMessages()[0].getSummary().contains(Label.This_invoice_is_not_open));
        
    }
    
    static testMethod void testExtension_negative() {
    	
    	custInvoice.Write_Off_Amount__c = -10;
    	custInvoice.Resolution_Code__c = tdf.resolutionCode.Id;
    	custInvoice.Invoice_Type__c = 'Adjustment';
    	insert custInvoice;
    	
    	custInvoiceLine.Quantity_Shipped__c = -1;
    	insert custInvoiceLine;
    	
    	custInvoice.Finalized__c =true;
    	update custInvoice;
    	
    	Apexpages.Standardcontroller con = new Apexpages.Standardcontroller(custInvoice);
        CustomerInvoiceWriteOffExt ext = new CustomerInvoiceWriteOffExt(con);
        ext.writeOff();
        
        List<Customer_Invoice__c> ciList = [Select id, Balance__c, Status__c
        	, (Select Id, Customer_Receipt__c, Finalized__c from Customer_Receipt_Lines__r) //KNDY-13995
        	from Customer_Invoice__c where id =:custInvoice.id limit 1];
        system.assertEquals(ciList[0].Balance__c,0,'The balance is more than 0'); 
        system.assertEquals(ciList[0].Customer_Receipt_Lines__r.size(),0);
        
    }
    

    static testMethod void testExtension_WriteoffCredit() {//KNDY-19379
        custInvoice.Resolution_Code__c = tdf.resolutionCode.Id;
        custInvoice.Invoice_Type__c = 'Prepayment';
        insert custInvoice;
        
        custInvoiceLine.Quantity_Shipped__c = -1;
        insert custInvoiceLine;
        
        custInvoice.Finalized__c =true;
        update custInvoice;
        
        Apexpages.Standardcontroller con = new Apexpages.Standardcontroller(custInvoice);
        CustomerInvoiceWriteOffExt ext = new CustomerInvoiceWriteOffExt(con);
        ext.writeOff();

        List<Customer_Invoice__c> ciList = [Select id, Balance__c, Status__c
            , (Select Id, Customer_Receipt__c, Type__c, Finalized__c from Customer_Receipt_Lines__r) 
            from Customer_Invoice__c where id =:custInvoice.id limit 1];
        system.assertEquals(ciList[0].Customer_Receipt_Lines__r.size(),1);
        system.assertEquals(ciList[0].Customer_Receipt_Lines__r[0].Type__c, PaymentService.TYPE_WRITEOFF_CREDIT);
        
    }
}