src-ken&y/objects/Currency__c.object
<CustomObject>
    <customHelpPage>HelpCurrency</customHelpPage>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Currency</label>
    <nameField>
        <label>Currency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Item__c.object
<CustomObject>
    <customHelpPage>HelpItems</customHelpPage>
    <description>Item Master object</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Item description can be up to 255 characters; use extended description field if needed</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Primary_Key__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Primary Key</label>
        <length>128</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Purchase_Order__c.object
<CustomObject>
    <customHelpPage>HelpPurchaseOrders</customHelpPage>
    <description>Purchase header information</description>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>POs must be approved by user with appropriate authorization limit</description>
        <inlineHelpText>The acceptable difference, expressed as an amount, between the sales order and the related purchase order. If you choose not to enter a tolerance amount, Kenandy assumes zero tolerance.</inlineHelpText>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Pending Authorization</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to currency</description>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Purchase Order Currency</relationshipLabel>
        <relationshipName>Purchase_Order_Currency</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Closed__c</fullName>
        <description>Date PO was closed or cancelled</description>
        <label>Date Closed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Delivery_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Location where orders of type Shipment should send the inventory</description>
        <inlineHelpText>Delivery location is defined on the Facility page. You can change the default value on the PO header if you choose a location within the specified facility. At the line level, the delivery location is determined by the location specified in the PO header.</inlineHelpText>
        <label>Delivery Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Location doesn&apos;t belong to the Facility</errorMessage>
            <filterItems>
                <field>Location__c.Facility__c</field>
                <operation>equals</operation>
                <valueField>$Source.Delivery_Facility__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MRP_Plan__c</fullName>
        <description>This number, generated by MRP, references the demand that this order is fulfilling.</description>
        <label>MRP Plan</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>Date PO is placed with vendor</description>
        <label>Order Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Production_Purchase_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Original Order that created this Shipment type order</description>
        <label>Production Purchase Order</label>
        <referenceTo>Purchase_Order__c</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the Purchase Order;  PO will be kept on file after beng closed until company runs a maintenance transaction to backup and purge closed and cancelled purchase orders</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>The PO type. &quot;Standard&quot; -&gt; lists goods or services you require. &quot;Production&quot; -&gt; establishes a contract with a co-manufacturer to produce goods. &quot;Shipment&quot; -&gt; lists goods ready to be picked up.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Production</fullName>
                </value>
                <value>
                    <fullName>Standard</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Shipment</fullName>
                </value>
                <value>
                    <fullName>Drop Ship</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Purchase Order</label>
    <nameField>
        <label>Purchase Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Purchase_Order_Line__c.object
<CustomObject>
    <customHelpPage>HelpPurchaseOrders</customHelpPage>
    <description>Line items on a purchase order document</description>
    <fields>
        <fullName>Currency__c</fullName>
        <formula>Purchase_Order__r.Currency__r.ISO_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Currency</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Added__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>Date this PO line item was added</description>
        <label>Date Added</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Closed__c</fullName>
        <description>Date this line item was closed or cancelled</description>
        <label>Date Closed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Last_Changed__c</fullName>
        <defaultValue>today()</defaultValue>
        <description>Date this line item was last changed</description>
        <label>Date Last Changed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Delivery_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Location</description>
        <label>Delivery Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Location doesn&apos;t belong to facility</errorMessage>
            <filterItems>
                <field>$Source.Company__c</field>
                <operation>equals</operation>
                <valueField>Location__c.Facility__r.Company__c</valueField>
            </filterItems>
            <filterItems>
                <field>Location__c.Facility__c</field>
                <operation>equals</operation>
                <valueField>$Source.Delivery_Facility__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Purchase Order Lines (Delivery Location)</relationshipLabel>
        <relationshipName>Purchase_Order_Lines1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Add description for non inventoried items;  the description will be added automatically for inventoried items. Use the notes field for other information about this detail line</description>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Line__c</fullName>
        <description>Line number on the purchase order</description>
        <label>Line</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MRP_Plan__c</fullName>
        <description>MRP Plan reference</description>
        <label>MRP Plan</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Quantity__c</fullName>
        <description>Quantity of items ordered on this line</description>
        <label>Order Quantity</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Primary_Key__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Primary Key</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Purchase_Order__c</fullName>
        <description>Purchase order number</description>
        <label>Purchase Order</label>
        <referenceTo>Purchase_Order__c</referenceTo>
        <relationshipLabel>Purchase Order Lines</relationshipLabel>
        <relationshipName>Purchase_Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity_Received__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Total quantity received on this purchase order</description>
        <label>Quantity Received</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity_Returned_to_Supplier__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Quantity returned to supplier for replacement</description>
        <label>Quantity Returned for Replacement</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity_Still_Due__c</fullName>
        <description>Quantity Still Due equals Order Quantity minus Quantity in Received Quantity Returned to Supplier minus Quantity Returned to Supplier for Credit</description>
        <formula>IF(  NOT(ISPICKVAL(Status__c, &apos;Open&apos;))  , 0, 

IF( (Order_Quantity__c - Quantity_Received__c + Quantity_Returned_to_Supplier__c) &lt;=0 , 0 , 

Order_Quantity__c - Quantity_Received__c + Quantity_Returned_to_Supplier__c ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Quantity Still Due equals (=) Order Quantity minus (-) Quantity Received plus (+) Quantity Returned to Supplier minus (-) Quantity Returned to Supplier for Credit.</inlineHelpText>
        <label>Quantity Still Due</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Select PO status: open, closed, cancelled, blanket planned, blanket released</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Suppliers_Part_Description__c</fullName>
        <description>Supplier&apos;s part description</description>
        <label>Supplier&apos;s Part Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Goods</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Expense</fullName>
                </value>
                <value>
                    <fullName>Asset</fullName>
                </value>
                <value>
                    <fullName>Drop Ship</fullName>
                </value>
                <value>
                    <fullName>Back To Back</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Quoted unit price</description>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <label>Purchase Order Line</label>
    <nameField>
        <label>Purchase Order Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/classes/PurchaseOrderSplitExt.cls
public with sharing class PurchaseOrderSplitExt {
	/* 
	 * spilt a production purchase order into a shipment order, decrementing the values on the production order
	 */
	private ApexPages.StandardController controller;
	
    public boolean setuperror {get; private set;} { setuperror = false; } 
    
    public PurchaseOrderSplitExt (ApexPages.StandardController c) {        
    	controller = c;    
    	Purchase_Order__c po = (Purchase_Order__c)controller.getRecord();
    	OrderLines = new List<OrderLine>(); 
    	for ( Purchase_Order_Line__c tmp : getLines() ) {
    		OrderLines.add ( new OrderLine( tmp) );
    	}
    	
    	if ( po.type__c != 'Production') {
    		 ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, 
					Label.ShipmentOrders_created_from_production_PurchaseOrders));
    		setuperror = true;
    	}
    	if ( po.Status__c != 'Open') {
    		 ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, 
					Label.ShipmentOrders_created_from_open_production_PurchaseOrders));
    		setuperror = true;
    	}
    }
    
    public List<OrderLine> OrderLines {get; set; }  
    
	public class OrderLine { 
		public decimal Quantity_To_Split {get; set; }
		public boolean selected { get; set; }  
		public Purchase_Order_Line__c poLine {get; set; } 
		public OrderLine(Purchase_Order_Line__c p ) { poLine = p; Quantity_To_Split = 0; } 
	} 
	
	public PageReference saveChild() { 
		
		// first verify that there were some lines entered, or thow a message
		integer have_a_line = 0;
		for ( OrderLine ol : OrderLines) {
			if ( ol.Quantity_To_Split > 0 ) {				have_a_line++;			}		
		}
		if ( have_a_line == 0 ) {
           ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, 
					Label.No_quantity_to_allocate_to_the_new_Purchase_order));
			return null;
		}
		
		// ready to go...
		// split info from the header and the lines selected / edited into a new order ( like a clone but receives quantity )
		Purchase_Order__c oldPO = (Purchase_Order__c)controller.getRecord();    
        Purchase_Order__c newPO = oldPO.clone(false,true);
        
        newPO.Approval_Status__c = 'Pending Authorization';
        newPO.Date_Closed__c = null;
        newPO.Order_Date__c = system.today();
        newPO.Status__c = 'Open';    
        newPO.Production_Purchase_Order__c = oldPO.id;
        newPO.Type__c = 'Shipment'; 
        newPO.Delivery_Location__c = oldPO.Delivery_Location__c; // this is bound to the page , snag it here

        Savepoint sp = Database.setSavepoint();
        
        try {
        		List<Purchase_Order_Line__c> POLListOrig = new List<Purchase_Order_Line__c> ();
        		List<Purchase_Order_Line__c> POLListNew = new List<Purchase_Order_Line__c> ();
        		
            	DML.insertAsUser( new list<sobject>{ newPO } );
         
	        	for ( OrderLine ol : OrderLines ) {
	        		
	        		if ( ol.Quantity_To_Split == 0.0 ) { continue; }
	        		
	        		Purchase_Order_Line__c oldPOLobject = ol.poLine;
	        		Purchase_Order_Line__c newPOLObject = oldPOLObject.clone(false,true);
		            	            
	        		if ( ol.Quantity_To_Split > oldPOLobject.Quantity_Still_Due__c ) { 
		        		// over allocated, bad...
		        		throw new QuantityException (Label.Cannot_ship_greater_than_Quantity_Still_Due);
		        	}
		        	
        			newPOLObject.Date_Added__c = system.today();
				newPOLObject.Date_Closed__c = null;
				newPOLObject.Date_Last_Changed__c = system.today();
				newPOLObject.MRP_Plan__c = null;           
				newPOLObject.Purchase_Order__c = newPO.ID;
				newPOLObject.Quantity_Returned_to_Supplier__c = 0.0;
				newPOLObject.Status__c = 'Open';
				newPOLObject.Order_Quantity__c = ol.Quantity_To_Split;
				newPOLObject.Quantity_Received__c = 0.0;
				newPOLObject.Primary_Key__c = null; // if the original had this field , we cannot carry it forward, it's a unique field
				
    				// infact, all Shipment lines for a Shipment order are set to a single location, got it?
		        	newPOLObject.Delivery_Location__c = oldPO.Delivery_Location__c;
		        	
		        POLListNew.add(newPOLObject);
		        	
		        	// now modify the old lines and update them also....
		        	oldPOLobject.Quantity_Received__c = KSE.addQuantityToField( oldPOLobject.Quantity_Received__c , ol.Quantity_To_Split );
		        	 
	        		POLListOrig.add(oldPOLobject); 
	        	}

			DML.updateAsUser( POLListOrig );
	        	DML.insertAsUser( POLListNew );  // update the old lines and insert the new lines 
	      	
        } catch (Exception e) {
	        	ApexPages.addMessages(e); 
	        	Database.rollback(sp);
        		return null;
        }
		
		// take them to the new record
		return new Apexpages.Standardcontroller( newPO ).view();
	}
	
	public class QuantityException extends Exception {} 
	
	private List<Purchase_Order_Line__c> getLines() { 

		//KNDY-10473: Adding CRUD/FLS checks with SOQLUtil
		Id conId = controller.getId();
		
		SOQLUtil soql = new SOQLUtil('Purchase_Order_Line__c', true); //enforceFLS=true, running in user mode
		soql.addFields(new set<string>{
			'SystemModstamp','Name','LastModifiedDate','LastModifiedById','Unit_Price__c','Type__c','Currency__c',
			'Suppliers_Part_Description__c','Supplier_Part__c','Status__c','Special_Notes__c','Rush_Line__c','Requisition_Number__c',
			'Quantity_Still_Due__c','Quantity_Returned_to_Supplier_for_Credit__c','Quantity_Returned_to_Supplier__c','Quantity_Received__c',
			'Purchase_UOM__c','Purchase_Order__c','Purchase_Order_Number__c','Promise_Date__c','Primary_Key__c','Overage_Quantity__c',
			'Overage_Percentage__c','Order_Quantity__c','Need_Date__c','Manufacturers_Part__c','MRP_Plan__c','Line__c','Line_Value__c',
			'Latest_Promise_Date__c','Item__c','Item_Name__c','Indirect__c','Description__c','Delivery_Location__c','Days_from_Promised__c',
			'Date_Last_Changed__c','Date_Closed__c','Date_Added__c','Company__c'
		});
		soql.setWhereClause('Purchase_Order__c = :conId');
		soql.setOrderByClause('Line__c asc');

		return Database.query(soql.getQuery());

	}
	
}