src-ken&y/objects/Customer_Invoice__c.object
<CustomObject>
    <customHelpPage>HelpCustomerInvoice</customHelpPage>
    <description>Customer invoices</description>
    <fields>
        <fullName>Amount_Applied__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Amount Applied to this invoice</description>
        <label>Amount Applied</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Amount_Paid__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Total amount paid so far against this invoice</description>
        <label>Amount Paid</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Changed_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>DO NOT ADD TO LAYOUT - this field tracks when new payments have been applied to a customer invoice</description>
        <label>Changed Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Deduction_Amount__c</fullName>
        <description>Amount deducted via the cash application process</description>
        <label>Deduction Amount</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Write_Off_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Input field on Visualforce Page CustomerPaymentPage.(Do not use on Page Layout)</description>
        <label>Write Off Amount</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Customer Invoice</label>
    <nameField>
        <label>Customer Invoice</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/ApplyPaymentsBatch.cls
public with sharing class ApplyPaymentsBatch implements Database.batchable<sObject>,Database.stateful, Process.Runnable {
    
    public string query;
    public set<Id> operatingCompanyIds = new set<Id>();
    
    public void runBatch( id CompanyId  ) {				// Process.Runnable implementation 
    		Database.executebatch( new ApplyPaymentsBatch( new set<id>{CompanyId} ),200);
    }
    
    public ApplyPaymentsBatch() {}  // no-arg constructor needed by Runnable

    public ApplyPaymentsBatch(set<id> OperatingCoIds){
        OperatingCompanyIDs = OperatingCoIds;
        // Select Invoices with changed equal true and pull related list of Payment Details to sum up
        query = 'select id, name, Amount_Paid__c, Write_off_Amount__c, Deduction_Amount__c, Amount_Applied__c '+
                //' (select id, name, Amount__c, Type__c from Payment_Lines__r)' + KNDY-2291
                'from Customer_Invoice__c where Changed_Flag__c=true ';        
    }
    
    public Database.QueryLocator start(Database.BatchableContext BC){ 
        //system.debug('Start query:'+query);        
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext info, List<Customer_Invoice__c> scope){
        CustomerInvoiceService.sumInvoicePayments(scope);
    }
    
    public void finish(Database.BatchableContext info){
    		MasterControlProgram.finishedBatch( this ); 	// allows the MCP to chain batches if configured to do so
    }
    

}