src-ken&y/objects/Customer_Invoice_Line__c.object
<CustomObject>
    <customHelpPage>HelpCustomerInvoice</customHelpPage>
    <fields>
        <fullName>Sales_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Sales Order Line.</description>
        <label>Sales Order Line</label>
        <referenceTo>Sales_Order_Line__c</referenceTo>
        <relationshipLabel>Customer Invoice Lines</relationshipLabel>
        <relationshipName>Customer_Transaction_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipment_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Shipment Line.</description>
        <label>Shipment Line</label>
        <referenceTo>Shipment_Line__c</referenceTo>
        <relationshipLabel>Customer Invoice Lines</relationshipLabel>
        <relationshipName>Customer_Invoice_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Shipment.</description>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipName>Customer_Transaction_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Invoice Line</label>
    <nameField>
        <label>Customer Invoice Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Order__c.object
<CustomObject>
    <customHelpPage>HelpOrder</customHelpPage>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Order_Line__c.object
<CustomObject>
    <customHelpPage>HelpOrder</customHelpPage>
    <description>The order lines for the related order object.</description>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Lines</relationshipLabel>
        <relationshipName>Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order Line</label>
    <nameField>
        <label>Order Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Receipt_Line__c.object
<CustomObject>
    <customHelpPage>HelpReceivingDocument</customHelpPage>
    <description>Purchase order receipts</description>
    <fields>
        <fullName>Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Line</label>
        <referenceTo>Order_Line__c</referenceTo>
        <relationshipLabel>Receipt Lines</relationshipLabel>
        <relationshipName>Receipt_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Receipt Lines</relationshipLabel>
        <relationshipName>Receipt_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order Line</label>
        <referenceTo>Sales_Order_Line__c</referenceTo>
        <relationshipLabel>Receipt Lines</relationshipLabel>
        <relationshipName>Receipt_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipment_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>reference to the shipment line to say this receipt is against which shipment</description>
        <label>Shipment Line</label>
        <referenceTo>Shipment_Line__c</referenceTo>
        <relationshipLabel>Receipt Lines</relationshipLabel>
        <relationshipName>Receipt_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Line status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Receipt Line</label>
    <nameField>
        <label>Receipt Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Receipt Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Sales_Order__c.object
<CustomObject>
    <customHelpPage>HelpSalesOrders_Managing</customHelpPage>
    <description>Sales Order Header</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>Order status</description>
        <label>Order Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>On hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Adjustment</fullName>
                </value>
                <value>
                    <fullName>RMA-Credit</fullName>
                </value>
                <value>
                    <fullName>RMA-Customer-Repair</fullName>
                </value>
                <value>
                    <fullName>RMA-Replacement</fullName>
                </value>
                <value>
                    <fullName>Resale</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Sales_Order_Line__c.object
<CustomObject>
    <customHelpPage>HelpSalesOrders_Managing</customHelpPage>
    <description>Line Items on the Sales Order.</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>Line open if item is not shipped; line closed if shipped; line partial if partially shipped</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type indicates the sales order line type. (eg. RMA, Kit, Kit-Child, etc...). Based on the value the Sales order line flow is controlled through different status.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>RMA</fullName>
                </value>
                <value>
                    <fullName>Kit</fullName>
                </value>
                <value>
                    <fullName>Kit-Child</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <label>Sales Order Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Shipment__c.object
<CustomObject>
    <customHelpPage>HelpShipment</customHelpPage>
    <description>Sales Order Shipment Header</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>Released</fullName>
                </value>
                <value>
                    <fullName>Staged</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Determines whether the shipment is used to fulfill a sales order or a transfer order.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sales Order Shipment</fullName>
                </value>
                <value>
                    <fullName>Transfer Order Shipment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Shipment</label>
    <nameField>
        <label>Shipment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Shipment_Line__c.object
<CustomObject>
    <customHelpPage>HelpShipment</customHelpPage>
    <description>Shipment lines.</description>
    <fields>
        <fullName>Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Line</label>
        <referenceTo>Order_Line__c</referenceTo>
        <relationshipLabel>Shipment Lines</relationshipLabel>
        <relationshipName>Shipment_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Shipment Lines</relationshipLabel>
        <relationshipName>Shipment_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to sales order line</description>
        <label>Sales Order Line</label>
        <referenceTo>Sales_Order_Line__c</referenceTo>
        <relationshipLabel>Shipment Lines</relationshipLabel>
        <relationshipName>Shipment_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <description>Lookup to Shipment</description>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Shipment Lines</relationshipLabel>
        <relationshipName>Shipment_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Shipment Line</label>
    <nameField>
        <label>Shipment Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipment Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/classes/ShipmentUndoConfirmExt.cls
public with Sharing Class ShipmentUndoConfirmExt{
    
    private ApexPages.StandardController con;
    public Boolean errorFound = false;
    string sourceDocument='';
    string shipmentStatusMessage='';
    public ShipmentUndoConfirmExt(ApexPages.StandardController sc){
         
        con = sc;
        Id shipmentId = con.getId();
         
        //KNDY-10473: Adding CRUD/FLS checks with SOQLUtil
		
		SOQLUtil soql = new SOQLUtil('Shipment_Line__c', true); //enforceFLS=true, running in user mode
		soql.addFields(new set<string>{
			'Id','Sales_Order_Line__c','Order_Line__c','shipment__r.status__c', 'shipment__r.type__c','Order__r.Status__c','Sales_Order__r.Status__c','Sales_Order__r.Released_to_3PL__c',
			'Item__r.Packaging_UOM__c'
		});
		soql.setWhereClause('Shipment__c = :shipmentId');
		
		SOQLUtil.ChildRelationship childRel1 = new SOQLUtil.ChildRelationship(soql, 'Receipt_Lines__r');
		childRel1.addFields(new set<string>{
			'id'
		});
		childRel1.setWhereClause('status__c not in (\'Void\',\'Cancelled\')');
		soql.addChildRelationship(childRel1);
		
		SOQLUtil.ChildRelationship childRel2 = new SOQLUtil.ChildRelationship(soql, 'Customer_Invoice_Lines__r');
		childRel2.addFields(new set<string>{
			'Id'
		});
		childRel2.setWhereClause('Customer_Invoice__r.Status__c != \'Cancelled\' AND Customer_Invoice__r.Status__c != \'Void\'');
		soql.addChildRelationship(childRel2);
		
		Map<id,Shipment_Line__c> shipLines = NEW Map<id,Shipment_Line__c>((List<Shipment_Line__c>)Database.query(soql.getQuery()));

         integer receiptLinesCount = 0;   

         integer linesCICount = 0;
         Boolean invalidshipmentType = false;
         
    	 for(Shipment_Line__c sl:shipLines.values())
    	 {
    		if(sl.Receipt_Lines__r.size()>0)
    			receiptLinesCount += sl.Receipt_Lines__r.size();
    		if(sl.Customer_Invoice_Lines__r.size() > 0)
    			linesCICount += sl.Customer_Invoice_Lines__r.size();
    		if(sl.shipment__r.type__c != 'Transfer Order Shipment' && invalidshipmentType == false){
        		invalidshipmentType = true;
         	}
    	 }
    	 if(invalidshipmentType){
    	 	errorFound = true;
    	 	shipmentStatusMessage = 'You can only undo shipment of type Transfer Order Shipment. Please use Manage Delivery page.';
        	
        	return;
         }
    	 if(linesCICount > 0)  //OTC-518
    	 {
    	 	errorFound = true;
    	 	shipmentStatusMessage = 'The sales order linked to the shipment has been invoiced. This shipment cannot be undone'; 
    	 }
    	 if(receiptLinesCount>0){
        	errorFound = true;
        	shipmentStatusMessage = 'The shipment is partially/fully received. This shipment cannot be undone';
    	 }
    
        if(shipmentStatusMessage=='')
        {
            if(shipLines.values()[0].shipment__r.status__c!='Confirmed' && shipLines.values()[0].shipment__r.status__c!='Delivered')
            {
            	errorFound = true;
            	shipmentStatusMessage = 'The shipment is in '+ shipLines.values()[0].shipment__r.status__c + ' Status. Only Confirmed or Delivered Shipments can be Undone';
            }
            else
            {
            	shipmentStatusMessage ='';
	            if(shipLines.values()[0].Sales_Order_Line__c!=null) 
	            {  
			      	if (shipLines.values()[0].Sales_Order__r.Status__c == 'Open' && shipLines.values()[0].Sales_Order__r.Released_to_3PL__c == true) 
			      	{
			        	errorFound = true;
			        	sourceDocument = 'Sales Order';	            
			        }  
	            }
	            if(shipLines.values()[0].Order_Line__c!=null) 
	            {  
			      	if (shipLines.values()[0].Order__r.Status__c != 'Open') 
			      	{
			      		sourceDocument = 'Transfer Order';
			        	errorFound = true;
			        }  
	            }
            }
        }
    }
    
    public PageReference undoShipConfirm(){
        
        try{
        	if(shipmentStatusMessage!='')
        	{
        		ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, shipmentStatusMessage));
        		return null;
        	}
        	if(errorFound == true && sourceDocument!='Transfer Order'){
        		ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, Label.SO_released_to_3PL));
        	}
        	else if(errorFound == true  && sourceDocument=='Transfer Order'){
        		ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, 'Transfer Order is CLosed. No Modification allowed.'));
        	}            	
        	else{
            	SalesOrderService sos = new SalesOrderService();
            	sos.undoShipConfirm(new Set<Id>{con.getId()});
            
            	ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.INFO, Label.Shipment_unconfirmed));
        	}
            
        }
        catch( Exception e ){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, MessageUtil.toFriendlyErrorMessage(e.getMessage())));
			system.debug(LoggingLevel.Error, 'EXCEPTION: ' + e.getMessage() + ' ' + e.getStackTraceString());
        }
        
        return null; 
    }
}