src-ken&y/objects/Customer__c.object
<CustomObject>
    <customHelpPage>HelpCustomers</customHelpPage>
    <description>Information that relates a Customer business to the manufacturing company (Company) and describes the business agreement between the two entities.</description>
    <label>Customer</label>
    <nameField>
        <label>Customer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Facility__c.object
<CustomObject>
    <customHelpPage>HelpFacilites</customHelpPage>
    <description>Warehouse or building</description>
    <label>Facility</label>
    <nameField>
        <label>Facility</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Product__c.object
<CustomObject>
    <customHelpPage>HelpProducts</customHelpPage>
    <description>Products are sellable Items with Selling Unit of Measure included</description>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the product is the primary product in the upc group i.e, if the product is actually registered for UPC.</description>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UPC_Code__c</fullName>
        <description>13 char UPC code</description>
        <label>UPC Code</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Substitution__c.object
<CustomObject>
    <customHelpPage>HelpSubstitution</customHelpPage>
    <fields>
        <fullName>Current_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The current product that the substitution should apply to.</description>
        <label>Current Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipName>Product_Selections</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Sold-to / Ship-to Customer to which the substitution should apply to.</description>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Customer__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Sold To, Ship To</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Substitutions</relationshipLabel>
        <relationshipName>Product_Selections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>The date on which the substitution is effective until.</description>
        <inlineHelpText>Date on which the block or substitution ends. The end date must be greater than the start date.</inlineHelpText>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Facility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The facility to which the substitution should apply to.</description>
        <label>Facility</label>
        <referenceTo>Facility__c</referenceTo>
        <relationshipName>Product_Selections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <formula>Current_Product__r.Primary__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>A check mark indicates that  the current product is the primary product.</inlineHelpText>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>The date on which the substitution is effective from.</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>UPC__c</fullName>
        <description>UPC Code from the Current Product.</description>
        <formula>Current_Product__r.UPC_Code__c</formula>
        <label>UPC</label>
        <type>Text</type>
    </fields>
    <label>Substitution</label>
    <nameField>
        <label>Substitution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Substitutions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/User_Preference__c.object
<CustomObject>
    <customHelpPage>HelpUserPreference</customHelpPage>
    <description>Track individual user preferences or configurations</description>
    <fields>
        <fullName>Default_Facility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Facility</description>
        <inlineHelpText>The default company facility to which a user belongs. This controls access to inventory transfer and inventory change records.</inlineHelpText>
        <label>Default Facility</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Default Facility does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>Facility__c.Company__c</field>
                <operation>equals</operation>
                <valueField>$Source.Default_Company__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Facility__c</referenceTo>
        <relationshipLabel>User Preferences</relationshipLabel>
        <relationshipName>User_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Preference</label>
    <nameField>
        <label>User Preference Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Preferences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/SubstitutionExt.cls
public with sharing class SubstitutionExt extends GridRelatedListController {
	
	ApexPages.StandardController con;
	private static SchemaUtil util = SchemaUtil.getInstance();
	
	public GridRelatedListController.GridRelatedListConfig SubstitutionsConfig {get; set;}
	
	public String getSubstitutionsConfigJson() {
        String configStr = JSON.serialize(this.SubstitutionsConfig);
        return configStr;
    }
    
    public String SubstitutionsFieldList = null;
	public String previousPage { get; set; }
	public Id defaultFacility{ get; set;}
    public string NamespaceUU { get { return KSE.NamespaceUU; }}
    
	public SubstitutionExt(ApexPages.StandardController scon){
		con = scon;
        previousPage = ApexPages.currentPage().getHeaders().get('Referer');
        
        //KNDY-10473: Adding CRUD/FLS checks with SOQLUtil
		
		SOQLUtil soql = new SOQLUtil('User_Preference__c', true); //enforceFLS=true, running in user mode
		soql.addFields(new set<string>{
			'Id','Default_Facility__c'
		});
		soql.setWhereClause('OwnerId = :UserInfo.getUserID()');
		soql.setLimit(1);

		List<User_Preference__c> u = Database.query(soql.getQuery());

        if (u.size() > 0){
	        if (u[0].Default_Facility__c != null)
	        	defaultFacility = u[0].Default_Facility__c;
        }		
        
        // Substitutions Grid config
        SubstitutionsConfig = new GridRelatedListController.GridRelatedListConfig();
        SubstitutionsConfig.uniqueId = 'SubstitutionsGrid';
        SubstitutionsConfig.title = 'Substitutions';
        SubstitutionsConfig.objectName = 'Substitution__c';
        SubstitutionsConfig.fieldset = 'Substitution_Edit';
        SubstitutionsConfig.buttons = 'create, delete, save, cancel, search';
        SubstitutionsConfig.alwaysUseFullDateTimeFormat = false;
    }
	
	public string getSubstitutionsFieldList() {
        if (SubstitutionsFieldList == null && SubstitutionsConfig != null) {
        	
        	FieldInfo fieldInfoItem;
        	// get the Substitutions field info list
            
            List<FieldInfo> fieldInfoList = FieldInfo.fetchJsonFieldInfos(SubstitutionsConfig.objectName, SubstitutionsConfig.fieldset);
            Set<String> hiddenFields = new Set<String> { 'Id'};
            
            // set all the fields as readonly
            for(Integer i = 0; i < fieldInfoList.size(); i++){
            	String fieldName = fieldInfoList[i].field;
            	fieldInfoList[i].field = fieldName;
            	if(! ( fieldName.endsWith('UPC__c') || fieldName.endsWith('Primary__c') ) ){
            	    fieldInfoList[i].editable = true;
            	}
            	else{
            	    fieldInfoList[i].editable = false;
            	}
            	fieldInfoList[i].hidden = hiddenFields.contains(fieldName);
            }
            
            SubstitutionsFieldList = JSON.serialize(fieldInfoList);
        }
        
        return SubstitutionsFieldList;
    }
    
    @RemoteAction
	public static JsonResult getSubstitutions(String upc, String productId, String primaryFlag, String customerId, String facilityId, String startDateString, String endDateString) {
		JsonResult result = new JsonResult();
		List<Substitution__c> substitutionList = new List<Substitution__c>();
        
        List<String> filters = new List<String>();
        
        if(upc != null && upc != ''){
            filters.add('Current_Product__r.UPC_Code__c = :upc');
        }
        
        if(productId != null && productId != ''){
            filters.add('Current_Product__c = :productId');
        }
        
        // Filter by primary only if primary is set, else display all results.
        Boolean primary = Boolean.valueOf(primaryFlag);
        if(primary){
            filters.add('Primary__c = true');
        }
        
        if(customerId != null && customerId != ''){
            filters.add('Customer__c = :customerId');
        }
        
        if(facilityId != null && facilityId != ''){
            filters.add('Facility__c = :facilityId');
        }
        
        if(startDateString != null && startDateString != ''){
            Date startDate = Date.parse(startDateString);
            filters.add('Start_Date__c >= :startDate');
        }
        
        if(endDateString != null && endDateString != ''){
            Date endDate = Date.parse(endDateString);
            filters.add('End_Date__c <= :endDate');
        }
        
        Iterator<String> iFilters = filters.iterator();
        
        String whereClause = '';
        
        while(iFilters.hasNext()){
            whereClause += iFilters.next();
            
            if(iFilters.hasNext()){
                whereClause += ' and ';    
            }
        }
        
        SOQLUtil soql = new SOQLUtil('Substitution__c');
	    soql.addFields('Substitution_Edit');
	    soql.setWhereClause(whereClause);
	    
	    substitutionList.addAll((List<Substitution__c>) Database.query(soql.getQuery()));
	    
		result.records = substitutionList;
        result.total = substitutionList.size();
        
        return result;
	}

}