src-ken&y/objects/Customer__c.object
<CustomObject>
    <customHelpPage>HelpCustomers</customHelpPage>
    <description>Information that relates a Customer business to the manufacturing company (Company) and describes the business agreement between the two entities.</description>
    <fields>
        <fullName>Sales_Tax_Rate__c</fullName>
        <label>Sales Tax Rate</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Percent</type>
    </fields>
    <label>Customer</label>
    <nameField>
        <label>Customer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Customer_Invoice__c.object
<CustomObject>
    <customHelpPage>HelpCustomerInvoice</customHelpPage>
    <description>Customer invoices</description>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If you want to ship an entire sales order in this shipment, you must enter a sales order; you can override this in each shipment line.</description>
        <inlineHelpText>If you want to ship an entire sales order in this shipment, you must enter a sales order; you can override this in each shipment line.</inlineHelpText>
        <label>Sales Order</label>
        <referenceTo>Sales_Order__c</referenceTo>
        <relationshipLabel>Customer Invoices</relationshipLabel>
        <relationshipName>Customer_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ship_to_City__c</fullName>
        <label>Ship to City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Street__c</fullName>
        <label>Ship to Street</label>
        <type>TextArea</type>
    </fields>
    <label>Customer Invoice</label>
    <nameField>
        <label>Customer Invoice</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Customer_Invoice_Line__c.object
<CustomObject>
    <customHelpPage>HelpCustomerInvoice</customHelpPage>
    <fields>
        <fullName>Customer_Invoice__c</fullName>
        <label>Customer Invoice</label>
        <referenceTo>Customer_Invoice__c</referenceTo>
        <relationshipLabel>Customer Invoice Lines</relationshipLabel>
        <relationshipName>Customer_Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sales_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Sales Order Line.</description>
        <label>Sales Order Line</label>
        <referenceTo>Sales_Order_Line__c</referenceTo>
        <relationshipLabel>Customer Invoice Lines</relationshipLabel>
        <relationshipName>Customer_Transaction_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Sales Order.</description>
        <inlineHelpText>If you want to ship an entire sales order in this shipment, you must enter a sales order; you can override this in each shipment line.</inlineHelpText>
        <label>Sales Order</label>
        <referenceTo>Sales_Order__c</referenceTo>
        <relationshipLabel>Customer Invoice Lines</relationshipLabel>
        <relationshipName>Customer_Invoice_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Tax_Rate__c</fullName>
        <label>Sales Tax Rate</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Sales_Tax__c</fullName>
        <label>Sales Tax Amount</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <label>Customer Invoice Line</label>
    <nameField>
        <label>Customer Invoice Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Purchase_Order__c.object
<CustomObject>
    <customHelpPage>HelpPurchaseOrders</customHelpPage>
    <description>Purchase header information</description>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related Sales Order.</description>
        <label>Sales Order</label>
        <referenceTo>Sales_Order__c</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Purchase Order</label>
    <nameField>
        <label>Purchase Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Sales_Order__c.object
<CustomObject>
    <customHelpPage>HelpSalesOrders_Managing</customHelpPage>
    <description>Sales Order Header</description>
    <fields>
        <fullName>Sales_Tax__c</fullName>
        <label>Sales Tax Amount</label>
        <summarizedField>Sales_Order_Line__c.Sales_Tax__c</summarizedField>
        <summaryFilterItems>
            <field>Sales_Order_Line__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Cancelled</value>
        </summaryFilterItems>
        <summaryForeignKey>Sales_Order_Line__c.Sales_Order__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Ship_to_City__c</fullName>
        <description>City where Sales Order should be shipped to. Defaults from Customer - Account - Shipping City.</description>
        <label>Ship-to City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Street__c</fullName>
        <description>Streetwhere Sales Order should be shipped to. Defaults from Customer - Account - Shipping Street.</description>
        <label>Ship-to Street</label>
        <type>TextArea</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Sales_Order_Line__c.object
<CustomObject>
    <customHelpPage>HelpSalesOrders_Managing</customHelpPage>
    <description>Line Items on the Sales Order.</description>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <label>Sales Order</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Company does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>Sales_Order__c.Company__c</field>
                <operation>equals</operation>
                <valueField>$Source.Company__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Sales_Order__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sales_Tax_Rate__c</fullName>
        <label>Sales Tax Rate</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Sales_Tax__c</fullName>
        <label>Sales Tax Amount</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <label>Sales Order Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Shipment__c.object
<CustomObject>
    <customHelpPage>HelpShipment</customHelpPage>
    <description>Sales Order Shipment Header</description>
    <fields>
        <fullName>Ship_to_Street__c</fullName>
        <label>Ship-to Street</label>
        <type>TextArea</type>
    </fields>
    <label>Shipment</label>
    <nameField>
        <label>Shipment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Shipment_Line__c.object
<CustomObject>
    <customHelpPage>HelpShipment</customHelpPage>
    <description>Shipment lines.</description>
    <fields>
        <fullName>Sales_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to sales order line</description>
        <label>Sales Order Line</label>
        <referenceTo>Sales_Order_Line__c</referenceTo>
        <relationshipLabel>Shipment Lines</relationshipLabel>
        <relationshipName>Shipment_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The sales order related to this shipment</description>
        <label>Sales Order</label>
        <referenceTo>Sales_Order__c</referenceTo>
        <relationshipLabel>Shipment Lines</relationshipLabel>
        <relationshipName>Shipment_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Shipment Line</label>
    <nameField>
        <label>Shipment Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipment Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Supplier_Invoice__c.object
<CustomObject>
    <customHelpPage>HelpSupplierInvoice</customHelpPage>
    <description>Record invoices for items or services  that are received from a supplier.  Bills can be recorded with or without purchase orders</description>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Sales Order.</description>
        <label>Sales Order</label>
        <referenceTo>Sales_Order__c</referenceTo>
        <relationshipLabel>Supplier Invoices</relationshipLabel>
        <relationshipName>Supplier_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ship_From_City__c</fullName>
        <label>DEPRECATED</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_From_Country__c</fullName>
        <label>DEPRECATED</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_From_State__c</fullName>
        <label>DEPRECATED</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_From_Street__c</fullName>
        <label>DEPRECATED</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Ship_From_Zip_Code__c</fullName>
        <label>DEPRECATED</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Street__c</fullName>
        <label>DEPRECATED</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Supplier_Invoice__c</fullName>
        <description>Supplier invoice no. reference</description>
        <label>Invoice Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Supplier Invoice</label>
    <nameField>
        <label>Supplier Invoice</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Supplier_Invoice_Line__c.object
<CustomObject>
    <customHelpPage>HelpSupplierInvoice</customHelpPage>
    <fields>
        <fullName>Invoice_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>lookup from credit memo line of type invoice to an invoice line.</description>
        <label>Invoice Line</label>
        <referenceTo>Supplier_Invoice_Line__c</referenceTo>
        <relationshipLabel>Supplier Invoice Lines</relationshipLabel>
        <relationshipName>Supplier_Invoice_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Tax_Rate__c</fullName>
        <label>Sales Tax Rate</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Ship_From_City__c</fullName>
        <description>to populate ship from city.</description>
        <label>Ship From City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_From_Country__c</fullName>
        <description>to populated ship from country.</description>
        <label>Ship From Country</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_From_State__c</fullName>
        <description>to populate ship from state</description>
        <label>Ship From State</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_From_Street__c</fullName>
        <description>to populate ship from street.</description>
        <label>Ship From Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Ship_From_Zip_Code__c</fullName>
        <description>to populate ship from zip code</description>
        <label>Ship From Zip Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Street__c</fullName>
        <description>to populate ship to street.</description>
        <label>Ship To Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Supplier_Invoice__c</fullName>
        <label>Supplier Invoice</label>
        <referenceTo>Supplier_Invoice__c</referenceTo>
        <relationshipLabel>Supplier Invoice Line</relationshipLabel>
        <relationshipName>Supplier_Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Supplier Invoice Line</label>
    <nameField>
        <label>Supplier Invoice Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier Invoice Line</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/classes/DefaultSalesTax.cls
public with sharing class DefaultSalesTax implements TaxService.ITaxAction {
		
		public List<FieldInfo> getDisplayFieldSet(Schema.sObjectType objectType){

			if(objectType == Sales_Order__c.getSobjectType()){
				List<FieldInfo> taxFields = FieldInfo.fetchJsonFieldInfos('Sales_Order_Line__c', new List<String>{'Sales_Tax__c','Sales_Tax_Rate__c'});

				for(FieldInfo f : taxFields){
					f.editable = false;
				}
				return taxFields;
			}else if(objectType == Customer_Invoice__c.getSobjectType()){
				List<FieldInfo> taxFields = FieldInfo.fetchJsonFieldInfos('Customer_Invoice_Line__c', new List<String>{'Sales_Tax__c','Sales_Tax_Rate__c'});

				for(FieldInfo f : taxFields){
					f.editable = false;
				}
				return taxFields;
			}else if(objectType == Supplier_Invoice__c.getSobjectType()){
				List<FieldInfo> taxFields = new List<FieldInfo>();
				taxFields.add(new FieldInfo('Ship_From_Street__c', 'Ship From Street', 'textarea'));
            	taxFields.add(new FieldInfo('Ship_From_City__c', 'Ship From City', 'string'));
            	taxFields.add(new FieldInfo('Ship_From_State__c', 'Ship From State', 'string'));
            	taxFields.add(new FieldInfo('Ship_From_Country__c', 'Ship From Country', 'string'));
            	taxFields.add(new FieldInfo('Ship_From_Zip_Code__c', 'Ship From Zip Code', 'string'));
            	
            	taxFields.add(new FieldInfo('Ship_To_Street__c', 'Ship To Street', 'textarea'));
            	taxFields.add(new FieldInfo('Ship_To_City__c', 'Ship To City', 'string'));
            	taxFields.add(new FieldInfo('Ship_To_State__c', 'Ship To State', 'string'));
            	taxFields.add(new FieldInfo('Ship_To_Country__c', 'Ship To Country', 'string'));
            	taxFields.add(new FieldInfo('Ship_To_Zip_Code__c', 'Ship To Zip Code', 'string'));
				return taxFields;
			}else{
				return null;
			}
		}

		public List<TaxService.TaxResult> getTaxes(List<Id>ids){
			if(ids.get(0).getSObjectType()  == Sales_Order__c.getSobjectType()){
				return getSalesOrderTax(ids);
			}else if(ids.get(0).getSObjectType()  == Customer_Invoice__c.getSobjectType()){
				return getCustomerInvoiceTax(ids);
			}else if(ids.get(0).getSObjectType() == Purchase_Order__c.getSobjectType()){
				return getPurchaseOrderTax(ids);
			}else if(ids.get(0).getSObjectType() == Supplier_Invoice__c.getSobjectType()){
				return getSupplierInvoiceTax(ids);
			}else{
				//do nothing
				return null;
			}
		}

		public List<TaxService.TaxResult> voidTaxes(List<id>ids){
			return null;
		}

		private List<TaxService.TaxResult> getSalesOrderTax(List<Id>ids){

			SoqlUtil soql = new SoqlUtil('Sales_Order_Line__c');
			soql.addFields(new Set<String>{'Id', 'Sales_Order__c', 'Extended_Price__c', 'Sales_Tax__c', 'Sales_Tax_Rate__c',
												'Product__r.Non_Taxable__c', 'Sales_Order__r.Ship_to__r.Sales_Tax_Rate__c',
												'Sales_Order__r.Ship_To__c'});
			soql.setWhereClause('Sales_Order__c in:ids');
			List<Sales_Order_Line__c> lines = Database.Query(soql.getQuery());

			Map<Id, TaxService.TaxResult> results = new Map<Id, TaxService.TaxResult>();
			for(Sales_Order_Line__c l : lines){
				TaxService.TaxResult tr = new TaxService.TaxResult();
				if(l.Sales_Order__r.Ship_To__c != null){
					l.Sales_Tax_Rate__c = l.Product__r.Non_Taxable__c == false && l.Sales_Order__r.Ship_to__r.Sales_Tax_Rate__c != null ? l.Sales_Order__r.Ship_to__r.Sales_Tax_Rate__c : 0;
				l.Sales_Tax__c = (l.Sales_Tax_Rate__c / 100) * l.Extended_Price__c;
					tr.isSuccess = true;
					tr.message = 'Tax Calculated for this sales order.';
				}else{
					tr.isSuccess = false;
					tr.message = 'Unable to calculate sales tax.  Ship To Customer is missing.';
				}

				results.put(l.Sales_Order__c, tr);


			}
			update lines;

			if(lines.size() == 0){
				TaxService.TaxResult tr = new TaxService.TaxResult();
				tr.isSuccess = true;
				tr.message = 'No lines to get tax for.';
				results.put(null, tr);
			}

			return results.values();
		}

		private List<TaxService.TaxResult> getPurchaseOrderTax(List<Id>ids){
			return null;
		}

		private List<TaxService.TaxResult>getCustomerInvoiceTax(List<Id>ids){
			Map<Id, TaxService.TaxResult> results = new Map<Id, TaxService.TaxResult>();

			SoqlUtil soql = new SoqlUtil('Customer_Invoice_Line__c');
			soql.addFields(new Set<String>{'Id', 'Customer_Invoice__c','Extended_Price__c', 'Sales_Tax__c', 'Sales_Tax_Rate__c', 'Product__r.Non_Taxable__c',
											'Shipment_Line__r.Shipment__r.Customer__r.Sales_Tax_Rate__c', 'Shipment_Line__c',
											'Customer_Invoice__r.Ship_To__r.Sales_Tax_Rate__c', 
											'Sales_Order_Line__r.Sales_Order__r.Ship_to__r.Sales_Tax_Rate__c'});
			soql.setWhereClause('Customer_Invoice__c in:ids');

			List<Customer_Invoice_Line__c> lines = Database.Query(soql.getQuery());

			for(Customer_Invoice_Line__c cil : lines){
				TaxService.TaxResult tr = new TaxService.TaxResult();
				tr.isSuccess = true;
				tr.message = 'Taxes Calculated.'; 
				tr.obj = (SObject) new Customer_Invoice__c(Id=cil.Customer_Invoice__c);

				if(cil.Shipment_Line__c != null){
					cil.Sales_Tax_Rate__c = cil.Product__r.Non_Taxable__c == false && cil.Shipment_Line__r.Shipment__r.Customer__r.Sales_Tax_Rate__c != null ? cil.Shipment_Line__r.Shipment__r.Customer__r.Sales_Tax_Rate__c : 0;
					cil.Sales_Tax__c = (cil.Sales_Tax_Rate__c/100) * cil.Extended_Price__c;
				}else if(cil.Sales_Order_Line__r != null){
					cil.Sales_Tax_Rate__c = cil.Product__r.Non_Taxable__c == false && cil.Sales_Order_Line__r.Sales_Order__r.Ship_to__r.Sales_Tax_Rate__c != null ? cil.Sales_Order_Line__r.Sales_Order__r.Ship_to__r.Sales_Tax_Rate__c : 0;
					cil.Sales_Tax__c = (cil.Sales_Tax_Rate__c/100) * cil.Extended_Price__c;
				}else if(cil.Customer_Invoice__r.Ship_to__r != null){
					cil.Sales_Tax_Rate__c = cil.Product__r.Non_Taxable__c == false && cil.Customer_Invoice__r.Ship_to__r.Sales_Tax_Rate__c != null ? cil.Customer_Invoice__r.Ship_to__r.Sales_Tax_Rate__c : 0;
					cil.Sales_Tax__c = (cil.Sales_Tax_Rate__c/100) * cil.Extended_Price__c;
				}else{
					tr.obj = (SObject) new Customer_Invoice__c(Id=cil.Customer_Invoice__c);
					tr.isSuccess = false;
					tr.message = 'Ship To Customer is required to get Tax.';
				}
				results.put(cil.Customer_Invoice__c, tr);
			}

			update lines;

			if(lines.size() == 0){
				TaxService.TaxResult tr = new TaxService.TaxResult();
				tr.isSuccess = true;
				tr.message = 'No lines to get tax for.';
				results.put(null, tr);
			}
			return results.values();
		}

		private List<TaxService.TaxResult>getSupplierInvoiceTax(List<Id>ids){
			system.debug('getSupplierInvoiceTax**'+ids);
			List<TaxService.TaxResult> results = new List<TaxService.TaxResult>();
			try{
				list<Supplier_Invoice__c> lstSI = [Select Id, Name,
                                                  (Select Id, Name,Ship_To_State__c, Ship_To_Street__c, Ship_To_City__c, Ship_To_Zip_Code__c, 
                                                  Ship_To_Country__c, Ship_From_Street__c, Ship_From_City__c,
                                                  Ship_From_State__c, Ship_From_Zip_Code__c, Ship_From_Country__c,
                                                  Sales_Tax_Rate__c, Sales_Tax_Amount__c,Unit_Price__c,
                                                  Invoice_Quantity__c From Supplier_Invoice_Lines__r) 
                                                  From Supplier_Invoice__c
                                                  Where Id in:ids];
				list<Supplier_Invoice_Line__c> lstSIL = new list<Supplier_Invoice_Line__c>();
			    system.debug('getSupplierInvoiceTax***'+lstSI);
				if(!lstSI.isEmpty()){
					for(Supplier_Invoice__c si : lstSI){
						TaxService.TaxResult t = new TaxService.TaxResult();
						system.debug('si.Supplier_Invoice_Lines__r****'+si.Supplier_Invoice_Lines__r);
						for(Supplier_Invoice_Line__c sil : si.Supplier_Invoice_Lines__r){
							sil.Sales_Tax_Rate__c = 1.79;
							sil.Sales_Tax_Amount__c = (sil.Unit_Price__c*sil.Invoice_Quantity__c)*.0179;
							lstSIL.add(sil);
						}
						t.isSuccess = true;
	                    t.obj = si;
	                    t.message = 'Tax calculated for ' + si.Name;
	                    results.add(t);
					}
					if(!lstSIL.isEmpty()){
						system.debug('lstSIL****'+lstSIL);
						update lstSIL;
					}
				}
			}catch(exception ex){
				results.clear();
				system.debug('exception**'+ex.getMessage());
				TaxService.TaxResult t = new TaxService.TaxResult();
				t.isSuccess = false;
				t.message = 'Error while calculating tax';
				results.add(t);
			}
			return results;
		}

}