src-ken&y/objects/Customer__c.object
<CustomObject>
    <customHelpPage>HelpCustomers</customHelpPage>
    <description>Information that relates a Customer business to the manufacturing company (Company) and describes the business agreement between the two entities.</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The company that originates and owns the customer relationship</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Customers</relationshipLabel>
        <relationshipName>Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer</label>
    <nameField>
        <label>Customer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Facility__c.object
<CustomObject>
    <customHelpPage>HelpFacilites</customHelpPage>
    <description>Warehouse or building</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Facilities</relationshipLabel>
        <relationshipName>Facilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Facility</label>
    <nameField>
        <label>Facility</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Fixed_Asset__c.object
<CustomObject>
    <customHelpPage>HelpFixedAssets</customHelpPage>
    <description>Stores the companies fixed assets for tracking and depreciation</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Fixed Assets</relationshipLabel>
        <relationshipName>Fixed_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The physical location of the asset.</description>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Fixed Assets</relationshipLabel>
        <relationshipName>Fixed_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Fixed Asset</label>
    <nameField>
        <label>Fixed Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fixed Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Item__c.object
<CustomObject>
    <customHelpPage>HelpItems</customHelpPage>
    <description>Item Master object</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company that controls this item</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Location__c.object
<CustomObject>
    <customHelpPage>HelpLocations</customHelpPage>
    <description>Organizational Unit or physical location primarily used if  subclassification reporting is desired</description>
    <fields>
        <fullName>Facility__c</fullName>
        <description>Lookup to facility</description>
        <label>Facility</label>
        <referenceTo>Facility__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Material_Tracking__c.object
<CustomObject>
    <fields>
        <fullName>Work_Order__c</fullName>
        <label>Work Order</label>
        <referenceTo>Work_Order__c</referenceTo>
        <relationshipLabel>Material Trackings</relationshipLabel>
        <relationshipName>Material_Trackings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Material Tracking</label>
    <nameField>
        <displayFormat>MT-{0000000000}</displayFormat>
        <label>Material Tracking</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Material Trackings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Operation_Tracking__c.object
<CustomObject>
    <fields>
        <fullName>Work_Order__c</fullName>
        <label>Work Order</label>
        <referenceTo>Work_Order__c</referenceTo>
        <relationshipLabel>Operation Trackings</relationshipLabel>
        <relationshipName>Operation_Trackings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Operation Tracking</label>
    <nameField>
        <label>Operation Tracking</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Operation Trackings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Receipt_Line__c.object
<CustomObject>
    <customHelpPage>HelpReceivingDocument</customHelpPage>
    <description>Purchase order receipts</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Receipt Lines</relationshipLabel>
        <relationshipName>Receipt_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Facility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to facility</description>
        <label>Facility</label>
        <referenceTo>Facility__c</referenceTo>
        <relationshipLabel>Receipt Lines</relationshipLabel>
        <relationshipName>Receipt_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to location</description>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Receipt Lines</relationshipLabel>
        <relationshipName>Receipt_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Receipt Line</label>
    <nameField>
        <label>Receipt Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Receipt Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Sales_Order_Line__c.object
<CustomObject>
    <customHelpPage>HelpSalesOrders_Managing</customHelpPage>
    <description>Line Items on the Sales Order.</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company passed down from the sales order header</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Will be populated for sales order lines with item source as &apos;Build To Order&apos;</description>
        <label>Work Order</label>
        <referenceTo>Work_Order__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <label>Sales Order Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Serial__c.object
<CustomObject>
    <customHelpPage>HelpSerials</customHelpPage>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Serials</relationshipLabel>
        <relationshipName>Serials</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Serial</label>
    <nameField>
        <label>Serial Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Serials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Shipment_Line__c.object
<CustomObject>
    <customHelpPage>HelpShipment</customHelpPage>
    <description>Shipment lines.</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company associated with this shipment invoice line</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Shipment Lines</relationshipLabel>
        <relationshipName>Shipment_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Facility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to facility</description>
        <label>Facility</label>
        <referenceTo>Facility__c</referenceTo>
        <relationshipLabel>Shipment Lines</relationshipLabel>
        <relationshipName>Shipment_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to location</description>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Shipment Lines</relationshipLabel>
        <relationshipName>Shipment_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Will be populated for shipment lines with item source as &apos;Build To Order&apos;</description>
        <label>Work Order</label>
        <referenceTo>Work_Order__c</referenceTo>
        <relationshipLabel>Shipment Lines</relationshipLabel>
        <relationshipName>Shipment_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Shipment Line</label>
    <nameField>
        <label>Shipment Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipment Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/SKID__c.object
<CustomObject>
    <customHelpPage>HelpSKIDAbout</customHelpPage>
    <description>Stock Keeping ID</description>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to location</description>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>SKIDs</relationshipLabel>
        <relationshipName>SKIDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Work order related to the on order SKID</description>
        <label>Work Order</label>
        <referenceTo>Work_Order__c</referenceTo>
        <relationshipLabel>SKIDs</relationshipLabel>
        <relationshipName>SKIDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SKID</label>
    <nameField>
        <label>SKID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SKIDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Work_Order__c.object
<CustomObject>
    <customHelpPage>HelpWorkOrder</customHelpPage>
    <description>All work orders including planned orders from MRP as well as unplanned orders.</description>
    <fields>
        <fullName>Complete_to_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Location</description>
        <label>Complete to Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Location__c.Facility__c</field>
                <operation>equals</operation>
                <valueField>$Source.Facility__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Work Orders (Complete to Location)</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Facility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The facility in which the work order will be processed.</description>
        <label>Facility</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Facility__c.Company__c</field>
                <operation>equals</operation>
                <valueField>$Source.Company__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Facility__c</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Workorders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Work Order</label>
    <nameField>
        <label>Work Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/WorkOrderKitExtV2.cls
public with sharing class WorkOrderKitExtV2 extends BaseController {
    public String namespaceUU { get; set; } { namespaceUU = KSE.namespaceUU; }
    public static Work_Order__c workOrder { get; set; }
    public static Boolean serialTracked { get; set; } { serialTracked = false; }
    public String serialFieldList { get; set; }
    public Integer gridSize { get; set; }
    final String TYPE_REFERENCE = 'reference' ;
    public static string serialAttributes { get;set;}

    public Boolean disable { get; set; } { disable = false; }    

    private static SchemaUtil util = SchemaUtil.getInstance();
    
    public class WorkOrderKitExtV2Exception extends Exception { }

    public WorkOrderKitExtV2(ApexPages.StandardController con) {
        workOrder = WorkOrderService.getWorkOrders(new Set<Id>{ con.getId() },null,new Set<String>{ 'Complete_To_Location__r.Facility__r.Company__c' },null)[0];

        if (workOrder.Company__r.Serial_Control__c == SkidService3.AT_RECEIPT) {
            serialTracked = true;
        }
        
        try {
            WorkOrderService.validateForKit(new List<Work_Order__c>{ workOrder });
            
            FieldInfo fii = new FieldInfo('','','integer');
            fii.editable = false;
            List<FieldInfo> fiList = new List<FieldInfo>{fii};
            List<String> serialAttributesList = SkidService3.serialAttributes;
            serialAttributes = JSON.serialize(serialAttributesList);
            fiList.addAll(FieldInfo.fetchJsonFieldInfos('Serial__c', 'Serial',serialAttributesList.size() > 0 ? String.join(serialAttributesList, ',') : null, false));
            
            for(FieldInfo fi : fiList){
                
                String field = fi.field.replace(KSE.NamespaceUU, '');
                if(field.toLowerCase() == 'name'){
                    fi.field='SerialNameId';
                    fi.fieldType = TYPE_REFERENCE;
                    fi.referenceTo = 'Serial__c';
                }
                else if( field.toLowerCase() == 'fixed_asset__c' ){
                    fi.editable = false;
                }
            }
            serialFieldList = JSON.serialize(fiList);
            gridSize = fiList.size() * 150;
        } catch(Exception e) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, MessageUtil.toFriendlyErrorMessage(e.getMessage())));
            disable = true;
        }
    }

    @RemoteAction
    public static JsonResult save(List<WorkOrderWrapper> mWrappers,List<String> mDateFields,List<String> skidDateFields) {
        JsonResult result = new JsonResult();
        Savepoint sp = Database.setSavepoint();
        Set<Id> woIds = new Set<Id>();

        try {
            for (WorkOrderWrapper mWrapper:mWrappers) {
                woIds.add(mWrapper.material.Work_Order__c);

                KendoUtils.UpdateDateFields(mWrapper.material,mDateFields);
                
                for (SkidService3.SerialWrapper sw:mWrapper.serialWrapperList) {
                    KendoUtils.UpdateDateFields(sw.skid,skidDateFields);
                }
            }

            Work_Order__c wo = WorkOrderService.getWorkOrders(woIds,null,new Set<String>{ 'Complete_To_Location__r.Facility__r.Company__c' },null)[0];

            Map<Id, Material_Tracking__c> materials = new Map<Id, Material_Tracking__c>(WorkOrderService.getMaterials(woIds,null,new Set<String>{ WorkOrderService.MATERIAL_TYPE_KIT, WorkOrderService.MATERIAL_TYPE_REPAIR },new Set<String>{ 'Kit' },new Set<String>{ 'Work_Order__r.Shipment_Line__r.Sales_Order_Line__r.Receipt_Line__c' },' AND Operation_Tracking__c = null ', true));

            for (WorkOrderWrapper mWrapper:mWrappers) {
                mWrapper.workOrder = wo.clone(true, true);
                mWrapper.material = materials.get(mWrapper.material.Id);
            }

            WorkOrderService.kit(mWrappers);
        } catch (Exception e) {
            Database.rollback(sp);
            result.success = false;
            result.addMessage(e.getMessage(),ApexPages.Severity.ERROR);
        }
        return result;
    }
    
    public String getWorkOrderJson() {
        return JSON.serialize(workOrder);  
    }
    
    @RemoteAction 
    public static JsonResult getKitData(Id woId) {
        JsonResult result = new JsonResult();
        try {
            result.records = WorkOrderService.getKitData(new Set<Id>{ woId });
            result.total = result.records.size();
        } catch (Exception e) {
            result.success = false;
            result.addMessage(e.getMessage(),ApexPages.Severity.ERROR);
        }
        return result;
    }

    @RemoteAction
    public static JsonResult addLine(Material_Tracking__c mt) {
        JsonResult result = new JsonResult();
        try {
            SKID__c skid = new SKID__c(
                Company__c = mt.Work_Order__r.Company__c,
                Type__c = SkidService3.SKID_TYPE_LOCATION,
                Item__c = mt.Item__c,
                Item__r = mt.Item__r,
                Facility2__c = mt.Work_Order__r.Facility__c,
                Facility2__r = mt.Work_Order__r.Facility__r,
                Quantity__c = 0,
                Quantity_Available__c = 0,
                Quantity_to_Issue__c = 0
            );
            SkidService3.SerialWrapper sw = new SkidService3.SerialWrapper(skid,new List<Serial__c>());
            sw.trackedAttributes = new List<String>();
            for (String attr:SkidService3.refreshTrackedAttr(null,null,new Item__c(Id = mt.Item__c))) {
                sw.trackedAttributes.add('skid.' + attr.toLowerCase());
            }
            result.records = new List<SkidService3.SerialWrapper>{ sw };
        } catch (Exception e) {
            result.success = false;
            result.addMessage(e.getMessage(),ApexPages.Severity.ERROR);
        }
        return result;
    }

    @RemoteAction
    public static JsonResult getLocation(Id locationId) {
        JsonResult result = new JsonResult();
        try {
            SOQLUtil locQuery = new SOQLUtil('Location__c');
            locQuery.addAllCustomFields();
            locQuery.setWhereClause('Id = \'' + locationId + '\'');
            result.records = new List<Location__c>{ (Location__c)Database.query(locQuery.getQuery())[0] };
        } catch (Exception e) {
            result.success = false;
            result.addMessage(e.getMessage(),ApexPages.Severity.ERROR);
        }
        return result;
    }
    
    public String getKitConfigJson() {
        GridRelatedListController.GridRelatedListConfig kitConfig = new GridRelatedListController.GridRelatedListConfig();
        kitConfig.uniqueId = 'kitGrid';
        kitConfig.title = 'Kit Information';
        kitConfig.objectName = 'Material_Tracking__c';
        kitConfig.parentRecord = workOrder;
        kitConfig.parentField = 'Work_Order__c';
        kitConfig.fieldset = 'Kit';
        kitConfig.buttons = 'Expand All, Collapse All, Populate Component Quantities';
        kitConfig.alwaysUseFullDateTimeFormat = false;
        return JSON.serialize(kitConfig);
    }
    
    public String getMtFieldList() {
        List<FieldInfo> fiList = FieldInfo.fetchJsonFieldInfos('Material_Tracking__c','Kit',null,true);
        fiList.remove(0); // Remove Id field from the list
        for (FieldInfo fi:fiList) {
            fi.field = 'material.' + fi.field;
        }
        return JSON.serialize(fiList);
    }
    
    public String getSkidFieldList() {
        List<String> displayFields = new List<String>();
        if (workOrder.Type__c == WorkOrderService.WO_TYPE_REPAIR && workOrder.Shipment_Line__c == null && workOrder.Field_Service__c) {
            displayFields.add('Customer__c');
        }
        displayFields.addAll(SkidService3.attributesForDisplay(null, new List<String>{ 'Consigned_Owner__c' }, false));
        List<FieldInfo> skidFields = FieldInfo.fetchJsonFieldInfos('SKID__c', displayFields);

        List<FieldInfo> readFields = FieldInfo.fetchJsonFieldInfos('SKID__c', SchemaUtil.getInstance().getFieldsFromFieldSetString(SKID__c.sObjectType, 'Kit_RO'));
        for (FieldInfo fi:readFields) {
            fi.editable = false;
        }
        skidFields.addAll(readFields);

        skidFields.addAll(FieldInfo.fetchJsonFieldInfos('SKID__c', new List<String>{ 'Quantity_Available__c', 'Quantity_to_Issue__c' }));

        for (FieldInfo fi:skidFields) {
            if (fi.field == 'Customer__c' || fi.field == 'Consigned_Owner__c' || fi.field == 'Quantity_Available__c') {
                fi.editable = false;
            }
            fi.field = 'skid.' + fi.field;
        }
        return JSON.serialize(skidFields);
    }
}