src-ken&y/objects/Customer__c.object
<CustomObject>
    <customHelpPage>HelpCustomers</customHelpPage>
    <description>Information that relates a Customer business to the manufacturing company (Company) and describes the business agreement between the two entities.</description>
    <fields>
        <fullName>Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customers</relationshipLabel>
        <relationshipName>Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fuel_Preference__c</fullName>
        <label>Fuel Preference</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer</label>
    <nameField>
        <label>Customer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Means_of_Transport__c.object
<CustomObject>
    <customHelpPage>HelpMeansOfTransport</customHelpPage>
    <description>Stores the different means of transportation and their details.</description>
    <label>Means of Transport</label>
    <nameField>
        <label>Means of Transport</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Means of Transport</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Transit_Route__c.object
<CustomObject>
    <customHelpPage>HelpTransitRoute</customHelpPage>
    <description>Stores the transit times between &quot;Ship From&quot;  and &quot;Ship To&quot; locations. This will be used to calculate the delivery date of a sales order.</description>
    <fields>
        <fullName>Assessorial_Amount__c</fullName>
        <label>Assessorial Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CWT_Factor__c</fullName>
        <label>CWT Factor</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Delivery_Method__c</fullName>
        <label>Delivery Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Delivery</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Pickup</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Destination__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The address at which the route for transportation ends.</description>
        <label>Destination</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transit Routes (Inbound)</relationshipLabel>
        <relationshipName>Transit_Routes_Inbound</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Distance_Rate__c</fullName>
        <inlineHelpText>Rate used to calculate cost of transit.</inlineHelpText>
        <label>Distance Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Distance__c</fullName>
        <description>The distance (in miles) covered by this route.</description>
        <inlineHelpText>Distance between the Ship-from location and the Ship-to destination.</inlineHelpText>
        <label>Distance (Miles)</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Fuel_Allowance__c</fullName>
        <label>Fuel Allowance %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Fuel_Rate__c</fullName>
        <label>Fuel Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Line_Haul_Amount__c</fullName>
        <label>Line Haul Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Means_of_Transport__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The means of transportation by which the goods will be carried in this route.</description>
        <label>Means of Transport</label>
        <referenceTo>Means_of_Transport__c</referenceTo>
        <relationshipLabel>Transit Routes</relationshipLabel>
        <relationshipName>Transit_Routes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The address from which the route for transportation originates.</description>
        <label>Origin</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transit Routes (Outbound)</relationshipLabel>
        <relationshipName>Transit_Routes_Outbound</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transit_Time__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The time (in days) it takes for the shipped goods to reach the destination of this route.</description>
        <inlineHelpText>The number of days it takes for the goods to reach the destination.</inlineHelpText>
        <label>Transit Time (Days)</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Transit Route</label>
    <nameField>
        <label>Transit Route</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transit Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/User_Preference__c.object
<CustomObject>
    <customHelpPage>HelpUserPreference</customHelpPage>
    <description>Track individual user preferences or configurations</description>
    <fields>
        <fullName>Default_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The company that is used to default on new orders</description>
        <label>Default Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>User Preferences</relationshipLabel>
        <relationshipName>User_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Preference</label>
    <nameField>
        <label>User Preference Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Preferences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/ConfigureOTCTest.cls
@isTest
private class ConfigureOTCTest {
    
    class ConfigureOTCTestData {
    	TestFuel fuel = new TestFuel();
    	
        User_Preference__c up = UserPreference.getInstance().Preference;
        {
        	up.Default_Company__c = fuel.company.id;
        	upsert up;
        }
        /* KNDY-10333
        Account originAddress = new Account(Name = 'TestOrigin');
        Account destAccount2 = new Account(Name = 'Dest Account 2');
        {	
        	insert new Account[] {         originAddress, destAccount2         };
        }
            
        Transit_Route__c tr = new Transit_Route__c(Destination__c = fuel.account.id,
                                                   Means_of_Transport__c = fuel.meansOfTransport.id, 
                                                   Origin__c = originAddress.Id,
                                                   Assessorial_Amount__c = 50,
                                                   CWT_Factor__c = 430,
                                                   Distance__c = 500,
                                                   Distance_Rate__c = 0.47,
                                                   Fuel_Allowance__c = 32.4,
                                                   Fuel_Rate__c = 5,
                                                   Line_Haul_Amount__c = 1000,
                                                   Transit_Time__c = 2,
                                                   Delivery_Method__c = 'Pickup');
		{	
			insert tr;
		}   
        */                                        
    }
    
    testMethod static void testConfigureOTCExtAndCustomerTrigger() {
        ConfigureOTCTestData testData = new ConfigureOTCTestData();
        
        Customer__c customerParent = testData.fuel.customerParent;
        customerParent.Fuel_Preference__c = '';
        update customerParent; 
        
        Test.startTest();
	        Test.setCurrentPage(Page.ConfigureOTC);        
	        ApexPages.currentPage().getParameters().put('id', testData.fuel.company.id);
	        ConfigureOTCExt ext = new ConfigureOTCExt( new ApexPages.StandardController( testData.fuel.company ) );
	        System.assertEquals(null, ext.otc.id);
	        
	        ext.otc.Parent_Level_Freight_Allowances_Only = true;
	        ext.onSave();
	        System.assertNotEquals(null, ext.otc.id);
	        System.assertEquals(false, TestHelper.hasPageMessage(ApexPages.Severity.FATAL, 'OTC Configuration Update Error:'));
	        
	        // reload 
	        ext = new ConfigureOTCExt( new ApexPages.StandardController( testData.fuel.company ) );
	        System.assertEquals(true, ext.otc.Parent_Level_Freight_Allowances_Only, 'ext.otc.Parent_Level_Freight_Allowances_Only__c should come true, as its set previously to that value');            
	        //ext.otc.Fuel_Allowance_Preference_None = 10;
	        ext.otc.Fuel_Allowance_Preference_Weekly = 20;
	        ext.otc.Fuel_Allowance_Preference_Monthly = 30;
	        ext.otc.Fuel_Allowance_Preference_Quarterly = 40;        
	        ext.onSave();  
        
        Test.stopTest();
        /* KNDY-10333 
        Transit_Route__c tr = [Select Fuel_Allowance__c, Distance_Rate__c from Transit_Route__c Where Id =:testData.tr.id limit 1];
        System.assertEquals(32.4, tr.Fuel_Allowance__c);
        System.assertEquals(0.47, tr.Distance_Rate__c);
        */
    }
    
    testMethod static void testFuelPreferenceWeeklyAndMonthly() {
        ConfigureOTCTestData testData = new ConfigureOTCTestData();   
        
        Customer__c customerParent = testData.fuel.customerParent;
        customerParent.Fuel_Preference__c = 'Weekly';
        update customerParent;  
        
        Test.startTest();
	    	Test.setCurrentPage(Page.ConfigureOTC);        
	        ApexPages.currentPage().getParameters().put('id', testData.fuel.company.id);
	        ConfigureOTCExt ext = new ConfigureOTCExt( new ApexPages.StandardController( testData.fuel.company ) );
	        ext.otc.Parent_Level_Freight_Allowances_Only = true;
	        ext.onSave();
	        
	        ext = new ConfigureOTCExt( new ApexPages.StandardController( testData.fuel.company ) );
	        ext.otc.Fuel_Allowance_Preference_Weekly = 20;
	        ext.otc.Fuel_Allowance_Preference_Monthly = 30;
	        ext.otc.Fuel_Allowance_Preference_Quarterly = 40;        
	        ext.onSave();
    		System.assertNotEquals(null, ext.otc.id);
	        System.assertEquals(false, TestHelper.hasPageMessage(ApexPages.Severity.FATAL, 'OTC Configuration Update Error:'));
    	Test.stopTest();
        /* KNDY-10333
        System.assertEquals(ext.otc.Fuel_Allowance_Preference_Weekly, [Select Fuel_Allowance__c, Distance_Rate__c from Transit_Route__c Where Id =:testData.tr.id limit 1].Fuel_Allowance__c);
        
        customerParent = testData.fuel.customerParent;
        customerParent.Fuel_Preference__c = 'Monthly';
        update customerParent;
        
        System.assertEquals(ext.otc.Fuel_Allowance_Preference_Monthly, [Select Fuel_Allowance__c from Transit_Route__c Where Id =:testData.tr.id].Fuel_Allowance__c);        
        
        // Fires Customer trigger to clean up the Fuel Allowance as no other customer is having the previous account address.
        customerParent.Address__c = testData.destAccount2.Id;
        update customerParent;
        
        System.assertEquals(0, [Select Fuel_Allowance__c from Transit_Route__c Where Id =:testData.tr.id].Fuel_Allowance__c);        
        
        // Fire Transit Route Trigger to update back the from the Latest Address from Customer
        testData.tr.Destination__c = testData.destAccount2.Id;
        update testData.tr;
        System.assertEquals(ext.otc.Fuel_Allowance_Preference_Monthly, [Select Fuel_Allowance__c from Transit_Route__c Where Id =:testData.tr.id].Fuel_Allowance__c);  
        */      
    }
    
}