src-ken&y/objects/Customer__c.object
<CustomObject>
    <customHelpPage>HelpCustomers</customHelpPage>
    <description>Information that relates a Customer business to the manufacturing company (Company) and describes the business agreement between the two entities.</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The company that originates and owns the customer relationship</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Customers</relationshipLabel>
        <relationshipName>Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer</label>
    <nameField>
        <label>Customer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Fulfillment__c.object
<CustomObject>
    <customHelpPage>HelpFulfillment</customHelpPage>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Fulfillments</relationshipLabel>
        <relationshipName>Fulfillments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Fulfillments</relationshipLabel>
        <relationshipName>Fulfillments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order Line</label>
        <referenceTo>Sales_Order_Line__c</referenceTo>
        <relationshipLabel>Fulfillments</relationshipLabel>
        <relationshipName>Fulfillments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>Sales_Order__c</referenceTo>
        <relationshipLabel>Fulfillments</relationshipLabel>
        <relationshipName>Fulfillments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Deinstall</fullName>
                </value>
                <value>
                    <fullName>Subscription</fullName>
                </value>
                <value>
                    <fullName>Recurring</fullName>
                </value>
                <value>
                    <fullName>Usage</fullName>
                </value>
                <value>
                    <fullName>Bundle</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Fulfillment</label>
    <nameField>
        <label>Fulfillment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fulfillments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Pricebook__c.object
<CustomObject>
    <customHelpPage>HelpPricebooks</customHelpPage>
    <description>List prices for a company and the products it sells</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The company that this pricebook belongs to</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Pricebooks</relationshipLabel>
        <relationshipName>Pricebooks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Pricebook</label>
    <nameField>
        <label>Pricebook Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricebooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Product__c.object
<CustomObject>
    <customHelpPage>HelpProducts</customHelpPage>
    <description>Products are sellable Items with Selling Unit of Measure included</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Receipt_Line__c.object
<CustomObject>
    <customHelpPage>HelpReceivingDocument</customHelpPage>
    <description>Purchase order receipts</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Receipt Lines</relationshipLabel>
        <relationshipName>Receipt_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Receiving_Document__c</fullName>
        <description>Lookup to Receiving Document</description>
        <label>Receiving Document</label>
        <referenceTo>Receiving_Document__c</referenceTo>
        <relationshipLabel>Receipt Lines</relationshipLabel>
        <relationshipName>Receipt_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sales_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order Line</label>
        <referenceTo>Sales_Order_Line__c</referenceTo>
        <relationshipLabel>Receipt Lines</relationshipLabel>
        <relationshipName>Receipt_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>Sales_Order__c</referenceTo>
        <relationshipLabel>Receipt Lines</relationshipLabel>
        <relationshipName>Receipt_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Receipt Line</label>
    <nameField>
        <label>Receipt Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Receipt Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Receiving_Document__c.object
<CustomObject>
    <customHelpPage>HelpReceivingDocument</customHelpPage>
    <description>Receiving Document - Advanced Shipment Notice - ASN</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Receiving Documents</relationshipLabel>
        <relationshipName>Advanced_Shipment_Notice</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Receiving Documents</relationshipLabel>
        <relationshipName>Receiving_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of Receiving Document</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Miscellaneous Receipt</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Return Receipt</fullName>
                </value>
                <value>
                    <fullName>Advanced Shipment Notice</fullName>
                </value>
                <value>
                    <fullName>Purchase Order Receipt</fullName>
                </value>
                <value>
                    <fullName>Receipt into In-Transit</fullName>
                </value>
                <value>
                    <fullName>In-Transit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Receiving Document</label>
    <nameField>
        <label>Receiving Document</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Receiving Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Sales_Order__c.object
<CustomObject>
    <customHelpPage>HelpSalesOrders_Managing</customHelpPage>
    <description>Sales Order Header</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Adjustment</fullName>
                </value>
                <value>
                    <fullName>RMA-Credit</fullName>
                </value>
                <value>
                    <fullName>RMA-Customer-Repair</fullName>
                </value>
                <value>
                    <fullName>RMA-Replacement</fullName>
                </value>
                <value>
                    <fullName>Resale</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Sales_Order_Line__c.object
<CustomObject>
    <customHelpPage>HelpSalesOrders_Managing</customHelpPage>
    <description>Line Items on the Sales Order.</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company passed down from the sales order header</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name_Hyperlink__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; &amp; Id, Name)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Name Hyperlink</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity_Fulfilled__c</fullName>
        <label>Quantity Fulfilled</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Related_Sales_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Sales Order Line</label>
        <referenceTo>Sales_Order_Line__c</referenceTo>
        <relationshipLabel>Sales Order Lines (Related Sales Order Line)</relationshipLabel>
        <relationshipName>Sales_Order_Lines1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <label>Sales Order</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Company does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>Sales_Order__c.Company__c</field>
                <operation>equals</operation>
                <valueField>$Source.Company__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Sales_Order__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type indicates the sales order line type. (eg. RMA, Kit, Kit-Child, etc...). Based on the value the Sales order line flow is controlled through different status.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>RMA</fullName>
                </value>
                <value>
                    <fullName>Kit</fullName>
                </value>
                <value>
                    <fullName>Kit-Child</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <label>Sales Order Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/classes/CreateRepairDocumentsExt.cls
public with sharing class CreateRepairDocumentsExt {
    public List<Sales_Order_Line__c> solList{get;set;}
    public List<RepairGridCon.WarrantyWrapper> wrapperList{get;set;}
    public String resultJsonString{get;set;}
    public SOQLUtil soql{get;set;}
    private static SchemaUtil util = SchemaUtil.getInstance();
    private static final set<String> validTypes = new set<String>{'RMA Receipt For Repair'};
    private static final String FIELD_SET = 'RMA_For_Repair';
    public string HelpURL{get;set;}

    public CreateRepairDocumentsExt(ApexPages.StandardController con) {
        solList = new List<Sales_Order_Line__c>();
        wrapperList = new List<RepairGridCon.WarrantyWrapper>();
        Id rdId = con.getId();
        HelpURL=URL.getSalesforceBaseUrl().toExternalForm()+'/apex/'+'HelpRepairDocuments';
        set<String> queryFields = new set<String>{
                'Id', 'Type__c'
        };
        soql = new SOQLUtil('Receiving_Document__c', TRUE);
        soql.addFields(queryFields);
        soql.setWhereClause('Id = :rdId');
        List<String> solQueryFields = util.getFieldsFromFieldSetString('Sales_Order_Line__c', FIELD_SET);
        List<String> additonalsolFields = new List<String>{'Company__c', 'Quantity_Fulfilled__c'};
        solQueryFields.addAll(additonalsolFields);

        String namespace = String.isBlank(KSE.NamespaceUU) ? '' : KSE.NamespaceUU.toLowerCase();
        Schema.sObjectType sObjType = util.getGlobalDescribe('Sales_Order_Line__c');
        Map<String, Schema.sObjectField> solFieldsMap = sObjType.getDescribe().fields.getMap();

        for(Integer i = 0; i < solQueryFields.size(); i++){

            string fieldPath = string.escapeSingleQuotes(solQueryFields[i]);
            fieldpath = fieldpath.trim();

            Schema.sObjectField sObjField;
            sObjField = solFieldsMap.containsKey(fieldPath) ? solFieldsMap.get(fieldPath) : solFieldsMap.get(namespace + fieldPath);

            if(sObjField != null){
                Schema.DescribeFieldResult dfr = sObjField.getDescribe();

                fieldPath = fieldPath.replace(namespace, '').toLowerCase();
                if(dfr.getType() == Schema.DisplayType.REFERENCE){
                    solQueryFields.add(fieldpath.replace('__c','__r.Name').toLowerCase().trim());
                }
            }

            solQueryFields[i] = 'Sales_Order_Line__r.' + solQueryFields[i];
        }
        //Need to exclude hyperlink field. Apex JSON Parser cannot handle the html
        set<String> excludedFields = new set<String>{'Sales_Order_Line__r.name_hyperlink__c'};
        set<String> subQueryFields = new set<String>{'Id', 'Sales_Order_Line__r.Related_Sales_Order_Line__c', 'Sales_Order_Line__r.Sales_Order__r.Company__c',
                'Sales_Order_Line__r.Sales_Order__r.Customer__c', 'Sales_Order_Line__r.Sales_Order__r.Bill_To__c', 'Sales_Order_Line__r.Sales_Order__r.Pricing_Date__c',
                'Sales_Order_Line__r.Sales_Order__r.Currency__c', 'Sales_Order_Line__r.Sales_Order__r.Ship_To__c', 'Sales_Order_Line__r.Pricebook__c'};
        subQueryFields.addAll(solQueryFields);
        subQueryFields.removeAll(excludedFields);

        SOQLUtil.ChildRelationship childRel = new SOQLUtil.ChildRelationship(soql, 'Receipt_Lines__r');
        childRel.addFields(subQueryFields);

        soql.addChildRelationship(childRel);

        List<Receiving_Document__c> rdList = Database.query(soql.getQuery());

        set<Id> originalSOLIds = KSE.grepRelatedIdSetFromList(rdList[0].Receipt_Lines__r, 'Sales_Order_Line__r.Related_Sales_Order_Line__c');

        Datetime nowDateTime = system.now();

        soql = new SOQLUtil('Fulfillment__c', TRUE);
        soql.addFields(new set<String>{'Sales_Order_Line__r.Parent_Sales_Order_Line__c', 'Product__r.Product_Type__c'});
        soql.addFields('Warranty');
        soql.setWhereClause('Sales_Order_Line__r.Parent_Sales_Order_Line__c IN :originalSOLIds AND Product__r.Product_Type__c = \'Warranty\' AND Start_Date__c <= :nowDateTime AND End_Date__c > :nowDateTime');

        List<Fulfillment__c> fList = Database.query(soql.getQuery());

        map<Id, Fulfillment__c> mOriginalSOToFulfillmentMap = new map<Id, Fulfillment__c>();

        for(Fulfillment__c f : fList) {
            mOriginalSOToFulfillmentMap.put(f.Sales_Order_Line__r.Parent_Sales_Order_Line__c, f);
        }

        for (Receipt_Line__c rl : rdList[0].Receipt_Lines__r) {
            Sales_Order_Line__c sol = new Sales_Order_Line__c();
            RepairGridCon.WarrantyWrapper wrapper;
            sol = rl.Sales_Order_Line__r.clone(false, true);
            sol.Customer__c = rl.Sales_Order_Line__r.Sales_Order__r.Customer__c;
            sol.Receipt_Line__c = rl.Id;
            sol.Quantity_Fulfilled__c = null;
            sol.Required_Date__c = null;
            sol.Ship_From_Location__c = null;
            sol.Ship_From_Location__r.Name = null;
            sol.Sales_Order__c = null;
            sol.Quantity_Ordered__c = rl.Sales_Order_Line__r.Quantity_Fulfilled__c != null ? Math.Abs(rl.Sales_Order_Line__r.Quantity_Fulfilled__c) : 0;
            sol.Non_Shippable__c = false;
            sol.Invoiceable__c = false;
            sol.Related_Sales_Order_Line__c = rl.Sales_Order_Line__c;
            sol.Type__c = 'Repair';
            sol.Parent_Sales_Order_Line__c = null;
            if(mOriginalSOToFulfillmentMap.containsKey(rl.Sales_Order_Line__r.Related_Sales_Order_Line__c)) {
                wrapper = new RepairGridCon.WarrantyWrapper(sol, mOriginalSOToFulfillmentMap.get(rl.Sales_Order_Line__r.Related_Sales_Order_Line__c));
            } else {
                wrapper = new RepairGridCon.WarrantyWrapper(sol, null);
            }

            wrapperList.add(wrapper);
        }

        if(validTypes.contains(rdList[0].Type__c)) {
            resultJsonString = JSON.Serialize(wrapperList);
        } else {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, 'Receiving Document must have valid type for creating Repair Documents'));
        }
    }
}