src-ken&y/objects/Customer_Receipt__c.object
<CustomObject>
    <customHelpPage>HelpReceipts</customHelpPage>
    <description>Records all customer receipts (checks, credit cards, EFT, etc) against invoice.</description>
    <fields>
        <fullName>Bank_Account_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bank Account</label>
        <referenceTo>Bank_Account__c</referenceTo>
        <relationshipLabel>Customer Receipts</relationshipLabel>
        <relationshipName>Customer_Receipts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deposit_Identifier__c</fullName>
        <label>Deposit Identifier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Authorized</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Receipt</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Prepayment</fullName>
                </value>
                <value>
                    <fullName>Refund</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Receipt</label>
    <nameField>
        <label>Customer Receipt</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/CustomerReceiptAddDepositIDExt.cls
/**
 * Created by zainab_shikari on 10/13/17.
 */

public with sharing class CustomerReceiptAddDepositIDExt {

	public Apexpages.Standardsetcontroller ssCon {get;set;}
	public static list<String> sCRIds {get;set;}
	public String lCRIdsJSON{get{
		return JSON.serialize(sCRIds);}}

	public CustomerReceiptAddDepositIDExt (Apexpages.Standardsetcontroller ssController) {
		ssCon = ssController;
		sCRIds = new list<String>((Set<String>)JSON.deserialize(JSON.serialize(KSE.grepIdSetFromList(ssCon.getSelected())), Set<String>.class));
		system.debug(LoggingLevel.Error,'sCRIds '+sCRIds);
	}


	@RemoteAction
	public static JsonResult validateCustomerReceipts(list<id> sCRIds) {

		JsonResult result = new JsonResult();
		SOQLUtil soql = new SOQLUtil('Customer_Receipt__c', true);
		soql.addFields(new set<String>{'Id','Name'});
		soql.setWhereClause('ID in :sCRIds and (Type__c != \'Receipt\' OR Status__c in (\'Cancelled\',\'Void\') OR Bank_Account_2__c = null)');
		soql.setLimit(1);
		list<Customer_Receipt__c> badCustomerReceipts = Database.query(soql.getQuery());
		if(!badCustomerReceipts.isEmpty()) {
			result.success=false;
			result.addMessage(Label.Deposit_ID_CR_Bad_Selection,ApexPages.severity.ERROR);
		}else{
			result.success = true;
		}
		return  result;

	}

	@RemoteAction
	public static JsonResult saveDepositIDs(list<String> crIDs, String depositId) {
		JsonResult result = new JsonResult();
		list<Customer_Receipt__c> lCRs = new list<Customer_Receipt__c>();
		for(String id : crIDs) {
			lCRs.add(new Customer_Receipt__c(Id = id, Deposit_Identifier__c = depositId));
		}

		try{
			DML.updateAsUser(lCRs);
			result.success = true;
		}catch(DmlException ex) {
			result.addMessage(ex, ApexPages.Severity.ERROR);
			result.success = false;
		}catch(Exception ex) {
			result.addMessage(ex, ApexPages.Severity.ERROR);
			result.success = false;
		}
		return result;
	}


}