src-ken&y/objects/Customer__c.object
<CustomObject>
    <customHelpPage>HelpCustomers</customHelpPage>
    <description>Information that relates a Customer business to the manufacturing company (Company) and describes the business agreement between the two entities.</description>
    <fields>
        <fullName>Pricebook__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Pricebooks are associated with the Sold-to customer (one pricebook per customer).</inlineHelpText>
        <label>Pricebook</label>
        <referenceTo>Pricebook__c</referenceTo>
        <relationshipLabel>Customers</relationshipLabel>
        <relationshipName>Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ship_From_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>For Ship-To Customers Only</description>
        <label>Ship From Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Ship-to Customers</relationshipLabel>
        <relationshipName>Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Skip_Substitution__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box to skip the product substitution on a sales order line. (Currently applicable to sold-to customers only.)</description>
        <label>Skip Substitution</label>
        <type>Checkbox</type>
    </fields>
    <label>Customer</label>
    <nameField>
        <label>Customer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Facility__c.object
<CustomObject>
    <customHelpPage>HelpFacilites</customHelpPage>
    <description>Warehouse or building</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Facility&apos;s description</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Facility</label>
    <nameField>
        <label>Facility</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Pricebook__c.object
<CustomObject>
    <customHelpPage>HelpPricebooks</customHelpPage>
    <description>List prices for a company and the products it sells</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Details about this pricebook</description>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Pricebook</label>
    <nameField>
        <label>Pricebook Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricebooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Product__c.object
<CustomObject>
    <customHelpPage>HelpProducts</customHelpPage>
    <description>Products are sellable Items with Selling Unit of Measure included</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Product&apos;s description</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the product is the primary product in the upc group i.e, if the product is actually registered for UPC.</description>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UPC_Code__c</fullName>
        <description>13 char UPC code</description>
        <label>UPC Code</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Sales_Order_Line__c.object
<CustomObject>
    <customHelpPage>HelpSalesOrders_Managing</customHelpPage>
    <description>Line Items on the Sales Order.</description>
    <fields>
        <fullName>Customer_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Site</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Sales Order Lines (Customer)</relationshipLabel>
        <relationshipName>Sales_Order_Lines2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>If item is misc, a description is required; if item is not misc, add additional information as needed. The description will be entered automatically on sales orders, shipping, and invoicing documents.</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Has_Exceptions__c</fullName>
        <description>If selected, there is a problem with the sales order line. Exceptions must be resolved before you can process the order.</description>
        <formula>Exceptions_Count__c &gt; 0</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Has Exceptions</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Line__c</fullName>
        <description>Beginning line number on the sales order</description>
        <label>Line</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_Sales_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Sales Order Line</label>
        <referenceTo>Sales_Order_Line__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pricebook__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pricebook</label>
        <referenceTo>Pricebook__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Product</description>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <filterItems>
                <field>Product__c.Item__r.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Product__c.Company__c</field>
                <operation>equals</operation>
                <valueField>$Source.Company__c</valueField>
            </filterItems>
            <filterItems>
                <field>Product__c.Company__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Required_Date__c</fullName>
        <defaultValue>today( )</defaultValue>
        <description>Date the customer requires the line item</description>
        <label>Need Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ship_From_Facility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship From Facility</label>
        <referenceTo>Facility__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ship_From_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Location</description>
        <label>Ship From Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Sales Order Line Ship From Location value does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>Location__c.Facility__r.Company__c</field>
                <operation>equals</operation>
                <valueField>$Source.Company__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Sales Order Lines (Ship From Location)</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>UPC_Code__c</fullName>
        <description>13 char UPC code</description>
        <label>UPC Code</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <label>Sales Order Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Substitution__c.object
<CustomObject>
    <customHelpPage>HelpSubstitution</customHelpPage>
    <fields>
        <fullName>Block__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, the product is blocked from substitution for the matching customer(s) and/or warehouse(s).</description>
        <inlineHelpText>A check mark indicates that  the system prevents the selected product from being shipped to a customer and/or facility.  If a customer and/or facility are not specified, the block applies to all customers and facilities.</inlineHelpText>
        <label>Block</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Current_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The current product that the substitution should apply to.</description>
        <label>Current Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipName>Product_Selections</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Sold-to / Ship-to Customer to which the substitution should apply to.</description>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Customer__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Sold To, Ship To</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Substitutions</relationshipLabel>
        <relationshipName>Product_Selections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>The date on which the substitution is effective until.</description>
        <inlineHelpText>Date on which the block or substitution ends. The end date must be greater than the start date.</inlineHelpText>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Facility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The facility to which the substitution should apply to.</description>
        <label>Facility</label>
        <referenceTo>Facility__c</referenceTo>
        <relationshipName>Product_Selections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <formula>Current_Product__r.Primary__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>A check mark indicates that  the current product is the primary product.</inlineHelpText>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>The date on which the substitution is effective from.</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Substitute_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The product that should be substituted for the current product.</description>
        <inlineHelpText>The substitute product must have the same UPC code as the current product.</inlineHelpText>
        <label>Substitute Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Substitutions (Substitute Product)</relationshipLabel>
        <relationshipName>Product_Selections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Substitution</label>
    <nameField>
        <label>Substitution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Substitutions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/SubstitutionTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers for Substitution__c object.
 */
 
//	Tests to perform:
//  1. Assert that Start date must be before End date.
//  2. Assert that Start range is not overlapped for similar rules.
//	3. Assert that only the rule active currently is being use. Not the past or future rules.
//	4. Assert that the most specific rule is chosen and falls back to generic rules if not available.
//	5. Assert that reason code is of type substitution.

@isTest
private class SubstitutionTest {
	
	static TestData globalTestData = new TestData();
	
	class SubstitutionTestData {
		
		// Create a substitution rule for Product-10 as primary (registered) product in the UPC group.
		public Substitution__c sub {
			get{
				if(sub == null){
					sub = new Substitution__c();
					sub.Name='Primary Product Sub';
					sub.Current_Product__c = globalTestData.product.Id;
                    sub.Start_Date__c = system.today()-1;
					sub.End_Date__c = system.today() + 720;
				}
				return sub;
			}
			set;
		}
		
		// Create a substitution rule to ALWAYS substitute Product-10 with Product-15.
		public Substitution__c sub2 {
			get{	
				if(sub2 == null){
					sub2 = new Substitution__c();
					sub2.Name='Secondary Product Sub';
					sub2.Current_Product__c = globalTestData.product2.Id;
					sub2.Substitute_Product__c = globalTestData.product.Id;
                    sub2.Start_Date__c = system.today()-1;
					sub2.End_Date__c = system.today() + 720;	
				}
				return sub2;
			}
			set;
		}
							  
		
		{	
			// Make sure that the two products have the same UPC code
			globalTestData.product2.UPC_Code__c = globalTestData.product.UPC_Code__c;
			update globalTestData.product2;
						
			// Initializes and inserts subtitution records.				  
			insert new List<Substitution__c>{sub, sub2};			
			
			// Assert that the records have been inserted.
			system.assert(sub.Id != null && sub2.Id != null );
			
		}
							  
	}
	
	//  KNDY-2122: Test the basic substitution functionality where the substitution rule is found correctly and 
	//	the product on the sales order line is substituted with another similar product.
	static testMethod void testProductSubstitution() {
    	
    	Test.startTest();
    	
    	SubstitutionTestData localTestData = new SubstitutionTestData();
    	
    	// Make sure the ordered date is within substitution rule's effective range.
    	globalTestData.salesOrder.Date_Time_Ordered__c = System.now();
    	update globalTestData.salesOrder;
    	
    	// Change the product to "Product-15" on all the so lines.
        List<Sales_Order_Line__c> updatedSOLines = new List<Sales_Order_Line__c>();
    	for(Sales_Order_Line__c sol : globalTestData.salesOrder.Sales_Order_Lines__r){
        	if(sol.Product__c != globalTestData.product2.Id){ 
        		sol.Product__c = globalTestData.product2.Id;
        		updatedSOLines.add(sol);
        	}
        }
        
        // Assert that atleast one sales order line is updated to test.
        system.assertNotEquals(0, updatedSOLines.size(), 'No lines were updated to Product-10 for testing');
        update updatedSOLines;
        
        for(Sales_Order_Line__c sol : [select Id, Product__c from Sales_Order_Line__c where Id IN :updatedSOLines]){
        	// Assert that the Product-15 is substituted with Product-10
        	system.assertEquals(globalTestData.product.Id, sol.Product__c);
        }
        
    }
    
    // KNDY-2122: Test that if the primary product is blocked, then the secondary products are blocked too, unless,
    // there is a more specific rule for that product.
    static testMethod void testPrimaryProductBlock() {
    	
    	Test.startTest();
    	
    	SubstitutionTestData localTestData = new SubstitutionTestData();
    	localTestData.sub.Block__c = true;
    	update localTestData.sub;
    	
    	// Make sure the ordered date is within substitution rule's effective range.
    	globalTestData.salesOrder.Date_Time_Ordered__c = System.now();
    	update globalTestData.salesOrder;
    	
    	// Make Product-10 primary product of the UPC group.
    	globalTestData.product.Primary__c = true;
    	update globalTestData.product;
    	
    	SalesOrderFlowCache.flush(Product__c.sObjectType);
    	
    	// Change the product to "Product-15" on all the so lines.
        List<Sales_Order_Line__c> updatedSOLines = new List<Sales_Order_Line__c>();
    	for(Sales_Order_Line__c sol : globalTestData.salesOrder.Sales_Order_Lines__r){
        	if(sol.Product__c != globalTestData.product2.Id){ 
        		sol.Product__c = globalTestData.product2.Id;
        		updatedSOLines.add(sol);
        	}
        }
        
        // Assert that atleast one sales order line is updated to test.
        system.assertNotEquals(0, updatedSOLines.size(), 'No lines were updated to Product-10 for testing');
        update updatedSOLines;
        
        for(Sales_Order_Line__c sol : [select Id, Product__c, Has_Exceptions__c
        								 from Sales_Order_Line__c 
        								where Id IN :updatedSOLines]){
        	// Assert that the Product-10 is substituted with Product-15
        	system.assert(sol.Has_Exceptions__c);
        	system.assertEquals(globalTestData.product2.Id, sol.Product__c);
        	system.assertEquals(true, ExceptionService.hasOpenTask(sol.Id, ExceptionUtil.PRODUCT_IS_BLOCKED.code));
        }
        
        Product__c product3 = globalTestData.product2.clone();
    	product3.Name = 'Product-11';
    	insert product3;
    	
        Substitution__c sub3 = new Substitution__c(
								  Name='SUB-3',
								  Facility__c = globalTestData.facility2.Id,
								  Current_Product__c = globalTestData.product.Id,
								  Substitute_Product__c = product3.Id,
                                  Start_Date__c = system.today()-1,
								  End_Date__c = system.today() + 720
							   );
    	insert sub3;
        
        // Change the product to "Product-10" on all the so lines.
        for(Sales_Order_Line__c sol : updatedSOLines){
    		sol.Product__c = globalTestData.product.Id;
        }
        
        // Assert that atleast one sales order line is updated to test.
        system.assertNotEquals(0, updatedSOLines.size(), 'No lines were updated to Product-10 for testing');
        update updatedSOLines;
        
        for (Sales_Order_Line__c sol : [SELECT Id, Product__c, Has_Exceptions__c, Description__c
        								  FROM Sales_Order_Line__c WHERE Id IN :updatedSOLines]){
        	// Assert that the Product-10 is substituted with Product-15
            System.assertEquals(product3.Description__c, sol.Description__c);
        	system.assertEquals(product3.Id, sol.Product__c, 'Expected the product to get substituted.');
        }
    }
    
    //	KNDY-2122: Test the substitution for a product and facility.
	static testMethod void testFacilityProductSubstitution() {
    	
    	Test.startTest();
    	
    	SubstitutionTestData localTestData = new SubstitutionTestData();
    	
    	Product__c product3 = globalTestData.product2.clone();
    	product3.Name = 'Product-11';
    	insert product3;
    	
    	Substitution__c sub3 = new Substitution__c(
								  Name='SUB-3',
								  Facility__c = globalTestData.facility2.Id,
								  Current_Product__c = globalTestData.product.Id,
								  Substitute_Product__c = product3.Id,
                                  Start_Date__c = system.today()-1,
								  End_Date__c = system.today() + 720
								  );
    	insert sub3;
    	
    	// Make sure the ordered date is within substitution rule's effective range.
    	globalTestData.salesOrder.Date_Time_Ordered__c = System.now();
    	globalTestData.salesOrder.Ship_From_Location__c = null;
    	update globalTestData.salesOrder;
    	
    	// Change the product to "Product-10" on all the so lines.
        List<Sales_Order_Line__c> updatedSOLines = new List<Sales_Order_Line__c>();
    	for(Sales_Order_Line__c sol : globalTestData.salesOrder.Sales_Order_Lines__r){
        	if(sol.Product__c != globalTestData.product.Id){ 
        		sol.Product__c = globalTestData.product.Id;
        		sol.Ship_From_Location__c = null;
        		updatedSOLines.add(sol);
        	}
        }
        
        // Assert that atleast one sales order line is updated to test.
        system.assertNotEquals(0, updatedSOLines.size(), 'No lines were updated to Product-10 for testing');
        update updatedSOLines;
        
        for(Sales_Order_Line__c sol : [select Id, Product__c from Sales_Order_Line__c where Id IN :updatedSOLines]){
        	// Assert that the Product-10 is substituted with Product-11
        	system.assertEquals(globalTestData.product.Id, sol.Product__c);
        }
        
        for(Sales_Order_Line__c sol : updatedSOLines){
        	sol.Ship_From_Location__c = globalTestData.location2.Id;
        }
        update updatedSOLines;
         
        for(Sales_Order_Line__c sol : [select Id, Product__c from Sales_Order_Line__c where Id IN :updatedSOLines]){
        	// Assert that the Product-10 is substituted with Product-11
        	system.assertEquals(product3.Id, sol.Product__c);
        }
        
    }
    
    // OTC-593
    static testMethod void testFacilityProductSubstitutionPriceError() {
    	
    	Test.startTest();
    	
    	SubstitutionTestData localTestData = new SubstitutionTestData();

  	
    	// Make sure the ordered date is within substitution rule's effective range.
    	globalTestData.salesOrder.Date_Time_Ordered__c = System.now();
    	globalTestData.salesOrder.Ship_From_Location__c = null;
    	update globalTestData.salesOrder;
    	
    	
    	
    	for(Sales_Order_Line__c sol : [select Id, Product__c, Unit_Price__c, Pricebook__c from Sales_Order_Line__c where Id 
    									IN :globalTestData.salesOrder.Sales_Order_Lines__r]){
        	system.assertNotEquals(null, sol.Unit_Price__c);
        	system.assertNotEquals(null, sol.Pricebook__c);
        	system.debug(LoggingLevel.INFO, sol);
        }
    	
        List<Sales_Order_Line__c> updatedSOLines = new List<Sales_Order_Line__c>();
    	for(Sales_Order_Line__c sol : globalTestData.salesOrder.Sales_Order_Lines__r){
    		sol.Ship_From_Location__c = null;
    		updatedSOLines.add(sol);
    	}
        
        // Assert that atleast one sales order line is updated to test.
        system.assertNotEquals(0, updatedSOLines.size(), 'No lines were updated to Product-10 for testing');
        update updatedSOLines;
        
        for(Sales_Order_Line__c sol : [select Id, Product__c, Unit_Price__c, Pricebook__c from Sales_Order_Line__c where Id IN :updatedSOLines]){
        	system.assertNotEquals(null, sol.Unit_Price__c);
        	system.assertNotEquals(null, sol.Pricebook__c);
        	system.debug(LoggingLevel.INFO, sol);
        	
        }
        
        for(Sales_Order_Line__c sol : updatedSOLines){
        	sol.Ship_From_Location__c = globalTestData.location2.Id;
        }
        update updatedSOLines;
         
        for(Sales_Order_Line__c sol : [select Id, Product__c, Unit_Price__c, Pricebook__c from Sales_Order_Line__c where Id IN :updatedSOLines]){
        	system.assertNotEquals(null, sol.Unit_Price__c);
        	system.assertNotEquals(null, sol.Pricebook__c);
        	system.debug(LoggingLevel.INFO, sol);
        	
        }
        
    }
    
    //	KNDY-2122: Test the substitution for a customer and product.
	static testMethod void testCustomerProductSubstitution() {
    	
    	Test.startTest();
    	
    	SubstitutionTestData localTestData = new SubstitutionTestData();
    	
    	Product__c product3 = globalTestData.product2.clone();
    	product3.Name = 'Product-11';
    	insert product3;
    	
    	Substitution__c sub3 = new Substitution__c(
								  Name='SUB-3',
								  Customer__c = globalTestData.customerShipTo.Id, // Ship-to customer
								  Current_Product__c = globalTestData.product.Id,
								  Substitute_Product__c = product3.Id,
                                  Start_Date__c = system.today()-1,
								  End_Date__c = system.today() + 720
								  );
    	insert sub3;
    	
    	// Make sure the ordered date is within substitution rule's effective range.
    	globalTestData.salesOrder.Date_Time_Ordered__c = System.now();
    	update globalTestData.salesOrder;
    	
    	// Change the product to "Product-10" on all the so lines.
        List<Sales_Order_Line__c> updatedSOLines = new List<Sales_Order_Line__c>();
    	for(Sales_Order_Line__c sol : globalTestData.salesOrder.Sales_Order_Lines__r){
        	if(sol.Product__c != globalTestData.product.Id){ 
        		sol.Product__c = globalTestData.product.Id;
        		updatedSOLines.add(sol);
        	}
        }
        
        // Assert that atleast one sales order line is updated to test.
        system.assertNotEquals(0, updatedSOLines.size(), 'No lines were updated to Product-10 for testing');
        update updatedSOLines;
        
        for(Sales_Order_Line__c sol : [select Id, Product__c from Sales_Order_Line__c where Id IN :updatedSOLines]){
        	// Assert that the Product-10 is substituted with Product-11
        	system.assertEquals(product3.Id, sol.Product__c);
        }
        
    }
    
    //	KNDY-2122: Test the substitution for a customer, facility and product.
	static testMethod void testFacilityCustomerProductSubstitution() {
    	
    	Test.startTest();
    	
    	SubstitutionTestData localTestData = new SubstitutionTestData();
    	
    	Product__c product3 = globalTestData.product2.clone();
    	product3.Name = 'Product-11';
    	insert product3;
    	
    	Substitution__c sub3 = new Substitution__c(
								  Name='SUB-3',
								  Facility__c = globalTestData.facility2.Id,
								  Customer__c = globalTestData.customer.Id,
								  Current_Product__c = globalTestData.product.Id,
								  Substitute_Product__c = product3.Id,
                                  Start_Date__c = system.today()-1,
								  End_Date__c = system.today() + 720
								  );
    	insert sub3;
    	
    	// Make sure the ordered date is within substitution rule's effective range.
    	globalTestData.salesOrder.Date_Time_Ordered__c = System.now();
    	globalTestData.salesOrder.Ship_From_Location__c = null;
    	update globalTestData.salesOrder;
    	
    	// Change the product to "Product-10" on all the so lines.
        List<Sales_Order_Line__c> updatedSOLines = new List<Sales_Order_Line__c>();
    	for(Sales_Order_Line__c sol : globalTestData.salesOrder.Sales_Order_Lines__r){
        	if(sol.Product__c != globalTestData.product.Id){ 
        		sol.Product__c = globalTestData.product.Id;
        		updatedSOLines.add(sol);
        	}
        }
        
        // Assert that atleast one sales order line is updated to test.
        system.assertNotEquals(0, updatedSOLines.size(), 'No lines were updated to Product-10 for testing');
        update updatedSOLines;
        
        for(Sales_Order_Line__c sol : [select Id, Product__c from Sales_Order_Line__c where Id IN :updatedSOLines]){
        	// Assert that the Product-10 is substituted with Product-11
        	system.assertEquals(product3.Id, sol.Product__c);
        }
        
    }
    
    //	KNDY-2122: Test skipping substitution for a sold-to customer for any facility and any product.
	static testMethod void testSkipProductSubstitution() {
    	
    	Test.startTest();
    	
    	SubstitutionTestData localTestData = new SubstitutionTestData();
    	
    	Product__c product3 = globalTestData.product2.clone();
    	product3.Name = 'Product-11';
    	insert product3;
    	
    	Substitution__c sub3 = new Substitution__c(
								  Name='SUB-3',
								  Facility__c = globalTestData.facility.Id,
								  Customer__c = globalTestData.customer.Id,
								  Current_Product__c = globalTestData.product.Id,
								  Substitute_Product__c = product3.Id,
                            	  Start_Date__c = system.today()-1,
								  End_Date__c = system.today() + 720
								  );
    	insert sub3;
    	
    	// Make sure the ordered date is within substitution rule's effective range.
    	globalTestData.salesOrder.Date_Time_Ordered__c = System.now();
    	update globalTestData.salesOrder;
    	
    	// Set the skip subtitution flag on the sold-to customer.
    	globalTestData.customer.Skip_Substitution__c = true;
    	update globalTestData.customer;
    	
    	// Change the product to "Product-10" on all the so lines.
        List<Sales_Order_Line__c> updatedSOLines = new List<Sales_Order_Line__c>();
    	for(Sales_Order_Line__c sol : globalTestData.salesOrder.Sales_Order_Lines__r){
        	if(sol.Product__c != globalTestData.product.Id){ 
        		sol.Product__c = globalTestData.product.Id;
        		sol.Ship_From_Location__c = globalTestData.location.Id;
        		updatedSOLines.add(sol);
        	}
        }
        
        // Assert that atleast one sales order line is updated to test.
        system.assertNotEquals(0, updatedSOLines.size(), 'No lines were updated to Product-10 for testing');
        update updatedSOLines;
        
        for(Sales_Order_Line__c sol : [select Id, Product__c from Sales_Order_Line__c where Id IN :updatedSOLines]){
        	// Assert that the Product-10 is not substituted
        	system.assertEquals(globalTestData.product.Id, sol.Product__c);
        }
    }
    
    // OTC-447: Test that substitution is triggered when one of 
    // the following fields are changed on the sales order lines.
    // 1. Product
	// 2. Estimated Ship Date
	// 3. Ship From Location
	static testMethod void testSubstitutionOnUpdate() {
    	
    	Test.startTest();
    	
    	//SubstitutionTestData localTestData = new SubstitutionTestData();
    	
    	Product__c product3 = globalTestData.product.clone();
    	product3.Name = 'Product-11';
    	insert product3;
    	
    	Substitution__c sub3 = new Substitution__c(
								  Name='SUB-3',
								  Facility__c = globalTestData.facility2.Id,
								  Customer__c = globalTestData.customer.Id,
								  Current_Product__c = globalTestData.product.Id,
								  Substitute_Product__c = product3.Id,
                            	  Start_Date__c = system.today()-1,
								  End_Date__c = system.today() + 720
								  );
    	insert sub3;
    	
    	List<Sales_Order_Line__c> solList = [select Id, Product__r.Name 
											   from Sales_Order_Line__c 
										      where Id IN :globalTestData.salesOrder.Sales_Order_Lines__r 
										      order by Line__c];
    	
    	// Change the product to "Product-10" on all the so lines.
        List<Sales_Order_Line__c> updatedSOLines = new List<Sales_Order_Line__c>();
    	for(Sales_Order_Line__c sol : solList){
        	if(sol.Product__c != globalTestData.product.Id){ 
        		sol.Product__c = globalTestData.product.Id;
        		updatedSOLines.add(sol);
        	}
        }
        
        // Assert that atleast one sales order line is updated to test.
        system.assertNotEquals(0, updatedSOLines.size(), 'No lines were updated to Product-10 for testing');
        
        // Clear the ship from location and required date (which should clear the estimated ship date).
    	solList[0].Ship_From_Location__c = null;
    	solList[1].Required_Date__c = system.today() - 5;
    	
        update solList;
        
        solList = [select Id, Product__r.Name 
					 from Sales_Order_Line__c 
				    where Id IN :solList order by Line__c];
        												   
        for(Sales_Order_Line__c sol : solList){
        	// Assert that the Product-10 is not substituted with Product-11
        	system.assertEquals(globalTestData.product.Id, sol.Product__c,
        			'Did not expect product to be substituted: ' + sol.Product__r.Name);
        }
        
        solList[0].Ship_From_Location__c = globalTestData.location1.Id;
        solList[1].Required_Date__c = system.today() + 5;
    	update solList;
    	
    	solList = [select Id, Product__r.Name 
					 from Sales_Order_Line__c 
				    where Id IN :solList order by Line__c];
        
        for(Sales_Order_Line__c sol : solList){
        	// Assert that the Product-10 is substituted with Product-11
        	system.assertEquals(product3.Id, sol.Product__c, 
        			'Expected product to be substituted: ' + sol.Product__r.Name);
        }
    }
}