src-ken&y/objects/Customer__c.object
<CustomObject>
    <customHelpPage>HelpCustomers</customHelpPage>
    <description>Information that relates a Customer business to the manufacturing company (Company) and describes the business agreement between the two entities.</description>
    <fields>
        <fullName>Ship_From_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>For Ship-To Customers Only</description>
        <label>Ship From Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Ship-to Customers</relationshipLabel>
        <relationshipName>Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of this customer: Approved,Under Consideration,Pending Approval,Not Approved,Inactive</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer</label>
    <nameField>
        <label>Customer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Location__c.object
<CustomObject>
    <customHelpPage>HelpLocations</customHelpPage>
    <description>Organizational Unit or physical location primarily used if  subclassification reporting is desired</description>
    <label>Location</label>
    <nameField>
        <label>Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Sales_Order__c.object
<CustomObject>
    <customHelpPage>HelpSalesOrders_Managing</customHelpPage>
    <description>Sales Order Header</description>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Customer</description>
        <label>Customer Sold To</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <errorMessage>Sales Order Customer value does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>Customer__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Sold To</value>
            </filterItems>
            <filterItems>
                <field>Customer__c.Company__c</field>
                <operation>equals</operation>
                <valueField>$Source.Company__c</valueField>
            </filterItems>
            <filterItems>
                <field>Customer__c.Company__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Sales Orders (Customer)</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ship_From_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Ship From Location</description>
        <label>Ship From Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ship_to__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Customer</description>
        <label>Customer Ship To</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Customer__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Ship To</value>
            </filterItems>
            <filterItems>
                <field>Customer__c.Parent_Customer__c</field>
                <operation>equals</operation>
                <valueField>$Source.Customer__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Sales Orders (Ship To)</relationshipLabel>
        <relationshipName>Sales_Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Order status</description>
        <label>Order Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>On hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Sales_Order_Line__c.object
<CustomObject>
    <customHelpPage>HelpSalesOrders_Managing</customHelpPage>
    <description>Line Items on the Sales Order.</description>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Sales Order Lines (Customer)</relationshipLabel>
        <relationshipName>Sales_Order_Lines2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity_Backordered__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Calculated field which equals quantity ordered - (quantity allocated + quantity shipped) </description>
        <inlineHelpText>Calculation: Quantity Ordered - (Quantity Allocated + Quantity Shipped). A sales order line cannot be closed if the backordered quantity is greater than zero.</inlineHelpText>
        <label>Quantity Backordered</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity_Ordered__c</fullName>
        <description>The number of items ordered in this sales order line</description>
        <label>Quantity Ordered</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity_Planned__c</fullName>
        <defaultValue>0.0</defaultValue>
        <description>The total quantity that is currently planned for shipping.</description>
        <inlineHelpText>The total quantity that is currently planned for shipping.</inlineHelpText>
        <label>Quantity Planned</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity_Shipped__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The number of items that have been shipped to date. This field is copied over and kept up to date from the corresponding shipment details object.</description>
        <label>Quantity Shipped</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <label>Sales Order</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Company does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>Sales_Order__c.Company__c</field>
                <operation>equals</operation>
                <valueField>$Source.Company__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Sales_Order__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ship_From_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Location</description>
        <label>Ship From Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Sales Order Line Ship From Location value does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>Location__c.Facility__r.Company__c</field>
                <operation>equals</operation>
                <valueField>$Source.Company__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Sales Order Lines (Ship From Location)</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Line open if item is not shipped; line closed if shipped; line partial if partially shipped</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <label>Sales Order Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Shipment__c.object
<CustomObject>
    <customHelpPage>HelpShipment</customHelpPage>
    <description>Sales Order Shipment Header</description>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Shipt To Customer</description>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Customer__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Ship To</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ship_From_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The location from which the shipment will be shipped.</description>
        <inlineHelpText>The location from which the shipment will be shipped.</inlineHelpText>
        <label>Ship From Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipment_Date_Estimated__c</fullName>
        <inlineHelpText>This date is driven by the Required Date (see Sales Order) and the Earliest Shipment Date.</inlineHelpText>
        <label>Estimated Ship Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>Released</fullName>
                </value>
                <value>
                    <fullName>Staged</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Shipment</label>
    <nameField>
        <label>Shipment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/ShipmentPlanExt.cls
public with sharing class ShipmentPlanExt extends GridRelatedListController {
		
	public String salesOrderLineFieldList ;
	public String fulfillmentLinesFieldList ;
	
	public GridRelatedListController.GridRelatedListConfig salesOrderLinesGridConfig {get; set;}
	public GridRelatedListController.GridRelatedListConfig fulfillmentLinesGridConfig {get; set;}
	
	public class PlanWrapper {
		public Shipment__c selectedPlan ;
		public List<Shipment__c> availablePlans ;
		public List<Sales_Order_Line__c> linesToPlan ;
		
		public PlanWrapper(){
			
		}
	}
	
	public ShipmentPlanExt(ApexPages.StandardController sCon){
		
		if(! Test.isRunningTest()){
			sCon.addFields(new List<string>{'Name','Id'});
		}
		
		// Sales Order Lines Grid Config
        salesOrderLinesGridConfig = new GridRelatedListController.GridRelatedListConfig();
        salesOrderLinesGridConfig.uniqueId = 'salesOrderLinesGrid';
        salesOrderLinesGridConfig.title = '';
        salesOrderLinesGridConfig.objectName = 'Shipment__c';
        salesOrderLinesGridConfig.fieldset = 'Planning_Detail';
        salesOrderLinesGridConfig.buttons = '';
        salesOrderLinesGridConfig.alwaysUseFullDateTimeFormat = false;
        
        // Available shipments Grid Config
        fulfillmentLinesGridConfig = new GridRelatedListController.GridRelatedListConfig();
        fulfillmentLinesGridConfig.uniqueId = 'fulfillmentLinesGrid';
        fulfillmentLinesGridConfig.title = '';
        fulfillmentLinesGridConfig.objectName = 'Sales_Order_Line__c'; 
        fulfillmentLinesGridConfig.fieldset = 'Planning_Detail';
        fulfillmentLinesGridConfig.buttons = '';
        fulfillmentLinesGridConfig.alwaysUseFullDateTimeFormat = false;
	}
	
	public String getSalesOrderLinesGridConfigJson() {
        String configStr = JSON.serialize(this.salesOrderLinesGridConfig);
        return configStr;
    }
    
    public String getFulfillmentLinesGridConfigJson() {
        String configStr = JSON.serialize(this.fulfillmentLinesGridConfig);
        return configStr;
    }
    
	public String getSalesOrderLineFieldList() {
		
        if (String.isBlank(salesOrderLineFieldList) && salesOrderLinesGridConfig != null) {
        	
        	FieldInfo fieldInfoItem;
        	
        	// get the Payment line details field info list
            List<FieldInfo> fieldInfoList = FieldInfo.fetchJsonFieldInfos(salesOrderLinesGridConfig.objectName, salesOrderLinesGridConfig.fieldset);
            Set<String> hiddenFields = new Set<String> {'Id'};
            
            for(Integer i = 0; i < fieldInfoList.size(); i++){
            	String fieldName = fieldInfoList[i].field;
            	
            	if(fieldName != 'Id' && fieldName != 'Name'){
                    fieldInfoList[i].field = 'selectedPlan.' + fieldName;
                }
                
            	fieldInfoList[i].editable = false;
            	fieldInfoList[i].hidden = hiddenFields.contains(fieldName);
            }
            
            salesOrderLineFieldList = JSON.serialize(fieldInfoList);
        }
        
        return salesOrderLineFieldList;
    }
    
    public String getFulfillmentLinesFieldList() {
       
        if (String.isBlank(fulfillmentLinesFieldList) && fulfillmentLinesGridConfig != null) {
        	
        	FieldInfo fieldInfoItem;
        	
        	// get the Substitutions field info list
            List<FieldInfo> fieldInfoList = FieldInfo.fetchJsonFieldInfos(fulfillmentLinesGridConfig.objectName, fulfillmentLinesGridConfig.fieldset);
            Set<String> hiddenFields = new Set<String> { 'Id'};
            
            // set all the fields as readonly
            for(Integer i = 0; i < fieldInfoList.size(); i++){
            	String fieldName = fieldInfoList[i].field;
            	if(fieldName != 'Id' && fieldName != 'Name'){
            		//fieldInfoList[i].field = NamespaceUU + fieldName;
            	}
            	fieldInfoList[i].editable = false;
            	fieldInfoList[i].hidden = hiddenFields.contains(fieldName);
            }
        	
            fulfillmentLinesFieldList = JSON.serialize(fieldInfoList);
        }
        
        return fulfillmentLinesFieldList;
    }
    
	@RemoteAction
	public static JsonResult getSalesOrderLines(List<String> filters){
		
		List<PlanWrapper> solWrapperList = new List<PlanWrapper>();
		Map<Shipment__c, List<Shipment__c>> shipmentsMap = new Map<Shipment__c, List<Shipment__c>>();
		Map<Shipment__c, List<Sales_Order_Line__c>> fulfillmentLinesMap = new Map<Shipment__c, List<Sales_Order_Line__c>>();
		Map<String, Set<String>> shipmentFilters = new Map<String, Set<String>>(); 
		List<Sales_Order_Line__c> salesOrderLines = new List<Sales_Order_Line__c>(); 
		Set<String> shipFromLocationIds = new Set<String>();
		Set<String> shipToIds = new Set<String>();
		
		SchemaUtil shUtil = new SchemaUtil();
		
		String whereClause = '';
		
		filters.add(' Quantity_Backordered__c > 0 ');
		filters.add(' Status__c = \'Open\' ');
							 
		Iterator<String> iFilters = filters.iterator();
        
        while(iFilters.hasNext()){
            whereClause += iFilters.next();
            
            if(iFilters.hasNext()){
                whereClause += ' and ';    
            }
        }
        					 
		/*String solQuery = shUtil.generateQueryFromFieldSet('Sales_Order_Line__c', 
															  new Set<String>{'Planning_Detail'}, 
															  new Set<String>{'Id', 'Name', 'Ship_From_Location__c', 'Quantity_Planned__c', 'Quantity_Shipped__c', 
															  				  'Quantity_Ordered__c', 'Ship_From_Location__r.Name', 
															  				  'Sales_Order__r.Ship_To__c', 'Sales_Order__r.Ship_To__r.Name'}, 
															  whereClause
														  );*/
		
		SOQLUtil soql = new SOQLUtil('Sales_Order_Line__c');
	    soql.addFields('Planning_Detail');
	    soql.addFields(new Set<String>{'Id', 'Name', 'Ship_From_Location__c', 'Quantity_Planned__c', 'Quantity_Shipped__c', 
															  				  'Quantity_Ordered__c', 'Ship_From_Location__r.Name', 
															  				  'Sales_Order__r.Ship_To__c', 'Sales_Order__r.Ship_To__r.Name'
					  });
	    soql.setWhereClause(whereClause);
	    	
		for(Sales_Order_Line__c sol : (List<Sales_Order_Line__c>) Database.query(soql.getQuery())){
			if(sol.Quantity_Ordered__c > KSE.addQuantityToField(sol.Quantity_Planned__c, sol.Quantity_Shipped__c)){
				Shipment__c solKey = new Shipment__c(
										Ship_From_Location__r = sol.Ship_From_Location__r, 
							   			Customer__r = sol.Sales_Order__r.Ship_To__r
							   		 );
										
				if(fulfillmentLinesMap.containsKey(solKey) == false){
					fulfillmentLinesMap.put(solKey, new List<Sales_Order_Line__c>());
				}
				
				fulfillmentLinesMap.get(solKey).add(sol);
				
				shipFromLocationIds.add(sol.Ship_From_Location__c);
				shipToIds.add(sol.Sales_Order__r.Ship_To__c);
			}
		}					 
		
		String shipmentWhereClause = '';
		shipmentWhereClause += ' Status__c NOT IN (\'Confirmed\', \'Delivered\') ';
		shipmentWhereClause += ' AND Ship_From_Location__c IN :shipFromLocationIds ';
		shipmentWhereClause += ' AND Customer__c IN :shipToIds ';
							 
		/*String shipmentQuery = shUtil.generateQueryFromFieldSet(
									  'Shipment__c', 
									  new Set<String>{'Sales_Order_Plan_Detail'}, 
									  new Set<String>{'Id', 'Name', 'Ship_From_Location__c', 'Customer__c', 
									  				  'Ship_From_Location__r.Name', 'Customer__r.Name'}, 
									  shipmentWhereClause
							   );*/
		
		soql = new SOQLUtil('Shipment__c');
	    soql.addFields('Sales_Order_Plan_Detail');
	    soql.addFields(new Set<String>{'Id', 'Name', 'Ship_From_Location__c', 'Customer__c', 
									  				  'Ship_From_Location__r.Name', 'Customer__r.Name'});
	    soql.setWhereClause(shipmentWhereClause);
	    
		List<Shipment__c> availableShipments = (List<Shipment__c>) Database.query(soql.getQuery());
		
		for(Shipment__c shipment : availableShipments){
			Shipment__c shipmentKey = new Shipment__c(
											Ship_From_Location__r = shipment.Ship_From_Location__r, 
							   				Customer__r = shipment.Customer__r
							   		  );
										
			if(shipmentsMap.containsKey(shipmentKey) == false){
				shipmentsMap.put(shipmentKey, new List<Shipment__c>());
			}
			
			shipmentsMap.get(shipmentKey).add(shipment);
		} 
		
		for(Shipment__c planningKey : fulfillmentLinesMap.keySet()){
			
			PlanWrapper planningWrapper = new PlanWrapper();
			planningWrapper.selectedPlan = planningKey;
			planningWrapper.availablePlans = shipmentsMap.get(planningKey);
			planningWrapper.linesToPlan = fulfillmentLinesMap.get(planningKey);
			
			// Add available shipments with zero lines.
		    solWrapperList.add(planningWrapper);
		}
		
		JsonResult result = new JsonResult();
		result.records = solWrapperList;
        result.total = solWrapperList.size();
        
        if(solWrapperList.isEmpty()){
        	result.addMessage('No open sales order lines found for planning.', ApexPages.Severity.INFO);
        }
        
        return result;   
	}
	
	@RemoteAction
	public static JsonResult plan(List<PlanWrapper> planWrapperList){
		
		JsonResult result = new JsonResult();
        Savepoint sp = Database.setSavepoint();
        
        try{
        	
        	//List<PlanWrapper> planWrapperList = (List<PlanWrapper>) JSON.deserialize(planWrappersString, List<PlanWrapper>.class);
        
        
		    List<ShipmentService.FulfillmentLineWrapper> fulfillmentLines = new List<ShipmentService.FulfillmentLineWrapper>();
			
			for(PlanWrapper planningWrapper : planWrapperList){
				for(Sales_Order_Line__c soLine : planningWrapper.linesToPlan){
					ShipmentService.FulfillmentLineWrapper fulfillmentLine = new ShipmentService.FulfillmentLineWrapper();
					fulfillmentLine.salesOrderLineId = soLine.Id;
					
					if(String.isBlank(planningWrapper.selectedPlan.Id)){
						fulfillmentLine.estimatedShipmentDate = planningWrapper.selectedPlan.Shipment_Date_Estimated__c;
					}else{
						fulfillmentLine.shipmentId = planningWrapper.selectedPlan.Id;
					}
					
					fulfillmentLines.add(fulfillmentLine);
				}
			}
			
			// Create a plan for the sales order lines.
			ShipmentService.plan(fulfillmentLines);
			
			result.success  = true; //(ExceptionService.hasErrors == true ? false : true);
	        
	        if(result.success){
	        	result.addMessage(Label.Changes_saved, ApexPages.Severity.CONFIRM);
	        }else{
	        	result.messages.addAll(ExceptionService.messages);
	        }
	        
        }catch ( DML.InsuffientAccessException e ) { 
 			Database.rollback(sp);
            result.success = false;
 			result.addMessage(Label.Insufficient_access_contact_administrator_for_permissions, ApexPages.Severity.ERROR); 
 			
 		}catch (Exception e) {
        	Database.rollback(sp);
            result.success = false;
            string errorMsg = e.getMessage();
            
            if(errorMsg.contains('FIELD_CUSTOM_VALIDATION_EXCEPTION')) {
                List<String> tempErr = errorMsg.split('FIELD_CUSTOM_VALIDATION_EXCEPTION,');
                errorMsg = tempErr[1].split(':')[0];
            }
            
            result.addMessage(errorMsg, ApexPages.Severity.ERROR);
        }

        return result;
	}
}