src-ken&y/objects/Facility__c.object
<CustomObject>
    <customHelpPage>HelpFacilites</customHelpPage>
    <description>Warehouse or building</description>
    <label>Facility</label>
    <nameField>
        <label>Facility</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Item__c.object
<CustomObject>
    <customHelpPage>HelpItems</customHelpPage>
    <description>Item Master object</description>
    <label>Item</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Location__c.object
<CustomObject>
    <customHelpPage>HelpLocations</customHelpPage>
    <description>Organizational Unit or physical location primarily used if  subclassification reporting is desired</description>
    <fields>
        <fullName>Facility__c</fullName>
        <description>Lookup to facility</description>
        <label>Facility</label>
        <referenceTo>Facility__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Nettable__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If checked the items in this location are nettable.</description>
        <label>Nettable</label>
        <type>Checkbox</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/SKID__c.object
<CustomObject>
    <customHelpPage>HelpSKIDAbout</customHelpPage>
    <description>Stock Keeping ID</description>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>SKIDs</relationshipLabel>
        <relationshipName>SKIDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to location</description>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>SKIDs</relationshipLabel>
        <relationshipName>SKIDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Quantity of the item in this SKID</description>
        <label>Quantity (Packaging UOM)</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>SKID Type delineates where the SKID is at in its life cycle</description>
        <inlineHelpText>SKID type reveals the state of the SKID in its lifecycle.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Forecast Demand</fullName>
                </value>
                <value>
                    <fullName>SO Demand</fullName>
                </value>
                <value>
                    <fullName>WOM Demand</fullName>
                </value>
                <value>
                    <fullName>WO Supply</fullName>
                </value>
                <value>
                    <fullName>PO Supply</fullName>
                </value>
                <value>
                    <fullName>History</fullName>
                </value>
                <value>
                    <fullName>Location</fullName>
                    <default>true</default>
                </value>
                <value>
               		<fullName>Planned Pick</fullName>
                 </value>
                 <value>
                     <fullName>Draft In-Transit</fullName>
                 </value>
                 <value>
                     <fullName>TO Supply</fullName>
                 </value>
                 <value>
                     <fullName>In-Transit</fullName>
                 </value>
                 <value>
                     <fullName>Allocated</fullName>
                 </value>
                 <value>
                     <fullName>TO Demand</fullName>
                 </value>
                 <value>
                     <fullName>WIP</fullName>
                 </value>
                 <value>
                     <fullName>Install Base</fullName>
                 </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SKID</label>
    <nameField>
        <label>SKID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SKIDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/Nettable.cls
public with sharing class Nettable {
    /** 
     * @description given a list of items, produce net/non net counts in a map
     */ 
    public static Map < Id, Nettable.NETcount > getNettable( List<Item__c> items) {
        
        set<id> idset = new set<id>();
        for ( Item__c it : items ) {            idset.add(it.id);       }

        Map < Id, NETcount > theMap = new Map<Id,NETcount>(); 
    
       

        /*
        //KNDY-10473: Adding CRUD/FLS checks with SOQLUtil
        */
        SOQLUtil soql = new SOQLUtil('SKID__c', true); //enforceFLS=true, running in user mode
        soql.addFields(new set<string>{
            'ID','Item__c','Location__r.Nettable__c','Quantity__c','Type__c'
        });
        soql.setWhereClause('Item__c in :idset and Type__c in (\'Location\',\'Allocated\')');
        soql.setOrderByClause('Location__r.Facility__r.Name, Location__r.Name ASC');
        for( SKID__c sk : Database.query(soql.getQuery())){
            
            // group the nettable by Item
            if ( ! theMap.containsKey( sk.Item__c ) ) {
                theMap.put( sk.Item__c, new NETcount() );
            }
            if (sk.Type__c == 'Allocated') {
                theMap.get(sk.Item__c).nettable -= sk.Quantity__c != null ? sk.Quantity__c : 0;
            }
            else {
                if ( sk.Location__r.Nettable__c ) { 
                    theMap.get(sk.Item__c).nettable += sk.Quantity__c != null ? sk.Quantity__c : 0;
                } else {
                    theMap.get(sk.Item__c).nonnettable += sk.Quantity__c != null ? sk.Quantity__c : 0;
                }
            }
        }     
        return theMap;
    }
    
    /** 
     * @description given a list of items and a facility ID, produce net/non net counts in a map
     */ 
    public static Map < Id, Nettable.NETcount > getNettableByFacility( List<Item__c> items, ID facilityID) {
        
        set<id> idset = new set<id>();
        for ( Item__c it : items ) {            idset.add(it.id);       }

        Map < Id, NETcount > theMap = new Map<Id,NETcount>(); 
    
      

        /*
        //KNDY-10473: Adding CRUD/FLS checks with SOQLUtil
        */
        SOQLUtil soql = new SOQLUtil('SKID__c', true); //enforceFLS=true, running in user mode
        soql.addFields(new set<string>{
            'ID','Item__c','Location__r.Nettable__c','Quantity__c','Type__c'
        });
        soql.setWhereClause('Item__c in :idset and Location__r.Facility__c =: facilityID and Type__c in (\'Location\',\'Allocated\')');
        soql.setOrderByClause('Location__r.Facility__r.Name, Location__r.Name ASC');
        for( SKID__c sk : Database.query(soql.getQuery())){
            
            // group the nettable by Item
            if ( ! theMap.containsKey( sk.Item__c ) ) {
                theMap.put( sk.Item__c, new NETcount() );
            }
            if (sk.Type__c == 'Allocated') {
                theMap.get(sk.Item__c).nettable -= sk.Quantity__c != null ? sk.Quantity__c : 0;
            }
            else {
                if ( sk.Location__r.Nettable__c ) { 
                    theMap.get(sk.Item__c).nettable += sk.Quantity__c != null ? sk.Quantity__c : 0;
                } else {
                    theMap.get(sk.Item__c).nonnettable += sk.Quantity__c != null ? sk.Quantity__c : 0;
                }
            }
        }     
        return theMap;
    }

    public with sharing class NETcount {
        public NETcount() { nettable = 0; nonnettable = 0; }
        public Double nettable {get;set;}
        public Double nonnettable {get;set;}  
    }
    
}