src-ken&y/objects/Facility__c.object
<CustomObject>
    <customHelpPage>HelpFacilites</customHelpPage>
    <description>Warehouse or building</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Facilities</relationshipLabel>
        <relationshipName>Facilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Facility</label>
    <nameField>
        <label>Facility</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Item__c.object
<CustomObject>
    <customHelpPage>HelpItems</customHelpPage>
    <description>Item Master object</description>
    <fields>
        <fullName>Buyer_Planner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Identifies principal buyer responsible for purchasing this item or planner responsible for planning orders for the item</description>
        <label>Buyer / Planner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company that controls this item</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purchasing_UOM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Purchasing Unit of Measure.  Table of acceptable UofM applies.</description>
        <inlineHelpText>When items are received into inventory, if the purchasing UOM is not equal to the stocking UOM, then the conversion factor is used to convert purchased quantities to stocking quantities. The conversion factor information is stored on the UOM page.</inlineHelpText>
        <label>Purchasing UOM</label>
        <referenceTo>UOM__c</referenceTo>
        <relationshipLabel>Items (Purchasing UOM)</relationshipLabel>
        <relationshipName>Items_Purchasing_UOM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <inlineHelpText>The source of the item. Click &quot;Help for this Page&quot; for information about the different item sources in Kenandy.</inlineHelpText>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Purchased</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Manufactured</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous</fullName>
                </value>
                <value>
                    <fullName>Phantom</fullName>
                </value>
                <value>
                    <fullName>Expense</fullName>
                </value>
                <value>
                    <fullName>Kit</fullName>
                </value>
                <value>
                    <fullName>Outside Processing</fullName>
                </value>
                <value>
                    <fullName>One Time Charge</fullName>
                </value>
                <value>
                    <fullName>Build To Order</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to supplier</description>
        <label>Supplier</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Item&apos;s Supplier must be of type Purchase From</errorMessage>
            <filterItems>
                <field>Supplier__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Purchase From</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Items (Supplier)</relationshipLabel>
        <relationshipName>Items1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Material_Tracking__c.object
<CustomObject>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Material Trackings</relationshipLabel>
        <relationshipName>Material_Trackings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier</label>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Material Trackings</relationshipLabel>
        <relationshipName>Material_Trackings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Material Tracking</label>
    <nameField>
        <displayFormat>MT-{0000000000}</displayFormat>
        <label>Material Tracking</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Material Trackings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/MRP__c.object
<CustomObject>
    <customHelpPage>HelpMRP</customHelpPage>
    <description>MRP supply/demand/planned information</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>MRPs</relationshipLabel>
        <relationshipName>MRPs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Facility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Facility of this order/supply</description>
        <inlineHelpText>MRP can be run at the company or facility level.  If run at the facility level, MRP only looks at the supply and demand for the selected facility.</inlineHelpText>
        <label>Facility</label>
        <referenceTo>Facility__c</referenceTo>
        <relationshipLabel>MRPs</relationshipLabel>
        <relationshipName>MRPs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Item</description>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>MRPs</relationshipLabel>
        <relationshipName>MRPs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MRP_Run__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to MRP_Run</description>
        <inlineHelpText>Lookup to MRP_Run</inlineHelpText>
        <label>MRP Run</label>
        <referenceTo>MRP_Run__c</referenceTo>
        <relationshipLabel>MRPs</relationshipLabel>
        <relationshipName>MRPs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>MRP</label>
    <nameField>
        <displayFormat>MRP-{0000000000}</displayFormat>
        <label>MRP</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MRPs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/MRP_Run__c.object
<CustomObject>
    <customHelpPage>HelpMRPRun</customHelpPage>
    <description>MRP Runtime Run ID and run time parameters</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Company</description>
        <inlineHelpText>Lookup to Company</inlineHelpText>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>MRP Runs</relationshipLabel>
        <relationshipName>MRP_Runs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Facility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Facility</description>
        <inlineHelpText>Lookup to Facility</inlineHelpText>
        <label>Facility</label>
        <referenceTo>Facility__c</referenceTo>
        <relationshipLabel>MRP Runs</relationshipLabel>
        <relationshipName>MRP_Runs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>MRP Run</label>
    <nameField>
        <displayFormat>MRP_Run - {0000000000}</displayFormat>
        <label>MRP_Run</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MRP Runs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Purchase_Order_Line__c.object
<CustomObject>
    <customHelpPage>HelpPurchaseOrders</customHelpPage>
    <description>Line items on a purchase order document</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Purchase Order Lines</relationshipLabel>
        <relationshipName>Purchase_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Item being purchased</description>
        <label>Item</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <errorMessage>Item is not active, or company does not match</errorMessage>
            <filterItems>
                <field>Item__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.Company__c</field>
                <operation>equals</operation>
                <valueField>Item__c.Company__c</valueField>
            </filterItems>
            <filterItems>
                <field>Item__c.Company__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>PurchaseOrder Lines</relationshipLabel>
        <relationshipName>Purchase_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Refers to the Supplier on the PO Header. Needed for setting the lookup filter for manufacturing cross reference.</description>
        <label>Purchase From Supplier</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Supplier__c.Type__c</field>
                <operation>equals</operation>
                <value>Purchasing</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Purchase Order Lines</relationshipLabel>
        <relationshipName>Purchase_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Purchase Order Line</label>
    <nameField>
        <label>Purchase Order Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Supplier__c.object
<CustomObject>
    <customHelpPage>HelpSuppliers</customHelpPage>
    <description>Supplier object</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Suppliers</relationshipLabel>
        <relationshipName>Suppliers1_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Supplier</label>
    <nameField>
        <label>Supplier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Work_Order__c.object
<CustomObject>
    <customHelpPage>HelpWorkOrder</customHelpPage>
    <description>All work orders including planned orders from MRP as well as unplanned orders.</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company this Work Order belongs to</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Facility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The facility in which the work order will be processed.</description>
        <label>Facility</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Facility__c.Company__c</field>
                <operation>equals</operation>
                <valueField>$Source.Company__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Facility__c</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Workorders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Item</description>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Work Order</label>
    <nameField>
        <label>Work Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/GenerateMRPTest.cls
/**
 * This class contains unit tests for 
 */
@isTest
private class GenerateMRPTest {

     @isTest static void t1() {
        TestData data = new TestData();
        insert new MRP__c( company__c = data.company.id );
        MRP_Run__c mrpRun = new MRP_Run__c();
        mrpRun.Company__c = data.company.id;
        mrpRun.Facility__c = null;
        insert mrpRun;
        MRP__c mrp = new MRP__c();
        mrp.Company__c = data.company.id;
        mrp.Facility__c = null;
        mrp.MRP_Run__c = mrpRun.ID;
        insert mrp;
        
        Test.startTest();
        GenerateMRPEraseTemp obj = new GenerateMRPEraseTemp(mrpRun.ID);
        Id jobid = Database.executeBatch( obj );
        Test.stopTest();
        system.assertEquals(0,[select Id from MRP__c where MRP_Run__c = : mrpRun.id].size() );
    } 
    
    
    


    static testMethod void MRPPlannedPurchaseExtension_test() {
        TestData data = new TestData();
        Test.startTest();
 		System.assertEquals(0, Limits.getQueries(), 'Limits.getQueries()  : '+ Limits.getQueries()); 
        Item__c itm = data.itemList[0];
        itm.Supplier__c = data.supplier.id;
        itm.Source__c = 'Purchased';
        itm.Buyer_Planner__c = UserInfo.getUserId();
        itm.Purchasing_UOM__c = data.uomList[0].Id;
        itm.Stocking_UOM__c = data.uomList[0].Id;
        update itm;
        List<MRP__c> mrpList = new List<MRP__c>(); 
        MRP__c tmp = new MRP__c( Company__c = data.Company.id , Required_Date__c = system.today(), 
            Item__c = data.itemList[0].id, Start_Date__c = system.today(),  Planned__c = true,
            Modified_Quantity__c = 12.0 );
        insert tmp;

        mrpList.add( tmp );
        ApexPages.StandardSetController con = new ApexPages.StandardSetController(mrpList);
        con.setSelected(mrpList);
        MRPPlannedPurchaseExtension ext =new MRPPlannedPurchaseExtension(con);
    
        system.assert( ! ApexPages.hasMessages() ,' oops '+ApexPages.getMessages() ); // clean thru all checks
        PageReference p0 = ext.generate(); 
        system.assert( p0 != null , ' expected not null ');
        Test.stopTest();
    }
    
    static testMethod void MRPPlannedPurchaseExtension_testErrorNoPurchasingUOM() {
        TestData data = new TestData();
        Test.startTest();
        System.assertEquals(0, Limits.getQueries(), 'Limits.getQueries()  : '+ Limits.getQueries()); 
        Item__c itm = data.itemList[0];
        itm.Supplier__c = data.supplier.id;
        itm.Source__c = 'Purchased';
        itm.Buyer_Planner__c = UserInfo.getUserId();
        itm.Purchasing_UOM__c = null;
        update itm;
        
        List<MRP__c> mrpList = new List<MRP__c>(); 
        MRP__c tmp = new MRP__c( Company__c = data.Company.id , Required_Date__c = system.today(), 
            Item__c = data.itemList[0].id, Start_Date__c = system.today(),  Planned__c = true,
            Modified_Quantity__c = 12.0 );
        insert tmp;
        
        mrpList.add( tmp );
        ApexPages.StandardSetController con = new ApexPages.StandardSetController(mrpList);
        con.setSelected(mrpList);
        MRPPlannedPurchaseExtension ext =new MRPPlannedPurchaseExtension(con);
    
        system.assert( ApexPages.hasMessages());
        system.assertEquals(Apexpages.getMessages().size(), 1);
        system.assertEquals(True,Apexpages.getMessages()[0].getdetail().contains(Label.Item_has_no_Purchasing_UOM));
        Test.stopTest();
    }
    // TODO more tests for the error conditions
    
    static testMethod void testMatlTrackingPlannedPurchase(){
        TestData data = new TestData();
        Material_Tracking__c mtlTracking = new Material_Tracking__c ();
        mtlTracking.Item__c = data.itemList[2].Id;
        mtlTracking.Work_Order__c = data.workOrder.Id;
        mtlTracking.Allocation_Required__c = true;
        mtlTracking.Allocate_on_Receipt__c = true;
        insert mtlTracking;
        Test.startTest();
        List<MRP__c> mrpList = new List<MRP__c>(); 
        MRP__c tmp = new MRP__c( Company__c = data.Company.id , Required_Date__c = system.today(), 
            Item__c = data.itemList[2].id, Start_Date__c = system.today(),  Is_Demand__c = true,
            Modified_Quantity__c = 12.0, Material_Tracking__c=mtlTracking.Id );
        
        MRP__c tmp1 = new MRP__c( Company__c = data.Company.id , Required_Date__c = system.today(), 
            Item__c = data.itemList[2].id, Start_Date__c = system.today(),  Planned__c = true,
            Modified_Quantity__c = 12.0 );
        mrpList.add(tmp);
        mrpList.add(tmp1);
        insert mrpList;
        
        mrpList[1].Next_Level_MRP__c = mrpList[0].Id;
        update mrpList;
        
        ApexPages.StandardSetController con = new ApexPages.StandardSetController( new List<MRP__c>{mrpList[1]});
        con.setSelected(mrpList);
        MRPPlannedPurchaseExtension ext =new MRPPlannedPurchaseExtension(con);
        PageReference p0 = ext.generate(); 
        system.assert( p0 != null , ' expected not null ');
        
        SOQLUtil util = new SOQLUtil('Purchase_Order_Line__c');
        util.addFields(new Set<String>{'Id','Name'});
        Id mtlTrackingid = mtlTracking.id;
        util.setWhereClause ('Material_Tracking__c = : mtlTrackingid' );
        List<Purchase_Order_Line__c> polines = Database.query(util.getQuery() );
        system.assert(polines != null && polines.size() > 0 );
        
        Test.stopTest();
    }
    
}