src-ken&y/objects/Fixed_Asset__c.object
<CustomObject>
    <customHelpPage>HelpFixedAssets</customHelpPage>
    <description>Stores the companies fixed assets for tracking and depreciation</description>
    <fields>
        <fullName>Book_Value__c</fullName>
        <description>This is the current value of the asset less the accumulated depreciation.</description>
        <formula>(Acquisition_Cost__c + Total_Adjustments__c) -Total_Depreciated_Value__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The current value of the asset, less the accumulated depreciation. The amount is stated in functional currency.</inlineHelpText>
        <label>Book Value</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date_Last_Depreciated__c</fullName>
        <description>Date asset was last depreciated.</description>
        <label>Date Last Depreciated</label>
        <summarizedField>Fixed_Asset_Depreciation__c.Depreciation_Date__c</summarizedField>
        <summaryForeignKey>Fixed_Asset_Depreciation__c.Fixed_Asset__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Declining_Balance__c</fullName>
        <inlineHelpText>Depends on the &quot;Depreciation Method&quot;. Can be either a percentage or &quot;Straight Line&quot; if MACRS is the depreciation method.</inlineHelpText>
        <label>Declining Balance</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Depreciation_Method__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>200%</fullName>
                </value>
                <value>
                    <fullName>150%</fullName>
                </value>
                <value>
                    <fullName>Straight Line</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Depreciable_Basis__c</fullName>
        <formula>(Acquisition_Cost__c + Total_Adjustments__c) -Residual_Value__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>stated in functional currency</inlineHelpText>
        <label>Depreciable Basis</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Depreciation_Convention__c</fullName>
        <inlineHelpText>Depends on &quot;Depreciation Period&quot;.</inlineHelpText>
        <label>Depreciation Convention</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Depreciation_Period__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Mid Month</fullName>
                </value>
                <value>
                    <fullName>Full Month</fullName>
                </value>
                <value>
                    <fullName>Mid Quarter</fullName>
                </value>
                <value>
                    <fullName>Full Quarter</fullName>
                </value>
                <value>
                    <fullName>Half Year</fullName>
                </value>
                <value>
                    <fullName>Full Year</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Depreciation_Count__c</fullName>
        <description>The total number of times depreciation has been applied to this Fixed Asset.</description>
        <inlineHelpText>The total number of times depreciation has been applied to this Fixed Asset.</inlineHelpText>
        <label>Depreciation Count</label>
        <summaryFilterItems>
            <field>Fixed_Asset_Depreciation__c.Subtransaction_Type__c</field>
            <operation>equals</operation>
            <value>Depreciation</value>
        </summaryFilterItems>
        <summaryForeignKey>Fixed_Asset_Depreciation__c.Fixed_Asset__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Depreciation_Period__c</fullName>
        <description>The time period between depreciation cycles for this asset.</description>
        <inlineHelpText>The time period between depreciation cycles for this asset.</inlineHelpText>
        <label>Depreciation Period</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Depreciation_Method__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Annually</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Estimated_End_of_Life__c</fullName>
        <description>In Service Date plus the number of months specified in Depreciation Life.</description>
        <inlineHelpText>The &quot;In Service Date&quot; plus the number of months specified in &quot;Depreciation Life&quot;.</inlineHelpText>
        <label>Estimated End of Life</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fixed_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link the relevant corporate book tax asset when creating a fixed asset for tax book purposes</description>
        <inlineHelpText>Link the relevant corporate book tax asset when creating a fixed asset for tax book purposes</inlineHelpText>
        <label>Fixed Asset (Corporate Book)</label>
        <referenceTo>Fixed_Asset__c</referenceTo>
        <relationshipLabel>Fixed Assets (Tax Books)</relationshipLabel>
        <relationshipName>Tax_Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>In_Service_Date__c</fullName>
        <description>Date this asset was put in to service.</description>
        <label>In Service Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Residual_Value__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Residual value of the asset at the end of its useful life.</description>
        <inlineHelpText>Residual value of the asset at the end of its service life. The amount is stated in functional currency.</inlineHelpText>
        <label>Residual Value</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Depreciated_Value__c</fullName>
        <description>Total Depreciation from all Fixed Asset Depreciations</description>
        <inlineHelpText>stated in functional currency</inlineHelpText>
        <label>Total Depreciated Value</label>
        <summarizedField>Fixed_Asset_Depreciation__c.Depreciation_Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Fixed_Asset_Depreciation__c.Subtransaction_Type__c</field>
            <operation>equals</operation>
            <value>Depreciation</value>
        </summaryFilterItems>
        <summaryForeignKey>Fixed_Asset_Depreciation__c.Fixed_Asset__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Fixed Asset</label>
    <nameField>
        <label>Fixed Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fixed Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Fixed_Asset_Depreciation__c.object
<CustomObject>
    <customHelpPage>HelpFixedAssets</customHelpPage>
    <description>Records depreciation amounts and dates for fixed assets over time.</description>
    <fields>
        <fullName>Depreciation_Key__c</fullName>
        <description>This key is used to enforce unique depreciation records for accounting records.</description>
        <externalId>true</externalId>
        <label>Depreciation Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Finalized__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag is set to true when the invoice is finalized and no more changes are expected</description>
        <label>Finalized</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Fixed_Asset__c</fullName>
        <description>The fixed asset that this depreciation is applied to.</description>
        <label>Fixed Asset</label>
        <referenceTo>Fixed_Asset__c</referenceTo>
        <relationshipLabel>Fixed Asset History</relationshipLabel>
        <relationshipName>Fixed_Asset_Depreciations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Fixed Asset Depreciation</label>
    <nameField>
        <label>Fixed Asset Depreciation Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fixed Asset Depreciations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/classes/AccountingMACRSDepreciation.cls
public with sharing class AccountingMACRSDepreciation implements FixedAssetService.IDepreciation{
	/* ------------------------ */
	/* Supporting Documentation */
	/* ------------------------ */
	
	/*
		http://www.irs.gov/pub/irs-pdf/p946.pdf
		http://www.irs.gov/publications/p946/ch04.html#en_US_2012_publink1000107574
		http://en.wikipedia.org/wiki/Depreciation
	*/
	
	public List<Fixed_Asset_Depreciation__c> execute(List<sObject> sObjRecs, Date depreciateToDate, boolean commitDepreciation){

		List<Fixed_Asset_Depreciation__c> upsertFixedAssetDepreciations = new List<Fixed_Asset_Depreciation__c>();
		
		List<Fixed_Asset__c> fixedAssets = (List<Fixed_Asset__c>)sObjRecs;
		
		for(Fixed_Asset__c fa : fixedAssets){
			
			//Setup and define initial data values for the depreciation cycles
			//NOTE: We are tracking Declining Balance and Straight Line side by side as SL will overtake DB at some point during the life of the asset
			integer periods = FixedAssetService.returnPeriodCount(fa.in_service_date__c, fa.estimated_end_of_life__c, fa.depreciation_period__c);
			decimal decliningBalancePercent;
			if(fa.declining_balance__c == '200%'){
				decliningBalancePercent = 2.0;
			}else if(fa.declining_balance__c == '150%'){
				decliningBalancePercent = 1.5;
			}else{
				//Assume Double Decline Model
				decliningBalancePercent = 2.0;
			}
			
			//Set Mid convention flag where relevant - will be used and changed on first depreciation cycle
			boolean applyMidConvention = false;
			if(fa.Total_Depreciated_Value__c == 0 && (fa.depreciation_convention__c.contains('Mid') || fa.depreciation_convention__c.contains('Half'))){
				applyMidConvention = true;
			}
			
			double dbDepreciationRate = decliningBalancePercent*(1.0/(decimal)periods);
			//system.debug('DB Depreciation Rate: ' + dbDepreciationRate);
			
			date depreciationDate;
			if(fa.Date_Last_Depreciated__c != null){
				depreciationDate = fa.Date_Last_Depreciated__c;
			}else{
				depreciationDate = fa.In_Service_Date__c;
			}
			integer cycles = 0;
			decimal currentDepreciatedValue = fa.Book_Value__c;//fa.Depreciable_Basis__c;
			decimal dbCurrentDepreciatedValue = fa.Book_Value__c;//fa.Depreciable_Basis__c;
			decimal slCurrentDepreciatedValue = fa.Book_Value__c;//fa.Depreciable_Basis__c;
			boolean slOvertaken = false;
			decimal slDepreciationAmount = 0;
			
			//Run depreciation cycles until the depreciation has been brought up to date
			while(depreciationDate < depreciateToDate && 0 <= currentDepreciatedValue){
				
				decimal dbDepreciationAmount = dbDepreciationRate*currentDepreciatedValue;
				dbDepreciationAmount = dbDepreciationAmount.setScale(2, System.Roundingmode.HALF_UP);
				
				//decimal remainingPeriods = periods - fa.depreciation_count__c - cycles;
				decimal remainingPeriods = FixedAssetService.returnPeriodCount(depreciationDate, fa.Estimated_End_of_Life__c, fa.Depreciation_Period__c);
				//Prevent divide by zero error
				if(remainingPeriods <= 0 || remainingPeriods == null){
					remainingPeriods = 1;
				}
				system.debug('remainingPeriods: ' + remainingPeriods);
				
				decimal tmpSLDepreciationAmount = (1.0/remainingPeriods)*(currentDepreciatedValue - fa.Residual_Value__c);
				tmpSLDepreciationAmount = tmpSLDepreciationAmount.setScale(2, System.Roundingmode.HALF_UP);
				
				if(tmpSLDepreciationAmount >= dbDepreciationAmount && !slOvertaken){
					slDepreciationAmount = tmpSLDepreciationAmount;
					slOvertaken = true;
				}
				
				system.debug('DB Amount: ' + dbDepreciationAmount);
				system.debug('SL Amount: ' + tmpSLDepreciationAmount);
				
				//Determine which of the two depreciation values is greater, and use that for this cycle
				decimal depreciationAmount;
				if(slOvertaken){
					depreciationAmount = slDepreciationAmount;
				}else{
					depreciationAmount = dbDepreciationAmount;
				}
				
				if(depreciationAmount > (currentDepreciatedValue - fa.residual_value__c)){
					depreciationAmount = (currentDepreciatedValue - fa.residual_value__c);
				}
				
				if(applyMidConvention){
					depreciationAmount = depreciationAmount/2.0;
					applyMidConvention = false;
				}
				
				currentDepreciatedValue = currentDepreciatedValue - depreciationAmount;
				system.debug('currentDepreciatedValue: ' + currentDepreciatedValue);
				//Generate depreciation iff the residual value will not be exceeded
				if(0 <= currentDepreciatedValue && depreciationAmount > 0){
					
					Fixed_Asset_Depreciation__c iFad = FixedAssetService.generateFixedAssetDepreciation(depreciationAmount, depreciationDate, currentDepreciatedValue, fa, FixedAssetService.TYPE_DEPRECIATION);
					upsertFixedAssetDepreciations.add(iFad);
					system.debug('iFad: ' + iFad);
				}
				cycles++;
				
				depreciationDate = FixedAssetService.incrementPeriod(depreciationDate, fa.depreciation_period__c);
			}
		}
		
		//Run DML if records have accumulated
		if(upsertFixedAssetDepreciations.size() > 0 && commitDepreciation){
			system.debug('upsertFixedAssetDepreciations: ' + upsertFixedAssetDepreciations.size() + ' - ' + upsertFixedAssetDepreciations);
			DML.upsertAsSystem(); List<Database.Upsertresult> upsertFixedAssetDepreciationsResults = Database.upsert(upsertFixedAssetDepreciations, Fixed_Asset_Depreciation__c.depreciation_key__c, false);
			system.debug('upsertFixedAssetDepreciations: ' + upsertFixedAssetDepreciationsResults);
			//DatabaseService.getInstance().processUpsertResults(upsertFixedAssetDepreciationsResults, upsertFixedAssetDepreciations, 'MACRS Fixed Asset Depreciation');
			DML.upsertAsSystem();
			upsert upsertFixedAssetDepreciations depreciation_key__c;
			
			List<Fixed_Asset_Depreciation__c> fadList = new List<Fixed_Asset_Depreciation__c>();
			for(Fixed_Asset_Depreciation__c fad : upsertFixedAssetDepreciations){
				fadList.add(new Fixed_Asset_Depreciation__c(id=fad.id,finalized__c = true));// as per KNDY-11088
				//fad.finalized__c = true;
			}
			DML.updateAsSystem(fadList);
			//DML.updateAsSystem(upsertFixedAssetDepreciations);
		}
		
		return upsertFixedAssetDepreciations;
		
	}
}