src-ken&y/objects/GL_Account__c.object
<CustomObject>
    <customHelpPage>HelpGLAccount</customHelpPage>
    <description>Table of acceptable General Ledger Numbers or Names with associated Cross Reference Information</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Select box if GL account is active</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FX_Type__c</fullName>
        <label>FX Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Monetary Cash</fullName>
                </value>
                <value>
                    <fullName>Monetary Non-cash</fullName>
                </value>
                <value>
                    <fullName>Non-monetary</fullName>
                </value>
                <value>
                    <fullName>P/L Monetary</fullName>
                </value>
                <value>
                    <fullName>P/L Non-monetary</fullName>
                </value>
                <value>
                    <fullName>Historical</fullName>
                </value>
                <value>
                    <fullName>Statistical</fullName>
                </value>
                <value>
                    <fullName>RFX</fullName>
                </value>
                <value>
                    <fullName>UFX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GL_Account_Name__c</fullName>
        <label>GL Account Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GL_Account_Number__c</fullName>
        <label>GL Account Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GL_Type_Code__c</fullName>
        <label>GL Type Code</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Revenue</fullName>
                </value>
                <value>
                    <fullName>Expense</fullName>
                </value>
                <value>
                    <fullName>Asset</fullName>
                </value>
                <value>
                    <fullName>Liability</fullName>
                </value>
                <value>
                    <fullName>Equity</fullName>
                </value>
                <value>
                    <fullName>--None--</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GL Account</label>
    <nameField>
        <label>GL Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Hierarchy__c.object
<CustomObject>
    <customHelpPage>HelpHierarchy</customHelpPage>
    <description>Customer and Product reporting hierarchies</description>
    <fields>
        <fullName>Code__c</fullName>
        <description>external id used for data loads and integration</description>
        <label>Code</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_DateTime__c</fullName>
        <label>Start DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type indicates which hierarchy this record supports</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sales Organization</fullName>
                </value>
                <value>
                    <fullName>National Account</fullName>
                </value>
                <value>
                    <fullName>Financial Hierarchy</fullName>
                </value>
                <value>
                    <fullName>Product Hierarchy</fullName>
                </value>
                <value>
                    <fullName>Segment Hierarchy</fullName>
                </value>
                <value>
                	<fullName>Customer Hierarchy</fullName>
            	</value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Hierarchy</label>
    <nameField>
        <label>Hierarchy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hierarchies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/SegmentHierarchyViewManageTest.cls
@istest
public class SegmentHierarchyViewManageTest {
    
    //Move to @testdatasetup
    @testSetup static Void  SegHierDataSetup(){
        TestFuel fuel = new TestFuel();
		list<hierarchy__c> hierarchylist = new list<hierarchy__c>();        
		list<sObject> sObjects = new list<sObject>();        

            System.Assert(fuel.customsegList.size()>0,'Expecting custom setting to be created.');
            System.AssertNotEquals(fuel.company,null,'Expecting company to be created.');   
            System.AssertNotEquals(fuel.GLTypeTestData,null,'Expecting GL type to be created.');   
            System.AssertNotEquals(fuel.GLAccountTestData,null,'Expecting GL accounts to be created.');
			System.AssertNotEquals(fuel.periodList,null,'Expecting Period to be created.');
            hierarchy__c hrec1 = new hierarchy__c(Name = 'Test Hierarchy 1', Code__c = fuel.GLAccountTestData[0].id, Start_DateTime__c = system.now(), type__c = 'GL Account');
            hierarchylist.add(hrec1);
            sObjects.add(fuel.GLAccountTestData[0]);  
            hierarchy__c hrec2 = new hierarchy__c(Name = 'Test Hierarchy 1', Code__c = fuel.GLAccountTestData[1].id, Start_DateTime__c = system.now(), type__c = 'GL Account');
            hierarchylist.add(hrec2);  
            sObjects.add(fuel.GLAccountTestData[1]);  
            hierarchy__c hrec3 = new hierarchy__c(Name = 'Test Hierarchy 1', Code__c = fuel.GLAccountTestData[2].id, Start_DateTime__c = system.now(), type__c = 'GL Account');
            hierarchylist.add(hrec3);  
            sObjects.add(fuel.GLAccountTestData[2]);  
            hierarchy__c hrec4 = new hierarchy__c(Name = 'Test Hierarchy 1', Code__c = fuel.GLAccountTestData[3].id, Start_DateTime__c = system.now(), type__c = 'GL Account');
            hierarchylist.add(hrec4);  
            hierarchy__c hrec5 = new hierarchy__c(Name = 'Test Hierarchy 1', Code__c = fuel.GLAccountTestData[4].id, Start_DateTime__c = system.now(), type__c = 'GL Account');
            hierarchylist.add(hrec5);  
            hierarchy__c hrec6 = new hierarchy__c(Name = 'Test Hierarchy 1', Code__c = fuel.GLAccountTestData[5].id, Start_DateTime__c = system.now(), type__c = 'GL Account');
            hierarchylist.add(hrec6);  
            sObjects.add(fuel.GLAccountTestData[3]);  
            insert hierarchylist;
            //segIds.addAll(new list<Id>{fuel.GLAccountTestData[4].id,fuel.GLAccountTestData[5].id,fuel.GLAccountTestData[6].id,fuel.GLAccountTestData[7].id});
    }

    public static testmethod void testSegmentHierarchyViewManagePage(){
         Test.startTest();
         list<hierarchy__c> hierarchys =[Select Name,Code__c, Start_DateTime__c, type__c From hierarchy__c where Name= 'Test Hierarchy 1'];
		 list<Id> segIds = new list<Id>();
		 list<GL_Account__c> glAccountList = [Select Name,Id,GL_Account_Number__c,GL_Account_Name__c,GL_Type_Code__c,Active__c,FX_Type__c  From GL_Account__c];       
         segIds.addAll(new list<Id>{glAccountList[4].id,glAccountList[5].id,glAccountList[6].id,glAccountList[7].id});
         list<hierarchy__c> hierarchylist = new list<hierarchy__c>{hierarchys[0],hierarchys[1],hierarchys[2],hierarchys[3]};
         list<hierarchy__c> hierarchylistupdated = new list<hierarchy__c>{hierarchys[4],hierarchys[5]};
		 string asOfDateJSON = JSON.serialize(system.now().adddays(2));
		 string asOfDateNewJSON = JSON.serialize(system.now().adddays(4));
		 string SegRecsToBeInsertedJSON = JSON.serialize(segIds);
		 string SegRecsJSON = JSON.serialize(glAccountList);
		 string HierRecSer = JSON.serialize(hierarchylist[0]);
		 string HierRecDestinationSer = JSON.serialize(hierarchylist[1]);
		 string HirecsToBeInsertedJSON = JSON.serialize(hierarchylistupdated);
		 string HirecsToBeUpdatedJSON = JSON.serialize(hierarchylist);
		 SegmentHierarchyViewManageExt.checkHierarchyNameAvailability('Test Hierarchy 1','GL Account');
		 SegmentHierarchyViewManageExt.FetchHierarchy('Test Hierarchy 1','GL Account', asOfDateJSON,null);
		 SegmentHierarchyViewManageExt.FetchHierarchy('Test Hierarchy 1','GL Account', asOfDateJSON,asOfDateNewJSON);
		 SegmentHierarchyViewManageExt.FetchHierarchyList('GL Account');
		 SegmentHierarchyViewManageExt.getHierarchyTypeList();
		 SegmentHierarchyViewManageExt.addSegmentToTreelist(SegRecsToBeInsertedJSON,'Test Hierarchy 1',asOfDateJSON,'GL Account');
		 SegmentHierarchyViewManageExt.getFieldInfoList('GL_Account__c',null,null,'');
		 SegmentHierarchyViewManageExt.getSegmentValueList('GL Account');
		 SegmentHierarchyViewManageExt.FetchSegmentList(SegRecsJSON,'GL_Account__c');
		 SegmentHierarchyViewManageExt.treeListRead(asOfDateJSON,null,'','','',SegRecsJSON,'','GL Account','Test Hierarchy 1');
		 SegmentHierarchyViewManageExt.CheckHierarchyExists('Test Hierarchy 1','GL Account',asOfDateJSON);
		 SegmentHierarchyViewManageExt.EventDeleteRow(asOfDateJSON,HierRecSer,hierarchylist[0].id,'GL Account','Test Hierarchy 1',SegRecsJSON,segIds);
		 SegmentHierarchyViewManageExt.EventDragAndDrop(asOfDateJSON,HierRecSer,hierarchylist[0].id,HierRecDestinationSer,hierarchylist[1].id,'GL Account','Test Hierarchy 1');
		 SegmentHierarchyViewManageExt.SaveResult(HirecsToBeInsertedJSON,HirecsToBeUpdatedJSON);
		 SegmentHierarchyViewManageExt.DeleteHierarchy('Test Hierarchy 1','GL Account',asOfDateJSON);
		 Test.stopTest();
    }

}