src-ken&y/objects/Hierarchy__c.object
<CustomObject>
    <customHelpPage>HelpHierarchy</customHelpPage>
    <description>Customer and Product reporting hierarchies</description>
    <fields>
        <fullName>Current_Bool__c</fullName>
        <description>Records are current if the start date &lt;= today and end &gt;= today, or no end date</description>
        <formula>AND( Start_Date__c &lt;=  TODAY(),OR( End_Date__c &gt;= TODAY(),  ISBLANK(End_Date__c)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Records are current if the start date &lt;= today and end &gt;= today, or no end date</inlineHelpText>
        <label>Current</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type indicates which hierarchy this record supports</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sales Organization</fullName>
                </value>
                <value>
                    <fullName>National Account</fullName>
                </value>
                <value>
                    <fullName>Financial Hierarchy</fullName>
                </value>
                <value>
                    <fullName>Product Hierarchy</fullName>
                </value>
                <value>
                    <fullName>Segment Hierarchy</fullName>
                </value>
                <value>
                	<fullName>Customer Hierarchy</fullName>
            	</value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Hierarchy</label>
    <nameField>
        <label>Hierarchy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hierarchies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Process_Job__c.object
<CustomObject>
    <customHelpPage>HelpProcessJobs</customHelpPage>
    <description>Establish and manage scheduled jobs to run at various hours or frequencies</description>
    <label>Process Job</label>
    <nameField>
        <label>Process Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/HierarchyPathBatch.cls
public with sharing class HierarchyPathBatch implements Database.Batchable<sObject>, Process.Runnable2, Database.Stateful {
    
    public List<Notify.Message> messages = new List<Notify.Message>();
    
    public void runBatch(Process_Job__c job) { 
        Database.executeBatch(new HierarchyPathBatch(),2000); 
    }
    
    public List<Hierarchy__c> start(Database.BatchableContext BC) { 
        //String query = 'select id,Type__c from Hierarchy__c WHERE Type__c != null AND Current_bool__c = true order by Type__c ';
        //return Database.query(query);
        
        String whereClause = 'Type__c != null AND Current_bool__c = true order by Type__c';//KNDY-8796
        SOQLUtil soql = new SOQLUtil('Hierarchy__c',true);
        soql.addFields(new Set<String>{'Id','Type__c'});
        soql.setWhereClause(whereClause);
        return Database.query(soql.getQuery());
    }
    
    public void execute(Database.BatchableContext info,List<Hierarchy__c> scope) {
        
        // deal with types one at a time, make a map and collect lists by the type
        map<string,list<Hierarchy__c>> hMap = new map<string,list<Hierarchy__c>>();        
        for ( Hierarchy__c h : scope) {
            if ( ! hMap.containsKey( h.type__c) ) 
                hMap.put(h.type__c,new List<Hierarchy__c>());
            hMap.get(h.Type__c).add(h);
        }
        
        // iterate over each type
        for ( string typ : hMap.keySet() ) { 
            scope = hMap.get(typ);  // focus on the list of a single type
            
            HierarchyController hcon = new HierarchyController( new Apexpages.standardController( scope[0] ));
            hcon.setHierarchyPath();
            
            // we need to update only those records which are in scope so we dont blow past the 10,000 dml limit
            // build the short list to update
            list<Hierarchy__c> toUpdate = new list<Hierarchy__c>();
            for ( Hierarchy__c hh : scope ) { 
                if ( hcon.allRecords.containsKey(hh.Id) )
                    toUpdate.add(hcon.allRecords.get(hh.Id));
                else {
                    //messages.add( new Notify.Message('Hierarchy record missing ', String.valueof(hh) ));
                    system.debug(LoggingLevel.INFO, 'missing from allRecords '+hh);
                }
            }
            DML.updateAsUser(toUpdate); // less than or equal 2000 rows
        }
    }
    
    public void finish(Database.BatchableContext info) { 
        MasterControlProgram.finishedBatch(this); 
        Notify.sendEmailBatchFinish( null, messages, info);
    }
    
}