src-ken&y/objects/Hierarchy__c.object
<CustomObject>
    <customHelpPage>HelpHierarchy</customHelpPage>
    <description>Customer and Product reporting hierarchies</description>
    <fields>
        <fullName>Pricebook__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Pricebook field will be used as part of customer hierarchy. When a pricebook is associated with a customer hierarchy, the corresponding price book will be used to determine the price of a product for a customer under the hierarchy.</description>
        <label>Pricebook</label>
        <referenceTo>Pricebook__c</referenceTo>
        <relationshipLabel>Hierarchies</relationshipLabel>
        <relationshipName>Hierarchies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Hierarchy</label>
    <nameField>
        <label>Hierarchy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hierarchies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Pricebook__c.object
<CustomObject>
    <customHelpPage>HelpPricebooks</customHelpPage>
    <description>List prices for a company and the products it sells</description>
    <label>Pricebook</label>
    <nameField>
        <label>Pricebook Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricebooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Pricebook_Line__c.object
<CustomObject>
    <customHelpPage>HelpPricebooks</customHelpPage>
    <description>Record individual prices for a Product at an effective time</description>
    <fields>
        <fullName>Price__c</fullName>
        <description>The Product price in this pricebook</description>
        <inlineHelpText>If fixed pricing is not selected, the price is based on the bracket/weight-based price for the product. To manage price brackets go to the Company page.</inlineHelpText>
        <label>Price</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pricebook__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Pricebook</label>
        <referenceTo>Pricebook__c</referenceTo>
        <relationshipLabel>Pricebook Lines</relationshipLabel>
        <relationshipName>Pricebook_Lines</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product group to which this pricebook line belongs</description>
        <label>Product Group</label>
        <referenceTo>Product_Group__c</referenceTo>
        <relationshipLabel>Pricebook Lines</relationshipLabel>
        <relationshipName>Pricebook_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>When does this price become effective</description>
        <inlineHelpText>Start date for this price</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Pricebook Line</label>
    <nameField>
        <displayFormat>PB-{0000000000}</displayFormat>
        <label>Pricebook Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricebook Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Product_Group__c.object
<CustomObject>
    <customHelpPage>HelpProductGroup</customHelpPage>
    <fields>
        <fullName>Hierarchy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product Hierarchy link to this Product Group</description>
        <inlineHelpText>The hierarchy to which the group belongs.</inlineHelpText>
        <label>Hierarchy</label>
        <referenceTo>Hierarchy__c</referenceTo>
        <relationshipLabel>Product Groups</relationshipLabel>
        <relationshipName>Product_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Group</label>
    <nameField>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/PricebookLineUpdateExtTest2.cls
/**
 * TestFuel based version for running tests at better speed
 */
@isTest
public class PricebookLineUpdateExtTest2 {
    testMethod static void testPricebookRelatedListExt() {
        TestFuel fuel = new TestFuel();
        PricebookRelatedListExt ext = new PricebookRelatedListExt(new ApexPages.StandardController(fuel.pricebook));
        System.assertEquals(fuel.pricebook, ext.config.parentRecord);
    }
    
    testMethod static void testRelatedFilters() {
        TestFuel fuel = new TestFuel();
        Pricebook__c pb = fuel.pricebook;
		Hierarchy__c hierarchy1 = fuel.hierarchy1;
		
        Pricebook_Line__c pl3 =new Pricebook_Line__c();
        pl3.product_group__c = fuel.productGroup.id;
        pl3.pricebook__c = fuel.pricebook.id;
        pl3.price__c = 12.11;
        pl3.start_date__c = system.today();
		insert pl3;
        
        
        KendoExt.LoadRecordsRelatedFilterInfo filterInfo = new KendoExt.LoadRecordsRelatedFilterInfo();
        filterInfo.relatedFilterValues = new Map<String, Object>{
                                                                'companyId' => fuel.company.id, 
                                                                'productId' => fuel.product.id
                                                                };
        
        PricebookLineUpdateExt.PricebookRelatedFilterLimiter pbLimiter = new PricebookLineUpdateExt.PricebookRelatedFilterLimiter();
        pbLimiter.setLoadRecordsRelatedFilterInfo(filterInfo);
        System.assertEquals(true, pbLimiter.hasRelevantIds());
        System.assert(pbLimiter.getRelevantIds().contains(pb.id));
        
        
        PricebookLineUpdateExt.ProductGroupRelatedFilterLimiter pgLimiter = new PricebookLineUpdateExt.ProductGroupRelatedFilterLimiter();
        pgLimiter.setLoadRecordsRelatedFilterInfo(filterInfo);
        System.assertEquals(true, pgLimiter.hasRelevantIds());
        System.assertEquals(0, pgLimiter.getRelevantIds().size());
        
        filterInfo.relatedFilterValues = new Map<String, Object>{
                                                                'companyId' => fuel.company.id, 
                                                                'productGroupId' => fuel.productGroup.id
                                                                };
        
        pgLimiter = new PricebookLineUpdateExt.ProductGroupRelatedFilterLimiter();
        pgLimiter.setLoadRecordsRelatedFilterInfo(filterInfo);
        System.assertEquals(false, pgLimiter.hasRelevantIds());
        System.assertEquals(1, pgLimiter.getRelevantIds().size());
        //System.debug(LoggingLevel.INFO, '*** pgLimiter: ' + pgLimiter);

        filterInfo.relatedFilterValues = new Map<String, Object>{
                                                                'companyId' => fuel.company.id, 
                                                                'pricebookId' => pb.id
                                                                };
        
        
        PricebookLineUpdateExt.ProductRelatedFilterLimiter pLimiter = new PricebookLineUpdateExt.ProductRelatedFilterLimiter();
        pLimiter.setLoadRecordsRelatedFilterInfo(filterInfo);
        System.assertEquals(true, pLimiter.hasRelevantIds());
        System.assertEquals(3, pLimiter.getRelevantIds().size());
        

        filterInfo.relatedFilterValues = new Map<String, Object>{
                                                                'companyId' => fuel.company.id, 
                                                                'productGroupId' => fuel.productGroup.id
                                                                };
        PricebookLineUpdateExt.HierarchyRelatedFilterLimiter hLimiter = new PricebookLineUpdateExt.HierarchyRelatedFilterLimiter();
        hLimiter.setLoadRecordsRelatedFilterInfo(filterInfo);
        System.assertEquals(true, hLimiter.hasRelevantIds());
        System.assertEquals(1, hLimiter.getRelevantIds().size());
        
    }
}