src-ken&y/objects/Inventory_Transaction__c.object
<CustomObject>
    <customHelpPage>HelpInventoryTransaction</customHelpPage>
    <description>This object records the movements of items caused by WIP and inventory transactions</description>
    <fields>
        <fullName>Purchase_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Purchase Order Line</description>
        <label>Purchase Order Line</label>
        <referenceTo>Purchase_Order_Line__c</referenceTo>
        <relationshipLabel>Inventory Transactions</relationshipLabel>
        <relationshipName>Inventory_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>Transaction quantity</description>
        <label>Quantity (Packaging UOM)</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>The reason this transaction occured</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Activate Proposed Costs</fullName>
                </value>
                <value>
                    <fullName>Transfer</fullName>
                </value>
                <value>
                    <fullName>Sales Order Allocation</fullName>
                </value>
                <value>
                    <fullName>Sales Order Pick</fullName>
                </value>
                <value>
                    <fullName>Transfer Order Allocation</fullName>
                </value>
                <value>
                    <fullName>Transfer Order Pick</fullName>
                </value>
                <value>
                    <fullName>Adjustment Decrease</fullName>
                </value>
                <value>
                    <fullName>Adjustment Increase</fullName>
                </value>
                <value>
                    <fullName>Cycle Count</fullName>
                </value>
                <value>
                    <fullName>Purchase Order Receipt</fullName>
                </value>
                <value>
                    <fullName>Transfer Order Receipt</fullName>
                </value>
                <value>
                    <fullName>QA Sample</fullName>
                </value>
                <value>
                    <fullName>Sales Order Undo Shipment</fullName>
                </value>
                <value>
                    <fullName>Work Order Assembly Completion</fullName>
                </value>
                <value>
                    <fullName>Work Order Assembly Scrap</fullName>
                </value>
                <value>
                    <fullName>Work Order Component Return</fullName>
                </value>
                <value>
                    <fullName>Work Order Component Scrap</fullName>
                </value>
                <value>
                    <fullName>Work Order Return To WIP</fullName>
                </value>
                <value>
                    <fullName>Work Order Issue From WIP</fullName>
                </value>
                <value>
                    <fullName>By-product</fullName>
                </value>
                <value>
                    <fullName>Work Order Component Issue</fullName>
                </value>
                <value>
                    <fullName>Sales Order Shipment</fullName>
                </value>
                <value>
                    <fullName>Transfer Order Shipment</fullName>
                </value>
                <value>
                    <fullName>Work Order Assembly Uncompletion</fullName>
                </value>
                <value>
                    <fullName>By-product Uncompletion</fullName>
                </value>
                <value>
                    <fullName>Void - Transfer Order Receipt</fullName>
                </value>
                <value>
                    <fullName>Void - Purchase Order Receipt</fullName>
                </value>
                <value>
                    <fullName>Transfer Order Undo Shipment</fullName>
                </value>
                <value>
                    <fullName>Transfer Order Unallocation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Inventory Transaction</label>
    <nameField>
        <label>Inventory Transaction</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Purchase_Order__c.object
<CustomObject>
    <customHelpPage>HelpPurchaseOrders</customHelpPage>
    <description>Purchase header information</description>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>The PO type. &quot;Standard&quot; -&gt; lists goods or services you require. &quot;Production&quot; -&gt; establishes a contract with a co-manufacturer to produce goods. &quot;Shipment&quot; -&gt; lists goods ready to be picked up.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Production</fullName>
                </value>
                <value>
                    <fullName>Standard</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Shipment</fullName>
                </value>
                <value>
                    <fullName>Drop Ship</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Purchase Order</label>
    <nameField>
        <label>Purchase Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Purchase_Order_Line__c.object
<CustomObject>
    <customHelpPage>HelpPurchaseOrders</customHelpPage>
    <description>Line items on a purchase order document</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Goods</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Expense</fullName>
                </value>
                <value>
                    <fullName>Asset</fullName>
                </value>
                <value>
                    <fullName>Drop Ship</fullName>
                </value>
                <value>
                    <fullName>Back To Back</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Purchase Order Line</label>
    <nameField>
        <label>Purchase Order Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Serial__c.object
<CustomObject>
    <customHelpPage>HelpSerials</customHelpPage>
    <fields>
        <fullName>SKID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The current skid this serial exists.</description>
        <inlineHelpText>The current skid this serial exists.</inlineHelpText>
        <label>SKID</label>
        <referenceTo>SKID__c</referenceTo>
        <relationshipLabel>Serials</relationshipLabel>
        <relationshipName>Serials</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Serial</label>
    <nameField>
        <label>Serial Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Serials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Serial_Transaction__c.object
<CustomObject>
    <customHelpPage>HelpSerials</customHelpPage>
    <fields>
        <fullName>Inventory_Transaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory Transaction</label>
        <referenceTo>Inventory_Transaction__c</referenceTo>
        <relationshipLabel>Serial Transactions</relationshipLabel>
        <relationshipName>Serial_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Receipt</fullName>
                </value>
                <value>
                    <fullName>Issue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Serial Transaction</label>
    <nameField>
        <label>Serial Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Serial Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/SKID__c.object
<CustomObject>
    <customHelpPage>HelpSKIDAbout</customHelpPage>
    <description>Stock Keeping ID</description>
    <fields>
        <fullName>Input_Quantity__c</fullName>
        <description>Input field for Quantity on visualforce pages. Scratch Field.</description>
        <inlineHelpText>Quantity to be transferred from one location to the other.</inlineHelpText>
        <label>Transfer Quantity</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to location</description>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>SKIDs</relationshipLabel>
        <relationshipName>SKIDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purchase_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The purchase order line that matched in Receiving</description>
        <label>Purchase Order Line</label>
        <referenceTo>Purchase_Order_Line__c</referenceTo>
        <relationshipLabel>SKIDs</relationshipLabel>
        <relationshipName>SKIDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Quantity of the item in this SKID</description>
        <label>Quantity (Packaging UOM)</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>SKID Type delineates where the SKID is at in its life cycle</description>
        <inlineHelpText>SKID type reveals the state of the SKID in its lifecycle.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Forecast Demand</fullName>
                </value>
                <value>
                    <fullName>SO Demand</fullName>
                </value>
                <value>
                    <fullName>WOM Demand</fullName>
                </value>
                <value>
                    <fullName>WO Supply</fullName>
                </value>
                <value>
                    <fullName>PO Supply</fullName>
                </value>
                <value>
                    <fullName>History</fullName>
                </value>
                <value>
                    <fullName>Location</fullName>
                    <default>true</default>
                </value>
                <value>
               		<fullName>Planned Pick</fullName>
                 </value>
                 <value>
                     <fullName>Draft In-Transit</fullName>
                 </value>
                 <value>
                     <fullName>TO Supply</fullName>
                 </value>
                 <value>
                     <fullName>In-Transit</fullName>
                 </value>
                 <value>
                     <fullName>Allocated</fullName>
                 </value>
                 <value>
                     <fullName>TO Demand</fullName>
                 </value>
                 <value>
                     <fullName>WIP</fullName>
                 </value>
                 <value>
                     <fullName>Install Base</fullName>
                 </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SKID</label>
    <nameField>
        <label>SKID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SKIDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/PurchaseOrderAPITest.cls
@isTest
private class PurchaseOrderAPITest {
    @testSetup
    private static void setupData() {
        TestFuel f = new TestFuel();
        System.assert(f.smrsList != null);
        System.assert(f.stockMovementRuleList != null);
        System.assert(f.purchaseOrder != null);
        insert new Configuration__c(Name = 'STACKTRACE');
    }

    public static TestFuelQuery fuel = new TestFuelQuery();

    private static testMethod void receiveNoAttributes() {
        delete [SELECT Id FROM Item_Attribute__c];

        Purchase_Order_Line__c pol = fuel.purchaseOrderLines[0];
        Location__c loc = fuel.location3;

        SKID__c skid = new SKID__c(
            Location__c = loc.Id,
            Input_Quantity__c = 1
        );

        Map<Id, List<Map<String, Object>>> lines = new Map<Id, List<Map<String, Object>>>();
        lines.put(pol.Id, new List<Map<String, Object>>{ new Map<String, Object>{ 'skid' => skid }});

        Test.startTest();
        PurchaseOrderAPI.Receive receive = new PurchaseOrderAPI.Receive();
        Action.Response resp = receive.execute(JSON.serialize(lines));
        System.assert(resp.success == true, resp);
        Test.stopTest();

        Inventory_Transaction__c it = [SELECT Id, Quantity__c FROM Inventory_Transaction__c WHERE Type__c = 'Purchase Order Receipt'];
        System.assert(it.Quantity__c == 1, it.Quantity__c);
    }

    private static testMethod void receiveAttributes() {
        Purchase_Order_Line__c pol = fuel.purchaseOrderLines[0];
        Location__c loc = fuel.location3;

        SKID__c skid = new SKID__c(
            Location__c = loc.Id,
            Lot_Number__c = 'LOTA',
            Expiration_Date__c = Date.today().addDays(10),
            Input_Quantity__c = 1
        );

        Map<Id, List<Map<String, Object>>> lines = new Map<Id, List<Map<String, Object>>>();
        lines.put(pol.Id, new List<Map<String, Object>>{ new Map<String, Object>{ 'skid' => skid }});

        Test.startTest();
        PurchaseOrderAPI.Receive receive = new PurchaseOrderAPI.Receive();
        Action.Response resp = receive.execute(JSON.serialize(lines));
        System.assert(resp.success == true, resp);
        Test.stopTest();

        Inventory_Transaction__c it = [SELECT Id, Quantity__c FROM Inventory_Transaction__c WHERE Type__c = 'Purchase Order Receipt' AND Lot__c != null AND Expiration_Date__c != null];
        System.assert(it.Quantity__c == 1, it.Quantity__c);
    }

    private static testMethod void receiveSerials() {
        update new Item_Attribute__c(Id = fuel.itemAttrObj.Id, Serial_Number__c = true);

        Purchase_Order_Line__c pol = fuel.purchaseOrderLines[0];
        Location__c loc = fuel.location3;

        SKID__c skid = new SKID__c(
            Location__c = loc.Id,
            Lot_Number__c = 'LOTA',
            Expiration_Date__c = Date.today().addDays(10),
            Input_Quantity__c = 1
        );

        List<Serial__c> serials = new List<Serial__c>{ new Serial__c(Name = 'SERIAL1') };

        Map<Id, List<Map<String, Object>>> lines = new Map<Id, List<Map<String, Object>>>{ pol.Id => new List<Map<String, Object>>() };
        Map<String, Object> skidWrapper = new Map<String, Object>();
        skidWrapper.put('skid', skid);
        skidWrapper.put('serials', serials);
        lines.get(pol.Id).add(skidWrapper);

        Test.startTest();
        PurchaseOrderAPI.Receive receive = new PurchaseOrderAPI.Receive();
        Action.Response resp = receive.execute(JSON.serialize(lines));
        System.assert(resp.success == true, resp);
        Test.stopTest();

        Inventory_Transaction__c it = [SELECT Id, Quantity__c FROM Inventory_Transaction__c WHERE Type__c = 'Purchase Order Receipt'];
        System.assert(it.Quantity__c == 1, it.Quantity__c);

        Serial_Transaction__c st = [SELECT Id, Serial__c, Serial__r.Name FROM Serial_Transaction__c WHERE Inventory_Transaction__c = :it.Id];
        System.assert(st.Serial__r.Name == serials[0].Name, st);
    }

    private static testMethod void close() {
        Purchase_Order__c po = fuel.purchaseOrder;
        Map<Id, PurchaseOrderAPI.PurchaseOrderWrapper> poMap = new Map<Id, PurchaseOrderAPI.PurchaseOrderWrapper>();
        poMap.put(po.Id, new PurchaseOrderAPI.PurchaseOrderWrapper(po.Id));
        poMap.put(po.Company__c, new PurchaseOrderAPI.PurchaseOrderWrapper(po.Id));

        Test.startTest();

        Map<Id, PurchaseOrderAPI.PurchaseOrderAPIStatus> statuses = PurchaseOrderAPI.close(poMap);

        Boolean isSuccess;
        for (PurchaseOrderAPI.PurchaseOrderAPIStatus status:statuses.values()) {
            if (isSuccess == null) isSuccess = status.success;
            else System.assert(isSuccess == !status.success, statuses);
        }
        
        Test.stopTest();

        Purchase_Order_Line__c pol = [SELECT Id, Purchase_Order__c, Purchase_Order__r.Status__c FROM Purchase_Order_Line__c WHERE Status__c = 'Closed'];
        System.assert(pol.Purchase_Order__r.Status__c == 'Closed', pol.Purchase_Order__r);
    }

    private static testMethod void deprecated() {
        try {
            PurchaseOrderAPI.receive(null);
            System.assert(false);
        } catch (Exception e) {
            System.assert(true);
        }
        try {
            PurchaseOrderAPI.PurchaseOrderLineWrapper pol = new PurchaseOrderAPI.PurchaseOrderLineWrapper();
            System.assert(false);
        } catch (Exception e) {
            System.assert(true);
        }
        try {
            PurchaseOrderAPI.ReceivingLine rl = new PurchaseOrderAPI.ReceivingLine();
            System.assert(false);
        } catch (Exception e) {
            System.assert(true);
        }
        try {
            PurchaseOrderAPI.PurchaseOrderAPIException ex = new PurchaseOrderAPI.PurchaseOrderAPIException('error');
            System.assert(false);
        } catch (Exception e) {
            System.assert(true);
        }
    }
}