src-ken&y/objects/Item__c.object
<CustomObject>
    <customHelpPage>HelpItems</customHelpPage>
    <description>Item Master object</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company that controls this item</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Container_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Container Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_Attribute__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>lists the attributes to be tracked for this item.</description>
        <inlineHelpText>Additional attributes such as expiration date, lot number, and date received.</inlineHelpText>
        <label>Item Attribute</label>
        <referenceTo>Item_Attribute__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Item_Attribute__c.object
<CustomObject>
    <customHelpPage>HelpItemAttribute</customHelpPage>
    <description>Contains all the attributes that should be tracked for any particular item.</description>
    <fields>
        <fullName>Lot_Number__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Specifies whether lot is tracked for the item.</description>
        <inlineHelpText>A check mark indicates that the selected item is being tracked by lot.If selected, you are prompted to enter the lot number when the item is received.</inlineHelpText>
        <label>Lot Number</label>
        <type>Checkbox</type>
    </fields>
    <label>Item Attribute</label>
    <nameField>
        <label>Item Attribute Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Attributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Material_Tracking__c.object
<CustomObject>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Material Trackings</relationshipLabel>
        <relationshipName>Material_Trackings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Operation_Tracking__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Operation Tracking</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Operation_Tracking__c.Work_Order__c</field>
                <operation>equals</operation>
                <valueField>$Source.Work_Order__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Operation_Tracking__c</referenceTo>
        <relationshipLabel>Material Trackings</relationshipLabel>
        <relationshipName>Material_Trackings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Kit</fullName>
                </value>
                <value>
                    <fullName>Backflush</fullName>
                </value>
                <value>
                    <fullName>By-product</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Work_Order__c</fullName>
        <label>Work Order</label>
        <referenceTo>Work_Order__c</referenceTo>
        <relationshipLabel>Material Trackings</relationshipLabel>
        <relationshipName>Material_Trackings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Material Tracking</label>
    <nameField>
        <displayFormat>MT-{0000000000}</displayFormat>
        <label>Material Tracking</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Material Trackings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Operation_Tracking__c.object
<CustomObject>
    <fields>
        <fullName>Routing__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Routing</label>
        <referenceTo>Routing__c</referenceTo>
        <relationshipLabel>Operation Trackings</relationshipLabel>
        <relationshipName>Operation_Trackings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Order__c</fullName>
        <label>Work Order</label>
        <referenceTo>Work_Order__c</referenceTo>
        <relationshipLabel>Operation Trackings</relationshipLabel>
        <relationshipName>Operation_Trackings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Operation Tracking</label>
    <nameField>
        <label>Operation Tracking</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Operation Trackings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Routing__c.object
<CustomObject>
    <customHelpPage>HelpWorkOrder</customHelpPage>
    <description>Routing Detail object:  contains the detailed operations required to make an Assembly</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company this routing belongs to</description>
        <inlineHelpText>Company this routing belongs to. After a routing has been created, you cannot change the company.</inlineHelpText>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Routings</relationshipLabel>
        <relationshipName>Routings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Routing</label>
    <nameField>
        <label>Routing</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/SKID__c.object
<CustomObject>
    <customHelpPage>HelpSKIDAbout</customHelpPage>
    <description>Stock Keeping ID</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to company</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>SKIDs</relationshipLabel>
        <relationshipName>SKIDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Facility2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Facility</label>
        <referenceTo>Facility__c</referenceTo>
        <relationshipLabel>SKIDs</relationshipLabel>
        <relationshipName>SKIDs2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>SKIDs</relationshipLabel>
        <relationshipName>SKIDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to location</description>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>SKIDs</relationshipLabel>
        <relationshipName>SKIDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lot_Number__c</fullName>
        <description>Lot Number of the item in this SKID</description>
        <label>Lot Number</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Material_Tracking__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Material Tracking</label>
        <referenceTo>Material_Tracking__c</referenceTo>
        <relationshipLabel>SKIDs</relationshipLabel>
        <relationshipName>SKIDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Quantity of the item in this SKID</description>
        <label>Quantity (Packaging UOM)</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>SKID Type delineates where the SKID is at in its life cycle</description>
        <inlineHelpText>SKID type reveals the state of the SKID in its lifecycle.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Forecast Demand</fullName>
                </value>
                <value>
                    <fullName>SO Demand</fullName>
                </value>
                <value>
                    <fullName>WOM Demand</fullName>
                </value>
                <value>
                    <fullName>WO Supply</fullName>
                </value>
                <value>
                    <fullName>PO Supply</fullName>
                </value>
                <value>
                    <fullName>History</fullName>
                </value>
                <value>
                    <fullName>Location</fullName>
                    <default>true</default>
                </value>
                <value>
               		<fullName>Planned Pick</fullName>
                 </value>
                 <value>
                     <fullName>Draft In-Transit</fullName>
                 </value>
                 <value>
                     <fullName>TO Supply</fullName>
                 </value>
                 <value>
                     <fullName>In-Transit</fullName>
                 </value>
                 <value>
                     <fullName>Allocated</fullName>
                 </value>
                 <value>
                     <fullName>TO Demand</fullName>
                 </value>
                 <value>
                     <fullName>WIP</fullName>
                 </value>
                 <value>
                     <fullName>Install Base</fullName>
                 </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Work_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Work order related to the on order SKID</description>
        <label>Work Order</label>
        <referenceTo>Work_Order__c</referenceTo>
        <relationshipLabel>SKIDs</relationshipLabel>
        <relationshipName>SKIDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SKID</label>
    <nameField>
        <label>SKID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SKIDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Work_Order__c.object
<CustomObject>
    <customHelpPage>HelpWorkOrder</customHelpPage>
    <description>All work orders including planned orders from MRP as well as unplanned orders.</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company this Work Order belongs to</description>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Complete_to_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Location</description>
        <label>Complete to Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Location__c.Facility__c</field>
                <operation>equals</operation>
                <valueField>$Source.Facility__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Work Orders (Complete to Location)</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Item</description>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Work Order type</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Regular</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Repair</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Work Order</label>
    <nameField>
        <label>Work Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/WorkOrderClosedExtTest.cls
@isTest
private class WorkOrderClosedExtTest {
    @testSetup
    private static void setupData() {
        TestFuel f = new TestFuel();
        System.assert(f.smrsList != null && f.stockMovementRuleList != null && f.itemSpec != null);

        delete [SELECT Id FROM Routing__c];

        WorkOrderPlanningService.release(new Set<Id>{ f.workOrder.Id });
    }
    
    private static TestFuelQuery fuel = new TestFuelQuery();

    private static testMethod void testWrongStatus() {
        WorkOrderPlanningService.undoRelease(new Set<Id>{ fuel.workOrder.Id });

        WorkOrderClosedExt ext = new WorkOrderClosedExt(new ApexPages.StandardController(fuel.workOrder));
        System.assert(ext.disableCloseButton);
    }

    public static testMethod void testAssemblyWipSkid() {
        insert new SKID__c(
            Company__c = fuel.company.Id,
            Item__c = fuel.workOrder.Item__c,
            Facility2__c = fuel.facility2.Id,
            Location__c = fuel.workOrder.Complete_To_Location__c,
            Quantity__c = 1,
            Type__c = SkidService3.SKID_TYPE_WIP,
            Work_Order__c = fuel.workOrder.Id
        );

        WorkOrderClosedExt ext = new WorkOrderClosedExt(new ApexPages.StandardController(fuel.workOrder));
        System.assert(ApexPages.hasMessages(ApexPages.Severity.FATAL), ApexPages.getMessages());
        System.assert(ext.disableCloseButton);
    }

    public static testMethod void testMaterialWipSkid() {
        Work_Order__c wo = WorkOrderService.getWorkOrders(new Set<Id>{ fuel.workOrder.Id },null,null,new Set<String>{ 'Material_Trackings__r' })[0];
        
        update new Item_Attribute__c(Id = fuel.itemAttrObj.Id, Lot_Number__c = false);
        update new Material_Tracking__c(Id = wo.Material_Trackings__r[0].Id, Type__c = 'Kit', Operation_Tracking__c = null);

        insert new SKID__c(
            Company__c = fuel.company.Id,
            Type__c = SkidService3.SKID_TYPE_LOCATION,
            Item__c = wo.Material_Trackings__r[0].Item__c,
            Container_Item__c = wo.Material_Trackings__r[0].Item__c,
            Quantity__c = 100,
            Quantity_Stocking_UOM__c = 100,
            Stocking_UOM__c = fuel.uomList[8].Id,
            Packaging_UOM__c = fuel.uomList[8].Id,
            Facility2__c = fuel.facility2.Id,
            Location__c = fuel.location3.Id,
            Expiration_Date__c = System.today() + 30
        );

        JsonResult kitResult = WorkOrderKitExtV2.getKitData(wo.Id);
        List<WorkOrderWrapper> kitRows = (List<WorkOrderWrapper>)kitResult.records;
        kitRows[0].serialWrapperList[0].skid.Quantity_to_Issue__c = 1;
        WorkOrderKitExtV2.save(kitRows,new List<String>(),new List<String>());
        
        WorkOrderClosedExt ext = new WorkOrderClosedExt(new ApexPages.StandardController(wo));
        System.assert(ApexPages.hasMessages(ApexPages.Severity.FATAL),ApexPages.getMessages());
    }

    public static testMethod void testClose() {
        WorkOrderPlanningService.release(new Set<Id>{ fuel.workOrder.Id });
        
        WorkOrderClosedExt ext = new WorkOrderClosedExt(new ApexPages.StandardController(fuel.workOrder));
        ext.closeWorkOrder();
        System.assert(!ApexPages.hasMessages(ApexPages.Severity.FATAL),ApexPages.getMessages());

        Work_Order__c wo = WorkOrderService.getWorkOrders(new Set<Id>{ fuel.workOrder.Id },null,null,null)[0];
        System.assert(wo.Status__c == WorkOrderService.WO_STATUS_CLOSED,'Expected WO status: Closed // WO status: ' + wo.Status__c);
        System.assert(wo.Close_Date__c != null,'Expected not null WO close date');
    }
}