src-ken&y/objects/Item__c.object
<CustomObject>
    <customHelpPage>HelpItems</customHelpPage>
    <description>Item Master object</description>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to supplier</description>
        <label>Supplier</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Item&apos;s Supplier must be of type Purchase From</errorMessage>
            <filterItems>
                <field>Supplier__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Purchase From</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Items (Supplier)</relationshipLabel>
        <relationshipName>Items1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Operation_Tracking__c.object
<CustomObject>
    <fields>
        <fullName>Quantity_Completed__c</fullName>
        <label>Quantity Completed</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity_Scrapped__c</fullName>
        <label>Quantity Scrapped</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <label>Operation Tracking</label>
    <nameField>
        <label>Operation Tracking</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Operation Trackings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Supplier__c.object
<CustomObject>
    <customHelpPage>HelpSuppliers</customHelpPage>
    <description>Supplier object</description>
    <fields>
        <fullName>Type__c</fullName>
        <description>The type of supplier record.</description>
        <inlineHelpText>Type of supplier record. Options include: Purchasing and Remit-To.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Parent</fullName>
                </value>
                <value>
                    <fullName>Purchasing</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Remit-To</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Supplier</label>
    <nameField>
        <label>Supplier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/MaterialTrackingTriggerHandler.cls
public with sharing class MaterialTrackingTriggerHandler {
    private static final Set<String> fieldsToRound = new Set<String>{ 'Quantity_Allocated__c', 'Quantity_Completed__c', 'Quantity_Issued__c', 'Quantity_Per_Assembly__c',
        'Quantity_Required__c', 'Quantity_Scrapped__c', 'Quantity_Used__c' };

    public static void beforeInsert() { KSE.roundNumberFields(Trigger.new, fieldsToRound); }
    public static void beforeUpdate() { KSE.roundNumberFields(Trigger.new, fieldsToRound); }

    public static void afterInsert() { ComponentTriggerHandler.validateOSP(Trigger.new); }
    public static void afterUpdate() {
        for (SObject mt:Trigger.new) {
            if (KSE.isFieldChanging('Item__c', mt, Trigger.oldMap) ||  KSE.isFieldChanging('Operation_Tracking__c', mt, Trigger.oldMap) || KSE.isFieldChanging('Type__c', mt, Trigger.oldMap) || KSE.isFieldChanging('Supplier__c', mt, Trigger.oldMap)) {
                ComponentTriggerHandler.validateOSP(Trigger.new);
                return;
            }
        }
    }
    
    public static void beforeDelete() { }
    public static void afterDelete() { }
    public static void afterUndelete() { }
}