src-ken&y/objects/Item__c.object
<CustomObject>
    <customHelpPage>HelpItems</customHelpPage>
    <description>Item Master object</description>
    <label>Item</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Purchase_Order_Line__c.object
<CustomObject>
    <customHelpPage>HelpPurchaseOrders</customHelpPage>
    <description>Line items on a purchase order document</description>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Item being purchased</description>
        <label>Item</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <errorMessage>Item is not active, or company does not match</errorMessage>
            <filterItems>
                <field>Item__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.Company__c</field>
                <operation>equals</operation>
                <valueField>Item__c.Company__c</valueField>
            </filterItems>
            <filterItems>
                <field>Item__c.Company__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>PurchaseOrder Lines</relationshipLabel>
        <relationshipName>Purchase_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order Line</label>
        <referenceTo>Sales_Order_Line__c</referenceTo>
        <relationshipLabel>Purchase Order Lines</relationshipLabel>
        <relationshipName>Purchase_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Goods</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Expense</fullName>
                </value>
                <value>
                    <fullName>Asset</fullName>
                </value>
                <value>
                    <fullName>Drop Ship</fullName>
                </value>
                <value>
                    <fullName>Back To Back</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Purchase Order Line</label>
    <nameField>
        <label>Purchase Order Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Receipt_Line__c.object
<CustomObject>
    <customHelpPage>HelpReceivingDocument</customHelpPage>
    <description>Purchase order receipts</description>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Item received</description>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Receipt Lines</relationshipLabel>
        <relationshipName>Receipt_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purchase_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Purchase Order Line</description>
        <label>Purchase Order Line</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Purchase_Order_Line__c.Purchase_Order__c</field>
                <operation>equals</operation>
                <valueField>$Source.Purchase_Order__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Purchase_Order_Line__c</referenceTo>
        <relationshipLabel>Receipt Lines</relationshipLabel>
        <relationshipName>Receipt_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Receiving_Document__c</fullName>
        <description>Lookup to Receiving Document</description>
        <label>Receiving Document</label>
        <referenceTo>Receiving_Document__c</referenceTo>
        <relationshipLabel>Receipt Lines</relationshipLabel>
        <relationshipName>Receipt_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sales_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order Line</label>
        <referenceTo>Sales_Order_Line__c</referenceTo>
        <relationshipLabel>Receipt Lines</relationshipLabel>
        <relationshipName>Receipt_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Receipt Line</label>
    <nameField>
        <label>Receipt Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Receipt Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Receiving_Document__c.object
<CustomObject>
    <customHelpPage>HelpReceivingDocument</customHelpPage>
    <description>Receiving Document - Advanced Shipment Notice - ASN</description>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of Receiving Document</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Miscellaneous Receipt</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Return Receipt</fullName>
                </value>
                <value>
                    <fullName>Advanced Shipment Notice</fullName>
                </value>
                <value>
                    <fullName>Purchase Order Receipt</fullName>
                </value>
                <value>
                    <fullName>Receipt into In-Transit</fullName>
                </value>
                <value>
                    <fullName>In-Transit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Receiving Document</label>
    <nameField>
        <label>Receiving Document</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Receiving Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Sales_Order_Line__c.object
<CustomObject>
    <customHelpPage>HelpSalesOrders_Managing</customHelpPage>
    <description>Line Items on the Sales Order.</description>
    <fields>
        <fullName>Receipt_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Receipt Line</label>
        <referenceTo>Receipt_Line__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SKID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SKID</label>
        <referenceTo>SKID__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type indicates the sales order line type. (eg. RMA, Kit, Kit-Child, etc...). Based on the value the Sales order line flow is controlled through different status.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>RMA</fullName>
                </value>
                <value>
                    <fullName>Kit</fullName>
                </value>
                <value>
                    <fullName>Kit-Child</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <label>Sales Order Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/SKID__c.object
<CustomObject>
    <customHelpPage>HelpSKIDAbout</customHelpPage>
    <description>Stock Keeping ID</description>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>SKIDs</relationshipLabel>
        <relationshipName>SKIDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purchase_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The purchase order line that matched in Receiving</description>
        <label>Purchase Order Line</label>
        <referenceTo>Purchase_Order_Line__c</referenceTo>
        <relationshipLabel>SKIDs</relationshipLabel>
        <relationshipName>SKIDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Quantity of the item in this SKID</description>
        <label>Quantity (Packaging UOM)</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Receipt_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Receipt Line</label>
        <referenceTo>Receipt_Line__c</referenceTo>
        <relationshipLabel>SKIDs</relationshipLabel>
        <relationshipName>SKIDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Sales Order Line when type is SO Demand</description>
        <label>Sales Order Line</label>
        <referenceTo>Sales_Order_Line__c</referenceTo>
        <relationshipLabel>SKIDs</relationshipLabel>
        <relationshipName>SKIDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>SKID Type delineates where the SKID is at in its life cycle</description>
        <inlineHelpText>SKID type reveals the state of the SKID in its lifecycle.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Forecast Demand</fullName>
                </value>
                <value>
                    <fullName>SO Demand</fullName>
                </value>
                <value>
                    <fullName>WOM Demand</fullName>
                </value>
                <value>
                    <fullName>WO Supply</fullName>
                </value>
                <value>
                    <fullName>PO Supply</fullName>
                </value>
                <value>
                    <fullName>History</fullName>
                </value>
                <value>
                    <fullName>Location</fullName>
                    <default>true</default>
                </value>
                <value>
               		<fullName>Planned Pick</fullName>
                 </value>
                 <value>
                     <fullName>Draft In-Transit</fullName>
                 </value>
                 <value>
                     <fullName>TO Supply</fullName>
                 </value>
                 <value>
                     <fullName>In-Transit</fullName>
                 </value>
                 <value>
                     <fullName>Allocated</fullName>
                 </value>
                 <value>
                     <fullName>TO Demand</fullName>
                 </value>
                 <value>
                     <fullName>WIP</fullName>
                 </value>
                 <value>
                     <fullName>Install Base</fullName>
                 </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SKID</label>
    <nameField>
        <label>SKID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SKIDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/ReceivingWrapper.cls
public with sharing class ReceivingWrapper { // used for Purchase Order, ASN, Transfer Order Receiving
    
    //foundation for source document agnostic receiving service to a certain extent, all receiving processes should use the same service methods everywhere
    
    public SObject rl{ get; set; } //PO line for PO Receiving , Receipt line for RD receiving, order line for TO Receiving
    public Purchase_Order_Line__c pol {get;set;} //used to store purchase order line to avoid conditionals of whether its PO or ASN everywhere as for ASN we need the associated POline too
    public Receipt_Line__c rcl {get;set;} 
    public Item__c item { get;set;} //for storing item to avoid figuring out the path and field names based on source document
    public SObject headerRecord{get;set;}
    public list<SkidService3.SerialWrapper> serialWrapperList { get; set; }
    public list<skid__c> skidList {get;set;}
    public list<String> trackedAttributes { get; set; }
    public Integer minimumShelfLife { get; set; } { minimumShelfLife = 0; }
    public Decimal conversionFactor{get;set;} { conversionFactor = 1; }
    public String lineType { get; set; } //types can be PurchaseOrder, AdvanceShipmentNotice, TransferOrder
    public String putawayType { get; set; }
    public Boolean blockAttributeChange { get;set;} {blockAttributeChange = false;} //used in rental return where what went out must be what is received
    public Boolean addLine { get;set;}
    
    public receivingWrapper( SObject rLine, Purchase_Order_Line__c poLine, Item__c itemRec, List<String> trackedAttr, SObject headerRec, list<SkidService3.SerialWrapper> swlist ){ 
        
        rl = rLine;
        pol = poLine;
        item = itemRec;
        trackedAttributes = trackedAttr;
        lineType = String.valueOf(rl.getSObjectType()).replace(KSE.namespaceUU,'');
        headerRecord = headerRec;

        if(pol != null ){
        	conversionFactor = KSE.getConversionFactor(pol);
        }
        else if(lineType == 'Receipt_Line__c'){
        	conversionFactor = 1;
        	
        	if((Id)rl.get('Sales_Order_Line__c') != null){
        	    conversionFactor = KSE.getConversionFactor(rl.getSObject('Sales_Order_Line__r'));
        	}
        	else if(rl.getSObject('Receiving_Document__r').get('Type__c') == 'Miscellaneous Receipt'){
        		 conversionFactor = KSE.getConversionFactor(rl);
        	}
        	
        	if((Id)rl.get('Sales_Order_Line__c') != null && swlist.size() > 0 && swlist[0].skid.Quantity__c > 0){ //ensure data exists
        	    blockAttributeChange = true;
        	}
        	else{
        	    addLine = true;
        	}
        }
        else if(lineType == 'Sales_Order_Line__c'){
        	conversionFactor = KSE.getConversionFactor(rl);
        	addLine = true;
        }

        if(serialWrapperList == null ) serialWrapperList = new List<SkidService3.SerialWrapper>();
        
        serialWrapperList.addAll(swlist);
        
    }

    public ReceivingWrapper(ReceivingWrapper rWrapper) {
        if (rWrapper.rl != null) this.rl = rWrapper.rl.clone(true, true, true, true);
        if (rWrapper.pol != null) this.pol = rWrapper.pol.clone(true, true, true, true);
        if (rWrapper.rcl != null) this.rcl = rWrapper.rcl.clone(true, true, true, true);
        if (rWrapper.item != null) this.item = rWrapper.item.clone(true, true, true, true);
        if (rWrapper.headerRecord != null) this.headerRecord = rWrapper.headerRecord.clone(true, true, true, true);
        if (rWrapper.serialWrapperList != null) {
            this.serialWrapperList = new List<SkidService3.SerialWrapper>();
            for (SkidService3.SerialWrapper sw:rWrapper.serialWrapperList) this.serialWrapperList.add(new SkidService3.SerialWrapper(sw));
        }
        if (rWrapper.skidList != null) this.skidList = rWrapper.skidList.deepClone(true, true, true);
        if (rWrapper.trackedAttributes != null) this.trackedAttributes = rWrapper.trackedAttributes.clone();
        this.minimumShelfLife = rWrapper.minimumShelfLife;
        this.conversionFactor = rWrapper.conversionFactor;
        this.lineType = rWrapper.lineType;
        this.putawayType = rWrapper.putawayType;
        this.blockAttributeChange = rWrapper.blockAttributeChange;
        this.addLine = rWrapper.addLine;
    }
}