src-ken&y/objects/Location__c.object
<CustomObject>
    <customHelpPage>HelpLocations</customHelpPage>
    <description>Organizational Unit or physical location primarily used if  subclassification reporting is desired</description>
    <label>Location</label>
    <nameField>
        <label>Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Stock_Movement_Rule__c.object
<CustomObject>
    <customHelpPage>HelpStockpoints</customHelpPage>
    <description>Defines the rules to use to decide the picking and the putaway location throughout the system.</description>
    <fields>
        <fullName>Location_List__c</fullName>
        <description>This field is used to store the json string of the list of location ids.</description>
        <inlineHelpText>Used to store json of list of location ids. Do not add to the layout.</inlineHelpText>
        <label>Location List</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Location to be used in pick/putaway.</description>
        <label>Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Location must belong to the company and facility specified !</errorMessage>
            <filterItems>
                <field>Location__c.Facility__r.Company__c</field>
                <operation>equals</operation>
                <valueField>$Source.Company__c</valueField>
            </filterItems>
            <filterItems>
                <field>Location__c.Facility__c</field>
                <operation>equals</operation>
                <valueField>$Source.Facility__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Stock Movement Rules</relationshipLabel>
        <relationshipName>Stock_Movement_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <description>Temporary use field for the location list visualforce section. Please do not add to layout!</description>
        <inlineHelpText>Temporary use field for the location list visualforce section. Please do not add to layout!</inlineHelpText>
        <label>Sequence</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Stock Movement Rule</label>
    <nameField>
        <label>Stock Movement Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stock Movement Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/LocationListExtension.cls
public with sharing class LocationListExtension {
    
    public class LocationListExtensionException extends Exception{}
    public list<Stock_Movement_Rule__c> smrList {get;set;}{ smrList = new list<Stock_Movement_Rule__c>();}
    
    public LocationListExtension(ApexPages.StandardController con) {
        
        try{
            if( con.getRecord().id != null ){
                Stock_Movement_Rule__c smr = (Stock_Movement_Rule__c) con.getRecord();
                
                list<Id> locList;
                if( smr.Location_List__c != null ){
                    try{
                        locList = (list<Id>)JSON.deserialize(String.valueOf(smr.get('Location_List__c')), list<Id>.Class);
                    }
                    catch(Exception e){
                        ApexPages.addMessage( new ApexPages.Message(ApexPages.Severity.Error, 'Invalid location specified on stock movement rule :'+smr.get('name') ));
                        return;
                    }
                }
                else if( smr.Location_List__c == null || locList.size() == 0 ){
                    throw new LocationListExtensionException('No Locations have been specified for this rule!');
                }
                
                if( locList.size() > 0 ){
                    
                    for( Integer i = 0; i< locList.size() ; i++ ){
                        Stock_Movement_Rule__c locRule = smr.clone(false,true);
                        locRule.Location__c = locList[i];
                        locRule.Sequence__c = i+1;
                        smrList.add( locRule );
                    }
                }
            }
        }
        catch( Exception e ){
            ApexPages.addMessage( new ApexPages.Message(ApexPages.Severity.Error, MessageUtil.toFriendlyErrorMessage(e.getMessage())));
            system.debug(LoggingLevel.Error, 'EXCEPTION: ' + e.getMessage() + ' ' + e.getStackTraceString());
        }
    }
}