src-ken&y/objects/Means_of_Transport__c.object
<CustomObject>
    <customHelpPage>HelpMeansOfTransport</customHelpPage>
    <description>Stores the different means of transportation and their details.</description>
    <fields>
        <fullName>Maximum_Cube__c</fullName>
        <description>Maximum Cube of a truck</description>
        <inlineHelpText>Maximum cubic capacity (dimensions) for this means of transport.</inlineHelpText>
        <label>Maximum Cube</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Means of Transport</label>
    <nameField>
        <label>Means of Transport</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Means of Transport</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Transit_Route__c.object
<CustomObject>
    <customHelpPage>HelpTransitRoute</customHelpPage>
    <description>Stores the transit times between &quot;Ship From&quot;  and &quot;Ship To&quot; locations. This will be used to calculate the delivery date of a sales order.</description>
    <fields>
        <fullName>Destination__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The address at which the route for transportation ends.</description>
        <label>Destination</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transit Routes (Inbound)</relationshipLabel>
        <relationshipName>Transit_Routes_Inbound</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Means_of_Transport__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The means of transportation by which the goods will be carried in this route.</description>
        <label>Means of Transport</label>
        <referenceTo>Means_of_Transport__c</referenceTo>
        <relationshipLabel>Transit Routes</relationshipLabel>
        <relationshipName>Transit_Routes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The address from which the route for transportation originates.</description>
        <label>Origin</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transit Routes (Outbound)</relationshipLabel>
        <relationshipName>Transit_Routes_Outbound</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A check mark indicates that this is the primary, or preferred, transit route between the origin and destination.</description>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Transit_Time__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The time (in days) it takes for the shipped goods to reach the destination of this route.</description>
        <inlineHelpText>The number of days it takes for the goods to reach the destination.</inlineHelpText>
        <label>Transit Time (Days)</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Transit Route</label>
    <nameField>
        <label>Transit Route</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transit Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/TransitRouteNewExtTest.cls
@isTest
private class TransitRouteNewExtTest { 
    
   static testmethod void testSave(){ 
       Means_of_Transport__c objMT = new Means_of_Transport__c();
       objMT.Name = 'Truck';
       objMT.Maximum_cube__c = 10;
       insert objMT;
    
       Account objact = new Account();
       objact.Name = 'TestOrigin';
       insert objact;
    
       Account objact1 = new Account();
       objact1.Name = 'TestDestination';
       insert objact1;
    
       ApexPages.standardcontroller sc = new ApexPages.standardcontroller(new transit_route__c());
       TransitRouteNewExt trExt = new TransitRouteNewExt(sc);
       trExt.newObj.Origin__c = objact.Id;
       trExt.newObj.Destination__c = objact1.Id;
       trExt.newObj.Means_Of_Transport__c = objMT.Id;
       trExt.newObj.Transit_Time__c = 5;
    
       test.startTest();
       trExt.save();
       system.assertNotEquals(null,trExt.newObj.Id);
       
       trExt.deleteRoute();
       test.stopTest();
       transit_route__c[] tmp = [ select id from transit_route__c where id = :trExt.newObj.id limit 1];
       system.assert( tmp.size() == 0, ' expected to be able to delete');
   }
    
    static testmethod void testSaveandNew(){
       Means_of_Transport__c objMT = new Means_of_Transport__c();
       objMT.Name = 'Truck';
       objMT.Maximum_cube__c = 10;
       insert objMT;
    
       Account objact = new Account();
       objact.Name = 'TestOrigin';
       insert objact;
    
       Account objact1 = new Account();
       objact1.Name = 'TestDestination';
       insert objact1;
    
       ApexPages.standardcontroller sc = new ApexPages.standardcontroller(new transit_route__c());
       TransitRouteNewExt trExt = new TransitRouteNewExt(sc);
       trExt.newObj.Origin__c = objact.Id;
       trExt.newObj.Destination__c = objact1.Id;
       trExt.newObj.Means_Of_Transport__c = objMT.Id;
       trExt.newObj.Transit_Time__c = 5;
    
       PageReference returnPageRef = trExt.saveandnew();
       
       system.assertNotEquals(null,trExt.newObj.Id);
    
       PageReference pageRef = Page.TransitRouteNew;
        system.assertEquals(returnPageRef.getURL(), pageRef.getUrl());
    }
   
   /**
   *    @description Test to check that we cannot create two primary 
   *    transit routes for the same origin and destination
   */ 
   static testmethod void testPrimaryKey(){
       Means_of_Transport__c objMT = new Means_of_Transport__c();
       objMT.Name = 'Truck';
       objMT.Maximum_cube__c = 10;
       insert objMT;
    
       Means_of_Transport__c objMT2 = new Means_of_Transport__c();
       objMT2.Name = 'Truck2';
       objMT2.Maximum_cube__c = 10;
       insert objMT2;

       Account objact = new Account();
       objact.Name = 'TestOrigin';
       insert objact;
    
       Account objact1 = new Account();
       objact1.Name = 'TestDestination';
       insert objact1;
    
       Transit_Route__c objTR = new Transit_Route__c();
       objTR.Origin__c = objact.Id;
       objTR.Destination__c = objact1.Id;
       objTR.Means_Of_Transport__c = objMT2.Id;
       objTR.Transit_Time__c = 5;
       objTR.Primary__c = true;
       insert objTR;
       system.assertEquals(true,objTR.Primary__c);
    
       Transit_Route__c objTR1 = new Transit_Route__c();
       objTR1.Origin__c = objact.Id;
       objTR1.Destination__c = objact1.Id;
       objTR1.Means_Of_Transport__c = objMT.Id;
       objTR1.Transit_Time__c = 8;
       objTR1.Primary__c = true;
        
        try{
           insert objTR1;
           system.assert(false);
        }
        catch(exception e){
           system.assert(e.getmessage().contains('DUPLICATE_VALUE'),e.getmessage());
        }
        system.assertEquals(null, objTR1.Id);
    }
}