src-ken&y/objects/Means_of_Transport__c.object
<CustomObject>
    <customHelpPage>HelpMeansOfTransport</customHelpPage>
    <description>Stores the different means of transportation and their details.</description>
    <fields>
        <fullName>Code__c</fullName>
        <description>The unique code assigned to the means of transport to identify it distinctly.</description>
        <externalId>true</externalId>
        <inlineHelpText>The code uniquely identifies the selected means of transport.</inlineHelpText>
        <label>Code</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Mode_of_Transport__c</fullName>
        <description>The mode (medium) through which the means of transport travels. Ex: Air, Water, Land etc,.</description>
        <inlineHelpText>Indicates how goods are transported. Options may include Road, Rail, Water, Air.</inlineHelpText>
        <label>Mode of Transport</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Land</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Rail</fullName>
                </value>
                <value>
                    <fullName>Water</fullName>
                </value>
                <value>
                    <fullName>Air</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Means of Transport</label>
    <nameField>
        <label>Means of Transport</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Means of Transport</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/TransitRouteServiceTest.cls
/**
 * This class contains unit tests for validating the behavior of test methods in TransitRouteService.cls
 */
@isTest
private class TransitRouteServiceTest {
	
	static testMethod void testDuplicateMeansOfTransport(){
	    
	    Means_of_Transport__c mot = new Means_of_Transport__c();
		mot.Code__c = '123';
		mot.Mode_of_Transport__c = 'Land';
		mot.Name = 'LTL';
		
		try{
			insert mot;
		}catch(Exception e){
			system.assert(false, 'Unexpected exception thrown: ' + e.getMessage());
		}
		
		Means_of_Transport__c mot2 = new Means_of_Transport__c();
		mot2.Code__c = '123';
		mot2.Mode_of_Transport__c = 'Land';
		mot2.Name = 'LTL';
		
		try{
			insert mot2;
			system.assert(false, 'Expected an exception to be thrown: ');
		}catch(DMLException e){
			system.assertEquals(StatusCode.DUPLICATE_VALUE, e.getDmlType(0), 'Unexpected exception thrown: ' + e.getMessage());
		}
	} 
}