src-ken&y/objects/Means_of_Transport__c.object
<CustomObject>
    <customHelpPage>HelpMeansOfTransport</customHelpPage>
    <description>Stores the different means of transportation and their details.</description>
    <label>Means of Transport</label>
    <nameField>
        <label>Means of Transport</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Means of Transport</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Sales_Order__c.object
<CustomObject>
    <customHelpPage>HelpSalesOrders_Managing</customHelpPage>
    <description>Sales Order Header</description>
    <fields>
        <fullName>Has_Exceptions__c</fullName>
        <description>Indicates if the record has exceptions that need to be resolved.</description>
        <formula>OR(
   Exceptions_Count__c &gt; 0,
   Line_Exceptions__c &gt; 0
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Exceptions must be resolved before the sales order/line can proceed.</inlineHelpText>
        <label>Has Exceptions</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Means_of_Transport__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The means of transport by which the sales order should be delivered.</description>
        <label>Means of Transport</label>
        <referenceTo>Means_of_Transport__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Required_Date__c</fullName>
        <description>Default required date for sales order lines.</description>
        <label>Need Date</label>
        <type>Date</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Sales_Order_Line__c.object
<CustomObject>
    <customHelpPage>HelpSalesOrders_Managing</customHelpPage>
    <description>Line Items on the Sales Order.</description>
    <fields>
        <fullName>Has_Exceptions__c</fullName>
        <description>If selected, there is a problem with the sales order line. Exceptions must be resolved before you can process the order.</description>
        <formula>Exceptions_Count__c &gt; 0</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Has Exceptions</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Required_Date__c</fullName>
        <defaultValue>today( )</defaultValue>
        <description>Date the customer requires the line item</description>
        <label>Need Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <label>Sales Order</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Company does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>Sales_Order__c.Company__c</field>
                <operation>equals</operation>
                <valueField>$Source.Company__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Sales_Order__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <label>Sales Order Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Shipment__c.object
<CustomObject>
    <customHelpPage>HelpShipment</customHelpPage>
    <description>Sales Order Shipment Header</description>
    <fields>
        <fullName>Has_Exceptions__c</fullName>
        <description>Indicates that there are issues to be resolved related to this shipment and may not be processed any further until then.</description>
        <formula>OR(
Exceptions_Count__c &gt; 0,
Line_Exceptions__c &gt; 0
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Has Exceptions</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Means_of_Transport__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The means of transport by which the shipment will be delivered.</description>
        <inlineHelpText>Indicates the transport used to ship the goods. The Means of Transport record includes the weight and volume limitations as well as pallet positions available.</inlineHelpText>
        <label>Means of Transport</label>
        <referenceTo>Means_of_Transport__c</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Planned_Delivery_Date__c</fullName>
        <description>The date on which the shipment is planned to be delivered to the customer.</description>
        <inlineHelpText>Date on which the shipment is planned to be delivered to the customer. The date is determined by the FOB term (pickup or delivery), which is specified on the sales order.</inlineHelpText>
        <label>Need Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Shipment_Date_Estimated__c</fullName>
        <inlineHelpText>This date is driven by the Required Date (see Sales Order) and the Earliest Shipment Date.</inlineHelpText>
        <label>Estimated Ship Date</label>
        <type>Date</type>
    </fields>
    <label>Shipment</label>
    <nameField>
        <label>Shipment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Shipment_Line__c.object
<CustomObject>
    <customHelpPage>HelpShipment</customHelpPage>
    <description>Shipment lines.</description>
    <fields>
        <fullName>Has_Exceptions__c</fullName>
        <formula>Exceptions_Count__c &gt; 0</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Has Exceptions</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sales_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to sales order line</description>
        <label>Sales Order Line</label>
        <referenceTo>Sales_Order_Line__c</referenceTo>
        <relationshipLabel>Shipment Lines</relationshipLabel>
        <relationshipName>Shipment_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The sales order related to this shipment</description>
        <label>Sales Order</label>
        <referenceTo>Sales_Order__c</referenceTo>
        <relationshipLabel>Shipment Lines</relationshipLabel>
        <relationshipName>Shipment_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <description>Lookup to Shipment</description>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Shipment Lines</relationshipLabel>
        <relationshipName>Shipment_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Shipment Line</label>
    <nameField>
        <label>Shipment Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipment Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/classes/ShipmentDatesBatchTest.cls
/**
 * This class contains unit tests for validating the behavior of ShipmentDatesBatch.cls
 */
@isTest
private class ShipmentDatesBatchTest {
	static TestFuel globalTestData = new TestFuel();
	
	static testMethod void testShipmentDatesBatchWithoutRequiredDate() {
        
        system.assert(globalTestData.salesOrder.Id != null);

        Test.startTest();
        
        globalTestData.salesOrder.Means_of_Transport__c = globalTestData.meansOfTransport.Id;
    	update globalTestData.salesOrder;
    	
    	globalTestData.facility2.Lead_Time__c = 2;
    	update globalTestData.facility2;
    	
    	// Release the sales order to check if the dates are being populated.
    	ApexPages.StandardController sc = new ApexPages.StandardController(globalTestData.salesOrder);
    	SOPlanExt soReleaseExt = new SOPlanExt(sc);
    	soReleaseExt.plan();
    	
    	Map<Id, Shipment__c> plannedShipments = new Map<Id, Shipment__c>();
    	
    	// Get the planned shipment for the sales order.
    	for(Shipment_Line__c shipmentLine : [select Id, Shipment__c, Shipment__r.Shipment_Date_Estimated__c 
											   from Shipment_Line__c 
										      where Sales_Order_Line__c IN :globalTestData.salesOrderLines]){
	   		plannedShipments.put(shipmentLine.Shipment__c, shipmentLine.Shipment__r);
	   	}
	    
        system.assert(plannedShipments.size() > 0);
		
		// Expire the estimated shipment date
		for(Shipment__c shipment : plannedShipments.values()){
			shipment.Shipment_Date_Estimated__c = null;
		}
		
		update plannedShipments.values();
		
		ShipmentDatesBatch batchInstance = new ShipmentDatesBatch();
		batchInstance.runBatch(globalTestData.company.Id);
		
		// Finish executing the batch
		Test.stopTest();
		
		for(Shipment_Line__c shipmentLine : [select Id, Shipment__c, Shipment__r.Shipment_Date_Estimated__c 
											   from Shipment_Line__c 
										      where Sales_Order_Line__c IN :globalTestData.salesOrderLines]){
	   		system.assert(shipmentLine.Shipment__r.Shipment_Date_Estimated__c >= system.today());
	   	}
    }
    
    static testMethod void testShipmentDatesBatchWithRequiredDate() {
        
        system.assert(globalTestData.salesOrder.Id != null);

        Test.startTest();
        
        Date requiredDate = system.today() + 7;
    	
    	globalTestData.salesOrder.Required_Date__c = requiredDate;
    	globalTestData.salesOrder.Means_of_Transport__c = globalTestData.meansOfTransport.Id;
    	update globalTestData.salesOrder;
    	
    	globalTestData.facility2.Lead_Time__c = 2;
    	update globalTestData.facility2;
    	
    	// Release the sales order to check if the dates are being populated.
    	ApexPages.StandardController sc = new ApexPages.StandardController(globalTestData.salesOrder);
    	SOPlanExt soReleaseExt = new SOPlanExt(sc);
    	soReleaseExt.plan();
    	
    	Map<Id, Shipment__c> plannedShipments = new Map<Id, Shipment__c>();
    	
    	// Get the planned shipment for the sales order.
    	for(Shipment_Line__c shipmentLine : [select Id, Shipment__c, Shipment__r.Shipment_Date_Estimated__c 
											   from Shipment_Line__c 
										      where Sales_Order_Line__c IN :globalTestData.salesOrderLines]){
	   		plannedShipments.put(shipmentLine.Shipment__c, shipmentLine.Shipment__r);
	   	}
	    
        system.assert(plannedShipments.size() > 0);
		
		// Expire the estimated shipment date
		for(Shipment__c shipment : plannedShipments.values()){
			shipment.Shipment_Date_Estimated__c = null;
		}
		
		update plannedShipments.values();
		
		ShipmentDatesBatch batchInstance = new ShipmentDatesBatch();
		batchInstance.runBatch(globalTestData.company.Id);
		
		// Finish executing the batch
		Test.stopTest();
		
		for(Shipment_Line__c shipmentLine : [select Id, Shipment__c, Shipment__r.Shipment_Date_Estimated__c 
											   from Shipment_Line__c 
										      where Sales_Order_Line__c IN :globalTestData.salesOrderLines]){
	   		system.assert(shipmentLine.Shipment__r.Shipment_Date_Estimated__c >= system.today());
	   	}
    }
    
    static testMethod void testShipmentDatesBatchWithShortRequiredDate() {
        
        system.assertNotEquals(null, globalTestData.salesOrder.Id, 'globalTestData.salesOrder: ' + globalTestData.salesOrder); //KNDY-4989

        Test.startTest();
        
        Date requiredDate = system.today() + 7;
    	
    	globalTestData.salesOrder.Required_Date__c = requiredDate;
    	globalTestData.salesOrder.Means_of_Transport__c = globalTestData.meansOfTransport.Id;
    	update globalTestData.salesOrder;
    	
    	globalTestData.facility2.Lead_Time__c = 2;
    	update globalTestData.facility2;
    	
    	// Release the sales order to check if the dates are being populated.
    	ApexPages.StandardController sc = new ApexPages.StandardController(globalTestData.salesOrder);
    	SOPlanExt soReleaseExt = new SOPlanExt(sc);
    	soReleaseExt.plan();
    	
    	globalTestData.salesOrder.Required_Date__c = system.today();
    	update globalTestData.salesOrder;
    	
    	Map<Id, Shipment__c> plannedShipments = new Map<Id, Shipment__c>();
    	
    	// Get the planned shipment for the sales order.
    	for(Shipment_Line__c shipmentLine : [select Id, Shipment__c, Shipment__r.Shipment_Date_Estimated__c 
											   from Shipment_Line__c 
										      where Sales_Order_Line__c IN :globalTestData.salesOrderLines]){
	   		plannedShipments.put(shipmentLine.Shipment__c, shipmentLine.Shipment__r);
	   	}
	    
	    //KNDY-4989
        system.assert(plannedShipments.size() > 0, 'exp: plannedShipments.size() > 0.  act: '+ plannedShipments.size() + ' *** gtd.sol.size: '+ globalTestData.salesOrderLines.size() + ' *** gtd.sol'+globalTestData.salesOrderLines);
		
		// Expire the estimated shipment date
		for(Shipment__c shipment : plannedShipments.values()){
			shipment.Shipment_Date_Estimated__c = null;
			shipment.Planned_Delivery_Date__c = system.today();
		}
		
		ExceptionService.ignoreSet.add('Shipment__c');
		update plannedShipments.values();
		ExceptionService.ignoreSet.remove('Shipment__c');
		
		ShipmentDatesBatch batchInstance = new ShipmentDatesBatch();
		batchInstance.runBatch(globalTestData.company.Id);
		
		// Finish executing the batch
		Test.stopTest();
		
		for(Shipment_Line__c shipmentLine : [select Id, Sales_Order_Line__r.Sales_Order__r.Has_Exceptions__c, Shipment__r.Shipment_Date_Estimated__c, Shipment__r.Planned_Delivery_Date__c,
													Shipment__r.Has_Exceptions__c 
											   from Shipment_Line__c 
										      where Sales_Order_Line__c IN :globalTestData.salesOrderLines]){
			
			//OTC-266
			system.assertEquals(system.today(), shipmentLine.Shipment__r.Shipment_Date_Estimated__c, 'shipmentLine: '+ shipmentLine);
	   	}
    }
}