src-ken&y/objects/Order__c.object
<CustomObject>
    <customHelpPage>HelpOrder</customHelpPage>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Order_Line__c.object
<CustomObject>
    <customHelpPage>HelpOrder</customHelpPage>
    <description>The order lines for the related order object.</description>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Lines</relationshipLabel>
        <relationshipName>Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity_Allocated__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The quantity that is allocated to the order line but not yet shipped.</description>
        <label>Quantity Allocated</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity_Received__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Quantity Received</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity_Shipped__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The number of items that have been shipped to date. This field is copied over and kept up to date from the corresponding shipment details object.</description>
        <label>Quantity Shipped</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order Line</label>
    <nameField>
        <label>Order Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/classes/TransferOrderCancelExt.cls
public with sharing class TransferOrderCancelExt {
    private ApexPages.StandardController con;
              
        public TransferOrderCancelExt(ApexPages.StandardController sc)
        {
            con = sc;
        }
        
        public Order__c order {get; set;}
        
        public PageReference Cancel(){
        
        try
        {           
            this.order =   (Order__c)con.getRecord();           
                        
            if(this.order.status__c=='Cancelled' || this.order.status__c =='Closed')
            {   ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, Label.Transfer_Order_cancelled_closed));
                return null;
            } 
            Boolean showerror = false;          
            
            //Cancel Order Lines
            
			//KNDY-10473: Adding CRUD/FLS checks with SOQLUtil
			Id orderId = this.order.Id;
			SOQLUtil soql = new SOQLUtil('Order_Line__c', true); //enforceFLS=true, running in user mode
			soql.addFields(new set<string>{
				'id','Name','Status__c','Quantity_Allocated__c','Quantity_Received__c','Quantity_Shipped__c'
			});
			soql.setWhereClause('Order__c = :orderId');

			List<Order_Line__c> orderLineList = Database.query(soql.getQuery());

            for(Order_Line__c oline: orderLineList){ 
                if(oline.Quantity_Allocated__c >0 || oline.Quantity_Received__c >0 || oline.Quantity_Shipped__c >0){
                    showerror = true;
                    break;
                }               
                System.debug('After break');
            }
            if(orderLineList.size()>0 && showerror == true){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, Label.Transfer_Order_cannot_be_cancelled));
                return null;
            }
                        
            if(orderLineList.size()>0 && showerror == false){
                ReceivingDocumentService.close(new Set<Id>{con.getId()},'Order_Line__c','Order__c','Order__c',null, true, false,'Cancelled');               
            }
                        
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.INFO, Label.Transfer_Order_cancelled));
            
        }
        catch( Exception e )
        {            
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, MessageUtil.toFriendlyErrorMessage(e.getMessage())));
            system.debug(LoggingLevel.Error, 'EXCEPTION: ' + e.getMessage() + ' ' + e.getStackTraceString());
        }
        
        return null; 
    }
}