src-ken&y/objects/Receipt_Line__c.object
<CustomObject>
    <customHelpPage>HelpReceivingDocument</customHelpPage>
    <description>Purchase order receipts</description>
    <fields>
        <fullName>Quantity_Declared__c</fullName>
        <description>Quantity shipped on Advanced Shipment Notice</description>
        <inlineHelpText>Quantity shipped on Advanced Shipment Notice.</inlineHelpText>
        <label>Quantity Declared</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity_Still_Due_For_Putaway__c</fullName>
        <label>Quantity Still Due For Putaway</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Receiving_Document__c</fullName>
        <description>Lookup to Receiving Document</description>
        <label>Receiving Document</label>
        <referenceTo>Receiving_Document__c</referenceTo>
        <relationshipLabel>Receipt Lines</relationshipLabel>
        <relationshipName>Receipt_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Line status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Receipt Line</label>
    <nameField>
        <label>Receipt Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Receipt Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/objects/Receiving_Document__c.object
<CustomObject>
    <customHelpPage>HelpReceivingDocument</customHelpPage>
    <description>Receiving Document - Advanced Shipment Notice - ASN</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>Receiving Document Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Receiving Document</label>
    <nameField>
        <label>Receiving Document</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Receiving Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/ReceivingDocumentReleaseExtTest.cls
@isTest
private class ReceivingDocumentReleaseExtTest {

    static testMethod void testReceivingDocumentRelease() {
        
        TestFuel testData = new TestFuel();
        
        Receiving_Document__c rd = testData.receivingDocumentMisc;
        
        Test.startTest();
        
        ApexPages.StandardController con = new ApexPages.StandardController(rd);
        ReceivingDocumentReleaseExt rdre = new ReceivingDocumentReleaseExt(con);
        
        rdre.release();
        
        Test.stopTest();
        
        list<Receipt_Line__c> rlList = [ select id, Status__c, Quantity_Still_Due_For_Putaway__c, Receiving_Document__r.Status__c, Quantity_Declared__c From Receipt_Line__c 
                                        where Receiving_Document__c =:rd.id ];
        
        system.assert( rlList.size() == 1 );
        
        Receipt_Line__c rl = rlList[0];
        system.assert( rl.status__c == 'Open', ApexPages.getMessages());
        system.assert( rl.Receiving_Document__r.status__c == 'Open');
        system.assert( rl.Quantity_Still_Due_For_Putaway__c == rl.Quantity_declared__c);
    }
    
    static testMethod void testReceivingDocumentReleaseErrors() {
        
        TestFuel testData = new TestFuel();
        
        Receiving_Document__c rd = testData.receivingDocumentMisc;
        Receipt_Line__c rl = testData.receivingDocumentMiscLines[0];
        rl.Status__c = 'Closed';
        DML.updateAsUser( rl );
        
        Test.startTest();
        
        ApexPages.StandardController con = new ApexPages.StandardController(rd);
        ReceivingDocumentReleaseExt rdre = new ReceivingDocumentReleaseExt(con);
        
        rdre.release();
        system.assert( ApexPages.getMessages().size() == 1, Label.Cannot_release_Receiving_Document );
        
        Test.stopTest();
    }
}