src-ken&y/objects/Sales_Order__c.object
<CustomObject>
    <customHelpPage>HelpSalesOrders_Managing</customHelpPage>
    <description>Sales Order Header</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>Order status</description>
        <label>Order Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>On hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Product_Weight__c</fullName>
        <label>Total Product Weight</label>
        <summarizedField>Sales_Order_Line__c.Product_Weight__c</summarizedField>
        <summaryFilterItems>
            <field>Sales_Order_Line__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Cancelled</value>
        </summaryFilterItems>
        <summaryForeignKey>Sales_Order_Line__c.Sales_Order__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Sales_Order_Line__c.object
<CustomObject>
    <customHelpPage>HelpSalesOrders_Managing</customHelpPage>
    <description>Line Items on the Sales Order.</description>
    <fields>
        <fullName>Parent_Sales_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Sales Order Line</label>
        <referenceTo>Sales_Order_Line__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <label>Sales Order</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Company does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>Sales_Order__c.Company__c</field>
                <operation>equals</operation>
                <valueField>$Source.Company__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Sales_Order__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Line open if item is not shipped; line closed if shipped; line partial if partially shipped</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <label>Sales Order Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/classes/SalesOrderCloseExtTest.cls
/**
 * @description:	Contains test methods for SalesOrderCloseExt.cls
 */
@isTest
public with sharing class SalesOrderCloseExtTest {
	static TestData globalTestData = new TestData();
	
	static testMethod void testSalesOrderCloseExt(){
		
		Test.startTest();
		
		globalTestData.salesOrder.Status__c = 'Closed';
		update globalTestData.salesOrder;
		
		ApexPages.StandardController con = new ApexPages.StandardController(globalTestData.salesOrder);
		
		SalesOrderCloseExt soce = new SalesOrderCloseExt(con);
		System.assertEquals(false, soce.showConfirm);
		
		globalTestData.salesOrder.Status__c = 'Open';
		update globalTestData.salesOrder;
		
		Sales_Order__c SO = [SELECT Id, Total_Product_Weight__c, (select id, Status__c from sales_order_lines__r) FROM Sales_Order__c WHERE Id = :globalTestData.salesOrder.Id];
		System.assert(SO.Total_Product_Weight__c > 0, SO.Total_Product_Weight__c);

		Sales_Order_Line__c[] solList = so.sales_order_lines__r;
		for (sales_order_line__c sol : solList){
			sol.Status__c = SalesOrderService.SO_STATUS_OPEN;
		}
		update solList;

		globalTestData.salesOrder.Status__c = 'Cancelled';
		update globalTestData.salesOrder;
		
		// OTC-485
		SO = [SELECT Id, Total_Product_Weight__c FROM Sales_Order__c WHERE Id = :globalTestData.salesOrder.Id];
		System.assertEquals(0, SO.Total_Product_Weight__c);

		con = new ApexPages.StandardController(globalTestData.salesOrder);
		
		soce = new SalesOrderCloseExt(con);
		System.assertEquals(false, soce.showConfirm);
		
		globalTestData.salesOrder.Status__c = 'Open';

		try {
			update globalTestData.salesOrder;
			System.assertEquals(false, true, 'Cannot update a Cancelled sales order status');
		} catch(Exception e) {
			System.debug(e.getMessage());
		}	
		
		Test.stopTest();
		
	}
	
	static testMethod void testCloseSalesOrder(){
		Test.startTest();
		
		globalTestData.salesOrder.Status__c = 'Open';
		update globalTestData.salesOrder;
		
		for(Sales_Order_Line__c sol : globalTestData.SalesOrderLines){
			sol.Status__c = 'Open';
		}
		
		update globalTestData.SalesOrderLines;
		
		ApexPages.StandardController con = new ApexPages.StandardController(globalTestData.salesOrder);
		
		SalesOrderCloseExt soce = new SalesOrderCloseExt(con);
		
		System.assertEquals(true, soce.showConfirm);

		Test.stopTest();
	}
	
	//Moved the below test from SalesOrderCloneExt
 	public static testMethod void t1() {
        //TestData data = new TestData();
        Test.StartTest(); 
        ApexPages.StandardController sc = new ApexPages.StandardController( globalTestData.salesOrder );
        SalesOrderCloneExt soc = new SalesOrderCloneExt( sc );
        Pagereference p0 = soc.Save();
        system.assert( p0 != null );
     }	
	
}