src-ken&y/objects/SKID__c.object
<CustomObject>
    <customHelpPage>HelpSKIDAbout</customHelpPage>
    <description>Stock Keeping ID</description>
    <fields>
        <fullName>Work_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Work order related to the on order SKID</description>
        <label>Work Order</label>
        <referenceTo>Work_Order__c</referenceTo>
        <relationshipLabel>SKIDs</relationshipLabel>
        <relationshipName>SKIDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SKID</label>
    <nameField>
        <label>SKID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SKIDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Work_Order__c.object
<CustomObject>
    <customHelpPage>HelpWorkOrder</customHelpPage>
    <description>All work orders including planned orders from MRP as well as unplanned orders.</description>
    <fields>
        <fullName>Contents__c</fullName>
        <label>Contents</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Work Order</label>
    <nameField>
        <label>Work Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/WorkOrderContentsExtTest.cls
@isTest
public with sharing class WorkOrderContentsExtTest {
    
    private static testMethod void testMissedCases() {
        TestFuel fuel = new TestFuel();
        List<SKID__c> skids = fuel.skids;
        Work_Order__c wo = fuel.workOrder;
        wo.contents__c = '1,2,3,7,8,14,15,16,19,20';
        update wo;
        //expected values
        String completeCases = '1-3,7-8,14-16,19-20';
        String missingCases = '4,5,6,9,10,11,12,13,17,18';
        Integer totalMissingCases = 10;
        WorkOrderPlanningService.release(new Set<Id>{wo.Id});
        ApexPages.StandardController con = new ApexPages.StandardController(wo);
        WorkOrderContentsExt ext = new WorkOrderContentsExt(con);
        
        System.assert(ext.completeCases != null );
        System.assert(ext.missingCases != null );
        System.assert(ext.totalMissingCases != null );
        System.assertEquals(completeCases,ext.completeCases);
        System.assertEquals(missingCases,ext.missingCases);
        System.assertEquals(totalMissingCases,ext.totalMissingCases);
        
    }  
    private static testMethod void testNOMissedCases() {
        TestFuel fuel = new TestFuel();
        List<SKID__c> skids = fuel.skids;
        Work_Order__c wo = fuel.workOrder;
        wo.contents__c = '1,2,3,4,5';
        update wo;
        //expected values
        String completeCases = '1-5';
        WorkOrderPlanningService.release(new Set<Id>{wo.Id});
        ApexPages.StandardController con = new ApexPages.StandardController(wo);
        WorkOrderContentsExt ext = new WorkOrderContentsExt(con);
        
        System.assert(ext.completeCases != null );
        System.assert(ext.missingCases == null );
        System.assert(ext.totalMissingCases == null );
        System.assertEquals(completeCases,ext.completeCases);
        
    }
}