src-ken&y/objects/Supplier_Invoice__c.object
<CustomObject>
    <customHelpPage>HelpSupplierInvoice</customHelpPage>
    <description>Record invoices for items or services  that are received from a supplier.  Bills can be recorded with or without purchase orders</description>
    <fields>
        <fullName>Supplier_Invoice__c</fullName>
        <description>Supplier invoice no. reference</description>
        <label>Invoice Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Supplier Invoice</label>
    <nameField>
        <label>Supplier Invoice</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Supplier_Invoice_Line__c.object
<CustomObject>
    <customHelpPage>HelpSupplierInvoice</customHelpPage>
    <fields>
        <fullName>Supplier_Invoice__c</fullName>
        <label>Supplier Invoice</label>
        <referenceTo>Supplier_Invoice__c</referenceTo>
        <relationshipLabel>Supplier Invoice Line</relationshipLabel>
        <relationshipName>Supplier_Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Supplier Invoice Line</label>
    <nameField>
        <label>Supplier Invoice Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier Invoice Line</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-ken&y/classes/TaskType.cls
global with sharing class TaskType {
		
	global static final String EXCEPTION_STATUS_OPEN = 'Open';
	global static final String EXCEPTION_STATUS_CLOSED = 'Closed';
	global static final String EXCEPTION_STATUS_OVERRIDDEN = 'Overridden';
	
	global static final Map<String,String> childToParentMap = new Map<String,String>{'Supplier_Invoice_Line__c'=>'Supplier_Invoice__c'};
	
	global String code {get; public set;}
	global String label {get; public set;}
	global String description {get; public set;}
	global String typeName {get; public set;}
	global String countFieldAPIName {get; public set;}
	global Id assignedTo {get; public set;}
	global Boolean ProhibitOverride {get; public set;}{prohibitOverride=false;}
	
	public TaskType(){ 
		
	}
	
	global TaskType(String code, String label, String description, String typeName, Id assignedTo){
		this(code, label, description, typeName, assignedTo, false);
	}
	
	global TaskType(String code, String label, String description, String typeName, Id assignedTo, Boolean ProhibitOverride){
		this(code, label, description, typeName, '', assignedTo, false);
	}
	
	global TaskType(String code, String label, String description, String typeName, String countFieldAPIName, Id assignedTo, Boolean ProhibitOverride){
		this.code = code;
		this.label = label;
		this.description = description;
		this.typeName = typeName;
		this.countFieldAPIName = countFieldAPIName;
		this.assignedTo = assignedTo;
		this.ProhibitOverride = ProhibitOverride;
	}
	
	
}