src-ken&y/objects/Supplier_Payment__c.object
<CustomObject>
    <customHelpPage>HelpSupplierPayments</customHelpPage>
    <description>Pay supplier invoices</description>
    <fields>
        <fullName>Batch_Job_ID__c</fullName>
        <label>Batch Job ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Finalized__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Finalized flag is set to true when the record is finalized and no changes to the record are expected.</description>
        <inlineHelpText>A check mark indicates that the document is final. Kenandy will automatically generate an accounting entry for it in the next scheduled batch process.</inlineHelpText>
        <label>Finalized</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Source_Key__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Source Key</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Supplier Payment</label>
    <nameField>
        <label>Supplier Payment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/SupplierPaymentPreFinalizeBatch.cls
public with sharing class SupplierPaymentPreFinalizeBatch implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.Stateful {
	
	private String batchJobId;
	private String likeText;
    private List<Notify.Message> messages = new List<Notify.Message>();
    private Type executeClass = null;
    private final String EXECUTE_NAME = null;
    private boolean totalCreditsExceedsDebits = false;
    private String query = 'Select Id from Supplier_Payment__c '+
					   ' where Finalized__c = false ' +
					   ' and Batch_Job_Id__C = :batchJobId and Source_Key__c LIKE :likeText';

	private Integer currentSequence;
	
	public SupplierPaymentPreFinalizeBatch(String batchId,boolean totalCreditsExceedsDebits, Type runClass, Integer sequence) {
		this.batchJobId = batchId;
		this.likeText = '%'+batchJobId+'%';
		this.totalCreditsExceedsDebits  = totalCreditsExceedsDebits;
		currentSequence = sequence;
		executeClass = runClass;
	}
	
	public Database.QueryLocator start(Database.BatchableContext info) {

		if(executeClass == null){
			likeText = info.getJobId();
		}
		return Database.getQueryLocator(query);
	}

   	public void execute(Database.BatchableContext info, List<Supplier_Payment__c> scope) {
        system.debug (LoggingLevel.ERROR,'Pre Finalize SP Execute : ' + scope);
   		if(executeClass != null){
   			ICustomAction e = (ICustomAction)executeClass.newInstance();
   			List<Notify.Message> m = (List<Notify.Message>)e.executeAction(scope);

   			if(m != null && m.size() > 0){
   				messages.addAll(m);
   			}
   		}
	}
	
	public void finish(Database.BatchableContext info) {
		BatchToChatter.processBatchInformation(info.getJobId(), this, messages);
		Notify.sendEmailBatchFinish( null, messages, info);        

		BatchInjector bi = null;
		if(executeClass != null){
			bi = BatchInjector.getNextBatch(Schema.Supplier_Payment__c.getSObjectType().getDescribe().getName(), currentSequence);
		}

		Id batchId;
		if(bi != null && bi.executer != null){
			//run next batch
			system.debug('finish method of payment pre finalize batch, starting SupplierPaymentPreFinalizeBatch' + info.getJobId() + ' , nextBatch ='+bi);
        	batchId = Database.executeBatch(new SupplierPaymentPreFinalizeBatch(batchJobId,totalCreditsExceedsDebits, bi.executer, bi.sequence), bi.scope);
		}else{
			//NOW finalize  supplier invoices, and update amount paid field. 
			MasterControlProgram.finishedBatch( this );
            system.debug('finish method of payment pre finalize batch, starting SupplierPaymentFinalizeBatch' + info.getJobId() );
			batchId = Database.executeBatch(new SupplierPaymentFinalizeBatch(batchJobId,totalCreditsExceedsDebits),200);
		}
		
	}

}