src-ken&y/objects/Supplier_Invoice__c.object
<CustomObject>
    <customHelpPage>HelpSupplierInvoice</customHelpPage>
    <description>Record invoices for items or services  that are received from a supplier.  Bills can be recorded with or without purchase orders</description>
    <fields>
        <fullName>Supplier_Invoice__c</fullName>
        <description>Supplier invoice no. reference</description>
        <label>Invoice Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Supplier Invoice</label>
    <nameField>
        <label>Supplier Invoice</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/objects/Supplier_Payment__c.object
<CustomObject>
    <customHelpPage>HelpSupplierPayments</customHelpPage>
    <description>Pay supplier invoices</description>
    <label>Supplier Payment</label>
    <nameField>
        <label>Supplier Payment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src-ken&y/classes/SupplierPaymentGlobalService.cls
global with sharing class SupplierPaymentGlobalService {

    global static SupplierPaymentGlobalService getInstance(List<Supplier_Invoice__c> invoicesToPay) {
        return null;
    }

    private SupplierPaymentGlobalService(List<Supplier_Invoice__c> invoicesToPay) {

    }

    global void save() {

    }

    global boolean hasUncaughtException() {
        return false;
    }

    global boolean hasPermissionError() {
        return false;
    }

    global Supplier_Payment__c getPayment() {
        return null;
    }

    global String getSupplierPaymentKey(Supplier_Invoice__c invoice) {
        return null;
    }

    global Map<String, List<Supplier_Invoice__c>> getInvoicesBySupplier() {

        return null;
    }

    global Map<String, List<Supplier_Invoice__c>> getCreditMemosBySupplier() {

        return null;
    }

    global Map<String, List<Supplier_Invoice__c>> getInputInvoicesBySupplier() {

        return null;
    }

    global Map<String, List<Supplier_Invoice__c>> getInputCreditMemosBySupplier() {

        return null;
    }
}